// Copyright 2020 Authors of Hubble
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package tetragon;

import "tetragon/tetragon.proto";

message GetProcessModelRequest { }

message Workload {
	string name = 1;
	string kind = 2;
}

message DestinationStats {
	uint64 TxBytes = 1;
	uint64 RxBytes = 2;
	uint64 TxDrops = 3;
	uint64 TxLimit = 4;
}

message Destination {
	repeated string destination_names = 1;
	tetragon.Pod destination_pod = 2;
	uint64 Port = 3;
	DestinationStats stats = 4;
}

message ProcessModel {
	string binary = 1;
	string parent = 2;
	string namespace = 3;
	Workload workload = 4;
	repeated Destination dest = 5;
}

message GetProcessModelResponse {
        repeated ProcessModel processes = 1;
}

service ProcessModelService {
rpc GetProcessModel(GetProcessModelRequest) returns (GetProcessModelResponse) {}
}
