// This file is copied from OSS, DO NOT EDIT

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Hubble

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tetragon/stack.proto

package tetragon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StackAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       uint64                 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackAddress) Reset() {
	*x = StackAddress{}
	mi := &file_tetragon_stack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackAddress) ProtoMessage() {}

func (x *StackAddress) ProtoReflect() protoreflect.Message {
	mi := &file_tetragon_stack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackAddress.ProtoReflect.Descriptor instead.
func (*StackAddress) Descriptor() ([]byte, []int) {
	return file_tetragon_stack_proto_rawDescGZIP(), []int{0}
}

func (x *StackAddress) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *StackAddress) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type StackTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*StackAddress        `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackTrace) Reset() {
	*x = StackTrace{}
	mi := &file_tetragon_stack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackTrace) ProtoMessage() {}

func (x *StackTrace) ProtoReflect() protoreflect.Message {
	mi := &file_tetragon_stack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackTrace.ProtoReflect.Descriptor instead.
func (*StackTrace) Descriptor() ([]byte, []int) {
	return file_tetragon_stack_proto_rawDescGZIP(), []int{1}
}

func (x *StackTrace) GetAddresses() []*StackAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type StackTraceLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackTraceLabel) Reset() {
	*x = StackTraceLabel{}
	mi := &file_tetragon_stack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackTraceLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackTraceLabel) ProtoMessage() {}

func (x *StackTraceLabel) ProtoReflect() protoreflect.Message {
	mi := &file_tetragon_stack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackTraceLabel.ProtoReflect.Descriptor instead.
func (*StackTraceLabel) Descriptor() ([]byte, []int) {
	return file_tetragon_stack_proto_rawDescGZIP(), []int{2}
}

func (x *StackTraceLabel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StackTraceLabel) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StackTraceNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *StackAddress          `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Labels        []*StackTraceLabel     `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	Children      []*StackTraceNode      `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackTraceNode) Reset() {
	*x = StackTraceNode{}
	mi := &file_tetragon_stack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackTraceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackTraceNode) ProtoMessage() {}

func (x *StackTraceNode) ProtoReflect() protoreflect.Message {
	mi := &file_tetragon_stack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackTraceNode.ProtoReflect.Descriptor instead.
func (*StackTraceNode) Descriptor() ([]byte, []int) {
	return file_tetragon_stack_proto_rawDescGZIP(), []int{3}
}

func (x *StackTraceNode) GetAddress() *StackAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *StackTraceNode) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StackTraceNode) GetLabels() []*StackTraceLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *StackTraceNode) GetChildren() []*StackTraceNode {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_tetragon_stack_proto protoreflect.FileDescriptor

const file_tetragon_stack_proto_rawDesc = "" +
	"\n" +
	"\x14tetragon/stack.proto\x12\btetragon\"@\n" +
	"\fStackAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\x04R\aaddress\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"B\n" +
	"\n" +
	"StackTrace\x124\n" +
	"\taddresses\x18\x01 \x03(\v2\x16.tetragon.StackAddressR\taddresses\"9\n" +
	"\x0fStackTraceLabel\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"\xc1\x01\n" +
	"\x0eStackTraceNode\x120\n" +
	"\aaddress\x18\x01 \x01(\v2\x16.tetragon.StackAddressR\aaddress\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x121\n" +
	"\x06labels\x18\x03 \x03(\v2\x19.tetragon.StackTraceLabelR\x06labels\x124\n" +
	"\bchildren\x18\x04 \x03(\v2\x18.tetragon.StackTraceNodeR\bchildrenB,Z*github.com/cilium/tetragon/api/v1/tetragonb\x06proto3"

var (
	file_tetragon_stack_proto_rawDescOnce sync.Once
	file_tetragon_stack_proto_rawDescData []byte
)

func file_tetragon_stack_proto_rawDescGZIP() []byte {
	file_tetragon_stack_proto_rawDescOnce.Do(func() {
		file_tetragon_stack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tetragon_stack_proto_rawDesc), len(file_tetragon_stack_proto_rawDesc)))
	})
	return file_tetragon_stack_proto_rawDescData
}

var file_tetragon_stack_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tetragon_stack_proto_goTypes = []any{
	(*StackAddress)(nil),    // 0: tetragon.StackAddress
	(*StackTrace)(nil),      // 1: tetragon.StackTrace
	(*StackTraceLabel)(nil), // 2: tetragon.StackTraceLabel
	(*StackTraceNode)(nil),  // 3: tetragon.StackTraceNode
}
var file_tetragon_stack_proto_depIdxs = []int32{
	0, // 0: tetragon.StackTrace.addresses:type_name -> tetragon.StackAddress
	0, // 1: tetragon.StackTraceNode.address:type_name -> tetragon.StackAddress
	2, // 2: tetragon.StackTraceNode.labels:type_name -> tetragon.StackTraceLabel
	3, // 3: tetragon.StackTraceNode.children:type_name -> tetragon.StackTraceNode
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tetragon_stack_proto_init() }
func file_tetragon_stack_proto_init() {
	if File_tetragon_stack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tetragon_stack_proto_rawDesc), len(file_tetragon_stack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tetragon_stack_proto_goTypes,
		DependencyIndexes: file_tetragon_stack_proto_depIdxs,
		MessageInfos:      file_tetragon_stack_proto_msgTypes,
	}.Build()
	File_tetragon_stack_proto = out.File
	file_tetragon_stack_proto_goTypes = nil
	file_tetragon_stack_proto_depIdxs = nil
}
