apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "l3l4networking"
  labels:
    app.kubernetes.io/version: 1.16.0-rc.1
spec:
  parser:
    udp:
      enable: true
      cgroup: true
      statsInterval: 10
    tcp:
      enable: true
      statsInterval: 10
    dns:
      enable: true
