#!/usr/bin/env bash
# Copyright (C) Isovalent, Inc. - All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property of
# Isovalent Inc and its suppliers, if any. The intellectual and technical
# concepts contained herein are proprietary to Isovalent Inc and its suppliers
# and may be covered by U.S. and Foreign Patents, patents in process, and are
# protected by trade secret or copyright law.  Dissemination of this information
# or reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Isovalent Inc.

# Create crash reports directory
mkdir -p /opt/cisco/daf/var/s6/services/cpa/crash-reports

# Redirect stderr to stdout
exec 2>&1

echo "############################################################"
echo "#                                                          #"
printf "#                CPA Service Stopped                       #\n"
printf "#                    Exit Code: %-26s #\n" "$1"
printf "#                    Signal: %-29s #\n" "$2"
printf "#                    Process Group ID: %-19s #\n" "$4"
echo "#                                                          #"
echo "############################################################"

# Run cpa-finish with the same arguments
# exec /opt/cisco/daf/bin/cpa-finish "$@"
s6-ftrig-notify /opt/cisco/daf/var/s6/services/cpa/crash "C"
