#!/usr/bin/env bash
# Copyright (C) Isovalent, Inc. - All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property of
# Isovalent Inc and its suppliers, if any. The intellectual and technical
# concepts contained herein are proprietary to Isovalent Inc and its suppliers
# and may be covered by U.S. and Foreign Patents, patents in process, and are
# protected by trade secret or copyright law.  Dissemination of this information
# or reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Isovalent Inc.
set -eou pipefail

TEN_MB=10485760
ONE_MB=1048576

# Calculate remaining storage in Bytes
remaining_storage=$(df --output=avail / | tail -n 1 || echo 1)
remaining_storage=$((remaining_storage * 1024))
num_files=10
total_size=$((remaining_storage / 20)) # 5% of remaining storage
file_size=$((total_size / num_files))

# Ensure minimum file size is 1 MB
if (( file_size < ${ONE_MB} )); then
    file_size=${ONE_MB}
fi

# Ensure minimum total size is 10 MB or total remaining storage
# Recalculate number of files based on total size
if (( total_size < ${TEN_MB} )); then
    if (( remaining_storage < ${TEN_MB} )); then
        total_size=${remaining_storage}
        num_files=$((total_size / file_size))
        if (( num_files < 1 )); then
            num_files=1
        fi
    else
        total_size=${TEN_MB}
    fi
fi

# Running s6-log
s6-log -d 3 -b -p n${num_files} s${file_size} S${total_size} T /opt/cisco/daf/log/cpa
