apiVersion: cilium.io/v1alpha1
kind: AlertRule
metadata:
  name: aws-credentials
spec:
  expression: |
    (process_exec.process.binary.contains("grep") || process_exec.process.binary.contains("find")) &&
    (process_exec.process.arguments.contains("aws_access_key") ||
    process_exec.process.arguments.contains("aws_secret") ||
    process_exec.process.arguments.contains("aws_session") ||
    process_exec.process.arguments.contains("accesskeyid") ||
    process_exec.process.arguments.contains("secretaccesskey"))
  message: Detected AWS credentials search activity.
  tags: [aws, mitre_credential_access, T1552]
