# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # master branch
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
    - enhancement
    - release-blocker
    commit-message:
      prefix: "vendor:"

  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
    - enhancement
    - release-blocker
    commit-message:
      prefix: "images:"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
    - enhancement
    - release-blocker
    commit-message:
      prefix: "ci:"

  # v1.11 branch
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "v1.11"
    labels:
    - enhancement
    - release-blocker
    commit-message:
      prefix: "[v1.11] vendor:"

  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "v1.11"
    labels:
    - enhancement
    - release-blocker
    commit-message:
      prefix: "[v1.11] images:"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "v1.11"
    labels:
    - enhancement
    - release-blocker
    commit-message:
      prefix: "[v1.11] ci:"

  # v1.10 branch
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "v1.10"
    labels:
    - enhancement
    - release-blocker
    commit-message:
      prefix: "[v1.10] vendor:"

  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "v1.10"
    labels:
    - enhancement
    - release-blocker
    commit-message:
      prefix: "[v1.10] images:"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "v1.10"
    labels:
    - enhancement
    - release-blocker
    commit-message:
      prefix: "[v1.10] ci:"
