// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fgs/fgs.proto

package fgs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthStatusType int32

const (
	HealthStatusType_HEALTH_STATUS_TYPE_UNDEF  HealthStatusType = 0
	HealthStatusType_HEALTH_STATUS_TYPE_STATUS HealthStatusType = 1
)

var HealthStatusType_name = map[int32]string{
	0: "HEALTH_STATUS_TYPE_UNDEF",
	1: "HEALTH_STATUS_TYPE_STATUS",
}

var HealthStatusType_value = map[string]int32{
	"HEALTH_STATUS_TYPE_UNDEF":  0,
	"HEALTH_STATUS_TYPE_STATUS": 1,
}

func (x HealthStatusType) String() string {
	return proto.EnumName(HealthStatusType_name, int32(x))
}

func (HealthStatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{0}
}

type HealthStatusResult int32

const (
	HealthStatusResult_HEALTH_STATUS_UNDEF   HealthStatusResult = 0
	HealthStatusResult_HEALTH_STATUS_RUNNING HealthStatusResult = 1
	HealthStatusResult_HEALTH_STATUS_STOPPED HealthStatusResult = 2
	HealthStatusResult_HEALTH_STATUS_ERROR   HealthStatusResult = 3
)

var HealthStatusResult_name = map[int32]string{
	0: "HEALTH_STATUS_UNDEF",
	1: "HEALTH_STATUS_RUNNING",
	2: "HEALTH_STATUS_STOPPED",
	3: "HEALTH_STATUS_ERROR",
}

var HealthStatusResult_value = map[string]int32{
	"HEALTH_STATUS_UNDEF":   0,
	"HEALTH_STATUS_RUNNING": 1,
	"HEALTH_STATUS_STOPPED": 2,
	"HEALTH_STATUS_ERROR":   3,
}

func (x HealthStatusResult) String() string {
	return proto.EnumName(HealthStatusResult_name, int32(x))
}

func (HealthStatusResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{1}
}

// EventType constants are based on the ones from pkg/api/client
type EventType int32

const (
	EventType_UNDEF           EventType = 0
	EventType_PROCESS_CONNECT EventType = 1
	EventType_PROCESS_LISTEN  EventType = 4
	EventType_PROCESS_EXEC    EventType = 5
	EventType_PROCESS_TLS     EventType = 6
	EventType_PROCESS_EXIT    EventType = 7
	EventType_PROCESS_CLOSE   EventType = 8
	EventType_PROCESS_ACCEPT  EventType = 9
	EventType_PROCESS_CRED    EventType = 10
	EventType_TEST            EventType = 254
)

var EventType_name = map[int32]string{
	0:   "UNDEF",
	1:   "PROCESS_CONNECT",
	4:   "PROCESS_LISTEN",
	5:   "PROCESS_EXEC",
	6:   "PROCESS_TLS",
	7:   "PROCESS_EXIT",
	8:   "PROCESS_CLOSE",
	9:   "PROCESS_ACCEPT",
	10:  "PROCESS_CRED",
	254: "TEST",
}

var EventType_value = map[string]int32{
	"UNDEF":           0,
	"PROCESS_CONNECT": 1,
	"PROCESS_LISTEN":  4,
	"PROCESS_EXEC":    5,
	"PROCESS_TLS":     6,
	"PROCESS_EXIT":    7,
	"PROCESS_CLOSE":   8,
	"PROCESS_ACCEPT":  9,
	"PROCESS_CRED":    10,
	"TEST":            254,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{2}
}

type CapabilitiesType int32

const (
	// In a system with the [_POSIX_CHOWN_RESTRICTED] option defined, this
	//overrides the restriction of changing file ownership and group
	//ownership.
	CapabilitiesType_CAP_CHOWN    CapabilitiesType = 0
	CapabilitiesType_DAC_OVERRIDE CapabilitiesType = 1
	// Overrides all DAC restrictions regarding read and search on files
	//and directories, including ACL restrictions if [_POSIX_ACL] is
	//defined. Excluding DAC access covered by "$1"_LINUX_IMMUTABLE.
	CapabilitiesType_CAP_DAC_READ_SEARCH  CapabilitiesType = 2
	CapabilitiesType_CAP_FOWNER           CapabilitiesType = 3
	CapabilitiesType_CAP_FSETID           CapabilitiesType = 4
	CapabilitiesType_CAP_KILL             CapabilitiesType = 5
	CapabilitiesType_CAP_SETGID           CapabilitiesType = 6
	CapabilitiesType_CAP_SETUID           CapabilitiesType = 7
	CapabilitiesType_CAP_SETPCAP          CapabilitiesType = 8
	CapabilitiesType_CAP_LINUX_IMMUTABLE  CapabilitiesType = 9
	CapabilitiesType_CAP_NET_BIND_SERVICE CapabilitiesType = 10
	CapabilitiesType_CAP_NET_BROADCAST    CapabilitiesType = 11
	CapabilitiesType_CAP_NET_ADMIN        CapabilitiesType = 12
	CapabilitiesType_CAP_NET_RAW          CapabilitiesType = 13
	CapabilitiesType_CAP_IPC_LOCK         CapabilitiesType = 14
	CapabilitiesType_CAP_IPC_OWNER        CapabilitiesType = 15
	// Insert and remove kernel modules - modify kernel without limit
	CapabilitiesType_CAP_SYS_MODULE     CapabilitiesType = 16
	CapabilitiesType_CAP_SYS_RAWIO      CapabilitiesType = 17
	CapabilitiesType_CAP_SYS_CHROOT     CapabilitiesType = 18
	CapabilitiesType_CAP_SYS_PTRACE     CapabilitiesType = 19
	CapabilitiesType_CAP_SYS_PACCT      CapabilitiesType = 20
	CapabilitiesType_CAP_SYS_ADMIN      CapabilitiesType = 21
	CapabilitiesType_CAP_SYS_BOOT       CapabilitiesType = 22
	CapabilitiesType_CAP_SYS_NICE       CapabilitiesType = 23
	CapabilitiesType_CAP_SYS_RESOURCE   CapabilitiesType = 24
	CapabilitiesType_CAP_SYS_TIME       CapabilitiesType = 25
	CapabilitiesType_CAP_SYS_TTY_CONFIG CapabilitiesType = 26
	CapabilitiesType_CAP_MKNOD          CapabilitiesType = 27
	CapabilitiesType_CAP_LEASE          CapabilitiesType = 28
	CapabilitiesType_CAP_AUDIT_WRITE    CapabilitiesType = 29
	CapabilitiesType_CAP_AUDIT_CONTROL  CapabilitiesType = 30
	CapabilitiesType_CAP_SETFCAP        CapabilitiesType = 31
	CapabilitiesType_CAP_MAC_OVERRIDE   CapabilitiesType = 32
	CapabilitiesType_CAP_MAC_ADMIN      CapabilitiesType = 33
	CapabilitiesType_CAP_SYSLOG         CapabilitiesType = 34
	CapabilitiesType_CAP_WAKE_ALARM     CapabilitiesType = 35
	CapabilitiesType_CAP_BLOCK_SUSPEND  CapabilitiesType = 36
	CapabilitiesType_CAP_AUDIT_READ     CapabilitiesType = 37
	CapabilitiesType_CAP_PERFMON        CapabilitiesType = 38
	//
	// CAP_BPF allows the following BPF operations:
	// - Creating all types of BPF maps
	// - Advanced verifier features
	//   - Indirect variable access
	//   - Bounded loops
	//   - BPF to BPF function calls
	//   - Scalar precision tracking
	//   - Larger complexity limits
	//   - Dead code elimination
	//   - And potentially other features
	// - Loading BPF Type Format (BTF) data
	// - Retrieve xlated and JITed code of BPF programs
	// - Use bpf_spin_lock() helper
	//
	// CAP_PERFMON relaxes the verifier checks further:
	// - BPF progs can use of pointer-to-integer conversions
	// - speculation attack hardening measures are bypassed
	// - bpf_probe_read to read arbitrary kernel memory is allowed
	// - bpf_trace_printk to print kernel memory is allowed
	//
	// CAP_SYS_ADMIN is required to use bpf_probe_write_user.
	//
	// CAP_SYS_ADMIN is required to iterate system wide loaded
	// programs, maps, links, BTFs and convert their IDs to file descriptors.
	//
	// CAP_PERFMON and CAP_BPF are required to load tracing programs.
	// CAP_NET_ADMIN and CAP_BPF are required to load networking programs.
	CapabilitiesType_CAP_BPF                CapabilitiesType = 39
	CapabilitiesType_CAP_CHECKPOINT_RESTORE CapabilitiesType = 40
)

var CapabilitiesType_name = map[int32]string{
	0:  "CAP_CHOWN",
	1:  "DAC_OVERRIDE",
	2:  "CAP_DAC_READ_SEARCH",
	3:  "CAP_FOWNER",
	4:  "CAP_FSETID",
	5:  "CAP_KILL",
	6:  "CAP_SETGID",
	7:  "CAP_SETUID",
	8:  "CAP_SETPCAP",
	9:  "CAP_LINUX_IMMUTABLE",
	10: "CAP_NET_BIND_SERVICE",
	11: "CAP_NET_BROADCAST",
	12: "CAP_NET_ADMIN",
	13: "CAP_NET_RAW",
	14: "CAP_IPC_LOCK",
	15: "CAP_IPC_OWNER",
	16: "CAP_SYS_MODULE",
	17: "CAP_SYS_RAWIO",
	18: "CAP_SYS_CHROOT",
	19: "CAP_SYS_PTRACE",
	20: "CAP_SYS_PACCT",
	21: "CAP_SYS_ADMIN",
	22: "CAP_SYS_BOOT",
	23: "CAP_SYS_NICE",
	24: "CAP_SYS_RESOURCE",
	25: "CAP_SYS_TIME",
	26: "CAP_SYS_TTY_CONFIG",
	27: "CAP_MKNOD",
	28: "CAP_LEASE",
	29: "CAP_AUDIT_WRITE",
	30: "CAP_AUDIT_CONTROL",
	31: "CAP_SETFCAP",
	32: "CAP_MAC_OVERRIDE",
	33: "CAP_MAC_ADMIN",
	34: "CAP_SYSLOG",
	35: "CAP_WAKE_ALARM",
	36: "CAP_BLOCK_SUSPEND",
	37: "CAP_AUDIT_READ",
	38: "CAP_PERFMON",
	39: "CAP_BPF",
	40: "CAP_CHECKPOINT_RESTORE",
}

var CapabilitiesType_value = map[string]int32{
	"CAP_CHOWN":              0,
	"DAC_OVERRIDE":           1,
	"CAP_DAC_READ_SEARCH":    2,
	"CAP_FOWNER":             3,
	"CAP_FSETID":             4,
	"CAP_KILL":               5,
	"CAP_SETGID":             6,
	"CAP_SETUID":             7,
	"CAP_SETPCAP":            8,
	"CAP_LINUX_IMMUTABLE":    9,
	"CAP_NET_BIND_SERVICE":   10,
	"CAP_NET_BROADCAST":      11,
	"CAP_NET_ADMIN":          12,
	"CAP_NET_RAW":            13,
	"CAP_IPC_LOCK":           14,
	"CAP_IPC_OWNER":          15,
	"CAP_SYS_MODULE":         16,
	"CAP_SYS_RAWIO":          17,
	"CAP_SYS_CHROOT":         18,
	"CAP_SYS_PTRACE":         19,
	"CAP_SYS_PACCT":          20,
	"CAP_SYS_ADMIN":          21,
	"CAP_SYS_BOOT":           22,
	"CAP_SYS_NICE":           23,
	"CAP_SYS_RESOURCE":       24,
	"CAP_SYS_TIME":           25,
	"CAP_SYS_TTY_CONFIG":     26,
	"CAP_MKNOD":              27,
	"CAP_LEASE":              28,
	"CAP_AUDIT_WRITE":        29,
	"CAP_AUDIT_CONTROL":      30,
	"CAP_SETFCAP":            31,
	"CAP_MAC_OVERRIDE":       32,
	"CAP_MAC_ADMIN":          33,
	"CAP_SYSLOG":             34,
	"CAP_WAKE_ALARM":         35,
	"CAP_BLOCK_SUSPEND":      36,
	"CAP_AUDIT_READ":         37,
	"CAP_PERFMON":            38,
	"CAP_BPF":                39,
	"CAP_CHECKPOINT_RESTORE": 40,
}

func (x CapabilitiesType) String() string {
	return proto.EnumName(CapabilitiesType_name, int32(x))
}

func (CapabilitiesType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{3}
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Container struct {
	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image *Image `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// Start time of the container.
	StartTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// PID in the container namespace.
	Pid *wrappers.UInt32Value `protobuf:"bytes,5,opt,name=pid,proto3" json:"pid,omitempty"`
	// If this is set true, it means that the process might have been originated from
	// a Kubernetes exec probe. For this field to be true, the following must be true:
	//
	// 1. The binary field matches the first element of the exec command list for either
	//    liveness or readiness probe excluding the basename. For example, "/bin/ls"
	//    and "ls" are considered a match.
	// 2. The arguments field exactly matches the rest of the exec command list.
	MaybeExecProbe       bool     `protobuf:"varint,13,opt,name=maybe_exec_probe,json=maybeExecProbe,proto3" json:"maybe_exec_probe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Container) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Container) GetPid() *wrappers.UInt32Value {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *Container) GetMaybeExecProbe() bool {
	if m != nil {
		return m.MaybeExecProbe
	}
	return false
}

type Pod struct {
	Namespace            string     `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels               []string   `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	Container            *Container `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{2}
}

func (m *Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pod.Unmarshal(m, b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pod.Marshal(b, m, deterministic)
}
func (m *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(m, src)
}
func (m *Pod) XXX_Size() int {
	return xxx_messageInfo_Pod.Size(m)
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

func (m *Pod) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Pod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pod) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Pod) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type Capabilities struct {
	Permitted            []CapabilitiesType `protobuf:"varint,1,rep,packed,name=permitted,proto3,enum=fgs.CapabilitiesType" json:"permitted,omitempty"`
	Effective            []CapabilitiesType `protobuf:"varint,2,rep,packed,name=effective,proto3,enum=fgs.CapabilitiesType" json:"effective,omitempty"`
	Inheritable          []CapabilitiesType `protobuf:"varint,3,rep,packed,name=inheritable,proto3,enum=fgs.CapabilitiesType" json:"inheritable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Capabilities) Reset()         { *m = Capabilities{} }
func (m *Capabilities) String() string { return proto.CompactTextString(m) }
func (*Capabilities) ProtoMessage()    {}
func (*Capabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{3}
}

func (m *Capabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capabilities.Unmarshal(m, b)
}
func (m *Capabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capabilities.Marshal(b, m, deterministic)
}
func (m *Capabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capabilities.Merge(m, src)
}
func (m *Capabilities) XXX_Size() int {
	return xxx_messageInfo_Capabilities.Size(m)
}
func (m *Capabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_Capabilities.DiscardUnknown(m)
}

var xxx_messageInfo_Capabilities proto.InternalMessageInfo

func (m *Capabilities) GetPermitted() []CapabilitiesType {
	if m != nil {
		return m.Permitted
	}
	return nil
}

func (m *Capabilities) GetEffective() []CapabilitiesType {
	if m != nil {
		return m.Effective
	}
	return nil
}

func (m *Capabilities) GetInheritable() []CapabilitiesType {
	if m != nil {
		return m.Inheritable
	}
	return nil
}

type Process struct {
	// Exec ID uniquely identifies the process over time across all the nodes in the cluster.
	ExecId               string                `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Pid                  *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Uid                  *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Cwd                  string                `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Binary               string                `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"`
	Arguments            string                `protobuf:"bytes,6,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Flags                string                `protobuf:"bytes,7,opt,name=flags,proto3" json:"flags,omitempty"`
	StartTime            *timestamp.Timestamp  `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Auid                 *wrappers.UInt32Value `protobuf:"bytes,9,opt,name=auid,proto3" json:"auid,omitempty"`
	Pod                  *Pod                  `protobuf:"bytes,10,opt,name=pod,proto3" json:"pod,omitempty"`
	Docker               string                `protobuf:"bytes,11,opt,name=docker,proto3" json:"docker,omitempty"`
	ParentExecId         string                `protobuf:"bytes,12,opt,name=parent_exec_id,json=parentExecId,proto3" json:"parent_exec_id,omitempty"`
	Refcnt               uint32                `protobuf:"varint,13,opt,name=refcnt,proto3" json:"refcnt,omitempty"`
	Cap                  *Capabilities         `protobuf:"bytes,14,opt,name=cap,proto3" json:"cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{4}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetExecId() string {
	if m != nil {
		return m.ExecId
	}
	return ""
}

func (m *Process) GetPid() *wrappers.UInt32Value {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *Process) GetUid() *wrappers.UInt32Value {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *Process) GetCwd() string {
	if m != nil {
		return m.Cwd
	}
	return ""
}

func (m *Process) GetBinary() string {
	if m != nil {
		return m.Binary
	}
	return ""
}

func (m *Process) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *Process) GetFlags() string {
	if m != nil {
		return m.Flags
	}
	return ""
}

func (m *Process) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Process) GetAuid() *wrappers.UInt32Value {
	if m != nil {
		return m.Auid
	}
	return nil
}

func (m *Process) GetPod() *Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (m *Process) GetDocker() string {
	if m != nil {
		return m.Docker
	}
	return ""
}

func (m *Process) GetParentExecId() string {
	if m != nil {
		return m.ParentExecId
	}
	return ""
}

func (m *Process) GetRefcnt() uint32 {
	if m != nil {
		return m.Refcnt
	}
	return 0
}

func (m *Process) GetCap() *Capabilities {
	if m != nil {
		return m.Cap
	}
	return nil
}

type ProcessConnect struct {
	Process              *Process              `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Parent               *Process              `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	SourceIp             string                `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort           *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationIp        string                `protobuf:"bytes,5,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort      *wrappers.UInt32Value `protobuf:"bytes,6,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	DestinationNames     []string              `protobuf:"bytes,7,rep,name=destination_names,json=destinationNames,proto3" json:"destination_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProcessConnect) Reset()         { *m = ProcessConnect{} }
func (m *ProcessConnect) String() string { return proto.CompactTextString(m) }
func (*ProcessConnect) ProtoMessage()    {}
func (*ProcessConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{5}
}

func (m *ProcessConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessConnect.Unmarshal(m, b)
}
func (m *ProcessConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessConnect.Marshal(b, m, deterministic)
}
func (m *ProcessConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessConnect.Merge(m, src)
}
func (m *ProcessConnect) XXX_Size() int {
	return xxx_messageInfo_ProcessConnect.Size(m)
}
func (m *ProcessConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessConnect.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessConnect proto.InternalMessageInfo

func (m *ProcessConnect) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ProcessConnect) GetParent() *Process {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ProcessConnect) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *ProcessConnect) GetSourcePort() *wrappers.UInt32Value {
	if m != nil {
		return m.SourcePort
	}
	return nil
}

func (m *ProcessConnect) GetDestinationIp() string {
	if m != nil {
		return m.DestinationIp
	}
	return ""
}

func (m *ProcessConnect) GetDestinationPort() *wrappers.UInt32Value {
	if m != nil {
		return m.DestinationPort
	}
	return nil
}

func (m *ProcessConnect) GetDestinationNames() []string {
	if m != nil {
		return m.DestinationNames
	}
	return nil
}

type ProcessClose struct {
	Process              *Process              `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Parent               *Process              `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	SourceIp             string                `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort           *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationIp        string                `protobuf:"bytes,5,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort      *wrappers.UInt32Value `protobuf:"bytes,6,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	DestinationNames     []string              `protobuf:"bytes,7,rep,name=destination_names,json=destinationNames,proto3" json:"destination_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProcessClose) Reset()         { *m = ProcessClose{} }
func (m *ProcessClose) String() string { return proto.CompactTextString(m) }
func (*ProcessClose) ProtoMessage()    {}
func (*ProcessClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{6}
}

func (m *ProcessClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessClose.Unmarshal(m, b)
}
func (m *ProcessClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessClose.Marshal(b, m, deterministic)
}
func (m *ProcessClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessClose.Merge(m, src)
}
func (m *ProcessClose) XXX_Size() int {
	return xxx_messageInfo_ProcessClose.Size(m)
}
func (m *ProcessClose) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessClose.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessClose proto.InternalMessageInfo

func (m *ProcessClose) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ProcessClose) GetParent() *Process {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ProcessClose) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *ProcessClose) GetSourcePort() *wrappers.UInt32Value {
	if m != nil {
		return m.SourcePort
	}
	return nil
}

func (m *ProcessClose) GetDestinationIp() string {
	if m != nil {
		return m.DestinationIp
	}
	return ""
}

func (m *ProcessClose) GetDestinationPort() *wrappers.UInt32Value {
	if m != nil {
		return m.DestinationPort
	}
	return nil
}

func (m *ProcessClose) GetDestinationNames() []string {
	if m != nil {
		return m.DestinationNames
	}
	return nil
}

type ProcessListen struct {
	Process              *Process              `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Parent               *Process              `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Ip                   string                `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProcessListen) Reset()         { *m = ProcessListen{} }
func (m *ProcessListen) String() string { return proto.CompactTextString(m) }
func (*ProcessListen) ProtoMessage()    {}
func (*ProcessListen) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{7}
}

func (m *ProcessListen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessListen.Unmarshal(m, b)
}
func (m *ProcessListen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessListen.Marshal(b, m, deterministic)
}
func (m *ProcessListen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessListen.Merge(m, src)
}
func (m *ProcessListen) XXX_Size() int {
	return xxx_messageInfo_ProcessListen.Size(m)
}
func (m *ProcessListen) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessListen.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessListen proto.InternalMessageInfo

func (m *ProcessListen) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ProcessListen) GetParent() *Process {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ProcessListen) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ProcessListen) GetPort() *wrappers.UInt32Value {
	if m != nil {
		return m.Port
	}
	return nil
}

type ProcessAccept struct {
	Process              *Process              `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Parent               *Process              `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	SourceIp             string                `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort           *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationIp        string                `protobuf:"bytes,5,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort      *wrappers.UInt32Value `protobuf:"bytes,6,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	DestinationNames     []string              `protobuf:"bytes,7,rep,name=destination_names,json=destinationNames,proto3" json:"destination_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProcessAccept) Reset()         { *m = ProcessAccept{} }
func (m *ProcessAccept) String() string { return proto.CompactTextString(m) }
func (*ProcessAccept) ProtoMessage()    {}
func (*ProcessAccept) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{8}
}

func (m *ProcessAccept) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessAccept.Unmarshal(m, b)
}
func (m *ProcessAccept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessAccept.Marshal(b, m, deterministic)
}
func (m *ProcessAccept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessAccept.Merge(m, src)
}
func (m *ProcessAccept) XXX_Size() int {
	return xxx_messageInfo_ProcessAccept.Size(m)
}
func (m *ProcessAccept) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessAccept.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessAccept proto.InternalMessageInfo

func (m *ProcessAccept) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ProcessAccept) GetParent() *Process {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ProcessAccept) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *ProcessAccept) GetSourcePort() *wrappers.UInt32Value {
	if m != nil {
		return m.SourcePort
	}
	return nil
}

func (m *ProcessAccept) GetDestinationIp() string {
	if m != nil {
		return m.DestinationIp
	}
	return ""
}

func (m *ProcessAccept) GetDestinationPort() *wrappers.UInt32Value {
	if m != nil {
		return m.DestinationPort
	}
	return nil
}

func (m *ProcessAccept) GetDestinationNames() []string {
	if m != nil {
		return m.DestinationNames
	}
	return nil
}

type ProcessExec struct {
	Process *Process `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Parent  *Process `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	// Ancestors of the process beyond the immediate parent.
	Ancestors            []*Process `protobuf:"bytes,3,rep,name=ancestors,proto3" json:"ancestors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProcessExec) Reset()         { *m = ProcessExec{} }
func (m *ProcessExec) String() string { return proto.CompactTextString(m) }
func (*ProcessExec) ProtoMessage()    {}
func (*ProcessExec) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{9}
}

func (m *ProcessExec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessExec.Unmarshal(m, b)
}
func (m *ProcessExec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessExec.Marshal(b, m, deterministic)
}
func (m *ProcessExec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessExec.Merge(m, src)
}
func (m *ProcessExec) XXX_Size() int {
	return xxx_messageInfo_ProcessExec.Size(m)
}
func (m *ProcessExec) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessExec.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessExec proto.InternalMessageInfo

func (m *ProcessExec) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ProcessExec) GetParent() *Process {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ProcessExec) GetAncestors() []*Process {
	if m != nil {
		return m.Ancestors
	}
	return nil
}

type ProcessExit struct {
	Process              *Process `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Parent               *Process `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessExit) Reset()         { *m = ProcessExit{} }
func (m *ProcessExit) String() string { return proto.CompactTextString(m) }
func (*ProcessExit) ProtoMessage()    {}
func (*ProcessExit) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{10}
}

func (m *ProcessExit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessExit.Unmarshal(m, b)
}
func (m *ProcessExit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessExit.Marshal(b, m, deterministic)
}
func (m *ProcessExit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessExit.Merge(m, src)
}
func (m *ProcessExit) XXX_Size() int {
	return xxx_messageInfo_ProcessExit.Size(m)
}
func (m *ProcessExit) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessExit.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessExit proto.InternalMessageInfo

func (m *ProcessExit) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ProcessExit) GetParent() *Process {
	if m != nil {
		return m.Parent
	}
	return nil
}

type ProcessCred struct {
	Process              *Process      `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Parent               *Process      `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Cap                  *Capabilities `protobuf:"bytes,3,opt,name=cap,proto3" json:"cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProcessCred) Reset()         { *m = ProcessCred{} }
func (m *ProcessCred) String() string { return proto.CompactTextString(m) }
func (*ProcessCred) ProtoMessage()    {}
func (*ProcessCred) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{11}
}

func (m *ProcessCred) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessCred.Unmarshal(m, b)
}
func (m *ProcessCred) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessCred.Marshal(b, m, deterministic)
}
func (m *ProcessCred) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessCred.Merge(m, src)
}
func (m *ProcessCred) XXX_Size() int {
	return xxx_messageInfo_ProcessCred.Size(m)
}
func (m *ProcessCred) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessCred.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessCred proto.InternalMessageInfo

func (m *ProcessCred) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ProcessCred) GetParent() *Process {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ProcessCred) GetCap() *Capabilities {
	if m != nil {
		return m.Cap
	}
	return nil
}

type Test struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{12}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

type Tls struct {
	Process              *Process              `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	SourceIp             string                `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort           *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationIp        string                `protobuf:"bytes,4,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort      *wrappers.UInt32Value `protobuf:"bytes,5,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	NegotiatedVersion    string                `protobuf:"bytes,6,opt,name=negotiated_version,json=negotiatedVersion,proto3" json:"negotiated_version,omitempty"`
	SupportedVersions    string                `protobuf:"bytes,7,opt,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`
	SniType              string                `protobuf:"bytes,8,opt,name=sni_type,json=sniType,proto3" json:"sni_type,omitempty"`
	SniName              string                `protobuf:"bytes,9,opt,name=sni_name,json=sniName,proto3" json:"sni_name,omitempty"`
	Cipher               string                `protobuf:"bytes,10,opt,name=cipher,proto3" json:"cipher,omitempty"`
	ClientFlags          string                `protobuf:"bytes,11,opt,name=client_flags,json=clientFlags,proto3" json:"client_flags,omitempty"`
	ServerFlags          string                `protobuf:"bytes,12,opt,name=server_flags,json=serverFlags,proto3" json:"server_flags,omitempty"`
	ClientVersion        string                `protobuf:"bytes,13,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ServerVersion        string                `protobuf:"bytes,14,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ClientAlert          string                `protobuf:"bytes,15,opt,name=client_alert,json=clientAlert,proto3" json:"client_alert,omitempty"`
	ServerAlert          string                `protobuf:"bytes,16,opt,name=server_alert,json=serverAlert,proto3" json:"server_alert,omitempty"`
	ClientSession        string                `protobuf:"bytes,17,opt,name=client_session,json=clientSession,proto3" json:"client_session,omitempty"`
	ServerSession        string                `protobuf:"bytes,18,opt,name=server_session,json=serverSession,proto3" json:"server_session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Tls) Reset()         { *m = Tls{} }
func (m *Tls) String() string { return proto.CompactTextString(m) }
func (*Tls) ProtoMessage()    {}
func (*Tls) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{13}
}

func (m *Tls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tls.Unmarshal(m, b)
}
func (m *Tls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tls.Marshal(b, m, deterministic)
}
func (m *Tls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tls.Merge(m, src)
}
func (m *Tls) XXX_Size() int {
	return xxx_messageInfo_Tls.Size(m)
}
func (m *Tls) XXX_DiscardUnknown() {
	xxx_messageInfo_Tls.DiscardUnknown(m)
}

var xxx_messageInfo_Tls proto.InternalMessageInfo

func (m *Tls) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *Tls) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *Tls) GetSourcePort() *wrappers.UInt32Value {
	if m != nil {
		return m.SourcePort
	}
	return nil
}

func (m *Tls) GetDestinationIp() string {
	if m != nil {
		return m.DestinationIp
	}
	return ""
}

func (m *Tls) GetDestinationPort() *wrappers.UInt32Value {
	if m != nil {
		return m.DestinationPort
	}
	return nil
}

func (m *Tls) GetNegotiatedVersion() string {
	if m != nil {
		return m.NegotiatedVersion
	}
	return ""
}

func (m *Tls) GetSupportedVersions() string {
	if m != nil {
		return m.SupportedVersions
	}
	return ""
}

func (m *Tls) GetSniType() string {
	if m != nil {
		return m.SniType
	}
	return ""
}

func (m *Tls) GetSniName() string {
	if m != nil {
		return m.SniName
	}
	return ""
}

func (m *Tls) GetCipher() string {
	if m != nil {
		return m.Cipher
	}
	return ""
}

func (m *Tls) GetClientFlags() string {
	if m != nil {
		return m.ClientFlags
	}
	return ""
}

func (m *Tls) GetServerFlags() string {
	if m != nil {
		return m.ServerFlags
	}
	return ""
}

func (m *Tls) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *Tls) GetServerVersion() string {
	if m != nil {
		return m.ServerVersion
	}
	return ""
}

func (m *Tls) GetClientAlert() string {
	if m != nil {
		return m.ClientAlert
	}
	return ""
}

func (m *Tls) GetServerAlert() string {
	if m != nil {
		return m.ServerAlert
	}
	return ""
}

func (m *Tls) GetClientSession() string {
	if m != nil {
		return m.ClientSession
	}
	return ""
}

func (m *Tls) GetServerSession() string {
	if m != nil {
		return m.ServerSession
	}
	return ""
}

type ListSensorsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSensorsRequest) Reset()         { *m = ListSensorsRequest{} }
func (m *ListSensorsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSensorsRequest) ProtoMessage()    {}
func (*ListSensorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{14}
}

func (m *ListSensorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSensorsRequest.Unmarshal(m, b)
}
func (m *ListSensorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSensorsRequest.Marshal(b, m, deterministic)
}
func (m *ListSensorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSensorsRequest.Merge(m, src)
}
func (m *ListSensorsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSensorsRequest.Size(m)
}
func (m *ListSensorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSensorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSensorsRequest proto.InternalMessageInfo

type SensorStatus struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SensorStatus) Reset()         { *m = SensorStatus{} }
func (m *SensorStatus) String() string { return proto.CompactTextString(m) }
func (*SensorStatus) ProtoMessage()    {}
func (*SensorStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{15}
}

func (m *SensorStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorStatus.Unmarshal(m, b)
}
func (m *SensorStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorStatus.Marshal(b, m, deterministic)
}
func (m *SensorStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorStatus.Merge(m, src)
}
func (m *SensorStatus) XXX_Size() int {
	return xxx_messageInfo_SensorStatus.Size(m)
}
func (m *SensorStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SensorStatus proto.InternalMessageInfo

func (m *SensorStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SensorStatus) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type ListSensorsResponse struct {
	Sensors              []*SensorStatus `protobuf:"bytes,1,rep,name=sensors,proto3" json:"sensors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListSensorsResponse) Reset()         { *m = ListSensorsResponse{} }
func (m *ListSensorsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSensorsResponse) ProtoMessage()    {}
func (*ListSensorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{16}
}

func (m *ListSensorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSensorsResponse.Unmarshal(m, b)
}
func (m *ListSensorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSensorsResponse.Marshal(b, m, deterministic)
}
func (m *ListSensorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSensorsResponse.Merge(m, src)
}
func (m *ListSensorsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSensorsResponse.Size(m)
}
func (m *ListSensorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSensorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSensorsResponse proto.InternalMessageInfo

func (m *ListSensorsResponse) GetSensors() []*SensorStatus {
	if m != nil {
		return m.Sensors
	}
	return nil
}

type EnableSensorRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableSensorRequest) Reset()         { *m = EnableSensorRequest{} }
func (m *EnableSensorRequest) String() string { return proto.CompactTextString(m) }
func (*EnableSensorRequest) ProtoMessage()    {}
func (*EnableSensorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{17}
}

func (m *EnableSensorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableSensorRequest.Unmarshal(m, b)
}
func (m *EnableSensorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableSensorRequest.Marshal(b, m, deterministic)
}
func (m *EnableSensorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableSensorRequest.Merge(m, src)
}
func (m *EnableSensorRequest) XXX_Size() int {
	return xxx_messageInfo_EnableSensorRequest.Size(m)
}
func (m *EnableSensorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableSensorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableSensorRequest proto.InternalMessageInfo

func (m *EnableSensorRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EnableSensorResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableSensorResponse) Reset()         { *m = EnableSensorResponse{} }
func (m *EnableSensorResponse) String() string { return proto.CompactTextString(m) }
func (*EnableSensorResponse) ProtoMessage()    {}
func (*EnableSensorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{18}
}

func (m *EnableSensorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableSensorResponse.Unmarshal(m, b)
}
func (m *EnableSensorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableSensorResponse.Marshal(b, m, deterministic)
}
func (m *EnableSensorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableSensorResponse.Merge(m, src)
}
func (m *EnableSensorResponse) XXX_Size() int {
	return xxx_messageInfo_EnableSensorResponse.Size(m)
}
func (m *EnableSensorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableSensorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableSensorResponse proto.InternalMessageInfo

func (m *EnableSensorResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DisableSensorRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableSensorRequest) Reset()         { *m = DisableSensorRequest{} }
func (m *DisableSensorRequest) String() string { return proto.CompactTextString(m) }
func (*DisableSensorRequest) ProtoMessage()    {}
func (*DisableSensorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{19}
}

func (m *DisableSensorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableSensorRequest.Unmarshal(m, b)
}
func (m *DisableSensorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableSensorRequest.Marshal(b, m, deterministic)
}
func (m *DisableSensorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableSensorRequest.Merge(m, src)
}
func (m *DisableSensorRequest) XXX_Size() int {
	return xxx_messageInfo_DisableSensorRequest.Size(m)
}
func (m *DisableSensorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableSensorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableSensorRequest proto.InternalMessageInfo

func (m *DisableSensorRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DisableSensorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableSensorResponse) Reset()         { *m = DisableSensorResponse{} }
func (m *DisableSensorResponse) String() string { return proto.CompactTextString(m) }
func (*DisableSensorResponse) ProtoMessage()    {}
func (*DisableSensorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{20}
}

func (m *DisableSensorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableSensorResponse.Unmarshal(m, b)
}
func (m *DisableSensorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableSensorResponse.Marshal(b, m, deterministic)
}
func (m *DisableSensorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableSensorResponse.Merge(m, src)
}
func (m *DisableSensorResponse) XXX_Size() int {
	return xxx_messageInfo_DisableSensorResponse.Size(m)
}
func (m *DisableSensorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableSensorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisableSensorResponse proto.InternalMessageInfo

type GetHealthStatusRequest struct {
	EventSet             []HealthStatusType `protobuf:"varint,1,rep,packed,name=event_set,json=eventSet,proto3,enum=fgs.HealthStatusType" json:"event_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetHealthStatusRequest) Reset()         { *m = GetHealthStatusRequest{} }
func (m *GetHealthStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetHealthStatusRequest) ProtoMessage()    {}
func (*GetHealthStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{21}
}

func (m *GetHealthStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthStatusRequest.Unmarshal(m, b)
}
func (m *GetHealthStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetHealthStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthStatusRequest.Merge(m, src)
}
func (m *GetHealthStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetHealthStatusRequest.Size(m)
}
func (m *GetHealthStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthStatusRequest proto.InternalMessageInfo

func (m *GetHealthStatusRequest) GetEventSet() []HealthStatusType {
	if m != nil {
		return m.EventSet
	}
	return nil
}

type HealthStatus struct {
	Event                HealthStatusType   `protobuf:"varint,1,opt,name=event,proto3,enum=fgs.HealthStatusType" json:"event,omitempty"`
	Status               HealthStatusResult `protobuf:"varint,2,opt,name=status,proto3,enum=fgs.HealthStatusResult" json:"status,omitempty"`
	Details              string             `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *HealthStatus) Reset()         { *m = HealthStatus{} }
func (m *HealthStatus) String() string { return proto.CompactTextString(m) }
func (*HealthStatus) ProtoMessage()    {}
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{22}
}

func (m *HealthStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthStatus.Unmarshal(m, b)
}
func (m *HealthStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthStatus.Marshal(b, m, deterministic)
}
func (m *HealthStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthStatus.Merge(m, src)
}
func (m *HealthStatus) XXX_Size() int {
	return xxx_messageInfo_HealthStatus.Size(m)
}
func (m *HealthStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthStatus.DiscardUnknown(m)
}

var xxx_messageInfo_HealthStatus proto.InternalMessageInfo

func (m *HealthStatus) GetEvent() HealthStatusType {
	if m != nil {
		return m.Event
	}
	return HealthStatusType_HEALTH_STATUS_TYPE_UNDEF
}

func (m *HealthStatus) GetStatus() HealthStatusResult {
	if m != nil {
		return m.Status
	}
	return HealthStatusResult_HEALTH_STATUS_UNDEF
}

func (m *HealthStatus) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type GetHealthStatusResponse struct {
	HealthStatus         []*HealthStatus `protobuf:"bytes,1,rep,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetHealthStatusResponse) Reset()         { *m = GetHealthStatusResponse{} }
func (m *GetHealthStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetHealthStatusResponse) ProtoMessage()    {}
func (*GetHealthStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{23}
}

func (m *GetHealthStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthStatusResponse.Unmarshal(m, b)
}
func (m *GetHealthStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetHealthStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthStatusResponse.Merge(m, src)
}
func (m *GetHealthStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetHealthStatusResponse.Size(m)
}
func (m *GetHealthStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthStatusResponse proto.InternalMessageInfo

func (m *GetHealthStatusResponse) GetHealthStatus() []*HealthStatus {
	if m != nil {
		return m.HealthStatus
	}
	return nil
}

type GetEventsRequest struct {
	// allow_list specifies a list of filters to apply to only return certain
	// events. If multiple filters are specified, at least one of them has to
	// match for an event to be included in the results.
	AllowList []*Filter `protobuf:"bytes,1,rep,name=allow_list,json=allowList,proto3" json:"allow_list,omitempty"`
	// deny_list specifies a list of filters to apply to exclude certain events
	// from the results. If multiple filters are specified, at least one of
	// them has to match for an event to be excluded.
	//
	// If both allow_list and deny_list are specified, the results contain the
	// set difference allow_list - deny_list.
	DenyList             []*Filter `protobuf:"bytes,2,rep,name=deny_list,json=denyList,proto3" json:"deny_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{24}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

func (m *GetEventsRequest) GetAllowList() []*Filter {
	if m != nil {
		return m.AllowList
	}
	return nil
}

func (m *GetEventsRequest) GetDenyList() []*Filter {
	if m != nil {
		return m.DenyList
	}
	return nil
}

type GetEventsResponse struct {
	// Types that are valid to be assigned to Event:
	//	*GetEventsResponse_ProcessExec
	//	*GetEventsResponse_ProcessConnect
	//	*GetEventsResponse_ProcessListen
	//	*GetEventsResponse_Tls
	//	*GetEventsResponse_ProcessExit
	//	*GetEventsResponse_ProcessClose
	//	*GetEventsResponse_ProcessAccept
	//	*GetEventsResponse_ProcessCred
	//	*GetEventsResponse_Test
	Event isGetEventsResponse_Event `protobuf_oneof:"event"`
	// Name of the node where this event was observed.
	NodeName string `protobuf:"bytes,1000,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Timestamp at which this event was observed.
	Time                 *timestamp.Timestamp `protobuf:"bytes,1001,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{25}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

type isGetEventsResponse_Event interface {
	isGetEventsResponse_Event()
}

type GetEventsResponse_ProcessExec struct {
	ProcessExec *ProcessExec `protobuf:"bytes,1,opt,name=process_exec,json=processExec,proto3,oneof"`
}

type GetEventsResponse_ProcessConnect struct {
	ProcessConnect *ProcessConnect `protobuf:"bytes,2,opt,name=process_connect,json=processConnect,proto3,oneof"`
}

type GetEventsResponse_ProcessListen struct {
	ProcessListen *ProcessListen `protobuf:"bytes,3,opt,name=process_listen,json=processListen,proto3,oneof"`
}

type GetEventsResponse_Tls struct {
	Tls *Tls `protobuf:"bytes,4,opt,name=tls,proto3,oneof"`
}

type GetEventsResponse_ProcessExit struct {
	ProcessExit *ProcessExit `protobuf:"bytes,5,opt,name=process_exit,json=processExit,proto3,oneof"`
}

type GetEventsResponse_ProcessClose struct {
	ProcessClose *ProcessClose `protobuf:"bytes,6,opt,name=process_close,json=processClose,proto3,oneof"`
}

type GetEventsResponse_ProcessAccept struct {
	ProcessAccept *ProcessAccept `protobuf:"bytes,7,opt,name=process_accept,json=processAccept,proto3,oneof"`
}

type GetEventsResponse_ProcessCred struct {
	ProcessCred *ProcessCred `protobuf:"bytes,8,opt,name=process_cred,json=processCred,proto3,oneof"`
}

type GetEventsResponse_Test struct {
	Test *Test `protobuf:"bytes,40000,opt,name=test,proto3,oneof"`
}

func (*GetEventsResponse_ProcessExec) isGetEventsResponse_Event() {}

func (*GetEventsResponse_ProcessConnect) isGetEventsResponse_Event() {}

func (*GetEventsResponse_ProcessListen) isGetEventsResponse_Event() {}

func (*GetEventsResponse_Tls) isGetEventsResponse_Event() {}

func (*GetEventsResponse_ProcessExit) isGetEventsResponse_Event() {}

func (*GetEventsResponse_ProcessClose) isGetEventsResponse_Event() {}

func (*GetEventsResponse_ProcessAccept) isGetEventsResponse_Event() {}

func (*GetEventsResponse_ProcessCred) isGetEventsResponse_Event() {}

func (*GetEventsResponse_Test) isGetEventsResponse_Event() {}

func (m *GetEventsResponse) GetEvent() isGetEventsResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *GetEventsResponse) GetProcessExec() *ProcessExec {
	if x, ok := m.GetEvent().(*GetEventsResponse_ProcessExec); ok {
		return x.ProcessExec
	}
	return nil
}

func (m *GetEventsResponse) GetProcessConnect() *ProcessConnect {
	if x, ok := m.GetEvent().(*GetEventsResponse_ProcessConnect); ok {
		return x.ProcessConnect
	}
	return nil
}

func (m *GetEventsResponse) GetProcessListen() *ProcessListen {
	if x, ok := m.GetEvent().(*GetEventsResponse_ProcessListen); ok {
		return x.ProcessListen
	}
	return nil
}

func (m *GetEventsResponse) GetTls() *Tls {
	if x, ok := m.GetEvent().(*GetEventsResponse_Tls); ok {
		return x.Tls
	}
	return nil
}

func (m *GetEventsResponse) GetProcessExit() *ProcessExit {
	if x, ok := m.GetEvent().(*GetEventsResponse_ProcessExit); ok {
		return x.ProcessExit
	}
	return nil
}

func (m *GetEventsResponse) GetProcessClose() *ProcessClose {
	if x, ok := m.GetEvent().(*GetEventsResponse_ProcessClose); ok {
		return x.ProcessClose
	}
	return nil
}

func (m *GetEventsResponse) GetProcessAccept() *ProcessAccept {
	if x, ok := m.GetEvent().(*GetEventsResponse_ProcessAccept); ok {
		return x.ProcessAccept
	}
	return nil
}

func (m *GetEventsResponse) GetProcessCred() *ProcessCred {
	if x, ok := m.GetEvent().(*GetEventsResponse_ProcessCred); ok {
		return x.ProcessCred
	}
	return nil
}

func (m *GetEventsResponse) GetTest() *Test {
	if x, ok := m.GetEvent().(*GetEventsResponse_Test); ok {
		return x.Test
	}
	return nil
}

func (m *GetEventsResponse) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *GetEventsResponse) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetEventsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetEventsResponse_ProcessExec)(nil),
		(*GetEventsResponse_ProcessConnect)(nil),
		(*GetEventsResponse_ProcessListen)(nil),
		(*GetEventsResponse_Tls)(nil),
		(*GetEventsResponse_ProcessExit)(nil),
		(*GetEventsResponse_ProcessClose)(nil),
		(*GetEventsResponse_ProcessAccept)(nil),
		(*GetEventsResponse_ProcessCred)(nil),
		(*GetEventsResponse_Test)(nil),
	}
}

type Filter struct {
	BinaryRegex          []string            `protobuf:"bytes,1,rep,name=binary_regex,json=binaryRegex,proto3" json:"binary_regex,omitempty"`
	Namespace            []string            `protobuf:"bytes,2,rep,name=namespace,proto3" json:"namespace,omitempty"`
	HealthCheck          *wrappers.BoolValue `protobuf:"bytes,3,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Pid                  []uint32            `protobuf:"varint,4,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	PidSet               []uint32            `protobuf:"varint,5,rep,packed,name=pid_set,json=pidSet,proto3" json:"pid_set,omitempty"`
	EventSet             []EventType         `protobuf:"varint,6,rep,packed,name=event_set,json=eventSet,proto3,enum=fgs.EventType" json:"event_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{26}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetBinaryRegex() []string {
	if m != nil {
		return m.BinaryRegex
	}
	return nil
}

func (m *Filter) GetNamespace() []string {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Filter) GetHealthCheck() *wrappers.BoolValue {
	if m != nil {
		return m.HealthCheck
	}
	return nil
}

func (m *Filter) GetPid() []uint32 {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *Filter) GetPidSet() []uint32 {
	if m != nil {
		return m.PidSet
	}
	return nil
}

func (m *Filter) GetEventSet() []EventType {
	if m != nil {
		return m.EventSet
	}
	return nil
}

func init() {
	proto.RegisterEnum("fgs.HealthStatusType", HealthStatusType_name, HealthStatusType_value)
	proto.RegisterEnum("fgs.HealthStatusResult", HealthStatusResult_name, HealthStatusResult_value)
	proto.RegisterEnum("fgs.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("fgs.CapabilitiesType", CapabilitiesType_name, CapabilitiesType_value)
	proto.RegisterType((*Image)(nil), "fgs.Image")
	proto.RegisterType((*Container)(nil), "fgs.Container")
	proto.RegisterType((*Pod)(nil), "fgs.Pod")
	proto.RegisterType((*Capabilities)(nil), "fgs.Capabilities")
	proto.RegisterType((*Process)(nil), "fgs.Process")
	proto.RegisterType((*ProcessConnect)(nil), "fgs.ProcessConnect")
	proto.RegisterType((*ProcessClose)(nil), "fgs.ProcessClose")
	proto.RegisterType((*ProcessListen)(nil), "fgs.ProcessListen")
	proto.RegisterType((*ProcessAccept)(nil), "fgs.ProcessAccept")
	proto.RegisterType((*ProcessExec)(nil), "fgs.ProcessExec")
	proto.RegisterType((*ProcessExit)(nil), "fgs.ProcessExit")
	proto.RegisterType((*ProcessCred)(nil), "fgs.ProcessCred")
	proto.RegisterType((*Test)(nil), "fgs.Test")
	proto.RegisterType((*Tls)(nil), "fgs.Tls")
	proto.RegisterType((*ListSensorsRequest)(nil), "fgs.ListSensorsRequest")
	proto.RegisterType((*SensorStatus)(nil), "fgs.SensorStatus")
	proto.RegisterType((*ListSensorsResponse)(nil), "fgs.ListSensorsResponse")
	proto.RegisterType((*EnableSensorRequest)(nil), "fgs.EnableSensorRequest")
	proto.RegisterType((*EnableSensorResponse)(nil), "fgs.EnableSensorResponse")
	proto.RegisterType((*DisableSensorRequest)(nil), "fgs.DisableSensorRequest")
	proto.RegisterType((*DisableSensorResponse)(nil), "fgs.DisableSensorResponse")
	proto.RegisterType((*GetHealthStatusRequest)(nil), "fgs.GetHealthStatusRequest")
	proto.RegisterType((*HealthStatus)(nil), "fgs.HealthStatus")
	proto.RegisterType((*GetHealthStatusResponse)(nil), "fgs.GetHealthStatusResponse")
	proto.RegisterType((*GetEventsRequest)(nil), "fgs.GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "fgs.GetEventsResponse")
	proto.RegisterType((*Filter)(nil), "fgs.Filter")
}

func init() { proto.RegisterFile("fgs/fgs.proto", fileDescriptor_507a05c52639eb54) }

var fileDescriptor_507a05c52639eb54 = []byte{
	// 2307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4b, 0x73, 0xe3, 0x58,
	0xf5, 0x8f, 0xed, 0xc4, 0xb6, 0x8e, 0x1f, 0xb9, 0xb9, 0x49, 0x27, 0x6e, 0x77, 0x66, 0x26, 0xed,
	0xe9, 0xee, 0x7f, 0xfe, 0x69, 0x48, 0x4f, 0xa5, 0x8b, 0x57, 0xc1, 0x4c, 0x95, 0x23, 0x2b, 0xb1,
	0xaa, 0x1d, 0xcb, 0x5c, 0x29, 0x9d, 0xe9, 0x62, 0xa1, 0x52, 0xec, 0x9b, 0x44, 0x35, 0x8e, 0x24,
	0x24, 0xa5, 0x1f, 0x55, 0x50, 0xc5, 0x0a, 0x3e, 0x06, 0x1b, 0xbe, 0x00, 0xbb, 0x59, 0xb2, 0x61,
	0xc9, 0x12, 0xd8, 0xb2, 0xa0, 0x28, 0xd8, 0xb3, 0xa6, 0xa8, 0xfb, 0x72, 0x64, 0x3b, 0xd3, 0x13,
	0x20, 0xcb, 0xd9, 0xf9, 0xfe, 0xce, 0xef, 0x9c, 0x7b, 0x5e, 0xba, 0xf7, 0x5c, 0x43, 0xed, 0xec,
	0x3c, 0x79, 0x76, 0x76, 0x9e, 0xec, 0x46, 0x71, 0x98, 0x86, 0xb8, 0x70, 0x76, 0x9e, 0x34, 0x3f,
	0x3a, 0x0f, 0xc3, 0xf3, 0x31, 0x7d, 0xc6, 0xa1, 0xd3, 0xab, 0xb3, 0x67, 0xa9, 0x7f, 0x49, 0x93,
	0xd4, 0xbb, 0x8c, 0x04, 0xab, 0xf9, 0xe1, 0x2c, 0xe1, 0x4d, 0xec, 0x45, 0x11, 0x8d, 0xa5, 0x95,
	0xd6, 0x53, 0x58, 0x32, 0x2f, 0xbd, 0x73, 0x8a, 0xeb, 0x90, 0xf7, 0x47, 0x8d, 0xdc, 0x56, 0x6e,
	0x5b, 0x23, 0x79, 0x7f, 0x84, 0x31, 0x2c, 0x06, 0xde, 0x25, 0x6d, 0xe4, 0x39, 0xc2, 0x7f, 0xb7,
	0xfe, 0x96, 0x03, 0x4d, 0x0f, 0x83, 0xd4, 0xf3, 0x03, 0x1a, 0xdf, 0x46, 0x03, 0x6f, 0xc1, 0x92,
	0xcf, 0xcc, 0x37, 0x0a, 0x5b, 0xb9, 0xed, 0xca, 0x1e, 0xec, 0x32, 0xff, 0xf9, 0x86, 0x44, 0x08,
	0xf0, 0x0f, 0x00, 0x92, 0xd4, 0x8b, 0x53, 0x97, 0x79, 0xde, 0x58, 0xe4, 0xb4, 0xe6, 0xae, 0xf0,
	0x7a, 0x57, 0x79, 0xbd, 0xeb, 0xa8, 0xb0, 0x88, 0xc6, 0xd9, 0x6c, 0x8d, 0x77, 0xa1, 0x10, 0xf9,
	0xa3, 0xc6, 0x12, 0xd7, 0xd9, 0x9c, 0xd3, 0x39, 0x36, 0x83, 0xf4, 0xf9, 0xde, 0x4b, 0x6f, 0x7c,
	0x45, 0x09, 0x23, 0xe2, 0x6d, 0x40, 0x97, 0xde, 0xbb, 0x53, 0xea, 0xd2, 0xb7, 0x74, 0xe8, 0x46,
	0x71, 0x78, 0x4a, 0x1b, 0xb5, 0xad, 0xdc, 0x76, 0x99, 0xd4, 0x39, 0x6e, 0xbc, 0xa5, 0xc3, 0x01,
	0x43, 0x5b, 0x3f, 0x87, 0xc2, 0x20, 0x1c, 0xe1, 0x4d, 0xd0, 0x58, 0x14, 0x49, 0xe4, 0x0d, 0xa9,
	0x0c, 0xf4, 0x1a, 0xb8, 0x31, 0xde, 0x75, 0x28, 0x8e, 0xbd, 0x53, 0x3a, 0x4e, 0x1a, 0x85, 0xad,
	0xc2, 0xb6, 0x46, 0xe4, 0x0a, 0x7f, 0x0b, 0xb4, 0xa1, 0x4a, 0x9c, 0x0c, 0xb2, 0xce, 0x73, 0x31,
	0x49, 0x27, 0xb9, 0x26, 0xb4, 0x7e, 0x9b, 0x83, 0xaa, 0xee, 0x45, 0xde, 0xa9, 0x3f, 0xf6, 0x53,
	0x9f, 0x26, 0xf8, 0x39, 0x68, 0x11, 0x8d, 0x2f, 0xfd, 0x34, 0xa5, 0x2c, 0xe3, 0x85, 0xed, 0xfa,
	0xde, 0x3d, 0xa1, 0x9e, 0x61, 0x39, 0xef, 0x22, 0x4a, 0xae, 0x79, 0x4c, 0x89, 0x9e, 0x9d, 0xd1,
	0x61, 0xea, 0xbf, 0x66, 0x4e, 0xbe, 0x4f, 0x69, 0xc2, 0xc3, 0xdf, 0x83, 0x8a, 0x1f, 0x5c, 0xd0,
	0xd8, 0x4f, 0xbd, 0xd3, 0x31, 0xe5, 0x51, 0x7c, 0xa5, 0x5a, 0x96, 0xd9, 0xfa, 0x6b, 0x01, 0x4a,
	0x83, 0x38, 0x1c, 0xd2, 0x24, 0xc1, 0x1b, 0x50, 0xe2, 0x29, 0x9e, 0xb4, 0x47, 0x91, 0x2d, 0xcd,
	0x91, 0xaa, 0x58, 0xfe, 0xb6, 0x15, 0xdb, 0x85, 0xc2, 0x95, 0x3f, 0x92, 0xcd, 0xf3, 0x35, 0xfc,
	0x2b, 0x7f, 0x84, 0x11, 0x14, 0x86, 0x6f, 0x46, 0x3c, 0xc1, 0x1a, 0x61, 0x3f, 0x59, 0x41, 0x4e,
	0xfd, 0xc0, 0x8b, 0xdf, 0xf1, 0x36, 0xd1, 0x88, 0x5c, 0xb1, 0xd2, 0x7a, 0xf1, 0xf9, 0xd5, 0x25,
	0x0d, 0xd2, 0xa4, 0x51, 0x14, 0xa5, 0x9d, 0x00, 0x78, 0x0d, 0x96, 0xce, 0xc6, 0xde, 0x79, 0xd2,
	0x28, 0x71, 0x89, 0x58, 0xcc, 0xb4, 0x6a, 0xf9, 0x3f, 0x69, 0xd5, 0x4f, 0x60, 0xd1, 0x63, 0x91,
	0x68, 0xb7, 0x88, 0x84, 0x33, 0x71, 0x13, 0x0a, 0x51, 0x38, 0x6a, 0x00, 0x57, 0x28, 0xf3, 0x02,
	0x0c, 0xc2, 0x11, 0x61, 0x20, 0x0b, 0x6a, 0x14, 0x0e, 0xbf, 0xa0, 0x71, 0xa3, 0x22, 0x82, 0x12,
	0x2b, 0xfc, 0x08, 0xea, 0x91, 0x17, 0xd3, 0x20, 0x75, 0x55, 0xfa, 0xab, 0x5c, 0x5e, 0x15, 0xa8,
	0x21, 0x8a, 0xb0, 0x0e, 0xc5, 0x98, 0x9e, 0x0d, 0x83, 0x94, 0x37, 0x7f, 0x8d, 0xc8, 0x15, 0xfe,
	0x18, 0x0a, 0x43, 0x2f, 0x6a, 0xd4, 0xf9, 0x8e, 0x2b, 0x73, 0x25, 0x27, 0x4c, 0xda, 0xfa, 0x73,
	0x1e, 0xea, 0xb2, 0xcc, 0x7a, 0x18, 0x04, 0x74, 0x98, 0xe2, 0x27, 0x50, 0x8a, 0x04, 0xc2, 0xab,
	0x5d, 0xd9, 0xab, 0x0a, 0x6f, 0x05, 0x46, 0x94, 0x10, 0x3f, 0x82, 0xa2, 0xf0, 0x43, 0xd6, 0x7f,
	0x9a, 0x26, 0x65, 0xf8, 0x01, 0x68, 0x49, 0x78, 0x15, 0x0f, 0xa9, 0xeb, 0x47, 0xbc, 0xf0, 0x1a,
	0x29, 0x0b, 0xc0, 0x8c, 0xf0, 0xa7, 0x50, 0x91, 0xc2, 0x28, 0x8c, 0x53, 0xf9, 0x21, 0xbd, 0x3f,
	0x9b, 0x20, 0x14, 0x06, 0x61, 0x9c, 0xe2, 0xc7, 0x50, 0x1f, 0xd1, 0x24, 0xf5, 0x03, 0x2f, 0xf5,
	0xc3, 0x80, 0x6d, 0x20, 0x9a, 0xa2, 0x96, 0x41, 0xcd, 0x08, 0x1f, 0x02, 0xca, 0xd2, 0xf8, 0x56,
	0xc5, 0x5b, 0x6c, 0xb5, 0x9c, 0xd1, 0xe2, 0xfb, 0x3d, 0x85, 0x95, 0xac, 0x21, 0x7e, 0x74, 0x34,
	0x4a, 0xfc, 0x60, 0xc8, 0xee, 0xd0, 0x67, 0x78, 0xeb, 0x8f, 0x79, 0xa8, 0xaa, 0xcc, 0x8e, 0xc3,
	0x84, 0x7e, 0x93, 0xd7, 0xbb, 0xc9, 0xeb, 0xaf, 0x73, 0x50, 0x93, 0xc9, 0xe8, 0xf9, 0x49, 0x4a,
	0x83, 0x3b, 0x4e, 0x2c, 0xbb, 0x06, 0x55, 0x46, 0xf3, 0x7e, 0xc4, 0x3e, 0xf5, 0x5b, 0x27, 0x91,
	0x33, 0x5b, 0x7f, 0xca, 0x4f, 0x3c, 0x6c, 0x0f, 0x87, 0x34, 0xfa, 0xe6, 0x93, 0xba, 0xa3, 0xd2,
	0xff, 0x2a, 0x07, 0x15, 0x99, 0x0c, 0x76, 0xf6, 0xdd, 0x71, 0x5a, 0x77, 0x40, 0xf3, 0x82, 0x21,
	0x4d, 0xd2, 0x30, 0x16, 0xd7, 0xfd, 0x2c, 0xf1, 0x5a, 0xdc, 0xfa, 0x49, 0xc6, 0x11, 0xff, 0x8e,
	0xeb, 0xdb, 0xfa, 0xc5, 0x75, 0x98, 0x7a, 0x4c, 0x47, 0x77, 0x1c, 0xa6, 0xbc, 0x16, 0x0a, 0xef,
	0xbd, 0x16, 0x8a, 0xb0, 0xe8, 0xd0, 0x24, 0x6d, 0xfd, 0x61, 0x09, 0x0a, 0xce, 0x38, 0xb9, 0xb5,
	0x0b, 0x53, 0xad, 0x99, 0x7f, 0x7f, 0x6b, 0x16, 0xfe, 0xe7, 0xd6, 0x5c, 0xbc, 0x6d, 0x6b, 0x2e,
	0xfd, 0x37, 0xad, 0xf9, 0x6d, 0xc0, 0x01, 0x3d, 0x0f, 0x53, 0xdf, 0x4b, 0xe9, 0xc8, 0x7d, 0x4d,
	0xe3, 0xc4, 0x0f, 0x03, 0x39, 0x5b, 0xac, 0x5c, 0x4b, 0x5e, 0x0a, 0x01, 0xa3, 0x27, 0x57, 0x11,
	0xdb, 0xee, 0x9a, 0xad, 0x06, 0x8e, 0x95, 0x89, 0x44, 0xb2, 0x13, 0x7c, 0x1f, 0xca, 0x49, 0xe0,
	0xbb, 0xe9, 0xbb, 0x48, 0x8c, 0x1e, 0x1a, 0x29, 0x25, 0x81, 0xcf, 0xe6, 0x30, 0x25, 0xe2, 0xc3,
	0xa8, 0x36, 0x11, 0xf5, 0xe5, 0x3c, 0x3a, 0xf4, 0xa3, 0x0b, 0x1a, 0xf3, 0x41, 0x42, 0x23, 0x72,
	0x85, 0x1f, 0x42, 0x75, 0x38, 0xf6, 0xd9, 0xa4, 0x20, 0xe6, 0x1c, 0x31, 0x47, 0x54, 0x04, 0x76,
	0xc0, 0xa7, 0x9d, 0x87, 0x50, 0x4d, 0x68, 0xfc, 0x9a, 0xc6, 0x92, 0x22, 0x46, 0x89, 0x8a, 0xc0,
	0x04, 0xe5, 0x31, 0xd4, 0xa5, 0x15, 0x15, 0x6d, 0x4d, 0x64, 0x58, 0xa0, 0x2a, 0xd2, 0xc7, 0x50,
	0x97, 0x96, 0x14, 0xad, 0x2e, 0x68, 0x02, 0x55, 0xb4, 0x6b, 0x9f, 0xbc, 0x31, 0x8d, 0xd3, 0xc6,
	0x72, 0xd6, 0xa7, 0x36, 0x83, 0x32, 0x3e, 0x09, 0x0a, 0xca, 0xfa, 0x24, 0x28, 0xd7, 0x3e, 0x25,
	0x34, 0xe1, 0x9b, 0xad, 0x64, 0x7d, 0xb2, 0x05, 0x98, 0xf1, 0x49, 0xd1, 0x70, 0xd6, 0x27, 0x49,
	0x6b, 0xad, 0x01, 0x66, 0x97, 0x86, 0x4d, 0x83, 0x24, 0x8c, 0x13, 0x42, 0x7f, 0x7a, 0xc5, 0xba,
	0xfc, 0x47, 0x50, 0x15, 0x88, 0x9d, 0x7a, 0xe9, 0x55, 0x32, 0x79, 0x09, 0xe4, 0x32, 0x2f, 0x81,
	0x06, 0x94, 0x68, 0xc0, 0x26, 0x63, 0x31, 0xee, 0x96, 0x89, 0x5a, 0xb6, 0xf6, 0x61, 0x75, 0xca,
	0x66, 0x12, 0x85, 0x41, 0x42, 0xf1, 0x53, 0x28, 0x25, 0x02, 0xe2, 0x13, 0xbe, 0xfa, 0xd6, 0xb2,
	0x1b, 0x11, 0xc5, 0x68, 0xfd, 0x3f, 0xac, 0x1a, 0xdc, 0x9c, 0x10, 0x4b, 0xc7, 0x6e, 0x72, 0xa4,
	0xf5, 0x04, 0xd6, 0xa6, 0xa9, 0x72, 0xbf, 0x99, 0xe7, 0x1b, 0xe3, 0x75, 0xfc, 0x64, 0xde, 0xe6,
	0x2c, 0x6f, 0x03, 0xee, 0xcd, 0xf0, 0x84, 0xc1, 0x56, 0x0f, 0xd6, 0x0f, 0x69, 0xda, 0xa5, 0xde,
	0x38, 0xbd, 0x90, 0xfe, 0x4a, 0x13, 0x7b, 0xa0, 0xd1, 0xd7, 0xa2, 0x24, 0xe9, 0xd4, 0xf3, 0x25,
	0x4b, 0xe6, 0x4f, 0x8a, 0x32, 0xe7, 0xd9, 0x34, 0x6d, 0xfd, 0x32, 0x07, 0xd5, 0xac, 0x18, 0x3f,
	0x85, 0x25, 0x2e, 0xe4, 0xae, 0x7c, 0xa5, 0x01, 0xc1, 0xc1, 0xcf, 0xa0, 0x98, 0x70, 0x90, 0x27,
	0xbf, 0xbe, 0xb7, 0x31, 0xc7, 0x26, 0x34, 0xb9, 0x1a, 0xa7, 0x44, 0xd2, 0x58, 0xb9, 0x46, 0x34,
	0xf5, 0x7c, 0xfe, 0x72, 0xe3, 0x9f, 0x90, 0x5c, 0xb6, 0x7e, 0x0c, 0x1b, 0x73, 0x61, 0xc9, 0x14,
	0x7e, 0x17, 0x6a, 0x17, 0x1c, 0x77, 0xe5, 0x66, 0xd9, 0xc2, 0x4d, 0x69, 0x54, 0x2f, 0x32, 0xab,
	0xd6, 0x05, 0xa0, 0x43, 0x9a, 0x1a, 0xcc, 0xd3, 0x49, 0x8e, 0x76, 0x00, 0xbc, 0xf1, 0x38, 0x7c,
	0xe3, 0x8e, 0xfd, 0x24, 0x95, 0x86, 0x2a, 0xdc, 0xd0, 0x81, 0x3f, 0x4e, 0xd9, 0xfb, 0x90, 0x8b,
	0x59, 0xe7, 0xe0, 0x6d, 0xd0, 0x46, 0x34, 0x78, 0x27, 0xa8, 0xf9, 0x79, 0x6a, 0x99, 0x49, 0x19,
	0xb3, 0xf5, 0xfb, 0x45, 0x58, 0xc9, 0x6c, 0x25, 0xfd, 0xfe, 0x0e, 0x54, 0xe5, 0x01, 0xcc, 0x1f,
	0x0a, 0xf2, 0x88, 0x46, 0xd9, 0x23, 0x9a, 0xdd, 0x97, 0xdd, 0x05, 0x52, 0x89, 0x32, 0xd7, 0xe7,
	0x67, 0xb0, 0xac, 0xd4, 0x86, 0x62, 0xf6, 0x97, 0x17, 0xc7, 0x6a, 0x56, 0x53, 0x3e, 0x0b, 0xba,
	0x0b, 0xa4, 0x1e, 0x4d, 0x3f, 0x14, 0x7e, 0x08, 0x0a, 0xe1, 0x9e, 0xd3, 0x40, 0x1e, 0xe9, 0x38,
	0xab, 0x2e, 0x66, 0xb4, 0xee, 0x02, 0xa9, 0x45, 0x53, 0x43, 0xdb, 0x26, 0x14, 0xd2, 0x71, 0x22,
	0xe7, 0x13, 0xf1, 0x1e, 0x72, 0xc6, 0x49, 0x77, 0x81, 0x30, 0x78, 0x3a, 0x22, 0x5f, 0x1d, 0xe0,
	0x33, 0x11, 0xf9, 0xe9, 0x54, 0x44, 0x7e, 0x8a, 0xbf, 0x0f, 0xb5, 0x49, 0x44, 0x6c, 0xe6, 0x96,
	0x33, 0xc9, 0xca, 0x54, 0x3c, 0x4c, 0xd0, 0x5d, 0x20, 0x6a, 0x03, 0x31, 0x9c, 0x67, 0x62, 0xf1,
	0xf8, 0xcc, 0xc6, 0x4f, 0xee, 0x99, 0x58, 0xc4, 0x34, 0x97, 0x89, 0x45, 0x8e, 0x77, 0x19, 0x6f,
	0x87, 0x31, 0x1d, 0xc9, 0xa7, 0xe4, 0x94, 0xb7, 0xec, 0x22, 0xcf, 0x78, 0xcb, 0xef, 0xf5, 0x87,
	0xb0, 0x98, 0xd2, 0x24, 0x6d, 0xfc, 0xee, 0x4b, 0x91, 0x76, 0x4d, 0x64, 0x81, 0x26, 0x6c, 0x0b,
	0x2e, 0xe2, 0xff, 0x58, 0x84, 0x23, 0x2a, 0xee, 0x82, 0xbf, 0x8b, 0xcb, 0xa4, 0xcc, 0x10, 0x7e,
	0x1b, 0x3c, 0x83, 0x45, 0xfe, 0x74, 0xfd, 0x47, 0xe9, 0x6b, 0xdf, 0xae, 0x9c, 0xb8, 0x5f, 0x92,
	0xdf, 0x5c, 0xeb, 0x2f, 0x39, 0x28, 0x8a, 0xe6, 0x62, 0x67, 0xb0, 0x78, 0x43, 0xbb, 0x31, 0x3d,
	0xa7, 0x6f, 0x79, 0xab, 0x6a, 0xa4, 0x22, 0x30, 0xc2, 0xa0, 0xe9, 0xff, 0x4d, 0xf2, 0x5c, 0x9e,
	0xf9, 0xdf, 0xe4, 0x53, 0x90, 0x5f, 0x83, 0x3b, 0xbc, 0xa0, 0xc3, 0x2f, 0x64, 0x13, 0xcc, 0x3b,
	0xb3, 0x1f, 0x86, 0x63, 0x71, 0xd5, 0x56, 0x04, 0x5f, 0x67, 0x74, 0xf6, 0xc6, 0x8f, 0x7c, 0xf6,
	0xc6, 0x2f, 0x6c, 0xd7, 0xc4, 0xbf, 0x04, 0x1b, 0x50, 0x8a, 0xfc, 0x11, 0x3f, 0x5c, 0x96, 0x38,
	0x5a, 0x8c, 0xfc, 0x91, 0x4d, 0xd9, 0xb0, 0x98, 0x39, 0x77, 0x8a, 0xfc, 0xdc, 0x11, 0xff, 0xba,
	0xf0, 0xef, 0x61, 0xfa, 0xc0, 0xd9, 0xb1, 0x00, 0xcd, 0x9e, 0x26, 0x78, 0x13, 0x1a, 0x5d, 0xa3,
	0xdd, 0x73, 0xba, 0xae, 0xed, 0xb4, 0x9d, 0x63, 0xdb, 0x75, 0x5e, 0x0d, 0x0c, 0xf7, 0xb8, 0xdf,
	0x31, 0x0e, 0xd0, 0x02, 0xfe, 0x00, 0xee, 0xdf, 0x20, 0x15, 0xbf, 0x51, 0x6e, 0xe7, 0x67, 0x80,
	0xe7, 0x0f, 0x1c, 0xbc, 0x01, 0xab, 0xd3, 0x4a, 0xca, 0xda, 0x7d, 0xb8, 0x37, 0x2d, 0x20, 0xc7,
	0xfd, 0xbe, 0xd9, 0x3f, 0x44, 0xb9, 0x79, 0x91, 0xed, 0x58, 0x83, 0x81, 0xd1, 0x41, 0xf9, 0x79,
	0x73, 0x06, 0x21, 0x16, 0x41, 0x85, 0x9d, 0x2f, 0x73, 0xa0, 0x4d, 0xc2, 0xc4, 0x1a, 0x2c, 0xa9,
	0x7d, 0x56, 0x61, 0x79, 0x40, 0x2c, 0xdd, 0xb0, 0x6d, 0x57, 0xb7, 0xfa, 0x7d, 0x43, 0x77, 0x50,
	0x0e, 0x63, 0xa8, 0x2b, 0xb0, 0x67, 0xda, 0x8e, 0xd1, 0x47, 0x8b, 0x18, 0x41, 0x55, 0x61, 0xc6,
	0xe7, 0x86, 0x8e, 0x96, 0xf0, 0x32, 0x54, 0x14, 0xe2, 0xf4, 0x6c, 0x54, 0x9c, 0xa6, 0x98, 0x0e,
	0x2a, 0xe1, 0x15, 0xa8, 0x4d, 0xac, 0xf7, 0x2c, 0xdb, 0x40, 0xe5, 0xac, 0xed, 0xb6, 0xae, 0x1b,
	0x03, 0x07, 0x69, 0x59, 0x45, 0x9d, 0x18, 0x1d, 0x04, 0x58, 0x83, 0x45, 0xc7, 0xb0, 0x1d, 0xf4,
	0xaf, 0xdc, 0xce, 0x6f, 0x8a, 0x80, 0x66, 0xff, 0x6c, 0xc2, 0x35, 0xd0, 0xf4, 0xf6, 0xc0, 0xd5,
	0xbb, 0xd6, 0x49, 0x1f, 0x2d, 0x30, 0x03, 0x9d, 0xb6, 0xee, 0x5a, 0x2f, 0x0d, 0x42, 0xcc, 0x8e,
	0x81, 0x72, 0x2c, 0x13, 0x8c, 0xc0, 0x50, 0x62, 0xb4, 0x3b, 0xae, 0x6d, 0xb4, 0x89, 0xde, 0x45,
	0x79, 0x5c, 0x07, 0x60, 0x82, 0x03, 0xeb, 0xa4, 0x6f, 0x10, 0x54, 0x98, 0xac, 0x6d, 0xc3, 0x31,
	0x3b, 0x68, 0x11, 0x57, 0xa1, 0xcc, 0xd6, 0x2f, 0xcc, 0x5e, 0x0f, 0x2d, 0x29, 0xa9, 0x6d, 0x38,
	0x87, 0x66, 0x07, 0x15, 0x33, 0xeb, 0x63, 0xb3, 0x83, 0x4a, 0x2c, 0x07, 0x72, 0x3d, 0xd0, 0xdb,
	0x03, 0x54, 0x56, 0xfb, 0xf6, 0xcc, 0xfe, 0xf1, 0xe7, 0xae, 0x79, 0x74, 0x74, 0xec, 0xb4, 0xf7,
	0x7b, 0x06, 0xd2, 0x70, 0x03, 0xd6, 0x98, 0xa0, 0x6f, 0x38, 0xee, 0xbe, 0xd9, 0x67, 0x0e, 0x91,
	0x97, 0xa6, 0x6e, 0x20, 0xc0, 0xf7, 0x60, 0x65, 0x22, 0x21, 0x56, 0xbb, 0xa3, 0xb7, 0x6d, 0x07,
	0x55, 0x58, 0xee, 0x14, 0xdc, 0xee, 0x1c, 0x99, 0x7d, 0x54, 0x55, 0xbb, 0x31, 0x88, 0xb4, 0x4f,
	0x50, 0x8d, 0xc5, 0xcd, 0x00, 0x73, 0xa0, 0xbb, 0x3d, 0x4b, 0x7f, 0x81, 0xea, 0x4a, 0x8b, 0x21,
	0x22, 0xc2, 0x65, 0x96, 0x71, 0xee, 0xe3, 0x2b, 0xdb, 0x3d, 0xb2, 0x3a, 0xc7, 0x3d, 0x03, 0x21,
	0x45, 0x63, 0x18, 0x69, 0x9f, 0x98, 0x16, 0x5a, 0xc9, 0xd2, 0xf4, 0x2e, 0xb1, 0x2c, 0x07, 0xe1,
	0x2c, 0x36, 0x70, 0x48, 0x5b, 0x37, 0xd0, 0x6a, 0x56, 0x75, 0xd0, 0xd6, 0x75, 0x07, 0xad, 0x65,
	0x21, 0xe1, 0xea, 0x3d, 0xe5, 0x19, 0x83, 0xf6, 0x99, 0xad, 0xf5, 0x2c, 0xd2, 0x67, 0x81, 0x6f,
	0xe0, 0x35, 0x40, 0x13, 0x27, 0x0c, 0xdb, 0x3a, 0x26, 0xba, 0x81, 0x1a, 0x59, 0x9e, 0x63, 0x1e,
	0x19, 0xe8, 0x3e, 0x5e, 0x07, 0x3c, 0x41, 0x9c, 0x57, 0xac, 0x4f, 0x0f, 0xcc, 0x43, 0xd4, 0x54,
	0x4d, 0x70, 0xf4, 0xa2, 0x6f, 0x75, 0xd0, 0x03, 0xb5, 0xec, 0x19, 0x6d, 0xdb, 0x40, 0x9b, 0xac,
	0xb3, 0xd9, 0xb2, 0x7d, 0xdc, 0x31, 0x1d, 0xf7, 0x84, 0x98, 0x8e, 0x81, 0x3e, 0x50, 0xb9, 0x16,
	0xa0, 0x6e, 0xf5, 0x1d, 0x62, 0xf5, 0xd0, 0x87, 0x99, 0x32, 0x1e, 0xb0, 0x32, 0x7e, 0xa4, 0x5c,
	0x3b, 0xca, 0x36, 0xd5, 0x96, 0x8a, 0x93, 0xa1, 0x22, 0xce, 0x87, 0x93, 0x86, 0x78, 0x65, 0xf7,
	0xac, 0x43, 0xd4, 0x52, 0x19, 0x3b, 0x69, 0xbf, 0x30, 0xdc, 0x76, 0xaf, 0x4d, 0x8e, 0xd0, 0xc7,
	0x6a, 0xd3, 0x7d, 0x56, 0x22, 0xd7, 0x3e, 0xb6, 0x07, 0x46, 0xbf, 0x83, 0x1e, 0x29, 0xaa, 0xf0,
	0x85, 0x35, 0x29, 0x7a, 0xac, 0x1c, 0x19, 0x18, 0xe4, 0xe0, 0xc8, 0xea, 0xa3, 0x27, 0xb8, 0x02,
	0x25, 0xae, 0x3b, 0x38, 0x40, 0xff, 0x87, 0x9b, 0xb0, 0x2e, 0xba, 0xde, 0xd0, 0x5f, 0x0c, 0x2c,
	0xb3, 0xcf, 0xd4, 0x6c, 0xc7, 0x22, 0x06, 0xda, 0xde, 0xfb, 0x67, 0x1e, 0x56, 0x0f, 0xfc, 0x80,
	0x1e, 0x5e, 0xf9, 0x23, 0xf6, 0xd2, 0x94, 0x03, 0x25, 0xfe, 0x0c, 0xb4, 0xc9, 0x95, 0x8f, 0xc5,
	0x98, 0x34, 0x3b, 0x6d, 0x34, 0xd7, 0x67, 0x61, 0x39, 0xc3, 0x2d, 0x7c, 0x92, 0xc3, 0x5d, 0xae,
	0x2f, 0x8e, 0x2e, 0xfc, 0x40, 0x11, 0x6f, 0x98, 0xeb, 0x9a, 0x9b, 0x37, 0x0b, 0x95, 0x2d, 0xbc,
	0x0f, 0x95, 0xcc, 0xa4, 0x8b, 0xc5, 0x10, 0x36, 0x3f, 0x4f, 0x37, 0x1b, 0xf3, 0x82, 0x89, 0x0d,
	0x03, 0xaa, 0xd9, 0xf1, 0x15, 0x0b, 0xee, 0x0d, 0xc3, 0x6f, 0xf3, 0xfe, 0x0d, 0x92, 0x89, 0x99,
	0x2e, 0xd4, 0xa6, 0xa6, 0x56, 0x2c, 0xd8, 0x37, 0x4d, 0xbc, 0xcd, 0xe6, 0x4d, 0x22, 0x65, 0xe9,
	0xb4, 0xc8, 0x2f, 0xa8, 0xe7, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xda, 0x0a, 0x63, 0x19, 0x8f,
	0x19, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FineGuidanceSensorsClient is the client API for FineGuidanceSensors service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FineGuidanceSensorsClient interface {
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (FineGuidanceSensors_GetEventsClient, error)
	GetHealth(ctx context.Context, in *GetHealthStatusRequest, opts ...grpc.CallOption) (*GetHealthStatusResponse, error)
	ListSensors(ctx context.Context, in *ListSensorsRequest, opts ...grpc.CallOption) (*ListSensorsResponse, error)
	EnableSensor(ctx context.Context, in *EnableSensorRequest, opts ...grpc.CallOption) (*EnableSensorResponse, error)
	DisableSensor(ctx context.Context, in *DisableSensorRequest, opts ...grpc.CallOption) (*DisableSensorResponse, error)
}

type fineGuidanceSensorsClient struct {
	cc *grpc.ClientConn
}

func NewFineGuidanceSensorsClient(cc *grpc.ClientConn) FineGuidanceSensorsClient {
	return &fineGuidanceSensorsClient{cc}
}

func (c *fineGuidanceSensorsClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (FineGuidanceSensors_GetEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FineGuidanceSensors_serviceDesc.Streams[0], "/fgs.FineGuidanceSensors/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &fineGuidanceSensorsGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FineGuidanceSensors_GetEventsClient interface {
	Recv() (*GetEventsResponse, error)
	grpc.ClientStream
}

type fineGuidanceSensorsGetEventsClient struct {
	grpc.ClientStream
}

func (x *fineGuidanceSensorsGetEventsClient) Recv() (*GetEventsResponse, error) {
	m := new(GetEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fineGuidanceSensorsClient) GetHealth(ctx context.Context, in *GetHealthStatusRequest, opts ...grpc.CallOption) (*GetHealthStatusResponse, error) {
	out := new(GetHealthStatusResponse)
	err := c.cc.Invoke(ctx, "/fgs.FineGuidanceSensors/GetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fineGuidanceSensorsClient) ListSensors(ctx context.Context, in *ListSensorsRequest, opts ...grpc.CallOption) (*ListSensorsResponse, error) {
	out := new(ListSensorsResponse)
	err := c.cc.Invoke(ctx, "/fgs.FineGuidanceSensors/ListSensors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fineGuidanceSensorsClient) EnableSensor(ctx context.Context, in *EnableSensorRequest, opts ...grpc.CallOption) (*EnableSensorResponse, error) {
	out := new(EnableSensorResponse)
	err := c.cc.Invoke(ctx, "/fgs.FineGuidanceSensors/EnableSensor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fineGuidanceSensorsClient) DisableSensor(ctx context.Context, in *DisableSensorRequest, opts ...grpc.CallOption) (*DisableSensorResponse, error) {
	out := new(DisableSensorResponse)
	err := c.cc.Invoke(ctx, "/fgs.FineGuidanceSensors/DisableSensor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FineGuidanceSensorsServer is the server API for FineGuidanceSensors service.
type FineGuidanceSensorsServer interface {
	GetEvents(*GetEventsRequest, FineGuidanceSensors_GetEventsServer) error
	GetHealth(context.Context, *GetHealthStatusRequest) (*GetHealthStatusResponse, error)
	ListSensors(context.Context, *ListSensorsRequest) (*ListSensorsResponse, error)
	EnableSensor(context.Context, *EnableSensorRequest) (*EnableSensorResponse, error)
	DisableSensor(context.Context, *DisableSensorRequest) (*DisableSensorResponse, error)
}

// UnimplementedFineGuidanceSensorsServer can be embedded to have forward compatible implementations.
type UnimplementedFineGuidanceSensorsServer struct {
}

func (*UnimplementedFineGuidanceSensorsServer) GetEvents(req *GetEventsRequest, srv FineGuidanceSensors_GetEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedFineGuidanceSensorsServer) GetHealth(ctx context.Context, req *GetHealthStatusRequest) (*GetHealthStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (*UnimplementedFineGuidanceSensorsServer) ListSensors(ctx context.Context, req *ListSensorsRequest) (*ListSensorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSensors not implemented")
}
func (*UnimplementedFineGuidanceSensorsServer) EnableSensor(ctx context.Context, req *EnableSensorRequest) (*EnableSensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableSensor not implemented")
}
func (*UnimplementedFineGuidanceSensorsServer) DisableSensor(ctx context.Context, req *DisableSensorRequest) (*DisableSensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableSensor not implemented")
}

func RegisterFineGuidanceSensorsServer(s *grpc.Server, srv FineGuidanceSensorsServer) {
	s.RegisterService(&_FineGuidanceSensors_serviceDesc, srv)
}

func _FineGuidanceSensors_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FineGuidanceSensorsServer).GetEvents(m, &fineGuidanceSensorsGetEventsServer{stream})
}

type FineGuidanceSensors_GetEventsServer interface {
	Send(*GetEventsResponse) error
	grpc.ServerStream
}

type fineGuidanceSensorsGetEventsServer struct {
	grpc.ServerStream
}

func (x *fineGuidanceSensorsGetEventsServer) Send(m *GetEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FineGuidanceSensors_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FineGuidanceSensorsServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fgs.FineGuidanceSensors/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FineGuidanceSensorsServer).GetHealth(ctx, req.(*GetHealthStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FineGuidanceSensors_ListSensors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSensorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FineGuidanceSensorsServer).ListSensors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fgs.FineGuidanceSensors/ListSensors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FineGuidanceSensorsServer).ListSensors(ctx, req.(*ListSensorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FineGuidanceSensors_EnableSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FineGuidanceSensorsServer).EnableSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fgs.FineGuidanceSensors/EnableSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FineGuidanceSensorsServer).EnableSensor(ctx, req.(*EnableSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FineGuidanceSensors_DisableSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FineGuidanceSensorsServer).DisableSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fgs.FineGuidanceSensors/DisableSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FineGuidanceSensorsServer).DisableSensor(ctx, req.(*DisableSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FineGuidanceSensors_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fgs.FineGuidanceSensors",
	HandlerType: (*FineGuidanceSensorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _FineGuidanceSensors_GetHealth_Handler,
		},
		{
			MethodName: "ListSensors",
			Handler:    _FineGuidanceSensors_ListSensors_Handler,
		},
		{
			MethodName: "EnableSensor",
			Handler:    _FineGuidanceSensors_EnableSensor_Handler,
		},
		{
			MethodName: "DisableSensor",
			Handler:    _FineGuidanceSensors_DisableSensor_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _FineGuidanceSensors_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fgs/fgs.proto",
}
