// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fgs/fgs.proto

package fgs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Container struct {
	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image *Image `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// Start time of the container.
	StartTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// PID in the container namespace.
	Pid                  string   `protobuf:"bytes,5,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Container) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Container) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type Pod struct {
	Namespace            string     `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels               []string   `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	Container            *Container `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{2}
}

func (m *Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pod.Unmarshal(m, b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pod.Marshal(b, m, deterministic)
}
func (m *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(m, src)
}
func (m *Pod) XXX_Size() int {
	return xxx_messageInfo_Pod.Size(m)
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

func (m *Pod) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Pod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pod) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Pod) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type Process struct {
	// Exec ID uniquely identifies the process over time across all the nodes in the cluster.
	ExecId               string               `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Pid                  string               `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Uid                  string               `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Cwd                  string               `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Binary               string               `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"`
	Arguments            string               `protobuf:"bytes,6,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Flags                string               `protobuf:"bytes,7,opt,name=flags,proto3" json:"flags,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Auid                 string               `protobuf:"bytes,9,opt,name=auid,proto3" json:"auid,omitempty"`
	Pod                  *Pod                 `protobuf:"bytes,10,opt,name=pod,proto3" json:"pod,omitempty"`
	ParentExecId         string               `protobuf:"bytes,11,opt,name=parent_exec_id,json=parentExecId,proto3" json:"parent_exec_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{3}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetExecId() string {
	if m != nil {
		return m.ExecId
	}
	return ""
}

func (m *Process) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Process) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Process) GetCwd() string {
	if m != nil {
		return m.Cwd
	}
	return ""
}

func (m *Process) GetBinary() string {
	if m != nil {
		return m.Binary
	}
	return ""
}

func (m *Process) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *Process) GetFlags() string {
	if m != nil {
		return m.Flags
	}
	return ""
}

func (m *Process) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Process) GetAuid() string {
	if m != nil {
		return m.Auid
	}
	return ""
}

func (m *Process) GetPod() *Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (m *Process) GetParentExecId() string {
	if m != nil {
		return m.ParentExecId
	}
	return ""
}

type ProcessConnect struct {
	Process              *Process `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Parent               *Process `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	SourceIp             string   `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort           uint32   `protobuf:"varint,4,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationIp        string   `protobuf:"bytes,5,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort      uint32   `protobuf:"varint,6,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	DestinationNames     []string `protobuf:"bytes,7,rep,name=destination_names,json=destinationNames,proto3" json:"destination_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessConnect) Reset()         { *m = ProcessConnect{} }
func (m *ProcessConnect) String() string { return proto.CompactTextString(m) }
func (*ProcessConnect) ProtoMessage()    {}
func (*ProcessConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{4}
}

func (m *ProcessConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessConnect.Unmarshal(m, b)
}
func (m *ProcessConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessConnect.Marshal(b, m, deterministic)
}
func (m *ProcessConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessConnect.Merge(m, src)
}
func (m *ProcessConnect) XXX_Size() int {
	return xxx_messageInfo_ProcessConnect.Size(m)
}
func (m *ProcessConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessConnect.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessConnect proto.InternalMessageInfo

func (m *ProcessConnect) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ProcessConnect) GetParent() *Process {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ProcessConnect) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *ProcessConnect) GetSourcePort() uint32 {
	if m != nil {
		return m.SourcePort
	}
	return 0
}

func (m *ProcessConnect) GetDestinationIp() string {
	if m != nil {
		return m.DestinationIp
	}
	return ""
}

func (m *ProcessConnect) GetDestinationPort() uint32 {
	if m != nil {
		return m.DestinationPort
	}
	return 0
}

func (m *ProcessConnect) GetDestinationNames() []string {
	if m != nil {
		return m.DestinationNames
	}
	return nil
}

type ProcessListen struct {
	Process              *Process `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Parent               *Process `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessListen) Reset()         { *m = ProcessListen{} }
func (m *ProcessListen) String() string { return proto.CompactTextString(m) }
func (*ProcessListen) ProtoMessage()    {}
func (*ProcessListen) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{5}
}

func (m *ProcessListen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessListen.Unmarshal(m, b)
}
func (m *ProcessListen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessListen.Marshal(b, m, deterministic)
}
func (m *ProcessListen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessListen.Merge(m, src)
}
func (m *ProcessListen) XXX_Size() int {
	return xxx_messageInfo_ProcessListen.Size(m)
}
func (m *ProcessListen) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessListen.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessListen proto.InternalMessageInfo

func (m *ProcessListen) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ProcessListen) GetParent() *Process {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ProcessListen) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ProcessListen) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type ProcessExec struct {
	Process *Process `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Parent  *Process `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	// Ancestors of the process beyond the immediate parent.
	Ancestors            []*Process `protobuf:"bytes,3,rep,name=ancestors,proto3" json:"ancestors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProcessExec) Reset()         { *m = ProcessExec{} }
func (m *ProcessExec) String() string { return proto.CompactTextString(m) }
func (*ProcessExec) ProtoMessage()    {}
func (*ProcessExec) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{6}
}

func (m *ProcessExec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessExec.Unmarshal(m, b)
}
func (m *ProcessExec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessExec.Marshal(b, m, deterministic)
}
func (m *ProcessExec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessExec.Merge(m, src)
}
func (m *ProcessExec) XXX_Size() int {
	return xxx_messageInfo_ProcessExec.Size(m)
}
func (m *ProcessExec) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessExec.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessExec proto.InternalMessageInfo

func (m *ProcessExec) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *ProcessExec) GetParent() *Process {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ProcessExec) GetAncestors() []*Process {
	if m != nil {
		return m.Ancestors
	}
	return nil
}

type GetEventsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{7}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

type GetEventsResponse struct {
	// Types that are valid to be assigned to Event:
	//	*GetEventsResponse_ProcessExec
	//	*GetEventsResponse_ProcessConnect
	//	*GetEventsResponse_ProcessListen
	Event isGetEventsResponse_Event `protobuf_oneof:"event"`
	// Name of the node where this event was observed.
	NodeName string `protobuf:"bytes,1000,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Timestamp at which this event was observed.
	Time                 *timestamp.Timestamp `protobuf:"bytes,1001,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_507a05c52639eb54, []int{8}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

type isGetEventsResponse_Event interface {
	isGetEventsResponse_Event()
}

type GetEventsResponse_ProcessExec struct {
	ProcessExec *ProcessExec `protobuf:"bytes,1,opt,name=process_exec,json=processExec,proto3,oneof"`
}

type GetEventsResponse_ProcessConnect struct {
	ProcessConnect *ProcessConnect `protobuf:"bytes,2,opt,name=process_connect,json=processConnect,proto3,oneof"`
}

type GetEventsResponse_ProcessListen struct {
	ProcessListen *ProcessListen `protobuf:"bytes,3,opt,name=process_listen,json=processListen,proto3,oneof"`
}

func (*GetEventsResponse_ProcessExec) isGetEventsResponse_Event() {}

func (*GetEventsResponse_ProcessConnect) isGetEventsResponse_Event() {}

func (*GetEventsResponse_ProcessListen) isGetEventsResponse_Event() {}

func (m *GetEventsResponse) GetEvent() isGetEventsResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *GetEventsResponse) GetProcessExec() *ProcessExec {
	if x, ok := m.GetEvent().(*GetEventsResponse_ProcessExec); ok {
		return x.ProcessExec
	}
	return nil
}

func (m *GetEventsResponse) GetProcessConnect() *ProcessConnect {
	if x, ok := m.GetEvent().(*GetEventsResponse_ProcessConnect); ok {
		return x.ProcessConnect
	}
	return nil
}

func (m *GetEventsResponse) GetProcessListen() *ProcessListen {
	if x, ok := m.GetEvent().(*GetEventsResponse_ProcessListen); ok {
		return x.ProcessListen
	}
	return nil
}

func (m *GetEventsResponse) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *GetEventsResponse) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetEventsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetEventsResponse_ProcessExec)(nil),
		(*GetEventsResponse_ProcessConnect)(nil),
		(*GetEventsResponse_ProcessListen)(nil),
	}
}

func init() {
	proto.RegisterType((*Image)(nil), "fgs.Image")
	proto.RegisterType((*Container)(nil), "fgs.Container")
	proto.RegisterType((*Pod)(nil), "fgs.Pod")
	proto.RegisterType((*Process)(nil), "fgs.Process")
	proto.RegisterType((*ProcessConnect)(nil), "fgs.ProcessConnect")
	proto.RegisterType((*ProcessListen)(nil), "fgs.ProcessListen")
	proto.RegisterType((*ProcessExec)(nil), "fgs.ProcessExec")
	proto.RegisterType((*GetEventsRequest)(nil), "fgs.GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "fgs.GetEventsResponse")
}

func init() { proto.RegisterFile("fgs/fgs.proto", fileDescriptor_507a05c52639eb54) }

var fileDescriptor_507a05c52639eb54 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6a, 0x1b, 0x39,
	0x14, 0xb6, 0xc7, 0xbf, 0x73, 0x1c, 0x3b, 0x8e, 0xb2, 0x9b, 0x1d, 0xbc, 0x0b, 0x31, 0x43, 0x76,
	0xc9, 0x6e, 0x16, 0xbb, 0xa4, 0xf4, 0xa2, 0x14, 0x72, 0xd1, 0x90, 0x26, 0x86, 0x52, 0xcc, 0xb4,
	0xbd, 0x36, 0xe3, 0x19, 0x79, 0x10, 0xd8, 0x92, 0x3a, 0x92, 0xfb, 0x73, 0xd1, 0x8b, 0x5e, 0xf5,
	0x21, 0x0a, 0xed, 0x53, 0xf4, 0x9d, 0xda, 0xb7, 0x28, 0x3a, 0xd2, 0x38, 0x13, 0x53, 0x68, 0x0b,
	0xb9, 0x3b, 0xfa, 0xce, 0x8f, 0xbe, 0xf3, 0x9d, 0x23, 0x41, 0x77, 0x91, 0xa9, 0xf1, 0x22, 0x53,
	0x23, 0x99, 0x0b, 0x2d, 0x48, 0x6d, 0x91, 0xa9, 0xc1, 0x61, 0x26, 0x44, 0xb6, 0xa4, 0x63, 0x84,
	0xe6, 0xeb, 0xc5, 0x58, 0xb3, 0x15, 0x55, 0x3a, 0x5e, 0x49, 0x1b, 0x15, 0x9e, 0x40, 0x63, 0xb2,
	0x8a, 0x33, 0x4a, 0x7a, 0xe0, 0xb1, 0x34, 0xa8, 0x0e, 0xab, 0xc7, 0x7e, 0xe4, 0xb1, 0x94, 0x10,
	0xa8, 0xf3, 0x78, 0x45, 0x03, 0x0f, 0x11, 0xb4, 0xc3, 0x8f, 0x55, 0xf0, 0xcf, 0x05, 0xd7, 0x31,
	0xe3, 0x34, 0xff, 0x99, 0x0c, 0x32, 0x84, 0x06, 0x33, 0xe5, 0x83, 0xda, 0xb0, 0x7a, 0xdc, 0x39,
	0x85, 0x91, 0xe1, 0x87, 0x17, 0x46, 0xd6, 0x41, 0xee, 0x03, 0x28, 0x1d, 0xe7, 0x7a, 0x66, 0x98,
	0x05, 0x75, 0x0c, 0x1b, 0x8c, 0x2c, 0xed, 0x51, 0x41, 0x7b, 0xf4, 0xac, 0xa0, 0x1d, 0xf9, 0x18,
	0x6d, 0xce, 0xa4, 0x0f, 0x35, 0xc9, 0xd2, 0xa0, 0x81, 0xf7, 0x19, 0x33, 0x7c, 0x0b, 0xb5, 0xa9,
	0x48, 0xc9, 0x5f, 0xe0, 0x9b, 0xdb, 0x95, 0x8c, 0x13, 0xea, 0x08, 0x5e, 0x03, 0xdf, 0xe5, 0x79,
	0x00, 0xcd, 0x65, 0x3c, 0xa7, 0x4b, 0x15, 0xd4, 0x86, 0xb5, 0x63, 0x3f, 0x72, 0x27, 0xf2, 0x3f,
	0xf8, 0x49, 0xd1, 0xb0, 0x23, 0xd7, 0xc3, 0x1e, 0x36, 0x32, 0x44, 0xd7, 0x01, 0xe1, 0x67, 0x0f,
	0x5a, 0xd3, 0x5c, 0x24, 0x54, 0x29, 0xf2, 0x07, 0xb4, 0xe8, 0x6b, 0x9a, 0xcc, 0x36, 0x12, 0x35,
	0xcd, 0x71, 0x92, 0x16, 0xac, 0xbd, 0x0d, 0x6b, 0x83, 0xac, 0x59, 0x8a, 0x12, 0xf9, 0x91, 0x31,
	0x0d, 0x92, 0xbc, 0x4a, 0xf1, 0x42, 0x3f, 0x32, 0xa6, 0x21, 0x38, 0x67, 0x3c, 0xce, 0xdf, 0xb8,
	0x76, 0xdd, 0xc9, 0xb4, 0x1a, 0xe7, 0xd9, 0x7a, 0x45, 0xb9, 0x56, 0x41, 0xd3, 0xb6, 0xba, 0x01,
	0xc8, 0x6f, 0xd0, 0x58, 0x2c, 0xe3, 0x4c, 0x05, 0x2d, 0xf4, 0xd8, 0xc3, 0x96, 0xe4, 0xed, 0x5f,
	0x91, 0x9c, 0x40, 0x3d, 0x36, 0x5c, 0x7d, 0xab, 0x9d, 0xb1, 0xc9, 0x00, 0x6a, 0x52, 0xa4, 0x01,
	0x60, 0x9d, 0x36, 0xaa, 0x33, 0x15, 0x69, 0x64, 0x40, 0x72, 0x04, 0x3d, 0x19, 0xe7, 0x94, 0xeb,
	0x59, 0x21, 0x46, 0x07, 0x33, 0x77, 0x2c, 0x7a, 0x81, 0x92, 0x84, 0x1f, 0x3c, 0xe8, 0x39, 0xdd,
	0xce, 0x05, 0xe7, 0x34, 0xd1, 0xe4, 0x1f, 0x68, 0x49, 0x8b, 0xa0, 0x7c, 0x9d, 0xd3, 0x1d, 0x5b,
	0xd8, 0x62, 0x51, 0xe1, 0x24, 0x47, 0xd0, 0xb4, 0xa5, 0x50, 0xd0, 0xed, 0x30, 0xe7, 0x23, 0x7f,
	0x82, 0xaf, 0xc4, 0x3a, 0x4f, 0xe8, 0x8c, 0x49, 0xa7, 0x73, 0xdb, 0x02, 0x13, 0x49, 0x0e, 0xa1,
	0xe3, 0x9c, 0x52, 0xe4, 0x1a, 0x45, 0xef, 0x46, 0x60, 0xa1, 0xa9, 0xc8, 0x35, 0xf9, 0x1b, 0x7a,
	0x29, 0x55, 0x9a, 0xf1, 0x58, 0x33, 0xc1, 0x4d, 0x09, 0x3b, 0x83, 0x6e, 0x09, 0x9d, 0x48, 0xf2,
	0x2f, 0xf4, 0xcb, 0x61, 0x58, 0xac, 0x89, 0xc5, 0x76, 0x4b, 0x38, 0x56, 0x3c, 0x81, 0xbd, 0x72,
	0x28, 0xee, 0x66, 0xd0, 0xc2, 0xcd, 0x2b, 0xd7, 0x78, 0x62, 0xf0, 0xf0, 0x5d, 0x15, 0xba, 0xae,
	0xa1, 0xc7, 0x4c, 0x69, 0xca, 0x6f, 0x59, 0x1c, 0xf3, 0x8e, 0x0b, 0x55, 0x3c, 0x26, 0xcd, 0x8c,
	0x37, 0x42, 0xf8, 0x11, 0xda, 0xe1, 0xfb, 0x2a, 0x74, 0x5c, 0x9e, 0x99, 0xd9, 0x2d, 0x33, 0xf8,
	0x0f, 0xfc, 0x98, 0x27, 0x54, 0x69, 0x91, 0xdb, 0x07, 0xb8, 0x1d, 0x78, 0xed, 0x0e, 0x09, 0xf4,
	0x2f, 0xa9, 0xbe, 0x78, 0x69, 0xf6, 0x3b, 0xa2, 0x2f, 0xd6, 0x54, 0xe9, 0xf0, 0x93, 0x07, 0x7b,
	0x25, 0x50, 0x49, 0xc1, 0x15, 0x25, 0xf7, 0x60, 0xc7, 0xd1, 0xc0, 0xe5, 0x73, 0x44, 0xfb, 0xe5,
	0xc2, 0xa6, 0x97, 0xab, 0x4a, 0xd4, 0x91, 0xa5, 0xd6, 0xce, 0x60, 0xb7, 0x48, 0x4b, 0xec, 0x32,
	0x3a, 0xee, 0xfb, 0xe5, 0x4c, 0xb7, 0xa7, 0x57, 0x95, 0xa8, 0x27, 0x6f, 0x6e, 0xee, 0x03, 0x28,
	0x90, 0xd9, 0x12, 0xc7, 0xe5, 0xfe, 0x3e, 0x52, 0x4e, 0xb7, 0x83, 0xbc, 0xaa, 0x44, 0x5d, 0x79,
	0x63, 0xb2, 0xe6, 0xe7, 0x12, 0x29, 0xc5, 0x8d, 0x08, 0xbe, 0xd8, 0x57, 0xdb, 0x36, 0x88, 0x59,
	0x05, 0x32, 0x86, 0x3a, 0x3e, 0xd9, 0xaf, 0xad, 0x1f, 0xbe, 0x59, 0x0c, 0x7c, 0xd8, 0x82, 0x06,
	0x35, 0xa2, 0x9c, 0x3e, 0x87, 0xfd, 0x47, 0x8c, 0xd3, 0xcb, 0x35, 0x4b, 0x8d, 0x94, 0x4f, 0x29,
	0x57, 0x22, 0x57, 0xe4, 0x0c, 0xfc, 0x8d, 0x6e, 0xe4, 0x77, 0x24, 0xb8, 0x2d, 0xee, 0xe0, 0x60,
	0x1b, 0xb6, 0xf2, 0x86, 0x95, 0x3b, 0xd5, 0x79, 0x13, 0x6f, 0xbe, 0xfb, 0x2d, 0x00, 0x00, 0xff,
	0xff, 0x86, 0xa7, 0xb8, 0x6f, 0x7b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FineGuidanceSensorsClient is the client API for FineGuidanceSensors service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FineGuidanceSensorsClient interface {
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (FineGuidanceSensors_GetEventsClient, error)
}

type fineGuidanceSensorsClient struct {
	cc *grpc.ClientConn
}

func NewFineGuidanceSensorsClient(cc *grpc.ClientConn) FineGuidanceSensorsClient {
	return &fineGuidanceSensorsClient{cc}
}

func (c *fineGuidanceSensorsClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (FineGuidanceSensors_GetEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FineGuidanceSensors_serviceDesc.Streams[0], "/fgs.FineGuidanceSensors/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &fineGuidanceSensorsGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FineGuidanceSensors_GetEventsClient interface {
	Recv() (*GetEventsResponse, error)
	grpc.ClientStream
}

type fineGuidanceSensorsGetEventsClient struct {
	grpc.ClientStream
}

func (x *fineGuidanceSensorsGetEventsClient) Recv() (*GetEventsResponse, error) {
	m := new(GetEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FineGuidanceSensorsServer is the server API for FineGuidanceSensors service.
type FineGuidanceSensorsServer interface {
	GetEvents(*GetEventsRequest, FineGuidanceSensors_GetEventsServer) error
}

// UnimplementedFineGuidanceSensorsServer can be embedded to have forward compatible implementations.
type UnimplementedFineGuidanceSensorsServer struct {
}

func (*UnimplementedFineGuidanceSensorsServer) GetEvents(req *GetEventsRequest, srv FineGuidanceSensors_GetEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}

func RegisterFineGuidanceSensorsServer(s *grpc.Server, srv FineGuidanceSensorsServer) {
	s.RegisterService(&_FineGuidanceSensors_serviceDesc, srv)
}

func _FineGuidanceSensors_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FineGuidanceSensorsServer).GetEvents(m, &fineGuidanceSensorsGetEventsServer{stream})
}

type FineGuidanceSensors_GetEventsServer interface {
	Send(*GetEventsResponse) error
	grpc.ServerStream
}

type fineGuidanceSensorsGetEventsServer struct {
	grpc.ServerStream
}

func (x *fineGuidanceSensorsGetEventsServer) Send(m *GetEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _FineGuidanceSensors_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fgs.FineGuidanceSensors",
	HandlerType: (*FineGuidanceSensorsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _FineGuidanceSensors_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fgs/fgs.proto",
}
