// Copyright 2020 Authors of Hubble
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

import "tetragon.proto";

package fgs;

option go_package = "github.com/isovalent/hubble-fgs/api/v1/fgs";

message InterfaceStats {
    string interface_name = 1;
    uint32 interface_ifindex = 2;
    uint64 bytes_sent = 3;
    uint64 bytes_received = 4;
    uint64 packets_sent = 5;
    uint64 packets_received = 6;
    uint64 tx_errors = 7;
    uint64 rx_errors = 8;
    uint64 tx_drops = 9;
    uint64 rx_drops = 10;
    tetragon.Pod    pod = 11;
    string netns = 12;
    string container_name = 13;
}

message SocketStats {
    uint64 bytes_sent = 1;
    uint64 bytes_received = 2;
    uint32 segs_in = 3;
    uint32 segs_out = 4;

    // TCP specific:
    uint32 srtt = 5;
    uint64 retransmits_bytes = 6;
    uint32 retransmits_segs = 7;
    uint32 to_zero_window = 8;

    uint32 sk_drop = 9;

    // UDP specific:
    uint64 bytes_consumed = 10;
    uint64 bytes_submitted = 11;
    uint32 segs_consumed = 12;
    uint32 segs_submitted = 13;
    uint32 skb_consume_misses = 14;
}

enum SocketProtocol {
    UNKNOWN = 0;
    TCP = 6;
    UDP = 17;
}

message ProcessConnect {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    string source_ip = 3;
    google.protobuf.UInt32Value source_port = 4;
    string destination_ip = 5;
    google.protobuf.UInt32Value destination_port = 6;
    repeated string destination_names = 7;
    uint64 sock_cookie = 8;
    tetragon.Pod destination_pod = 9;
    SocketProtocol protocol = 10;
}

message ProcessClose {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    string source_ip = 3;
    google.protobuf.UInt32Value source_port = 4;
    string destination_ip = 5;
    google.protobuf.UInt32Value destination_port = 6;
    repeated string destination_names = 7;
    uint64 sock_cookie = 8;
    SocketStats stats = 9;
    tetragon.Pod destination_pod = 10;
    SocketProtocol protocol = 11;
    string socket_type = 12;
}

message ProcessListen {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    string ip = 3;
    google.protobuf.UInt32Value port = 4;
    uint64 sock_cookie = 5;
    SocketProtocol protocol = 6;
}

message ProcessAccept {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    string source_ip = 3;
    google.protobuf.UInt32Value source_port = 4;
    string destination_ip = 5;
    google.protobuf.UInt32Value destination_port = 6;
    repeated string destination_names = 7;
    uint64 sock_cookie = 8;
    tetragon.Pod destination_pod = 9;
    SocketProtocol protocol = 10;
}

message ProcessIpError {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    string source_ip = 3;
    string destination_ip = 4;
    string version = 5;
    uint64 sock_cookie = 6;
    tetragon.Pod destination_pod = 7;
    string details = 8;
}

message ProcessExec {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    // Ancestors of the process beyond the immediate parent.
    repeated tetragon.Process ancestors = 3;
}

message ProcessExit {
    tetragon.Process process = 1;
    tetragon.Process parent  = 2;
    string  signal  = 3;
    uint32  status  = 4;
}

message ProcessCred {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    tetragon.Capabilities cap = 3;
}

message KprobeSock {
    string family = 1;
    string type = 2;
    string protocol = 3;
    uint32 mark = 4;
    uint32 priority = 5;
    string saddr = 6;
    string daddr = 7;
    uint32 sport = 8;
    uint32 dport = 9;
}

message KprobeSkb {
    uint32 hash = 1;
    uint32 len = 2;
    uint32 priority = 3;
    uint32 mark = 4;
    string saddr = 5;
    string daddr = 6;
    uint32 sport = 7;
    uint32 dport = 8;
    uint32 proto = 9;
    uint32 sec_path_len = 10;
    uint32 sec_path_olen = 11;
}

message KprobePath {
    string mount = 1;
    string path  = 2;
    string flags = 3;
}

message KprobeFile {
    string mount = 1;
    string path  = 2;
    string flags = 3;
}

message KprobeTruncatedBytes {
	bytes bytes_arg = 1;
	uint64 orig_size = 2;
}

message KprobeCred {
    repeated tetragon.CapabilitiesType permitted = 1;
    repeated tetragon.CapabilitiesType effective = 2;
    repeated tetragon.CapabilitiesType inheritable = 3;
}

message KprobeArgument {
    oneof arg {
	string    string_arg = 1;
	int32     int_arg = 2;
	KprobeSkb skb_arg = 3;
	uint64    size_arg = 4;
	bytes     bytes_arg = 5;
	KprobePath path_arg = 6;
	KprobeFile file_arg = 7;
	KprobeTruncatedBytes truncated_bytes_arg = 8;
	KprobeSock sock_arg = 9;
	KprobeCred cred_arg = 10;
    }
}

enum KprobeAction {
	KPROBE_ACTION_UNKNOWN    = 0;
	KPROBE_ACTION_POST	 = 1;
	KPROBE_ACTION_FOLLOWFD   = 2;
	KPROBE_ACTION_SIGKILL    = 3;
	KPROBE_ACTION_UNFOLLOWFD = 4;
	KPROBE_ACTION_OVERRIDE   = 5;
	KPROBE_ACTION_COPYFD     = 6;
}

message ProcessKprobe {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    string function_name = 3;
    repeated KprobeArgument args = 4;
    KprobeArgument return = 5;
    KprobeAction action = 6;
}

message ProcessTracepoint {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    string subsys = 4;
    string event = 5;
    // TODO: once we implement all we want, rename KprobeArgument to GenericArgument
    repeated KprobeArgument args = 6;
}

enum FileAction {
    FILE_INVALID = 0;
    FILE_WRITE = 1;
    FILE_READ = 2;
    FILE_DELETE = 3;
    FILE_CREATE = 4;
}

message ProcessFile {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    FileAction action = 3;
    string filename = 4;
    uint64 inode_number = 5;
    google.protobuf.Timestamp time = 6;
    string hook = 7;
}

message SockInfo {
    string source_ip = 1;
    google.protobuf.UInt32Value source_port = 2;
    string destination_ip = 3;
    google.protobuf.UInt32Value destination_port = 4;
    uint64 sock_cookie = 5;
    SocketProtocol protocol = 6;
    repeated string destination_names = 7;
    tetragon.Pod destination_pod = 8;
  }

message ProcessSockStats {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    SockInfo socket = 3;
    SocketStats stats = 4;
}

message Test {
	uint64 arg0 = 1;
	uint64 arg1 = 2;
	uint64 arg2 = 3;
	uint64 arg3 = 4;
}

enum TlsCertificateError {
    TLS_CERT_ERROR_UNDEF             = 0;
    TLS_CERT_ERROR_UNKNOWN           = 1;
    TLS_CERT_ERROR_TOO_LARGE         = 2 [deprecated=true];
    TLS_CERT_ERROR_GET_DATA_HDR      = 3 [deprecated=true];
    TLS_CERT_ERROR_NO_BUFFER         = 4 [deprecated=true];
    TLS_CERT_ERROR_COPY              = 5 [deprecated=true];
    TLS_CERT_ERROR_LENGTH_READ       = 6;
    TLS_CERT_ERROR_CERT_READ         = 7;
    TLS_CERT_ERROR_CERT_PARTIAL      = 8;
    TLS_CERT_ERROR_PARSE_X509        = 9;
    TLS_CERT_ERROR_MISSING_CODE      = 10 [deprecated=true];
    TLS_CERT_ERROR_GET_DATA_CERT     = 11 [deprecated=true];
    TLS_CERT_ERROR_GET_DATA_MORECERT = 12 [deprecated=true];
    TLS_CERT_ERROR_COPY_CERT         = 13 [deprecated=true];
    TLS_CERT_ERROR_COPY_MORE_CERT    = 14 [deprecated=true];
    TLS_CERT_ERROR_BAD_HEADER        = 15;
    TLS_CERT_ERROR_MISSING_ERROR     = 16;
    TLS_CERT_ERROR_SPURIOUS_CERTS    = 17;
}

message Tls {
    tetragon.Process process = 1;
    string source_ip = 2;
    google.protobuf.UInt32Value source_port = 3;
    string destination_ip = 4;
    google.protobuf.UInt32Value destination_port = 5;
    string negotiated_version = 6;
    string supported_versions = 7;
    string sni_type = 8;
    string sni_name = 9;
    string cipher = 10;
    string client_flags = 11;
    string server_flags = 12;
    string client_version = 13;
    string server_version = 14;
    string client_alert = 15;
    string server_alert = 16;
    string client_session = 17;
    string server_session = 18;
    repeated string certificates = 19;
    TlsCertificateError certificate_error = 20;
    uint32 parser_state_next = 21 [deprecated=true];
    uint32 parser_state_needed = 22 [deprecated=true];
    uint32 parser_state_csize = 23 [deprecated=true];
    uint32 parser_state_skblen = 24 [deprecated=true];
    string parser_internal_state = 25;
}

/*
 * HTTP PARSER
 */
message HttpHeader {
   string name  = 1;
   string value = 2;
}

message HttpRequest {
   google.protobuf.Timestamp timestamp = 1;
   string method               = 2;
   string uri                  = 3;
   string version              = 4;
   string host                 = 5;
   string agent                = 6;
   google.protobuf.UInt32Value content_length = 7;
   repeated HttpHeader headers = 8;
   string flags                = 9;
   string transfer_encoding    = 10;
}

message HttpResponse {
   google.protobuf.Timestamp timestamp = 1;
   string version               = 2;
   uint32 code                  = 3;
   string reason                = 4;
   google.protobuf.UInt32Value content_length = 5;
   repeated HttpHeader headers  = 6;
   string flags                 = 7;
   string transfer_encoding     = 8;
}

message HttpInfo {
   HttpRequest request              = 1;
   HttpResponse response            = 2;
   google.protobuf.Duration latency = 3;
}

message ProcessHttp {
    tetragon.Process process = 1;
    SockInfo socket = 2;
    HttpInfo http   = 3;
    repeated string destination_names = 4 [deprecated=true]; // deprecated in favor of socket.destination_names.
    tetragon.Pod destination_pod = 5;
}

message DnsInfo {
    repeated uint32 question_types = 1;
    repeated uint32 answer_types = 2;
    int32 rcode = 3;
    repeated string names = 4;
    repeated string ips = 5;
    string query = 6;
    bool response = 7;
}

message ProcessDns {
    tetragon.Process process = 1;
    SockInfo socket = 2;
    DnsInfo dns   = 3;
    repeated string destination_names = 4 [deprecated=true]; // deprecated in favor of socket.destination_names.
    tetragon.Pod destination_pod = 5;
}

/**
 * Stack traces
 */

message StackAddress {
	uint64 address = 1;
	string symbol = 2;
}

message StackTrace {
	repeated StackAddress addresses = 1;
}

message StackTraceLabel {
	string key = 1;
	uint64 count = 2;
}

message StackTraceNode {
	StackAddress address = 1;
	uint64 count = 2;
	repeated StackTraceLabel labels = 3;
	repeated StackTraceNode children = 4;
}

/**
 * Sensors
 */

message ListSensorsRequest { }

message SensorStatus {
	string name = 1;
	bool enabled = 2;
}
message ListSensorsResponse {
	repeated SensorStatus sensors = 1;
}

message AddTracingPolicyRequest {
	string yaml = 1;
}
message AddTracingPolicyResponse {}

message DeleteTracingPolicyRequest {
	string yaml = 1;
}
message DeleteTracingPolicyResponse {}

message RemoveSensorRequest {
	string name = 1;
}
message RemoveSensorResponse {}


message EnableSensorRequest {
	string name = 1;
}

message EnableSensorResponse {}

message DisableSensorRequest {
	string name = 1;
}

message SetSensorConfigRequest {
	string name = 1;
	string cfgkey = 2;
	string cfgval = 3;
}

message SetSensorConfigResponse {}

message GetSensorConfigRequest {
	string name = 1;
	string cfgkey = 2;
}

message GetSensorConfigResponse {
	string cfgval = 1;
}

message DisableSensorResponse { }

message GetStackTraceTreeRequest {
	string name = 1;
}

message GetStackTraceTreeResponse {
	StackTraceNode root = 1;
}

message GetVersionRequest{}
message GetVersionResponse{
	string version = 1;
}

service FineGuidanceSensors {
    rpc GetEvents(GetEventsRequest) returns (stream GetEventsResponse) {}
    rpc GetHealth(GetHealthStatusRequest) returns (GetHealthStatusResponse) {}

    rpc AddTracingPolicy(AddTracingPolicyRequest) returns (AddTracingPolicyResponse) {}
    rpc RemoveSensor(RemoveSensorRequest) returns (RemoveSensorResponse) {}

    rpc ListSensors(ListSensorsRequest) returns (ListSensorsResponse) {}
    rpc EnableSensor(EnableSensorRequest) returns (EnableSensorResponse) {}
    rpc DisableSensor(DisableSensorRequest) returns (DisableSensorResponse) {}
    rpc SetSensorConfig(SetSensorConfigRequest) returns (SetSensorConfigResponse) {}
    rpc GetSensorConfig(GetSensorConfigRequest) returns (GetSensorConfigResponse) {}

    rpc GetStackTraceTree(GetStackTraceTreeRequest) returns (GetStackTraceTreeResponse) {}

    rpc GetVersion(GetVersionRequest) returns (GetVersionResponse) {}
}

enum HealthStatusType {
 HEALTH_STATUS_TYPE_UNDEF  = 0;
 HEALTH_STATUS_TYPE_STATUS = 1;
}

enum HealthStatusResult {
 HEALTH_STATUS_UNDEF    = 0;
 HEALTH_STATUS_RUNNING  = 1;
 HEALTH_STATUS_STOPPED  = 2;
 HEALTH_STATUS_ERROR    = 3;
}

message GetHealthStatusRequest {
    repeated HealthStatusType event_set = 1;
}

message HealthStatus {
	HealthStatusType event = 1;
	HealthStatusResult status = 2;
	string details = 3;
}

message GetHealthStatusResponse {
	repeated HealthStatus health_status = 1;
}

// AggregationOptions defines configuration options for aggregating events.
message AggregationOptions {
    // Aggregation window size. Defaults to 15 seconds if this field is not set.
    google.protobuf.Duration window_size = 1;
    // Size of the buffer for the aggregator to receive incoming events. If the
    // buffer becomes full, the aggregator will log a warning and start dropping
    // incoming events.
    uint64 channel_buffer_size = 2;
}

message GetEventsRequest {
    // allow_list specifies a list of filters to apply to only return certain
    // events. If multiple filters are specified, at least one of them has to
    // match for an event to be included in the results.
    repeated Filter allow_list = 1;
    // deny_list specifies a list of filters to apply to exclude certain events
    // from the results. If multiple filters are specified, at least one of
    // them has to match for an event to be excluded.
    //
    // If both allow_list and deny_list are specified, the results contain the
    // set difference allow_list - deny_list.
    repeated Filter deny_list = 2;
    // aggregation_options configures aggregation options for this request.
    // If this field is not set, responses will not be aggregated.
    //
    // Note that currently only process_accept and process_connect events are
    // aggregated. Other events remain unaggregated.
    AggregationOptions aggregation_options = 3;
}

// AggregationInfo contains information about aggregation results.
message AggregationInfo {
    // Total count of events in this aggregation time window.
    uint64 count = 1;
}

message ProcessNetworkBurst {
    tetragon.Process process = 1;
    tetragon.Process parent = 2;
    string protocol = 3;
    string direction = 4;
    string burst_state = 5;
    uint64 window_size = 6;
    uint64 hist_avg = 7;
    uint64 hist_trigger = 8;
    uint64 window_avg = 9;
}

message GetEventsResponse {
    oneof event {
        ProcessExec process_exec = 1;
        ProcessConnect process_connect = 2;
        ProcessListen process_listen = 3;
        Tls tls = 4;
        ProcessExit process_exit = 5;
        ProcessClose process_close = 6;
        ProcessAccept process_accept = 7;
        ProcessCred process_cred = 8;
        ProcessKprobe process_kprobe = 9;
        ProcessTracepoint process_tracepoint = 10;
        ProcessSockStats process_sock_stats = 11;
        ProcessHttp process_http = 12;
        InterfaceStats interface_stats = 13;
        ProcessDns process_dns = 14;
        ProcessNetworkBurst process_network_burst = 15;
        ProcessFile process_file = 16;
         ProcessIpError process_ip_error = 17;

        Test test = 40000;
    }
    // Name of the node where this event was observed.
    string node_name = 1000;
    // Timestamp at which this event was observed.
    //
    // For an aggregated response, this field to set to the timestamp at which
    // the event was observed for the first time in a given aggregation time window.
    google.protobuf.Timestamp time = 1001;

    // aggregation_info contains information about aggregation results. This field
    // is set only for aggregated responses.
    AggregationInfo aggregation_info = 1002;
}

// EventType constants are based on the ones from pkg/api/client
enum EventType {
    option allow_alias = true;
	UNDEF = 0;
	PROCESS_CONNECT = 1;
	PROCESS_LISTEN = 4;
	PROCESS_EXEC = 5;
	PROCESS_TLS = 6;
    // TLS is an alias for PROCESS_TLS
	TLS = 6;
	PROCESS_EXIT = 7;
	PROCESS_CLOSE = 8;
	PROCESS_ACCEPT = 9;
	PROCESS_CRED = 10;
	PROCESS_KPROBE = 13;
	PROCESS_TRACEPOINT = 14;
	PROCESS_SOCKSTATS = 15;
    // TLS is an alias for PROCESS_SOCKSTATS
	PROCESS_SOCK_STATS = 15;
	PROCESS_HTTP = 16;
	INTERFACE_STATS = 17;
	PROCESS_DNS = 18;
	PROCESS_NETWORK_BURST = 19;
	PROCESS_FILE = 20;
    PROCESS_IP_ERROR = 21;

	TEST = 254;
}

message Filter {
    repeated string binary_regex = 1;
    repeated string namespace = 2;
    google.protobuf.BoolValue health_check = 3;
    repeated uint32 pid = 4;
    repeated uint32 pid_set = 5;
    repeated EventType event_set = 6;
    // A series of regexes for filtering over pod name
    repeated string pod_regex = 7;
}
