// Copyright 2020 Authors of Hubble
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

package fgs;

message Image {
    string id = 1;
    string name = 2;
}

message Container {
    string id = 1;
    string name = 2;
    Image image = 3;
    // Start time of the container.
    google.protobuf.Timestamp start_time = 4;
    // PID in the container namespace.
    google.protobuf.UInt32Value pid = 5;

    // If this is set true, it means that the process might have been originated from
    // a Kubernetes exec probe. For this field to be true, the following must be true:
    //
    // 1. The binary field matches the first element of the exec command list for either
    //    liveness or readiness probe excluding the basename. For example, "/bin/ls"
    //    and "ls" are considered a match.
    // 2. The arguments field exactly matches the rest of the exec command list.
    bool maybe_exec_probe = 13;
}

message Pod {
    string namespace = 1;
    string name = 2;
    repeated string labels = 3;
    Container container = 4;
}

message Process {
    // Exec ID uniquely identifies the process over time across all the nodes in the cluster.
    string exec_id = 1;
    google.protobuf.UInt32Value pid = 2;
    google.protobuf.UInt32Value uid = 3;
    string cwd = 4;
    string binary = 5;
    string arguments = 6;
    string flags = 7;
    google.protobuf.Timestamp start_time = 8;
    google.protobuf.UInt32Value auid = 9;
    Pod pod = 10;
    string docker = 11;
    string parent_exec_id = 12;
}

message ProcessConnect {
    Process process = 1;
    Process parent = 2;
    string source_ip = 3;
    google.protobuf.UInt32Value source_port = 4;
    string destination_ip = 5;
    google.protobuf.UInt32Value destination_port = 6;
    repeated string destination_names = 7;
}

message ProcessListen {
    Process process = 1;
    Process parent = 2;
    string ip = 3;
    google.protobuf.UInt32Value port = 4;
}

message ProcessExec {
    Process process = 1;
    Process parent = 2;
    // Ancestors of the process beyond the immediate parent.
    repeated Process ancestors = 3;
}

message ProcessExit {
    Process process = 1;
    Process parent = 2;
}

message Tls {
    Process process = 1;
    string source_ip = 2;
    google.protobuf.UInt32Value source_port = 3;
    string destination_ip = 4;
    google.protobuf.UInt32Value destination_port = 5;
    string negotiated_version = 6;
    string supported_versions = 7;
    string sni_type = 8;
    string sni_name = 9;
    string cipher = 10;
    string client_flags = 11;
    string server_flags = 12;
    string client_version = 13;
    string server_version = 14;
    string client_alert = 15;
    string server_alert = 16;
    string client_session = 17;
    string server_session = 18;
}

service FineGuidanceSensors {
    rpc GetEvents(GetEventsRequest) returns (stream GetEventsResponse) {}
}

message GetEventsRequest {
    // allow_list specifies a list of filters to apply to only return certain
    // events. If multiple filters are specified, at least one of them has to
    // match for an event to be included in the results.
    repeated Filter allow_list = 1;
    // deny_list specifies a list of filters to apply to exclude certain events
    // from the results. If multiple filters are specified, at least one of
    // them has to match for an event to be excluded.
    //
    // If both allow_list and deny_list are specified, the results contain the
    // set difference allow_list - deny_list.
    repeated Filter deny_list = 2;
}

message GetEventsResponse {
    oneof event {
        ProcessExec process_exec = 1;
        ProcessConnect process_connect = 2;
        ProcessListen process_listen = 3;
	Tls tls = 4;
	ProcessExit process_exit = 5;
    }
    // Name of the node where this event was observed.
    string node_name = 1000;
    // Timestamp at which this event was observed.
    google.protobuf.Timestamp time = 1001;
}

// EventType constants are based on the ones from pkg/api/client
enum EventType {
	UNDEF = 0;
	PROCESS_CONNECT = 1;
	PROCESS_LISTEN = 4;
	PROCESS_EXEC = 5;
	PROCESS_TLS = 6;
	PROCESS_EXIT = 7;
}

message Filter {
    repeated string binary_regex = 1;
    repeated string namespace = 2;
    google.protobuf.BoolValue health_check = 3;
    repeated uint32 pid = 4;
    repeated uint32 pid_set = 5;
    repeated EventType event_set = 6;
}
