#ifndef _ISO_MSG_TYPES_
#define _ISO_MSG_TYPES_

// TODO: remove
#include "../modules/tetragon-oss/bpf/lib/msg_types.h"

/* Msg Types */
enum iso_msg_ops {
	ISO_MSG_OP_UNDEF = MSG_OP_UNDEF,
	ISO_MSG_OP_IPV4_TCPCONNECT = 1,
	ISO_MSG_OP_IPV4_TCPCONNECTRET = 2,
	ISO_MSG_OP_IPV4_BIND = 3,
	ISO_MSG_OP_IPV4_LISTEN = 4,
	ISO_MSG_OP_EXECVE = MSG_OP_EXECVE,
	ISO_MSG_OP_TLS = 6,
	ISO_MSG_OP_EXIT = MSG_OP_EXIT,
	ISO_MSG_OP_IPV4_TCPCLOSE = 8,
	ISO_MSG_OP_IPV4_TCPACCEPT = 9,
	ISO_MSG_OP_CREDS = 10,
	ISO_MSG_OP_KFREE_SKB = 11,
	ISO_MSG_OP_TLS_CONT = 12,
	ISO_MSG_OP_GENERIC_KPROBE = MSG_OP_GENERIC_KPROBE,
	ISO_MSG_OP_GENERIC_TRACEPOINT = MSG_OP_GENERIC_TRACEPOINT,
	ISO_MSG_OP_IPV4_TCPSTATS = 15,
	ISO_MSG_OP_HTTP = 16,

	ISO_MSG_OP_IPV4_UDPCONNECT = 18,
	ISO_MSG_OP_IPV4_UDPPAYLOAD = 21,

	ISO_MSG_OP_IPV4_PROCESS_BURST = 22,

	ISO_MSG_OP_CLONE = MSG_OP_CLONE,

	ISO_MSG_OP_MAX,

	ISO_MSG_OP_TEST = 254,
};
#endif // _ISO_MSG_TYPES_
