#ifndef _MSG_TYPES_
#define _MSG_TYPES_

/* Msg Types */
enum msg_ops {
	MSG_OP_UNDEF = 0,
	MSG_OP_IPV4_TCPCONNECT = 1,
	MSG_OP_IPV4_TCPCONNECTRET = 2,
	MSG_OP_IPV4_BIND = 3,
	MSG_OP_IPV4_LISTEN = 4,
	MSG_OP_EXECVE = 5,
	MSG_OP_TLS = 6,
	MSG_OP_EXIT = 7,
	MSG_OP_IPV4_TCPCLOSE = 8,
	MSG_OP_IPV4_TCPACCEPT = 9,
	MSG_OP_CREDS = 10,
	MSG_OP_KFREE_SKB = 11,
	MSG_OP_TLS_CONT = 12,
	MSG_OP_GENERIC_KPROBE = 13,
	MSG_OP_GENERIC_TRACEPOINT = 14,
	MSG_OP_IPV4_TCPSTATS = 15,
	MSG_OP_HTTP = 16,

	MSG_OP_IPV4_UDPCONNECT = 18,
	MSG_OP_IPV4_UDPPAYLOAD = 21,

	MSG_OP_IPV4_PROCESS_BURST = 22,

	MSG_OP_CLONE = 23,

	MSG_OP_MAX,

	// testing
	MSG_OP_TEST = 254,
};
#endif // _MSG_TYPES_
