{
 "title": "Tetragon / TCP Latency / Socket",
 "tags": [
  "Tetragon",
  "networking"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tetragon_events_total, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}, workload)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\"}, pod)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"}, node)"
    }
   },
   {
    "name": "binary",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\"}, binary)"
    }
   },
   {
    "name": "dstdns",
    "label": "remote DNS name",
    "query": {
     "query": "query_result(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"} or tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "SRTT Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SRTT [μs] histogram",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pkt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SRTT histogram over time",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (increase(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median SRTT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (increase(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 SRTT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (increase(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 SRTT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SRTT quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Latency Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency [μs] histogram",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "pkt" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (le) (increase(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency [μs] histogram over time",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by (le) (increase(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Median Latency",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (increase(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P90 Latency",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (le) (increase(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P95 Latency",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency quantiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])))",
       "legendFormat": "Median"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])))",
       "legendFormat": "P95"
      }
     ]
    }
   ]
  },
  {
   "title": "SRTT Quantiles by K8s Workload & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Median SRTT (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.5, sum by (le, namespace, workload, binary) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{namespace}}/{{workload}} > {{binary}}"
      }
     ]
    },
    {
     "title": "P90 SRTT (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.90, sum by (le, namespace, workload, binary) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{namespace}}/{{workload}} > {{binary}}"
      }
     ]
    },
    {
     "title": "P95 SRTT (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.95, sum by (le, namespace, workload, binary) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{namespace}}/{{workload}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Quantiles by K8s Workload & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Median Latency (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.5, sum by (le, namespace, workload, binary) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{namespace}}/{{workload}} > {{binary}}"
      }
     ]
    },
    {
     "title": "P90 Latency (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.9, sum by (le, namespace, workload, binary) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{namespace}}/{{workload}} > {{binary}}"
      }
     ]
    },
    {
     "title": "P95 Latency (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.95, sum by (le, namespace, workload, binary) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{namespace}}/{{workload}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SRTT Quantiles by Node & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Median SRTT (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.5, sum by (le, node, binary) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "P90 SRTT (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.9, sum by (le, node, binary) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "P95 SRTT (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.95, sum by (le, node, binary) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Quantiles by Node & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Median Latency (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.5, sum by (le, node, binary) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "P90 Latency (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.9, sum by (le, node, binary) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "P95 Latency (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.95, sum by (le, node, binary) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SRTT Quantiles by Remote DNS Name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Median SRTT (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.5, sum by (le, dstdns) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "P90 SRTT (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.9, sum by (le, dstdns) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "P95 SRTT (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.95, sum by (le, dstdns) (rate(tetragon_socket_stats_srtt_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Quantiles by Remote DNS Name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Median Latency (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.5, sum by (le, dstdns) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "P90 Latency (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.9, sum by (le, dstdns) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "P95 Latency (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.95, sum by (le, dstdns) (rate(tetragon_tcp_latency_microseconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    }
   ]
  }
 ]
}