# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/master/.golangci.yaml as a reference.
version: "2"
output:
  formats:
    tab:
      path: stdout
      colors: false
linters:
  default: none
  enable:
    - err113
    - goheader
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    goheader:
      template-path: ./COPYRIGHT
  exclusions:
    rules:
      - linters:
          - err113
        text: "do not define dynamic errors, use wrapped static errors instead"
      - linters:
          - revive
        text: "exported:"
      - linters:
          - revive
        text: "package-comments:"
      - linters:
          - revive
        text: "var-naming:"
    # for now excempt for follow up patches when I have some extra energy
    paths:
      - "pkg/nxos"
      - "pkg/proto"
      - "pkg/dpu/pensando"
      - "pkg/grpc/haclt"
      - "pkg/grpc/hasvr"
      - "pkg/metrics/opcodemetrics"
      - "pkg/aggregator"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
      - github.com/isovalent/hubble-fgs
run:
  build-tags:
    - e2e_tests
    - sudo_tests
