FROM ubuntu:jammy@sha256:6042500cf4b44023ea1894effe7890666b0c5c7871ed83a97c36c76ae560bb9b

RUN apt-get -y update
RUN apt-get -y install clang-format-15
RUN ln -s /bin/clang-format-15 /bin/clang-format

USER 1000
WORKDIR /fgs

ENTRYPOINT ["clang-format"]
CMD ["--help"]
