FROM quay.io/isovalent/hubble-llvm:2022-01-03-a6dfdaf as bpf-builder
WORKDIR /go/src/github.com/isovalent/hubble-fgs
RUN apt-get update  -y && \
    apt-get upgrade -y && \
    apt-get install -y linux-libc-dev
COPY . ./
RUN make hubble-bpf

FROM quay.io/cilium/cilium-bpftool AS bpftool
COPY . ./


FROM golang:1.16
RUN apt-get update -y &&    \
    apt-get upgrade -y &&   \
    apt-get install -y      \
	linux-libc-dev      \
	rpm2cpio            \
	cpio                \
	git                 \
	flex                \
	bison               \
	autoconf            \
	libelf-dev          \
	libcap-dev          \
	bc                  \
	netcat-traditional  \
	vim                 \
	file                \
	strace              \
	jq                  \
	less
COPY --from=bpf-builder /go/src/github.com/isovalent/hubble-fgs/bpf/objs/*.o /var/lib/hubble-fgs/
COPY --from=bpftool  /bin/bpftool /usr/bin/
WORKDIR /go/src/github.com/isovalent/hubble-fgs
COPY . ./
RUN make hubble-fgs hubble-enterprise test-compile tester-progs


ENV FGS_PROCFS=/procRoot/
# CMD ["sh", "-c", "/go/src/github.com/isovalent/hubble-fgs/hubble-fgs --procfs=/procRoot/ --export-filename=/tmp/hubble-fgs.log --metrics-server :2112 --tls --tlstc --verbose 4"]
CMD ["sh", "-c", "/go/src/github.com/isovalent/hubble-fgs/hubble-fgs --procfs=/procRoot/"]
