FROM isovalent/tetragon-slim:latest AS tetragon-slim-release

FROM scratch AS linux-tarball-1

# Copy install script
COPY install/linux-tarball/install.sh /
COPY install/linux-tarball/uninstall.sh /

# COPY configurations
COPY install/linux-tarball/usr /usr

# Copy the systemd service file
COPY install/linux-tarball/systemd/tetragon-enterprise.service /usr/lib/systemd/system/

# Make a copy of the systemd resources into our location
COPY install/linux-tarball/systemd /usr/local/lib/tetragon/systemd

# Our binaries
COPY --from=tetragon-slim-release /usr/bin/tetrabox /usr/local/bin/

# BPF files and tetragon-fs-scanner
COPY --from=tetragon-slim-release /var/lib/tetragon /usr/local/lib/tetragon/bpf

# make symbolic links
RUN --mount=type=bind,from=alpine,source=/bin,target=/bin \
    --mount=type=bind,from=alpine,source=/lib,target=/lib \
	ln -s /usr/local/bin/tetrabox /usr/local/bin/tetragon && \
	ln -s /usr/local/bin/tetrabox /usr/local/bin/tetra    && \
	rm /usr/local/lib/tetragon/bpf/tetragon-fs-scanner    && \
	ln -s /usr/local/bin/tetrabox /usr/local/lib/tetragon/bpf/tetragon-fs-scanner

# We need one layer
FROM scratch AS linux-tarball-2

ARG TETRAGON_VERSION
ARG TARGET_ARCH

# We explicitly prefix the filesystem with tetragon-slim-${TETRAGON_VERSION}-${TARGET_ARCH}
COPY --from=linux-tarball-1 / /tetragon-slim-${TETRAGON_VERSION}-${TARGET_ARCH}/
