FROM isovalent/hubble-fgs:latest as hubble-fgs-release

FROM scratch as linux-tarball-1

# Copy install script
COPY install/linux-tarball/install.sh /
COPY install/linux-tarball/uninstall.sh /

# COPY configurations
COPY install/linux-tarball/usr /usr

# Copy the systemd service file
COPY install/linux-tarball/systemd/tetragon-enterprise.service /usr/lib/systemd/system/

# Make a copy of the systemd resources into our location
COPY install/linux-tarball/systemd /usr/local/lib/hubble-fgs/systemd

# Our binaries
COPY --from=hubble-fgs-release /usr/bin/hubble-fgs /usr/local/bin/
COPY --from=hubble-fgs-release /usr/bin/hubble-enterprise /usr/local/bin/
COPY --from=hubble-fgs-release /usr/bin/hubble-enterprise /usr/local/bin/hubble-fgs-printer

# Helper binaries
COPY --from=hubble-fgs-release /usr/bin/bpftool /usr/local/lib/hubble-fgs/bpftool

# BPF files and hubble-fgs-fs-scanner
COPY --from=hubble-fgs-release /var/lib/hubble-fgs /usr/local/lib/hubble-fgs/bpf

# We need one layer
FROM scratch as linux-tarball-2

ARG HUBBLE_FGS_VERSION
ARG TARGET_ARCH

# We explicitly prefix the filesystem with hubble-fgs-${HUBBLE_FGS_VERSION}-${TARGET_ARCH}
COPY --from=linux-tarball-1 / /hubble-fgs-${HUBBLE_FGS_VERSION}-${TARGET_ARCH}/
