FROM quay.io/isovalent/hubble-llvm:2022-01-03-a6dfdaf as bpf-builder
WORKDIR /go/src/github.com/isovalent/hubble-fgs
RUN apt update
RUN apt install -y linux-libc-dev
COPY . ./
RUN make hubble-bpf

FROM quay.io/cilium/cilium-builder:b7a9dcdcadd77d38db87bbd06b9bc238e9dab5a0@sha256:eecc017a6ccf0c7884f1ffcf10e58462a272f5e41c0ece09adb351e8839e3157 as hubble-builder
WORKDIR /go/src/github.com/isovalent/hubble-fgs
RUN apt-get update && apt-get install -y libelf-dev zlib1g-dev
COPY . ./
RUN make hubble-fgs-image

FROM quay.io/isovalent/hubble-fgs-bins:latest as hubble-fgs-btf
WORKDIR /go/src/github.com/isovalent/hubble-fgs
COPY . ./
RUN mkdir bins && \
    cp /var/run/hubble-fgs/* ./bins/

FROM docker.io/library/alpine:3.12
RUN addgroup hubble	       && \
    mkdir /var/lib/hubble-fgs/ && \
    mkdir /var/run/hubble-fgs/ && \
    mkdir libs		       && \
    apk add --no-cache bash curl grep jq
COPY --from=hubble-builder /go/src/github.com/isovalent/hubble-fgs/hubble-fgs /usr/bin/
COPY --from=hubble-builder /go/src/github.com/isovalent/hubble-fgs/hubble-enterprise /usr/bin/
COPY --from=bpf-builder /go/src/github.com/isovalent/hubble-fgs/bpf/objs/*.o /var/lib/hubble-fgs/
COPY --from=hubble-fgs-btf /go/src/github.com/isovalent/hubble-fgs/bins/* /var/lib/hubble-fgs/
RUN ln -s /usr/bin/hubble-enterprise /usr/bin/hubble-fgs-printer
CMD ["sh", "-c", "/usr/bin/hubble-fgs"]
