FROM ubuntu:noble@sha256:dfc10878be8d8fc9c61cbff33166cb1d1fe44391539243703c72766894fa834a

RUN apt-get -y update
RUN apt-get -y install clang-format-15
RUN ln -s /bin/clang-format-15 /bin/clang-format

USER 1000
WORKDIR /fgs

ENTRYPOINT ["clang-format"]
CMD ["--help"]
