FROM quay.io/isovalent/hubble-llvm:2022-01-03-a6dfdaf as bpf-builder

WORKDIR /go/src/github.com/isovalent/hubble-fgs
RUN apt update
RUN apt install -y linux-libc-dev
COPY . ./
RUN make hubble-bpf && pwd

FROM quay.io/isovalent/hubble-libbpf:v0.2.3 as hubble-libbpf
WORKDIR /go/src/github.com/isovalent/hubble-fgs
COPY . ./

FROM docker.io/library/golang:1.17.6@sha256:204c2e4637f7bcd0ebb32886d6f2d03f2deda92cf2f77e5a76746a77ff8c1de8
RUN apt update
RUN apt install -y linux-libc-dev rpm2cpio cpio git flex bison autoconf libelf-dev bc netcat-traditional
WORKDIR /go/src/github.com/isovalent/hubble-fgs
COPY --from=bpf-builder /go/src/github.com/isovalent/hubble-fgs/bpf/objs/*.o /var/lib/hubble-fgs/
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0.2.0 /usr/local/lib/
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0 /usr/local/lib/
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so /usr/local/lib/
CMD LD_LIBRARY_PATH=/usr/local/lib/ go test ./pkg/observer/

ENV FGS_BTF=/var/lib/hubble-fgs/btf
ENV FGS_PROCFS=/procRoot/
ENV LD_LIBRARY_PATH=/usr/local/lib/
