# First collect gmni used for testing
FROM --platform=$BUILDPLATFORM ghcr.io/openconfig/gnmic:0.42.1@sha256:3e135878f555772653a278742d2c7460b47c20e2907e07f611ecf4cc5a2261cf AS gnmic
ARG TARGETARCH

# Second builder (cross-)compile:
# - agw 
# - agwctl 
FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.0@sha256:c83e68f3ebb6943a2904fa66348867d108119890a2c6a2e6f07b38d0eb6c25c5 AS agw-builder
WORKDIR /go/src/github.com/isovalent/hubble-fgs
ARG TARGETARCH BUILDARCH
RUN apt-get update && apt-get upgrade -y
RUN if [ $BUILDARCH != $TARGETARCH ]; \
    then apt-get install -y libelf-dev zlib1g-dev crossbuild-essential-$TARGETARCH; \
    else apt-get install -y libelf-dev zlib1g-dev; fi
RUN ldconfig /usr/local/
COPY . ./
RUN if [ $BUILDARCH != $TARGETARCH ]; \
    then make agw agwctl TARGET_ARCH=$TARGETARCH CC=aarch64-linux-gnu-gcc; \
    else make agw agwctl TARGET_ARCH=$TARGETARCH; fi
RUN apt-get autoremove -y && apt-get clean

# Third builder (cross-)compile a stripped gops
FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.0-alpine@sha256:d4c4845f5d60c6a974c6000ce58ae079328d03ab7f721a0734277e69905473e5 AS gops
ARG TARGETARCH
RUN apk update && apk upgrade && apk add --no-cache binutils git \
 && git clone https://github.com/google/gops /go/src/github.com/google/gops \
 && cd /go/src/github.com/google/gops \
 && git checkout -b v0.3.27 v0.3.27 \
 && GOARCH=$TARGETARCH go build -ldflags="-s -w" .
RUN apk cache clean

# Final step run on target platform
FROM docker.io/library/alpine:3.22.2@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412 AS base-build
RUN apk update && apk upgrade --no-cache
# John cut these: iptables tcpdump vim-tiny and replaced ntp->chrony cron->cronie
RUN apk del openntpd
RUN apk add --no-cache net-tools iproute2 netcat-openbsd curl openssh-client bind-tools iputils-ping logrotate cronie sshpass bash ntpsec ca-certificates openssl
# Update CA certs
RUN update-ca-certificates
RUN apk cache clean
RUN mkdir -p /usr/src/app
RUN mkdir -p /opt/cisco/daf/etc
RUN mkdir -p /opt/cisco/daf/log
RUN mkdir -p /opt/cisco/hypershield/etc
RUN mkdir -p /etc/ssl/certs
RUN mkdir -p /data/volatile
RUN mkdir -p /iox_data
RUN mkdir -p /iox_data/isovalent/policy
WORKDIR /usr/src/app
#COPY --from=gnmic /app/gnmic ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/agw ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/agwctl ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/agwctl.sh ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/health.sh ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/post.sh ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/cleanup.sh ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/init.sh ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/policy-allowall.json ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/dafconfig /opt/cisco/daf/etc
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/ntp.conf /etc/ntpsec
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/crontab ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/logrotate.hs /etc/logrotate.d/hs
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/restart-fwa.sh ./
RUN chmod 600 /etc/logrotate.d/hs
EXPOSE 8880 8881 8882
ENTRYPOINT ["./init.sh"]

# Test container for headless testing (no NXOS dependencies)
# It container env vars for all AGW configuration flags, which can be overwritten at runtime
FROM docker.io/library/alpine:3.22.2@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412 AS agw-test
ENV AGW_CONFIG="" \
    AGW_NETWORK_POLICY="" \
    AGW_ENABLE_K8S="false" \
    AGW_ENABLE_NXOS="false" \
    AGW_DPU_SERVER_ADDRESS="0.0.0.0:8880" \
    AGW_VRF_MAP="" \
    AGW_DEBUG="false" \
    AGW_K8S_SERVICE_ACCOUNT_AUTH="" \
    AGW_TIMESCAPE_CLIENT_ENABLE="false" \
    AGW_TIMESCAPE_PASSWORD="" \
    AGW_TIMESCAPE_ENDPOINT=""
RUN apk update && apk upgrade --no-cache
EXPOSE 8880
WORKDIR /usr/src/app
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/agw ./
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/agwctl ./
RUN mkdir -p /opt/cisco/daf/etc
RUN mkdir -p /iox_data
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/dafconfig /opt/cisco/daf/etc
COPY --from=agw-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/test-entrypoint.sh /usr/src/app/entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
