FROM quay.io/isovalent/hubble-llvm:2020-02-25 as bpf-builder
WORKDIR /go/src/github.com/covalentio/hubble-fgs
COPY . ./
RUN apt update
RUN apt install -y linux-libc-dev
RUN make hubble-bpf

FROM quay.io/isovalent/hubble-libbpf:v0.2.1 as hubble-libbpf
WORKDIR /go/src/github.com/covalentio/hubble-fgs
COPY . ./

FROM quay.io/cilium/cilium-builder:2019-09-04 as hubble-builder
WORKDIR /go/src/github.com/covalentio/hubble-fgs
COPY . ./
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0.2.0 /usr/local/lib/
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0 /usr/local/lib/
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so /usr/local/lib/
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.a /usr/local/lib/
RUN ldconfig /usr/local/; export LD_LIBRARY_PATH=/usr/local/lib/
RUN make hubble-fgs-image

FROM quay.io/isovalent/hubble-fgs-bins:latest as hubble-fgs-btf
WORKDIR /go/src/github.com/covalentio/hubble-fgs
COPY . ./
RUN mkdir bins && \
    cp /var/run/hubble-fgs/* ./bins/

FROM docker.io/library/alpine:3.12
RUN addgroup hubble	       && \
    mkdir /var/lib/hubble-fgs/ && \
    mkdir /var/run/hubble-fgs/ && \
    mkdir libs		       && \
    apk add --no-cache bash curl grep jq
COPY --from=hubble-builder /go/src/github.com/covalentio/hubble-fgs/hubble-fgs /usr/bin/
COPY --from=hubble-builder /go/src/github.com/covalentio/hubble-fgs/hubble-enterprise /usr/bin/
COPY --from=bpf-builder /go/src/github.com/covalentio/hubble-fgs/bpf/objs/*.o /var/lib/hubble-fgs/
COPY --from=hubble-fgs-btf /go/src/github.com/covalentio/hubble-fgs/bins/* /var/lib/hubble-fgs/
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0.2.0 /usr/local/lib/
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0 /usr/local/lib/
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so /usr/local/lib/
COPY --from=hubble-libbpf /go/src/github.com/covalentio/hubble-fgs/src/libbpf.a /usr/local/lib/
CMD ["sh", "-c", "/usr/bin/hubble-fgs --procfs=/procRoot/"]
