# This Dockerfile can be used to compile natively on amd64 and cross-compile on
# amd64 for arm64.
#
# It can technically build natively on arm64 and cross-compile on arm64 for
# amd64 but the steps involving the gcc cross compiler might need rework. It's
# assumed that if [ $BUILDARCH != $TARGETARCH ] we are cross-compiling from
# amd64 to arm64
#
# For help on Docker cross compilation see the following blogpost:
# https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

# renovate: datasource=docker depName=artifactory.devhub-cloud.cisco.com/sto-cg-docker/chainguard-base
ARG APK_IMAGE=artifactory.devhub-cloud.cisco.com/sto-cg-docker/chainguard-base:v20230214-2026.09.28
# renovate: datasource=docker depName=artifactory.devhub-cloud.cisco.com/sto-cg-docker/static
ARG BASE_IMAGE=artifactory.devhub-cloud.cisco.com/sto-cg-docker/static:latest-2026.09.24

# First builder (cross-)compile the BPF programs
FROM --platform=$BUILDPLATFORM quay.io/cilium/clang:969f95f8ef7923af36bf657ba6d4c65691f56882@sha256:ff83e52d3ea150b3d93e4ae40ae86620003ac3f6d91fe6e939dcc95469f83ff2 AS bpf-builder
WORKDIR /go/src/github.com/isovalent/hubble-fgs
RUN apt-get update && apt-get install -y linux-libc-dev gzip
COPY . ./
ARG TARGETARCH
ARG DEBUG
RUN make tetragon-bpf LOCAL_CLANG=1 TARGET_ARCH=$TARGETARCH DEBUG=$DEBUG
RUN apt-get install -y llvm && llvm-strip -g bpf/objs/*.o
RUN gzip bpf/objs/*.o

# Second builder (cross-)compile:
# - tetragon-fs-scanner (this one compiles a C program, so a gcc cross compiler is needed)
# - tetragon
# - tetra
# Using Debian golang image for cross-compilation support (needs apt-get for crossbuild-essential)
FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.27.1@sha256:f44f6e88636cfb311f9ebace870ded69d943f227bb3cb27d32ffd84ea18c43ea AS tetragon-builder
WORKDIR /go/src/github.com/isovalent/hubble-fgs
ARG TARGETARCH BUILDARCH
RUN apt-get update
RUN if [ $BUILDARCH != $TARGETARCH ]; \
    then apt-get install -y libelf-dev zlib1g-dev crossbuild-essential-$TARGETARCH; \
    else apt-get install -y libelf-dev zlib1g-dev; fi
RUN ldconfig /usr/local/
COPY . ./
RUN if [ $BUILDARCH != $TARGETARCH ]; \
    then make tetrabox TARGET_ARCH=$TARGETARCH CC=aarch64-linux-gnu-gcc; \
    else make tetrabox TARGET_ARCH=$TARGETARCH; fi

# Third builder (cross-)compile a stripped gops
# Chainguard go-dev image
# renovate: datasource=docker depName=artifactory.devhub-cloud.cisco.com/sto-cg-docker/go
FROM --platform=$BUILDPLATFORM artifactory.devhub-cloud.cisco.com/sto-cg-docker/go:v1.27.1-dev@sha256:6d22a8f256cda4b0c2a20447709e1ebe805546a7a3ea50fb889ec92e49c5fdb5 AS gops
ARG TARGETARCH
# Chainguard go-dev uses wolfi, install binutils and git via apk
RUN apk add --no-cache binutils git \
 && GOARCH=$TARGETARCH go build -ldflags="-s -w" .

# Install runtime APK dependencies into a clean rootfs so APK repository
# credentials from the builder image are not copied into final images.
FROM ${BASE_IMAGE} AS static-base
FROM ${APK_IMAGE} AS runtime-deps
COPY --from=static-base / /rootfs
RUN apk add --no-cache --no-commit-hooks --root /rootfs \
    bash \
    busybox \
    ca-certificates \
    glibc \
    ld-linux \
    libgcc \
    libstdc++ \
    openssl \
    && rm -rf /rootfs/etc/apk /rootfs/etc/apko.json \
    && rm -rf /rootfs/var/cache/apk/*

# Almost final step runs on target platform (might need emulation) and
# retrieves (cross-)compiled binaries from builders
FROM scratch AS release
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
USER root
COPY --from=runtime-deps /rootfs/ /
RUN addgroup -S hubble	       && \
    mkdir /var/lib/tetragon/ && \
    mkdir /var/run/tetragon/ && \
    mkdir libs		       && \
    mkdir -p /etc/tetragon/tetragon.conf.d/ && \
    mkdir -p /etc/tetragon/tetragon.tp.d/ && \
    mkdir -p /etc/tetragon/tetragon.policies.d/
COPY --from=tetragon-builder /go/src/github.com/isovalent/hubble-fgs/tetrabox /usr/bin/tetrabox
COPY --from=tetragon-builder /go/src/github.com/isovalent/hubble-fgs/bpf/objs/tetragon-runner /var/lib/tetragon/
COPY --from=bpf-builder /go/src/github.com/isovalent/hubble-fgs/bpf/objs/* /var/lib/tetragon/
RUN     ln -s /usr/bin/tetrabox /usr/bin/tetragon && \
	ln -s /usr/bin/tetrabox /usr/bin/tetra    && \
	ln -s /usr/bin/tetrabox /var/lib/tetragon/tetragon-fs-scanner
ENTRYPOINT ["/usr/bin/tetragon"]
