# This Dockerfile can be used to compile natively on amd64 and cross-compile on
# amd64 for arm64.
#
# It can technically build natively on arm64 and cross-compile on arm64 for
# amd64 but the steps involving the gcc cross compiler might need rework. It's
# assumed that if [ $BUILDARCH != $TARGETARCH ] we are cross-compiling from
# amd64 to arm64
#
# For help on Docker cross compilation see the following blogpost:
# https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

# renovate: datasource=docker depName=artifactory.devhub-cloud.cisco.com/sto-cg-docker/chainguard-base
ARG APK_IMAGE=artifactory.devhub-cloud.cisco.com/sto-cg-docker/chainguard-base:v20230214-2026.06.26
# renovate: datasource=docker depName=artifactory.devhub-cloud.cisco.com/sto-cg-docker/static
ARG BASE_IMAGE=artifactory.devhub-cloud.cisco.com/sto-cg-docker/static:latest-2026.07.09

# First builder (cross-)compile the BPF programs
FROM --platform=$BUILDPLATFORM quay.io/cilium/clang:b97f5b3d5c38da62fb009f21a53cd42aefd54a2f@sha256:e1c8ed0acd2e24ed05377f2861d8174af28e09bef3bbc79649c8eba165207df0 AS bpf-builder
WORKDIR /go/src/github.com/isovalent/hubble-fgs
RUN apt-get update && apt-get install -y linux-libc-dev gzip
COPY . ./
ARG TARGETARCH
ARG DEBUG
RUN make tetragon-bpf LOCAL_CLANG=1 TARGET_ARCH=$TARGETARCH DEBUG=$DEBUG
RUN apt-get install -y llvm && llvm-strip -g bpf/objs/*.o
RUN gzip bpf/objs/*.o

# Second builder (cross-)compile:
# - tetragon-fs-scanner (this one compiles a C program, so a gcc cross compiler is needed)
# - tetragon
# - tetra
# Using Debian golang image for cross-compilation support (needs apt-get for crossbuild-essential)
FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.5@sha256:63f132d58c1f589f0dcda584933a9bb44bfda1150f1506377f5a902f34d86033 AS tetragon-builder
WORKDIR /go/src/github.com/isovalent/hubble-fgs
ARG TARGETARCH BUILDARCH
RUN apt-get update
RUN if [ $BUILDARCH != $TARGETARCH ]; \
    then apt-get install -y libelf-dev zlib1g-dev crossbuild-essential-$TARGETARCH; \
    else apt-get install -y libelf-dev zlib1g-dev; fi
RUN ldconfig /usr/local/
COPY . ./
RUN if [ $BUILDARCH != $TARGETARCH ]; \
    then make tetrabox TARGET_ARCH=$TARGETARCH CC=aarch64-linux-gnu-gcc; \
    else make tetrabox TARGET_ARCH=$TARGETARCH; fi

# Third builder (cross-)compile a stripped gops
# Chainguard go-dev image
# renovate: datasource=docker depName=artifactory.devhub-cloud.cisco.com/sto-cg-docker/go
FROM --platform=$BUILDPLATFORM artifactory.devhub-cloud.cisco.com/sto-cg-docker/go:v1.26.5-dev@sha256:660959dbf4c86dc8828f83fdbbc0f4e202c9d9420aaa2196bf399bd554b135e5 AS gops
ARG TARGETARCH
# Chainguard go-dev uses wolfi, install binutils and git via apk
RUN apk add --no-cache binutils git \
 && GOARCH=$TARGETARCH go build -ldflags="-s -w" .

# Install runtime APK dependencies into a clean rootfs so APK repository
# credentials from the builder image are not copied into final images.
FROM ${BASE_IMAGE} AS static-base
FROM ${APK_IMAGE} AS runtime-deps
COPY --from=static-base / /rootfs
RUN apk add --no-cache --no-commit-hooks --root /rootfs \
    bash \
    busybox \
    ca-certificates \
    glibc \
    ld-linux \
    libgcc \
    libstdc++ \
    openssl \
    && rm -rf /rootfs/etc/apk /rootfs/etc/apko.json \
    && rm -rf /rootfs/var/cache/apk/*

# Almost final step runs on target platform (might need emulation) and
# retrieves (cross-)compiled binaries from builders
FROM scratch AS release
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
USER root
COPY --from=runtime-deps /rootfs/ /
RUN addgroup -S hubble	       && \
    mkdir /var/lib/tetragon/ && \
    mkdir /var/run/tetragon/ && \
    mkdir libs		       && \
    mkdir -p /etc/tetragon/tetragon.conf.d/ && \
    mkdir -p /etc/tetragon/tetragon.tp.d/ && \
    mkdir -p /etc/tetragon/tetragon.policies.d/
COPY --from=tetragon-builder /go/src/github.com/isovalent/hubble-fgs/tetrabox /usr/bin/tetrabox
COPY --from=tetragon-builder /go/src/github.com/isovalent/hubble-fgs/bpf/objs/tetragon-runner /var/lib/tetragon/
COPY --from=bpf-builder /go/src/github.com/isovalent/hubble-fgs/bpf/objs/* /var/lib/tetragon/
RUN     ln -s /usr/bin/tetrabox /usr/bin/tetragon && \
	ln -s /usr/bin/tetrabox /usr/bin/tetra    && \
	ln -s /usr/bin/tetrabox /var/lib/tetragon/tetragon-fs-scanner
ENTRYPOINT ["/usr/bin/tetragon"]
