FROM docker.io/library/golang:1.21.1-alpine@sha256:4bc6541af94a67d9dcabba9826c36e4e9497dacf4e8755ac503000b6ff75318f

RUN apk --update add bash unzip curl make

WORKDIR /go/src/github.com/isovalent/hubble-fgs
RUN --mount=type=bind,readwrite,target=/go/src/github.com/isovalent/hubble-fgs cd /go/src/github.com/isovalent/hubble-fgs/ && ./contrib/build/install-protoc.sh
RUN --mount=type=bind,readwrite,target=/go/src/github.com/isovalent/hubble-fgs cd /go/src/github.com/isovalent/hubble-fgs/modules/tetragon-oss && go install -buildvcs=false ./cmd/protoc-gen-go-tetragon

#- vi:ft=dockerfile -#
