FROM ubuntu:jammy@sha256:f9d633ff6640178c2d0525017174a688e2c1aef28f0a0130b26bd5554491f0da

RUN apt-get -y update
RUN apt-get -y install clang-format-15
RUN ln -s /bin/clang-format-15 /bin/clang-format

USER 1000
WORKDIR /fgs

ENTRYPOINT ["clang-format"]
CMD ["--help"]
