# Main builder (cross-)compile:
# - fwa
# - fwactl
FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.2@sha256:2a2b4b5791cea8ae09caecba7bad0bd9631def96e5fe362e4a5e67009fe4ae61 AS fwa-builder
WORKDIR /go/src/github.com/isovalent/hubble-fgs
ARG TARGETARCH BUILDARCH
RUN apt-get update && apt-get upgrade -y
RUN if [ $BUILDARCH != $TARGETARCH ]; \
    then apt-get install -y libelf-dev zlib1g-dev crossbuild-essential-$TARGETARCH; \
    else apt-get install -y libelf-dev zlib1g-dev; fi
RUN ldconfig /usr/local/
COPY . ./
RUN if [ $BUILDARCH != $TARGETARCH ]; \
    then make fwa fwactl TARGET_ARCH=$TARGETARCH CC=aarch64-linux-gnu-gcc; \
    else make fwa fwactl TARGET_ARCH=$TARGETARCH; fi
RUN apt-get autoremove -y && apt-get clean

# Third builder (cross-)compile a stripped gops
FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.2-alpine@sha256:c2a1f7b2095d046ae14b286b18413a05bb82c9bca9b25fe7ff5efef0f0826166 AS gops
ARG TARGETARCH
RUN apk update && apk upgrade && apk add --no-cache binutils git \
 && git clone https://github.com/google/gops /go/src/github.com/google/gops \
 && cd /go/src/github.com/google/gops \
 && git checkout -b v0.3.27 v0.3.27 \
 && GOARCH=$TARGETARCH go build -ldflags="-s -w" .
RUN apk cache clean

# Final step run on target platform
FROM docker.io/library/alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659 AS base-build
RUN apk update && apk upgrade --no-cache
RUN apk cache clean
RUN mkdir -p /usr/src/app
RUN mkdir -p /nic/conf/hypershield
WORKDIR /usr/src/app
COPY --from=fwa-builder /go/src/github.com/isovalent/hubble-fgs/fwa ./
COPY --from=fwa-builder /go/src/github.com/isovalent/hubble-fgs/fwactl ./
COPY --from=fwa-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/dafconfig /nic/conf/hypershield/firewall.json

# Test container for headless testing (no dataplane dependencies)
# It container env vars for all FWA configuration flags, which can be overwritten at runtime
FROM docker.io/library/alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659 AS fwa-test
ENV FWA_CONFIG="" \
    FWA_NETWORK_POLICY="" \
    FWA_ENABLE_DATAPLANE="false" \
    FWA_ENABLE_AGW="true" \
    FWA_ENABLE_LOGGER="false" \
    FWA_ENABLE_EVENT_STREAM="false" \
    FWA_SERVER_ADDRESS="127.0.0.1:8880" \
    FWA_DP_SOCKET_PATH="" \
    FWA_DEBUG="false"
RUN apk update && apk upgrade --no-cache && apk add --no-cache iproute2
WORKDIR /usr/src/app
COPY --from=fwa-builder /go/src/github.com/isovalent/hubble-fgs/fwa ./
COPY --from=fwa-builder /go/src/github.com/isovalent/hubble-fgs/fwactl ./
RUN mkdir -p /nic/conf/hypershield
COPY --from=fwa-builder /go/src/github.com/isovalent/hubble-fgs/install/agw/dafconfig /nic/conf/hypershield/firewall.json
COPY --from=fwa-builder /go/src/github.com/isovalent/hubble-fgs/install/fwa/test-entrypoint.sh /usr/src/app/entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
