FROM docker.io/library/golang:1.21.1-alpine@sha256:1c9cc949513477766da12bfa80541c4f24957323b0ee00630a6ff4ccf334b75b

RUN apk --update add bash unzip curl make

WORKDIR /go/src/github.com/isovalent/hubble-fgs
RUN --mount=type=bind,readwrite,target=/go/src/github.com/isovalent/hubble-fgs cd /go/src/github.com/isovalent/hubble-fgs/ && ./contrib/build/install-protoc.sh
RUN --mount=type=bind,readwrite,target=/go/src/github.com/isovalent/hubble-fgs cd /go/src/github.com/isovalent/hubble-fgs/modules/tetragon-oss && go install -buildvcs=false ./cmd/protoc-gen-go-tetragon

#- vi:ft=dockerfile -#
