FROM docker.io/library/golang:1.20.7-alpine@sha256:b255d9352ff4967f0424731acf5a262c3bb4b5bd712e6324ad9ed533c9d2aee7

RUN apk --update add bash unzip curl make

WORKDIR /go/src/github.com/isovalent/hubble-fgs
RUN --mount=type=bind,readwrite,target=/go/src/github.com/isovalent/hubble-fgs cd /go/src/github.com/isovalent/hubble-fgs/ && ./contrib/build/install-protoc.sh
RUN --mount=type=bind,readwrite,target=/go/src/github.com/isovalent/hubble-fgs cd /go/src/github.com/isovalent/hubble-fgs/modules/tetragon-oss && go install -buildvcs=false ./cmd/protoc-gen-go-tetragon

#- vi:ft=dockerfile -#
