# Copyright Isovalent Authors
# SPDX-License-Identifier: LicenseRef-Isovalent-Enterprise

# Chainguard go-dev image (includes shell, make, git via wolfi packages)
# renovate: datasource=docker depName=artifactory.devhub-cloud.cisco.com/sto-cg-docker/go
ARG GOLANG_IMAGE=artifactory.devhub-cloud.cisco.com/sto-cg-docker/go:v1.27.1-dev@sha256:6d22a8f256cda4b0c2a20447709e1ebe805546a7a3ea50fb889ec92e49c5fdb5

# Chainguard static image (replaces alpine)
# renovate: datasource=docker depName=artifactory.devhub-cloud.cisco.com/sto-cg-docker/static
ARG BASE_IMAGE=artifactory.devhub-cloud.cisco.com/sto-cg-docker/static:latest-2026.09.24

# BUILDPLATFORM is an automatic platform ARG enabled by Docker BuildKit.
# Represents the plataform where the build is happening, do not mix with
# TARGETARCH
FROM --platform=${BUILDPLATFORM} ${GOLANG_IMAGE} AS builder
# TARGETOS is an automatic platform ARG enabled by Docker BuildKit.
ARG TARGETOS
# TARGETARCH is an automatic platform ARG enabled by Docker BuildKit.
ARG TARGETARCH
WORKDIR /go/src/github.com/isovalent/hubble-fgs
RUN --mount=type=bind,readwrite,target=/go/src/github.com/isovalent/hubble-fgs \
    --mount=target=/root/.cache,type=cache \
    --mount=target=/go/pkg/mod,type=cache \
    make GOARCH=${TARGETARCH} tetragon-oci-hook tetragon-oci-hook-setup tetragon-nri-hook \
    && mkdir -p /out/${TARGETOS}/${TARGETARCH}/usr/bin \
    && mv ./tetragon-oci-hook       /out/${TARGETOS}/${TARGETARCH}/usr/bin \
    && mv ./tetragon-oci-hook-setup /out/${TARGETOS}/${TARGETARCH}/usr/bin \
    && mv ./tetragon-nri-hook       /out/${TARGETOS}/${TARGETARCH}/usr/bin

FROM ${BASE_IMAGE} AS static-base
FROM ${GOLANG_IMAGE} AS rootfs-cleaner
COPY --from=static-base / /rootfs
RUN apk add --no-commit-hooks --no-cache --root /rootfs busybox && \
    rm -rf /rootfs/etc/apk /rootfs/etc/apko.json /rootfs/var/cache/apk

FROM scratch AS release
# TARGETOS is an automatic platform ARG enabled by Docker BuildKit.
ARG TARGETOS
# TARGETARCH is an automatic platform ARG enabled by Docker BuildKit.
ARG TARGETARCH
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
COPY --from=rootfs-cleaner /rootfs/ /
COPY --from=builder /out/${TARGETOS}/${TARGETARCH}/usr/bin/tetragon-oci-hook       /usr/bin/
COPY --from=builder /out/${TARGETOS}/${TARGETARCH}/usr/bin/tetragon-oci-hook-setup /usr/bin/
COPY --from=builder /out/${TARGETOS}/${TARGETARCH}/usr/bin/tetragon-nri-hook       /usr/bin/
USER root
WORKDIR /
