ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
OSS_DIR := $(ROOT_DIR)/modules/tetragon-oss
CONTAINER_ENGINE ?= docker

# If you change GOPRIVATE, you also need to change:
# - contrib/build/depfix and
# - .github/workflows/renovate.yaml
GOPRIVATE := "github.com/isovalent"
GO ?= go
GO := GOPRIVATE=$(GOPRIVATE) $(GO)
CONTAINER_ENGINE ?= docker

BUF ?= buf
BUF_BREAKING_AGAINST_BRANCH ?= origin/master

# renovate: datasource=docker
BUILDER_IMAGE ?= quay.io/isovalent-dev/ipa-builder:v1.20.0-dev.108-20260907004600@sha256:be520893c7eb0995c342d28b091160b2291bea515403251fd1384b1b93f6f903
