ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
OSS_DIR := $(ROOT_DIR)/modules/tetragon-oss
CONTAINER_ENGINE ?= docker

# If you change GOPRIVATE, you also need to change:
# - contrib/build/depfix and
# - .github/workflows/renovate.yaml
GOPRIVATE := "github.com/isovalent"
GO ?= go
GO := GOPRIVATE=$(GOPRIVATE) $(GO)
CONTAINER_ENGINE ?= docker

BUF ?= buf
BUF_BREAKING_AGAINST_BRANCH ?= origin/master

# renovate: datasource=docker
BUILDER_IMAGE ?= quay.io/isovalent-dev/ipa-builder:v1.20.0-dev.53-20260710164520@sha256:80edabec51f34322b2e4c58275fa4c930949249cb2403baeda96ab0b3f017880
