DOCKER_IMAGE_TAG ?= latest
INDEX_DIR ?= catalog
IMAGE_REPOSITORY ?= quay.io/isovalent

##@ OLM index

.PHONY: olm-index-build
olm-index-build: ## Build the OLM catalog index image.
	$(CONTAINER_ENGINE) build -f ./install/olm/catalog.Dockerfile -t $(IMAGE_REPOSITORY)/tetragon-operator-index:v0.0.1 --build-arg INDEX_DIR=$(INDEX_DIR) ./install/olm

.PHONY: olm-index-push
olm-index-push: ## Push the OLM catalog index image.
	$(CONTAINER_ENGINE) push $(IMAGE_REPOSITORY)/tetragon-operator-index:v0.0.1

.PHONY: olm-index-add
olm-index-add: ## Add a bundle to the OLM catalog index image.
	DOCKER_IMAGE_TAG=$(DOCKER_IMAGE_TAG) IMAGE_REPOSITORY=$(IMAGE_REPOSITORY) INDEX_DIR=$(INDEX_DIR) ./install/olm/catalog-add.sh
