ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
OSS_DIR := $(ROOT_DIR)/modules/tetragon-oss
CONTAINER_ENGINE ?= docker

# If you change GOPRIVATE, you also need to change:
# - contrib/build/depfix and
# - .github/workflows/renovate.yaml
GOPRIVATE := "github.com/isovalent"
GO ?= go
GO := GOPRIVATE=$(GOPRIVATE) $(GO)
CONTAINER_ENGINE ?= docker

BUF ?= buf
BUF_BREAKING_AGAINST_BRANCH ?= origin/master

# renovate: datasource=docker
BUILDER_IMAGE ?= quay.io/isovalent-dev/ipa-builder:v1.20.0-dev.37-20260622011148@sha256:a453e55727395d3484c929cab85fd85bbcd1a7bfdbc12240e1bdd5121afd8b56
