DOCKER_IMAGE_TAG ?= latest
IMAGE_REPOSITORY ?= quay.io/isovalent

##@ OLM bundle

.PHONY: bundle-build
bundle-build: ## Build the bundle image.
	$(CONTAINER_ENGINE) build -f ./install/olm/bundle.Dockerfile -t $(IMAGE_REPOSITORY)/tetragon-operator-bundle:$(DOCKER_IMAGE_TAG) ./install/olm

.PHONY: bundle-push
bundle-push: ## Push the bundle image.
	$(CONTAINER_ENGINE) push $(IMAGE_REPOSITORY)/tetragon-operator-bundle:$(DOCKER_IMAGE_TAG)

