{
 "title": "Benchmarks Hubble-Enterprise",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  {
   "title": "Events/Sec",
   "type": "timeseries",
   "description": "events per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(type) (rate(tetragon_events_total{node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Event Ratios",
   "type": "piechart",
   "description": "Total events by type over interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(tetragon_events_total{node=~\"$node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enterprise CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"enterprise\",node=~\"$node\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enterprise Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"kube-system\",node=~\"$node\",pod=~\"hubble-enterprise.+\",container=\"enterprise\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost/Sec",
   "type": "gauge",
   "description": "events per second",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tetragon_ringbuf_perf_event_lost{node=~\"$node\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Bench CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"httperf-bench\",node=~\"$node\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP  Bench Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"default\",node=~\"$node\",pod=~\"httperf.+\",container=\"httperf-bench\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_max_usage_bytes{namespace=\"default\",node=~\"$node\",pod=~\"httperf.+\",container=\"httperf-bench\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX Bench CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"nginx-.+\",container=\"nginx\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX  Bench Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"default\",node=~\"$node\",pod=~\"nginx.+\",container=\"nginx\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_max_usage_bytes{namespace=\"default\",node=~\"$node\",pod=~\"nginx.+\",container=\"nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}