{
 "title": "Tetragon Debugging",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(tetragon_map_in_use_gauge, pod)"
    }
   },
   { "name": "node", "query": { "query": "label_values(node)" } },
   {
    "name": "loki",
    "label": "loki datasource",
    "query": "hubble-enterprise/hubble-enterprise"
   }
  ]
 },
 "panels": [
  {
   "title": "Go Routines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "UDP GC Runner",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(tetragon_socket_stats_udp_retrieve_total{node=~\"$node\", count=\"Ticker\"}[$__rate_interval])) * 60",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Map Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Map Sizes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "entries" } },
     "targets": [
      {
       "expr": "sum by(map) (tetragon_map_in_use_gauge{node=~\"$node\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Map Growth Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "entries/s" } },
     "targets": [
      {
       "expr": "sum by(map) (deriv(tetragon_map_in_use_gauge{node=~\"$node\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Tetragon Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events/Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "sum by(type) (rate(tetragon_events_total{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Event Ratios",
     "type": "piechart",
     "description": "Total events by type over interval",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by(type) (increase(tetragon_events_total{node=~\"$node\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Enterprise CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"tetragon\",node=~\"$node\"}[$__rate_interval]) * 100",
       "legendFormat": "{{node}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Enterprise Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container=\"tetragon\",node=~\"$node\"}",
       "legendFormat": "{{node}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Event Loss Rate",
     "type": "timeseries",
     "description": "Events lost per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "rate(tetragon_ringbuf_perf_event_lost_total{node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{node}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Total Events Lost",
     "type": "gauge",
     "description": "Total lost events over interval",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "floor(increase(tetragon_ringbuf_perf_event_lost_total{node=~\"$node\"}[$__range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Enterprise Pod Restarts",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "floor(sum by(pod) (increase(kube_pod_container_status_restarts_total{container=\"tetragon\", pod=~\"$pod\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Parser",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Queries/Replies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(response, rcodes) (rate(tetragon_dns_total{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{response}} ({{rcodes}})"
      }
     ]
    },
    {
     "title": "DNS Cache Misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "misses/s" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_dns_cache_misses_total{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "DNS Cache Evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "evictions/s" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_dns_cache_evictions_total{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Missing Destination Names TxBytes",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(binary) (rate(tetragon_socket_stats_txbytes_total{node=~\"$node\", dstdns=\"\", dstpod=\"\"}[$__rate_interval]) / 1024)",
       "legendFormat": "{{binary}}"
      }
     ]
    },
    {
     "title": "Missing Destination Names RxBytes",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(binary) (rate(tetragon_socket_stats_rxbytes_total{node=~\"$node\", dstdns=\"\", dstpod=\"\"}[$__rate_interval])) / 1024",
       "legendFormat": "{{binary}}"
      }
     ]
    },
    {
     "title": "Process Connect Events By Destination",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "count by(protocol, destination_name) (rate({job=\"$loki\", pod=~\"$pod\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\" | __error__=`` [$__interval]))",
       "legendFormat": "{{protocol}} {{destination_name}}"
      }
     ]
    },
    {
     "title": "Missing Destination Names Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "count by(protocol) (rate({job=\"$loki\", pod=~\"$pod\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\", destination_pod=\"process_connect.destination_pod.name\" | destination_name = `` | destination_pod = `` | __error__=`` [$__interval]))",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Missing TCP Destination Names By IP",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "events" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(destination_ip, binary) (count_over_time({job=\"$loki\", pod=~\"$pod\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\", destination_pod=\"process_connect.destination_pod.name\", binary=\"process_connect.process.binary\" | destination_name = `` | protocol = `TCP` | destination_pod = `` | __error__=`` [$__range]))",
       "legendFormat": "{{binary}} -> {{destination_ip}}"
      }
     ]
    },
    {
     "title": "Missing UDP Destination Names By IP",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "events" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(destination_ip, binary) (count_over_time({job=\"$loki\", pod=~\"$pod\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\", destination_pod=\"process_connect.destination_pod.name\", binary=\"process_connect.process.binary\" | destination_name = `` | destination_pod = `` | protocol = `UDP` | __error__=`` [$__range]))",
       "legendFormat": "{{binary}} -> {{destination_ip}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Parser",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "TLS Parser",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "TLS Parser Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "errors/s" } },
     "targets": [
      {
       "expr": "sum by(error, continuation) (rate(tetragon_tls_errors_total{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Percent Completed Continuations",
     "type": "timeseries",
     "description": "Ratio of expected continuation events to actual",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "tetragon_tls_expected_continutation_events_total{node=~\"$node\", pod=~\"$pod\"}",
       "legendFormat": "Expected"
      },
      {
       "expr": "tetragon_tls_actual_continutation_events_total{node=~\"$node\", pod=~\"$pod\"}",
       "legendFormat": "Actual"
      }
     ]
    },
    {
     "title": "TLS Errors Total",
     "type": "gauge",
     "description": "Total TLS errors over interval.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(error, continuation) (increase(tetragon_tls_errors_total{pod=~\"$pod\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TLS Cipher Suites",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "sum by(cipher) (rate(tetragon_tls_handshakes_total{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "TLS SNI Names",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "sum by(sni_name) (rate(tetragon_tls_handshakes_total{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "TLS Versions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "sum by(version) (rate(tetragon_tls_handshakes_total{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "L3/L7 Health Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "L3/L7 Events Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "sum by(type) (rate(tetragon_events_total{node=~\"$node\", type=~\"PROCESS_CONNECT|PROCESS_ACCEPT|PROCESS_CLOSE|PROCESS_LISTEN|PROCESS_DNS|PROCESS_HTTP|TLS|PROCESS_TLS|PROCESS_SOCKSTATS\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Layer 3 Errors Summary",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Errors/Minute" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_layer3_event_errors_total{node=~\"$node\"}[$__rate_interval])) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Layer 3 Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "errors/s" } },
     "targets": [
      {
       "expr": "sum by(error) (rate(tetragon_layer3_event_errors_total{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}