{
 "title": "Tetragon DNS",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tetragon_events_total, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}, workload)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\"}, pod)"
    }
   },
   {
    "name": "binary",
    "query": {
     "query": "label_values(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\",pod=~\"$pod\"}, binary)\n"
    }
   },
   { "name": "topk", "query": "10" },
   {
    "name": "topk_names",
    "query": {
     "query": "query_result(topk($topk, sum by(names) (avg_over_time(tetragon_dns_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", binary=~\"$binary\"}[$__range]))))"
    }
   },
   {
    "name": "topk_name_errors",
    "query": {
     "query": "query_result(topk($topk, sum by(names) (avg_over_time(tetragon_dns_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", binary=~\"$binary\",rcodes=\"NameError\"}[$__range]))))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests and Responses Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Requests And Responses Rate (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(response) (rate(tetragon_dns_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\",binary=~\"$binary\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Codes Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(rcodes) (rate(tetragon_dns_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", binary=~\"$binary\", response=\"Response\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests : Responses Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(response) (rate(tetragon_dns_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\",binary=~\"$binary\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Codes Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(rcodes) (tetragon_dns_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", binary=~\"$binary\", response=\"Response\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DNS Names Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "DNS Names (top k=$topk)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(names) (tetragon_dns_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", binary=~\"$binary\", names=~\"$topk_names\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tetragon_dns_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", binary=~\"$binary\", names!~\"$topk_names\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "DNS Names Request Rate (top k=$topk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(names) (rate(tetragon_dns_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", binary=~\"$binary\", names=~\"$topk_names\", response=~\"Request\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NameError Rate (top k=$topk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(names) (rate(tetragon_dns_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", binary=~\"$binary\", names=~\"$topk_name_errors\", response=~\"Response\", rcodes=\"NameError\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}