{
 "title": "(WIP Natalia) \"kubectl exec\" Audit Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "Workload",
    "query": {}
   },
   { "name": "ContainerRuntime", "query": "/usr/sbin/runc" }
  ]
 },
 "panels": [
  {
   "title": "Malicious \"kubectl exec\" events (per namespace)",
   "type": "gauge",
   "description": "Monitoring the /usr/bin/bash, /usr/bin/sh, /bin/bash or /bin/sh binary executions in the appropriate Kubernetes workloads",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\",job=\"fgs_log\"} |~\"process_exec\" |~\"$namespace\" | json | process_exec_parent_binary=`$ContainerRuntime` and process_exec_parent_pid != 1 [1h])) by (process_exec_process_pod_workload)",
     "legendFormat": "{{process_exec_process_pod_workload}}"
    }
   ]
  },
  {
   "title": "Runtime Events (per pod)",
   "type": "bargauge",
   "description": "Monitoring the /usr/bin/bash, /usr/bin/sh, /bin/bash or /bin/sh binary executions in the appropriate Kubernetes workloads",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\",job=\"fgs_log\"} |~\"process_exec\" |~\"$namespace\" |~\"$Workload\" | json | (process_exec_parent_binary=`/bin/sh` or process_exec_parent_binary=`/usr/bin/sh` or process_exec_parent_binary=`/bin/bash` or process_exec_parent_binary=`/usr/bin/bash`) or (process_exec_parent_binary=`$ContainerRuntime` and process_exec_parent_pid != 1) [1h])) by (process_exec_process_pod_workload)",
     "legendFormat": "{{process_exec_pod_workload}}"
    }
   ]
  },
  {
   "title": "Networking Events (per pod)",
   "type": "bargauge",
   "description": "Monitoring the /usr/bin/bash, /usr/bin/sh, /bin/bash or /bin/sh binary executions in the appropriate Kubernetes workloads",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\",job=\"fgs_log\"} |~\"process_connect\" |~\"$namespace\" |~\"$Workload\" | json | (process_connect_parent_binary=`/bin/sh` or process_connect_parent_binary=`/usr/bin/sh` or process_connect_parent_binary=`/bin/bash` or process_connect_parent_binary=`/usr/bin/bash`) or (process_connect_parent_binary=`$ContainerRuntime` and process_connect_parent_pid != 1) [1h])) by (process_connect_process_pod_workload)",
     "legendFormat": "{{process_connect_process_workload}}"
    }
   ]
  },
  {
   "title": "File Integrity Monitoring Events (per pod)",
   "type": "bargauge",
   "description": "Monitoring the /usr/bin/bash, /usr/bin/sh, /bin/bash or /bin/sh binary executions in the appropriate Kubernetes workloads",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\",job=\"fgs_log\"} |~\"process_file\" |~\"$namespace\" |~\"$Workload\" | json | (process_file_parent_binary=`/bin/sh` or process_file_parent_binary=`/usr/bin/sh` or process_file_parent_binary=`/usr/bin/bash` or process_file_parent_binary=`/bin/bash`) or (process_file_parent_binary=`$ContainerRuntime` and process_file_parent_pid != 1) [1h])) by (process_file_process_pod_workload)",
     "legendFormat": "{{process_file_process_pod_workload}}"
    }
   ]
  },
  {
   "title": "Malicious \"kubectl exec\" events (per namespace)",
   "type": "table",
   "description": "Monitoring the /usr/bin/bash, /usr/bin/sh, /bin/bash or /bin/sh binary executions in the appropriate Kubernetes workloads",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\",job=\"fgs_log\"} |~\"process_exec\" |~\"$namespace\" | json | process_exec_parent_binary=`/usr/sbin/runc` and process_exec_parent_pid != 1"
    }
   ]
  },
  {
   "title": "Malicious \"kubectl exec\" child processes (per pod)",
   "type": "table",
   "description": "Monitoring the /usr/bin/bash, /usr/bin/sh, /bin/bash or /bin/sh binary executions in the appropriate Kubernetes workloads",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\",job=\"fgs_log\"} |~\"process_exec\" |~\"$namespace\" |~\"$Workload\" | json | process_exec_parent_binary=`/usr/sbin/runc` and process_exec_parent_pid != 1"
    }
   ]
  },
  {
   "title": "Sensitive File Names (per pod)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\",job=\"fgs_log\"} |~\"process_file\" |~\"$namespace\" |~\"$Workload\" | json | (process_file_parent_binary=`/bin/sh` or process_file_parent_binary=`/usr/bin/sh` or process_file_parent_binary=`/usr/bin/bash` or process_file_parent_binary=`/bin/bash`) or (process_file_parent_binary=`/usr/sbin/runc` and process_file_parent_pid != 1) [1h])) by (process_file_args_generic_arg_file_str)",
     "legendFormat": "{{process_file_args_generic_arg_file_str}}"
    }
   ]
  },
  {
   "title": "Sensitive File Access (per pod)",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 23 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\",job=\"fgs_log\"} |~\"process_file\" |~\"$namespace\" |~\"$Workload\" | json | (process_file_parent_binary=`/bin/sh` or process_file_parent_binary=`/usr/bin/sh` or process_file_parent_binary=`/usr/bin/bash` or process_file_parent_binary=`/bin/bash`) or (process_file_parent_binary=`/usr/sbin/runc` and process_file_parent_pid != 1) "
    }
   ]
  }
 ]
}