{
 "title": "Tetragon L7 Parser Debugging",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(tetragon_map_in_use_gauge, pod)"
    }
   },
   { "name": "node", "query": { "query": "label_values(node)" } },
   {
    "name": "loki",
    "label": "loki datasource",
    "query": "hubble-enterprise/hubble-enterprise"
   }
  ]
 },
 "panels": [
  { "title": "Tetragon Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events/Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "events/s" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(tetragon_events_total{node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Event Ratios",
   "type": "piechart",
   "description": "Total events by type over interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(tetragon_events_total{node=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enterprise CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"enterprise\",node=~\"$node\"}[$__rate_interval]) * 100",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Enterprise Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"hubble-enterprise\",pod=~\"hubble-enterprise.+\",container=\"enterprise\",node=~\"$node\"}",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Event Loss Rate",
   "type": "timeseries",
   "description": "Events lost per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "events/s" } },
   "targets": [
    {
     "expr": "rate(tetragon_ringbuf_perf_event_lost{node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Total Events Lost",
   "type": "gauge",
   "description": "Total lost events over interval",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tetragon_ringbuf_perf_event_lost{node=~\"$node\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Enterprise Pod Restarts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(kube_pod_container_status_restarts_total{namespace=\"hubble-enterprise\", container=\"enterprise\", pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DNS Parser", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "DNS Queries/Replies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(response, rcodes) (rate(tetragon_dns_total{node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{response}} ({{rcodes}})"
    }
   ]
  },
  {
   "title": "DNS Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "misses/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_dns_cache_misses{node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "DNS Cache Evictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "evictions/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_dns_cache_evictions{node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Missing Destination Names TxBytes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by(binary) (rate(tetragon_socket_stats_txbytes{node=~\"$node\", dstdns=\"\", dstpod=\"\"}[$__rate_interval]) / 1024)",
     "legendFormat": "{{binary}}"
    }
   ]
  },
  {
   "title": "Missing Destination Names RxBytes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by(binary) (rate(tetragon_socket_stats_rxbytes{node=~\"$node\", dstdns=\"\", dstpod=\"\"}[$__rate_interval])) / 1024",
     "legendFormat": "{{binary}}"
    }
   ]
  },
  {
   "title": "Process Connect Events By Destination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "events/s" } },
   "targets": [
    {
     "expr": "count by(protocol, destination_name) (rate({job=\"$loki\", pod=~\"$pod\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\" | __error__=`` [$__interval]))",
     "legendFormat": "{{protocol}} {{destination_name}}"
    }
   ]
  },
  {
   "title": "Missing Destination Names Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "events/s" } },
   "targets": [
    {
     "expr": "count by(protocol) (rate({job=\"$loki\", pod=~\"$pod\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\", destination_pod=\"process_connect.destination_pod.name\" | destination_name = `` | destination_pod = `` | __error__=`` [$__interval]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Missing TCP Destination Names By IP",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(destination_ip, binary) (count_over_time({job=\"$loki\", pod=~\"$pod\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\", destination_pod=\"process_connect.destination_pod.name\", binary=\"process_connect.process.binary\" | destination_name = `` | protocol = `TCP` | destination_pod = `` | __error__=`` [$__range]))",
     "legendFormat": "{{binary}} -> {{destination_ip}}"
    }
   ]
  },
  {
   "title": "Missing UDP Destination Names By IP",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(destination_ip, binary) (count_over_time({job=\"$loki\", pod=~\"$pod\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\", destination_pod=\"process_connect.destination_pod.name\", binary=\"process_connect.process.binary\" | destination_name = `` | destination_pod = `` | protocol = `UDP` | __error__=`` [$__range]))",
     "legendFormat": "{{binary}} -> {{destination_ip}}"
    }
   ]
  },
  { "title": "HTTP Parser", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  { "title": "TLS Parser", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  { "title": "L3/L7 Health Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "L3/L7 Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "events/s" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(tetragon_events_total{node=~\"$node\", type=~\"PROCESS_CONNECT|PROCESS_ACCEPT|PROCESS_CLOSE|PROCESS_LISTEN|PROCESS_DNS|PROCESS_HTTP|TLS|PROCESS_TLS|PROCESS_SOCKSTATS\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Layer 3 Errors Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "Errors/Minute" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_layer3_event_errors{node=~\"$node\"}[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Layer 3 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "errors/s" } },
   "targets": [
    {
     "expr": "sum by(error) (rate(tetragon_layer3_event_errors{node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}