{
 "title": "Multicast",
 "description": "Multicast Dashboard",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "dstmcast", "label": "dstmcast", "query": { "query": "label_values(dstmcast)" } },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Source Multicast TXBytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(isovalent_socket_stats_udp_mcast_txbytes{dstmcast =~ \"$dstmcast\", namespace=~\"$namespace\"}[$__rate_interval]) >0",
     "legendFormat": "{{pod}} > {{binary}} {{srcmcast}} {{dstmcast}}"
    }
   ]
  },
  {
   "title": "Destination Multicast RXBytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(isovalent_socket_stats_udp_mcast_rxbytes{srcmcast =~ \"$dstmcast\", namespace=~\"$namespace\"}[$__rate_interval])>0",
     "legendFormat": "{{binary}} {{srcmcast}} {{dstmcast}}"
    }
   ]
  },
  {
   "title": "Source Multicast TX Segments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(isovalent_socket_stats_udp_mcast_txsegs{dstmcast =~ \"$dstmcast\", namespace=~\"$namespace\"}[$__rate_interval])>0",
     "legendFormat": "{{pod}} {{binary}} {{srcmcast}} {{dstmcast}}"
    }
   ]
  },
  {
   "title": "Destination Multicast RXSegments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(isovalent_socket_stats_udp_mcast_rxsegs{srcmcast =~ \"$dstmcast\", namespace=~\"$namespace\"}[$__rate_interval])>0",
     "legendFormat": "{{pod}} {{binary}} {{srcmcast}} {{dstmcast}}"
    }
   ]
  },
  {
   "title": "Source Multicast RX Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(isovalent_socket_stats_udp_mcast_rxbytes{dstmcast =~ \"$dstmcast\", namespace=~\"$namespace\"}[$__rate_interval])>0",
     "legendFormat": "{{pod}} {{binary}} {{dstmcast}}"
    }
   ]
  },
  {
   "title": "Destination Multicast TX  Bytes ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(isovalent_socket_stats_udp_mcast_txbytes{srcmcast =~ \"$dstmcast\", namespace=~\"$namespace\"}[$__rate_interval])>0",
     "legendFormat": "{{pod}} {{binary}} {{srcmcast}}"
    }
   ]
  },
  {
   "title": "Source Multicast RX Segments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(isovalent_socket_stats_udp_mcast_rxsegs{dstmcast =~ \"$dstmcast\", namespace=~\"$namespace\"}[$__rate_interval])>0",
     "legendFormat": "{{pod}} {{binary}} {{dstmcast}}"
    }
   ]
  },
  {
   "title": "Destination Multicast TX  Segments ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(isovalent_socket_stats_udp_mcast_txbytes{srcmcast =~ \"$dstmcast\", namespace=~\"$namespace\"}[$__rate_interval])>0",
     "legendFormat": "{{pod}} {{binary}} {{srcmcast}}"
    }
   ]
  },
  {
   "title": "TX Multicast Bursts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bursts/sec" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(isovalent_socket_stats_udp_txbursts{pod!=\"\", namespace=~\"$namespace\"}[5m])))>0",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  },
  {
   "title": "RX Multicast Bursts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bursts/sec" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(isovalent_socket_stats_udp_txbursts{pod!=\"\", namespace=~\"$namespace\"}[5m])))>0",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  }
 ]
}