{
 "title": "Network Interface Metrics",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(isovalent_interface_txbytes,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(isovalent_interface_txbytes{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(isovalent_interface_txbytes{cluster=~\"$cluster\",namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "interface",
    "label": "interface",
    "query": {
     "query": "label_values(isovalent_interface_txbytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Egress per Namespace",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(isovalent_interface_txbytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Interface TX/RX Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Network Interface TX Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(isovalent_interface_txbytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface RX Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(isovalent_interface_rxbytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface TX Segments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(isovalent_interface_txsegs{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface RX Segments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(isovalent_interface_rxsegs{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface TX Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(isovalent_interface_txdrops{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface RX Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(isovalent_interface_rxdrops{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface TX Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(isovalent_interface_txerrors{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface RX Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(isovalent_interface_rxerrors{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  { "title": "Queue Disc Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "QLen Buckets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(isovalent_interface_qlen00{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "P00 {{ name }} {{ pod }}"
    },
    {
     "expr": "rate(isovalent_interface_qlen01{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "P01 {{ name }} {{ pod }}"
    },
    {
     "expr": "rate(isovalent_interface_qlen10{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "P10 {{ name }} {{ pod }}"
    },
    {
     "expr": "rate(isovalent_interface_qlen25{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "P25 {{ name }} {{ pod }}"
    },
    {
     "expr": "rate(isovalent_interface_qlen50{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "P50 {{ name }} {{ pod }}"
    },
    {
     "expr": "rate(isovalent_interface_qlen75{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "P75 {{ name }} {{ pod }}"
    },
    {
     "expr": "rate(isovalent_interface_qlen90{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "P90 {{ name }} {{ pod }}"
    },
    {
     "expr": "rate(isovalent_interface_qlen99{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "P99 {{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "QLen from 0 to 1 percent",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "rate(isovalent_interface_qlen00{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "QLen from 1 to 10 percent",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "rate(isovalent_interface_qlen01{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "QLen from 10 to 25 percent",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(isovalent_interface_qlen10{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "QLen from 25 to 50 percent",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "rate(isovalent_interface_qlen25{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "QLen from 50 to 75 percent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "rate(isovalent_interface_qlen50{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "QLen from 75 to 90 percent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "rate(isovalent_interface_qlen75{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "QLen from 99 to 100 percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "rate(isovalent_interface_qlen99{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "QLen from 90 to 99 percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "rate(isovalent_interface_qlen99{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  }
 ]
}