{
 "title": "Runtime Security Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(tetragon_events_total, pod)"
    }
   },
   { "name": "node", "query": { "query": "label_values(node)" } },
   {
    "name": "namespaces",
    "query": {
     "query": "label_values(tetragon_events_total, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tetragon Enterprise CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"enterprise\",node=~\"$node\"}[$__rate_interval]) * 100",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Tetragon Enterprise Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"hubble-enterprise\",pod=~\"hubble-enterprise.+\",container=\"enterprise\",node=~\"$node\"}",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Executed binaries on the cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_total[$__rate_interval])) by (binary, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executed binaries (pod, namespace)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_total{pod=~\"$pod\",namespace=~\"$namespaces\"}[$__rate_interval])) by (binary, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shells executed in the  pod/namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_total{binary=~\"/bin/bash|/bin/sh\", namespace=~\"$namespaces\"}[$__rate_interval])) by (pod, binary)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensitive Syscalls namespace/pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_total{type=\"PROCESS_KPROBE\",pod=~\"$pod\",namespace=~\"$namespaces\"}[$__rate_interval])) by (binary, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensitive File Accesses (pod, namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_file_actions_total{namespace=~\"$namespaces\"}[$__rate_interval])) by (rule, action, policy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensitive File Accesses (Host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_file_actions_total{namespace=\"<host>\"}[$__rate_interval])) by (rule, action, policy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External DNS names (namespaces)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_dns_total{namespace=~\"$namespaces\"}[$__rate_interval])) by (names, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External DNS names (namespace/pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(tetragon_dns_total{namespace=~\"$namespaces\",pod=~\"$pod\"}[$__rate_interval])) by (binary, names)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}