{
 "title": "TCP Metrics",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(node)" } },
   { "name": "pod", "query": { "query": "label_values(pod)" } },
   { "name": "dstdns", "query": { "query": "label_values(dstdns)" } },
   { "name": "dstpod", "query": { "query": "label_values(dstpod)" } },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "binary", "label": "binary", "query": { "query": "label_values(binary)" } },
   { "name": "bucket", "label": "bucket", "query": { "query": "label_values(bucket)" } }
  ]
 },
 "panels": [
  {
   "title": "Top 10 txsegments per binary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_txsegs{pod =~ \"$pod\",namespace=\"$namespace\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 txsegments per binary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_rxsegs{pod =~ \"$pod\",namespace=\"$namespace\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP TX Bursts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_txbursts{pod!=\"\",namespace=\"$namespace\"}[5m])))",
     "legendFormat": "{{pod}} > {{binary}}"
    }
   ]
  },
  {
   "title": "TCP RX Bursts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_rxbursts{pod!=\"\",namespace=\"$namespace\"}[5m])))",
     "legendFormat": "{{pod}} > {{binary}}"
    }
   ]
  },
  {
   "title": "TCP Latency Histogram",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(tetragon_socket_stats_rtt{namespace=~\"$namespace\"}[$__rate_interval])>0",
     "legendFormat": "{{pod}} | {{binary}} > {{dstpod}} | {{bucket}} "
    }
   ]
  },
  {
   "title": "Latency Buckets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(tetragon_socket_stats_rtt{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SRTT Between Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "tetragon_socket_stats_srtt{pod=~\"$pod\",dstpod=~\"$dstpod\",namespace=~\"$namespace\", quantile=\"0.99\"}>0",
     "legendFormat": "{{pod}} {{binary}} -> {{dstpod}}"
    }
   ]
  },
  { "title": "SRTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Top 10 - srtt per DNS destination",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(tetragon_socket_stats_srtt{dstdns=~\"$dstdns\",namespace=~\"$namespace\"}) by (dstdns))",
     "legendFormat": "{{dstdns}}"
    }
   ]
  },
  {
   "title": "Top 10 pod->pod bits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (pod, dstpod) ((rate(tetragon_socket_stats_rxbytes{dstpod=~\"$dstpod\",namespace=~\"$namespace\"}[5m]) + rate(tetragon_socket_stats_txbytes{dstpod=~\"$dstpod\",namespace=~\"$namespace\"}[5m]))))*8",
     "legendFormat": "{{pod}} -> {{dstpod}}"
    }
   ]
  },
  { "title": "Bytes-new", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Top 10 txbits per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_txbytes{pod=~\"$pod\",namespace=~\"$namespace\"}[5m])))*8",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  },
  {
   "title": "Top 10 rxbits per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_rxbytes{pod=~\"$pod\",namespace=~\"$namespace\"}[5m])))*8",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  },
  {
   "title": "Top 10 txbits per dstdns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(tetragon_socket_stats_txbytes{dstdns != \"\"}[5m])",
     "legendFormat": "{{dstdns}}"
    }
   ]
  },
  {
   "title": "Top 10 pod->dst bits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (pod, dstdns, namespace) ((rate(tetragon_socket_stats_rxbytes{dstdns =~ \"$dstdns\"}[5m]) + rate(tetragon_socket_stats_txbytes{dstdns =~ \"$dstdns\"}[5m]))))*8",
     "legendFormat": "{{pod}} -> {{dstdns}}"
    }
   ]
  },
  {
   "title": "Egress megabytes per pod",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(tetragon_socket_stats_txbytes{pod=~\"$pod\",namespace=~\"$namespace\"}) by(pod) / 1024 / 1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Zerowindows per pod",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_zerowindow{pod =~ \"$pod\",namespace=~\"$namespace\"}[$__interval])) by (pod)",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Retransmitted bytes between pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_retransmitbytes{dstpod=~\"$dstpod\",namespace=~\"$namespace\"}[$__interval])) by (pod, dstpod)",
     "legendFormat": "{{pod}} -> {{dstpod}}"
    }
   ]
  }
 ]
}