{
 "title": "Tetragon Health",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tetragon_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tetragon_build_info{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(tetragon_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\"},pod)"
    }
   },
   { "name": "node", "query": { "query": "label_values(node)" } },
   { "name": "k", "label": "top k", "query": "10" },
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "💓 Tetragon Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tetragon Health",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Tetragon Health\n\n#### ℹ️ Provides high level health indicators on Tetragon components, including Kubernetes level checks such as whether components are in a running state (i.e. not Pending/Crashing etc).\n\n"
   }
  },
  {
   "title": "Agent Pods Not Running",
   "type": "stat",
   "description": "Tracks the number of Tetragon Agents that are not in the Running state.  This could indicate Pods that are crashing, cannot be scheduled (i.e. Pending), image pull issues etc.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Tetragon Agents" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{pod=~\"tetragon-[0-9a-z]+\", pod=~\"$pod\", phase!=\"Running\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"} == 1 or kube_pod_container_status_waiting_reason{pod=~\"tetragon-[0-9a-z]+\", pod=~\"$pod\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"} > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tetragon Pod Restarts Since",
   "type": "stat",
   "description": "This is the total number of times Tetragon components have restarted in the given time range.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"tetragon\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__range]))",
     "legendFormat": "Tetragon Agent Restarts"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"tetragon-operator\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", cluster=~\"$cluster\", node=~\"$node\"}[$__range]))",
     "legendFormat": "Tetragon Operator Restarts"
    }
   ]
  },
  {
   "title": "Total Event Ratios",
   "type": "piechart",
   "description": "Total events by type over interval",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(tetragon_events_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tetragon Pod Restarts",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, floor(sum by (pod) (increase(kube_pod_container_status_restarts_total{container=~\"tetragon.*\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events by Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(tetragon_events_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Events Lost",
   "type": "gauge",
   "description": "Total lost events over interval",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, floor(increase(tetragon_ringbuf_perf_event_lost_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__range])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Event Loss Rate",
   "type": "timeseries",
   "description": "Events lost per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "topk($k, sum by (node, pod) (rate(tetragon_ringbuf_perf_event_lost_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{node}}/{{pod}}"
    }
   ]
  },
  {
   "title": "🗄️ BPF Maps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "BPF Map Health",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "# BPF Map Health\n\nTetragon uses BPF maps as a datastore.\n\nℹ️ **These maps are fundamental to Tetragon's operation. If they reach capacity then related functionality may fail.**"
     }
    },
    {
     "title": "Error Rate by Map",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "errs/sec" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_map_errors_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval])) by (map)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Map Utilization",
     "type": "timeseries",
     "description": "Provides current \"pressure\" on BPF maps which act as data stores for Tetragon agents.  High pressure can indicate overutilization of BPF maps and may lead to degradation of functionality.",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(tetragon_map_in_use_gauge{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}) by (map, total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Map Sizes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "entries" } },
     "targets": [
      {
       "expr": "sum by (map) (tetragon_map_in_use_gauge{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Map Growth Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "entries/s" } },
     "targets": [
      {
       "expr": "sum by(map) (deriv(tetragon_map_in_use_gauge{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Map Utilization",
     "type": "stat",
     "description": "Provides current \"pressure\" on BPF maps which act as data stores for Tetragon agents.  High pressure can indicate overutilization of BPF maps and may lead to degradation of functionality.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tetragon_map_in_use_gauge{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}) by (map, total)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "💻 Tetragon System CPU/Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tetragon Agent CPU Runtime Latency",
     "type": "stat",
     "description": "This metric provides the 90th and 50th (i.e. median) percentile of Tetragon agent run-time scheduling.\n\nThis is related to CPU availability and utilization, high values or increases here denote in either throttling or lack of compute resources.\n\nHigh sustained runtime will likely indicate problems with Tetragon functionality.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(go_sched_latencies_seconds_bucket{pod=~\"tetragon-[0-9a-z]+\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval])) by (le))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(go_sched_latencies_seconds_bucket{pod=~\"tetragon-[0-9a-z]+\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Tetragon Agent Container Memory Utilization",
     "type": "stat",
     "description": "Total memory utilization of Tetragon Agent Pods",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, sum(container_memory_working_set_bytes{container=\"tetragon\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Tetragon Agent Container CPU Utilization",
     "type": "stat",
     "description": "Provides top-k Tetragon Agent CPU utilization metrics.",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, sum(rate(container_cpu_usage_seconds_total{container=\"tetragon\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval])) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Tetragon Agent Container Memory Utilization",
     "type": "timeseries",
     "description": "Total memory utilization of Tetragon Agent Pods",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "topk($k, sum(container_memory_working_set_bytes{container=\"tetragon\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}) by (node, pod))",
       "legendFormat": "{{node}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Tetragon Agent Container CPU Utilization",
     "type": "timeseries",
     "description": "Provides top-k Tetragon Agent CPU utilization metrics.",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk($k, sum(rate(container_cpu_usage_seconds_total{container=\"tetragon\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval])) by (node, pod))",
       "legendFormat": "{{node}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Tetragon Agent Container Memory Limit Utilization",
     "type": "timeseries",
     "description": "This shows how close Tetragon workload Pods are to their set memory limits (if set).  By default Tetragon installs without explicit memory limits - in which case nothing should be shown here.\n\nHowever if Tetragon has a memory limit set this will show how much of their limit Tetragon Pods are using.\n\nPods that hit their limit will be killed for running out of memory by the Linux host OS and can cause disruptions in functionality.\n\nConsistently high values here should indicate that you may want to increase limits.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "(sum by (pod)(container_memory_working_set_bytes{container=\"tetragon\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"})) / (sum by (pod) (kube_pod_container_resource_limits{container=\"tetragon\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", resource=\"memory\", node=~\"$node\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "⚠️ Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "errors/s" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_errors_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Layer 3 Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "errors/s" } },
     "targets": [
      {
       "expr": "sum by (error) (rate(tetragon_layer3_event_errors_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error logs",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "{pod=~\"tetragon.*\", pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\", node_name=~\"$node\"} |= `error`"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Parser",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Parser",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 36 },
     "options": {
      "content": "This section is intended for validating or debugging the DNS parser.\n\nNote that some panels are not affected by the pod & namespace variables."
     }
    },
    {
     "title": "DNS Queries/Replies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (response, rcodes) (rate(tetragon_dns_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{response}} ({{rcodes}})"
      }
     ]
    },
    {
     "title": "DNS Cache Misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "misses/s" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_dns_cache_misses_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "DNS Cache Evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "evictions/s" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_dns_cache_evictions_total{node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "TCP TX Segments with Missing Destination Names by Binary",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "pkt/s" } },
     "targets": [
      {
       "expr": "sum by(binary) (rate(tetragon_socket_stats_txsegs_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\", dstdns=\"\", dstnamespace=\"\", dstworkload=\"\", dstpod=\"\"}[$__rate_interval]))",
       "legendFormat": "{{binary}}"
      }
     ]
    },
    {
     "title": "TCP RX Segments with Missing Destination Names by Binary",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "pkt/s" } },
     "targets": [
      {
       "expr": "sum by(binary) (rate(tetragon_socket_stats_rxsegs_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\", dstdns=\"\", dstnamespace=\"\", dstworkload=\"\", dstpod=\"\"}[$__rate_interval]))",
       "legendFormat": "{{binary}}"
      }
     ]
    },
    {
     "title": "Process Connect Events by Destination & Protocol",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "count by(protocol, destination_name) (rate({pod=~\"tetragon.*\", pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\" | __error__=`` [$__interval]))",
       "legendFormat": "{{protocol}} {{destination_name}}"
      }
     ]
    },
    {
     "title": "Missing Destination Names by Protocol",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "count by(protocol) (rate({pod=~\"tetragon.*\", pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\", destination_pod=\"process_connect.destination_pod.name\" | destination_name = `` | destination_pod = `` | __error__=`` [$__interval]))",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Missing TCP Destination Names by Binary & IP",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "events" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(destination_ip, binary) (count_over_time({pod=~\"tetragon.*\", pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\", destination_pod=\"process_connect.destination_pod.name\", binary=\"process_connect.process.binary\" | destination_name = `` | protocol = `TCP` | destination_pod = `` | __error__=`` [$__range]))",
       "legendFormat": "{{binary}} -> {{destination_ip}}"
      }
     ]
    },
    {
     "title": "Missing UDP Destination Names by Binary & IP",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "events" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(destination_ip, binary) (count_over_time({pod=~\"tetragon.*\", pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\", node_name=~\"$node\"} |= `\"process_connect\"` | json destination_name=\"process_connect.destination_names\", destination_ip=\"process_connect.destination_ip\", protocol=\"process_connect.protocol\", destination_pod=\"process_connect.destination_pod.name\", binary=\"process_connect.process.binary\" | destination_name = `` | destination_pod = `` | protocol = `UDP` | __error__=`` [$__range]))",
       "legendFormat": "{{binary}} -> {{destination_ip}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Parser",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true
  },
  {
   "title": "TLS Parser",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "TLS Parser",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
     "options": {
      "content": "This section is intended for validating or debugging the TLS parser.\n\nNote that some panels are not affected by the pod & namespace variables."
     }
    },
    {
     "title": "TLS Parser Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "errors/s" } },
     "targets": [
      {
       "expr": "sum by(error, continuation) (rate(tetragon_tls_errors_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percent Completed Continuations",
     "type": "timeseries",
     "description": "Ratio of actual continuation events to expected",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_tls_actual_continutation_events_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval])) / sum(rate(tetragon_tls_expected_continutation_events_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval])) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TLS Errors Total",
     "type": "gauge",
     "description": "Total TLS errors over the time range",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(error, continuation) (increase(tetragon_tls_errors_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TLS Cipher Suites",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "sum by(cipher) (rate(tetragon_tls_handshakes_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{cipher}}"
      }
     ]
    },
    {
     "title": "TLS SNI Names",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "sum by(sni_name) (rate(tetragon_tls_handshakes_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{sni_name}}"
      }
     ]
    },
    {
     "title": "TLS Versions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "events/s" } },
     "targets": [
      {
       "expr": "sum by(version) (rate(tetragon_tls_handshakes_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{version}}"
      }
     ]
    }
   ]
  }
 ]
}