{
 "title": "UDP Metrics",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "pod", "label": "pod", "query": { "query": "label_values(pod)" } },
   { "name": "dstpod", "label": "dstpod", "query": { "query": "label_values(dstpod)" } },
   { "name": "dstdns", "label": "dstdns", "query": { "query": "label_values(dstdns)" } },
   { "name": "binary", "query": { "query": "label_values(binary)" } },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "bucket", "label": "bucket", "query": { "query": "label_values(bucket)" } },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "UDP MCast Latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(tetragon_socket_stats_udp_mcast_latency{binary=~\"$binary\",pod=~\"$pod\",bucket=~\"$bucket\",namespace=~\"$namespace\"}[$__rate_interval])>0",
     "legendFormat": "{{bucket}} {{pod}} {{binary}} {{dstmcast}} --> {{srcmcast}}"
    }
   ]
  },
  {
   "title": "Latency Buckets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(tetragon_socket_stats_udp_mcast_latency{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 txbytes per binary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_udp_txbytes_total{pod =~ \"$pod\"}[5m])))",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  },
  {
   "title": "Top 10 rxbytes per binary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_udp_rxbytes_total{pod!=\"\"}[5m])))",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  },
  {
   "title": "Top 10 stack txbytes per binary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_udp_stack_txbytes_total{pod =~ \"$pod\"}[5m])))",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  },
  {
   "title": "Top 10 stack rxbytes per binary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_udp_stack_rxbytes_total{pod!=\"\"}[5m])))",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  },
  {
   "title": "Top 10 pod->pod bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, dstpod) ((rate(tetragon_socket_stats_udp_rxbytes_total{dstpod != \"\"}[5m]) + rate(tetragon_socket_stats_udp_txbytes_total{dstpod != \"\"}[5m]))))",
     "legendFormat": "{{pod}} -> {{dstpod}}"
    }
   ]
  },
  {
   "title": "Top 10 txbytes per dstdns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (dstdns) (rate(tetragon_socket_stats_udp_txbytes_total{dstdns=\"$dstdns\"}[5m])))",
     "legendFormat": "{{dstdns}}"
    }
   ]
  },
  {
   "title": "Top 10 txbursts per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bursts/sec" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_udp_txbursts_total{pod =~ \"$pod\"}[5m])))",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  },
  {
   "title": "Top 10 rxbursts per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bursts/sec" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_udp_rxbursts_total{pod =~ \"$pod\"}[5m])))",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  },
  {
   "title": "LRU UDP in use",
   "type": "timeseries",
   "description": "Tracks number of entries in the LRU cache used for statistics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "tetragon_lru_in_use_gauge" }
   ]
  },
  {
   "title": "UDP Parser Health (1hr)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(binary)(rate(tetragon_socket_stats_udp_txbytes_total{binary=\"\"}[1h]))",
     "legendFormat": "TXBytes Missing Binary"
    },
    {
     "expr": "sum by(binary)(rate(tetragon_socket_stats_udp_rxbytes_total{binary=\"\"}[1h]))",
     "legendFormat": "RXBytes Missing Binary"
    },
    {
     "expr": "sum by(binary)(rate(tetragon_socket_stats_udp_stack_txbytes_total{binary=\"\"}[1h]))",
     "legendFormat": "Stack TXBytes  Missing Binary"
    },
    {
     "expr": "sum by(binary)(rate(tetragon_socket_stats_udp_stack_rxbytes_total{binary=\"\"}[1h]))",
     "legendFormat": "Stack RXBytes Missing Binary"
    },
    {
     "expr": "sum (rate(tetragon_socket_stats_udp_consume_misses_total{}[1h]))",
     "legendFormat": "Consume Misses"
    }
   ]
  },
  {
   "title": "Top 10 pod->dst bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, dstdns) ((rate(tetragon_socket_stats_udp_rxbytes_total{dstdns != \"\"}[5m]) + rate(tetragon_socket_stats_udp_txbytes_total{dstdns != \"\"}[5m]))))",
     "legendFormat": "{{pod}} -> {{dstdns}}"
    }
   ]
  },
  {
   "title": "Top 10 txsegments per binary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_udp_txsegs_total{pod =~ \"$pod\"}[5m])))",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  },
  {
   "title": "Top 10 rxsegments per binary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (pod, binary) (rate(tetragon_socket_stats_udp_rxsegs_total{pod =~ \"$pod\"}[5m])))",
     "legendFormat": "{{pod}} ({{binary}})"
    }
   ]
  }
 ]
}