{
 "title": "Tetragon / Bursts & Dips",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tetragon_events_total, namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(tetragon_events_total{namespace=~\"$namespace\"}, workload)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(tetragon_events_total{namespace=~\"$namespace\", workload=~\"$workload\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TCP Watermarks by Binary (top 10)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "TCP TX Bursts per $__interval",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, workload, pod, binary) (increase(tetragon_socket_stats_txbursts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\"}[$__interval])) > 0)",
     "legendFormat": "{{namespace}} > {{workload}} > {{pod}} > {{binary}}"
    }
   ]
  },
  {
   "title": "TCP RX Bursts per $__interval",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, workload, pod, binary) (increase(tetragon_socket_stats_rxbursts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\"}[$__interval])) > 0)",
     "legendFormat": "{{namespace}} > {{workload}} > {{pod}} > {{binary}}"
    }
   ]
  },
  {
   "title": "TCP TX Dips per $__interval",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, workload, pod, binary) (increase(tetragon_socket_stats_txdips_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\"}[$__interval])) > 0)",
     "legendFormat": "{{namespace}} > {{workload}} > {{pod}} > {{binary}}"
    }
   ]
  },
  {
   "title": "TCP RX Dips per $__interval",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, workload, pod, binary) (increase(tetragon_socket_stats_rxdips_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\"}[$__interval])) > 0)",
     "legendFormat": "{{namespace}} > {{workload}} > {{pod}} > {{binary}}"
    }
   ]
  },
  {
   "title": "UDP Watermarks by Binary (top 10)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "UDP TX Bursts per $__interval",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, workload, pod, binary) (increase(tetragon_socket_stats_udp_txbursts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\"}[$__interval])) > 0)",
     "legendFormat": "{{namespace}} > {{workload}} > {{pod}} > {{binary}}"
    }
   ]
  },
  {
   "title": "UDP RX Bursts per $__interval",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, workload, pod, binary) (increase(tetragon_socket_stats_udp_rxbursts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\"}[$__interval])) > 0)",
     "legendFormat": "{{namespace}} > {{workload}} > {{pod}} > {{binary}}"
    }
   ]
  },
  {
   "title": "UDP TX Dips per $__interval",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, workload, pod, binary) (increase(tetragon_socket_stats_udp_txdips_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\"}[$__interval])) > 0)",
     "legendFormat": "{{namespace}} > {{workload}} > {{pod}} > {{binary}}"
    }
   ]
  },
  {
   "title": "UDP RX Dips per $__interval",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, workload, pod, binary) (increase(tetragon_socket_stats_udp_rxdips_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\"}[$__interval])) > 0)",
     "legendFormat": "{{namespace}} > {{workload}} > {{pod}} > {{binary}}"
    }
   ]
  }
 ]
}