//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.

package abicalls

// This file is autogenerated by kernel-syscall-info

// System call ABI call information for x86 starting from v4.19 to v6.10-rc3
var CallsX86_64 = map[string]X86_64{
	"read": X86_64{
		X64:  New(0, "__x64_sys_read"),
		IA32: New(3, "__ia32_sys_read"),
		X32:  New(0, "__x64_sys_read"),
	},
	"write": X86_64{
		X64:  New(1, "__x64_sys_write"),
		IA32: New(4, "__ia32_sys_write"),
		X32:  New(1, "__x64_sys_write"),
	},
	"open": X86_64{
		X64:  New(2, "__x64_sys_open"),
		IA32: New(5, "__ia32_compat_sys_open"),
		X32:  New(2, "__x64_sys_open"),
	},
	"close": X86_64{
		X64:  New(3, "__x64_sys_close"),
		IA32: New(6, "__ia32_sys_close"),
		X32:  New(3, "__x64_sys_close"),
	},
	"stat": X86_64{
		X64:  New(4, "__x64_sys_newstat"),
		IA32: New(106, "__ia32_compat_sys_newstat"),
		X32:  New(4, "__x64_sys_newstat"),
	},
	"fstat": X86_64{
		X64:  New(5, "__x64_sys_newfstat"),
		IA32: New(108, "__ia32_compat_sys_newfstat"),
		X32:  New(5, "__x64_sys_newfstat"),
	},
	"lstat": X86_64{
		X64:  New(6, "__x64_sys_newlstat"),
		IA32: New(107, "__ia32_compat_sys_newlstat"),
		X32:  New(6, "__x64_sys_newlstat"),
	},
	"poll": X86_64{
		X64:  New(7, "__x64_sys_poll"),
		IA32: New(168, "__ia32_sys_poll"),
		X32:  New(7, "__x64_sys_poll"),
	},
	"lseek": X86_64{
		X64:  New(8, "__x64_sys_lseek"),
		IA32: New(19, "__ia32_compat_sys_lseek"),
		X32:  New(8, "__x64_sys_lseek"),
	},
	"mmap": X86_64{
		X64:  New(9, "__x64_sys_mmap"),
		IA32: New(90, "__ia32_compat_sys_x86_mmap", "__ia32_compat_sys_ia32_mmap"),
		X32:  New(9, "__x64_sys_mmap"),
	},
	"mprotect": X86_64{
		X64:  New(10, "__x64_sys_mprotect"),
		IA32: New(125, "__ia32_sys_mprotect"),
		X32:  New(10, "__x64_sys_mprotect"),
	},
	"munmap": X86_64{
		X64:  New(11, "__x64_sys_munmap"),
		IA32: New(91, "__ia32_sys_munmap"),
		X32:  New(11, "__x64_sys_munmap"),
	},
	"brk": X86_64{
		X64:  New(12, "__x64_sys_brk"),
		IA32: New(45, "__ia32_sys_brk"),
		X32:  New(12, "__x64_sys_brk"),
	},
	"rt_sigaction": X86_64{
		X64:  New(13, "__x64_sys_rt_sigaction"),
		IA32: New(174, "__ia32_compat_sys_rt_sigaction"),
		X32:  New(512, "__x32_compat_sys_rt_sigaction"),
	},
	"rt_sigprocmask": X86_64{
		X64:  New(14, "__x64_sys_rt_sigprocmask"),
		IA32: New(175, "__ia32_sys_rt_sigprocmask", "__ia32_compat_sys_rt_sigprocmask"),
		X32:  New(14, "__x64_sys_rt_sigprocmask"),
	},
	"rt_sigreturn": X86_64{
		X64:  New(15, "__x64_sys_rt_sigreturn"),
		IA32: New(173, "sys32_rt_sigreturn", "__ia32_compat_sys_rt_sigreturn"),
		X32:  New(513, "sys32_x32_rt_sigreturn", "__x32_compat_sys_x32_rt_sigreturn"),
	},
	"ioctl": X86_64{
		X64:  New(16, "__x64_sys_ioctl"),
		IA32: New(54, "__ia32_compat_sys_ioctl"),
		X32:  New(514, "__x32_compat_sys_ioctl"),
	},
	"pread64": X86_64{
		X64:  New(17, "__x64_sys_pread64"),
		IA32: New(180, "__ia32_compat_sys_x86_pread", "__ia32_compat_sys_ia32_pread64"),
		X32:  New(17, "__x64_sys_pread64"),
	},
	"pwrite64": X86_64{
		X64:  New(18, "__x64_sys_pwrite64"),
		IA32: New(181, "__ia32_compat_sys_x86_pwrite", "__ia32_compat_sys_ia32_pwrite64"),
		X32:  New(18, "__x64_sys_pwrite64"),
	},
	"readv": X86_64{
		X64:  New(19, "__x64_sys_readv"),
		IA32: New(145, "__ia32_compat_sys_readv"),
		X32:  New(515, "__x32_compat_sys_readv", "__x32_sys_readv"),
	},
	"writev": X86_64{
		X64:  New(20, "__x64_sys_writev"),
		IA32: New(146, "__ia32_compat_sys_writev"),
		X32:  New(516, "__x32_compat_sys_writev", "__x32_sys_writev"),
	},
	"access": X86_64{
		X64:  New(21, "__x64_sys_access"),
		IA32: New(33, "__ia32_sys_access"),
		X32:  New(21, "__x64_sys_access"),
	},
	"pipe": X86_64{
		X64:  New(22, "__x64_sys_pipe"),
		IA32: New(42, "__ia32_sys_pipe"),
		X32:  New(22, "__x64_sys_pipe"),
	},
	"select": X86_64{
		X64:  New(23, "__x64_sys_select"),
		IA32: New(82, "__ia32_compat_sys_old_select"),
		X32:  New(23, "__x64_sys_select"),
	},
	"sched_yield": X86_64{
		X64:  New(24, "__x64_sys_sched_yield"),
		IA32: New(158, "__ia32_sys_sched_yield"),
		X32:  New(24, "__x64_sys_sched_yield"),
	},
	"mremap": X86_64{
		X64:  New(25, "__x64_sys_mremap"),
		IA32: New(163, "__ia32_sys_mremap"),
		X32:  New(25, "__x64_sys_mremap"),
	},
	"msync": X86_64{
		X64:  New(26, "__x64_sys_msync"),
		IA32: New(144, "__ia32_sys_msync"),
		X32:  New(26, "__x64_sys_msync"),
	},
	"mincore": X86_64{
		X64:  New(27, "__x64_sys_mincore"),
		IA32: New(218, "__ia32_sys_mincore"),
		X32:  New(27, "__x64_sys_mincore"),
	},
	"madvise": X86_64{
		X64:  New(28, "__x64_sys_madvise"),
		IA32: New(219, "__ia32_sys_madvise"),
		X32:  New(28, "__x64_sys_madvise"),
	},
	"shmget": X86_64{
		X64:  New(29, "__x64_sys_shmget"),
		IA32: New(395, "__ia32_sys_shmget"),
		X32:  New(29, "__x64_sys_shmget"),
	},
	"shmat": X86_64{
		X64:  New(30, "__x64_sys_shmat"),
		IA32: New(397, "__ia32_compat_sys_shmat"),
		X32:  New(30, "__x64_sys_shmat"),
	},
	"shmctl": X86_64{
		X64:  New(31, "__x64_sys_shmctl"),
		IA32: New(396, "__ia32_compat_sys_shmctl"),
		X32:  New(31, "__x64_sys_shmctl"),
	},
	"dup": X86_64{
		X64:  New(32, "__x64_sys_dup"),
		IA32: New(41, "__ia32_sys_dup"),
		X32:  New(32, "__x64_sys_dup"),
	},
	"dup2": X86_64{
		X64:  New(33, "__x64_sys_dup2"),
		IA32: New(63, "__ia32_sys_dup2"),
		X32:  New(33, "__x64_sys_dup2"),
	},
	"pause": X86_64{
		X64:  New(34, "__x64_sys_pause"),
		IA32: New(29, "__ia32_sys_pause"),
		X32:  New(34, "__x64_sys_pause"),
	},
	"nanosleep": X86_64{
		X64:  New(35, "__x64_sys_nanosleep"),
		IA32: New(162, "__ia32_compat_sys_nanosleep", "__ia32_sys_nanosleep_time32"),
		X32:  New(35, "__x64_sys_nanosleep"),
	},
	"getitimer": X86_64{
		X64:  New(36, "__x64_sys_getitimer"),
		IA32: New(105, "__ia32_compat_sys_getitimer"),
		X32:  New(36, "__x64_sys_getitimer"),
	},
	"alarm": X86_64{
		X64:  New(37, "__x64_sys_alarm"),
		IA32: New(27, "__ia32_sys_alarm"),
		X32:  New(37, "__x64_sys_alarm"),
	},
	"setitimer": X86_64{
		X64:  New(38, "__x64_sys_setitimer"),
		IA32: New(104, "__ia32_compat_sys_setitimer"),
		X32:  New(38, "__x64_sys_setitimer"),
	},
	"getpid": X86_64{
		X64:  New(39, "__x64_sys_getpid"),
		IA32: New(20, "__ia32_sys_getpid"),
		X32:  New(39, "__x64_sys_getpid"),
	},
	"sendfile": X86_64{
		X64:  New(40, "__x64_sys_sendfile64"),
		IA32: New(187, "__ia32_compat_sys_sendfile"),
		X32:  New(40, "__x64_sys_sendfile64"),
	},
	"socket": X86_64{
		X64:  New(41, "__x64_sys_socket"),
		IA32: New(359, "__ia32_sys_socket"),
		X32:  New(41, "__x64_sys_socket"),
	},
	"connect": X86_64{
		X64:  New(42, "__x64_sys_connect"),
		IA32: New(362, "__ia32_sys_connect"),
		X32:  New(42, "__x64_sys_connect"),
	},
	"accept": X86_64{
		X64:  New(43, "__x64_sys_accept"),
		IA32: nil,
		X32:  New(43, "__x64_sys_accept"),
	},
	"sendto": X86_64{
		X64:  New(44, "__x64_sys_sendto"),
		IA32: New(369, "__ia32_sys_sendto"),
		X32:  New(44, "__x64_sys_sendto"),
	},
	"recvfrom": X86_64{
		X64:  New(45, "__x64_sys_recvfrom"),
		IA32: New(371, "__ia32_compat_sys_recvfrom"),
		X32:  New(517, "__x32_compat_sys_recvfrom"),
	},
	"sendmsg": X86_64{
		X64:  New(46, "__x64_sys_sendmsg"),
		IA32: New(370, "__ia32_compat_sys_sendmsg"),
		X32:  New(518, "__x32_compat_sys_sendmsg"),
	},
	"recvmsg": X86_64{
		X64:  New(47, "__x64_sys_recvmsg"),
		IA32: New(372, "__ia32_compat_sys_recvmsg"),
		X32:  New(519, "__x32_compat_sys_recvmsg"),
	},
	"shutdown": X86_64{
		X64:  New(48, "__x64_sys_shutdown"),
		IA32: New(373, "__ia32_sys_shutdown"),
		X32:  New(48, "__x64_sys_shutdown"),
	},
	"bind": X86_64{
		X64:  New(49, "__x64_sys_bind"),
		IA32: New(361, "__ia32_sys_bind"),
		X32:  New(49, "__x64_sys_bind"),
	},
	"listen": X86_64{
		X64:  New(50, "__x64_sys_listen"),
		IA32: New(363, "__ia32_sys_listen"),
		X32:  New(50, "__x64_sys_listen"),
	},
	"getsockname": X86_64{
		X64:  New(51, "__x64_sys_getsockname"),
		IA32: New(367, "__ia32_sys_getsockname"),
		X32:  New(51, "__x64_sys_getsockname"),
	},
	"getpeername": X86_64{
		X64:  New(52, "__x64_sys_getpeername"),
		IA32: New(368, "__ia32_sys_getpeername"),
		X32:  New(52, "__x64_sys_getpeername"),
	},
	"socketpair": X86_64{
		X64:  New(53, "__x64_sys_socketpair"),
		IA32: New(360, "__ia32_sys_socketpair"),
		X32:  New(53, "__x64_sys_socketpair"),
	},
	"setsockopt": X86_64{
		X64:  New(54, "__x64_sys_setsockopt"),
		IA32: New(366, "__ia32_compat_sys_setsockopt", "__ia32_sys_setsockopt"),
		X32:  New(541, "__x32_compat_sys_setsockopt", "__x32_sys_setsockopt"),
	},
	"getsockopt": X86_64{
		X64:  New(55, "__x64_sys_getsockopt"),
		IA32: New(365, "__ia32_compat_sys_getsockopt", "__ia32_sys_getsockopt"),
		X32:  New(542, "__x32_compat_sys_getsockopt", "__x32_sys_getsockopt"),
	},
	"clone": X86_64{
		X64:  New(56, "__x64_sys_clone"),
		IA32: New(120, "__ia32_compat_sys_x86_clone", "__ia32_compat_sys_ia32_clone"),
		X32:  New(56, "__x64_sys_clone"),
	},
	"fork": X86_64{
		X64:  New(57, "__x64_sys_fork"),
		IA32: New(2, "__ia32_sys_fork"),
		X32:  New(57, "__x64_sys_fork"),
	},
	"vfork": X86_64{
		X64:  New(58, "__x64_sys_vfork"),
		IA32: New(190, "__ia32_sys_vfork"),
		X32:  New(58, "__x64_sys_vfork"),
	},
	"execve": X86_64{
		X64:  New(59, "__x64_sys_execve"),
		IA32: New(11, "__ia32_compat_sys_execve"),
		X32:  New(520, "__x32_compat_sys_execve"),
	},
	"exit": X86_64{
		X64:  New(60, "__x64_sys_exit"),
		IA32: New(1, "__ia32_sys_exit"),
		X32:  New(60, "__x64_sys_exit"),
	},
	"wait4": X86_64{
		X64:  New(61, "__x64_sys_wait4"),
		IA32: New(114, "__ia32_compat_sys_wait4"),
		X32:  New(61, "__x64_sys_wait4"),
	},
	"kill": X86_64{
		X64:  New(62, "__x64_sys_kill"),
		IA32: New(37, "__ia32_sys_kill"),
		X32:  New(62, "__x64_sys_kill"),
	},
	"uname": X86_64{
		X64:  New(63, "__x64_sys_newuname"),
		IA32: New(122, "__ia32_sys_newuname"),
		X32:  New(63, "__x64_sys_newuname"),
	},
	"semget": X86_64{
		X64:  New(64, "__x64_sys_semget"),
		IA32: New(393, "__ia32_sys_semget"),
		X32:  New(64, "__x64_sys_semget"),
	},
	"semop": X86_64{
		X64:  New(65, "__x64_sys_semop"),
		IA32: nil,
		X32:  New(65, "__x64_sys_semop"),
	},
	"semctl": X86_64{
		X64:  New(66, "__x64_sys_semctl"),
		IA32: New(394, "__ia32_compat_sys_semctl"),
		X32:  New(66, "__x64_sys_semctl"),
	},
	"shmdt": X86_64{
		X64:  New(67, "__x64_sys_shmdt"),
		IA32: New(398, "__ia32_sys_shmdt"),
		X32:  New(67, "__x64_sys_shmdt"),
	},
	"msgget": X86_64{
		X64:  New(68, "__x64_sys_msgget"),
		IA32: New(399, "__ia32_sys_msgget"),
		X32:  New(68, "__x64_sys_msgget"),
	},
	"msgsnd": X86_64{
		X64:  New(69, "__x64_sys_msgsnd"),
		IA32: New(400, "__ia32_compat_sys_msgsnd"),
		X32:  New(69, "__x64_sys_msgsnd"),
	},
	"msgrcv": X86_64{
		X64:  New(70, "__x64_sys_msgrcv"),
		IA32: New(401, "__ia32_compat_sys_msgrcv"),
		X32:  New(70, "__x64_sys_msgrcv"),
	},
	"msgctl": X86_64{
		X64:  New(71, "__x64_sys_msgctl"),
		IA32: New(402, "__ia32_compat_sys_msgctl"),
		X32:  New(71, "__x64_sys_msgctl"),
	},
	"fcntl": X86_64{
		X64:  New(72, "__x64_sys_fcntl"),
		IA32: New(55, "__ia32_compat_sys_fcntl64"),
		X32:  New(72, "__x64_sys_fcntl"),
	},
	"flock": X86_64{
		X64:  New(73, "__x64_sys_flock"),
		IA32: New(143, "__ia32_sys_flock"),
		X32:  New(73, "__x64_sys_flock"),
	},
	"fsync": X86_64{
		X64:  New(74, "__x64_sys_fsync"),
		IA32: New(118, "__ia32_sys_fsync"),
		X32:  New(74, "__x64_sys_fsync"),
	},
	"fdatasync": X86_64{
		X64:  New(75, "__x64_sys_fdatasync"),
		IA32: New(148, "__ia32_sys_fdatasync"),
		X32:  New(75, "__x64_sys_fdatasync"),
	},
	"truncate": X86_64{
		X64:  New(76, "__x64_sys_truncate"),
		IA32: New(92, "__ia32_compat_sys_truncate"),
		X32:  New(76, "__x64_sys_truncate"),
	},
	"ftruncate": X86_64{
		X64:  New(77, "__x64_sys_ftruncate"),
		IA32: New(93, "__ia32_compat_sys_ftruncate"),
		X32:  New(77, "__x64_sys_ftruncate"),
	},
	"getdents": X86_64{
		X64:  New(78, "__x64_sys_getdents"),
		IA32: New(141, "__ia32_compat_sys_getdents"),
		X32:  New(78, "__x64_sys_getdents"),
	},
	"getcwd": X86_64{
		X64:  New(79, "__x64_sys_getcwd"),
		IA32: New(183, "__ia32_sys_getcwd"),
		X32:  New(79, "__x64_sys_getcwd"),
	},
	"chdir": X86_64{
		X64:  New(80, "__x64_sys_chdir"),
		IA32: New(12, "__ia32_sys_chdir"),
		X32:  New(80, "__x64_sys_chdir"),
	},
	"fchdir": X86_64{
		X64:  New(81, "__x64_sys_fchdir"),
		IA32: New(133, "__ia32_sys_fchdir"),
		X32:  New(81, "__x64_sys_fchdir"),
	},
	"rename": X86_64{
		X64:  New(82, "__x64_sys_rename"),
		IA32: New(38, "__ia32_sys_rename"),
		X32:  New(82, "__x64_sys_rename"),
	},
	"mkdir": X86_64{
		X64:  New(83, "__x64_sys_mkdir"),
		IA32: New(39, "__ia32_sys_mkdir"),
		X32:  New(83, "__x64_sys_mkdir"),
	},
	"rmdir": X86_64{
		X64:  New(84, "__x64_sys_rmdir"),
		IA32: New(40, "__ia32_sys_rmdir"),
		X32:  New(84, "__x64_sys_rmdir"),
	},
	"creat": X86_64{
		X64:  New(85, "__x64_sys_creat"),
		IA32: New(8, "__ia32_sys_creat"),
		X32:  New(85, "__x64_sys_creat"),
	},
	"link": X86_64{
		X64:  New(86, "__x64_sys_link"),
		IA32: New(9, "__ia32_sys_link"),
		X32:  New(86, "__x64_sys_link"),
	},
	"unlink": X86_64{
		X64:  New(87, "__x64_sys_unlink"),
		IA32: New(10, "__ia32_sys_unlink"),
		X32:  New(87, "__x64_sys_unlink"),
	},
	"symlink": X86_64{
		X64:  New(88, "__x64_sys_symlink"),
		IA32: New(83, "__ia32_sys_symlink"),
		X32:  New(88, "__x64_sys_symlink"),
	},
	"readlink": X86_64{
		X64:  New(89, "__x64_sys_readlink"),
		IA32: New(85, "__ia32_sys_readlink"),
		X32:  New(89, "__x64_sys_readlink"),
	},
	"chmod": X86_64{
		X64:  New(90, "__x64_sys_chmod"),
		IA32: New(15, "__ia32_sys_chmod"),
		X32:  New(90, "__x64_sys_chmod"),
	},
	"fchmod": X86_64{
		X64:  New(91, "__x64_sys_fchmod"),
		IA32: New(94, "__ia32_sys_fchmod"),
		X32:  New(91, "__x64_sys_fchmod"),
	},
	"chown": X86_64{
		X64:  New(92, "__x64_sys_chown"),
		IA32: New(182, "__ia32_sys_chown16"),
		X32:  New(92, "__x64_sys_chown"),
	},
	"fchown": X86_64{
		X64:  New(93, "__x64_sys_fchown"),
		IA32: New(95, "__ia32_sys_fchown16"),
		X32:  New(93, "__x64_sys_fchown"),
	},
	"lchown": X86_64{
		X64:  New(94, "__x64_sys_lchown"),
		IA32: New(16, "__ia32_sys_lchown16"),
		X32:  New(94, "__x64_sys_lchown"),
	},
	"umask": X86_64{
		X64:  New(95, "__x64_sys_umask"),
		IA32: New(60, "__ia32_sys_umask"),
		X32:  New(95, "__x64_sys_umask"),
	},
	"gettimeofday": X86_64{
		X64:  New(96, "__x64_sys_gettimeofday"),
		IA32: New(78, "__ia32_compat_sys_gettimeofday"),
		X32:  New(96, "__x64_sys_gettimeofday"),
	},
	"getrlimit": X86_64{
		X64:  New(97, "__x64_sys_getrlimit"),
		IA32: New(76, "__ia32_compat_sys_old_getrlimit"),
		X32:  New(97, "__x64_sys_getrlimit"),
	},
	"getrusage": X86_64{
		X64:  New(98, "__x64_sys_getrusage"),
		IA32: New(77, "__ia32_compat_sys_getrusage"),
		X32:  New(98, "__x64_sys_getrusage"),
	},
	"sysinfo": X86_64{
		X64:  New(99, "__x64_sys_sysinfo"),
		IA32: New(116, "__ia32_compat_sys_sysinfo"),
		X32:  New(99, "__x64_sys_sysinfo"),
	},
	"times": X86_64{
		X64:  New(100, "__x64_sys_times"),
		IA32: New(43, "__ia32_compat_sys_times"),
		X32:  New(100, "__x64_sys_times"),
	},
	"ptrace": X86_64{
		X64:  New(101, "__x64_sys_ptrace"),
		IA32: New(26, "__ia32_compat_sys_ptrace"),
		X32:  New(521, "__x32_compat_sys_ptrace"),
	},
	"getuid": X86_64{
		X64:  New(102, "__x64_sys_getuid"),
		IA32: New(24, "__ia32_sys_getuid16"),
		X32:  New(102, "__x64_sys_getuid"),
	},
	"syslog": X86_64{
		X64:  New(103, "__x64_sys_syslog"),
		IA32: New(103, "__ia32_sys_syslog"),
		X32:  New(103, "__x64_sys_syslog"),
	},
	"getgid": X86_64{
		X64:  New(104, "__x64_sys_getgid"),
		IA32: New(47, "__ia32_sys_getgid16"),
		X32:  New(104, "__x64_sys_getgid"),
	},
	"setuid": X86_64{
		X64:  New(105, "__x64_sys_setuid"),
		IA32: New(23, "__ia32_sys_setuid16"),
		X32:  New(105, "__x64_sys_setuid"),
	},
	"setgid": X86_64{
		X64:  New(106, "__x64_sys_setgid"),
		IA32: New(46, "__ia32_sys_setgid16"),
		X32:  New(106, "__x64_sys_setgid"),
	},
	"geteuid": X86_64{
		X64:  New(107, "__x64_sys_geteuid"),
		IA32: New(49, "__ia32_sys_geteuid16"),
		X32:  New(107, "__x64_sys_geteuid"),
	},
	"getegid": X86_64{
		X64:  New(108, "__x64_sys_getegid"),
		IA32: New(50, "__ia32_sys_getegid16"),
		X32:  New(108, "__x64_sys_getegid"),
	},
	"setpgid": X86_64{
		X64:  New(109, "__x64_sys_setpgid"),
		IA32: New(57, "__ia32_sys_setpgid"),
		X32:  New(109, "__x64_sys_setpgid"),
	},
	"getppid": X86_64{
		X64:  New(110, "__x64_sys_getppid"),
		IA32: New(64, "__ia32_sys_getppid"),
		X32:  New(110, "__x64_sys_getppid"),
	},
	"getpgrp": X86_64{
		X64:  New(111, "__x64_sys_getpgrp"),
		IA32: New(65, "__ia32_sys_getpgrp"),
		X32:  New(111, "__x64_sys_getpgrp"),
	},
	"setsid": X86_64{
		X64:  New(112, "__x64_sys_setsid"),
		IA32: New(66, "__ia32_sys_setsid"),
		X32:  New(112, "__x64_sys_setsid"),
	},
	"setreuid": X86_64{
		X64:  New(113, "__x64_sys_setreuid"),
		IA32: New(70, "__ia32_sys_setreuid16"),
		X32:  New(113, "__x64_sys_setreuid"),
	},
	"setregid": X86_64{
		X64:  New(114, "__x64_sys_setregid"),
		IA32: New(71, "__ia32_sys_setregid16"),
		X32:  New(114, "__x64_sys_setregid"),
	},
	"getgroups": X86_64{
		X64:  New(115, "__x64_sys_getgroups"),
		IA32: New(80, "__ia32_sys_getgroups16"),
		X32:  New(115, "__x64_sys_getgroups"),
	},
	"setgroups": X86_64{
		X64:  New(116, "__x64_sys_setgroups"),
		IA32: New(81, "__ia32_sys_setgroups16"),
		X32:  New(116, "__x64_sys_setgroups"),
	},
	"setresuid": X86_64{
		X64:  New(117, "__x64_sys_setresuid"),
		IA32: New(164, "__ia32_sys_setresuid16"),
		X32:  New(117, "__x64_sys_setresuid"),
	},
	"getresuid": X86_64{
		X64:  New(118, "__x64_sys_getresuid"),
		IA32: New(165, "__ia32_sys_getresuid16"),
		X32:  New(118, "__x64_sys_getresuid"),
	},
	"setresgid": X86_64{
		X64:  New(119, "__x64_sys_setresgid"),
		IA32: New(170, "__ia32_sys_setresgid16"),
		X32:  New(119, "__x64_sys_setresgid"),
	},
	"getresgid": X86_64{
		X64:  New(120, "__x64_sys_getresgid"),
		IA32: New(171, "__ia32_sys_getresgid16"),
		X32:  New(120, "__x64_sys_getresgid"),
	},
	"getpgid": X86_64{
		X64:  New(121, "__x64_sys_getpgid"),
		IA32: New(132, "__ia32_sys_getpgid"),
		X32:  New(121, "__x64_sys_getpgid"),
	},
	"setfsuid": X86_64{
		X64:  New(122, "__x64_sys_setfsuid"),
		IA32: New(138, "__ia32_sys_setfsuid16"),
		X32:  New(122, "__x64_sys_setfsuid"),
	},
	"setfsgid": X86_64{
		X64:  New(123, "__x64_sys_setfsgid"),
		IA32: New(139, "__ia32_sys_setfsgid16"),
		X32:  New(123, "__x64_sys_setfsgid"),
	},
	"getsid": X86_64{
		X64:  New(124, "__x64_sys_getsid"),
		IA32: New(147, "__ia32_sys_getsid"),
		X32:  New(124, "__x64_sys_getsid"),
	},
	"capget": X86_64{
		X64:  New(125, "__x64_sys_capget"),
		IA32: New(184, "__ia32_sys_capget"),
		X32:  New(125, "__x64_sys_capget"),
	},
	"capset": X86_64{
		X64:  New(126, "__x64_sys_capset"),
		IA32: New(185, "__ia32_sys_capset"),
		X32:  New(126, "__x64_sys_capset"),
	},
	"rt_sigpending": X86_64{
		X64:  New(127, "__x64_sys_rt_sigpending"),
		IA32: New(176, "__ia32_compat_sys_rt_sigpending"),
		X32:  New(522, "__x32_compat_sys_rt_sigpending"),
	},
	"rt_sigtimedwait": X86_64{
		X64:  New(128, "__x64_sys_rt_sigtimedwait"),
		IA32: New(177, "__ia32_compat_sys_rt_sigtimedwait", "__ia32_compat_sys_rt_sigtimedwait_time32"),
		X32:  New(523, "__x32_compat_sys_rt_sigtimedwait", "__x32_compat_sys_rt_sigtimedwait_time64"),
	},
	"rt_sigqueueinfo": X86_64{
		X64:  New(129, "__x64_sys_rt_sigqueueinfo"),
		IA32: New(178, "__ia32_compat_sys_rt_sigqueueinfo"),
		X32:  New(524, "__x32_compat_sys_rt_sigqueueinfo"),
	},
	"rt_sigsuspend": X86_64{
		X64:  New(130, "__x64_sys_rt_sigsuspend"),
		IA32: New(179, "__ia32_sys_rt_sigsuspend", "__ia32_compat_sys_rt_sigsuspend"),
		X32:  New(130, "__x64_sys_rt_sigsuspend"),
	},
	"sigaltstack": X86_64{
		X64:  New(131, "__x64_sys_sigaltstack"),
		IA32: New(186, "__ia32_compat_sys_sigaltstack"),
		X32:  New(525, "__x32_compat_sys_sigaltstack"),
	},
	"utime": X86_64{
		X64:  New(132, "__x64_sys_utime"),
		IA32: New(30, "__ia32_compat_sys_utime", "__ia32_sys_utime32"),
		X32:  New(132, "__x64_sys_utime"),
	},
	"mknod": X86_64{
		X64:  New(133, "__x64_sys_mknod"),
		IA32: New(14, "__ia32_sys_mknod"),
		X32:  New(133, "__x64_sys_mknod"),
	},
	"personality": X86_64{
		X64:  New(135, "__x64_sys_personality"),
		IA32: New(136, "__ia32_sys_personality"),
		X32:  New(135, "__x64_sys_personality"),
	},
	"ustat": X86_64{
		X64:  New(136, "__x64_sys_ustat"),
		IA32: New(62, "__ia32_compat_sys_ustat"),
		X32:  New(136, "__x64_sys_ustat"),
	},
	"statfs": X86_64{
		X64:  New(137, "__x64_sys_statfs"),
		IA32: New(99, "__ia32_compat_sys_statfs"),
		X32:  New(137, "__x64_sys_statfs"),
	},
	"fstatfs": X86_64{
		X64:  New(138, "__x64_sys_fstatfs"),
		IA32: New(100, "__ia32_compat_sys_fstatfs"),
		X32:  New(138, "__x64_sys_fstatfs"),
	},
	"sysfs": X86_64{
		X64:  New(139, "__x64_sys_sysfs"),
		IA32: New(135, "__ia32_sys_sysfs"),
		X32:  New(139, "__x64_sys_sysfs"),
	},
	"getpriority": X86_64{
		X64:  New(140, "__x64_sys_getpriority"),
		IA32: New(96, "__ia32_sys_getpriority"),
		X32:  New(140, "__x64_sys_getpriority"),
	},
	"setpriority": X86_64{
		X64:  New(141, "__x64_sys_setpriority"),
		IA32: New(97, "__ia32_sys_setpriority"),
		X32:  New(141, "__x64_sys_setpriority"),
	},
	"sched_setparam": X86_64{
		X64:  New(142, "__x64_sys_sched_setparam"),
		IA32: New(154, "__ia32_sys_sched_setparam"),
		X32:  New(142, "__x64_sys_sched_setparam"),
	},
	"sched_getparam": X86_64{
		X64:  New(143, "__x64_sys_sched_getparam"),
		IA32: New(155, "__ia32_sys_sched_getparam"),
		X32:  New(143, "__x64_sys_sched_getparam"),
	},
	"sched_setscheduler": X86_64{
		X64:  New(144, "__x64_sys_sched_setscheduler"),
		IA32: New(156, "__ia32_sys_sched_setscheduler"),
		X32:  New(144, "__x64_sys_sched_setscheduler"),
	},
	"sched_getscheduler": X86_64{
		X64:  New(145, "__x64_sys_sched_getscheduler"),
		IA32: New(157, "__ia32_sys_sched_getscheduler"),
		X32:  New(145, "__x64_sys_sched_getscheduler"),
	},
	"sched_get_priority_max": X86_64{
		X64:  New(146, "__x64_sys_sched_get_priority_max"),
		IA32: New(159, "__ia32_sys_sched_get_priority_max"),
		X32:  New(146, "__x64_sys_sched_get_priority_max"),
	},
	"sched_get_priority_min": X86_64{
		X64:  New(147, "__x64_sys_sched_get_priority_min"),
		IA32: New(160, "__ia32_sys_sched_get_priority_min"),
		X32:  New(147, "__x64_sys_sched_get_priority_min"),
	},
	"sched_rr_get_interval": X86_64{
		X64:  New(148, "__x64_sys_sched_rr_get_interval"),
		IA32: New(161, "__ia32_compat_sys_sched_rr_get_interval", "__ia32_sys_sched_rr_get_interval_time32"),
		X32:  New(148, "__x64_sys_sched_rr_get_interval"),
	},
	"mlock": X86_64{
		X64:  New(149, "__x64_sys_mlock"),
		IA32: New(150, "__ia32_sys_mlock"),
		X32:  New(149, "__x64_sys_mlock"),
	},
	"munlock": X86_64{
		X64:  New(150, "__x64_sys_munlock"),
		IA32: New(151, "__ia32_sys_munlock"),
		X32:  New(150, "__x64_sys_munlock"),
	},
	"mlockall": X86_64{
		X64:  New(151, "__x64_sys_mlockall"),
		IA32: New(152, "__ia32_sys_mlockall"),
		X32:  New(151, "__x64_sys_mlockall"),
	},
	"munlockall": X86_64{
		X64:  New(152, "__x64_sys_munlockall"),
		IA32: New(153, "__ia32_sys_munlockall"),
		X32:  New(152, "__x64_sys_munlockall"),
	},
	"vhangup": X86_64{
		X64:  New(153, "__x64_sys_vhangup"),
		IA32: New(111, "__ia32_sys_vhangup"),
		X32:  New(153, "__x64_sys_vhangup"),
	},
	"modify_ldt": X86_64{
		X64:  New(154, "__x64_sys_modify_ldt"),
		IA32: New(123, "__ia32_sys_modify_ldt"),
		X32:  New(154, "__x64_sys_modify_ldt"),
	},
	"pivot_root": X86_64{
		X64:  New(155, "__x64_sys_pivot_root"),
		IA32: New(217, "__ia32_sys_pivot_root"),
		X32:  New(155, "__x64_sys_pivot_root"),
	},
	"_sysctl": X86_64{
		X64:  New(156, "__x64_sys_sysctl"),
		IA32: New(149, "__ia32_compat_sys_sysctl"),
		X32:  nil,
	},
	"prctl": X86_64{
		X64:  New(157, "__x64_sys_prctl"),
		IA32: New(172, "__ia32_sys_prctl"),
		X32:  New(157, "__x64_sys_prctl"),
	},
	"arch_prctl": X86_64{
		X64:  New(158, "__x64_sys_arch_prctl"),
		IA32: New(384, "__ia32_compat_sys_arch_prctl"),
		X32:  New(158, "__x64_sys_arch_prctl"),
	},
	"adjtimex": X86_64{
		X64:  New(159, "__x64_sys_adjtimex"),
		IA32: New(124, "__ia32_compat_sys_adjtimex", "__ia32_sys_adjtimex_time32"),
		X32:  New(159, "__x64_sys_adjtimex"),
	},
	"setrlimit": X86_64{
		X64:  New(160, "__x64_sys_setrlimit"),
		IA32: New(75, "__ia32_compat_sys_setrlimit"),
		X32:  New(160, "__x64_sys_setrlimit"),
	},
	"chroot": X86_64{
		X64:  New(161, "__x64_sys_chroot"),
		IA32: New(61, "__ia32_sys_chroot"),
		X32:  New(161, "__x64_sys_chroot"),
	},
	"sync": X86_64{
		X64:  New(162, "__x64_sys_sync"),
		IA32: New(36, "__ia32_sys_sync"),
		X32:  New(162, "__x64_sys_sync"),
	},
	"acct": X86_64{
		X64:  New(163, "__x64_sys_acct"),
		IA32: New(51, "__ia32_sys_acct"),
		X32:  New(163, "__x64_sys_acct"),
	},
	"settimeofday": X86_64{
		X64:  New(164, "__x64_sys_settimeofday"),
		IA32: New(79, "__ia32_compat_sys_settimeofday"),
		X32:  New(164, "__x64_sys_settimeofday"),
	},
	"mount": X86_64{
		X64:  New(165, "__x64_sys_mount"),
		IA32: New(21, "__ia32_compat_sys_mount"),
		X32:  New(165, "__x64_sys_mount"),
	},
	"umount2": X86_64{
		X64:  New(166, "__x64_sys_umount"),
		IA32: New(52, "__ia32_sys_umount"),
		X32:  New(166, "__x64_sys_umount"),
	},
	"swapon": X86_64{
		X64:  New(167, "__x64_sys_swapon"),
		IA32: New(87, "__ia32_sys_swapon"),
		X32:  New(167, "__x64_sys_swapon"),
	},
	"swapoff": X86_64{
		X64:  New(168, "__x64_sys_swapoff"),
		IA32: New(115, "__ia32_sys_swapoff"),
		X32:  New(168, "__x64_sys_swapoff"),
	},
	"reboot": X86_64{
		X64:  New(169, "__x64_sys_reboot"),
		IA32: New(88, "__ia32_sys_reboot"),
		X32:  New(169, "__x64_sys_reboot"),
	},
	"sethostname": X86_64{
		X64:  New(170, "__x64_sys_sethostname"),
		IA32: New(74, "__ia32_sys_sethostname"),
		X32:  New(170, "__x64_sys_sethostname"),
	},
	"setdomainname": X86_64{
		X64:  New(171, "__x64_sys_setdomainname"),
		IA32: New(121, "__ia32_sys_setdomainname"),
		X32:  New(171, "__x64_sys_setdomainname"),
	},
	"iopl": X86_64{
		X64:  New(172, "__x64_sys_iopl"),
		IA32: New(110, "__ia32_sys_iopl"),
		X32:  New(172, "__x64_sys_iopl"),
	},
	"ioperm": X86_64{
		X64:  New(173, "__x64_sys_ioperm"),
		IA32: New(101, "__ia32_sys_ioperm"),
		X32:  New(173, "__x64_sys_ioperm"),
	},
	"init_module": X86_64{
		X64:  New(175, "__x64_sys_init_module"),
		IA32: New(128, "__ia32_sys_init_module"),
		X32:  New(175, "__x64_sys_init_module"),
	},
	"delete_module": X86_64{
		X64:  New(176, "__x64_sys_delete_module"),
		IA32: New(129, "__ia32_sys_delete_module"),
		X32:  New(176, "__x64_sys_delete_module"),
	},
	"quotactl": X86_64{
		X64:  New(179, "__x64_sys_quotactl"),
		IA32: New(131, "__ia32_compat_sys_quotactl32"),
		X32:  New(179, "__x64_sys_quotactl"),
	},
	"gettid": X86_64{
		X64:  New(186, "__x64_sys_gettid"),
		IA32: New(224, "__ia32_sys_gettid"),
		X32:  New(186, "__x64_sys_gettid"),
	},
	"readahead": X86_64{
		X64:  New(187, "__x64_sys_readahead"),
		IA32: New(225, "__ia32_compat_sys_x86_readahead", "__ia32_compat_sys_ia32_readahead"),
		X32:  New(187, "__x64_sys_readahead"),
	},
	"setxattr": X86_64{
		X64:  New(188, "__x64_sys_setxattr"),
		IA32: New(226, "__ia32_sys_setxattr"),
		X32:  New(188, "__x64_sys_setxattr"),
	},
	"lsetxattr": X86_64{
		X64:  New(189, "__x64_sys_lsetxattr"),
		IA32: New(227, "__ia32_sys_lsetxattr"),
		X32:  New(189, "__x64_sys_lsetxattr"),
	},
	"fsetxattr": X86_64{
		X64:  New(190, "__x64_sys_fsetxattr"),
		IA32: New(228, "__ia32_sys_fsetxattr"),
		X32:  New(190, "__x64_sys_fsetxattr"),
	},
	"getxattr": X86_64{
		X64:  New(191, "__x64_sys_getxattr"),
		IA32: New(229, "__ia32_sys_getxattr"),
		X32:  New(191, "__x64_sys_getxattr"),
	},
	"lgetxattr": X86_64{
		X64:  New(192, "__x64_sys_lgetxattr"),
		IA32: New(230, "__ia32_sys_lgetxattr"),
		X32:  New(192, "__x64_sys_lgetxattr"),
	},
	"fgetxattr": X86_64{
		X64:  New(193, "__x64_sys_fgetxattr"),
		IA32: New(231, "__ia32_sys_fgetxattr"),
		X32:  New(193, "__x64_sys_fgetxattr"),
	},
	"listxattr": X86_64{
		X64:  New(194, "__x64_sys_listxattr"),
		IA32: New(232, "__ia32_sys_listxattr"),
		X32:  New(194, "__x64_sys_listxattr"),
	},
	"llistxattr": X86_64{
		X64:  New(195, "__x64_sys_llistxattr"),
		IA32: New(233, "__ia32_sys_llistxattr"),
		X32:  New(195, "__x64_sys_llistxattr"),
	},
	"flistxattr": X86_64{
		X64:  New(196, "__x64_sys_flistxattr"),
		IA32: New(234, "__ia32_sys_flistxattr"),
		X32:  New(196, "__x64_sys_flistxattr"),
	},
	"removexattr": X86_64{
		X64:  New(197, "__x64_sys_removexattr"),
		IA32: New(235, "__ia32_sys_removexattr"),
		X32:  New(197, "__x64_sys_removexattr"),
	},
	"lremovexattr": X86_64{
		X64:  New(198, "__x64_sys_lremovexattr"),
		IA32: New(236, "__ia32_sys_lremovexattr"),
		X32:  New(198, "__x64_sys_lremovexattr"),
	},
	"fremovexattr": X86_64{
		X64:  New(199, "__x64_sys_fremovexattr"),
		IA32: New(237, "__ia32_sys_fremovexattr"),
		X32:  New(199, "__x64_sys_fremovexattr"),
	},
	"tkill": X86_64{
		X64:  New(200, "__x64_sys_tkill"),
		IA32: New(238, "__ia32_sys_tkill"),
		X32:  New(200, "__x64_sys_tkill"),
	},
	"time": X86_64{
		X64:  New(201, "__x64_sys_time"),
		IA32: New(13, "__ia32_compat_sys_time", "__ia32_sys_time32"),
		X32:  New(201, "__x64_sys_time"),
	},
	"futex": X86_64{
		X64:  New(202, "__x64_sys_futex"),
		IA32: New(240, "__ia32_compat_sys_futex", "__ia32_sys_futex_time32"),
		X32:  New(202, "__x64_sys_futex"),
	},
	"sched_setaffinity": X86_64{
		X64:  New(203, "__x64_sys_sched_setaffinity"),
		IA32: New(241, "__ia32_compat_sys_sched_setaffinity"),
		X32:  New(203, "__x64_sys_sched_setaffinity"),
	},
	"sched_getaffinity": X86_64{
		X64:  New(204, "__x64_sys_sched_getaffinity"),
		IA32: New(242, "__ia32_compat_sys_sched_getaffinity"),
		X32:  New(204, "__x64_sys_sched_getaffinity"),
	},
	"io_setup": X86_64{
		X64:  New(206, "__x64_sys_io_setup"),
		IA32: New(245, "__ia32_compat_sys_io_setup"),
		X32:  New(543, "__x32_compat_sys_io_setup"),
	},
	"io_destroy": X86_64{
		X64:  New(207, "__x64_sys_io_destroy"),
		IA32: New(246, "__ia32_sys_io_destroy"),
		X32:  New(207, "__x64_sys_io_destroy"),
	},
	"io_getevents": X86_64{
		X64:  New(208, "__x64_sys_io_getevents"),
		IA32: New(247, "__ia32_compat_sys_io_getevents", "__ia32_sys_io_getevents_time32"),
		X32:  New(208, "__x64_sys_io_getevents"),
	},
	"io_submit": X86_64{
		X64:  New(209, "__x64_sys_io_submit"),
		IA32: New(248, "__ia32_compat_sys_io_submit"),
		X32:  New(544, "__x32_compat_sys_io_submit"),
	},
	"io_cancel": X86_64{
		X64:  New(210, "__x64_sys_io_cancel"),
		IA32: New(249, "__ia32_sys_io_cancel"),
		X32:  New(210, "__x64_sys_io_cancel"),
	},
	"lookup_dcookie": X86_64{
		X64:  New(212, "__x64_sys_lookup_dcookie"),
		IA32: New(253, "__ia32_compat_sys_lookup_dcookie"),
		X32:  New(212, "__x64_sys_lookup_dcookie"),
	},
	"epoll_create": X86_64{
		X64:  New(213, "__x64_sys_epoll_create"),
		IA32: New(254, "__ia32_sys_epoll_create"),
		X32:  New(213, "__x64_sys_epoll_create"),
	},
	"remap_file_pages": X86_64{
		X64:  New(216, "__x64_sys_remap_file_pages"),
		IA32: New(257, "__ia32_sys_remap_file_pages"),
		X32:  New(216, "__x64_sys_remap_file_pages"),
	},
	"getdents64": X86_64{
		X64:  New(217, "__x64_sys_getdents64"),
		IA32: New(220, "__ia32_sys_getdents64"),
		X32:  New(217, "__x64_sys_getdents64"),
	},
	"set_tid_address": X86_64{
		X64:  New(218, "__x64_sys_set_tid_address"),
		IA32: New(258, "__ia32_sys_set_tid_address"),
		X32:  New(218, "__x64_sys_set_tid_address"),
	},
	"restart_syscall": X86_64{
		X64:  New(219, "__x64_sys_restart_syscall"),
		IA32: New(0, "__ia32_sys_restart_syscall"),
		X32:  New(219, "__x64_sys_restart_syscall"),
	},
	"semtimedop": X86_64{
		X64:  New(220, "__x64_sys_semtimedop"),
		IA32: nil,
		X32:  New(220, "__x64_sys_semtimedop"),
	},
	"fadvise64": X86_64{
		X64:  New(221, "__x64_sys_fadvise64"),
		IA32: New(250, "__ia32_compat_sys_x86_fadvise64", "__ia32_compat_sys_ia32_fadvise64"),
		X32:  New(221, "__x64_sys_fadvise64"),
	},
	"timer_create": X86_64{
		X64:  New(222, "__x64_sys_timer_create"),
		IA32: New(259, "__ia32_compat_sys_timer_create"),
		X32:  New(526, "__x32_compat_sys_timer_create"),
	},
	"timer_settime": X86_64{
		X64:  New(223, "__x64_sys_timer_settime"),
		IA32: New(260, "__ia32_compat_sys_timer_settime", "__ia32_sys_timer_settime32"),
		X32:  New(223, "__x64_sys_timer_settime"),
	},
	"timer_gettime": X86_64{
		X64:  New(224, "__x64_sys_timer_gettime"),
		IA32: New(261, "__ia32_compat_sys_timer_gettime", "__ia32_sys_timer_gettime32"),
		X32:  New(224, "__x64_sys_timer_gettime"),
	},
	"timer_getoverrun": X86_64{
		X64:  New(225, "__x64_sys_timer_getoverrun"),
		IA32: New(262, "__ia32_sys_timer_getoverrun"),
		X32:  New(225, "__x64_sys_timer_getoverrun"),
	},
	"timer_delete": X86_64{
		X64:  New(226, "__x64_sys_timer_delete"),
		IA32: New(263, "__ia32_sys_timer_delete"),
		X32:  New(226, "__x64_sys_timer_delete"),
	},
	"clock_settime": X86_64{
		X64:  New(227, "__x64_sys_clock_settime"),
		IA32: New(264, "__ia32_compat_sys_clock_settime", "__ia32_sys_clock_settime32"),
		X32:  New(227, "__x64_sys_clock_settime"),
	},
	"clock_gettime": X86_64{
		X64:  New(228, "__x64_sys_clock_gettime"),
		IA32: New(265, "__ia32_compat_sys_clock_gettime", "__ia32_sys_clock_gettime32"),
		X32:  New(228, "__x64_sys_clock_gettime"),
	},
	"clock_getres": X86_64{
		X64:  New(229, "__x64_sys_clock_getres"),
		IA32: New(266, "__ia32_compat_sys_clock_getres", "__ia32_sys_clock_getres_time32"),
		X32:  New(229, "__x64_sys_clock_getres"),
	},
	"clock_nanosleep": X86_64{
		X64:  New(230, "__x64_sys_clock_nanosleep"),
		IA32: New(267, "__ia32_compat_sys_clock_nanosleep", "__ia32_sys_clock_nanosleep_time32"),
		X32:  New(230, "__x64_sys_clock_nanosleep"),
	},
	"exit_group": X86_64{
		X64:  New(231, "__x64_sys_exit_group"),
		IA32: New(252, "__ia32_sys_exit_group"),
		X32:  New(231, "__x64_sys_exit_group"),
	},
	"epoll_wait": X86_64{
		X64:  New(232, "__x64_sys_epoll_wait"),
		IA32: New(256, "__ia32_sys_epoll_wait"),
		X32:  New(232, "__x64_sys_epoll_wait"),
	},
	"epoll_ctl": X86_64{
		X64:  New(233, "__x64_sys_epoll_ctl"),
		IA32: New(255, "__ia32_sys_epoll_ctl"),
		X32:  New(233, "__x64_sys_epoll_ctl"),
	},
	"tgkill": X86_64{
		X64:  New(234, "__x64_sys_tgkill"),
		IA32: New(270, "__ia32_sys_tgkill"),
		X32:  New(234, "__x64_sys_tgkill"),
	},
	"utimes": X86_64{
		X64:  New(235, "__x64_sys_utimes"),
		IA32: New(271, "__ia32_compat_sys_utimes", "__ia32_sys_utimes_time32"),
		X32:  New(235, "__x64_sys_utimes"),
	},
	"mbind": X86_64{
		X64:  New(237, "__x64_sys_mbind"),
		IA32: New(274, "__ia32_sys_mbind"),
		X32:  New(237, "__x64_sys_mbind"),
	},
	"set_mempolicy": X86_64{
		X64:  New(238, "__x64_sys_set_mempolicy"),
		IA32: New(276, "__ia32_sys_set_mempolicy"),
		X32:  New(238, "__x64_sys_set_mempolicy"),
	},
	"get_mempolicy": X86_64{
		X64:  New(239, "__x64_sys_get_mempolicy"),
		IA32: New(275, "__ia32_compat_sys_get_mempolicy"),
		X32:  New(239, "__x64_sys_get_mempolicy"),
	},
	"mq_open": X86_64{
		X64:  New(240, "__x64_sys_mq_open"),
		IA32: New(277, "__ia32_compat_sys_mq_open"),
		X32:  New(240, "__x64_sys_mq_open"),
	},
	"mq_unlink": X86_64{
		X64:  New(241, "__x64_sys_mq_unlink"),
		IA32: New(278, "__ia32_sys_mq_unlink"),
		X32:  New(241, "__x64_sys_mq_unlink"),
	},
	"mq_timedsend": X86_64{
		X64:  New(242, "__x64_sys_mq_timedsend"),
		IA32: New(279, "__ia32_compat_sys_mq_timedsend", "__ia32_sys_mq_timedsend_time32"),
		X32:  New(242, "__x64_sys_mq_timedsend"),
	},
	"mq_timedreceive": X86_64{
		X64:  New(243, "__x64_sys_mq_timedreceive"),
		IA32: New(280, "__ia32_compat_sys_mq_timedreceive", "__ia32_sys_mq_timedreceive_time32"),
		X32:  New(243, "__x64_sys_mq_timedreceive"),
	},
	"mq_notify": X86_64{
		X64:  New(244, "__x64_sys_mq_notify"),
		IA32: New(281, "__ia32_compat_sys_mq_notify"),
		X32:  New(527, "__x32_compat_sys_mq_notify"),
	},
	"mq_getsetattr": X86_64{
		X64:  New(245, "__x64_sys_mq_getsetattr"),
		IA32: New(282, "__ia32_compat_sys_mq_getsetattr"),
		X32:  New(245, "__x64_sys_mq_getsetattr"),
	},
	"kexec_load": X86_64{
		X64:  New(246, "__x64_sys_kexec_load"),
		IA32: New(283, "__ia32_compat_sys_kexec_load"),
		X32:  New(528, "__x32_compat_sys_kexec_load"),
	},
	"waitid": X86_64{
		X64:  New(247, "__x64_sys_waitid"),
		IA32: New(284, "__ia32_compat_sys_waitid"),
		X32:  New(529, "__x32_compat_sys_waitid"),
	},
	"add_key": X86_64{
		X64:  New(248, "__x64_sys_add_key"),
		IA32: New(286, "__ia32_sys_add_key"),
		X32:  New(248, "__x64_sys_add_key"),
	},
	"request_key": X86_64{
		X64:  New(249, "__x64_sys_request_key"),
		IA32: New(287, "__ia32_sys_request_key"),
		X32:  New(249, "__x64_sys_request_key"),
	},
	"keyctl": X86_64{
		X64:  New(250, "__x64_sys_keyctl"),
		IA32: New(288, "__ia32_compat_sys_keyctl"),
		X32:  New(250, "__x64_sys_keyctl"),
	},
	"ioprio_set": X86_64{
		X64:  New(251, "__x64_sys_ioprio_set"),
		IA32: New(289, "__ia32_sys_ioprio_set"),
		X32:  New(251, "__x64_sys_ioprio_set"),
	},
	"ioprio_get": X86_64{
		X64:  New(252, "__x64_sys_ioprio_get"),
		IA32: New(290, "__ia32_sys_ioprio_get"),
		X32:  New(252, "__x64_sys_ioprio_get"),
	},
	"inotify_init": X86_64{
		X64:  New(253, "__x64_sys_inotify_init"),
		IA32: New(291, "__ia32_sys_inotify_init"),
		X32:  New(253, "__x64_sys_inotify_init"),
	},
	"inotify_add_watch": X86_64{
		X64:  New(254, "__x64_sys_inotify_add_watch"),
		IA32: New(292, "__ia32_sys_inotify_add_watch"),
		X32:  New(254, "__x64_sys_inotify_add_watch"),
	},
	"inotify_rm_watch": X86_64{
		X64:  New(255, "__x64_sys_inotify_rm_watch"),
		IA32: New(293, "__ia32_sys_inotify_rm_watch"),
		X32:  New(255, "__x64_sys_inotify_rm_watch"),
	},
	"migrate_pages": X86_64{
		X64:  New(256, "__x64_sys_migrate_pages"),
		IA32: New(294, "__ia32_sys_migrate_pages"),
		X32:  New(256, "__x64_sys_migrate_pages"),
	},
	"openat": X86_64{
		X64:  New(257, "__x64_sys_openat"),
		IA32: New(295, "__ia32_compat_sys_openat"),
		X32:  New(257, "__x64_sys_openat"),
	},
	"mkdirat": X86_64{
		X64:  New(258, "__x64_sys_mkdirat"),
		IA32: New(296, "__ia32_sys_mkdirat"),
		X32:  New(258, "__x64_sys_mkdirat"),
	},
	"mknodat": X86_64{
		X64:  New(259, "__x64_sys_mknodat"),
		IA32: New(297, "__ia32_sys_mknodat"),
		X32:  New(259, "__x64_sys_mknodat"),
	},
	"fchownat": X86_64{
		X64:  New(260, "__x64_sys_fchownat"),
		IA32: New(298, "__ia32_sys_fchownat"),
		X32:  New(260, "__x64_sys_fchownat"),
	},
	"futimesat": X86_64{
		X64:  New(261, "__x64_sys_futimesat"),
		IA32: New(299, "__ia32_compat_sys_futimesat", "__ia32_sys_futimesat_time32"),
		X32:  New(261, "__x64_sys_futimesat"),
	},
	"newfstatat": X86_64{
		X64:  New(262, "__x64_sys_newfstatat"),
		IA32: nil,
		X32:  New(262, "__x64_sys_newfstatat"),
	},
	"unlinkat": X86_64{
		X64:  New(263, "__x64_sys_unlinkat"),
		IA32: New(301, "__ia32_sys_unlinkat"),
		X32:  New(263, "__x64_sys_unlinkat"),
	},
	"renameat": X86_64{
		X64:  New(264, "__x64_sys_renameat"),
		IA32: New(302, "__ia32_sys_renameat"),
		X32:  New(264, "__x64_sys_renameat"),
	},
	"linkat": X86_64{
		X64:  New(265, "__x64_sys_linkat"),
		IA32: New(303, "__ia32_sys_linkat"),
		X32:  New(265, "__x64_sys_linkat"),
	},
	"symlinkat": X86_64{
		X64:  New(266, "__x64_sys_symlinkat"),
		IA32: New(304, "__ia32_sys_symlinkat"),
		X32:  New(266, "__x64_sys_symlinkat"),
	},
	"readlinkat": X86_64{
		X64:  New(267, "__x64_sys_readlinkat"),
		IA32: New(305, "__ia32_sys_readlinkat"),
		X32:  New(267, "__x64_sys_readlinkat"),
	},
	"fchmodat": X86_64{
		X64:  New(268, "__x64_sys_fchmodat"),
		IA32: New(306, "__ia32_sys_fchmodat"),
		X32:  New(268, "__x64_sys_fchmodat"),
	},
	"faccessat": X86_64{
		X64:  New(269, "__x64_sys_faccessat"),
		IA32: New(307, "__ia32_sys_faccessat"),
		X32:  New(269, "__x64_sys_faccessat"),
	},
	"pselect6": X86_64{
		X64:  New(270, "__x64_sys_pselect6"),
		IA32: New(308, "__ia32_compat_sys_pselect6", "__ia32_compat_sys_pselect6_time32"),
		X32:  New(270, "__x64_sys_pselect6"),
	},
	"ppoll": X86_64{
		X64:  New(271, "__x64_sys_ppoll"),
		IA32: New(309, "__ia32_compat_sys_ppoll", "__ia32_compat_sys_ppoll_time32"),
		X32:  New(271, "__x64_sys_ppoll"),
	},
	"unshare": X86_64{
		X64:  New(272, "__x64_sys_unshare"),
		IA32: New(310, "__ia32_sys_unshare"),
		X32:  New(272, "__x64_sys_unshare"),
	},
	"set_robust_list": X86_64{
		X64:  New(273, "__x64_sys_set_robust_list"),
		IA32: New(311, "__ia32_compat_sys_set_robust_list"),
		X32:  New(530, "__x32_compat_sys_set_robust_list"),
	},
	"get_robust_list": X86_64{
		X64:  New(274, "__x64_sys_get_robust_list"),
		IA32: New(312, "__ia32_compat_sys_get_robust_list"),
		X32:  New(531, "__x32_compat_sys_get_robust_list"),
	},
	"splice": X86_64{
		X64:  New(275, "__x64_sys_splice"),
		IA32: New(313, "__ia32_sys_splice"),
		X32:  New(275, "__x64_sys_splice"),
	},
	"tee": X86_64{
		X64:  New(276, "__x64_sys_tee"),
		IA32: New(315, "__ia32_sys_tee"),
		X32:  New(276, "__x64_sys_tee"),
	},
	"sync_file_range": X86_64{
		X64:  New(277, "__x64_sys_sync_file_range"),
		IA32: New(314, "__ia32_compat_sys_x86_sync_file_range", "__ia32_compat_sys_ia32_sync_file_range"),
		X32:  New(277, "__x64_sys_sync_file_range"),
	},
	"vmsplice": X86_64{
		X64:  New(278, "__x64_sys_vmsplice"),
		IA32: New(316, "__ia32_compat_sys_vmsplice"),
		X32:  New(532, "__x32_compat_sys_vmsplice", "__x32_sys_vmsplice"),
	},
	"move_pages": X86_64{
		X64:  New(279, "__x64_sys_move_pages"),
		IA32: New(317, "__ia32_compat_sys_move_pages"),
		X32:  New(533, "__x32_compat_sys_move_pages", "__x32_sys_move_pages"),
	},
	"utimensat": X86_64{
		X64:  New(280, "__x64_sys_utimensat"),
		IA32: New(320, "__ia32_compat_sys_utimensat", "__ia32_sys_utimensat_time32"),
		X32:  New(280, "__x64_sys_utimensat"),
	},
	"epoll_pwait": X86_64{
		X64:  New(281, "__x64_sys_epoll_pwait"),
		IA32: New(319, "__ia32_sys_epoll_pwait"),
		X32:  New(281, "__x64_sys_epoll_pwait"),
	},
	"signalfd": X86_64{
		X64:  New(282, "__x64_sys_signalfd"),
		IA32: New(321, "__ia32_compat_sys_signalfd"),
		X32:  New(282, "__x64_sys_signalfd"),
	},
	"timerfd_create": X86_64{
		X64:  New(283, "__x64_sys_timerfd_create"),
		IA32: New(322, "__ia32_sys_timerfd_create"),
		X32:  New(283, "__x64_sys_timerfd_create"),
	},
	"eventfd": X86_64{
		X64:  New(284, "__x64_sys_eventfd"),
		IA32: New(323, "__ia32_sys_eventfd"),
		X32:  New(284, "__x64_sys_eventfd"),
	},
	"fallocate": X86_64{
		X64:  New(285, "__x64_sys_fallocate"),
		IA32: New(324, "__ia32_compat_sys_x86_fallocate", "__ia32_compat_sys_ia32_fallocate"),
		X32:  New(285, "__x64_sys_fallocate"),
	},
	"timerfd_settime": X86_64{
		X64:  New(286, "__x64_sys_timerfd_settime"),
		IA32: New(325, "__ia32_compat_sys_timerfd_settime", "__ia32_sys_timerfd_settime32"),
		X32:  New(286, "__x64_sys_timerfd_settime"),
	},
	"timerfd_gettime": X86_64{
		X64:  New(287, "__x64_sys_timerfd_gettime"),
		IA32: New(326, "__ia32_compat_sys_timerfd_gettime", "__ia32_sys_timerfd_gettime32"),
		X32:  New(287, "__x64_sys_timerfd_gettime"),
	},
	"accept4": X86_64{
		X64:  New(288, "__x64_sys_accept4"),
		IA32: New(364, "__ia32_sys_accept4"),
		X32:  New(288, "__x64_sys_accept4"),
	},
	"signalfd4": X86_64{
		X64:  New(289, "__x64_sys_signalfd4"),
		IA32: New(327, "__ia32_compat_sys_signalfd4"),
		X32:  New(289, "__x64_sys_signalfd4"),
	},
	"eventfd2": X86_64{
		X64:  New(290, "__x64_sys_eventfd2"),
		IA32: New(328, "__ia32_sys_eventfd2"),
		X32:  New(290, "__x64_sys_eventfd2"),
	},
	"epoll_create1": X86_64{
		X64:  New(291, "__x64_sys_epoll_create1"),
		IA32: New(329, "__ia32_sys_epoll_create1"),
		X32:  New(291, "__x64_sys_epoll_create1"),
	},
	"dup3": X86_64{
		X64:  New(292, "__x64_sys_dup3"),
		IA32: New(330, "__ia32_sys_dup3"),
		X32:  New(292, "__x64_sys_dup3"),
	},
	"pipe2": X86_64{
		X64:  New(293, "__x64_sys_pipe2"),
		IA32: New(331, "__ia32_sys_pipe2"),
		X32:  New(293, "__x64_sys_pipe2"),
	},
	"inotify_init1": X86_64{
		X64:  New(294, "__x64_sys_inotify_init1"),
		IA32: New(332, "__ia32_sys_inotify_init1"),
		X32:  New(294, "__x64_sys_inotify_init1"),
	},
	"preadv": X86_64{
		X64:  New(295, "__x64_sys_preadv"),
		IA32: New(333, "__ia32_compat_sys_preadv"),
		X32:  New(534, "__x32_compat_sys_preadv64"),
	},
	"pwritev": X86_64{
		X64:  New(296, "__x64_sys_pwritev"),
		IA32: New(334, "__ia32_compat_sys_pwritev"),
		X32:  New(535, "__x32_compat_sys_pwritev64"),
	},
	"rt_tgsigqueueinfo": X86_64{
		X64:  New(297, "__x64_sys_rt_tgsigqueueinfo"),
		IA32: New(335, "__ia32_compat_sys_rt_tgsigqueueinfo"),
		X32:  New(536, "__x32_compat_sys_rt_tgsigqueueinfo"),
	},
	"perf_event_open": X86_64{
		X64:  New(298, "__x64_sys_perf_event_open"),
		IA32: New(336, "__ia32_sys_perf_event_open"),
		X32:  New(298, "__x64_sys_perf_event_open"),
	},
	"recvmmsg": X86_64{
		X64:  New(299, "__x64_sys_recvmmsg"),
		IA32: New(337, "__ia32_compat_sys_recvmmsg", "__ia32_compat_sys_recvmmsg_time32"),
		X32:  New(537, "__x32_compat_sys_recvmmsg", "__x32_compat_sys_recvmmsg_time64"),
	},
	"fanotify_init": X86_64{
		X64:  New(300, "__x64_sys_fanotify_init"),
		IA32: New(338, "__ia32_sys_fanotify_init"),
		X32:  New(300, "__x64_sys_fanotify_init"),
	},
	"fanotify_mark": X86_64{
		X64:  New(301, "__x64_sys_fanotify_mark"),
		IA32: New(339, "__ia32_compat_sys_fanotify_mark"),
		X32:  New(301, "__x64_sys_fanotify_mark"),
	},
	"prlimit64": X86_64{
		X64:  New(302, "__x64_sys_prlimit64"),
		IA32: New(340, "__ia32_sys_prlimit64"),
		X32:  New(302, "__x64_sys_prlimit64"),
	},
	"name_to_handle_at": X86_64{
		X64:  New(303, "__x64_sys_name_to_handle_at"),
		IA32: New(341, "__ia32_sys_name_to_handle_at"),
		X32:  New(303, "__x64_sys_name_to_handle_at"),
	},
	"open_by_handle_at": X86_64{
		X64:  New(304, "__x64_sys_open_by_handle_at"),
		IA32: New(342, "__ia32_compat_sys_open_by_handle_at"),
		X32:  New(304, "__x64_sys_open_by_handle_at"),
	},
	"clock_adjtime": X86_64{
		X64:  New(305, "__x64_sys_clock_adjtime"),
		IA32: New(343, "__ia32_compat_sys_clock_adjtime", "__ia32_sys_clock_adjtime32"),
		X32:  New(305, "__x64_sys_clock_adjtime"),
	},
	"syncfs": X86_64{
		X64:  New(306, "__x64_sys_syncfs"),
		IA32: New(344, "__ia32_sys_syncfs"),
		X32:  New(306, "__x64_sys_syncfs"),
	},
	"sendmmsg": X86_64{
		X64:  New(307, "__x64_sys_sendmmsg"),
		IA32: New(345, "__ia32_compat_sys_sendmmsg"),
		X32:  New(538, "__x32_compat_sys_sendmmsg"),
	},
	"setns": X86_64{
		X64:  New(308, "__x64_sys_setns"),
		IA32: New(346, "__ia32_sys_setns"),
		X32:  New(308, "__x64_sys_setns"),
	},
	"getcpu": X86_64{
		X64:  New(309, "__x64_sys_getcpu"),
		IA32: New(318, "__ia32_sys_getcpu"),
		X32:  New(309, "__x64_sys_getcpu"),
	},
	"process_vm_readv": X86_64{
		X64:  New(310, "__x64_sys_process_vm_readv"),
		IA32: New(347, "__ia32_compat_sys_process_vm_readv"),
		X32:  New(539, "__x32_compat_sys_process_vm_readv", "__x32_sys_process_vm_readv"),
	},
	"process_vm_writev": X86_64{
		X64:  New(311, "__x64_sys_process_vm_writev"),
		IA32: New(348, "__ia32_compat_sys_process_vm_writev"),
		X32:  New(540, "__x32_compat_sys_process_vm_writev", "__x32_sys_process_vm_writev"),
	},
	"kcmp": X86_64{
		X64:  New(312, "__x64_sys_kcmp"),
		IA32: New(349, "__ia32_sys_kcmp"),
		X32:  New(312, "__x64_sys_kcmp"),
	},
	"finit_module": X86_64{
		X64:  New(313, "__x64_sys_finit_module"),
		IA32: New(350, "__ia32_sys_finit_module"),
		X32:  New(313, "__x64_sys_finit_module"),
	},
	"sched_setattr": X86_64{
		X64:  New(314, "__x64_sys_sched_setattr"),
		IA32: New(351, "__ia32_sys_sched_setattr"),
		X32:  New(314, "__x64_sys_sched_setattr"),
	},
	"sched_getattr": X86_64{
		X64:  New(315, "__x64_sys_sched_getattr"),
		IA32: New(352, "__ia32_sys_sched_getattr"),
		X32:  New(315, "__x64_sys_sched_getattr"),
	},
	"renameat2": X86_64{
		X64:  New(316, "__x64_sys_renameat2"),
		IA32: New(353, "__ia32_sys_renameat2"),
		X32:  New(316, "__x64_sys_renameat2"),
	},
	"seccomp": X86_64{
		X64:  New(317, "__x64_sys_seccomp"),
		IA32: New(354, "__ia32_sys_seccomp"),
		X32:  New(317, "__x64_sys_seccomp"),
	},
	"getrandom": X86_64{
		X64:  New(318, "__x64_sys_getrandom"),
		IA32: New(355, "__ia32_sys_getrandom"),
		X32:  New(318, "__x64_sys_getrandom"),
	},
	"memfd_create": X86_64{
		X64:  New(319, "__x64_sys_memfd_create"),
		IA32: New(356, "__ia32_sys_memfd_create"),
		X32:  New(319, "__x64_sys_memfd_create"),
	},
	"kexec_file_load": X86_64{
		X64:  New(320, "__x64_sys_kexec_file_load"),
		IA32: nil,
		X32:  New(320, "__x64_sys_kexec_file_load"),
	},
	"bpf": X86_64{
		X64:  New(321, "__x64_sys_bpf"),
		IA32: New(357, "__ia32_sys_bpf"),
		X32:  New(321, "__x64_sys_bpf"),
	},
	"execveat": X86_64{
		X64:  New(322, "__x64_sys_execveat"),
		IA32: New(358, "__ia32_compat_sys_execveat"),
		X32:  New(545, "__x32_compat_sys_execveat"),
	},
	"userfaultfd": X86_64{
		X64:  New(323, "__x64_sys_userfaultfd"),
		IA32: New(374, "__ia32_sys_userfaultfd"),
		X32:  New(323, "__x64_sys_userfaultfd"),
	},
	"membarrier": X86_64{
		X64:  New(324, "__x64_sys_membarrier"),
		IA32: New(375, "__ia32_sys_membarrier"),
		X32:  New(324, "__x64_sys_membarrier"),
	},
	"mlock2": X86_64{
		X64:  New(325, "__x64_sys_mlock2"),
		IA32: New(376, "__ia32_sys_mlock2"),
		X32:  New(325, "__x64_sys_mlock2"),
	},
	"copy_file_range": X86_64{
		X64:  New(326, "__x64_sys_copy_file_range"),
		IA32: New(377, "__ia32_sys_copy_file_range"),
		X32:  New(326, "__x64_sys_copy_file_range"),
	},
	"preadv2": X86_64{
		X64:  New(327, "__x64_sys_preadv2"),
		IA32: New(378, "__ia32_compat_sys_preadv2"),
		X32:  New(546, "__x32_compat_sys_preadv64v2"),
	},
	"pwritev2": X86_64{
		X64:  New(328, "__x64_sys_pwritev2"),
		IA32: New(379, "__ia32_compat_sys_pwritev2"),
		X32:  New(547, "__x32_compat_sys_pwritev64v2"),
	},
	"pkey_mprotect": X86_64{
		X64:  New(329, "__x64_sys_pkey_mprotect"),
		IA32: New(380, "__ia32_sys_pkey_mprotect"),
		X32:  New(329, "__x64_sys_pkey_mprotect"),
	},
	"pkey_alloc": X86_64{
		X64:  New(330, "__x64_sys_pkey_alloc"),
		IA32: New(381, "__ia32_sys_pkey_alloc"),
		X32:  New(330, "__x64_sys_pkey_alloc"),
	},
	"pkey_free": X86_64{
		X64:  New(331, "__x64_sys_pkey_free"),
		IA32: New(382, "__ia32_sys_pkey_free"),
		X32:  New(331, "__x64_sys_pkey_free"),
	},
	"statx": X86_64{
		X64:  New(332, "__x64_sys_statx"),
		IA32: New(383, "__ia32_sys_statx"),
		X32:  New(332, "__x64_sys_statx"),
	},
	"io_pgetevents": X86_64{
		X64:  New(333, "__x64_sys_io_pgetevents"),
		IA32: New(385, "__ia32_compat_sys_io_pgetevents"),
		X32:  New(333, "__x64_sys_io_pgetevents"),
	},
	"rseq": X86_64{
		X64:  New(334, "__x64_sys_rseq"),
		IA32: New(386, "__ia32_sys_rseq"),
		X32:  New(334, "__x64_sys_rseq"),
	},
	"pidfd_send_signal": X86_64{
		X64:  New(424, "__x64_sys_pidfd_send_signal"),
		IA32: New(424, "__ia32_sys_pidfd_send_signal"),
		X32:  New(424, "__x64_sys_pidfd_send_signal"),
	},
	"io_uring_setup": X86_64{
		X64:  New(425, "__x64_sys_io_uring_setup"),
		IA32: New(425, "__ia32_sys_io_uring_setup"),
		X32:  New(425, "__x64_sys_io_uring_setup"),
	},
	"io_uring_enter": X86_64{
		X64:  New(426, "__x64_sys_io_uring_enter"),
		IA32: New(426, "__ia32_sys_io_uring_enter"),
		X32:  New(426, "__x64_sys_io_uring_enter"),
	},
	"io_uring_register": X86_64{
		X64:  New(427, "__x64_sys_io_uring_register"),
		IA32: New(427, "__ia32_sys_io_uring_register"),
		X32:  New(427, "__x64_sys_io_uring_register"),
	},
	"open_tree": X86_64{
		X64:  New(428, "__x64_sys_open_tree"),
		IA32: New(428, "__ia32_sys_open_tree"),
		X32:  New(428, "__x64_sys_open_tree"),
	},
	"move_mount": X86_64{
		X64:  New(429, "__x64_sys_move_mount"),
		IA32: New(429, "__ia32_sys_move_mount"),
		X32:  New(429, "__x64_sys_move_mount"),
	},
	"fsopen": X86_64{
		X64:  New(430, "__x64_sys_fsopen"),
		IA32: New(430, "__ia32_sys_fsopen"),
		X32:  New(430, "__x64_sys_fsopen"),
	},
	"fsconfig": X86_64{
		X64:  New(431, "__x64_sys_fsconfig"),
		IA32: New(431, "__ia32_sys_fsconfig"),
		X32:  New(431, "__x64_sys_fsconfig"),
	},
	"fsmount": X86_64{
		X64:  New(432, "__x64_sys_fsmount"),
		IA32: New(432, "__ia32_sys_fsmount"),
		X32:  New(432, "__x64_sys_fsmount"),
	},
	"fspick": X86_64{
		X64:  New(433, "__x64_sys_fspick"),
		IA32: New(433, "__ia32_sys_fspick"),
		X32:  New(433, "__x64_sys_fspick"),
	},
	"pidfd_open": X86_64{
		X64:  New(434, "__x64_sys_pidfd_open"),
		IA32: New(434, "__ia32_sys_pidfd_open"),
		X32:  New(434, "__x64_sys_pidfd_open"),
	},
	"clone3": X86_64{
		X64:  New(435, "__x64_sys_clone3"),
		IA32: New(435, "__ia32_sys_clone3"),
		X32:  New(435, "__x64_sys_clone3"),
	},
	"close_range": X86_64{
		X64:  New(436, "__x64_sys_close_range"),
		IA32: nil,
		X32:  New(436, "__x64_sys_close_range"),
	},
	"openat2": X86_64{
		X64:  New(437, "__x64_sys_openat2"),
		IA32: New(437, "__ia32_sys_openat2"),
		X32:  New(437, "__x64_sys_openat2"),
	},
	"pidfd_getfd": X86_64{
		X64:  New(438, "__x64_sys_pidfd_getfd"),
		IA32: New(438, "__ia32_sys_pidfd_getfd"),
		X32:  New(438, "__x64_sys_pidfd_getfd"),
	},
	"faccessat2": X86_64{
		X64:  New(439, "__x64_sys_faccessat2"),
		IA32: nil,
		X32:  New(439, "__x64_sys_faccessat2"),
	},
	"process_madvise": X86_64{
		X64:  New(440, "__x64_sys_process_madvise"),
		IA32: nil,
		X32:  New(440, "__x64_sys_process_madvise"),
	},
	"epoll_pwait2": X86_64{
		X64:  New(441, "__x64_sys_epoll_pwait2"),
		IA32: New(441, "__ia32_compat_sys_epoll_pwait2"),
		X32:  New(441, "__x64_sys_epoll_pwait2"),
	},
	"mount_setattr": X86_64{
		X64:  New(442, "__x64_sys_mount_setattr"),
		IA32: nil,
		X32:  New(442, "__x64_sys_mount_setattr"),
	},
	"quotactl_path": X86_64{
		X64:  New(443, "__x64_sys_quotactl_path"),
		IA32: nil,
		X32:  New(443, "__x64_sys_quotactl_path"),
	},
	"quotactl_fd": X86_64{
		X64:  New(443, "__x64_sys_quotactl_fd"),
		IA32: nil,
		X32:  New(443, "__x64_sys_quotactl_fd"),
	},
	"landlock_create_ruleset": X86_64{
		X64:  New(444, "__x64_sys_landlock_create_ruleset"),
		IA32: nil,
		X32:  New(444, "__x64_sys_landlock_create_ruleset"),
	},
	"landlock_add_rule": X86_64{
		X64:  New(445, "__x64_sys_landlock_add_rule"),
		IA32: nil,
		X32:  New(445, "__x64_sys_landlock_add_rule"),
	},
	"landlock_restrict_self": X86_64{
		X64:  New(446, "__x64_sys_landlock_restrict_self"),
		IA32: nil,
		X32:  New(446, "__x64_sys_landlock_restrict_self"),
	},
	"memfd_secret": X86_64{
		X64:  New(447, "__x64_sys_memfd_secret"),
		IA32: nil,
		X32:  New(447, "__x64_sys_memfd_secret"),
	},
	"process_mrelease": X86_64{
		X64:  New(448, "__x64_sys_process_mrelease"),
		IA32: nil,
		X32:  New(448, "__x64_sys_process_mrelease"),
	},
	"futex_waitv": X86_64{
		X64:  New(449, "__x64_sys_futex_waitv"),
		IA32: nil,
		X32:  New(449, "__x64_sys_futex_waitv"),
	},
	"set_mempolicy_home_node": X86_64{
		X64:  New(450, "__x64_sys_set_mempolicy_home_node"),
		IA32: nil,
		X32:  New(450, "__x64_sys_set_mempolicy_home_node"),
	},
	"cachestat": X86_64{
		X64:  New(451, "__x64_sys_cachestat"),
		IA32: nil,
		X32:  New(451, "__x64_sys_cachestat"),
	},
	"fchmodat2": X86_64{
		X64:  New(452, "__x64_sys_fchmodat2"),
		IA32: nil,
		X32:  New(452, "__x64_sys_fchmodat2"),
	},
	"map_shadow_stack": X86_64{
		X64:  New(453, "__x64_sys_map_shadow_stack"),
		IA32: nil,
		X32:  New(453, "__x64_sys_map_shadow_stack"),
	},
	"futex_wake": X86_64{
		X64:  New(454, "__x64_sys_futex_wake"),
		IA32: nil,
		X32:  New(454, "__x64_sys_futex_wake"),
	},
	"futex_wait": X86_64{
		X64:  New(455, "__x64_sys_futex_wait"),
		IA32: nil,
		X32:  New(455, "__x64_sys_futex_wait"),
	},
	"futex_requeue": X86_64{
		X64:  New(456, "__x64_sys_futex_requeue"),
		IA32: nil,
		X32:  New(456, "__x64_sys_futex_requeue"),
	},
	"lsm_get_self_attr": X86_64{
		X64:  New(457, "__x64_sys_lsm_get_self_attr"),
		IA32: nil,
		X32:  New(457, "__x64_sys_lsm_get_self_attr"),
	},
	"statmount": X86_64{
		X64:  New(457, "__x64_sys_statmount"),
		IA32: nil,
		X32:  New(457, "__x64_sys_statmount"),
	},
	"listmount": X86_64{
		X64:  New(458, "__x64_sys_listmount"),
		IA32: nil,
		X32:  New(458, "__x64_sys_listmount"),
	},
	"lsm_set_self_attr": X86_64{
		X64:  New(458, "__x64_sys_lsm_set_self_attr"),
		IA32: nil,
		X32:  New(458, "__x64_sys_lsm_set_self_attr"),
	},
	"lsm_list_modules": X86_64{
		X64:  New(459, "__x64_sys_lsm_list_modules"),
		IA32: nil,
		X32:  New(459, "__x64_sys_lsm_list_modules"),
	},
	"mseal": X86_64{
		X64:  New(462, "__x64_sys_mseal"),
		IA32: nil,
		X32:  New(462, "__x64_sys_mseal"),
	},
	"waitpid": X86_64{
		X64:  nil,
		IA32: New(7, "__ia32_sys_waitpid"),
		X32:  nil,
	},
	"oldstat": X86_64{
		X64:  nil,
		IA32: New(18, "__ia32_sys_stat"),
		X32:  nil,
	},
	"umount": X86_64{
		X64:  nil,
		IA32: New(22, "__ia32_sys_oldumount"),
		X32:  nil,
	},
	"stime": X86_64{
		X64:  nil,
		IA32: New(25, "__ia32_compat_sys_stime", "__ia32_sys_stime32"),
		X32:  nil,
	},
	"oldfstat": X86_64{
		X64:  nil,
		IA32: New(28, "__ia32_sys_fstat"),
		X32:  nil,
	},
	"nice": X86_64{
		X64:  nil,
		IA32: New(34, "__ia32_sys_nice"),
		X32:  nil,
	},
	"signal": X86_64{
		X64:  nil,
		IA32: New(48, "__ia32_sys_signal"),
		X32:  nil,
	},
	"oldolduname": X86_64{
		X64:  nil,
		IA32: New(59, "__ia32_sys_olduname"),
		X32:  nil,
	},
	"sigaction": X86_64{
		X64:  nil,
		IA32: New(67, "__ia32_compat_sys_sigaction"),
		X32:  nil,
	},
	"sgetmask": X86_64{
		X64:  nil,
		IA32: New(68, "__ia32_sys_sgetmask"),
		X32:  nil,
	},
	"ssetmask": X86_64{
		X64:  nil,
		IA32: New(69, "__ia32_sys_ssetmask"),
		X32:  nil,
	},
	"sigsuspend": X86_64{
		X64:  nil,
		IA32: New(72, "__ia32_sys_sigsuspend"),
		X32:  nil,
	},
	"sigpending": X86_64{
		X64:  nil,
		IA32: New(73, "__ia32_compat_sys_sigpending"),
		X32:  nil,
	},
	"oldlstat": X86_64{
		X64:  nil,
		IA32: New(84, "__ia32_sys_lstat"),
		X32:  nil,
	},
	"uselib": X86_64{
		X64:  nil,
		IA32: New(86, "__ia32_sys_uselib"),
		X32:  nil,
	},
	"readdir": X86_64{
		X64:  nil,
		IA32: New(89, "__ia32_compat_sys_old_readdir"),
		X32:  nil,
	},
	"socketcall": X86_64{
		X64:  nil,
		IA32: New(102, "__ia32_compat_sys_socketcall"),
		X32:  nil,
	},
	"olduname": X86_64{
		X64:  nil,
		IA32: New(109, "__ia32_sys_uname"),
		X32:  nil,
	},
	"ipc": X86_64{
		X64:  nil,
		IA32: New(117, "__ia32_compat_sys_ipc"),
		X32:  nil,
	},
	"sigreturn": X86_64{
		X64:  nil,
		IA32: New(119, "sys32_sigreturn", "__ia32_compat_sys_sigreturn"),
		X32:  nil,
	},
	"sigprocmask": X86_64{
		X64:  nil,
		IA32: New(126, "__ia32_compat_sys_sigprocmask"),
		X32:  nil,
	},
	"bdflush": X86_64{
		X64:  nil,
		IA32: New(134, "__ia32_sys_bdflush"),
		X32:  nil,
	},
	"_llseek": X86_64{
		X64:  nil,
		IA32: New(140, "__ia32_sys_llseek"),
		X32:  nil,
	},
	"_newselect": X86_64{
		X64:  nil,
		IA32: New(142, "__ia32_compat_sys_select"),
		X32:  nil,
	},
	"ugetrlimit": X86_64{
		X64:  nil,
		IA32: New(191, "__ia32_compat_sys_getrlimit"),
		X32:  nil,
	},
	"mmap2": X86_64{
		X64:  nil,
		IA32: New(192, "__ia32_sys_mmap_pgoff"),
		X32:  nil,
	},
	"truncate64": X86_64{
		X64:  nil,
		IA32: New(193, "__ia32_compat_sys_x86_truncate64", "__ia32_compat_sys_ia32_truncate64"),
		X32:  nil,
	},
	"ftruncate64": X86_64{
		X64:  nil,
		IA32: New(194, "__ia32_compat_sys_x86_ftruncate64", "__ia32_compat_sys_ia32_ftruncate64"),
		X32:  nil,
	},
	"stat64": X86_64{
		X64:  nil,
		IA32: New(195, "__ia32_compat_sys_x86_stat64", "__ia32_compat_sys_ia32_stat64"),
		X32:  nil,
	},
	"lstat64": X86_64{
		X64:  nil,
		IA32: New(196, "__ia32_compat_sys_x86_lstat64", "__ia32_compat_sys_ia32_lstat64"),
		X32:  nil,
	},
	"fstat64": X86_64{
		X64:  nil,
		IA32: New(197, "__ia32_compat_sys_x86_fstat64", "__ia32_compat_sys_ia32_fstat64"),
		X32:  nil,
	},
	"lchown32": X86_64{
		X64:  nil,
		IA32: New(198, "__ia32_sys_lchown"),
		X32:  nil,
	},
	"getuid32": X86_64{
		X64:  nil,
		IA32: New(199, "__ia32_sys_getuid"),
		X32:  nil,
	},
	"getgid32": X86_64{
		X64:  nil,
		IA32: New(200, "__ia32_sys_getgid"),
		X32:  nil,
	},
	"geteuid32": X86_64{
		X64:  nil,
		IA32: New(201, "__ia32_sys_geteuid"),
		X32:  nil,
	},
	"getegid32": X86_64{
		X64:  nil,
		IA32: New(202, "__ia32_sys_getegid"),
		X32:  nil,
	},
	"setreuid32": X86_64{
		X64:  nil,
		IA32: New(203, "__ia32_sys_setreuid"),
		X32:  nil,
	},
	"setregid32": X86_64{
		X64:  nil,
		IA32: New(204, "__ia32_sys_setregid"),
		X32:  nil,
	},
	"getgroups32": X86_64{
		X64:  nil,
		IA32: New(205, "__ia32_sys_getgroups"),
		X32:  nil,
	},
	"setgroups32": X86_64{
		X64:  nil,
		IA32: New(206, "__ia32_sys_setgroups"),
		X32:  nil,
	},
	"fchown32": X86_64{
		X64:  nil,
		IA32: New(207, "__ia32_sys_fchown"),
		X32:  nil,
	},
	"setresuid32": X86_64{
		X64:  nil,
		IA32: New(208, "__ia32_sys_setresuid"),
		X32:  nil,
	},
	"getresuid32": X86_64{
		X64:  nil,
		IA32: New(209, "__ia32_sys_getresuid"),
		X32:  nil,
	},
	"setresgid32": X86_64{
		X64:  nil,
		IA32: New(210, "__ia32_sys_setresgid"),
		X32:  nil,
	},
	"getresgid32": X86_64{
		X64:  nil,
		IA32: New(211, "__ia32_sys_getresgid"),
		X32:  nil,
	},
	"chown32": X86_64{
		X64:  nil,
		IA32: New(212, "__ia32_sys_chown"),
		X32:  nil,
	},
	"setuid32": X86_64{
		X64:  nil,
		IA32: New(213, "__ia32_sys_setuid"),
		X32:  nil,
	},
	"setgid32": X86_64{
		X64:  nil,
		IA32: New(214, "__ia32_sys_setgid"),
		X32:  nil,
	},
	"setfsuid32": X86_64{
		X64:  nil,
		IA32: New(215, "__ia32_sys_setfsuid"),
		X32:  nil,
	},
	"setfsgid32": X86_64{
		X64:  nil,
		IA32: New(216, "__ia32_sys_setfsgid"),
		X32:  nil,
	},
	"fcntl64": X86_64{
		X64:  nil,
		IA32: New(221, "__ia32_compat_sys_fcntl64"),
		X32:  nil,
	},
	"sendfile64": X86_64{
		X64:  nil,
		IA32: New(239, "__ia32_sys_sendfile64"),
		X32:  nil,
	},
	"set_thread_area": X86_64{
		X64:  nil,
		IA32: New(243, "__ia32_sys_set_thread_area"),
		X32:  nil,
	},
	"get_thread_area": X86_64{
		X64:  nil,
		IA32: New(244, "__ia32_sys_get_thread_area"),
		X32:  nil,
	},
	"statfs64": X86_64{
		X64:  nil,
		IA32: New(268, "__ia32_compat_sys_statfs64"),
		X32:  nil,
	},
	"fstatfs64": X86_64{
		X64:  nil,
		IA32: New(269, "__ia32_compat_sys_fstatfs64"),
		X32:  nil,
	},
	"fadvise64_64": X86_64{
		X64:  nil,
		IA32: New(272, "__ia32_compat_sys_x86_fadvise64_64", "__ia32_compat_sys_ia32_fadvise64_64"),
		X32:  nil,
	},
	"fstatat64": X86_64{
		X64:  nil,
		IA32: New(300, "__ia32_compat_sys_x86_fstatat", "__ia32_compat_sys_ia32_fstatat64"),
		X32:  nil,
	},
	"clock_gettime64": X86_64{
		X64:  nil,
		IA32: New(403, "__ia32_sys_clock_gettime"),
		X32:  nil,
	},
	"clock_settime64": X86_64{
		X64:  nil,
		IA32: New(404, "__ia32_sys_clock_settime"),
		X32:  nil,
	},
	"clock_adjtime64": X86_64{
		X64:  nil,
		IA32: New(405, "__ia32_sys_clock_adjtime"),
		X32:  nil,
	},
	"clock_getres_time64": X86_64{
		X64:  nil,
		IA32: New(406, "__ia32_sys_clock_getres"),
		X32:  nil,
	},
	"clock_nanosleep_time64": X86_64{
		X64:  nil,
		IA32: New(407, "__ia32_sys_clock_nanosleep"),
		X32:  nil,
	},
	"timer_gettime64": X86_64{
		X64:  nil,
		IA32: New(408, "__ia32_sys_timer_gettime"),
		X32:  nil,
	},
	"timer_settime64": X86_64{
		X64:  nil,
		IA32: New(409, "__ia32_sys_timer_settime"),
		X32:  nil,
	},
	"timerfd_gettime64": X86_64{
		X64:  nil,
		IA32: New(410, "__ia32_sys_timerfd_gettime"),
		X32:  nil,
	},
	"timerfd_settime64": X86_64{
		X64:  nil,
		IA32: New(411, "__ia32_sys_timerfd_settime"),
		X32:  nil,
	},
	"utimensat_time64": X86_64{
		X64:  nil,
		IA32: New(412, "__ia32_sys_utimensat"),
		X32:  nil,
	},
	"pselect6_time64": X86_64{
		X64:  nil,
		IA32: New(413, "__ia32_compat_sys_pselect6_time64"),
		X32:  nil,
	},
	"ppoll_time64": X86_64{
		X64:  nil,
		IA32: New(414, "__ia32_compat_sys_ppoll_time64"),
		X32:  nil,
	},
	"io_pgetevents_time64": X86_64{
		X64:  nil,
		IA32: New(416, "__ia32_sys_io_pgetevents"),
		X32:  nil,
	},
	"recvmmsg_time64": X86_64{
		X64:  nil,
		IA32: New(417, "__ia32_compat_sys_recvmmsg_time64"),
		X32:  nil,
	},
	"mq_timedsend_time64": X86_64{
		X64:  nil,
		IA32: New(418, "__ia32_sys_mq_timedsend"),
		X32:  nil,
	},
	"mq_timedreceive_time64": X86_64{
		X64:  nil,
		IA32: New(419, "__ia32_sys_mq_timedreceive"),
		X32:  nil,
	},
	"semtimedop_time64": X86_64{
		X64:  nil,
		IA32: New(420, "__ia32_sys_semtimedop"),
		X32:  nil,
	},
	"rt_sigtimedwait_time64": X86_64{
		X64:  nil,
		IA32: New(421, "__ia32_compat_sys_rt_sigtimedwait_time64"),
		X32:  nil,
	},
	"futex_time64": X86_64{
		X64:  nil,
		IA32: New(422, "__ia32_sys_futex"),
		X32:  nil,
	},
	"sched_rr_get_interval_time64": X86_64{
		X64:  nil,
		IA32: New(423, "__ia32_sys_sched_rr_get_interval"),
		X32:  nil,
	},
}
