// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

package appmodelmetrics

import (
	"io"

	"github.com/cilium/tetragon/pkg/metrics/consts"
	"github.com/prometheus/client_golang/prometheus"
)

// Phase identifies a stage in the application model export pipeline.
type Phase string

const (
	PhaseGetProcessModel Phase = "get_process_model"
	PhaseConversion      Phase = "conversion"
	PhaseDiff            Phase = "diff"
	PhaseExportTick      Phase = "export_tick"
	PhaseExport          Phase = "export"
	PhaseExportAppModel  Phase = "export_app_model"
)

var phases = []Phase{
	PhaseGetProcessModel,
	PhaseConversion,
	PhaseDiff,
	PhaseExportTick,
	PhaseExport,
	PhaseExportAppModel,
}

// LookupErrorType identifies a silent lookup failure in GetProcessModel.
type LookupErrorType string

const (
	LookupDNS       LookupErrorType = "dns"
	LookupCgroup    LookupErrorType = "cgroup"
	LookupNSID      LookupErrorType = "nsid"
	LookupUUID      LookupErrorType = "uuid"
	LookupSyscall   LookupErrorType = "syscall"
	LookupContainer LookupErrorType = "container"
)

var lookupErrorTypes = []LookupErrorType{
	LookupDNS,
	LookupCgroup,
	LookupNSID,
	LookupUUID,
	LookupSyscall,
	LookupContainer,
}

// TelemetryType identifies a category of telemetry entry.
type TelemetryType string

const (
	TelemetryProcess TelemetryType = "process"
	TelemetryNetwork TelemetryType = "network"
)

var telemetryTypes = []TelemetryType{
	TelemetryProcess,
	TelemetryNetwork,
}

// EntityKind identifies an application model entity type.
type EntityKind string

const (
	EntityNamespace   EntityKind = "namespace"
	EntityWorkload    EntityKind = "workload"
	EntityContainer   EntityKind = "container"
	EntityProcess     EntityKind = "process"
	EntityConnection  EntityKind = "connection"
	EntityDestination EntityKind = "destination"
)

var entityKinds = []EntityKind{
	EntityNamespace,
	EntityWorkload,
	EntityContainer,
	EntityProcess,
	EntityConnection,
	EntityDestination,
}

var (
	ExportTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Namespace: consts.MetricsNamespace,
		Name:      "appmodel_export_total",
		Help:      "Total number of application model export cycles completed.",
	})

	ExportNoChangesTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Namespace: consts.MetricsNamespace,
		Name:      "appmodel_export_no_changes_total",
		Help:      "Total number of application model export cycles where the diff was empty.",
	})

	DurationUsecTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: consts.MetricsNamespace,
		Name:      "appmodel_duration_usec_total",
		Help:      "Cumulative microseconds spent in each application model export phase. Phases are hierarchical: export_tick includes get_process_model, conversion, and export; export includes diff and sub-phase work.",
	}, []string{"phase"})

	ErrorsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: consts.MetricsNamespace,
		Name:      "appmodel_errors_total",
		Help:      "Total number of errors by application model export phase.",
	}, []string{"phase"})

	LookupErrorsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: consts.MetricsNamespace,
		Name:      "appmodel_lookup_errors_total",
		Help:      "Total number of silent lookup failures in GetProcessModel by type.",
	}, []string{"type"})

	TelemetryEntriesTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: consts.MetricsNamespace,
		Name:      "appmodel_telemetry_entries_total",
		Help:      "Total number of telemetry entries generated by type.",
	}, []string{"type"})

	ExportedBytesTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Namespace: consts.MetricsNamespace,
		Name:      "appmodel_exported_bytes_total",
		Help:      "Total number of bytes written to the telemetry JSON output.",
	})

	Entities = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: consts.MetricsNamespace,
		Name:      "appmodel_entities",
		Help:      "Current number of application model entities by kind.",
	}, []string{"kind"})
)

// InitMetrics registers all application model metrics and pre-initializes
// all known label combinations so time series appear immediately.
func InitMetrics(registry *prometheus.Registry) {
	registry.MustRegister(ExportTotal)
	registry.MustRegister(ExportNoChangesTotal)
	registry.MustRegister(DurationUsecTotal)
	registry.MustRegister(ErrorsTotal)
	registry.MustRegister(LookupErrorsTotal)
	registry.MustRegister(TelemetryEntriesTotal)
	registry.MustRegister(ExportedBytesTotal)
	registry.MustRegister(Entities)

	// Pre-initialize all label combinations
	for _, p := range phases {
		DurationUsecTotal.WithLabelValues(string(p)).Add(0)
		ErrorsTotal.WithLabelValues(string(p)).Add(0)
	}
	for _, t := range lookupErrorTypes {
		LookupErrorsTotal.WithLabelValues(string(t)).Add(0)
	}
	for _, t := range telemetryTypes {
		TelemetryEntriesTotal.WithLabelValues(string(t)).Add(0)
	}
	for _, k := range entityKinds {
		Entities.WithLabelValues(string(k)).Set(0)
	}
}

// InitMetricsForDocs registers metrics and adds example entries for documentation.
func InitMetricsForDocs(registry *prometheus.Registry) {
	InitMetrics(registry)

	RecordExport()
	RecordNoChanges()
	RecordDuration(PhaseGetProcessModel, 1500)
	RecordError(PhaseExport)
	RecordLookupError(LookupDNS)
	RecordTelemetryEntries(TelemetryProcess, 5)
	SetEntities(EntityProcess, 42)
	ExportedBytesTotal.Add(1024)
}

// RecordExport increments the export cycle counter.
func RecordExport() {
	ExportTotal.Inc()
}

// RecordNoChanges increments the no-changes counter.
func RecordNoChanges() {
	ExportNoChangesTotal.Inc()
}

// RecordDuration adds the given microseconds to the duration counter for the phase.
func RecordDuration(phase Phase, usec float64) {
	DurationUsecTotal.WithLabelValues(string(phase)).Add(usec)
}

// RecordError increments the error counter for the phase.
func RecordError(phase Phase) {
	ErrorsTotal.WithLabelValues(string(phase)).Inc()
}

// RecordLookupError increments the lookup error counter for the type.
func RecordLookupError(typ LookupErrorType) {
	LookupErrorsTotal.WithLabelValues(string(typ)).Inc()
}

// RecordTelemetryEntries adds the given count to the telemetry entries counter.
func RecordTelemetryEntries(typ TelemetryType, count int) {
	TelemetryEntriesTotal.WithLabelValues(string(typ)).Add(float64(count))
}

// SetEntities sets the entity gauge for the kind.
func SetEntities(kind EntityKind, count int) {
	Entities.WithLabelValues(string(kind)).Set(float64(count))
}

// byteCounterWriter wraps an io.WriteCloser and tracks the number of bytes written.
type byteCounterWriter struct {
	io.WriteCloser
	bytesWritten prometheus.Counter
}

func (w *byteCounterWriter) Write(p []byte) (int, error) {
	n, err := w.WriteCloser.Write(p)
	w.bytesWritten.Add(float64(n))
	return n, err
}

// NewExportedBytesCounterWriter wraps a writer to increment ExportedBytesTotal on writes.
func NewExportedBytesCounterWriter(w io.WriteCloser) io.WriteCloser {
	return &byteCounterWriter{
		WriteCloser:  w,
		bytesWritten: ExportedBytesTotal,
	}
}
