// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Tetragon

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SandboxPolicyNamespacedLister helps list SandboxPoliciesNamespaced.
// All objects returned here must be treated as read-only.
type SandboxPolicyNamespacedLister interface {
	// List lists all SandboxPoliciesNamespaced in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.SandboxPolicyNamespaced, err error)
	// SandboxPoliciesNamespaced returns an object that can list and get SandboxPoliciesNamespaced.
	SandboxPoliciesNamespaced(namespace string) SandboxPolicyNamespacedNamespaceLister
	SandboxPolicyNamespacedListerExpansion
}

// sandboxPolicyNamespacedLister implements the SandboxPolicyNamespacedLister interface.
type sandboxPolicyNamespacedLister struct {
	indexer cache.Indexer
}

// NewSandboxPolicyNamespacedLister returns a new SandboxPolicyNamespacedLister.
func NewSandboxPolicyNamespacedLister(indexer cache.Indexer) SandboxPolicyNamespacedLister {
	return &sandboxPolicyNamespacedLister{indexer: indexer}
}

// List lists all SandboxPoliciesNamespaced in the indexer.
func (s *sandboxPolicyNamespacedLister) List(selector labels.Selector) (ret []*v1alpha1.SandboxPolicyNamespaced, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SandboxPolicyNamespaced))
	})
	return ret, err
}

// SandboxPoliciesNamespaced returns an object that can list and get SandboxPoliciesNamespaced.
func (s *sandboxPolicyNamespacedLister) SandboxPoliciesNamespaced(namespace string) SandboxPolicyNamespacedNamespaceLister {
	return sandboxPolicyNamespacedNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// SandboxPolicyNamespacedNamespaceLister helps list and get SandboxPoliciesNamespaced.
// All objects returned here must be treated as read-only.
type SandboxPolicyNamespacedNamespaceLister interface {
	// List lists all SandboxPoliciesNamespaced in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.SandboxPolicyNamespaced, err error)
	// Get retrieves the SandboxPolicyNamespaced from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.SandboxPolicyNamespaced, error)
	SandboxPolicyNamespacedNamespaceListerExpansion
}

// sandboxPolicyNamespacedNamespaceLister implements the SandboxPolicyNamespacedNamespaceLister
// interface.
type sandboxPolicyNamespacedNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all SandboxPoliciesNamespaced in the indexer for a given namespace.
func (s sandboxPolicyNamespacedNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.SandboxPolicyNamespaced, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SandboxPolicyNamespaced))
	})
	return ret, err
}

// Get retrieves the SandboxPolicyNamespaced from the indexer for a given namespace and name.
func (s sandboxPolicyNamespacedNamespaceLister) Get(name string) (*v1alpha1.SandboxPolicyNamespaced, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("sandboxpolicynamespaced"), name)
	}
	return obj.(*v1alpha1.SandboxPolicyNamespaced), nil
}
