//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.
//

package common

import (
	"fmt"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// NewGeneratedFile creates a new codegen pakage and file in the project
func NewGeneratedFile(gen *protogen.Plugin, file *protogen.File, pkg string) *protogen.GeneratedFile {
	importPath := filepath.Join(string(file.GoImportPath), "codegen", pkg)
	fileName := filepath.Join(strings.TrimSuffix(file.GeneratedFilenamePrefix, "fgs"), "codegen", pkg, fmt.Sprintf("%s.pb.go", pkg))

	g := gen.NewGeneratedFile(fileName, protogen.GoImportPath(importPath))
	g.P(`//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.
//
`)
	g.P("// Code generated by protoc-gen-go-fgs. DO NOT EDIT")
	g.P()
	g.P("package ", pkg)
	g.P()

	return g
}

// GoIdent is a convenience helper that returns a qualified go ident as a string for
// a given import package and name
func GoIdent(g *protogen.GeneratedFile, importPath string, name string) string {
	return g.QualifiedGoIdent(protogen.GoIdent{
		GoName:       name,
		GoImportPath: protogen.GoImportPath(importPath),
	})
}

// FgsApiIdent is a convenience helper that calls GoIdent with the path to the FGS API
// package.
func FgsApiIdent(g *protogen.GeneratedFile, name string) string {
	return GoIdent(g, "github.com/isovalent/hubble-fgs/api/v1/fgs", name)
}

// Logger is a convenience helper that generates a call to logger.GetLogger()
func Logger(g *protogen.GeneratedFile) string {
	return fmt.Sprintf("%s()", GoIdent(g, "github.com/isovalent/hubble-fgs/pkg/logger", "GetLogger"))
}
