// Copyright 2019 Authors of Hubble
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

import (
	"encoding/binary"
)

const (
	DOCKER_ID_LENGTH = 16

	MSG_OP_UNDEF = 0
	// The following events generate MsgIPv4TcpConnectUnix type events.

	// MSG_OP_IPV4_TCPCONNECT event indicates a TCP connect() syscall
	// has been started. The event is generated on entry into a connect() call
	// and includes the info listed in `MsgIPv4TcpConnect`. It does _not_
	// imply the connect call will be succesful and the 'Return' field
	// is undefined at this point. The event is disabled by default users
	// should use TCPCONNECTRET events which populate the 'Return' field.
	// The other fields `Kube`, `Common`, and `PID' will be populated using
	// data stored from exec() call of the associated pid.
	MSG_OP_IPV4_TCPCONNECT = 1
	// MSG_OP_IPV5_TCPCONNECTRET event indicates a connect() syscall has
	// returned. The event populates the `MsgIPv4TcpConnect` and `Return`
	// codes. If the call is an asynchronous call the `Return` code will
	// indicate this. The other fields `Kube`, `Common`, and `PID' will
	// be populated using data stored from exec() call of the associated pid.
	MSG_OP_IPV4_TCPCONNECTRET = 2
	// MSG_OP_IPV4_BIND event indicates a bind() syscall has been issued.
	// This hook is placed behind the syscall in order to account for
	// kernel side generating ports and IP addresses when user does not
	// provide them. This event is not generated by default. By default
	// the bind() information is stored and only returned when the process
	// issues a subsequent listen() call. The other fields `Kube`, `Common`,
	// and `PID' will be populated using data stored from exec() call of
	// the associated pid.
	MSG_OP_IPV4_BIND = 3
	// MSG_OP_IPV4_LISTEN event indicates a listen() syscall has been issued.
	// This hook will generate an event including the information stored
	// from previous exec call and bind call.
	MSG_OP_IPV4_LISTEN = 4
	// MSG_OP_EXECVE event indicates a process was created. The 'PID'
	// and 'Common' fields will be populated. This event is positioned
	// after exec() calls have been validated so failed syscalls will
	// not be reported. To generate events provide the '-e' option to
	// hubble-fgs, without the option the hook only populates the data
	// store for later use by above events.
	MSG_OP_EXECVE = 5

	MSG_OP_TLS = 6

	MSG_OP_EXIT = 7

	MSG_OP_IPV4_TCPCLOSE = 8

	MSG_OP_IPV4_ACCEPT = 9

	MSG_OP_CRED = 10

	// just for testing
	MSG_OP_TEST = 254
)

const (
	ARGSBUFFER     = 1024 + 16
	SIZEOF_EXECVE  = 32
	MAX_SIZEOF_CWD = 256

	SNI_BUFFER_SIZE = 32
)

// Msg Flag Definitions
const (
	EventUnknown = 0x00
	// EventExecve indicates the event is generated by an execve*. See
	// EventProcFS for the other option. A correctly formatted event should
	// either set EventExecve or EventProcFS.
	EventExecve = 0x01
	// Deprecated: EventExecveAt indicates the event is generated by an
	// execveAt syscall
	EventExecveAt = 0x02
	// EventProcFS indicates the event is generated from a proc interface.
	// This happens at FGS init when existing processes are being loaded
	// into FGS event buffer. All events should have either EventExecve or
	// EventProcFS set.
	EventProcFS = 0x04
	// EventTruncFilename indicates we truncated the processes filename
	// because the buffer size is too small. Consider increasing buffer
	// size to avoid this.
	EventTruncFilename = 0x08
	// EventTruncArgs indicates we truncated the processes arguments because
	// the buffer size was too small to fit all exec args. Consider increasing
	// buffer size to avoid this.
	EventTruncArgs = 0x10
	// EventTaskWalk indicates we walked the process hierarchy to find a
	// parent process in the FGS buffer. This may happen when we did not
	// receive an exec event for the immediate parent of a process.
	// Typically means we are looking at a fork that in turn did another
	// fork we don't currently track fork events exactly and instead push
	// an event with the original parent exec data. This flag can provide
	// this insight into the event if needed. Primarily useful for debugging.
	EventTaskWalk = 0x20
	// EventMiss is an *error flag* indicating we could not find parent info
	// in the FGS event buffer. If this is set it should be reported to FGS
	// developers for debugging. FGS will do its best to recover information
	// about the process from available kernel data structures instead of
	// using cached info in this case. However, args will not be available.
	EventMiss = 0x40
	// EventNeedsAUID is an *internal flag* for FGS to indicate the audit
	// has not yet been resolved. The BPF hooks look at this flag to
	// determine if probing the audit system is necessary.
	EventNeedsAUID = 0x80
	// EventErrorFilename is an *error flag* indicating an error happened
	// while reading the filename. If this is set it should be reported to
	// FGS developers for debugging.
	EventErrorFilename = 0x100
	// EventErrorArgs is an *error flag* indicating an error happened while
	// reading the process args. If this is set it should be reported to
	// FGS developers for debugging.
	EventErrorArgs = 0x200
	// EventNeedsCWD is an *internal flag* for FGS to indicate the current
	// working directory has not yet been resolved. The FGS hooks look at
	// this flag to determine if probing the CWD is necessary.
	EventNeedsCWD = 0x400
	// EventNoCWDSupport indicates we removed the CWD from the event because
	// the buffer size is too small. Consider increasing buffer size to avoid
	// this.
	EventNoCWDSupport = 0x800
	// EventRootCWD indicates the CWD is the root directory. This is necessary
	// to inform readers the CWD is not in the event buffer and is '/' instead.
	EventRootCWD = 0x1000
	// EventErrorCWD is an *error flag* indicating an error happened while
	// reading the CWD of a process. If this is set it should be reported to
	// FGS developers for debugging.
	EventErrorCWD = 0x2000
	// EventClone indicates the process issues a clone before exec* was
	// issued. This is the general flow to exec* a new process. However,
	// its possible to replace the current process with a new process
	// by doing an exec* without a clone. In this case the flag will
	// be omitted. Also the same PID will be used by the kernel for both
	// the old process and the newly exec'd process.
	EventClone = 0x4000
)

// TLS supported version 8bit codes
const (
	TLSVersion13 = 0x0403
	TLSVersion12 = 0x0303
	TLSVersion11 = 0x0203
	TLSVersion10 = 0x0103
)

// TLS flags
const (
	TlsFlagCopyError           = 0x0001
	TlsFlagMaxTlvs             = 0x0002
	TlsFlagFrameTooLarge       = 0x0004
	TlsFlagHelloMsgMiss        = 0x0008
	TlsFlagCipherError         = 0x0010
	TlsFlagCipherTooLarge      = 0x0020
	TlsFlagCompressionError    = 0x0040
	TlsFlagCompressionTooLarge = 0x0080
	TlsFlagExtError            = 0x0100
	TlsFlagExtTooLarge         = 0x0200
	TlsFlagVersion             = 0x0400
)

// API between Kernel BPF and Userspace hubble-fgs Golang agent
type MsgCommon struct {
	Op    uint8
	Pad   [3]uint8
	Size  uint32
	Ktime uint64
}

type OpCode int

const (
	MsgOpUndef = iota
	MsgOpIPv4TCPConnect
	MsgOpIPv4TCPConnectReturn
	MsgOpIPv4Bind
	MsgOpIPv4Listen
	MsgOpExecve
)

func (op OpCode) String() string {
	return [...]string{
		"Undef",
		"TCPConnect",
		"TCPConnectReturn",
		"TCPBind",
		"TCPListen",
		"Execve",
		"TLS"}[op]
}

type MsgExec struct {
	Size  uint32
	PID   uint32
	NSPID uint32
	UID   uint32
	AUID  uint32
	Flags uint32
	Ktime uint64
}

type MsgIPv4Tuple struct {
	SAddr uint32
	DAddr uint32
	DPort uint16
	SPort uint16
	Proto uint8
	// define as uint8 otherwise padding in struct breaks
	PostData [6]uint8
	Pad      [5]uint8
}

func (m *MsgIPv4Tuple) GetPostDAddr() uint32 {
	return binary.LittleEndian.Uint32(m.PostData[0:4])
}

func (m *MsgIPv4Tuple) GetPostDPort() uint16 {
	return binary.LittleEndian.Uint16(m.PostData[4:6])
}

type MsgK8s struct {
	NetNS  uint32
	Cid    uint32
	Cgrpid uint64
	Docker [DOCKER_ID_LENGTH]byte
}

type MsgIPv4Tcp struct {
	Common     MsgCommon
	Tuple      MsgIPv4Tuple
	Return     int64
	ProcessKey MsgExecveKey
}

// API between Userspace hubble-fgs Golang agent and Unix domain socket listener
type MsgExecUnix struct {
	Size     uint32
	PID      uint32
	NSPID    uint32
	UID      uint32
	AUID     uint32
	pad      uint32
	Flags    uint32
	Ktime    uint64
	Filename string
	Args     string
}

type MsgK8sUnix struct {
	NetNS  uint32
	Cid    uint32
	Cgrpid uint64
	Docker string
}

type MsgIPv4TcpEventUnix struct {
	Common     MsgCommon
	Tuple      MsgIPv4Tuple
	Kube       MsgK8sUnix
	Return     int64
	ProcessKey MsgExecveKey
}

var MsgUnixSize uint32 = 640

type MsgCapabilities struct {
	Permitted   uint64
	Effective   uint64
	Inheritable uint64
}

type MsgExecveEvent struct {
	Common       MsgCommon
	Kube         MsgK8s
	Parent       MsgExecveKey
	ParentFlags  uint64
	Capabilities MsgCapabilities
}

type MsgExecveEventUnix struct {
	Common       MsgCommon
	Kube         MsgK8sUnix
	Parent       MsgExecveKey
	ParentFlags  uint64
	Capabilities MsgCapabilities
	Process      MsgExecUnix
}

type MsgTLSIPv4 struct {
	SAddr uint32
	DAddr uint32
	DPort uint16
	SPort uint16
	Uid   uint64
	Proto uint8
	Pad   [3]uint8
}

type MsgTLS struct {
	Version           uint16
	Length            uint16
	Type              uint8
	Subtype           uint8
	LegacyyVersion    uint16
	SNI               [32]uint8
	SupportedVersions [16]uint8
	Cipher            uint16
	AlertLevel        uint8
	AlertDescription  uint8
	Flags             uint32
	Session           [64]uint8
}

type MsgExecveKey struct {
	Pid   uint32
	Pad   uint32
	Ktime uint64
}

type MsgTLSAlert struct {
	Level       uint8
	Description uint8
	Count       uint16
}

type MsgTLSEvent struct {
	Common      MsgCommon
	Tuple       MsgTLSIPv4
	ClientHello MsgTLS
	ServerHello MsgTLS
	ProcessKey  MsgExecveKey
}

type MsgExitEvent struct {
	Common     MsgCommon
	ProcessKey MsgExecveKey
}

type MsgExitEventUnix = MsgExitEvent

type MsgCredEvent struct {
	Common       MsgCommon
	ProcessKey   MsgExecveKey
	Capabilities MsgCapabilities
}

type MsgCredEventUnix = MsgCredEvent

type MsgTestEvent struct {
	Common MsgCommon
}

type MsgTestEventUnix = MsgTestEvent

type SensorStatus struct {
	Name    string
	Enabled bool
}

func SwapByte(b uint16) uint16 {
	return (b << 8) | (b >> 8)
}
