{
 "title": "File Exec Monitoring Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(tetragon_file_exec_actions_total,namespace)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(tetragon_file_exec_actions_total{namespace=~\"$namespace\"},workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate of Exec Events",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(tetragon_file_exec_actions_total{namespace=~\"$namespace\", workload=~\"$workload\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top-10 File Digests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "topk(10, sum by(digest, file) (tetragon_file_exec_actions_total{namespace=~\"$namespace\", workload=~\"$workload\"}))",
     "legendFormat": "{{file}} <=> {{digest}}"
    }
   ]
  },
  {
   "title": "File Exec Events In/Out the EventCache",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(direction) (tetragon_file_exec_cache_events_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost File Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum(tetragon_missed_events_total{msg_op=~\"129\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "File Exec Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(error) (tetragon_file_exec_ebpf_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}