apiVersion: cilium.io/v1alpha1
kind: TetragonNetworkPolicy
metadata:
  name: "example-deny-segmentation"
  annotations:
    author: "IsovalentQATeam"
spec:
  podSelector:
    matchLabels:
      class: "xwing"
  processSelector:
    operator: "In"
    values:
      - "/usr/bin/curl"
      - "/usr/sbin/curl"
  defaultAction: "allow"
  rules:
  - hook: "connect"
    action: "deny"
    destination:
    - podSelector:
        matchLabels:
          org: "empire"
      ports:
        protocol: "TCP"
