apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-exec-monitoring"
spec:
  exec:
    enable: true
    selectors:
    - matchDigests:
      - operator: "In"
        values:
        - "sha1:f2e2c1b280ae3268c15fd31cd8d2fcec9a984c5f" # /bin/cat
      matchActions:
      - action: Block
