apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-monitoring"
spec:
  file:
    file_paths_patterns:
    - type: FileSystemType
      file_system_type:
        names: 
        - "securityfs"
        - "sysfs"
        - "proc"
    monitorHostFiles: true
