apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-monitoring"
spec:
  file:
    file_config:
      # Currently we have a check to load FIM only for kernels >= 4.19.
      # By using this flag we provide the ability to load (and test) FIM
      # on older kernels (i.e. openshift 4.18).
      forceLoad: "false"
      # This option allows users to enable file digests in exec events.
      # This is currently supported in newer kernels (>= 5.18).
      # If the user enables them but the kernel does not support them,
      # we fallback to not using them.
      enableExecDigests: "false"
      # This option choose the way that we calculate the inode map size.
      # Possible values are "fixed" and "auto" (default "fixed"). The final
      # inode map size will be calculated based on the following formula:
      #
      # if watchedInodeMapSizePolicy == "fixed":
      #   watchedInodeMapSize = watchedInodeMapMaxiumSize
      # else if watchedInodeMapSizePolicy == "auto":
      #   watchedInodeMapSize = (watchedInodeMapSizeMultiplier * number_of_inodes) + watchedInodeMapSizeConstant
      # else:
      #   return error
      #
      # The number_of_inodes defined as the number of inodes in the file system
      # that match the respective tracing policy at the time that the policy is installed.
      watchedInodeMapSizePolicy: "fixed"
      # This option allows users to define a specific size for the map
      # that holds the watched inodes. The default value (i.e. if
      # the user does not specify that option) is 256K entries.
      watchedInodeMapMaxiumSize: "262144"
      # This option allows users to define a multiplier for the map
      # that holds the watched inodes. The default value (i.e. if
      # the user does not specify that option) is 4.
      watchedInodeMapSizeMultiplier: "4"
      # This option allows users to define a constant for the map
      # that holds the watched inodes. The default value (i.e. if
      # the user does not specify that option) is 262144.
      watchedInodeMapSizeConstant: "262144"
    file_paths:
    - "/etc/"
    - "/var/testfile"
    file_paths_exclude:
    - "/etc/demo1"
    - "/etc/demo2"
    - "/etc/locale.alias"
    monitorHostFiles: true
    podSelector:
      matchExpressions:
      - key: "k8s:io.kubernetes.pod.namespace"
        operator: "In"
        values:
        - "default"
      - key: "k8s:io.kubernetes.pod.app"
        operator: "In"
        values:
        - "ubuntu"
      matchLabels:
        "k8s:io.kubernetes.pod.namespace": "default"
        "k8s:io.kubernetes.pod.app": "ubuntu"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/bin/cat"
      matchDigests:
      - operator: "In"
        values:
        - "sha1:cae542290d1bb5c91c637350e0a633f71fd2a6e4" # /bin/sleep
        - "sha1:439667f622b84ecb9f381be93cc9139f83a92f66" # /bin/bash
      matchLinuxNamespaces:
      - namespace: Pid
        filter: Host
      - namespace: Mnt
        filter: NoHost
      matchLinuxCapabilities:
      - type: Effective
        operator: In
        values:
        - "CAP_CHOWN"
        - "CAP_NET_RAW"
        - "CAP_SYS_ADMIN"
      matchRenameSrcType:
      - operator: "In"
        values:
        - "File"
        - "Directory"
      matchOperations:
      - operator: "In"
        values:
        - "FILE_DELETE"
        - "FILE_WRITE"
      matchActions:
      - action: Block # Possible values: Block or Post (default).
