apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-exec-monitoring"
spec:
  exec:
    enable: true
    defaultActions:
    - action: Post
    selectors:
    - matchDigests:
      - operator: "In"
        values:
        - "sha1:f2e2c1b280ae3268c15fd31cd8d2fcec9a984c5f" # /bin/cat
      matchLinuxCapabilities:
      - type: Effective
        operator: In
        values:
        - "CAP_CHOWN"
        - "CAP_NET_RAW"
        - "CAP_SYS_ADMIN"
      matchActions:
      - action: Block
