apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "http"
spec:
  parser:
    http:
      enable: true
      selectors:
      - matchPorts:
        - 8025
        - 8026
        - 8027
        - 8028
        - 8029
        - 8030
        - 8031
        - 8032
        - 8033
        - 8079
        - 8080
        - 8081
        - 8082
        - 8083
        - 8084
        - 8085
        - 8086
        - 8087
        - 8088
        - 8089
        - 8090
        - 8091
        - 8092
        - 8093
        - 8094
        - 8095
        - 8096
        - 8097
        - 8098
        - 8099
        - 8100
        - 8110
        - 8111
        - 8112
        - 8142
        - 8143
        - 8144
        - 8145
        - 8146
        - 8147
        - 8148
        - 8149
        - 8150
        - 8151
        - 8152
        - 8153
        - 8154
        - 8181
        - 8184
        - 8185
        - 8188
        - 8443
        - 8444
        - 8445
        - 8446
        - 8447
        - 8448
        - 8449
        - 80800
    tcp:
      enable: true
      histogram:
        enable: false
