apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "udp"
spec:
  parser:
    udp:
      enable: true
      cgroup: true
      statsInterval: 10
      deleteIdleSocketInterval: 60
      burst:
        enable: true
        windowSize: 1000
        triggerPercent: 50
    tcp:
      enable: true
      statsInterval: 10
      burst:
        enable: true
        windowSize: 1000
        triggerPercent: 50
      histogram:
        enable: true
        min: 0
        max: 4000
    burstExitGen:
      enable: true
      interval: 1000
    dns:
      enable: true
