apiVersion: isovalent.com/v1alpha1
kind: TracingPolicy
metadata:
  name: "udp"
spec:
  parser:
    udp:
      enable: true
      cgroup: true
      statsinterval: 20
      mintimesocketinterval: 20
      deleteidlesocketinterval: 60
