apiVersion: isovalent.com/v1alpha1
kind: TracingPolicy
metadata:
  name: "udp"
spec:
  parser:
    udp:
      enable: true
      cgroup: true
      statsInterval: 20
      deleteIdleSocketInterval: 60
    udpBurst:
      enable: true
      windowSize: 1000
      triggerPercent: 50
    dns:
      enable: true
