apiVersion: isovalent.com/v1alpha1
kind: TracingPolicy
metadata:
  name: "sys-write"
spec:
  kprobes:
  - call: "__x64_sys_write"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "char_buf"
      sizeargindex: 3
    - index: 2
      type: "size_t"
    allowfilters:
      pids:
      - op: "neq"
        value: 1
        followforks: true
        isnamespacepid: true
      - op: "neq"
        value: 0
        followforks: false
        isnamespacepid: true
      args:
      - index: 0
        op: "eq"
        value: "1"
