apiVersion: isovalent.com/v1alpha1
kind: TracingPolicy
metadata:
  name: "sys-write"
spec:
  kprobes:
  - call: "__x64_sys_write"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "char_buf"
      sizeArgIndex: 3
    - index: 2
      type: "size_t"
    # (pid in {1, 2} && arg0 == "1" && arg2 != "hello") || (pid in {3, 4} && arg0 == "2" && arg1 == "world")
    selectors:
    - matchPIDs:
      - operator: In
        values:
        - 1
        - 2
      matchArgs:
      - index: 0
        operator: Equal
        values:
        - "1"
      - index: 1
        operator: NotEqual
        values:
        - "hello"
    - matchPIDs:
      - operator: In
        values:
        - 3
        - 4
      matchArgs:
      - index: 0
        operator: Equal
        values:
        - "2"
      - index: 1
        operator: NotEqual
        values:
        - "world"
