---
# Source: hubble-fgs/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-fgs
  namespace: kube-system
---
# Source: hubble-fgs/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fgs-config
  namespace: kube-system
data:
  config.yaml: |
    debug: false
    enable-cilium-api: true
    cilium-bpf: /sys/fs/bpf/tc/globals/
    enable-k8s-api: true
    export-file-compress: true
    export-file-max-backups: 5
    export-file-max-size-mb: 10
    export-filename: /var/run/cilium/hubble-fgs.log
    metrics-server: :2112
    process-cache-size: 32768
    procfs: /procRoot
    tlstc: true
---
# Source: hubble-fgs/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hubble-fgs
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
# Source: hubble-fgs/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hubble-fgs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hubble-fgs
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: hubble-fgs
---
# Source: hubble-fgs/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hubble-fgs
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: hubble-fgs
  template:
    metadata:
      labels:
        k8s-app: hubble-fgs
    spec:
      serviceAccountName: hubble-fgs
      containers:
        - name: hubble-fgs
          command:
            - /usr/bin/hubble-fgs
          args:
          image: quay.io/isovalent/hubble-fgs:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/hubble-fgs
              name: fgs-config
              readOnly: true
            - mountPath: /sys/fs/bpf
              mountPropagation: HostToContainer
              name: bpf-maps
            - mountPath: "/var/run/cilium"
              name: run
            - mountPath: "/procRoot"
              name: fgs-proc
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: FGS_SOCKET_PATH
            value: "/var/run/cilium/hubble-fgs.sock"
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      tolerations:
        - operator: Exists
      volumes:
        - configMap:
            name: fgs-config
            items:
            - key: config.yaml
              path: config.yaml
          name: fgs-config
        - hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
          name: bpf-maps
        - hostPath:
            path: /var/run/cilium
            type: DirectoryOrCreate
          name: run
        - hostPath:
            path: /proc/
            type: Directory
          name: fgs-proc
