---
# Source: hubble-fgs/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hubble-fgs
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: hubble-fgs
  template:
    metadata:
      labels:
        k8s-app: hubble-fgs
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - cilium
            namespaces:
            - cilium
            - kube-system
            topologyKey: kubernetes.io/hostname
      containers:
        - name: hubble-fgs
          command:
            - /usr/bin/hubble-fgs
          args:
            - --procfs=/procRoot
            - --set-pid-max
            - -e
            - -t
          image: quay.io/isovalent/hubble-fgs:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/var/run/cilium"
              name: run
            - mountPath: "/procRoot"
              name: fgs-proc
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: FGS_SOCKET_PATH
            value: "/var/run/cilium/hubble-fgs.sock"
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /var/run/cilium
            type: DirectoryOrCreate
          name: run
        - hostPath:
            path: /proc/
            type: Directory
          name: fgs-proc
