enabled: true
imagePullPolicy: IfNotPresent
priorityClassName: ""
imagePullSecrets: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
nodeSelector: {}
tolerations:
- operator: Exists
affinity: {}
extraHostPathMounts: []
extraConfigmapMounts: []
daemonSetAnnotations: {}
extraVolumes: []
updateStrategy: {}
podLabels: {}
daemonSetLabelsOverride: {}
selectorLabelsOverride: {}
podLabelsOverride: {}
serviceLabelsOverride: {}

# Set DNS policy for tetragon pods.
#
# Recommended DNS policy for tetragon pod depends on whether the export container
# needs to resolve external DNS names (e.g. an S3 URL) or internal ones (e.g. a Kubernetes
# DNS name for elasticsearch service).
#
# - For external DNS names, use "Default" so that the export container continues to function
#   properly in case there is a connectivity issue between the export container and core-dns.
# - For internal DNS names, use "ClusterFirstWithHostNet" so that the export container can
#   resolve them.
#
# https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
dnsPolicy: Default

# exportDirectory specifies directory to put Tetragon JSON export files.
exportDirectory: "/var/run/cilium/hubble"
# exportFileRotationInterval specifies file creation interval for hubble-export-s3.
exportFileCreationInterval: "120s"

#
# Configures whether Tetragon pods run on the host network.
#
# IMPORTANT: Tetragon must be on the host network for the process visibility to
# function properly. However, S3 export does not work on the host network when used with
# kiam to assign a role due to a limitation in how kiam configures iptables rules to
# intercept requests to AWS metadata server.
#
# Set this flag to false if and only if you don't use the process visibility functionality
# and you use kiam to assign a role to upload events to S3.
#
# Reference: https://github.com/uswitch/kiam/issues/119
#
hostNetwork: true

tetragon:
  enabled: true
  image:
    override: ~
    repository: quay.io/isovalent/tetragon
    tag: v1.11.1
  metadata:
    enabled: false
    image:
      override: ~
      repository: quay.io/isovalent/hubble-enterprise-metadata
      tag: current
      # Override the global image pull policy.
      imagePullPolicy: Always
  resources: {}
  extraArgs: {}
  extraEnv: []
  # extraEnv:
  #   - name: foo
  #     value: bar
  extraVolumeMounts: []
  securityContext:
    privileged: true

  # Tetragon puts processes in an LRU cache. The cache is used to find ancestors
  # for subsequently exec'ed processes.
  processCacheSize: 65536

  # JSON export filename. Set it to an empty string to disable JSON export altogether.
  exportFilename: fgs.log

  # JSON export file permissions as a string. Set it to "600" to restrict access to owner.
  exportFilePerm: "644"

  # Size in megabytes at which to rotate JSON export files.
  exportFileMaxSizeMB: 10

  # Number of rotated files to retain.
  exportFileMaxBackups: 5

  # Compress rotated JSON export files.
  exportFileCompress: false

  # Rate-limit event export (events per minute), Set to -1 to export all events.
  exportRateLimit: -1

  # -- EXPERIMENTAL: Enable Hubble flow export. When this value is not empty, Tetragon exports
  # ProcessConnect events as Hubble flow JSON in addition to exporting them as process_connect JSON.
  flowExportFilename: ""

  # Size in megabytes at which to rotate flow JSON export files.
  flowExportFileMaxSizeMB: 10

  # Number of rotated flow JSON export files to retain.
  flowExportFileMaxBackups: 5

  # Compress rotated flow JSON export files.
  flowExportFileCompress: false

  # Allowlist for JSON export. For example, to export only process_connect events from
  # the default namespace:
  #
  # exportAllowList: |
  #   {"namespace":["default"],"event_set":["PROCESS_CONNECT"]}
  exportAllowList: |-
    {"event_set":["PROCESS_CONNECT", "PROCESS_EXEC", "PROCESS_HTTP", "PROCESS_KPROBE", "PROCESS_LISTEN", "PROCESS_TLS"]}

  # Denylist for JSON export. For example, to exclude exec events that look similar to
  # Kubernetes health checks and all the events from kube-system namespace and the host:
  #
  # exportDenyList: |
  #   {"health_check":true}
  #   {"namespace":["kube-system",""]}
  #
  exportDenyList: |-
    {"health_check":true}
    {"namespace":["", "cilium", "kube-system"]}

  # Filters to include or exclude fields from Tetragon events. Without any filters, all
  # fields are included by default. The presence of at least one inclusion filter implies
  # default-exclude (i.e. any fields that don't match an inclusion filter will be
  # excluded). Field paths are expressed using dot notation like "a.b.c" and multiple
  # field paths can be separated by commas like "a.b.c,d,e.f". An optional "event_set" may
  # be specified to apply the field filter to a specific set of events.
  #
  # For example, to exclude the "parent" field from all events and include the "process"
  # field in PROCESS_KPROBE events while excluding all others:
  #
  # fieldFilters: |
  #   {"fields": "parent", "action": "EXCLUDE"}
  #   {"event_set": ["PROCESS_KPROBE"], "fields": "process", "action": "INCLUDE"}
  #
  fieldFilters: |-
    {}

  # Access Kubernetes API to associate Tetragon events with Kubernetes pods.
  enableK8sAPI: true

  # -- DEPRECATED: enableCiliumAPI is deprecated in v1.12 and will be removed in v1.13.
  # Use tetragonOperator.podInfo.enabled and Tetragon's DNS sensor instead to get
  # destination endpoint information for network events.
  #
  # Access Cilium API to associate Tetragon events with Cilium endpoints and DNS cache.
  enableCiliumAPI: false

  # enableProcessCred enables Capabilities visibility in exec and kprobe events.
  enableProcessCred: false

  # enableProcessNs enables Namespaces visibility in exec and kprobe events.
  enableProcessNs: false

  # fimRuntimeEndpoint provides a custom container runtime endpoint for FIM (can be used only for containerd or cri-o)
  fimRuntimeEndpoint: ""

  # Set --btf option to explicitly specify an absolute path to the metadata file. For advanced users only.
  btf: ""

  # Override the command. For advanced users only.
  commandOverride: []

  # Override the arguments. For advanced users only.
  argsOverride: []

  # -- EXPERIMENTAL: This field may be removed in the future without notice.
  #
  # Enable TCP segment sampling to collect metrics. Recommended sample rate: 4096. Set it to zero to disable.
  #
  # Note that the counter for sampling is global, and it is not per socket.
  tcpStatsSampleSegs: 0

  prometheus:
    # -- Whether to enable exposing Tetragon metrics.
    enabled: true
    # -- The address at which to expose metrics. Set it to "" to expose on all available interfaces.
    address: ""
    # -- The port at which to expose metrics.
    port: 2112
    serviceMonitor:
      # -- Whether to create a 'ServiceMonitor' resource targeting the tetragon pods.
      enabled: false
      # -- The set of labels to place on the 'ServiceMonitor' resource.
      labelsOverride: {}

  grpc:
    # -- Whether to enable exposing Tetragon gRPC.
    enabled: true
    # -- The address at which to expose gRPC. Examples: localhost:54321, unix:///var/run/tetragon/tetragon.sock
    address: "localhost:54321"

  gops:
     # -- The address at which to expose gops.
     address: "localhost"
     # -- The port at which to expose gops.
     port: 8118

  # -- Enable policy filter. This is required for K8s namespace and pod-label filtering. This feature is in beta, so disabled by default.
  enablePolicyFilter: false
  # -- Enable policy filter debug messages.
  enablePolicyFilterDebug: false

tetragonOperator:
  # -- tetragon-operator image.
  image:
    override: ~
    repository: quay.io/isovalent/tetragon-operator
    tag: v1.11.1
    pullPolicy: IfNotPresent
  # Skip CRD creation.
  skipCRDCreation: false
  podInfo:
    # -- Enables the PodInfo CRD and the controller that reconciles PodInfo
    # custom resources.
    enabled: true

export:
  # Valid values: "stdout". Disabled by default, populate the value to enable.
  mode: ""
  extraArgs: {}
  extraEnv: []
  extraVolumeMounts: []
  securityContext: {}

  # Override the command. For advanced users only.
  commandOverride: [ ]

  # Override the arguments. For advanced users only.
  argsOverride: [ ]

  # filenames defines list of files for fluentd to tail and export.
  filenames:
  - fgs.log

  stdout:
    image:
      override: ~
      repository: quay.io/isovalent/hubble-export-stdout
      tag: v1.0.3
