// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

#ifndef DNS_PSTREE_H
#define DNS_PSTREE_H

#include "vmlinux.h"
#include "bpf_task.h"
#include "l3_config.h"
#include "fgs_rodata_config.h"

#include "dns.h"
#include "process/process_endpoint.h"
#include "errmetrics.h"

static __u64 BPF_FUNC(sk_cgroup_id, void *sk);
static __u64 BPF_FUNC(sk_ancestor_cgroup_id, void *sk, int ancestor_level);

// DNS needs source in its endpoint_id_value because these IDs can come from the
// BPF side, from the parser that reads DNS answers, or from userspace network
// policies.
struct dns_endpoint_id_value {
	uint64_t id;
	uint64_t source;
};

// This is a dummy var for BTF: because of a compiler bug, the struct only used
// in inner maps are not included in the BTF defition, which leads to the
// following loading error:
//
// load BTF maps: map tg_dns_ip_id_maps: can't parse BTF map definition of inner
// map: can't get size of BTF key: type *btf.Fwd: type is unsized"
//
// See more https://github.com/cilium/ebpf/discussions/1658#discussioncomment-12491339
struct ip_addr dummy_btf_ip_addr;

// IP -> ID. This maps an IP address (the IPv4 or IPv6 address) to the endpoint
// ID generated by the BPF DNS parser or userspace. This map is read-write from
// BPF and read-only from userspace.
struct {
	__uint(type, BPF_MAP_TYPE_ARRAY_OF_MAPS);
	__type(key, __u32); /* allocPodID */
	__uint(max_entries, 1); // will be resized by userspace
	__array(
		values, struct {
			__uint(type, BPF_MAP_TYPE_LRU_HASH);
			__uint(max_entries, 1); // will be resized by userspace
			__type(key, struct ip_addr);
			__type(value, struct dns_endpoint_id_value);
		});
} tg_dns_ip_id SEC(".maps");

// domain_string -> ID, this is read-write from BPF and userspace. From the BPF
// DNS parser and userspace network policies.
struct {
	__uint(type, BPF_MAP_TYPE_LRU_HASH);
	__uint(max_entries, 1); // will be resized by user space
	__type(key, char[DNS_MAX_NAME_SIZE + 1]);
	__type(value, struct dns_endpoint_id_value);
} tg_dns_fqdn_id SEC(".maps");

// ID -> domain_string, same as the above map but for debugging and printing purposes.
struct {
	__uint(type, BPF_MAP_TYPE_LRU_HASH);
	__uint(max_entries, 1); // will be resized by user space
	__type(key, struct dns_endpoint_id_value);
	__type(value, char[DNS_MAX_NAME_SIZE + 1]);
} tg_dns_id_fqdn SEC(".maps");

struct {
	__uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
	__uint(max_entries, 1);
	__type(key, uint32_t);
	__type(value, struct dns_endpoint_id_value);
} tg_h_dns_epid SEC(".maps");

struct {
	__uint(type, BPF_MAP_TYPE_ARRAY);
	__uint(max_entries, 1);
	__type(key, uint32_t);
	__type(value, uint64_t);
} tg_glb_dns_id SEC(".maps");

// The global counter for the allocation ID which are the links between the
// cgroup ID and the Pods.
struct {
	__uint(type, BPF_MAP_TYPE_ARRAY);
	__uint(max_entries, 1);
	__type(key, uint32_t);
	__type(value, uint32_t);
} tg_dns_alloc_id SEC(".maps");

// The link between the cgroup IDs and the allocation IDs.
struct {
	__uint(type, BPF_MAP_TYPE_HASH);
	__uint(max_entries, 1); // will be resized by userspace
	__type(key, uint64_t);
	__type(value, uint32_t);
} tg_dns_cgid_aid SEC(".maps");

volatile __CONST uint64_t KUBEPODS_SLICE_CGID;

#define MAX_CGROUP_DEPTH 30

// find_parent_cgroupid_network walk the cgroup hierarchy from root to the sk
// cgroup to find the kubepods.slice cgroup, if found it returns the parent of
// the sk cgroup, if not found (or in case of error) it returns zero.
//
// This function has a twin tracing function named find_parent_cgroupid_tracing
// that should be updated if this code is changed.
FUNC_INLINE uint64_t find_parent_cgroupid_network(struct bpf_sock *sk)
{
	uint64_t cgid, previous_cgid, own_cgid;
	uint8_t kubepods_found = false;

	if (!sk)
		return 0;

	own_cgid = sk_cgroup_id(sk);

	previous_cgid = 0;
	for (size_t i = 0; i < MAX_CGROUP_DEPTH; i++) {
		cgid = sk_ancestor_cgroup_id(sk, i);

		if (cgid == KUBEPODS_SLICE_CGID)
			kubepods_found = true;

		if (cgid == own_cgid) {
			if (kubepods_found)
				return previous_cgid;
			else
				return 0;
		}

		previous_cgid = cgid;
	}

	return 0;
}

// find_parent_cgroupid_tracing is the tracing version of the network
// find_parent_cgroupid_network function. Make sure all changes are reflected to
// the other function as well.
FUNC_INLINE uint64_t find_parent_cgroupid_tracing(void)
{
	uint64_t cgid, previous_cgid, own_cgid;
	uint8_t kubepods_found = false;

	own_cgid = get_current_cgroup_id();

	previous_cgid = 0;
	for (size_t i = 0; i < MAX_CGROUP_DEPTH; i++) {
		cgid = get_current_ancestor_cgroup_id(i);

		if (cgid == KUBEPODS_SLICE_CGID)
			kubepods_found = true;

		if (cgid == own_cgid) {
			if (kubepods_found)
				return previous_cgid;
			else
				return 0;
		}

		previous_cgid = cgid;
	}

	return 0;
}

FUNC_INLINE int find_alloc_id(uint64_t cgroup_id)
{
	uint32_t *alloc_id;
	uint32_t zero = 0;

	// if cgroup_id is equal to zero, that means either that the process
	// does not belong to a Pod (is a "host process") or that the cgroup ID
	// lookup failed. In both cases, default to alloc ID zero.
	if (cgroup_id != 0 && FGS_CONFIG(DNS_PARSER_PER_POD_ENABLED)) {
		alloc_id = map_lookup_elem(&tg_dns_cgid_aid, &cgroup_id);
		if (!alloc_id) {
			// lookup the global variable counter
			alloc_id = map_lookup_elem(&tg_dns_alloc_id, &zero);
			if (unlikely(!alloc_id))
				return -DNS_ERR_ZERO_ELEM_NULL;

			__sync_add_and_fetch(alloc_id, 1);

			// bind the cgid to an alloc_id
			if (map_update_elem(&tg_dns_cgid_aid, &cgroup_id, alloc_id, 0) < 0)
				return -DNS_ERR_ALLOCID_BIND;
		}
		return *alloc_id;
	}

	return 0;
}

FUNC_INLINE void find_dns_key(struct destination_endpoint_key *key, struct ip_addr ip_key)
{
	int alloc_id = 0;
	struct dns_endpoint_id_value *dns_value;
	void *tg_dns_ip_id_map;

	if (FGS_CONFIG(DNS_PARSER_PER_POD_ENABLED))
		alloc_id = find_alloc_id(find_parent_cgroupid_tracing());

	if (alloc_id >= 0) {
		tg_dns_ip_id_map = map_lookup_elem(&tg_dns_ip_id, &alloc_id);
		if (tg_dns_ip_id_map) {
			dns_value = map_lookup_elem(tg_dns_ip_id_map, &ip_key);
			if (dns_value) {
				key->destination_id = dns_value->id;
				key->source = dns_value->source;
			}
		} else {
			// Monitor the case in which no maps are here for the alloc ID
			errmetrics(EAGAIN); // EAGAIN: Resource temporarily unavailable
		}
	}
}

// Assigns an ID from the ip and domain. Most of the time it generates a new ID
// from BPF side but reuses an existing userspace-generated policy ID when one
// exists. This is only used in the BPF DNS parser.
FUNC_INLINE int assign_dns_id_mapping(struct __sk_buff *skb, struct ip_addr *ip, char *domain)
{
	struct dns_endpoint_id_value *id_val;
	void *ip_id_map;
	uint64_t *global_id;
	uint32_t zero = 0;
	int alloc_id = 0;

	// build ID for domain
	id_val = map_lookup_elem(&tg_dns_fqdn_id, domain);
	if (id_val) {
		// If the ID is not coming from userspace or the DNS parser BPF
		// side, the map was malformed with a wrong source. Note that
		// SOURCE_DNS should still write into tg_dns_ip_id
		// because we can have many IPs to the same domain.
		if (id_val->source != DESTINATION_SOURCE_USERSPACE && id_val->source != DESTINATION_SOURCE_DNS)
			return -DNS_ERR_ASSIGN_INVALID_SOURCE;
	} else {
		// Generate a new ID from BPF side
		id_val = map_lookup_elem(&tg_h_dns_epid, &zero);
		if (unlikely(!id_val))
			return -DNS_ERR_ZERO_ELEM_NULL;
		global_id = map_lookup_elem(&tg_glb_dns_id, &zero);
		if (unlikely(!global_id))
			return -DNS_ERR_ZERO_ELEM_NULL;

		id_val->id = __sync_add_and_fetch(global_id, 1);
		id_val->source = DESTINATION_SOURCE_DNS;

		DEBUG("ID generated: %d", id_val->id);

		if (map_update_elem(&tg_dns_fqdn_id, domain, id_val, BPF_ANY) < 0)
			return -DNS_ERR_ASSIGN_FQDNID_UPDATE_FAILED;
		if (map_update_elem(&tg_dns_id_fqdn, id_val, domain, BPF_ANY))
			return -DNS_ERR_ASSIGN_IDFQDN_UPDATE_FAILED;
	}

	if (FGS_CONFIG(DNS_PARSER_PER_POD_ENABLED)) {
		alloc_id = find_alloc_id(find_parent_cgroupid_network(skb->sk));
		if (alloc_id < 0)
			return alloc_id;
	}

	ip_id_map = map_lookup_elem(&tg_dns_ip_id, &alloc_id);
	if (!ip_id_map)
		return -DNS_ERR_ASSIGN_INNER_MISSING;

	if (map_update_elem(ip_id_map, ip, id_val, BPF_ANY))
		return -DNS_ERR_ASSIGN_IPID_UPDATE_FAILED;

	return 0;
}

#endif // DNS_PSTREE_H
