// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

#ifndef DNS_PSTREE_H
#define DNS_PSTREE_H

#include "vmlinux.h"
#include "bpf_task.h"

#include "dns.h"
#include "process/process_endpoint.h"

// DNS needs source in its endpoint_id_value because these IDs can come from the
// BPF side; from the parser that reads DNS answers or from the userspace side,
// from the parser of the quota policies.
struct dns_endpoint_id_value {
	uint64_t id;
	uint64_t source;
};

// This is a dummy var for BTF: because of a compiler bug, the struct only used
// in inner maps are not included in the BTF defition, which leads to the
// following loading error:
//
// load BTF maps: map tg_dns_ip_id_maps: can't parse BTF map definition of inner
// map: can't get size of BTF key: type *btf.Fwd: type is unsized"
//
// See more https://github.com/cilium/ebpf/discussions/1658#discussioncomment-12491339
struct ip_addr dummy_btf_ip_addr;

// IP -> ID. This maps an IP address (the IPv4 or IPv6 address) to the endpoint
// ID generated by the BPF DNS parser or userspace. This map is read-write from
// BPF and read-only from userspace.
struct {
	__uint(type, BPF_MAP_TYPE_ARRAY_OF_MAPS);
	__type(key, __u32); /* allocPodID */
	__uint(max_entries, 1); // will be resized by userspace
	__array(
		values, struct {
			__uint(type, BPF_MAP_TYPE_LRU_HASH);
			__uint(max_entries, 1); // will be resized by userspace
			__type(key, struct ip_addr);
			__type(value, struct dns_endpoint_id_value);
		});
} tg_dns_ip_id SEC(".maps");

// domain_string -> ID, this is read-write from BPF and userspace. From the BPF
// DNS parser and the quota policy parser.
struct {
	__uint(type, BPF_MAP_TYPE_LRU_HASH);
	__uint(max_entries, 1); // will be resized by user space
	__type(key, char[DNS_MAX_NAME_SIZE + 1]);
	__type(value, struct dns_endpoint_id_value);
} tg_dns_fqdn_id SEC(".maps");

// ID -> domain_string, same as the above map but for debugging and printing purposes.
struct {
	__uint(type, BPF_MAP_TYPE_LRU_HASH);
	__uint(max_entries, 1); // will be resized by user space
	__type(key, struct dns_endpoint_id_value);
	__type(value, char[DNS_MAX_NAME_SIZE + 1]);
} tg_dns_id_fqdn SEC(".maps");

struct {
	__uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
	__uint(max_entries, 1);
	__type(key, uint32_t);
	__type(value, struct dns_endpoint_id_value);
} tg_h_dns_epid SEC(".maps");

struct {
	__uint(type, BPF_MAP_TYPE_ARRAY);
	__uint(max_entries, 1);
	__type(key, uint32_t);
	__type(value, uint64_t);
} tg_glb_dns_id SEC(".maps");

// The global counter for the allocation ID which are the links between the
// cgroup ID and the Pods.
struct {
	__uint(type, BPF_MAP_TYPE_ARRAY);
	__uint(max_entries, 1);
	__type(key, uint32_t);
	__type(value, uint32_t);
} tg_dns_alloc_id SEC(".maps");

struct {
	__uint(type, BPF_MAP_TYPE_ARRAY);
	__uint(max_entries, 1);
	__type(key, uint32_t);
	__type(value, uint64_t);
} tg_kpod_cgid SEC(".maps");

// The link between the cgroup IDs and the allocation IDs.
struct {
	__uint(type, BPF_MAP_TYPE_HASH);
	__uint(max_entries, 1); // will be resized by userspace
	__type(key, uint64_t);
	__type(value, uint32_t);
} tg_dns_cgid_aid SEC(".maps");

// Assigns an ID from the ip and domain. Most of the time it generates a new ID
// from BPF side but, in the case a quota policy was parsed by userspace, reuses
// an existing userspace generated ID. This is only used in the BPF DNS parser.
FUNC_INLINE int assign_dns_id_mapping(struct ip_addr *ip, char *domain)
{
	struct dns_endpoint_id_value *id_val;
	void *ip_id_map;
	uint64_t *global_id;
	uint32_t zero = 0;

	// build ID for domain
	id_val = map_lookup_elem(&tg_dns_fqdn_id, domain);
	if (id_val) {
		// If the ID is not coming from userspace or the DNS parser BPF
		// side, the map was malformed with a wrong source. Note that
		// SOURCE_DNS should still write into tg_dns_ip_id
		// because we can have many IPs to the same domain.
		if (id_val->source != DESTINATION_SOURCE_USERSPACE && id_val->source != DESTINATION_SOURCE_DNS)
			return -1;
	} else {
		// Generate a new ID from BPF side
		id_val = map_lookup_elem(&tg_h_dns_epid, &zero);
		if (!id_val)
			return -1;
		global_id = map_lookup_elem(&tg_glb_dns_id, &zero);
		if (!global_id)
			return -1;

		id_val->id = __sync_add_and_fetch(global_id, 1);
		id_val->source = DESTINATION_SOURCE_DNS;

		DEBUG("ID generated: %d", id_val->id);

		map_update_elem(&tg_dns_fqdn_id, domain, id_val, BPF_ANY);
		map_update_elem(&tg_dns_id_fqdn, id_val, domain, BPF_ANY);
	}

	ip_id_map = map_lookup_elem(&tg_dns_ip_id, &zero);
	if (!ip_id_map)
		return -1;
	map_update_elem(ip_id_map, ip, id_val, BPF_ANY);

	return 0;
}

#endif // DNS_PSTREE_H
