apiVersion: cilium.io/v1alpha1
kind: TetragonNetworkPolicy
metadata:
  name: "example-label-segmentation"
  annotations:
    author: "IsovalentQATeam"
spec:
  logicalNetworkSelector:
    vrf: "red"
  defaultAction: "deny"
  rules:
  - description: "smartswitchRedPolicy"
    hook: "firewall"
    action: "allow"
    source:
    - ipBlock:
        cidr: "10.1.0.1/16"
      ports:
        protocol: "TCP"
    destination:
    - ipBlock:
        cidr: "10.2.0.1/16"
      ports:
        protocol: "TCP"
