{{- if or .Values.tracingPolicies.default.enabled .Values.tracingPolicies.default.privileges.enabled }}
{{- range $path, $_ := .Files.Glob "default-policies/privileges/**.yaml" }}
---
{{ $.Files.Get $path }}
{{- end }}
{{- end }}
