services:
  agw-test:
    image: isovalent/agw-test
    container_name: agw-test
    network_mode: host
    environment:
      - AGW_CONFIG=
      - AGW_NETWORK_POLICY=
      - AGW_ENABLE_K8S=false
      - AGW_ENABLE_NXOS=false
      - AGW_DPU_SERVER_ADDRESS=0.0.0.0:8880
      - AGW_VRF_MAP=default:1
      - AGW_DEBUG=true
      - AGW_K8S_SERVICE_ACCOUNT_AUTH=

  fwa-test:
    image: isovalent/fwa-test
    container_name: fwa-test
    network_mode: host
    environment:
      - FWA_CONFIG=
      - FWA_NETWORK_POLICY=
      - FWA_ENABLE_DATAPLANE=false
      - FWA_ENABLE_AGW=true
      - FWA_ENABLE_LOGGER=false
      - FWA_SERVER_ADDRESS=127.0.0.1:8880
      - FWA_DP_SOCKET_PATH=
      - FWA_DEBUG=true
