//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright (c) 2021 Isovalent

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionSelector) DeepCopyInto(out *ActionSelector) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionSelector.
func (in *ActionSelector) DeepCopy() *ActionSelector {
	if in == nil {
		return nil
	}
	out := new(ActionSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgSelector) DeepCopyInto(out *ArgSelector) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgSelector.
func (in *ArgSelector) DeepCopy() *ArgSelector {
	if in == nil {
		return nil
	}
	out := new(ArgSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpSelector) DeepCopyInto(out *HttpSelector) {
	*out = *in
	if in.MatchPorts != nil {
		in, out := &in.MatchPorts, &out.MatchPorts
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpSelector.
func (in *HttpSelector) DeepCopy() *HttpSelector {
	if in == nil {
		return nil
	}
	out := new(HttpSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpSpec) DeepCopyInto(out *HttpSpec) {
	*out = *in
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]HttpSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpSpec.
func (in *HttpSpec) DeepCopy() *HttpSpec {
	if in == nil {
		return nil
	}
	out := new(HttpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KProbeArg) DeepCopyInto(out *KProbeArg) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KProbeArg.
func (in *KProbeArg) DeepCopy() *KProbeArg {
	if in == nil {
		return nil
	}
	out := new(KProbeArg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KProbeSelector) DeepCopyInto(out *KProbeSelector) {
	*out = *in
	if in.MatchPIDs != nil {
		in, out := &in.MatchPIDs, &out.MatchPIDs
		*out = make([]PIDSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchArgs != nil {
		in, out := &in.MatchArgs, &out.MatchArgs
		*out = make([]ArgSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchActions != nil {
		in, out := &in.MatchActions, &out.MatchActions
		*out = make([]ActionSelector, len(*in))
		copy(*out, *in)
	}
	if in.MatchReturnArgs != nil {
		in, out := &in.MatchReturnArgs, &out.MatchReturnArgs
		*out = make([]ArgSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KProbeSelector.
func (in *KProbeSelector) DeepCopy() *KProbeSelector {
	if in == nil {
		return nil
	}
	out := new(KProbeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KProbeSpec) DeepCopyInto(out *KProbeSpec) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]KProbeArg, len(*in))
		copy(*out, *in)
	}
	out.ReturnArg = in.ReturnArg
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]KProbeSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KProbeSpec.
func (in *KProbeSpec) DeepCopy() *KProbeSpec {
	if in == nil {
		return nil
	}
	out := new(KProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PIDSelector) DeepCopyInto(out *PIDSelector) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PIDSelector.
func (in *PIDSelector) DeepCopy() *PIDSelector {
	if in == nil {
		return nil
	}
	out := new(PIDSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParserPolicySpec) DeepCopyInto(out *ParserPolicySpec) {
	*out = *in
	in.Tls.DeepCopyInto(&out.Tls)
	in.Http.DeepCopyInto(&out.Http)
	out.Udp = in.Udp
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParserPolicySpec.
func (in *ParserPolicySpec) DeepCopy() *ParserPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ParserPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TlsSelector) DeepCopyInto(out *TlsSelector) {
	*out = *in
	if in.MatchPorts != nil {
		in, out := &in.MatchPorts, &out.MatchPorts
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TlsSelector.
func (in *TlsSelector) DeepCopy() *TlsSelector {
	if in == nil {
		return nil
	}
	out := new(TlsSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TlsSpec) DeepCopyInto(out *TlsSpec) {
	*out = *in
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]TlsSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TlsSpec.
func (in *TlsSpec) DeepCopy() *TlsSpec {
	if in == nil {
		return nil
	}
	out := new(TlsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracepointSpec) DeepCopyInto(out *TracepointSpec) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]KProbeArg, len(*in))
		copy(*out, *in)
	}
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]KProbeSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracepointSpec.
func (in *TracepointSpec) DeepCopy() *TracepointSpec {
	if in == nil {
		return nil
	}
	out := new(TracepointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingPolicy) DeepCopyInto(out *TracingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingPolicy.
func (in *TracingPolicy) DeepCopy() *TracingPolicy {
	if in == nil {
		return nil
	}
	out := new(TracingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TracingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingPolicyList) DeepCopyInto(out *TracingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TracingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingPolicyList.
func (in *TracingPolicyList) DeepCopy() *TracingPolicyList {
	if in == nil {
		return nil
	}
	out := new(TracingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TracingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingPolicySpec) DeepCopyInto(out *TracingPolicySpec) {
	*out = *in
	if in.KProbes != nil {
		in, out := &in.KProbes, &out.KProbes
		*out = make([]KProbeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tracepoints != nil {
		in, out := &in.Tracepoints, &out.Tracepoints
		*out = make([]TracepointSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Parser.DeepCopyInto(&out.Parser)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingPolicySpec.
func (in *TracingPolicySpec) DeepCopy() *TracingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TracingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdpPolicySpec) DeepCopyInto(out *UdpPolicySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdpPolicySpec.
func (in *UdpPolicySpec) DeepCopy() *UdpPolicySpec {
	if in == nil {
		return nil
	}
	out := new(UdpPolicySpec)
	in.DeepCopyInto(out)
	return out
}
