apiVersion: hubble-enterprise.io/v1
metadata:
  name: "tracepoint-lseek"
spec:
  description: "tracepoint lseek hook"
  tracepoints:
  - subsystem: "syscalls"
    event: "sys_enter_lseek"
    args:
    - index: 7
    - index: 5
    selectors:
    - matchpids:
        - operator: eq
          values:
          - 1111
          followforks: true
          isnamespacepid: false
      matchargs:
      - index: 7
        operator: eq
        values:
        - "4444"
