{
 "title": "Tetragon / HTTP Golden Signals / Pod <-> Pod",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tetragon_events_total, cluster)"
    }
   },
   {
    "name": "namespace_a",
    "label": "namespace A",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "workload_a",
    "label": "workload A",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\"}, workload)"
    }
   },
   {
    "name": "pod_a",
    "label": "pod A",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\"}, pod)"
    }
   },
   {
    "name": "namespace_b",
    "label": "namespace B",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "workload_b",
    "label": "workload B",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\"}, workload)"
    }
   },
   {
    "name": "pod_b",
    "label": "pod B",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview A -> B", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (5xx Responses) Rate (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\", code=~\"5..\"}[$__range])) / sum(increase(tetragon_http_response_total{cluster=~\"$cluster\", cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Median Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (5xx Responses) Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\", code=~\"5..\"}[$__rate_interval])) / sum(rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration [s] histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration histogram over time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  { "title": "Overview B -> A", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Requests (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (5xx Responses) Rate (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\", code=~\"5..\"}[$__range])) / sum(increase(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Median Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (5xx Responses) Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\", code=~\"5..\"}[$__rate_interval])) / sum(rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration [s] histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration histogram over time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  }
 ]
}