{{- if or .Values.tracingPolicies.default.enabled .Values.tracingPolicies.default.network.enabled }}
{{- range $path, $_ := .Files.Glob "default-policies/network/**.yaml" }}
---
{{ $.Files.Get $path }}
{{- end }}
{{- end }}
