{{- if or .Values.tracingPolicies.default.enabled .Values.tracingPolicies.default.mount.enabled }}
{{- range $path, $_ := .Files.Glob "default-policies/mount/**.yaml" }}
---
{{ $.Files.Get $path }}
{{- end }}
{{- end }}
