{{- if or .Values.tracingPolicies.default.enabled .Values.tracingPolicies.default.security.enabled }}
{{- range $path, $_ := .Files.Glob "default-policies/security/**.yaml" }}
---
{{ $.Files.Get $path }}
{{- end }}
{{- end }}
