{{- if or .Values.splunk_hec.tls.ca .Values.splunk_hec.tls.crt .Values.splunk_hec.tls.key }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- with .Values.secretLabelsOverride}}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    {{- include "tetragon.labels" . | nindent 4 }}
    {{- end }}
  name: {{ include "tetragon.name" . }}-splunk-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- if .Values.splunk_hec.tls.ca }}
  ca.crt: {{ .Values.splunk_hec.tls.ca | default "" | b64enc }}
{{- end }}
{{- if .Values.splunk_hec.tls.crt }}
  tls.crt: {{ .Values.splunk_hec.tls.crt | default "" | b64enc }}
{{- end }}
{{- if .Values.splunk_hec.tls.key }}
  tls.key: {{ .Values.splunk_hec.tls.key | default "" | b64enc }}
{{- end }}
{{- end }}
