// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

//go:build sudo_tests

package jhashtest

import (
	"errors"
	"flag"
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/cilium/ebpf"
	"github.com/cilium/tetragon/pkg/kernels"
	"github.com/stretchr/testify/require"
)

const (
	programName = "test_jhash"
	objName     = "jhash_test.o"
	testMapName = "tg_jhash_test"
)

var verifierLogs = flag.Bool("verlogs", false, "Write the full verifier logs in the ./verifier.log file")

func loadJhashTestCollection(t *testing.T) *ebpf.Collection {
	// load test program
	collSpec, err := ebpf.LoadCollectionSpec(filepath.Join("../../../bpf/tests/objs", objName))
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			t.Fatalf("please run 'make tetragon-bpf-test' to compile the BPF test program: %s", err)
		}
		t.Fatal(err)
	}

	collOpts := ebpf.CollectionOptions{}
	if verifierLogs != nil && *verifierLogs {
		collOpts.Programs = ebpf.ProgramOptions{
			LogLevel: ebpf.LogLevelInstruction,
		}
	}
	coll, err := ebpf.NewCollectionWithOptions(collSpec, collOpts)
	if err != nil {
		if ve, ok := errors.AsType[*ebpf.VerifierError](err); ok {
			t.Fatalf("verifier error: %+v\n", ve)
		}
		t.Fatal(err)
	}
	t.Cleanup(func() {
		coll.Close()
	})

	prog, ok := coll.Programs[programName]
	if !ok {
		t.Fatalf("%s not found", programName)
	}

	if verifierLogs != nil && *verifierLogs {
		logFile, err := os.Create("verifier.log")
		if err != nil {
			t.Fatal(err)
		}

		_, err = logFile.WriteString(prog.VerifierLog)
		if err != nil {
			t.Fatal(err)
		}
		logFile.Close()
	}

	return coll
}

type jhashTest struct {
	Input  [16]byte
	Output uint32
	Len    uint32
}

type jhashTestUnix struct {
	Input  []byte
	Output uint32
	Len    uint32
}

func TestJhash(t *testing.T) {
	if !kernels.MinKernelVersion("5.10") {
		t.Skipf("Jhash test causes verifier issues on kernels <v5.10. This is not a problem for testing the correctness of the algorithm though.")
	}

	coll := loadJhashTestCollection(t)

	prog, ok := coll.Programs[programName]
	if !ok {
		t.Fatalf("%s not found", programName)
	}

	testMap, ok := coll.Maps[testMapName]
	if !ok {
		t.Fatalf("map %s not found", testMap)
	}

	// The following hash outputs were generated by exercising the kernel's jhash function in a C program.
	tests := []jhashTestUnix{
		{Input: []byte{0x1e}, Output: 0xd9b90840},
		{Input: []byte{0x33, 0xa3}, Output: 0x4b89f942},
		{Input: []byte{0xa5, 0x41, 0xd0}, Output: 0xd8ad39f6},
		{Input: []byte{0xb0, 0xe6, 0x00, 0x1d}, Output: 0x9ff057f8},
		{Input: []byte{0x27, 0x98, 0x31, 0x10, 0xb1}, Output: 0x55c1ccc3},
		{Input: []byte{0x0b, 0x17, 0x9c, 0x15, 0x6d, 0x53}, Output: 0x04090f4b},
		{Input: []byte{0xa6, 0x42, 0x5f, 0x2d, 0x8f, 0xd8, 0x40}, Output: 0x2a8a8b63},
		{Input: []byte{0x8f, 0xce, 0x78, 0x42, 0xfc, 0xe1, 0xb4, 0x6c}, Output: 0xcfe3e010},
		{Input: []byte{0x40, 0x5d, 0xca, 0x79, 0xf9, 0x74, 0xd5, 0x6e, 0xb4}, Output: 0xfaaafa9e},
		{Input: []byte{0x52, 0x0a, 0xd2, 0x17, 0xe9, 0xc3, 0xca, 0x08, 0x66, 0xf1}, Output: 0x2d061451},
		{Input: []byte{0x16, 0xce, 0x68, 0x2f, 0x08, 0x8d, 0xbd, 0x12, 0x21, 0x21, 0xd7}, Output: 0x9b89a48f},
		{Input: []byte{0xb3, 0xec, 0x40, 0x24, 0xc2, 0x03, 0x59, 0x17, 0xe8, 0x6e, 0xad, 0x41}, Output: 0xa30bfebc},
		{Input: []byte{0x73, 0xc7, 0x7e, 0x41, 0xd7, 0xbb, 0x5d, 0x07, 0x52, 0x0f, 0x3f, 0x3c, 0x7e}, Output: 0x31207e83},
		{Input: []byte{0x44, 0x0f, 0xd4, 0x6f, 0x12, 0x8c, 0x3a, 0x2b, 0xf9, 0x0f, 0xa8, 0x11, 0xea, 0x51}, Output: 0xa03506fb},
		{Input: []byte{0xa2, 0x64, 0x7b, 0x01, 0x1e, 0xeb, 0xc4, 0x04, 0xd8, 0x05, 0x7e, 0x26, 0x31, 0x33, 0xf4}, Output: 0xa5824adc},
	}

	for _, test := range tests {
		key := uint32(0)
		value := jhashTest{Len: uint32(len(test.Input))}
		copy(value.Input[:], test.Input)
		err := testMap.Update(key, value, ebpf.UpdateAny)
		require.NoError(t, err)
		_, err = prog.Run(&ebpf.RunOptions{})
		require.NoError(t, err)

		err = testMap.Lookup(key, &value)
		require.NoError(t, err)

		require.Equal(t, test.Output, value.Output)
		t.Logf("Input: 0x%x, Output: 0x%08x", test.Input, value.Output)
	}
}
