{
 "title": "Tetragon / TCP Throughput / Socket - Host Binaries",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tetragon_events_total, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"}, node)"
    }
   },
   {
    "name": "binary",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\"}, binary)"
    }
   },
   {
    "name": "dstdns",
    "label": "remote DNS name",
    "query": {
     "query": "query_result(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\"} or tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes Sent (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retransmitted Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_retransmitbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Sent (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retransmitted Segments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_retransmitsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Sent Segment Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range])) / sum(increase(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Sent Segment Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) / sum(increase(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Received (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket Drops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_drops_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Received (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zero Windows",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_zerowindow_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Received Segment Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range])) / sum(increase(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Received Segment Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) / sum(increase(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX by Node & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Sent (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (rate(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Segments Sent (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "seg/s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (rate(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Avg Sent Segment Size (top 5)",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "topk(5, (sum by (node, binary) (increase(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) / sum by (node, binary) (increase(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval]))) > 0) or vector(0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RX by Node & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Received (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (rate(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Segments Received (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "seg/s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (rate(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Avg Received Segment Size (top 5)",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "topk(5, (sum by (node, binary) (increase(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) / sum by (node, binary) (increase(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval]))) > 0) or vector(0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Retransmits and Drops by Node & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Retransmitted Bytes per $__interval",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (increase(tetragon_socket_stats_retransmitbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0) or vector(0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Retransmitted Segments per $__interval",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (increase(tetragon_socket_stats_retransmitsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0) or vector(0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Socket Drops per $__interval",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (increase(tetragon_socket_stats_drops_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0) or vector(0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Zero Windows per $__interval",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (increase(tetragon_socket_stats_zerowindow_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0) or vector(0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TX by Remote DNS Name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Sent (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (rate(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Segments Sent (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "seg/s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (rate(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Avg Sent Segment Size (top 5)",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "topk(5, (sum by (dstdns) (increase(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) / sum by (dstdns) (increase(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval]))) > 0) or vector(0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RX by Remote DNS Name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Received (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (rate(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Segments Received (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "seg/s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (rate(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Avg Received Segment Size (top 5)",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "topk(5, (sum by (dstdns) (increase(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) / sum by (dstdns) (increase(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval]))) > 0) or vector(0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Retransmits and Drops by Remote DNS Name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Retransmitted Bytes per $__interval",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (increase(tetragon_socket_stats_retransmitbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0) or vector(0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Retransmitted Bytes per $__interval",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (increase(tetragon_socket_stats_retransmitsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0) or vector(0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Socket Drops per $__interval",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (increase(tetragon_socket_stats_drops_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0) or vector(0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Zero Windows per $__interval",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (increase(tetragon_socket_stats_zerowindow_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0) or vector(0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    }
   ]
  }
 ]
}