apiVersion: cilium.io/v1alpha1
kind: TetragonNetworkPolicy
metadata:
  name: "example-label-segmentation"
  annotations:
    author: "IsovalentQATeam"
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  podSelector:
    matchLabels:
      class: "xwing"
  processSelector:
    operator: "In"
    values:
      - "/usr/bin/curl"
      - "/usr/sbin/curl"
  defaultAction: "deny"
  rules:
  - description: "connectAllowRule"
    hook: "connect"
    action: "allow"
    destination:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: "deathstar"
      ports:
        protocol: "TCP"
        ports: [80, 8080]
    - ipBlock:
        cidr: "127.0.0.1/32"
      ports:
        protocol: "TCP"
    - ipBlock:
        cidr: "142.250.217.78/24" # google
      ports:
        protocol: "TCP"
    - FQDN:
      - "ebpf.io"
      - "tetragon.io"
      ports:
        protocol: "TCP"
        ports: [80, 8080]
