// System call ids for x86 ABIs
// Autogenerated by kernel-syscall-info

package syscallinfo

import (
	"runtime"
	"testing"

	"github.com/cilium/tetragon/pkg/sensors/tracing"
	"github.com/stretchr/testify/require"
)

func TestIDs(t *testing.T) {
	if runtime.GOARCH != "amd64" {
		t.Skip()
	}
	for n, s := range kernelSyscallIDs {
		// remove "sys_" prefix
		name := n[4:]
		{
			id := int(-1)
			if s.X64 != nil {
				id = int(*s.X64)
			}
			ossid, _ := tracing.SyscallVal(name).ID()
			if ossid == -1 && ossid != id {
				t.Logf("oss syscallinfo seems to be missing for x64/%s", name)
				continue
			}
			require.Equal(t, ossid, id, name)
		}

		{
			id32 := int(-1)
			if s.IA32 != nil {
				id32 = int(*s.IA32)
			}
			ossid32, _ := tracing.SyscallVal("i386/" + name).ID()
			if ossid32 == -1 && ossid32 != id32 {
				t.Logf("oss syscallinfo seems to be missing for ia32/%s", name)
				continue
			}
			if ossid32 != -1 {
				ossid32 &= ^tracing.Is32Bit
			}
			require.Equal(t, ossid32, id32, "i386/"+name)
		}
	}
}
