package syscallinfo

type X86ID struct {
	X64, X32, IA32 *uint
}

func GetX86IDs(n string) *X86ID {
	ret, ok := kernelSyscallIDs[n]
	if !ok {
		return nil
	}
	return &ret
}

// System call ids for x86 ABIs
// Autogenerated by kernel-syscall-info
func idptr__(x uint) *uint {
	return &x
}

var kernelSyscallIDs = map[string]X86ID{
	"sys_bdflush": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(134),
	},
	"sys_getgroups32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(205),
	},
	"sys_dup2": {
		X64:  idptr__(33),
		X32:  nil,
		IA32: idptr__(63),
	},
	"sys_set_robust_list": {
		X64:  idptr__(273),
		X32:  idptr__(530),
		IA32: idptr__(311),
	},
	"sys_nice": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(34),
	},
	"sys_io_setup": {
		X64:  idptr__(206),
		X32:  idptr__(543),
		IA32: idptr__(245),
	},
	"sys_pselect6_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(413),
	},
	"sys_preadv": {
		X64:  idptr__(295),
		X32:  idptr__(534),
		IA32: idptr__(333),
	},
	"sys_mq_notify": {
		X64:  idptr__(244),
		X32:  idptr__(527),
		IA32: idptr__(281),
	},
	"sys_syncfs": {
		X64:  idptr__(306),
		X32:  nil,
		IA32: idptr__(344),
	},
	"sys_timer_settime": {
		X64:  idptr__(223),
		X32:  nil,
		IA32: idptr__(260),
	},
	"sys_mq_getsetattr": {
		X64:  idptr__(245),
		X32:  nil,
		IA32: idptr__(282),
	},
	"sys_keyctl": {
		X64:  idptr__(250),
		X32:  nil,
		IA32: idptr__(288),
	},
	"sys_ioctl": {
		X64:  idptr__(16),
		X32:  idptr__(514),
		IA32: idptr__(54),
	},
	"sys_map_shadow_stack": {
		X64:  idptr__(453),
		X32:  nil,
		IA32: idptr__(453),
	},
	"sys_mq_timedsend_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(418),
	},
	"sys_mount": {
		X64:  idptr__(165),
		X32:  nil,
		IA32: idptr__(21),
	},
	"sys_clock_getres": {
		X64:  idptr__(229),
		X32:  nil,
		IA32: idptr__(266),
	},
	"sys_gtty": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(32),
	},
	"sys_lseek": {
		X64:  idptr__(8),
		X32:  nil,
		IA32: idptr__(19),
	},
	"sys_shmdt": {
		X64:  idptr__(67),
		X32:  nil,
		IA32: idptr__(398),
	},
	"sys_sched_get_priority_max": {
		X64:  idptr__(146),
		X32:  nil,
		IA32: idptr__(159),
	},
	"sys_sendmmsg": {
		X64:  idptr__(307),
		X32:  idptr__(538),
		IA32: idptr__(345),
	},
	"sys_fstat64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(197),
	},
	"sys_fstatfs64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(269),
	},
	"sys_lstat": {
		X64:  idptr__(6),
		X32:  nil,
		IA32: idptr__(107),
	},
	"sys_fremovexattr": {
		X64:  idptr__(199),
		X32:  nil,
		IA32: idptr__(237),
	},
	"sys_dup3": {
		X64:  idptr__(292),
		X32:  nil,
		IA32: idptr__(330),
	},
	"sys_stime": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(25),
	},
	"sys_profil": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(98),
	},
	"sys_setresgid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(210),
	},
	"sys_setpgid": {
		X64:  idptr__(109),
		X32:  nil,
		IA32: idptr__(57),
	},
	"sys_setrlimit": {
		X64:  idptr__(160),
		X32:  nil,
		IA32: idptr__(75),
	},
	"sys_quotactl_fd": {
		X64:  idptr__(443),
		X32:  nil,
		IA32: idptr__(443),
	},
	"sys_lsm_set_self_attr": {
		X64:  idptr__(460),
		X32:  nil,
		IA32: idptr__(460),
	},
	"sys_prof": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(44),
	},
	"sys_setgroups32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(206),
	},
	"sys_recvmsg": {
		X64:  idptr__(47),
		X32:  idptr__(519),
		IA32: idptr__(372),
	},
	"sys_mlock2": {
		X64:  idptr__(325),
		X32:  nil,
		IA32: idptr__(376),
	},
	"sys_pidfd_open": {
		X64:  idptr__(434),
		X32:  nil,
		IA32: idptr__(434),
	},
	"sys_mpx": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(56),
	},
	"sys_semop": {
		X64:  idptr__(65),
		X32:  nil,
		IA32: nil,
	},
	"sys_lremovexattr": {
		X64:  idptr__(198),
		X32:  nil,
		IA32: idptr__(236),
	},
	"sys_inotify_init": {
		X64:  idptr__(253),
		X32:  nil,
		IA32: idptr__(291),
	},
	"sys_getgid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(200),
	},
	"sys_semctl": {
		X64:  idptr__(66),
		X32:  nil,
		IA32: idptr__(394),
	},
	"sys_getpgid": {
		X64:  idptr__(121),
		X32:  nil,
		IA32: idptr__(132),
	},
	"sys_iopl": {
		X64:  idptr__(172),
		X32:  nil,
		IA32: idptr__(110),
	},
	"sys_timer_delete": {
		X64:  idptr__(226),
		X32:  nil,
		IA32: idptr__(263),
	},
	"sys_tee": {
		X64:  idptr__(276),
		X32:  nil,
		IA32: idptr__(315),
	},
	"sys_pwritev": {
		X64:  idptr__(296),
		X32:  idptr__(535),
		IA32: idptr__(334),
	},
	"sys_faccessat2": {
		X64:  idptr__(439),
		X32:  nil,
		IA32: idptr__(439),
	},
	"sys_fchown32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(207),
	},
	"sys_shmat": {
		X64:  idptr__(30),
		X32:  nil,
		IA32: idptr__(397),
	},
	"sys_mlock": {
		X64:  idptr__(149),
		X32:  nil,
		IA32: idptr__(150),
	},
	"sys_timerfd_settime": {
		X64:  idptr__(286),
		X32:  nil,
		IA32: idptr__(325),
	},
	"sys_futex_requeue": {
		X64:  idptr__(456),
		X32:  nil,
		IA32: idptr__(456),
	},
	"sys_statmount": {
		X64:  idptr__(457),
		X32:  nil,
		IA32: idptr__(457),
	},
	"sys_statfs64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(268),
	},
	"sys_symlink": {
		X64:  idptr__(88),
		X32:  nil,
		IA32: idptr__(83),
	},
	"sys_setresgid": {
		X64:  idptr__(119),
		X32:  nil,
		IA32: idptr__(170),
	},
	"sys_flistxattr": {
		X64:  idptr__(196),
		X32:  nil,
		IA32: idptr__(234),
	},
	"sys_remap_file_pages": {
		X64:  idptr__(216),
		X32:  nil,
		IA32: idptr__(257),
	},
	"sys_symlinkat": {
		X64:  idptr__(266),
		X32:  nil,
		IA32: idptr__(304),
	},
	"sys_fcntl": {
		X64:  idptr__(72),
		X32:  nil,
		IA32: idptr__(55),
	},
	"sys_fspick": {
		X64:  idptr__(433),
		X32:  nil,
		IA32: idptr__(433),
	},
	"sys_futex_wake": {
		X64:  idptr__(454),
		X32:  nil,
		IA32: idptr__(454),
	},
	"sys_vmsplice": {
		X64:  idptr__(278),
		X32:  idptr__(532),
		IA32: idptr__(316),
	},
	"sys_getppid": {
		X64:  idptr__(110),
		X32:  nil,
		IA32: idptr__(64),
	},
	"sys_vhangup": {
		X64:  idptr__(153),
		X32:  nil,
		IA32: idptr__(111),
	},
	"sys__newselect": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(142),
	},
	"sys_bind": {
		X64:  idptr__(49),
		X32:  nil,
		IA32: idptr__(361),
	},
	"sys_munlockall": {
		X64:  idptr__(152),
		X32:  nil,
		IA32: idptr__(153),
	},
	"sys_utime": {
		X64:  idptr__(132),
		X32:  nil,
		IA32: idptr__(30),
	},
	"sys_break": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(17),
	},
	"sys_fchdir": {
		X64:  idptr__(81),
		X32:  nil,
		IA32: idptr__(133),
	},
	"sys_sigpending": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(73),
	},
	"sys_oldlstat": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(84),
	},
	"sys_chmod": {
		X64:  idptr__(90),
		X32:  nil,
		IA32: idptr__(15),
	},
	"sys_getpriority": {
		X64:  idptr__(140),
		X32:  nil,
		IA32: idptr__(96),
	},
	"sys_sched_rr_get_interval": {
		X64:  idptr__(148),
		X32:  nil,
		IA32: idptr__(161),
	},
	"sys_move_pages": {
		X64:  idptr__(279),
		X32:  idptr__(533),
		IA32: idptr__(317),
	},
	"sys_pidfd_send_signal": {
		X64:  idptr__(424),
		X32:  nil,
		IA32: idptr__(424),
	},
	"sys_madvise": {
		X64:  idptr__(28),
		X32:  nil,
		IA32: idptr__(219),
	},
	"sys_restart_syscall": {
		X64:  idptr__(219),
		X32:  nil,
		IA32: idptr__(0),
	},
	"sys_execveat": {
		X64:  idptr__(322),
		X32:  idptr__(545),
		IA32: idptr__(358),
	},
	"sys_getuid": {
		X64:  idptr__(102),
		X32:  nil,
		IA32: idptr__(24),
	},
	"sys_time": {
		X64:  idptr__(201),
		X32:  nil,
		IA32: idptr__(13),
	},
	"sys_putpmsg": {
		X64:  idptr__(182),
		X32:  nil,
		IA32: idptr__(189),
	},
	"sys_sigprocmask": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(126),
	},
	"sys_unlink": {
		X64:  idptr__(87),
		X32:  nil,
		IA32: idptr__(10),
	},
	"sys_syslog": {
		X64:  idptr__(103),
		X32:  nil,
		IA32: idptr__(103),
	},
	"sys_prctl": {
		X64:  idptr__(157),
		X32:  nil,
		IA32: idptr__(172),
	},
	"sys_sched_setaffinity": {
		X64:  idptr__(203),
		X32:  nil,
		IA32: idptr__(241),
	},
	"sys_accept": {
		X64:  idptr__(43),
		X32:  nil,
		IA32: nil,
	},
	"sys_lstat64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(196),
	},
	"sys_setxattr": {
		X64:  idptr__(188),
		X32:  nil,
		IA32: idptr__(226),
	},
	"sys_ulimit": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(58),
	},
	"sys_setgid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(214),
	},
	"sys_io_destroy": {
		X64:  idptr__(207),
		X32:  nil,
		IA32: idptr__(246),
	},
	"sys_llistxattr": {
		X64:  idptr__(195),
		X32:  nil,
		IA32: idptr__(233),
	},
	"sys_socketcall": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(102),
	},
	"sys_setuid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(213),
	},
	"sys_sched_rr_get_interval_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(423),
	},
	"sys_setreuid": {
		X64:  idptr__(113),
		X32:  nil,
		IA32: idptr__(70),
	},
	"sys_clock_gettime": {
		X64:  idptr__(228),
		X32:  nil,
		IA32: idptr__(265),
	},
	"sys_inotify_rm_watch": {
		X64:  idptr__(255),
		X32:  nil,
		IA32: idptr__(293),
	},
	"sys_lsetxattr": {
		X64:  idptr__(189),
		X32:  nil,
		IA32: idptr__(227),
	},
	"sys_fchown": {
		X64:  idptr__(93),
		X32:  nil,
		IA32: idptr__(95),
	},
	"sys_ftime": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(35),
	},
	"sys_fcntl64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(221),
	},
	"sys_clone": {
		X64:  idptr__(56),
		X32:  nil,
		IA32: idptr__(120),
	},
	"sys_getxattr": {
		X64:  idptr__(191),
		X32:  nil,
		IA32: idptr__(229),
	},
	"sys_ugetrlimit": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(191),
	},
	"sys_geteuid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(201),
	},
	"sys_rt_sigprocmask": {
		X64:  idptr__(14),
		X32:  nil,
		IA32: idptr__(175),
	},
	"sys_mprotect": {
		X64:  idptr__(10),
		X32:  nil,
		IA32: idptr__(125),
	},
	"sys_setsockopt": {
		X64:  idptr__(54),
		X32:  idptr__(541),
		IA32: idptr__(366),
	},
	"sys_create_module": {
		X64:  idptr__(174),
		X32:  nil,
		IA32: idptr__(127),
	},
	"sys_mq_timedreceive": {
		X64:  idptr__(243),
		X32:  nil,
		IA32: idptr__(280),
	},
	"sys_mmap2": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(192),
	},
	"sys_close": {
		X64:  idptr__(3),
		X32:  nil,
		IA32: idptr__(6),
	},
	"sys_writev": {
		X64:  idptr__(20),
		X32:  idptr__(516),
		IA32: idptr__(146),
	},
	"sys_setresuid": {
		X64:  idptr__(117),
		X32:  nil,
		IA32: idptr__(164),
	},
	"sys_sync": {
		X64:  idptr__(162),
		X32:  nil,
		IA32: idptr__(36),
	},
	"sys_unshare": {
		X64:  idptr__(272),
		X32:  nil,
		IA32: idptr__(310),
	},
	"sys_exit": {
		X64:  idptr__(60),
		X32:  nil,
		IA32: idptr__(1),
	},
	"sys_io_uring_register": {
		X64:  idptr__(427),
		X32:  nil,
		IA32: idptr__(427),
	},
	"sys_ftruncate": {
		X64:  idptr__(77),
		X32:  nil,
		IA32: idptr__(93),
	},
	"sys_times": {
		X64:  idptr__(100),
		X32:  nil,
		IA32: idptr__(43),
	},
	"sys_quotactl": {
		X64:  idptr__(179),
		X32:  nil,
		IA32: idptr__(131),
	},
	"sys_getrandom": {
		X64:  idptr__(318),
		X32:  nil,
		IA32: idptr__(355),
	},
	"sys_timer_settime64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(409),
	},
	"sys_mmap": {
		X64:  idptr__(9),
		X32:  nil,
		IA32: idptr__(90),
	},
	"sys_chdir": {
		X64:  idptr__(80),
		X32:  nil,
		IA32: idptr__(12),
	},
	"sys_rt_sigsuspend": {
		X64:  idptr__(130),
		X32:  nil,
		IA32: idptr__(179),
	},
	"sys_faccessat": {
		X64:  idptr__(269),
		X32:  nil,
		IA32: idptr__(307),
	},
	"sys_semget": {
		X64:  idptr__(64),
		X32:  nil,
		IA32: idptr__(393),
	},
	"sys_ioperm": {
		X64:  idptr__(173),
		X32:  nil,
		IA32: idptr__(101),
	},
	"sys_get_kernel_syms": {
		X64:  idptr__(177),
		X32:  nil,
		IA32: idptr__(130),
	},
	"sys_tgkill": {
		X64:  idptr__(234),
		X32:  nil,
		IA32: idptr__(270),
	},
	"sys_kexec_file_load": {
		X64:  idptr__(320),
		X32:  nil,
		IA32: nil,
	},
	"sys_poll": {
		X64:  idptr__(7),
		X32:  nil,
		IA32: idptr__(168),
	},
	"sys_arch_prctl": {
		X64:  idptr__(158),
		X32:  nil,
		IA32: idptr__(384),
	},
	"sys_pread64": {
		X64:  idptr__(17),
		X32:  nil,
		IA32: idptr__(180),
	},
	"sys_accept4": {
		X64:  idptr__(288),
		X32:  nil,
		IA32: idptr__(364),
	},
	"sys_vm86old": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(113),
	},
	"sys_capget": {
		X64:  idptr__(125),
		X32:  nil,
		IA32: idptr__(184),
	},
	"sys_afs_syscall": {
		X64:  idptr__(183),
		X32:  nil,
		IA32: idptr__(137),
	},
	"sys_mq_timedsend": {
		X64:  idptr__(242),
		X32:  nil,
		IA32: idptr__(279),
	},
	"sys_waitpid": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(7),
	},
	"sys_rename": {
		X64:  idptr__(82),
		X32:  nil,
		IA32: idptr__(38),
	},
	"sys_sethostname": {
		X64:  idptr__(170),
		X32:  nil,
		IA32: idptr__(74),
	},
	"sys_query_module": {
		X64:  idptr__(178),
		X32:  nil,
		IA32: idptr__(167),
	},
	"sys_gettimeofday": {
		X64:  idptr__(96),
		X32:  nil,
		IA32: idptr__(78),
	},
	"sys_getgroups": {
		X64:  idptr__(115),
		X32:  nil,
		IA32: idptr__(80),
	},
	"sys_getresuid": {
		X64:  idptr__(118),
		X32:  nil,
		IA32: idptr__(165),
	},
	"sys_getcpu": {
		X64:  idptr__(309),
		X32:  nil,
		IA32: idptr__(318),
	},
	"sys_copy_file_range": {
		X64:  idptr__(326),
		X32:  nil,
		IA32: idptr__(377),
	},
	"sys_landlock_add_rule": {
		X64:  idptr__(445),
		X32:  nil,
		IA32: idptr__(445),
	},
	"sys_process_mrelease": {
		X64:  idptr__(448),
		X32:  nil,
		IA32: idptr__(448),
	},
	"sys_ppoll_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(414),
	},
	"sys_fork": {
		X64:  idptr__(57),
		X32:  nil,
		IA32: idptr__(2),
	},
	"sys_oldstat": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(18),
	},
	"sys_getcwd": {
		X64:  idptr__(79),
		X32:  nil,
		IA32: idptr__(183),
	},
	"sys_process_vm_writev": {
		X64:  idptr__(311),
		X32:  idptr__(540),
		IA32: idptr__(348),
	},
	"sys_fstat": {
		X64:  idptr__(5),
		X32:  nil,
		IA32: idptr__(108),
	},
	"sys_setsid": {
		X64:  idptr__(112),
		X32:  nil,
		IA32: idptr__(66),
	},
	"sys_tuxcall": {
		X64:  idptr__(184),
		X32:  nil,
		IA32: nil,
	},
	"sys_listmount": {
		X64:  idptr__(458),
		X32:  nil,
		IA32: idptr__(458),
	},
	"sys_ptrace": {
		X64:  idptr__(101),
		X32:  idptr__(521),
		IA32: idptr__(26),
	},
	"sys_tkill": {
		X64:  idptr__(200),
		X32:  nil,
		IA32: idptr__(238),
	},
	"sys_nfsservctl": {
		X64:  idptr__(180),
		X32:  nil,
		IA32: idptr__(169),
	},
	"sys_statfs": {
		X64:  idptr__(137),
		X32:  nil,
		IA32: idptr__(99),
	},
	"sys_personality": {
		X64:  idptr__(135),
		X32:  nil,
		IA32: idptr__(136),
	},
	"sys_adjtimex": {
		X64:  idptr__(159),
		X32:  nil,
		IA32: idptr__(124),
	},
	"sys_set_thread_area": {
		X64:  idptr__(205),
		X32:  nil,
		IA32: idptr__(243),
	},
	"sys_io_cancel": {
		X64:  idptr__(210),
		X32:  nil,
		IA32: idptr__(249),
	},
	"sys_flock": {
		X64:  idptr__(73),
		X32:  nil,
		IA32: idptr__(143),
	},
	"sys_umount2": {
		X64:  idptr__(166),
		X32:  nil,
		IA32: idptr__(52),
	},
	"sys_fsconfig": {
		X64:  idptr__(431),
		X32:  nil,
		IA32: idptr__(431),
	},
	"sys_sgetmask": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(68),
	},
	"sys_futex_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(422),
	},
	"sys__sysctl": {
		X64:  idptr__(156),
		X32:  nil,
		IA32: idptr__(149),
	},
	"sys_epoll_pwait": {
		X64:  idptr__(281),
		X32:  nil,
		IA32: idptr__(319),
	},
	"sys_open_by_handle_at": {
		X64:  idptr__(304),
		X32:  nil,
		IA32: idptr__(342),
	},
	"sys_sched_setattr": {
		X64:  idptr__(314),
		X32:  nil,
		IA32: idptr__(351),
	},
	"sys_open_tree": {
		X64:  idptr__(428),
		X32:  nil,
		IA32: idptr__(428),
	},
	"sys_getdents64": {
		X64:  idptr__(217),
		X32:  nil,
		IA32: idptr__(220),
	},
	"sys_mkdir": {
		X64:  idptr__(83),
		X32:  nil,
		IA32: idptr__(39),
	},
	"sys_getgid": {
		X64:  idptr__(104),
		X32:  nil,
		IA32: idptr__(47),
	},
	"sys_openat2": {
		X64:  idptr__(437),
		X32:  nil,
		IA32: idptr__(437),
	},
	"sys_set_mempolicy_home_node": {
		X64:  idptr__(450),
		X32:  nil,
		IA32: idptr__(450),
	},
	"sys_fsync": {
		X64:  idptr__(74),
		X32:  nil,
		IA32: idptr__(118),
	},
	"sys_pkey_alloc": {
		X64:  idptr__(330),
		X32:  nil,
		IA32: idptr__(381),
	},
	"sys_landlock_restrict_self": {
		X64:  idptr__(446),
		X32:  nil,
		IA32: idptr__(446),
	},
	"sys_lsm_get_self_attr": {
		X64:  idptr__(459),
		X32:  nil,
		IA32: idptr__(459),
	},
	"sys_ipc": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(117),
	},
	"sys_renameat": {
		X64:  idptr__(264),
		X32:  nil,
		IA32: idptr__(302),
	},
	"sys_utimensat": {
		X64:  idptr__(280),
		X32:  nil,
		IA32: idptr__(320),
	},
	"sys_fanotify_init": {
		X64:  idptr__(300),
		X32:  nil,
		IA32: idptr__(338),
	},
	"sys_chown32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(212),
	},
	"sys_modify_ldt": {
		X64:  idptr__(154),
		X32:  nil,
		IA32: idptr__(123),
	},
	"sys_sched_get_priority_min": {
		X64:  idptr__(147),
		X32:  nil,
		IA32: idptr__(160),
	},
	"sys_timer_gettime": {
		X64:  idptr__(224),
		X32:  nil,
		IA32: idptr__(261),
	},
	"sys_msgget": {
		X64:  idptr__(68),
		X32:  nil,
		IA32: idptr__(399),
	},
	"sys_idle": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(112),
	},
	"sys_readahead": {
		X64:  idptr__(187),
		X32:  nil,
		IA32: idptr__(225),
	},
	"sys_setfsgid": {
		X64:  idptr__(123),
		X32:  nil,
		IA32: idptr__(139),
	},
	"sys_getsid": {
		X64:  idptr__(124),
		X32:  nil,
		IA32: idptr__(147),
	},
	"sys_signal": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(48),
	},
	"sys_truncate64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(193),
	},
	"sys_recvfrom": {
		X64:  idptr__(45),
		X32:  idptr__(517),
		IA32: idptr__(371),
	},
	"sys_eventfd2": {
		X64:  idptr__(290),
		X32:  nil,
		IA32: idptr__(328),
	},
	"sys_move_mount": {
		X64:  idptr__(429),
		X32:  nil,
		IA32: idptr__(429),
	},
	"sys_epoll_pwait2": {
		X64:  idptr__(441),
		X32:  nil,
		IA32: idptr__(441),
	},
	"sys_mount_setattr": {
		X64:  idptr__(442),
		X32:  nil,
		IA32: idptr__(442),
	},
	"sys_ssetmask": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(69),
	},
	"sys_setfsgid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(216),
	},
	"sys_timerfd_create": {
		X64:  idptr__(283),
		X32:  nil,
		IA32: idptr__(322),
	},
	"sys_clock_nanosleep": {
		X64:  idptr__(230),
		X32:  nil,
		IA32: idptr__(267),
	},
	"sys_mkdirat": {
		X64:  idptr__(258),
		X32:  nil,
		IA32: idptr__(296),
	},
	"sys_finit_module": {
		X64:  idptr__(313),
		X32:  nil,
		IA32: idptr__(350),
	},
	"sys_fsmount": {
		X64:  idptr__(432),
		X32:  nil,
		IA32: idptr__(432),
	},
	"sys_cachestat": {
		X64:  idptr__(451),
		X32:  nil,
		IA32: idptr__(451),
	},
	"sys_vfork": {
		X64:  idptr__(58),
		X32:  nil,
		IA32: idptr__(190),
	},
	"sys_sendfile": {
		X64:  idptr__(40),
		X32:  nil,
		IA32: idptr__(187),
	},
	"sys_msgsnd": {
		X64:  idptr__(69),
		X32:  nil,
		IA32: idptr__(400),
	},
	"sys_sendfile64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(239),
	},
	"sys_pause": {
		X64:  idptr__(34),
		X32:  nil,
		IA32: idptr__(29),
	},
	"sys_stty": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(31),
	},
	"sys_timerfd_settime64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(411),
	},
	"sys_shutdown": {
		X64:  idptr__(48),
		X32:  nil,
		IA32: idptr__(373),
	},
	"sys_request_key": {
		X64:  idptr__(249),
		X32:  nil,
		IA32: idptr__(287),
	},
	"sys_chown": {
		X64:  idptr__(92),
		X32:  nil,
		IA32: idptr__(182),
	},
	"sys_pkey_mprotect": {
		X64:  idptr__(329),
		X32:  nil,
		IA32: idptr__(380),
	},
	"sys_vm86": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(166),
	},
	"sys_utimensat_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(412),
	},
	"sys_recvmmsg_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(417),
	},
	"sys_reboot": {
		X64:  idptr__(169),
		X32:  nil,
		IA32: idptr__(88),
	},
	"sys_getrusage": {
		X64:  idptr__(98),
		X32:  nil,
		IA32: idptr__(77),
	},
	"sys_eventfd": {
		X64:  idptr__(284),
		X32:  nil,
		IA32: idptr__(323),
	},
	"sys_stat64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(195),
	},
	"sys_wait4": {
		X64:  idptr__(61),
		X32:  nil,
		IA32: idptr__(114),
	},
	"sys_ustat": {
		X64:  idptr__(136),
		X32:  nil,
		IA32: idptr__(62),
	},
	"sys_epoll_create": {
		X64:  idptr__(213),
		X32:  nil,
		IA32: idptr__(254),
	},
	"sys_timer_getoverrun": {
		X64:  idptr__(225),
		X32:  nil,
		IA32: idptr__(262),
	},
	"sys_setns": {
		X64:  idptr__(308),
		X32:  nil,
		IA32: idptr__(346),
	},
	"sys_pkey_free": {
		X64:  idptr__(331),
		X32:  nil,
		IA32: idptr__(382),
	},
	"sys_nanosleep": {
		X64:  idptr__(35),
		X32:  nil,
		IA32: idptr__(162),
	},
	"sys_recvmmsg": {
		X64:  idptr__(299),
		X32:  idptr__(537),
		IA32: idptr__(337),
	},
	"sys_setgid": {
		X64:  idptr__(106),
		X32:  nil,
		IA32: idptr__(46),
	},
	"sys_creat": {
		X64:  idptr__(85),
		X32:  nil,
		IA32: idptr__(8),
	},
	"sys_settimeofday": {
		X64:  idptr__(164),
		X32:  nil,
		IA32: idptr__(79),
	},
	"sys_linkat": {
		X64:  idptr__(265),
		X32:  nil,
		IA32: idptr__(303),
	},
	"sys_ppoll": {
		X64:  idptr__(271),
		X32:  nil,
		IA32: idptr__(309),
	},
	"sys_inotify_init1": {
		X64:  idptr__(294),
		X32:  nil,
		IA32: idptr__(332),
	},
	"sys_alarm": {
		X64:  idptr__(37),
		X32:  nil,
		IA32: idptr__(27),
	},
	"sys_fsetxattr": {
		X64:  idptr__(190),
		X32:  nil,
		IA32: idptr__(228),
	},
	"sys_lookup_dcookie": {
		X64:  idptr__(212),
		X32:  nil,
		IA32: idptr__(253),
	},
	"sys_semtimedop": {
		X64:  idptr__(220),
		X32:  nil,
		IA32: nil,
	},
	"sys_newfstatat": {
		X64:  idptr__(262),
		X32:  nil,
		IA32: nil,
	},
	"sys_timerfd_gettime": {
		X64:  idptr__(287),
		X32:  nil,
		IA32: idptr__(326),
	},
	"sys_getpgrp": {
		X64:  idptr__(111),
		X32:  nil,
		IA32: idptr__(65),
	},
	"sys_timer_create": {
		X64:  idptr__(222),
		X32:  idptr__(526),
		IA32: idptr__(259),
	},
	"sys_preadv2": {
		X64:  idptr__(327),
		X32:  idptr__(546),
		IA32: idptr__(378),
	},
	"sys_getitimer": {
		X64:  idptr__(36),
		X32:  nil,
		IA32: idptr__(105),
	},
	"sys_getuid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(199),
	},
	"sys_getresuid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(209),
	},
	"sys_fchownat": {
		X64:  idptr__(260),
		X32:  nil,
		IA32: idptr__(298),
	},
	"sys_umask": {
		X64:  idptr__(95),
		X32:  nil,
		IA32: idptr__(60),
	},
	"sys_capset": {
		X64:  idptr__(126),
		X32:  nil,
		IA32: idptr__(185),
	},
	"sys_exit_group": {
		X64:  idptr__(231),
		X32:  nil,
		IA32: idptr__(252),
	},
	"sys_renameat2": {
		X64:  idptr__(316),
		X32:  nil,
		IA32: idptr__(353),
	},
	"sys_clone3": {
		X64:  idptr__(435),
		X32:  nil,
		IA32: idptr__(435),
	},
	"sys__llseek": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(140),
	},
	"sys_setfsuid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(215),
	},
	"sys_uname": {
		X64:  idptr__(63),
		X32:  nil,
		IA32: idptr__(122),
	},
	"sys_pipe2": {
		X64:  idptr__(293),
		X32:  nil,
		IA32: idptr__(331),
	},
	"sys_kcmp": {
		X64:  idptr__(312),
		X32:  nil,
		IA32: idptr__(349),
	},
	"sys_readlinkat": {
		X64:  idptr__(267),
		X32:  nil,
		IA32: idptr__(305),
	},
	"sys_fstatfs": {
		X64:  idptr__(138),
		X32:  nil,
		IA32: idptr__(100),
	},
	"sys_munlock": {
		X64:  idptr__(150),
		X32:  nil,
		IA32: idptr__(151),
	},
	"sys_io_pgetevents": {
		X64:  idptr__(333),
		X32:  nil,
		IA32: idptr__(385),
	},
	"sys_getegid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(202),
	},
	"sys_munmap": {
		X64:  idptr__(11),
		X32:  nil,
		IA32: idptr__(91),
	},
	"sys_fchmodat": {
		X64:  idptr__(268),
		X32:  nil,
		IA32: idptr__(306),
	},
	"sys_statx": {
		X64:  idptr__(332),
		X32:  nil,
		IA32: idptr__(383),
	},
	"sys_lgetxattr": {
		X64:  idptr__(192),
		X32:  nil,
		IA32: idptr__(230),
	},
	"sys_mseal": {
		X64:  idptr__(462),
		X32:  nil,
		IA32: idptr__(462),
	},
	"sys_oldfstat": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(28),
	},
	"sys_fadvise64": {
		X64:  idptr__(221),
		X32:  nil,
		IA32: idptr__(250),
	},
	"sys_rt_sigpending": {
		X64:  idptr__(127),
		X32:  idptr__(522),
		IA32: idptr__(176),
	},
	"sys_security": {
		X64:  idptr__(185),
		X32:  nil,
		IA32: nil,
	},
	"sys_epoll_ctl_old": {
		X64:  idptr__(214),
		X32:  nil,
		IA32: nil,
	},
	"sys_mincore": {
		X64:  idptr__(27),
		X32:  nil,
		IA32: idptr__(218),
	},
	"sys_timerfd_gettime64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(410),
	},
	"sys_clock_adjtime": {
		X64:  idptr__(305),
		X32:  nil,
		IA32: idptr__(343),
	},
	"sys_mknod": {
		X64:  idptr__(133),
		X32:  nil,
		IA32: idptr__(14),
	},
	"sys_set_mempolicy": {
		X64:  idptr__(238),
		X32:  nil,
		IA32: idptr__(276),
	},
	"sys_fchmodat2": {
		X64:  idptr__(452),
		X32:  nil,
		IA32: idptr__(452),
	},
	"sys_sigreturn": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(119),
	},
	"sys_getdents": {
		X64:  idptr__(78),
		X32:  nil,
		IA32: idptr__(141),
	},
	"sys_fanotify_mark": {
		X64:  idptr__(301),
		X32:  nil,
		IA32: idptr__(339),
	},
	"sys_process_vm_readv": {
		X64:  idptr__(310),
		X32:  idptr__(539),
		IA32: idptr__(347),
	},
	"sys_futex_waitv": {
		X64:  idptr__(449),
		X32:  nil,
		IA32: idptr__(449),
	},
	"sys_stat": {
		X64:  idptr__(4),
		X32:  nil,
		IA32: idptr__(106),
	},
	"sys_sysfs": {
		X64:  idptr__(139),
		X32:  nil,
		IA32: idptr__(135),
	},
	"sys_chroot": {
		X64:  idptr__(161),
		X32:  nil,
		IA32: idptr__(61),
	},
	"sys_waitid": {
		X64:  idptr__(247),
		X32:  idptr__(529),
		IA32: idptr__(284),
	},
	"sys_signalfd": {
		X64:  idptr__(282),
		X32:  nil,
		IA32: idptr__(321),
	},
	"sys_getrlimit": {
		X64:  idptr__(97),
		X32:  nil,
		IA32: idptr__(76),
	},
	"sys_setfsuid": {
		X64:  idptr__(122),
		X32:  nil,
		IA32: idptr__(138),
	},
	"sys_sigaltstack": {
		X64:  idptr__(131),
		X32:  idptr__(525),
		IA32: idptr__(186),
	},
	"sys_sched_setparam": {
		X64:  idptr__(142),
		X32:  nil,
		IA32: idptr__(154),
	},
	"sys_sendmsg": {
		X64:  idptr__(46),
		X32:  idptr__(518),
		IA32: idptr__(370),
	},
	"sys_swapon": {
		X64:  idptr__(167),
		X32:  nil,
		IA32: idptr__(87),
	},
	"sys_clock_adjtime64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(405),
	},
	"sys_uselib": {
		X64:  idptr__(134),
		X32:  nil,
		IA32: idptr__(86),
	},
	"sys_setdomainname": {
		X64:  idptr__(171),
		X32:  nil,
		IA32: idptr__(121),
	},
	"sys_epoll_ctl": {
		X64:  idptr__(233),
		X32:  nil,
		IA32: idptr__(255),
	},
	"sys_acct": {
		X64:  idptr__(163),
		X32:  nil,
		IA32: idptr__(51),
	},
	"sys_sched_getaffinity": {
		X64:  idptr__(204),
		X32:  nil,
		IA32: idptr__(242),
	},
	"sys_io_uring_setup": {
		X64:  idptr__(425),
		X32:  nil,
		IA32: idptr__(425),
	},
	"sys_oldolduname": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(59),
	},
	"sys_getresgid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(211),
	},
	"sys_fadvise64_64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(272),
	},
	"sys_clock_gettime64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(403),
	},
	"sys_kill": {
		X64:  idptr__(62),
		X32:  nil,
		IA32: idptr__(37),
	},
	"sys_ftruncate64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(194),
	},
	"sys_clock_nanosleep_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(407),
	},
	"sys_close_range": {
		X64:  idptr__(436),
		X32:  nil,
		IA32: idptr__(436),
	},
	"sys_getsockname": {
		X64:  idptr__(51),
		X32:  nil,
		IA32: idptr__(367),
	},
	"sys_dup": {
		X64:  idptr__(32),
		X32:  nil,
		IA32: idptr__(41),
	},
	"sys_futimesat": {
		X64:  idptr__(261),
		X32:  nil,
		IA32: idptr__(299),
	},
	"sys_pselect6": {
		X64:  idptr__(270),
		X32:  nil,
		IA32: idptr__(308),
	},
	"sys_name_to_handle_at": {
		X64:  idptr__(303),
		X32:  nil,
		IA32: idptr__(341),
	},
	"sys_sched_getattr": {
		X64:  idptr__(315),
		X32:  nil,
		IA32: idptr__(352),
	},
	"sys_mknodat": {
		X64:  idptr__(259),
		X32:  nil,
		IA32: idptr__(297),
	},
	"sys_mlockall": {
		X64:  idptr__(151),
		X32:  nil,
		IA32: idptr__(152),
	},
	"sys_io_getevents": {
		X64:  idptr__(208),
		X32:  nil,
		IA32: idptr__(247),
	},
	"sys_prlimit64": {
		X64:  idptr__(302),
		X32:  nil,
		IA32: idptr__(340),
	},
	"sys_sigsuspend": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(72),
	},
	"sys_fchmod": {
		X64:  idptr__(91),
		X32:  nil,
		IA32: idptr__(94),
	},
	"sys_access": {
		X64:  idptr__(21),
		X32:  nil,
		IA32: idptr__(33),
	},
	"sys_epoll_wait": {
		X64:  idptr__(232),
		X32:  nil,
		IA32: idptr__(256),
	},
	"sys_kexec_load": {
		X64:  idptr__(246),
		X32:  idptr__(528),
		IA32: idptr__(283),
	},
	"sys_memfd_create": {
		X64:  idptr__(319),
		X32:  nil,
		IA32: idptr__(356),
	},
	"sys_rseq": {
		X64:  idptr__(334),
		X32:  nil,
		IA32: idptr__(386),
	},
	"sys_sigaction": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(67),
	},
	"sys_setpriority": {
		X64:  idptr__(141),
		X32:  nil,
		IA32: idptr__(97),
	},
	"sys_getresgid": {
		X64:  idptr__(120),
		X32:  nil,
		IA32: idptr__(171),
	},
	"sys_listxattr": {
		X64:  idptr__(194),
		X32:  nil,
		IA32: idptr__(232),
	},
	"sys_rt_sigreturn": {
		X64:  idptr__(15),
		X32:  idptr__(513),
		IA32: idptr__(173),
	},
	"sys_getpeername": {
		X64:  idptr__(52),
		X32:  nil,
		IA32: idptr__(368),
	},
	"sys_bpf": {
		X64:  idptr__(321),
		X32:  nil,
		IA32: idptr__(357),
	},
	"sys_olduname": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(109),
	},
	"sys_mq_timedreceive_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(419),
	},
	"sys_readv": {
		X64:  idptr__(19),
		X32:  idptr__(515),
		IA32: idptr__(145),
	},
	"sys_setgroups": {
		X64:  idptr__(116),
		X32:  nil,
		IA32: idptr__(81),
	},
	"sys_sched_getscheduler": {
		X64:  idptr__(145),
		X32:  nil,
		IA32: idptr__(157),
	},
	"sys_get_mempolicy": {
		X64:  idptr__(239),
		X32:  nil,
		IA32: idptr__(275),
	},
	"sys_mq_unlink": {
		X64:  idptr__(241),
		X32:  nil,
		IA32: idptr__(278),
	},
	"sys_rt_sigaction": {
		X64:  idptr__(13),
		X32:  idptr__(512),
		IA32: idptr__(174),
	},
	"sys_gettid": {
		X64:  idptr__(186),
		X32:  nil,
		IA32: idptr__(224),
	},
	"sys_removexattr": {
		X64:  idptr__(197),
		X32:  nil,
		IA32: idptr__(235),
	},
	"sys_clock_settime": {
		X64:  idptr__(227),
		X32:  nil,
		IA32: idptr__(264),
	},
	"sys_splice": {
		X64:  idptr__(275),
		X32:  nil,
		IA32: idptr__(313),
	},
	"sys_swapoff": {
		X64:  idptr__(168),
		X32:  nil,
		IA32: idptr__(115),
	},
	"sys_io_submit": {
		X64:  idptr__(209),
		X32:  idptr__(544),
		IA32: idptr__(248),
	},
	"sys_sync_file_range": {
		X64:  idptr__(277),
		X32:  nil,
		IA32: idptr__(314),
	},
	"sys_rt_tgsigqueueinfo": {
		X64:  idptr__(297),
		X32:  idptr__(536),
		IA32: idptr__(335),
	},
	"sys_lsm_list_modules": {
		X64:  idptr__(461),
		X32:  nil,
		IA32: idptr__(461),
	},
	"sys_pivot_root": {
		X64:  idptr__(155),
		X32:  nil,
		IA32: idptr__(217),
	},
	"sys_setitimer": {
		X64:  idptr__(38),
		X32:  nil,
		IA32: idptr__(104),
	},
	"sys_lchown": {
		X64:  idptr__(94),
		X32:  nil,
		IA32: idptr__(16),
	},
	"sys_sysinfo": {
		X64:  idptr__(99),
		X32:  nil,
		IA32: idptr__(116),
	},
	"sys_setuid": {
		X64:  idptr__(105),
		X32:  nil,
		IA32: idptr__(23),
	},
	"sys_msync": {
		X64:  idptr__(26),
		X32:  nil,
		IA32: idptr__(144),
	},
	"sys_socketpair": {
		X64:  idptr__(53),
		X32:  nil,
		IA32: idptr__(360),
	},
	"sys_rmdir": {
		X64:  idptr__(84),
		X32:  nil,
		IA32: idptr__(40),
	},
	"sys_inotify_add_watch": {
		X64:  idptr__(254),
		X32:  nil,
		IA32: idptr__(292),
	},
	"sys_pidfd_getfd": {
		X64:  idptr__(438),
		X32:  nil,
		IA32: idptr__(438),
	},
	"sys_listen": {
		X64:  idptr__(50),
		X32:  nil,
		IA32: idptr__(363),
	},
	"sys_readlink": {
		X64:  idptr__(89),
		X32:  nil,
		IA32: idptr__(85),
	},
	"sys_fdatasync": {
		X64:  idptr__(75),
		X32:  nil,
		IA32: idptr__(148),
	},
	"sys_fgetxattr": {
		X64:  idptr__(193),
		X32:  nil,
		IA32: idptr__(231),
	},
	"sys_add_key": {
		X64:  idptr__(248),
		X32:  nil,
		IA32: idptr__(286),
	},
	"sys_ioprio_set": {
		X64:  idptr__(251),
		X32:  nil,
		IA32: idptr__(289),
	},
	"sys_link": {
		X64:  idptr__(86),
		X32:  nil,
		IA32: idptr__(9),
	},
	"sys_delete_module": {
		X64:  idptr__(176),
		X32:  nil,
		IA32: idptr__(129),
	},
	"sys_perf_event_open": {
		X64:  idptr__(298),
		X32:  nil,
		IA32: idptr__(336),
	},
	"sys_connect": {
		X64:  idptr__(42),
		X32:  nil,
		IA32: idptr__(362),
	},
	"sys_sched_setscheduler": {
		X64:  idptr__(144),
		X32:  nil,
		IA32: idptr__(156),
	},
	"sys_read": {
		X64:  idptr__(0),
		X32:  nil,
		IA32: idptr__(3),
	},
	"sys_futex": {
		X64:  idptr__(202),
		X32:  nil,
		IA32: idptr__(240),
	},
	"sys_futex_wait": {
		X64:  idptr__(455),
		X32:  nil,
		IA32: idptr__(455),
	},
	"sys_readdir": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(89),
	},
	"sys_lchown32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(198),
	},
	"sys_shmget": {
		X64:  idptr__(29),
		X32:  nil,
		IA32: idptr__(395),
	},
	"sys_seccomp": {
		X64:  idptr__(317),
		X32:  nil,
		IA32: idptr__(354),
	},
	"sys_membarrier": {
		X64:  idptr__(324),
		X32:  nil,
		IA32: idptr__(375),
	},
	"sys_mbind": {
		X64:  idptr__(237),
		X32:  nil,
		IA32: idptr__(274),
	},
	"sys_set_tid_address": {
		X64:  idptr__(218),
		X32:  nil,
		IA32: idptr__(258),
	},
	"sys_msgctl": {
		X64:  idptr__(71),
		X32:  nil,
		IA32: idptr__(402),
	},
	"sys_get_thread_area": {
		X64:  idptr__(211),
		X32:  nil,
		IA32: idptr__(244),
	},
	"sys_fallocate": {
		X64:  idptr__(285),
		X32:  nil,
		IA32: idptr__(324),
	},
	"sys_timer_gettime64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(408),
	},
	"sys_setregid": {
		X64:  idptr__(114),
		X32:  nil,
		IA32: idptr__(71),
	},
	"sys_sendto": {
		X64:  idptr__(44),
		X32:  nil,
		IA32: idptr__(369),
	},
	"sys_truncate": {
		X64:  idptr__(76),
		X32:  nil,
		IA32: idptr__(92),
	},
	"sys_userfaultfd": {
		X64:  idptr__(323),
		X32:  nil,
		IA32: idptr__(374),
	},
	"sys_pwritev2": {
		X64:  idptr__(328),
		X32:  idptr__(547),
		IA32: idptr__(379),
	},
	"sys_brk": {
		X64:  idptr__(12),
		X32:  nil,
		IA32: idptr__(45),
	},
	"sys_socket": {
		X64:  idptr__(41),
		X32:  nil,
		IA32: idptr__(359),
	},
	"sys_clock_settime64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(404),
	},
	"sys_clock_getres_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(406),
	},
	"sys_shmctl": {
		X64:  idptr__(31),
		X32:  nil,
		IA32: idptr__(396),
	},
	"sys_rt_sigqueueinfo": {
		X64:  idptr__(129),
		X32:  idptr__(524),
		IA32: idptr__(178),
	},
	"sys_rt_sigtimedwait_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(421),
	},
	"sys_getegid": {
		X64:  idptr__(108),
		X32:  nil,
		IA32: idptr__(50),
	},
	"sys_rt_sigtimedwait": {
		X64:  idptr__(128),
		X32:  idptr__(523),
		IA32: idptr__(177),
	},
	"sys_umount": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(22),
	},
	"sys_mremap": {
		X64:  idptr__(25),
		X32:  nil,
		IA32: idptr__(163),
	},
	"sys_mq_open": {
		X64:  idptr__(240),
		X32:  nil,
		IA32: idptr__(277),
	},
	"sys_signalfd4": {
		X64:  idptr__(289),
		X32:  nil,
		IA32: idptr__(327),
	},
	"sys_io_uring_enter": {
		X64:  idptr__(426),
		X32:  nil,
		IA32: idptr__(426),
	},
	"sys_io_pgetevents_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(416),
	},
	"sys_open": {
		X64:  idptr__(2),
		X32:  nil,
		IA32: idptr__(5),
	},
	"sys_epoll_wait_old": {
		X64:  idptr__(215),
		X32:  nil,
		IA32: nil,
	},
	"sys_ioprio_get": {
		X64:  idptr__(252),
		X32:  nil,
		IA32: idptr__(290),
	},
	"sys_semtimedop_time64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(420),
	},
	"sys_getpmsg": {
		X64:  idptr__(181),
		X32:  nil,
		IA32: idptr__(188),
	},
	"sys_openat": {
		X64:  idptr__(257),
		X32:  nil,
		IA32: idptr__(295),
	},
	"sys_unlinkat": {
		X64:  idptr__(263),
		X32:  nil,
		IA32: idptr__(301),
	},
	"sys_setreuid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(203),
	},
	"sys_setregid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(204),
	},
	"sys_execve": {
		X64:  idptr__(59),
		X32:  idptr__(520),
		IA32: idptr__(11),
	},
	"sys_migrate_pages": {
		X64:  idptr__(256),
		X32:  nil,
		IA32: idptr__(294),
	},
	"sys_select": {
		X64:  idptr__(23),
		X32:  nil,
		IA32: idptr__(82),
	},
	"sys_getsockopt": {
		X64:  idptr__(55),
		X32:  idptr__(542),
		IA32: idptr__(365),
	},
	"sys_geteuid": {
		X64:  idptr__(107),
		X32:  nil,
		IA32: idptr__(49),
	},
	"sys_init_module": {
		X64:  idptr__(175),
		X32:  nil,
		IA32: idptr__(128),
	},
	"sys_landlock_create_ruleset": {
		X64:  idptr__(444),
		X32:  nil,
		IA32: idptr__(444),
	},
	"sys_memfd_secret": {
		X64:  idptr__(447),
		X32:  nil,
		IA32: idptr__(447),
	},
	"sys_lock": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(53),
	},
	"sys_write": {
		X64:  idptr__(1),
		X32:  nil,
		IA32: idptr__(4),
	},
	"sys_epoll_create1": {
		X64:  idptr__(291),
		X32:  nil,
		IA32: idptr__(329),
	},
	"sys_fstatat64": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(300),
	},
	"sys_get_robust_list": {
		X64:  idptr__(274),
		X32:  idptr__(531),
		IA32: idptr__(312),
	},
	"sys_process_madvise": {
		X64:  idptr__(440),
		X32:  nil,
		IA32: idptr__(440),
	},
	"sys_utimes": {
		X64:  idptr__(235),
		X32:  nil,
		IA32: idptr__(271),
	},
	"sys_sched_yield": {
		X64:  idptr__(24),
		X32:  nil,
		IA32: idptr__(158),
	},
	"sys_getpid": {
		X64:  idptr__(39),
		X32:  nil,
		IA32: idptr__(20),
	},
	"sys_msgrcv": {
		X64:  idptr__(70),
		X32:  nil,
		IA32: idptr__(401),
	},
	"sys_pwrite64": {
		X64:  idptr__(18),
		X32:  nil,
		IA32: idptr__(181),
	},
	"sys_sched_getparam": {
		X64:  idptr__(143),
		X32:  nil,
		IA32: idptr__(155),
	},
	"sys_vserver": {
		X64:  idptr__(236),
		X32:  nil,
		IA32: idptr__(273),
	},
	"sys_fsopen": {
		X64:  idptr__(430),
		X32:  nil,
		IA32: idptr__(430),
	},
	"sys_setresuid32": {
		X64:  nil,
		X32:  nil,
		IA32: idptr__(208),
	},
	"sys_pipe": {
		X64:  idptr__(22),
		X32:  nil,
		IA32: idptr__(42),
	},
}
