apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- with .Values.daemonSetAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- with .Values.daemonSetLabelsOverride}}
    {{- toYaml . | nindent 4 }}
  {{- else }}
    {{- include "hubble-enterprise.labels" . | nindent 4 }}
  {{- end }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
    {{- with .Values.selectorLabelsOverride }}
      {{- toYaml . | nindent 6 }}
    {{- else }}
      {{- include "hubble-enterprise.selectorLabels" . | nindent 6 }}
    {{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
      {{- with .Values.podLabelsOverride }}
        {{- toYaml . | nindent 8 }}
      {{- else }}
        {{- include "hubble-enterprise.labels" . | nindent 8 }}
      {{- end }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Chart.Name }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- if .Values.enterprise.enabled }}
      initContainers:
      {{- include "container.enterprise.init-operator" . | nindent 6 -}}
{{- if not .Values.enterprise.btf }}
      {{- include "container.enterprise.init" . | nindent 6 -}}
{{- end }}
{{- end }}
      containers:
{{- if eq .Values.export.mode "stdout" }}
      {{- include "container.export.stdout" . | nindent 6 -}}
{{- else if eq .Values.export.mode "fluentd" }}
      {{- include "container.export.fluentd" . | nindent 6 -}}
{{- else if eq .Values.export.mode "s3" }}
      {{- include "container.export.s3" . | nindent 6 -}}
{{- end }}
{{- if and (not (eq .Values.export.mode "stdout")) (.Values.export.enableStdout) }}
      {{- include "container.export.stdout" . | nindent 6 -}}
{{- end }}
{{- if .Values.enterprise.enabled }}
      {{- include "container.enterprise" . | nindent 6 -}}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      terminationGracePeriodSeconds: 1
      volumes:
      - name: cilium-run
        hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
      - name: export-logs
        hostPath:
          path: {{ .Values.exportDirectory }}
          type: DirectoryOrCreate
{{- if .Values.enterprise.enabled }}
      - name: fgs-config
        configMap:
          name: {{ .Chart.Name }}-config
      - name: bpf-maps
        hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
      - name: host-proc
        hostPath:
          path: /proc
          type: Directory
{{- if not .Values.enterprise.btf }}
      - emptyDir: {}
        name: metadata-files
{{- end }}
{{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- if eq .Values.export.mode "fluentd" }}
      {{- include "container.export.fluentd.volumes" . | nindent 6 -}}
{{- end }}
{{- range .Values.extraHostPathMounts }}
      - name: {{ .name }}
        hostPath:
          path: {{ .mountPath }}
{{- end }}
{{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
{{- end }}
