{{ if eq .Values.export.mode "s3"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{- include "container.export.s3.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "tetragon-enterprise.labels" . | nindent 4 }}
type: Opaque
data:
  aws-region: {{ required "missing export.s3.awsRegion" .Values.export.s3.awsRegion | b64enc | quote }}
{{- if and .Values.export.s3.awsSecretAccessKey .Values.export.s3.awsAccessKeyId }}
  aws-access-key-id: {{ .Values.export.s3.awsAccessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.export.s3.awsSecretAccessKey | b64enc | quote }}
{{- end }}
{{- end }}
