apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "hubble-enterprise.labels" . | nindent 4 }}
data:
{{- if .Values.enterprise.btf }}
  btf: {{ .Values.enterprise.btf }}
{{- end }}
  procfs: /procRoot
  tlstc: {{ .Values.enterprise.enableTLSEvents | quote }}
  enable-process-cred: {{ .Values.enterprise.enableProcessCred | quote }}
  enable-process-ns: {{ .Values.enterprise.enableProcessNs | quote }}
  fim-runtime-endpoint: {{ .Values.enterprise.fimRuntimeEndpoint | quote }}
  process-cache-size: {{ .Values.enterprise.processCacheSize | quote }}
{{- if .Values.enterprise.exportFilename }}
  export-filename: {{ .Values.exportDirectory}}/{{ .Values.enterprise.exportFilename }}
  export-file-max-size-mb: {{ .Values.enterprise.exportFileMaxSizeMB | quote }}
  export-file-max-backups: {{ .Values.enterprise.exportFileMaxBackups | quote }}
  export-file-compress: {{ .Values.enterprise.exportFileCompress | quote }}
  export-allowlist: |-
{{- .Values.enterprise.exportAllowList | trim | nindent 4 }}
  export-denylist: |-
{{- .Values.enterprise.exportDenyList | trim | nindent 4 }}
  field-filters: |-
{{- .Values.enterprise.fieldFilters | trim | nindent 4 }}
{{- if eq .Values.export.mode "s3"}}
  export-file-rotation-interval: {{ .Values.exportFileCreationInterval | default "15s" }}
{{- end }}
  export-rate-limit: {{ .Values.enterprise.exportRateLimit | quote }}
{{- end }}
{{- if .Values.enterprise.enableK8sAPI }}
  enable-k8s-api: "true"
{{- end }}
{{- if .Values.enterprise.enableCiliumAPI }}
  enable-cilium-api: "true"
  cilium-bpf: /sys/fs/bpf/tc/globals/
{{- end }}
{{- if .Values.enterprise.prometheus.enabled }}
  metrics-server: {{ .Values.enterprise.prometheus.address }}:{{ .Values.enterprise.prometheus.port }}
{{- else }}
  metrics-server: ""
{{- end }}
{{- if .Values.enterprise.grpc.enabled }}
  server-address: {{ .Values.enterprise.grpc.address }}
{{- else }}
  server-address: ""
{{- end }}
{{- if .Values.enterprise.tcpStatsSampleSegs }}
  tcp-stats-sample-segs: {{ .Values.enterprise.tcpStatsSampleSegs | quote }}
{{- end }}
  gops-address: {{ .Values.enterprise.gops.address }}:{{ .Values.enterprise.gops.port }}
{{- if .Values.enterprise.enablePolicyFilter }}
  enable-policy-filter: "true"
{{- end }}
{{- if .Values.enterprise.enablePolicyFilterDebug }}
  enable-policy-filter-debug: "true"
{{- end }}
