{{/* validate hubble config */}}
{{- if and .Values.rbac.enabled .Values.rbac.observerProxy.tlsDisabled (ne .Values.rbac.observerProxy.authMode "none") }}
{{ fail "TLS cannot be disabled for Hubble RBAC when an authentication method is configured. Please either enable TLS (set .Values.rbac.observerProxy.tlsDisabled to false), disable Hubble RBAC (set .Values.rbac.enabled to false), or configure Hubble RBAC as an unauthenticated proxy for the Observer gRPC API (set .Values.rbac.observerProxy.authMode to none)" }}
{{- end }}
{{- if and .Values.rbac.enabled (eq .Values.rbac.observerProxy.authMode "none")  }}
{{ fail "RBAC was enabled, but observerProxy.authMode was set to none. Please set observerProxy.authMode to oidc or disable RBAC." }}
{{- end }}
{{- if and .Values.rbac.enabled (not .Values.rbac.observerProxy.oidcURL) }}
{{ fail "RBAC was enabled, but observerProxy.oidcURL was left empty. Please configure observerProxy.oidcURL." }}
{{- end }}
{{- if and .Values.rbac.enabled (not .Values.rbac.observerProxy.oidcClientID) }}
{{ fail "RBAC was enabled, but observerProxy.oidcClientID was left empty. Please configure observerProxy.oidcClientID." }}
{{- end }}
{{- if and .Values.rbac.enabled (not .Values.rbac.observerProxy.jwtScopeField) }}
{{ fail "RBAC was enabled, but observerProxy.jwtScopeField was left empty. Please configure observerProxy.jwtScopeField." }}
{{- end }}

{{- if and .Values.rbac.enabled .Values.rbac.metricsProxy.tlsDisabled (ne .Values.rbac.metricsProxy.authMode "none") }}
{{ fail "TLS cannot be disabled for Hubble RBAC when an authentication method is configured. Please either enable TLS (set .Values.rbac.metricsProxy.tlsDisabled to false), disable Hubble RBAC (set .Values.rbac.enabled to false), or configure Hubble RBAC as an unauthenticated proxy for the metrics endpoint (set .Values.rbac.metricsProxy.authMode to none)" }}
{{- end }}
{{- if and .Values.rbac.enabled (and (eq .Values.rbac.metricsProxy.authMode "oidc") (not .Values.rbac.metricsProxy.oidcURL)) }}
{{ fail "RBAC was enabled, but metricsProxy.oidcURL was left empty while metricsProxy.authMod was set to oidc. Please configure metricsProxy.oidcURL." }}
{{- end }}
{{- if and .Values.rbac.enabled (and (eq .Values.rbac.metricsProxy.authMode "oidc") (not .Values.rbac.metricsProxy.oidcClientID)) }}
{{ fail "RBAC was enabled, but metricsProxy.oidcClientID was left empty while metricsProxy.authMod was set to oidc. Please configure metricsProxy.oidcClientID." }}
{{- end }}
{{- if and .Values.rbac.enabled (and (eq .Values.rbac.metricsProxy.authMode "oidc") (not .Values.rbac.metricsProxy.jwtScopeField)) }}
{{ fail "RBAC was enabled, but metricsProxy.jwtScopeField was left empty while metricsProxy.authMode was set to oidc. Please configure metricsProxy.jwtScopeField." }}
{{- end }}
