{
 "title": "File Monitoring Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(tetragon_file_actions_total,namespace)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(tetragon_file_actions_total{namespace=~\"$namespace\"},workload)"
    }
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": {
     "query": "label_values(tetragon_file_actions_total{namespace=~\"$namespace\", workload=~\"$workload\"},policy)"
    }
   },
   {
    "name": "rule",
    "label": "Rule",
    "query": {
     "query": "label_values(tetragon_file_actions_total{namespace=~\"$namespace\", workload=~\"$workload\", policy=~\"$policy\"},rule)"
    }
   },
   {
    "name": "action",
    "label": "Action",
    "query": {
     "query": "label_values(tetragon_file_actions_total{namespace=~\"$namespace\", workload=~\"$workload\", policy=~\"$policy\", rule=~\"$rule\"},action)"
    }
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values(tetragon_file_actions_total{namespace=~\"$namespace\", workload=~\"$workload\", policy=~\"$policy\", rule=~\"$rule\", action=~\"$action\"},operation)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate of File Events (filtered)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(tetragon_file_actions_total{namespace=~\"$namespace\", workload=~\"$workload\", policy=~\"$policy\", rule=~\"$rule\", action=~\"$action\", operation=~\"$operation\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of File Events Cluster-Wide",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(tetragon_file_events_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost File Events",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum(tetragon_missed_events_total{msg_op=~\"129|131\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "File Events In/Out Cache",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(direction) (tetragon_file_cache_events_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}