// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cmd.proto

package dp

import (
	fmt "fmt"

	proto "github.com/gogo/protobuf/proto"

	math "math"

	gogoproto "github.com/gogo/protobuf/gogoproto"

	types "github.com/gogo/protobuf/types"

	pds "github.com/isovalent/hubble-fgs/pkg/dpu/pensando/pds"

	io "io"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// goproto_enum_prefix from public import gogo.proto
var E_GoprotoEnumPrefix = gogoproto.E_GoprotoEnumPrefix

// goproto_enum_stringer from public import gogo.proto
var E_GoprotoEnumStringer = gogoproto.E_GoprotoEnumStringer

// enum_stringer from public import gogo.proto
var E_EnumStringer = gogoproto.E_EnumStringer

// enum_customname from public import gogo.proto
var E_EnumCustomname = gogoproto.E_EnumCustomname

// enumdecl from public import gogo.proto
var E_Enumdecl = gogoproto.E_Enumdecl

// enumvalue_customname from public import gogo.proto
var E_EnumvalueCustomname = gogoproto.E_EnumvalueCustomname

// goproto_getters_all from public import gogo.proto
var E_GoprotoGettersAll = gogoproto.E_GoprotoGettersAll

// goproto_enum_prefix_all from public import gogo.proto
var E_GoprotoEnumPrefixAll = gogoproto.E_GoprotoEnumPrefixAll

// goproto_stringer_all from public import gogo.proto
var E_GoprotoStringerAll = gogoproto.E_GoprotoStringerAll

// verbose_equal_all from public import gogo.proto
var E_VerboseEqualAll = gogoproto.E_VerboseEqualAll

// face_all from public import gogo.proto
var E_FaceAll = gogoproto.E_FaceAll

// gostring_all from public import gogo.proto
var E_GostringAll = gogoproto.E_GostringAll

// populate_all from public import gogo.proto
var E_PopulateAll = gogoproto.E_PopulateAll

// stringer_all from public import gogo.proto
var E_StringerAll = gogoproto.E_StringerAll

// onlyone_all from public import gogo.proto
var E_OnlyoneAll = gogoproto.E_OnlyoneAll

// equal_all from public import gogo.proto
var E_EqualAll = gogoproto.E_EqualAll

// description_all from public import gogo.proto
var E_DescriptionAll = gogoproto.E_DescriptionAll

// testgen_all from public import gogo.proto
var E_TestgenAll = gogoproto.E_TestgenAll

// benchgen_all from public import gogo.proto
var E_BenchgenAll = gogoproto.E_BenchgenAll

// marshaler_all from public import gogo.proto
var E_MarshalerAll = gogoproto.E_MarshalerAll

// unmarshaler_all from public import gogo.proto
var E_UnmarshalerAll = gogoproto.E_UnmarshalerAll

// stable_marshaler_all from public import gogo.proto
var E_StableMarshalerAll = gogoproto.E_StableMarshalerAll

// sizer_all from public import gogo.proto
var E_SizerAll = gogoproto.E_SizerAll

// goproto_enum_stringer_all from public import gogo.proto
var E_GoprotoEnumStringerAll = gogoproto.E_GoprotoEnumStringerAll

// enum_stringer_all from public import gogo.proto
var E_EnumStringerAll = gogoproto.E_EnumStringerAll

// unsafe_marshaler_all from public import gogo.proto
var E_UnsafeMarshalerAll = gogoproto.E_UnsafeMarshalerAll

// unsafe_unmarshaler_all from public import gogo.proto
var E_UnsafeUnmarshalerAll = gogoproto.E_UnsafeUnmarshalerAll

// goproto_extensions_map_all from public import gogo.proto
var E_GoprotoExtensionsMapAll = gogoproto.E_GoprotoExtensionsMapAll

// goproto_unrecognized_all from public import gogo.proto
var E_GoprotoUnrecognizedAll = gogoproto.E_GoprotoUnrecognizedAll

// gogoproto_import from public import gogo.proto
var E_GogoprotoImport = gogoproto.E_GogoprotoImport

// protosizer_all from public import gogo.proto
var E_ProtosizerAll = gogoproto.E_ProtosizerAll

// compare_all from public import gogo.proto
var E_CompareAll = gogoproto.E_CompareAll

// typedecl_all from public import gogo.proto
var E_TypedeclAll = gogoproto.E_TypedeclAll

// enumdecl_all from public import gogo.proto
var E_EnumdeclAll = gogoproto.E_EnumdeclAll

// goproto_registration from public import gogo.proto
var E_GoprotoRegistration = gogoproto.E_GoprotoRegistration

// messagename_all from public import gogo.proto
var E_MessagenameAll = gogoproto.E_MessagenameAll

// goproto_sizecache_all from public import gogo.proto
var E_GoprotoSizecacheAll = gogoproto.E_GoprotoSizecacheAll

// goproto_unkeyed_all from public import gogo.proto
var E_GoprotoUnkeyedAll = gogoproto.E_GoprotoUnkeyedAll

// goproto_getters from public import gogo.proto
var E_GoprotoGetters = gogoproto.E_GoprotoGetters

// goproto_stringer from public import gogo.proto
var E_GoprotoStringer = gogoproto.E_GoprotoStringer

// verbose_equal from public import gogo.proto
var E_VerboseEqual = gogoproto.E_VerboseEqual

// face from public import gogo.proto
var E_Face = gogoproto.E_Face

// gostring from public import gogo.proto
var E_Gostring = gogoproto.E_Gostring

// populate from public import gogo.proto
var E_Populate = gogoproto.E_Populate

// stringer from public import gogo.proto
var E_Stringer = gogoproto.E_Stringer

// onlyone from public import gogo.proto
var E_Onlyone = gogoproto.E_Onlyone

// equal from public import gogo.proto
var E_Equal = gogoproto.E_Equal

// description from public import gogo.proto
var E_Description = gogoproto.E_Description

// testgen from public import gogo.proto
var E_Testgen = gogoproto.E_Testgen

// benchgen from public import gogo.proto
var E_Benchgen = gogoproto.E_Benchgen

// marshaler from public import gogo.proto
var E_Marshaler = gogoproto.E_Marshaler

// unmarshaler from public import gogo.proto
var E_Unmarshaler = gogoproto.E_Unmarshaler

// stable_marshaler from public import gogo.proto
var E_StableMarshaler = gogoproto.E_StableMarshaler

// sizer from public import gogo.proto
var E_Sizer = gogoproto.E_Sizer

// unsafe_marshaler from public import gogo.proto
var E_UnsafeMarshaler = gogoproto.E_UnsafeMarshaler

// unsafe_unmarshaler from public import gogo.proto
var E_UnsafeUnmarshaler = gogoproto.E_UnsafeUnmarshaler

// goproto_extensions_map from public import gogo.proto
var E_GoprotoExtensionsMap = gogoproto.E_GoprotoExtensionsMap

// goproto_unrecognized from public import gogo.proto
var E_GoprotoUnrecognized = gogoproto.E_GoprotoUnrecognized

// protosizer from public import gogo.proto
var E_Protosizer = gogoproto.E_Protosizer

// compare from public import gogo.proto
var E_Compare = gogoproto.E_Compare

// typedecl from public import gogo.proto
var E_Typedecl = gogoproto.E_Typedecl

// messagename from public import gogo.proto
var E_Messagename = gogoproto.E_Messagename

// goproto_sizecache from public import gogo.proto
var E_GoprotoSizecache = gogoproto.E_GoprotoSizecache

// goproto_unkeyed from public import gogo.proto
var E_GoprotoUnkeyed = gogoproto.E_GoprotoUnkeyed

// nullable from public import gogo.proto
var E_Nullable = gogoproto.E_Nullable

// embed from public import gogo.proto
var E_Embed = gogoproto.E_Embed

// customtype from public import gogo.proto
var E_Customtype = gogoproto.E_Customtype

// customname from public import gogo.proto
var E_Customname = gogoproto.E_Customname

// jsontag from public import gogo.proto
var E_Jsontag = gogoproto.E_Jsontag

// moretags from public import gogo.proto
var E_Moretags = gogoproto.E_Moretags

// casttype from public import gogo.proto
var E_Casttype = gogoproto.E_Casttype

// castkey from public import gogo.proto
var E_Castkey = gogoproto.E_Castkey

// castvalue from public import gogo.proto
var E_Castvalue = gogoproto.E_Castvalue

// stdtime from public import gogo.proto
var E_Stdtime = gogoproto.E_Stdtime

// stdduration from public import gogo.proto
var E_Stdduration = gogoproto.E_Stdduration

// wktpointer from public import gogo.proto
var E_Wktpointer = gogoproto.E_Wktpointer

// ServiceRequestOp encodes the API operation in the user
// issues request via Unix Domain Socket (UDS)
type ServiceRequestOp int32

const (
	ServiceRequestOp_SERVICE_OP_NONE           ServiceRequestOp = 0
	ServiceRequestOp_SERVICE_OP_CREATE         ServiceRequestOp = 1
	ServiceRequestOp_SERVICE_OP_DELETE         ServiceRequestOp = 2
	ServiceRequestOp_SERVICE_OP_UPDATE         ServiceRequestOp = 3
	ServiceRequestOp_SERVICE_OP_READ           ServiceRequestOp = 4
	ServiceRequestOp_SERVICE_OP_READ_STREAMING ServiceRequestOp = 5
)

var ServiceRequestOp_name = map[int32]string{
	0: "SERVICE_OP_NONE",
	1: "SERVICE_OP_CREATE",
	2: "SERVICE_OP_DELETE",
	3: "SERVICE_OP_UPDATE",
	4: "SERVICE_OP_READ",
	5: "SERVICE_OP_READ_STREAMING",
}
var ServiceRequestOp_value = map[string]int32{
	"SERVICE_OP_NONE":           0,
	"SERVICE_OP_CREATE":         1,
	"SERVICE_OP_DELETE":         2,
	"SERVICE_OP_UPDATE":         3,
	"SERVICE_OP_READ":           4,
	"SERVICE_OP_READ_STREAMING": 5,
}

func (x ServiceRequestOp) String() string {
	return proto.EnumName(ServiceRequestOp_name, int32(x))
}
func (ServiceRequestOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cmd_f2e62d0fb0157b6d, []int{0}
}

type CommandOp int32

const (
	CommandOp_CMD_OP_NONE                               CommandOp = 0
	CommandOp_CMD_OP_FLOW_DUMP                          CommandOp = 1
	CommandOp_CMD_OP_SESSION_DETAIL_DUMP                CommandOp = 2
	CommandOp_CMD_OP_PIPELINE_DROP_STATS_DUMP           CommandOp = 3
	CommandOp_CMD_OP_DATAPATH_ASSIST_DUMP               CommandOp = 4
	CommandOp_CMD_OP_DATAPATH_ASSIST                    CommandOp = 5
	CommandOp_CMD_OP_FLOW_CLEAR                         CommandOp = 6
	CommandOp_CMD_OP_NACL_DUMP                          CommandOp = 7
	CommandOp_CMD_OP_PIN_UPLINKS_TO_HOST                CommandOp = 8
	CommandOp_CMD_OP_PIN_UPLINKS_TO_ARM                 CommandOp = 9
	CommandOp_CMD_OP_PIN_UPLINK_TO_LIF                  CommandOp = 10
	CommandOp_CMD_OP_PIN_UPLINKS_CLEAR                  CommandOp = 11
	CommandOp_CMD_OP_PIN_UPLINKS_DUMP                   CommandOp = 12
	CommandOp_CMD_OP_EGRESS_NACL_DUMP                   CommandOp = 13
	CommandOp_CMD_OP_PIPELINE_TABLE_INFO_DUMP           CommandOp = 14
	CommandOp_CMD_OP_PIPELINE_TABLE_CONSTANT_DUMP       CommandOp = 15
	CommandOp_CMD_OP_PIPELINE_DROP_STATS_CLEAR          CommandOp = 16
	CommandOp_CMD_OP_DATAPATH_ASSIST_CLEAR              CommandOp = 17
	CommandOp_CMD_OP_GVE_ENABLE                         CommandOp = 18
	CommandOp_CMD_OP_GVE_DISABLE                        CommandOp = 19
	CommandOp_CMD_OP_GVE_HDR_LEN_UPDATE                 CommandOp = 20
	CommandOp_CMD_OP_NSG_POLICY_DUMP                    CommandOp = 21
	CommandOp_CMD_OP_NSG_RULE_DUMP                      CommandOp = 22
	CommandOp_CMD_OP_RXFLOW_DUMP                        CommandOp = 23
	CommandOp_CMD_OP_RXFLOW_CLEAR                       CommandOp = 24
	CommandOp_CMD_OP_TXFLOW_DUMP                        CommandOp = 25
	CommandOp_CMD_OP_TXFLOW_CLEAR                       CommandOp = 26
	CommandOp_CMD_OP_ROUTE_TABLE_DUMP                   CommandOp = 27
	CommandOp_CMD_OP_IPSEC_SA_DUMP                      CommandOp = 28
	CommandOp_CMD_OP_IPSEC_SPI_DUMP                     CommandOp = 29
	CommandOp_CMD_OP_IPSEC_STATS_DUMP                   CommandOp = 30
	CommandOp_CMD_OP_IPSEC_STATS_CLEAR                  CommandOp = 31
	CommandOp_CMD_OP_PIPELINE_IP_FRAG_STATE_UPD         CommandOp = 32
	CommandOp_CMD_OP_PIPELINE_STATS_DUMP                CommandOp = 33
	CommandOp_CMD_OP_PIPELINE_STATS_CLEAR               CommandOp = 34
	CommandOp_CMD_OP_P4I_IP_FRAG_REASSEMBLY_STATS_DUMP  CommandOp = 35
	CommandOp_CMD_OP_P4I_IP_FRAG_REASSEMBLY_STATS_CLEAR CommandOp = 36
	CommandOp_CMD_OP_P4E_IP_FRAG_REASSEMBLY_STATS_DUMP  CommandOp = 37
	CommandOp_CMD_OP_P4E_IP_FRAG_REASSEMBLY_STATS_CLEAR CommandOp = 38
	CommandOp_CMD_OP_UPLINK_RX_POLICER_DUMP             CommandOp = 39
	CommandOp_CMD_OP_PIPELINE_IP_REASSEMBLY_STATE_UPD   CommandOp = 40
	CommandOp_CMD_OP_LIF_CAROUSEL_CONFIG                CommandOp = 41
	CommandOp_CMD_OP_LIF_CAROUSEL_CONFIG_DUMP           CommandOp = 42
	CommandOp_CMD_OP_COLLECTOR_SESSION_DUMP             CommandOp = 43
	CommandOp_CMD_OP_COLLECTOR_SESSION_STATS_DUMP       CommandOp = 44
	CommandOp_CMD_OP_COLLECTOR_SESSION_STATS_CLEAR      CommandOp = 45
	CommandOp_CMD_OP_TELEMETRY_POLICY_DUMP              CommandOp = 46
	CommandOp_CMD_OP_ARFS_FLOW_DUMP                     CommandOp = 47
	CommandOp_CMD_OP_ARFS_FLOW_CLEAR                    CommandOp = 48
	CommandOp_CMD_OP_PIPELINE_P4I_DEBUG_STATS_DUMP      CommandOp = 49
	CommandOp_CMD_OP_PIPELINE_P4E_DEBUG_STATS_DUMP      CommandOp = 50
	CommandOp_CMD_OP_PIPELINE_P4E_OPCODE_STATS_DUMP     CommandOp = 51
	CommandOp_CMD_OP_PIPELINE_P4E_MPATH_STATS_DUMP      CommandOp = 52
	CommandOp_CMD_OP_GVE_LAN_RX_CONFIG                  CommandOp = 53
	CommandOp_CMD_OP_GVE_LAN_RX_CONFIG_DUMP             CommandOp = 54
	CommandOp_CMD_OP_PIPELINE_P4I_DEBUG_STATS_CLEAR     CommandOp = 55
	CommandOp_CMD_OP_PIPELINE_P4E_DEBUG_STATS_CLEAR     CommandOp = 56
	CommandOp_CMD_OP_PIPELINE_P4E_OPCODE_STATS_CLEAR    CommandOp = 57
	CommandOp_CMD_OP_PIPELINE_P4E_MPATH_STATS_CLEAR     CommandOp = 58
	CommandOp_CMD_OP_PIPELINE_P4E_RDMA_TEST_UPDATE      CommandOp = 59
	CommandOp_CMD_OP_PIPELINE_P4E_RDMA_CAPTURE_DUMP     CommandOp = 60
	CommandOp_CMD_OP_PIPELINE_P4E_RDMA_CAPTURE_UPDATE   CommandOp = 61
	CommandOp_CMD_OP_PIPELINE_LPM_LKP_DMA_QDIST_CONTROL CommandOp = 62
	CommandOp_CMD_OP_RDMA_KEY_TABLE_ENTRY_DUMP          CommandOp = 63
	CommandOp_CMD_OP_RDMA_PAGE_TABLE_ENTRY_DUMP         CommandOp = 64
	CommandOp_CMD_OP_PIPELINE_P4E_RDMA_TEST_DUMP        CommandOp = 65
	CommandOp_CMD_OP_PIPELINE_P4E_RDMA_TEST_CLEAR       CommandOp = 66
	CommandOp_CMD_OP_LIF_CAROUSEL_VPORT_QUOTA_DUMP      CommandOp = 67
	CommandOp_CMD_OP_LIF_CAROUSEL_GLOBAL_QUOTA_DUMP     CommandOp = 68
	CommandOp_CMD_OP_PIPELINE_P4I_OPCODE_STATS_DUMP     CommandOp = 69
	CommandOp_CMD_OP_PIPELINE_P4I_QP_STATS_DUMP         CommandOp = 70
	CommandOp_CMD_OP_PIPELINE_P4E_QP_STATS_DUMP         CommandOp = 71
	CommandOp_CMD_OP_PIPELINE_P4I_OPCODE_STATS_CLEAR    CommandOp = 72
	CommandOp_CMD_OP_PIPELINE_P4I_QP_STATS_CLEAR        CommandOp = 73
	CommandOp_CMD_OP_PIPELINE_P4E_QP_STATS_CLEAR        CommandOp = 74
	CommandOp_CMD_OP_CRYPTO_TEST_AES                    CommandOp = 75
	CommandOp_CMD_OP_FLOW_STATS_DUMP                    CommandOp = 76
	CommandOp_CMD_OP_FLOW_STATS_CLEAR                   CommandOp = 77
	CommandOp_CMD_OP_SHOW_PIPELINE_COUNTERS             CommandOp = 78
	CommandOp_CMD_OP_HS_SHOW_POLICIES                   CommandOp = 79
	CommandOp_CMD_OP_HS_POLICIES_OFF                    CommandOp = 80
	CommandOp_CMD_OP_HS_POLICIES_ON                     CommandOp = 81
	CommandOp_CMD_OP_HS_VERIFICATION_ON                 CommandOp = 82
	CommandOp_CMD_OP_HS_VERIFICATION_OFF                CommandOp = 83
	CommandOp_CMD_OP_HS_LOGGING                         CommandOp = 84
	CommandOp_CMD_OP_HA_ENABLE                          CommandOp = 85
	CommandOp_CMD_OP_HA_DISABLE                         CommandOp = 86
	CommandOp_CMD_OP_HS_POLICER_ON                      CommandOp = 87
	CommandOp_CMD_OP_HS_POLICER_OFF                     CommandOp = 88
)

var CommandOp_name = map[int32]string{
	0:  "CMD_OP_NONE",
	1:  "CMD_OP_FLOW_DUMP",
	2:  "CMD_OP_SESSION_DETAIL_DUMP",
	3:  "CMD_OP_PIPELINE_DROP_STATS_DUMP",
	4:  "CMD_OP_DATAPATH_ASSIST_DUMP",
	5:  "CMD_OP_DATAPATH_ASSIST",
	6:  "CMD_OP_FLOW_CLEAR",
	7:  "CMD_OP_NACL_DUMP",
	8:  "CMD_OP_PIN_UPLINKS_TO_HOST",
	9:  "CMD_OP_PIN_UPLINKS_TO_ARM",
	10: "CMD_OP_PIN_UPLINK_TO_LIF",
	11: "CMD_OP_PIN_UPLINKS_CLEAR",
	12: "CMD_OP_PIN_UPLINKS_DUMP",
	13: "CMD_OP_EGRESS_NACL_DUMP",
	14: "CMD_OP_PIPELINE_TABLE_INFO_DUMP",
	15: "CMD_OP_PIPELINE_TABLE_CONSTANT_DUMP",
	16: "CMD_OP_PIPELINE_DROP_STATS_CLEAR",
	17: "CMD_OP_DATAPATH_ASSIST_CLEAR",
	18: "CMD_OP_GVE_ENABLE",
	19: "CMD_OP_GVE_DISABLE",
	20: "CMD_OP_GVE_HDR_LEN_UPDATE",
	21: "CMD_OP_NSG_POLICY_DUMP",
	22: "CMD_OP_NSG_RULE_DUMP",
	23: "CMD_OP_RXFLOW_DUMP",
	24: "CMD_OP_RXFLOW_CLEAR",
	25: "CMD_OP_TXFLOW_DUMP",
	26: "CMD_OP_TXFLOW_CLEAR",
	27: "CMD_OP_ROUTE_TABLE_DUMP",
	28: "CMD_OP_IPSEC_SA_DUMP",
	29: "CMD_OP_IPSEC_SPI_DUMP",
	30: "CMD_OP_IPSEC_STATS_DUMP",
	31: "CMD_OP_IPSEC_STATS_CLEAR",
	32: "CMD_OP_PIPELINE_IP_FRAG_STATE_UPD",
	33: "CMD_OP_PIPELINE_STATS_DUMP",
	34: "CMD_OP_PIPELINE_STATS_CLEAR",
	35: "CMD_OP_P4I_IP_FRAG_REASSEMBLY_STATS_DUMP",
	36: "CMD_OP_P4I_IP_FRAG_REASSEMBLY_STATS_CLEAR",
	37: "CMD_OP_P4E_IP_FRAG_REASSEMBLY_STATS_DUMP",
	38: "CMD_OP_P4E_IP_FRAG_REASSEMBLY_STATS_CLEAR",
	39: "CMD_OP_UPLINK_RX_POLICER_DUMP",
	40: "CMD_OP_PIPELINE_IP_REASSEMBLY_STATE_UPD",
	41: "CMD_OP_LIF_CAROUSEL_CONFIG",
	42: "CMD_OP_LIF_CAROUSEL_CONFIG_DUMP",
	43: "CMD_OP_COLLECTOR_SESSION_DUMP",
	44: "CMD_OP_COLLECTOR_SESSION_STATS_DUMP",
	45: "CMD_OP_COLLECTOR_SESSION_STATS_CLEAR",
	46: "CMD_OP_TELEMETRY_POLICY_DUMP",
	47: "CMD_OP_ARFS_FLOW_DUMP",
	48: "CMD_OP_ARFS_FLOW_CLEAR",
	49: "CMD_OP_PIPELINE_P4I_DEBUG_STATS_DUMP",
	50: "CMD_OP_PIPELINE_P4E_DEBUG_STATS_DUMP",
	51: "CMD_OP_PIPELINE_P4E_OPCODE_STATS_DUMP",
	52: "CMD_OP_PIPELINE_P4E_MPATH_STATS_DUMP",
	53: "CMD_OP_GVE_LAN_RX_CONFIG",
	54: "CMD_OP_GVE_LAN_RX_CONFIG_DUMP",
	55: "CMD_OP_PIPELINE_P4I_DEBUG_STATS_CLEAR",
	56: "CMD_OP_PIPELINE_P4E_DEBUG_STATS_CLEAR",
	57: "CMD_OP_PIPELINE_P4E_OPCODE_STATS_CLEAR",
	58: "CMD_OP_PIPELINE_P4E_MPATH_STATS_CLEAR",
	59: "CMD_OP_PIPELINE_P4E_RDMA_TEST_UPDATE",
	60: "CMD_OP_PIPELINE_P4E_RDMA_CAPTURE_DUMP",
	61: "CMD_OP_PIPELINE_P4E_RDMA_CAPTURE_UPDATE",
	62: "CMD_OP_PIPELINE_LPM_LKP_DMA_QDIST_CONTROL",
	63: "CMD_OP_RDMA_KEY_TABLE_ENTRY_DUMP",
	64: "CMD_OP_RDMA_PAGE_TABLE_ENTRY_DUMP",
	65: "CMD_OP_PIPELINE_P4E_RDMA_TEST_DUMP",
	66: "CMD_OP_PIPELINE_P4E_RDMA_TEST_CLEAR",
	67: "CMD_OP_LIF_CAROUSEL_VPORT_QUOTA_DUMP",
	68: "CMD_OP_LIF_CAROUSEL_GLOBAL_QUOTA_DUMP",
	69: "CMD_OP_PIPELINE_P4I_OPCODE_STATS_DUMP",
	70: "CMD_OP_PIPELINE_P4I_QP_STATS_DUMP",
	71: "CMD_OP_PIPELINE_P4E_QP_STATS_DUMP",
	72: "CMD_OP_PIPELINE_P4I_OPCODE_STATS_CLEAR",
	73: "CMD_OP_PIPELINE_P4I_QP_STATS_CLEAR",
	74: "CMD_OP_PIPELINE_P4E_QP_STATS_CLEAR",
	75: "CMD_OP_CRYPTO_TEST_AES",
	76: "CMD_OP_FLOW_STATS_DUMP",
	77: "CMD_OP_FLOW_STATS_CLEAR",
	78: "CMD_OP_SHOW_PIPELINE_COUNTERS",
	79: "CMD_OP_HS_SHOW_POLICIES",
	80: "CMD_OP_HS_POLICIES_OFF",
	81: "CMD_OP_HS_POLICIES_ON",
	82: "CMD_OP_HS_VERIFICATION_ON",
	83: "CMD_OP_HS_VERIFICATION_OFF",
	84: "CMD_OP_HS_LOGGING",
	85: "CMD_OP_HA_ENABLE",
	86: "CMD_OP_HA_DISABLE",
	87: "CMD_OP_HS_POLICER_ON",
	88: "CMD_OP_HS_POLICER_OFF",
}
var CommandOp_value = map[string]int32{
	"CMD_OP_NONE":                               0,
	"CMD_OP_FLOW_DUMP":                          1,
	"CMD_OP_SESSION_DETAIL_DUMP":                2,
	"CMD_OP_PIPELINE_DROP_STATS_DUMP":           3,
	"CMD_OP_DATAPATH_ASSIST_DUMP":               4,
	"CMD_OP_DATAPATH_ASSIST":                    5,
	"CMD_OP_FLOW_CLEAR":                         6,
	"CMD_OP_NACL_DUMP":                          7,
	"CMD_OP_PIN_UPLINKS_TO_HOST":                8,
	"CMD_OP_PIN_UPLINKS_TO_ARM":                 9,
	"CMD_OP_PIN_UPLINK_TO_LIF":                  10,
	"CMD_OP_PIN_UPLINKS_CLEAR":                  11,
	"CMD_OP_PIN_UPLINKS_DUMP":                   12,
	"CMD_OP_EGRESS_NACL_DUMP":                   13,
	"CMD_OP_PIPELINE_TABLE_INFO_DUMP":           14,
	"CMD_OP_PIPELINE_TABLE_CONSTANT_DUMP":       15,
	"CMD_OP_PIPELINE_DROP_STATS_CLEAR":          16,
	"CMD_OP_DATAPATH_ASSIST_CLEAR":              17,
	"CMD_OP_GVE_ENABLE":                         18,
	"CMD_OP_GVE_DISABLE":                        19,
	"CMD_OP_GVE_HDR_LEN_UPDATE":                 20,
	"CMD_OP_NSG_POLICY_DUMP":                    21,
	"CMD_OP_NSG_RULE_DUMP":                      22,
	"CMD_OP_RXFLOW_DUMP":                        23,
	"CMD_OP_RXFLOW_CLEAR":                       24,
	"CMD_OP_TXFLOW_DUMP":                        25,
	"CMD_OP_TXFLOW_CLEAR":                       26,
	"CMD_OP_ROUTE_TABLE_DUMP":                   27,
	"CMD_OP_IPSEC_SA_DUMP":                      28,
	"CMD_OP_IPSEC_SPI_DUMP":                     29,
	"CMD_OP_IPSEC_STATS_DUMP":                   30,
	"CMD_OP_IPSEC_STATS_CLEAR":                  31,
	"CMD_OP_PIPELINE_IP_FRAG_STATE_UPD":         32,
	"CMD_OP_PIPELINE_STATS_DUMP":                33,
	"CMD_OP_PIPELINE_STATS_CLEAR":               34,
	"CMD_OP_P4I_IP_FRAG_REASSEMBLY_STATS_DUMP":  35,
	"CMD_OP_P4I_IP_FRAG_REASSEMBLY_STATS_CLEAR": 36,
	"CMD_OP_P4E_IP_FRAG_REASSEMBLY_STATS_DUMP":  37,
	"CMD_OP_P4E_IP_FRAG_REASSEMBLY_STATS_CLEAR": 38,
	"CMD_OP_UPLINK_RX_POLICER_DUMP":             39,
	"CMD_OP_PIPELINE_IP_REASSEMBLY_STATE_UPD":   40,
	"CMD_OP_LIF_CAROUSEL_CONFIG":                41,
	"CMD_OP_LIF_CAROUSEL_CONFIG_DUMP":           42,
	"CMD_OP_COLLECTOR_SESSION_DUMP":             43,
	"CMD_OP_COLLECTOR_SESSION_STATS_DUMP":       44,
	"CMD_OP_COLLECTOR_SESSION_STATS_CLEAR":      45,
	"CMD_OP_TELEMETRY_POLICY_DUMP":              46,
	"CMD_OP_ARFS_FLOW_DUMP":                     47,
	"CMD_OP_ARFS_FLOW_CLEAR":                    48,
	"CMD_OP_PIPELINE_P4I_DEBUG_STATS_DUMP":      49,
	"CMD_OP_PIPELINE_P4E_DEBUG_STATS_DUMP":      50,
	"CMD_OP_PIPELINE_P4E_OPCODE_STATS_DUMP":     51,
	"CMD_OP_PIPELINE_P4E_MPATH_STATS_DUMP":      52,
	"CMD_OP_GVE_LAN_RX_CONFIG":                  53,
	"CMD_OP_GVE_LAN_RX_CONFIG_DUMP":             54,
	"CMD_OP_PIPELINE_P4I_DEBUG_STATS_CLEAR":     55,
	"CMD_OP_PIPELINE_P4E_DEBUG_STATS_CLEAR":     56,
	"CMD_OP_PIPELINE_P4E_OPCODE_STATS_CLEAR":    57,
	"CMD_OP_PIPELINE_P4E_MPATH_STATS_CLEAR":     58,
	"CMD_OP_PIPELINE_P4E_RDMA_TEST_UPDATE":      59,
	"CMD_OP_PIPELINE_P4E_RDMA_CAPTURE_DUMP":     60,
	"CMD_OP_PIPELINE_P4E_RDMA_CAPTURE_UPDATE":   61,
	"CMD_OP_PIPELINE_LPM_LKP_DMA_QDIST_CONTROL": 62,
	"CMD_OP_RDMA_KEY_TABLE_ENTRY_DUMP":          63,
	"CMD_OP_RDMA_PAGE_TABLE_ENTRY_DUMP":         64,
	"CMD_OP_PIPELINE_P4E_RDMA_TEST_DUMP":        65,
	"CMD_OP_PIPELINE_P4E_RDMA_TEST_CLEAR":       66,
	"CMD_OP_LIF_CAROUSEL_VPORT_QUOTA_DUMP":      67,
	"CMD_OP_LIF_CAROUSEL_GLOBAL_QUOTA_DUMP":     68,
	"CMD_OP_PIPELINE_P4I_OPCODE_STATS_DUMP":     69,
	"CMD_OP_PIPELINE_P4I_QP_STATS_DUMP":         70,
	"CMD_OP_PIPELINE_P4E_QP_STATS_DUMP":         71,
	"CMD_OP_PIPELINE_P4I_OPCODE_STATS_CLEAR":    72,
	"CMD_OP_PIPELINE_P4I_QP_STATS_CLEAR":        73,
	"CMD_OP_PIPELINE_P4E_QP_STATS_CLEAR":        74,
	"CMD_OP_CRYPTO_TEST_AES":                    75,
	"CMD_OP_FLOW_STATS_DUMP":                    76,
	"CMD_OP_FLOW_STATS_CLEAR":                   77,
	"CMD_OP_SHOW_PIPELINE_COUNTERS":             78,
	"CMD_OP_HS_SHOW_POLICIES":                   79,
	"CMD_OP_HS_POLICIES_OFF":                    80,
	"CMD_OP_HS_POLICIES_ON":                     81,
	"CMD_OP_HS_VERIFICATION_ON":                 82,
	"CMD_OP_HS_VERIFICATION_OFF":                83,
	"CMD_OP_HS_LOGGING":                         84,
	"CMD_OP_HA_ENABLE":                          85,
	"CMD_OP_HA_DISABLE":                         86,
	"CMD_OP_HS_POLICER_ON":                      87,
	"CMD_OP_HS_POLICER_OFF":                     88,
}

func (x CommandOp) String() string {
	return proto.EnumName(CommandOp_name, int32(x))
}
func (CommandOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cmd_f2e62d0fb0157b6d, []int{1}
}

// ServiceRequestMessage represents the config message from the app
// and the corresponding operation to be performed
type ServiceRequestMessage struct {
	// one of the CRUD operations
	ConfigOp ServiceRequestOp `protobuf:"varint,1,opt,name=ConfigOp,proto3,enum=cmd.ServiceRequestOp" json:"ConfigOp,omitempty"`
	// ConfigMsg is protobuf encoded config message and it can be any of the
	// supported config objects (e.g. VPCRequestMsg etc.)
	ConfigMsg            *types.Any `protobuf:"bytes,2,opt,name=ConfigMsg,proto3" json:"ConfigMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceRequestMessage) Reset()         { *m = ServiceRequestMessage{} }
func (m *ServiceRequestMessage) String() string { return proto.CompactTextString(m) }
func (*ServiceRequestMessage) ProtoMessage()    {}
func (*ServiceRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmd_f2e62d0fb0157b6d, []int{0}
}
func (m *ServiceRequestMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ServiceRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ServiceRequestMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ServiceRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRequestMessage.Merge(dst, src)
}
func (m *ServiceRequestMessage) XXX_Size() int {
	return m.Size()
}
func (m *ServiceRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRequestMessage proto.InternalMessageInfo

func (m *ServiceRequestMessage) GetConfigOp() ServiceRequestOp {
	if m != nil {
		return m.ConfigOp
	}
	return ServiceRequestOp_SERVICE_OP_NONE
}

func (m *ServiceRequestMessage) GetConfigMsg() *types.Any {
	if m != nil {
		return m.ConfigMsg
	}
	return nil
}

// ServiceResponseMessage is the response to ServiceRequestMessage
type ServiceResponseMessage struct {
	// response or reply status for the request
	ApiStatus pds.ApiStatus `protobuf:"varint,1,opt,name=ApiStatus,proto3,enum=types.ApiStatus" json:"ApiStatus,omitempty"`
	// content of the response (esp. for Get requests)
	Response             *types.Any `protobuf:"bytes,2,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceResponseMessage) Reset()         { *m = ServiceResponseMessage{} }
func (m *ServiceResponseMessage) String() string { return proto.CompactTextString(m) }
func (*ServiceResponseMessage) ProtoMessage()    {}
func (*ServiceResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmd_f2e62d0fb0157b6d, []int{1}
}
func (m *ServiceResponseMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ServiceResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ServiceResponseMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ServiceResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceResponseMessage.Merge(dst, src)
}
func (m *ServiceResponseMessage) XXX_Size() int {
	return m.Size()
}
func (m *ServiceResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceResponseMessage proto.InternalMessageInfo

func (m *ServiceResponseMessage) GetApiStatus() pds.ApiStatus {
	if m != nil {
		return m.ApiStatus
	}
	return pds.ApiStatus_API_STATUS_OK
}

func (m *ServiceResponseMessage) GetResponse() *types.Any {
	if m != nil {
		return m.Response
	}
	return nil
}

type CommandMessage struct {
	Command              CommandOp  `protobuf:"varint,1,opt,name=Command,proto3,enum=cmd.CommandOp" json:"Command,omitempty"`
	CommandMsg           *types.Any `protobuf:"bytes,2,opt,name=CommandMsg,proto3" json:"CommandMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommandMessage) Reset()         { *m = CommandMessage{} }
func (m *CommandMessage) String() string { return proto.CompactTextString(m) }
func (*CommandMessage) ProtoMessage()    {}
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmd_f2e62d0fb0157b6d, []int{2}
}
func (m *CommandMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommandMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommandMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CommandMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandMessage.Merge(dst, src)
}
func (m *CommandMessage) XXX_Size() int {
	return m.Size()
}
func (m *CommandMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommandMessage proto.InternalMessageInfo

func (m *CommandMessage) GetCommand() CommandOp {
	if m != nil {
		return m.Command
	}
	return CommandOp_CMD_OP_NONE
}

func (m *CommandMessage) GetCommandMsg() *types.Any {
	if m != nil {
		return m.CommandMsg
	}
	return nil
}

type Range struct {
	Low                  uint32   `protobuf:"varint,1,opt,name=Low,proto3" json:"Low,omitempty"`
	High                 uint32   `protobuf:"varint,2,opt,name=High,proto3" json:"High,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmd_f2e62d0fb0157b6d, []int{3}
}
func (m *Range) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Range.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(dst, src)
}
func (m *Range) XXX_Size() int {
	return m.Size()
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetLow() uint32 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *Range) GetHigh() uint32 {
	if m != nil {
		return m.High
	}
	return 0
}

func init() {
	proto.RegisterType((*ServiceRequestMessage)(nil), "cmd.ServiceRequestMessage")
	proto.RegisterType((*ServiceResponseMessage)(nil), "cmd.ServiceResponseMessage")
	proto.RegisterType((*CommandMessage)(nil), "cmd.CommandMessage")
	proto.RegisterType((*Range)(nil), "cmd.Range")
	proto.RegisterEnum("cmd.ServiceRequestOp", ServiceRequestOp_name, ServiceRequestOp_value)
	proto.RegisterEnum("cmd.CommandOp", CommandOp_name, CommandOp_value)
}
func (m *ServiceRequestMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceRequestMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ConfigOp != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCmd(dAtA, i, uint64(m.ConfigOp))
	}
	if m.ConfigMsg != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCmd(dAtA, i, uint64(m.ConfigMsg.Size()))
		n1, err := m.ConfigMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ServiceResponseMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceResponseMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ApiStatus != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCmd(dAtA, i, uint64(m.ApiStatus))
	}
	if m.Response != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCmd(dAtA, i, uint64(m.Response.Size()))
		n2, err := m.Response.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *CommandMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommandMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Command != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCmd(dAtA, i, uint64(m.Command))
	}
	if m.CommandMsg != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCmd(dAtA, i, uint64(m.CommandMsg.Size()))
		n3, err := m.CommandMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Range) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Range) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Low != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCmd(dAtA, i, uint64(m.Low))
	}
	if m.High != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintCmd(dAtA, i, uint64(m.High))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintCmd(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ServiceRequestMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConfigOp != 0 {
		n += 1 + sovCmd(uint64(m.ConfigOp))
	}
	if m.ConfigMsg != nil {
		l = m.ConfigMsg.Size()
		n += 1 + l + sovCmd(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ServiceResponseMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ApiStatus != 0 {
		n += 1 + sovCmd(uint64(m.ApiStatus))
	}
	if m.Response != nil {
		l = m.Response.Size()
		n += 1 + l + sovCmd(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CommandMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Command != 0 {
		n += 1 + sovCmd(uint64(m.Command))
	}
	if m.CommandMsg != nil {
		l = m.CommandMsg.Size()
		n += 1 + l + sovCmd(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Range) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Low != 0 {
		n += 1 + sovCmd(uint64(m.Low))
	}
	if m.High != 0 {
		n += 1 + sovCmd(uint64(m.High))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCmd(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCmd(x uint64) (n int) {
	return sovCmd(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ServiceRequestMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceRequestMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceRequestMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigOp", wireType)
			}
			m.ConfigOp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConfigOp |= (ServiceRequestOp(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmd
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConfigMsg == nil {
				m.ConfigMsg = &types.Any{}
			}
			if err := m.ConfigMsg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCmd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ServiceResponseMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceResponseMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceResponseMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiStatus", wireType)
			}
			m.ApiStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApiStatus |= (pds.ApiStatus(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmd
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Response == nil {
				m.Response = &types.Any{}
			}
			if err := m.Response.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCmd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommandMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommandMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommandMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			m.Command = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Command |= (CommandOp(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommandMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmd
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommandMsg == nil {
				m.CommandMsg = &types.Any{}
			}
			if err := m.CommandMsg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCmd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Range) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Range: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Range: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Low", wireType)
			}
			m.Low = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Low |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field High", wireType)
			}
			m.High = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.High |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCmd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCmd(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCmd
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCmd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCmd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthCmd
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCmd
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCmd(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCmd = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCmd   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("cmd.proto", fileDescriptor_cmd_f2e62d0fb0157b6d) }

var fileDescriptor_cmd_f2e62d0fb0157b6d = []byte{
	// 1269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xdb, 0x76, 0xd3, 0x46,
	0x17, 0xc6, 0x09, 0xa7, 0x4c, 0x7e, 0xc2, 0x30, 0x24, 0x21, 0x09, 0x10, 0x42, 0x38, 0x85, 0x00,
	0x06, 0x02, 0x7f, 0xcf, 0xa7, 0xb1, 0x34, 0x92, 0xa7, 0x19, 0x69, 0x94, 0x99, 0x71, 0x20, 0xbd,
	0x99, 0x15, 0x88, 0x71, 0xb3, 0x56, 0x63, 0xbb, 0x38, 0xb4, 0x8b, 0x5e, 0xf4, 0x59, 0xfa, 0x38,
	0xbd, 0xec, 0x23, 0x74, 0xf1, 0x12, 0xbd, 0xed, 0x92, 0x46, 0xb6, 0xb7, 0x6c, 0x99, 0xf4, 0xce,
	0xd9, 0xdf, 0xa7, 0xbd, 0xbf, 0xf9, 0x66, 0xef, 0x2d, 0x05, 0xcd, 0xbc, 0x3e, 0x3a, 0xa8, 0x76,
	0xdf, 0x76, 0x8e, 0x3b, 0x64, 0xfa, 0xf5, 0xd1, 0xc1, 0x0a, 0x6a, 0x75, 0x5a, 0x1d, 0x17, 0x58,
	0x59, 0x6e, 0x75, 0x3a, 0xad, 0x9f, 0x9a, 0x8f, 0xb3, 0xbf, 0x5e, 0xbd, 0x7b, 0xf3, 0x78, 0xbf,
	0xfd, 0x3e, 0x87, 0x66, 0x8f, 0xdf, 0x77, 0x9b, 0x3d, 0xf7, 0xc7, 0xfa, 0xef, 0x68, 0x41, 0x37,
	0xdf, 0xfe, 0x72, 0xf8, 0xba, 0xa9, 0x9a, 0x3f, 0xbf, 0x6b, 0xf6, 0x8e, 0xa3, 0x66, 0xaf, 0xb7,
	0xdf, 0x6a, 0x92, 0xa7, 0xe8, 0xbc, 0xd7, 0x69, 0xbf, 0x39, 0x6c, 0xc9, 0xee, 0x52, 0x65, 0xad,
	0xb2, 0x31, 0xb7, 0xb5, 0x50, 0x4d, 0xeb, 0x15, 0xd9, 0xb2, 0xab, 0x06, 0x34, 0xb2, 0x85, 0x66,
	0xdc, 0xef, 0xa8, 0xd7, 0x5a, 0x9a, 0x5a, 0xab, 0x6c, 0xcc, 0x6e, 0xcd, 0x57, 0x9d, 0x8e, 0x6a,
	0x5f, 0x47, 0x95, 0xb6, 0xdf, 0xab, 0x21, 0x6d, 0xfd, 0x37, 0xb4, 0x38, 0xc8, 0xd8, 0xeb, 0x76,
	0xda, 0xbd, 0x66, 0x5f, 0x40, 0x15, 0xcd, 0xd0, 0xee, 0xa1, 0x3e, 0xde, 0x3f, 0x7e, 0xd7, 0xcb,
	0x15, 0xe0, 0xaa, 0x93, 0x3e, 0x88, 0xab, 0x21, 0x85, 0x3c, 0x41, 0xe7, 0xfb, 0x29, 0x3e, 0x5a,
	0x7c, 0xc0, 0x5a, 0xef, 0xa2, 0x39, 0xaf, 0x73, 0x74, 0xb4, 0xdf, 0x3e, 0xe8, 0xd7, 0xdc, 0x40,
	0xe7, 0xf2, 0x48, 0x5e, 0x71, 0x2e, 0x3b, 0x73, 0x1e, 0x93, 0x5d, 0xd5, 0x87, 0xc9, 0x73, 0x84,
	0xfa, 0xcf, 0x9e, 0x70, 0x58, 0xc0, 0x5b, 0x7f, 0x84, 0xce, 0xa8, 0xfd, 0x76, 0xab, 0x49, 0x30,
	0x9a, 0x16, 0x9d, 0x5f, 0xb3, 0x22, 0x17, 0x54, 0xfa, 0x93, 0x10, 0x74, 0xba, 0x7e, 0xd8, 0xfa,
	0x31, 0x4b, 0x75, 0x41, 0x65, 0xbf, 0x37, 0xff, 0xa8, 0x20, 0x3c, 0xea, 0x37, 0xb9, 0x8c, 0x2e,
	0x6a, 0xa6, 0x76, 0xb9, 0xc7, 0xac, 0x4c, 0x6c, 0x2c, 0x63, 0x86, 0x4f, 0x91, 0x05, 0x74, 0x09,
	0x04, 0x3d, 0xc5, 0xa8, 0x61, 0xb8, 0x32, 0x12, 0xf6, 0x99, 0x60, 0x86, 0xe1, 0xa9, 0x91, 0x70,
	0x23, 0xf1, 0x53, 0xf6, 0xf4, 0x48, 0x66, 0xc5, 0xa8, 0x8f, 0x4f, 0x93, 0xeb, 0x68, 0x79, 0x24,
	0x68, 0xb5, 0x51, 0x8c, 0x46, 0x3c, 0x0e, 0xf1, 0x99, 0xcd, 0x7f, 0x16, 0xd3, 0x4b, 0xcf, 0xed,
	0x21, 0x17, 0xd1, 0xac, 0x17, 0xf9, 0x40, 0xd7, 0x3c, 0xc2, 0x79, 0x20, 0x10, 0xf2, 0x85, 0xf5,
	0x1b, 0x51, 0x82, 0x2b, 0x64, 0x15, 0xad, 0xe4, 0x51, 0xcd, 0xb4, 0xe6, 0x32, 0xb6, 0x3e, 0x33,
	0x94, 0x0b, 0x87, 0x4f, 0x91, 0x5b, 0xe8, 0x46, 0x8e, 0x27, 0x3c, 0x61, 0x82, 0xc7, 0xcc, 0xfa,
	0x2a, 0x65, 0x1b, 0x6a, 0xb4, 0x23, 0x4d, 0x93, 0x1b, 0xe8, 0x6a, 0x4e, 0xf2, 0xa9, 0xa1, 0x09,
	0x35, 0x75, 0x4b, 0xb5, 0xe6, 0xda, 0x38, 0xc2, 0x69, 0xb2, 0x82, 0x16, 0xcb, 0x09, 0xf8, 0x4c,
	0xea, 0x00, 0xd4, 0xe5, 0x09, 0x46, 0x15, 0x3e, 0x0b, 0xe4, 0xc6, 0xd4, 0xcb, 0xe5, 0x9c, 0x03,
	0x72, 0x13, 0x1e, 0xdb, 0x46, 0x22, 0x78, 0xbc, 0xad, 0xad, 0x91, 0xb6, 0x2e, 0xb5, 0xc1, 0xe7,
	0x53, 0x8b, 0xca, 0x71, 0xaa, 0x22, 0x3c, 0x43, 0xae, 0xa1, 0xa5, 0x31, 0x38, 0x45, 0x05, 0x0f,
	0x30, 0x2a, 0x45, 0x75, 0x2e, 0x68, 0x96, 0x5c, 0x45, 0x57, 0x4a, 0xd0, 0x4c, 0xd7, 0xff, 0x00,
	0xc8, 0x42, 0xc5, 0xb4, 0x06, 0xa2, 0x2f, 0x94, 0x79, 0x68, 0x68, 0x4d, 0x30, 0xcb, 0xe3, 0x40,
	0x3a, 0xd2, 0x1c, 0xb9, 0x87, 0x6e, 0x95, 0x93, 0x3c, 0x19, 0x6b, 0x43, 0xe3, 0xdc, 0xcb, 0x8b,
	0xe4, 0x36, 0x5a, 0xfb, 0xc8, 0x8d, 0x38, 0xb5, 0x98, 0xac, 0xa1, 0x6b, 0x13, 0xae, 0xc4, 0x31,
	0x2e, 0x01, 0xdf, 0xc3, 0x5d, 0x66, 0x59, 0x9c, 0x16, 0xc3, 0x84, 0x2c, 0x22, 0x02, 0xc2, 0x3e,
	0xd7, 0x59, 0xfc, 0x32, 0x70, 0x36, 0x8d, 0xd7, 0x7d, 0x65, 0x05, 0x8b, 0xfb, 0x0d, 0x3b, 0x0f,
	0x6e, 0x38, 0xd6, 0xa1, 0x4d, 0xa4, 0xe0, 0xde, 0x9e, 0x53, 0xbc, 0x40, 0x96, 0xd0, 0x3c, 0xc0,
	0x54, 0x43, 0x30, 0x87, 0x2c, 0x82, 0x62, 0xea, 0xe5, 0xb0, 0x2b, 0xaf, 0x90, 0x2b, 0xe8, 0x72,
	0x31, 0xee, 0x44, 0x2f, 0x81, 0x07, 0x0c, 0x78, 0x60, 0x19, 0x3c, 0x60, 0xe0, 0x03, 0x2b, 0xe0,
	0x62, 0x94, 0x6c, 0x98, 0xbe, 0xa7, 0xd9, 0x53, 0x57, 0x81, 0x30, 0x9e, 0x68, 0xe6, 0x59, 0x4d,
	0x1d, 0x72, 0x8d, 0x2c, 0xa3, 0x85, 0x22, 0x92, 0x70, 0x07, 0x5d, 0x07, 0x19, 0x73, 0x68, 0x38,
	0x09, 0xab, 0xa0, 0x85, 0x20, 0xe8, 0xc4, 0xdc, 0x20, 0x77, 0xd0, 0xcd, 0xd1, 0xab, 0xe3, 0x89,
	0x0d, 0x14, 0x0d, 0x33, 0x22, 0x4b, 0xed, 0xc4, 0x6b, 0x85, 0x26, 0xcf, 0x69, 0xa0, 0xc8, 0x4d,
	0x30, 0x6e, 0x23, 0xb8, 0xab, 0xb3, 0x4e, 0x1e, 0xa2, 0x8d, 0x3e, 0xe1, 0x39, 0x1f, 0x94, 0x50,
	0x8c, 0x6a, 0xcd, 0xa2, 0x9a, 0xd8, 0x83, 0xe9, 0x6e, 0x91, 0x47, 0xe8, 0xfe, 0x7f, 0x61, 0xbb,
	0xe4, 0xb7, 0x0b, 0xc9, 0xd9, 0x09, 0xc9, 0xef, 0x14, 0x92, 0xb3, 0x93, 0x92, 0xdf, 0x25, 0x37,
	0xd1, 0xf5, 0x9c, 0x9e, 0x0f, 0xa7, 0x7a, 0xe9, 0x9a, 0x89, 0x29, 0x97, 0xf1, 0x1e, 0x79, 0x80,
	0xee, 0x95, 0x98, 0x38, 0x92, 0xd1, 0x59, 0xb9, 0x01, 0xac, 0x14, 0x3c, 0xb0, 0x1e, 0x55, 0xb2,
	0xa1, 0x99, 0x48, 0x67, 0x2a, 0xe0, 0x21, 0xbe, 0x0f, 0x46, 0xb3, 0x04, 0x77, 0x15, 0x37, 0x81,
	0x28, 0x4f, 0x0a, 0xc1, 0x3c, 0x23, 0xd5, 0x70, 0x5b, 0xa6, 0x94, 0x07, 0x60, 0x7a, 0xc7, 0x29,
	0xc0, 0x8f, 0x87, 0x64, 0x03, 0xdd, 0x3e, 0x81, 0xe8, 0xac, 0x78, 0x04, 0x26, 0xd8, 0x30, 0xc1,
	0x22, 0x66, 0xd4, 0x5e, 0x61, 0xae, 0xaa, 0xa0, 0x49, 0xa9, 0x0a, 0x34, 0x58, 0xeb, 0x8f, 0xc1,
	0x38, 0x0e, 0x21, 0x97, 0xf8, 0x09, 0x90, 0x30, 0x30, 0x30, 0xbd, 0x78, 0x9f, 0xd5, 0x1a, 0x21,
	0x14, 0xfb, 0xb4, 0x9c, 0xc9, 0xc6, 0x99, 0x5b, 0xe4, 0x3e, 0xba, 0x53, 0xc6, 0x94, 0x89, 0x27,
	0xfd, 0x42, 0xf7, 0x3e, 0x9b, 0x94, 0x34, 0xca, 0x76, 0x14, 0x60, 0x3e, 0x07, 0xc3, 0x94, 0xae,
	0x1c, 0x41, 0xe3, 0xb4, 0x1b, 0xf2, 0xab, 0xfb, 0x3f, 0xb8, 0x95, 0x31, 0xd4, 0x25, 0xf8, 0xa4,
	0x5c, 0x55, 0xf1, 0xa4, 0xce, 0x94, 0x4f, 0x27, 0x1d, 0x60, 0x9c, 0xfa, 0x19, 0xd9, 0x44, 0x77,
	0x4f, 0x3c, 0xab, 0xe3, 0x7e, 0x3e, 0x29, 0x2d, 0x3c, 0xac, 0xa3, 0x7e, 0x31, 0xc9, 0x17, 0xe5,
	0x47, 0xd4, 0x1a, 0xa6, 0x4d, 0x7f, 0xd7, 0x7e, 0x39, 0x29, 0x69, 0xc6, 0xf4, 0x68, 0x62, 0x1a,
	0x2a, 0xdf, 0x70, 0x5f, 0x95, 0x0d, 0xcb, 0x18, 0x35, 0xcf, 0xfb, 0x35, 0x9c, 0xd5, 0x3e, 0x59,
	0x24, 0x91, 0x15, 0xdb, 0x89, 0x4d, 0xf9, 0x3b, 0x7e, 0xf6, 0xfa, 0x90, 0xb1, 0x51, 0x52, 0xe0,
	0x6f, 0xc0, 0x8b, 0x28, 0x4b, 0xb7, 0xcd, 0xf6, 0xf2, 0xed, 0xca, 0xe2, 0xb4, 0x57, 0x33, 0x05,
	0xdf, 0x82, 0x9d, 0x97, 0xb1, 0x12, 0x1a, 0xb2, 0x71, 0xda, 0x77, 0xe4, 0x2e, 0x5a, 0xff, 0xf8,
	0xe9, 0x33, 0x1e, 0x2d, 0x7b, 0x4d, 0x16, 0x79, 0xce, 0xce, 0x1a, 0xb0, 0xb3, 0x30, 0xd9, 0xbb,
	0x89, 0x54, 0xc6, 0xee, 0x34, 0xa4, 0xc9, 0x77, 0xbd, 0x07, 0xec, 0x2c, 0x30, 0x43, 0x21, 0x6b,
	0x54, 0x40, 0xaa, 0x3f, 0xa9, 0xa1, 0xc6, 0xdb, 0x9c, 0x95, 0xed, 0xfa, 0x94, 0xba, 0x53, 0xf8,
	0x74, 0x0a, 0xca, 0x69, 0x6c, 0x84, 0x16, 0x96, 0xf7, 0x1c, 0x2f, 0xeb, 0xb9, 0x7a, 0xb9, 0x95,
	0xa0, 0xb2, 0xe3, 0xf1, 0x49, 0x96, 0x8f, 0xf0, 0xbe, 0x07, 0xbb, 0xc4, 0x53, 0x7b, 0x89, 0x91,
	0xce, 0x67, 0xca, 0x34, 0xde, 0x06, 0x58, 0xb6, 0x62, 0x80, 0x66, 0x01, 0x5e, 0x94, 0x00, 0x73,
	0x49, 0x23, 0x30, 0xbd, 0xba, 0x2e, 0x5f, 0x0c, 0x15, 0x78, 0xb2, 0x11, 0x1b, 0xa6, 0x34, 0x8e,
	0xc1, 0xf3, 0x75, 0x9d, 0xb3, 0xd2, 0xf5, 0xc7, 0x99, 0xc6, 0x12, 0x14, 0xae, 0xeb, 0x41, 0xdc,
	0xca, 0x20, 0xc0, 0x09, 0xd8, 0x8b, 0x05, 0x2c, 0xc6, 0x3b, 0xe0, 0x2b, 0xa6, 0xae, 0xed, 0x2e,
	0x53, 0x3c, 0xe0, 0x1e, 0x35, 0xe9, 0xf2, 0x95, 0x31, 0x56, 0xe0, 0x75, 0x31, 0x06, 0x07, 0x01,
	0xd6, 0xe0, 0x9b, 0xa9, 0xae, 0xad, 0x90, 0x61, 0x98, 0x7e, 0x79, 0x9b, 0x1a, 0xfe, 0xf3, 0xc3,
	0x6a, 0xe5, 0xaf, 0x0f, 0xab, 0x95, 0xbf, 0x3f, 0xac, 0x56, 0x7e, 0x98, 0x3a, 0xe8, 0x26, 0xa7,
	0x5e, 0x9d, 0xcd, 0xfe, 0xf3, 0x78, 0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0x5b, 0x1d,
	0x5d, 0x1a, 0x0e, 0x00, 0x00,
}
