{
 "title": "Tetragon / TCP Throughput / Pod <-> Pod",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tetragon_events_total, cluster)"
    }
   },
   {
    "name": "namespace_a",
    "label": "namespace A",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "workload_a",
    "label": "workload A",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\"}, workload)"
    }
   },
   {
    "name": "pod_a",
    "label": "pod A",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\"}, pod)"
    }
   },
   {
    "name": "namespace_b",
    "label": "namespace B",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "workload_b",
    "label": "workload B",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\"}, workload)"
    }
   },
   {
    "name": "pod_b",
    "label": "pod B",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview A -> B", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes Sent (avg over time)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Retransmitted Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_retransmitbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Received (avg over time)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Sent (avg over time)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Retransmitted Segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_retransmitsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Received (avg over time)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Sent Segment Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__range])) / sum(increase(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Segment Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval])) / sum(rate(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval])) / sum(rate(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Zero Windows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_zerowindow_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Received Segment Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__range])) / sum(increase(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview B -> A", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Bytes Sent (avg over time)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Retransmitted Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_retransmitbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Received (avg over time)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Sent (avg over time)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Retransmitted Segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_retransmitsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Received (avg over time)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Sent Segment Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__range])) / sum(increase(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Segment Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_txbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval])) / sum(rate(tetragon_socket_stats_txsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval])) / sum(rate(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__rate_interval]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Zero Windows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_zerowindow_total{cluster=~\"$cluster\", namespace=~\"$namespace_b\", workload=~\"$workload_b\", pod=~\"$pod_b\", dstnamespace=~\"$namespace_a\", dstworkload=~\"$workload_a\", dstpod=~\"$pod_a\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Received Segment Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__range])) / sum(increase(tetragon_socket_stats_rxsegs_total{cluster=~\"$cluster\", namespace=~\"$namespace_a\", workload=~\"$workload_a\", pod=~\"$pod_a\", dstnamespace=~\"$namespace_b\", dstworkload=~\"$workload_b\", dstpod=~\"$pod_b\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}