apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "l3l4networking"
  labels:
    app.kubernetes.io/version: 1.18.0-rc.2
spec:
  parser:
    udp:
      enable: true
      cgroup: true
      statsInterval: 60
    tcp:
      enable: true
      statsInterval: 60
    dns:
      enable: true
