// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Tetragon

// Code generated by protoc-gen-go-tetragon. DO NOT EDIT

package helpers

import (
	fmt "fmt"
	tetragon "github.com/cilium/tetragon/api/v1/tetragon"
	proto "google.golang.org/protobuf/proto"
)

// ResponseTypeString returns an event's type as a string
func ResponseTypeString(response *tetragon.GetEventsResponse) (string, error) {
	if response == nil {
		return "", fmt.Errorf("Response is nil")
	}

	event := response.Event
	if event == nil {
		return "", fmt.Errorf("Event is nil")
	}

	switch event.(type) {
	case *tetragon.GetEventsResponse_ProcessExec:
		return tetragon.EventType_PROCESS_EXEC.String(), nil
	case *tetragon.GetEventsResponse_ProcessConnect:
		return tetragon.EventType_PROCESS_CONNECT.String(), nil
	case *tetragon.GetEventsResponse_ProcessListen:
		return tetragon.EventType_PROCESS_LISTEN.String(), nil
	case *tetragon.GetEventsResponse_Tls:
		return tetragon.EventType_TLS.String(), nil
	case *tetragon.GetEventsResponse_ProcessExit:
		return tetragon.EventType_PROCESS_EXIT.String(), nil
	case *tetragon.GetEventsResponse_ProcessClose:
		return tetragon.EventType_PROCESS_CLOSE.String(), nil
	case *tetragon.GetEventsResponse_ProcessAccept:
		return tetragon.EventType_PROCESS_ACCEPT.String(), nil
	case *tetragon.GetEventsResponse_ProcessKprobe:
		return tetragon.EventType_PROCESS_KPROBE.String(), nil
	case *tetragon.GetEventsResponse_ProcessTracepoint:
		return tetragon.EventType_PROCESS_TRACEPOINT.String(), nil
	case *tetragon.GetEventsResponse_ProcessSockStats:
		return tetragon.EventType_PROCESS_SOCK_STATS.String(), nil
	case *tetragon.GetEventsResponse_ProcessHttp:
		return tetragon.EventType_PROCESS_HTTP.String(), nil
	case *tetragon.GetEventsResponse_InterfaceStats:
		return tetragon.EventType_INTERFACE_STATS.String(), nil
	case *tetragon.GetEventsResponse_ProcessDns:
		return tetragon.EventType_PROCESS_DNS.String(), nil
	case *tetragon.GetEventsResponse_ProcessNetworkBurst:
		return tetragon.EventType_PROCESS_NETWORK_BURST.String(), nil
	case *tetragon.GetEventsResponse_ProcessFile:
		return tetragon.EventType_PROCESS_FILE.String(), nil
	case *tetragon.GetEventsResponse_ProcessIpError:
		return tetragon.EventType_PROCESS_IP_ERROR.String(), nil
	case *tetragon.GetEventsResponse_ProcessLoader:
		return tetragon.EventType_PROCESS_LOADER.String(), nil
	case *tetragon.GetEventsResponse_ProcessNetworkWatermark:
		return tetragon.EventType_PROCESS_NETWORK_WATERMARK.String(), nil
	case *tetragon.GetEventsResponse_ProcessUprobe:
		return tetragon.EventType_PROCESS_UPROBE.String(), nil
	case *tetragon.GetEventsResponse_ProcessUdpSeqCheckError:
		return tetragon.EventType_PROCESS_UDP_SEQ_CHECK_ERROR.String(), nil
	case *tetragon.GetEventsResponse_ProcessFileExec:
		return tetragon.EventType_PROCESS_FILE_EXEC.String(), nil
	case *tetragon.GetEventsResponse_ProcessIcmp:
		return tetragon.EventType_PROCESS_ICMP.String(), nil
	case *tetragon.GetEventsResponse_ProcessRawsockCreate:
		return tetragon.EventType_PROCESS_RAWSOCK_CREATE.String(), nil
	case *tetragon.GetEventsResponse_ProcessRawsockClose:
		return tetragon.EventType_PROCESS_RAWSOCK_CLOSE.String(), nil
	case *tetragon.GetEventsResponse_ProcessSandboxSyscall:
		return tetragon.EventType_PROCESS_SANDBOX_SYSCALL.String(), nil
	case *tetragon.GetEventsResponse_ProcessThrottle:
		return tetragon.EventType_PROCESS_THROTTLE.String(), nil
	case *tetragon.GetEventsResponse_ProcessLsm:
		return tetragon.EventType_PROCESS_LSM.String(), nil
	case *tetragon.GetEventsResponse_Test:
		return tetragon.EventType_TEST.String(), nil
	case *tetragon.GetEventsResponse_RateLimitInfo:
		return tetragon.EventType_RATE_LIMIT_INFO.String(), nil

	}
	return "", fmt.Errorf("Unhandled response type %T", event)
}

// ResponseGetProcess returns a GetEventsResponse's process if it exists
func ResponseGetProcess(response *tetragon.GetEventsResponse) *tetragon.Process {
	if response == nil {
		return nil
	}

	event := response.Event
	if event == nil {
		return nil
	}

	return ResponseInnerGetProcess(event)
}

// ResponseInnerGetProcess returns a GetEventsResponse inner event's process if it exists
func ResponseInnerGetProcess(event tetragon.IsGetEventsResponse_Event) *tetragon.Process {
	switch ev := event.(type) {
	case *tetragon.GetEventsResponse_ProcessExec:
		return ev.ProcessExec.Process
	case *tetragon.GetEventsResponse_ProcessExit:
		return ev.ProcessExit.Process
	case *tetragon.GetEventsResponse_ProcessKprobe:
		return ev.ProcessKprobe.Process
	case *tetragon.GetEventsResponse_ProcessTracepoint:
		return ev.ProcessTracepoint.Process
	case *tetragon.GetEventsResponse_ProcessUprobe:
		return ev.ProcessUprobe.Process
	case *tetragon.GetEventsResponse_ProcessLsm:
		return ev.ProcessLsm.Process
	case *tetragon.GetEventsResponse_ProcessLoader:
		return ev.ProcessLoader.Process
	case *tetragon.GetEventsResponse_ProcessConnect:
		return ev.ProcessConnect.Process
	case *tetragon.GetEventsResponse_ProcessClose:
		return ev.ProcessClose.Process
	case *tetragon.GetEventsResponse_ProcessListen:
		return ev.ProcessListen.Process
	case *tetragon.GetEventsResponse_ProcessAccept:
		return ev.ProcessAccept.Process
	case *tetragon.GetEventsResponse_ProcessRawsockCreate:
		return ev.ProcessRawsockCreate.Process
	case *tetragon.GetEventsResponse_ProcessRawsockClose:
		return ev.ProcessRawsockClose.Process
	case *tetragon.GetEventsResponse_ProcessIcmp:
		return ev.ProcessIcmp.Process
	case *tetragon.GetEventsResponse_ProcessIpError:
		return ev.ProcessIpError.Process
	case *tetragon.GetEventsResponse_ProcessFile:
		return ev.ProcessFile.Process
	case *tetragon.GetEventsResponse_ProcessFileExec:
		return ev.ProcessFileExec.Process
	case *tetragon.GetEventsResponse_ProcessSockStats:
		return ev.ProcessSockStats.Process
	case *tetragon.GetEventsResponse_Tls:
		return ev.Tls.Process
	case *tetragon.GetEventsResponse_ProcessHttp:
		return ev.ProcessHttp.Process
	case *tetragon.GetEventsResponse_ProcessNetworkBurst:
		return ev.ProcessNetworkBurst.Process
	case *tetragon.GetEventsResponse_ProcessNetworkWatermark:
		return ev.ProcessNetworkWatermark.Process
	case *tetragon.GetEventsResponse_ProcessUdpSeqCheckError:
		return ev.ProcessUdpSeqCheckError.Process
	case *tetragon.GetEventsResponse_ProcessDns:
		return ev.ProcessDns.Process
	case *tetragon.GetEventsResponse_ProcessSandboxSyscall:
		return ev.ProcessSandboxSyscall.Process

	}
	return nil
}

// ResponseGetProcessKprobe returns a GetEventsResponse's process if it exists
func ResponseGetProcessKprobe(response *tetragon.GetEventsResponse) *tetragon.ProcessKprobe {
	if response == nil {
		return nil
	}

	return response.GetProcessKprobe()
}

// ResponseGetParent returns a GetEventsResponse's parent process if it exists
func ResponseGetParent(response *tetragon.GetEventsResponse) *tetragon.Process {
	if response == nil {
		return nil
	}

	event := response.Event
	if event == nil {
		return nil
	}

	return ResponseInnerGetParent(event)
}

// ResponseInnerGetParent returns a GetEventsResponse inner event's parent process if it exists
func ResponseInnerGetParent(event tetragon.IsGetEventsResponse_Event) *tetragon.Process {
	switch ev := event.(type) {
	case *tetragon.GetEventsResponse_ProcessExec:
		return ev.ProcessExec.Parent
	case *tetragon.GetEventsResponse_ProcessExit:
		return ev.ProcessExit.Parent
	case *tetragon.GetEventsResponse_ProcessKprobe:
		return ev.ProcessKprobe.Parent
	case *tetragon.GetEventsResponse_ProcessTracepoint:
		return ev.ProcessTracepoint.Parent
	case *tetragon.GetEventsResponse_ProcessUprobe:
		return ev.ProcessUprobe.Parent
	case *tetragon.GetEventsResponse_ProcessLsm:
		return ev.ProcessLsm.Parent
	case *tetragon.GetEventsResponse_ProcessConnect:
		return ev.ProcessConnect.Parent
	case *tetragon.GetEventsResponse_ProcessClose:
		return ev.ProcessClose.Parent
	case *tetragon.GetEventsResponse_ProcessListen:
		return ev.ProcessListen.Parent
	case *tetragon.GetEventsResponse_ProcessAccept:
		return ev.ProcessAccept.Parent
	case *tetragon.GetEventsResponse_ProcessRawsockCreate:
		return ev.ProcessRawsockCreate.Parent
	case *tetragon.GetEventsResponse_ProcessRawsockClose:
		return ev.ProcessRawsockClose.Parent
	case *tetragon.GetEventsResponse_ProcessIcmp:
		return ev.ProcessIcmp.Parent
	case *tetragon.GetEventsResponse_ProcessIpError:
		return ev.ProcessIpError.Parent
	case *tetragon.GetEventsResponse_ProcessFile:
		return ev.ProcessFile.Parent
	case *tetragon.GetEventsResponse_ProcessFileExec:
		return ev.ProcessFileExec.Parent
	case *tetragon.GetEventsResponse_ProcessSockStats:
		return ev.ProcessSockStats.Parent
	case *tetragon.GetEventsResponse_Tls:
		return ev.Tls.Parent
	case *tetragon.GetEventsResponse_ProcessHttp:
		return ev.ProcessHttp.Parent
	case *tetragon.GetEventsResponse_ProcessNetworkBurst:
		return ev.ProcessNetworkBurst.Parent
	case *tetragon.GetEventsResponse_ProcessNetworkWatermark:
		return ev.ProcessNetworkWatermark.Parent
	case *tetragon.GetEventsResponse_ProcessUdpSeqCheckError:
		return ev.ProcessUdpSeqCheckError.Parent
	case *tetragon.GetEventsResponse_ProcessDns:
		return ev.ProcessDns.Parent
	case *tetragon.GetEventsResponse_ProcessSandboxSyscall:
		return ev.ProcessSandboxSyscall.Parent

	}
	return nil
}

// ResponseTypeMap returns a map from event field names (e.g. "process_exec") to corresponding
// protobuf messages (e.g. &tetragon.ProcessExec{}).
func ResponseTypeMap() map[string]proto.Message {
	return map[string]proto.Message{
		"process_exec":                &tetragon.ProcessExec{},
		"process_connect":             &tetragon.ProcessConnect{},
		"process_listen":              &tetragon.ProcessListen{},
		"tls":                         &tetragon.Tls{},
		"process_exit":                &tetragon.ProcessExit{},
		"process_close":               &tetragon.ProcessClose{},
		"process_accept":              &tetragon.ProcessAccept{},
		"process_kprobe":              &tetragon.ProcessKprobe{},
		"process_tracepoint":          &tetragon.ProcessTracepoint{},
		"process_sock_stats":          &tetragon.ProcessSockStats{},
		"process_http":                &tetragon.ProcessHttp{},
		"interface_stats":             &tetragon.InterfaceStats{},
		"process_dns":                 &tetragon.ProcessDns{},
		"process_network_burst":       &tetragon.ProcessNetworkBurst{},
		"process_file":                &tetragon.ProcessFile{},
		"process_ip_error":            &tetragon.ProcessIpError{},
		"process_loader":              &tetragon.ProcessLoader{},
		"process_network_watermark":   &tetragon.ProcessNetworkWatermark{},
		"process_uprobe":              &tetragon.ProcessUprobe{},
		"process_udp_seq_check_error": &tetragon.ProcessUdpSeqCheckError{},
		"process_file_exec":           &tetragon.ProcessFileExec{},
		"process_icmp":                &tetragon.ProcessIcmp{},
		"process_rawsock_create":      &tetragon.ProcessRawsockCreate{},
		"process_rawsock_close":       &tetragon.ProcessRawsockClose{},
		"process_sandbox_syscall":     &tetragon.ProcessSandboxSyscall{},
		"process_throttle":            &tetragon.ProcessThrottle{},
		"process_lsm":                 &tetragon.ProcessLsm{},
		"test":                        &tetragon.Test{},
		"rate_limit_info":             &tetragon.RateLimitInfo{},
	}
}

// ProcessEventMap returns a map from event field names (e.g. "process_exec") to corresponding
// protobuf messages in a given tetragon.GetEventsResponse (e.g. response.GetProcessExec()).
func ProcessEventMap(response *tetragon.GetEventsResponse) map[string]any {
	return map[string]any{
		"process_exec":                response.GetProcessExec(),
		"process_connect":             response.GetProcessConnect(),
		"process_listen":              response.GetProcessListen(),
		"tls":                         response.GetTls(),
		"process_exit":                response.GetProcessExit(),
		"process_close":               response.GetProcessClose(),
		"process_accept":              response.GetProcessAccept(),
		"process_kprobe":              response.GetProcessKprobe(),
		"process_tracepoint":          response.GetProcessTracepoint(),
		"process_sock_stats":          response.GetProcessSockStats(),
		"process_http":                response.GetProcessHttp(),
		"interface_stats":             response.GetInterfaceStats(),
		"process_dns":                 response.GetProcessDns(),
		"process_network_burst":       response.GetProcessNetworkBurst(),
		"process_file":                response.GetProcessFile(),
		"process_ip_error":            response.GetProcessIpError(),
		"process_loader":              response.GetProcessLoader(),
		"process_network_watermark":   response.GetProcessNetworkWatermark(),
		"process_uprobe":              response.GetProcessUprobe(),
		"process_udp_seq_check_error": response.GetProcessUdpSeqCheckError(),
		"process_file_exec":           response.GetProcessFileExec(),
		"process_icmp":                response.GetProcessIcmp(),
		"process_rawsock_create":      response.GetProcessRawsockCreate(),
		"process_rawsock_close":       response.GetProcessRawsockClose(),
		"process_sandbox_syscall":     response.GetProcessSandboxSyscall(),
		"process_throttle":            response.GetProcessThrottle(),
		"process_lsm":                 response.GetProcessLsm(),
		"test":                        response.GetTest(),
		"rate_limit_info":             response.GetRateLimitInfo(),
	}
}
