{{- if .Values.integratedGrafana.enabled }}
# This template was created by following the steps:
# 1. Configure and deploy kube-prometheus-stack Helm chart
# 2. Use kubectl to retrieve YAML for Prometheus StatefulSet
# 3. Remove unnecessary parts: config reloader container, rules config,
#    web config, default values
# 4. Load Prometheus config from a ConfigMap
# 5. Template resources metadata - names, namespaces, labels
# 6. Final cleanup and comments
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prometheus.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "prometheus.name" . }}
  template:
    metadata:
      labels:
        # TODO: Set app.kubernetes.io/version to Prometheus version instead of Tetragon
        {{- include "prometheus.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "prometheus.name" . }}
      terminationGracePeriodSeconds: 600
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.55.0@sha256:378f4e03703557d1c6419e6caccf922f96e6d88a530f7431d66a4c4f4b1000fe
        args:
        - --config.file=/etc/prometheus/prometheus.yaml # config file from ConfigMap
        - --web.console.templates=/etc/prometheus/consoles
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.enable-lifecycle
        - --web.external-url=http://{{ include "prometheus.name" . }}:9090
        - --web.route-prefix=/
        - --storage.tsdb.retention.time=24h # time retention
        - --storage.tsdb.retention.size=4GiB # size retention - must be less than volume sizeLimit
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.wal-compression
        ports:
        - containerPort: 9090
          name: http-web
          protocol: TCP
        {{- with .Values.integratedGrafana.prometheus.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /-/healthy
            port: http-web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: http-web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /-/ready
            port: http-web
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 3
        volumeMounts:
        - mountPath: /prometheus
          name: prometheus-db
          subPath: prometheus-db
        - mountPath: /etc/prometheus
          name: config
          readOnly: true
      volumes:
      - name: prometheus-db
        emptyDir:
          sizeLimit: 5Gi
      - name: config
        configMap:
          name: {{ include "prometheus.name" . }}-config
{{- end }}
