{
 "title": "Tetragon / HTTP Golden Signals / Socket - Host Binaries",
 "tags": [
  "Tetragon",
  "networking"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tetragon_events_total, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"}, node)"
    }
   },
   {
    "name": "binary",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\"}, binary)"
    }
   },
   {
    "name": "dstdns",
    "label": "remote DNS name",
    "query": {
     "query": "query_result(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\"} or tetragon_socket_stats_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\"})"
    }
   },
   {
    "name": "host",
    "label": "Host header",
    "query": {
     "query": "label_values(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\"},host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\", host=~\"$host\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (5xx Responses) Rate (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\", code=~\"5..\"}[$__range])) / sum(increase(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Median Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (5xx Responses) Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\", code=~\"5..\"}[$__rate_interval])) / sum(rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration [s] histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration histogram over time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (le) (increase(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "By Node & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Errors (5xx Responses) Rate (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, (sum by (node, binary) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\", code=~\"5..\"}[$__rate_interval])) / sum by (namespace, workload, binary) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Median Duration (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.5, sum by (le, node, binary) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "P90 Duration (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.9, sum by (le, node, binary) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "P95 Duration (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.95, sum by (le, node, binary) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Remote DNS Name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Errors (5xx Responses) Rate (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, (sum by (dstdns) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\", code=~\"5..\"}[$__rate_interval])) / sum by (dstdns) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Median Duration (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.5, sum by (le, dstdns) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "P90 Duration (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.9, sum by (le, dstdns) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "P95 Duration (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.95, sum by (le, dstdns) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Host Header",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (host) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Errors (5xx Responses) Rate (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, (sum by (host) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\", code=~\"5..\"}[$__rate_interval])) / sum by (host) (rate(tetragon_http_response_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Median Duration (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.5, sum by (le, host) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "P90 Duration (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.9, sum by (le, host) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "P95 Duration (top 5)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, histogram_quantile(0.95, sum by (le, host) (rate(tetragon_http_stats_latency_bucket{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\", host=~\"$host\"}[$__rate_interval]))) > 0)",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  }
 ]
}