{
 "title": "Hubble Export Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cilium_version, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total flows exported",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hubble_flows_exported_total{cluster=~\"${cluster}\"}[$__range])) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Total exported",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hubble_flows_exported_bytes_total{cluster=~\"${cluster}\"}[$__range])) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Average flow export rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "flows/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_exported_total{cluster=~\"${cluster}\"}[$__range])) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Average export data rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_exported_bytes_total{cluster=~\"${cluster}\"}[$__range])) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Newest flow exported",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(hubble_flows_last_exported_timestamp{cluster=~\"$cluster\"}[$__range])) * 1000",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Newest flow age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(max_over_time(hubble_flows_last_exported_timestamp{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Flow export rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "flows/s" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_exported_total{cluster=~\"${cluster}\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Export rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_exported_bytes_total{cluster=~\"${cluster}\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Most recent flow age",
   "type": "timeseries",
   "description": "This is the maximum difference between the time and the timestamp of the most recent Flow exported across all Cilium pods.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max(max_over_time(hubble_flows_last_exported_timestamp{cluster=~\"${cluster}\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}