apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "dns"
spec:
  parser:
    udp:
      enable: true
      cgroup: true
      deleteIdleSocketInterval: 60
      disableEvents:
        disableListen: true
    dns:
      enable: true
