apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "nodeselector-internal-ip"
spec:
  nodeSelector:
    matchExpressions:
      - key: "tetragon.io/internal-ip"
        operator: In
        values: ["10.0.0.5", "10.0.0.6"]
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
