apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: tetragon-operator
    app.kubernetes.io/instance: tetragon
  name: tetragon-operator
spec:
  endpoints:
    - honorLabels: true
      path: /metrics
      port: metrics
      relabelings:
        - replacement: ${1}
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
  selector:
    matchLabels:
      app.kubernetes.io/name: tetragon-operator
      app.kubernetes.io/instance: tetragon
