apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tetragon-operator
    app.kubernetes.io/instance: tetragon
  name: tetragon-operator
spec:
  ports:
    - name: metrics
      port: 2113
      protocol: TCP
  selector:
    app.kubernetes.io/name: tetragon-operator
    app.kubernetes.io/instance: tetragon
  type: ClusterIP
