// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

package getalerts

import (
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"google.golang.org/protobuf/encoding/protojson"

	"github.com/cilium/tetragon/api/v1/tetragon"
	ossEncoder "github.com/cilium/tetragon/pkg/encoder"

	"github.com/isovalent/hubble-fgs/pkg/encoder"
)

var Options struct {
	Output         string
	AlertRuleNames []string
	CelExpression  []string
	Color          string
	Timestamps     bool
}

func New() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "getalerts",
		Short: "Stream alert events",
		Long:  "Stream alert events generated by matching AlertRules.",
		RunE: func(cmd *cobra.Command, _ []string) error {
			return getAlerts(cmd.OutOrStdout())
		},
	}

	flags := cmd.Flags()
	flags.StringVarP(&Options.Output, "output", "o", "json", "Output format (json, compact)")
	flags.StringArrayVar(&Options.AlertRuleNames, "alert-rule-names", nil, "Filter by alert rule name(s)")
	flags.StringArrayVar(&Options.CelExpression, "cel-expression", nil, "Filter by CEL expression(s)")
	flags.StringVar(&Options.Color, "color", "auto", "Colorize compact output (auto, always, never)")
	flags.BoolVar(&Options.Timestamps, "timestamps", false, "Include timestamps in compact output")

	return cmd
}

func getAlerts(w io.Writer) error {
	c, err := NewClient()
	if err != nil {
		return fmt.Errorf("failed to create gRPC client: %w", err)
	}
	defer c.Close()

	req := &tetragon.GetAlertsRequest{
		AlertRuleNames: Options.AlertRuleNames,
		CelExpression:  Options.CelExpression,
	}

	stream, err := c.Client.GetAlerts(c.Ctx, req)
	if err != nil {
		return fmt.Errorf("failed to call GetAlerts: %w", err)
	}

	enc := newAlertEncoder(w)
	for {
		alert, err := stream.Recv()
		if err != nil {
			if c.Ctx.Err() != nil {
				return nil
			}
			return fmt.Errorf("error receiving alert: %w", err)
		}
		if err := enc(alert); err != nil {
			fmt.Fprintf(os.Stderr, "failed to encode alert: %v\n", err)
		}
	}
}

// alertEncoder is a function that encodes a single Alert to the output.
type alertEncoder func(*tetragon.Alert) error

func newAlertEncoder(w io.Writer) alertEncoder {
	if Options.Output == "compact" {
		colorMode := ossEncoder.ColorMode(Options.Color)
		inner := encoder.NewEnterpriseEncoder(w, colorMode, Options.Timestamps)
		return func(alert *tetragon.Alert) error {
			prefix := ""
			if rule := alert.GetRule(); rule != nil {
				prefix = fmt.Sprintf("%-8s %s ", rule.GetSeverity(), rule.GetName())
			}
			return inner.EncodePrefix(prefix, alert.GetEvent())
		}
	}
	marshaler := protojson.MarshalOptions{UseProtoNames: true}
	return func(alert *tetragon.Alert) error {
		out, err := marshaler.Marshal(alert)
		if err != nil {
			return err
		}
		fmt.Fprintln(w, string(out))
		return nil
	}
}
