FROM docker.io/library/ubuntu:22.04 AS kvm-builder

# Install build dependencies
RUN apt-get -y update
RUN apt-get -y install sudo bash debootstrap
RUN apt-get clean autoclean

# Copy files over
RUN mkdir -p fgs-bin
RUN mkdir -p fgs-lib
COPY . .

# Build the KVM image in the container when run
SHELL ["bash", "-c"]
CMD bash ./scripts/mkroot.sh

# vi:ft=dockerfile
