FROM quay.io/isovalent/hubble-libbpf:v0.2.3 as libbpf-builder

FROM quay.io/isovalent/hubble-llvm:2020-12-29-45f6aa2 as clang-builder

FROM docker.io/library/ubuntu:20.04 AS kvm-builder

# Install build dependencies
RUN apt-get -y update
RUN apt-get -y install sudo bash debootstrap
RUN apt-get clean autoclean

# Copy files over
RUN mkdir -p fgs-bin
COPY --from=clang-builder /usr/local/bin/clang-11 fgs-bin/clang
COPY --from=clang-builder /usr/local/bin/llc fgs-bin
RUN mkdir -p fgs-lib
COPY --from=libbpf-builder /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so fgs-lib
COPY --from=libbpf-builder /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0 fgs-lib
COPY --from=libbpf-builder /go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0.2.0 fgs-lib
COPY . .

# Build the KVM image in the container when run
SHELL ["bash", "-c"]
CMD bash ./scripts/mkroot.sh

# vi:ft=dockerfile
