# Copyright (C) Isovalent, Inc. - All Rights Reserved.
#
# UBI container image build targets.
#  tetragon: build the standard release image, then the enterprise wrapper copies binaries into UBI base
#  aggregator/operator: build the regular Dockerfile with --build-arg BASE_IMAGE=<ubi>,
#    then layer labels and LICENSE on top via a thin enterprise wrapper Dockerfile

ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))/..
include $(ROOT_DIR)/Makefile.defs

DOCKER_IMAGE_TAG ?= latest
TARGET_ARCH ?= amd64
CONTAINER_ENGINE_ARGS ?=
DEBUG ?= 0

VERSION ?= $(shell cd $(ROOT_DIR) && (git describe --tags --always --exclude 'api/*' --exclude '*-codedrop' 2>/dev/null || git describe --tags --always --exclude '*-codedrop' 2>/dev/null || git describe --always 2>/dev/null || echo "UNKNOWN_GIT_VERSION!") | sed 's|^api/||')

# renovate: datasource=docker
UBI_IMAGE ?= registry.redhat.io/ubi9/ubi-minimal:9.7@sha256:42c0bdc0534c1465e623a193929a66e9abeb214c61c80c360d99a2a491b0336b

TETRAGON_UBI_IMAGE_NAME ?= isovalent/tetragon-ubi
AGGREGATOR_UBI_IMAGE_NAME ?= isovalent/tetragon-aggregator-ubi
OPERATOR_UBI_IMAGE_NAME ?= isovalent/tetragon-operator-ubi

.PHONY: image-ubi
image-ubi: ## Build the Tetragon agent UBI container image (2-stage).
	$(CONTAINER_ENGINE) build -t "${TETRAGON_UBI_IMAGE_NAME}-stage:${DOCKER_IMAGE_TAG}" \
		--build-arg DEBUG=${DEBUG} \
		--target release --platform=linux/${TARGET_ARCH} ${CONTAINER_ENGINE_ARGS} $(ROOT_DIR)
	$(CONTAINER_ENGINE) build -f $(ROOT_DIR)/enterprise/images/tetragon/Dockerfile \
		-t "${TETRAGON_UBI_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" \
		--build-arg SOURCE_IMAGE=${TETRAGON_UBI_IMAGE_NAME}-stage:${DOCKER_IMAGE_TAG} \
		--build-arg UBI_IMAGE=${UBI_IMAGE} \
		--build-arg VERSION=${VERSION} \
		--build-arg BUILD_DATE=$$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
		--platform=linux/${TARGET_ARCH} ${CONTAINER_ENGINE_ARGS} $(ROOT_DIR)
	@echo "Push like this when ready:"
	@echo "${CONTAINER_ENGINE} push ${TETRAGON_UBI_IMAGE_NAME}:$(DOCKER_IMAGE_TAG)"

.PHONY: image-aggregator-ubi
image-aggregator-ubi: ## Build the Tetragon aggregator UBI container image (2-stage).
	$(CONTAINER_ENGINE) build -f $(ROOT_DIR)/Dockerfile.aggregator \
		-t "${AGGREGATOR_UBI_IMAGE_NAME}-stage:${DOCKER_IMAGE_TAG}" \
		--build-arg BASE_IMAGE=${UBI_IMAGE} \
		--target release --platform=linux/${TARGET_ARCH} ${CONTAINER_ENGINE_ARGS} $(ROOT_DIR)
	$(CONTAINER_ENGINE) build -f $(ROOT_DIR)/enterprise/images/tetragon-aggregator/Dockerfile \
		-t "${AGGREGATOR_UBI_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" \
		--build-arg BASE_IMAGE=${AGGREGATOR_UBI_IMAGE_NAME}-stage:${DOCKER_IMAGE_TAG} \
		--build-arg VERSION=${VERSION} \
		--build-arg BUILD_DATE=$$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
		--platform=linux/${TARGET_ARCH} ${CONTAINER_ENGINE_ARGS} $(ROOT_DIR)
	@echo "Push like this when ready:"
	@echo "${CONTAINER_ENGINE} push ${AGGREGATOR_UBI_IMAGE_NAME}:$(DOCKER_IMAGE_TAG)"

.PHONY: image-operator-ubi
image-operator-ubi: ## Build the Tetragon operator UBI container image (2-stage).
	$(CONTAINER_ENGINE) build -f $(ROOT_DIR)/Dockerfile.operator \
		-t "${OPERATOR_UBI_IMAGE_NAME}-stage:${DOCKER_IMAGE_TAG}" \
		--build-arg BASE_IMAGE=${UBI_IMAGE} \
		--target release --platform=linux/${TARGET_ARCH} ${CONTAINER_ENGINE_ARGS} $(ROOT_DIR)
	$(CONTAINER_ENGINE) build -f $(ROOT_DIR)/enterprise/images/tetragon-operator/Dockerfile \
		-t "${OPERATOR_UBI_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" \
		--build-arg BASE_IMAGE=${OPERATOR_UBI_IMAGE_NAME}-stage:${DOCKER_IMAGE_TAG} \
		--build-arg VERSION=${VERSION} \
		--build-arg BUILD_DATE=$$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
		--platform=linux/${TARGET_ARCH} ${CONTAINER_ENGINE_ARGS} $(ROOT_DIR)
	@echo "Push like this when ready:"
	@echo "${CONTAINER_ENGINE} push ${OPERATOR_UBI_IMAGE_NAME}:$(DOCKER_IMAGE_TAG)"

.PHONY: images-ubi
images-ubi: image-ubi image-aggregator-ubi image-operator-ubi ## Build all UBI container images.
