{
 "title": "Tetragon High Level Health",
 "description": "High level overview dashboard for Tetragon Enterprise (part of Isovalent Platform). At a glance, should provide strong indicators of potential issues in the cluster. Indicators here are designed to provide opinionated thresholds on problematic Tetragon metrics.",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tetragon_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tetragon_build_info{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(tetragon_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "k", "label": "top k", "query": "8" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "💓 Tetragon Uptime (Kubernetes)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "ℹ️ High level health indicators on Tetragon components in a Kubernetes cluster, such as whether components are in a running state (i.e. not Pending/Crashing etc).\n\nNote: this section requires metrics exported by [kube-state-metrics](https://kubernetes.io/docs/concepts/cluster-administration/kube-state-metrics/).\n\n"
   }
  },
  {
   "title": "Tetragon version(s) running",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (version, time) (tetragon_build_info{cluster=~\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tetragon Pods Running State",
   "type": "timeseries",
   "description": "Tracks the running state of Tetragon Pods such as the Agent and the Operator. A non-zero number of not running Tetragon Pods could indicate the number of Pods that are crashing, cannot be scheduled (i.e. Pending), or having image pull issues, etc.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", phase!=\"Running\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} == 1 or kube_pod_container_status_waiting_reason{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0)",
     "legendFormat": "Agent not running"
    },
    {
     "expr": "count(kube_pod_container_status_running{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0)",
     "legendFormat": "Agent running"
    },
    {
     "expr": "count(kube_pod_status_phase{pod=~\"tetragon-operator-.+\", phase!=\"Running\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} == 1 or kube_pod_container_status_waiting_reason{pod=~\"tetragon-operator-.+\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0)",
     "legendFormat": "Operator not running"
    },
    {
     "expr": "count(kube_pod_container_status_running{pod=~\"tetragon-operator-.+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0)",
     "legendFormat": "Operator running"
    }
   ]
  },
  {
   "title": "Max Tetragon Pods in State",
   "type": "stat",
   "description": "Tracks the running state of Tetragon Pods such as the Agent and the Operator. A non-zero number of not running Tetragon Pods could indicate the number of Pods that are crashing, cannot be scheduled (i.e. Pending), or having image pull issues, etc.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time((count(kube_pod_status_phase{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", phase!=\"Running\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} == 1) or count(kube_pod_container_status_waiting_reason{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Agents not running"
    },
    {
     "expr": "max_over_time((count(kube_pod_container_status_running{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Agents running"
    },
    {
     "expr": "max_over_time((count(kube_pod_status_phase{pod=~\"tetragon-operator-.+\", phase!=\"Running\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} == 1) or count(kube_pod_container_status_waiting_reason{pod=~\"tetragon-operator-.+\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Operators not running"
    },
    {
     "expr": "max_over_time((count(kube_pod_container_status_running{pod=~\"tetragon-operator-.+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Operators running"
    }
   ]
  },
  {
   "title": "Max Tetragon Pods in State",
   "type": "stat",
   "description": "Tracks the running state of Tetragon Pods such as the Agent and the Operator. A non-zero number of not running Tetragon Pods could indicate the number of Pods that are crashing, cannot be scheduled (i.e. Pending), or having image pull issues, etc.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time((count(kube_pod_status_phase{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", phase!=\"Running\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} == 1) or count(kube_pod_container_status_waiting_reason{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Agents not running"
    },
    {
     "expr": "max_over_time((count(kube_pod_container_status_running{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Agents running"
    },
    {
     "expr": "max_over_time((count(kube_pod_status_phase{pod=~\"tetragon-operator-.+\", phase!=\"Running\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} == 1) or count(kube_pod_container_status_waiting_reason{pod=~\"tetragon-operator-.+\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Operators not running"
    },
    {
     "expr": "max_over_time((count(kube_pod_container_status_running{pod=~\"tetragon-operator-.+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Operators running"
    }
   ]
  },
  {
   "title": "Max Tetragon Pods in State",
   "type": "stat",
   "description": "Tracks the running state of Tetragon Pods such as the Agent and the Operator. A non-zero number of not running Tetragon Pods could indicate the number of Pods that are crashing, cannot be scheduled (i.e. Pending), or having image pull issues, etc.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time((count(kube_pod_status_phase{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", phase!=\"Running\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} == 1) or count(kube_pod_container_status_waiting_reason{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Agents not running"
    },
    {
     "expr": "max_over_time((count(kube_pod_container_status_running{pod=~\"tetragon-[0-9a-z]+\", container=\"tetragon\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Agents running"
    },
    {
     "expr": "max_over_time((count(kube_pod_status_phase{pod=~\"tetragon-operator-.+\", phase!=\"Running\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} == 1) or count(kube_pod_container_status_waiting_reason{pod=~\"tetragon-operator-.+\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Operators not running"
    },
    {
     "expr": "max_over_time((count(kube_pod_container_status_running{pod=~\"tetragon-operator-.+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0))[$__range:$__rate_interval])",
     "legendFormat": "Operators running"
    }
   ]
  },
  {
   "title": "Tetragon Pod Restarts (trailing 15 minutes)",
   "type": "timeseries",
   "description": "Displays Tetragon components that have restarted in the given time range.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (container) (increase(kube_pod_container_status_restarts_total{container=~\"tetragon.*\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[15m]))",
     "legendFormat": "{{container}} restarts"
    }
   ]
  },
  {
   "title": "Total Tetragon Pod Restarts",
   "type": "stat",
   "description": "Displays Tetragon components that have restarted in the given time range.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (container) (round(increase(kube_pod_container_status_restarts_total{container=~\"tetragon.*\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "{{container}} restarts"
    }
   ]
  },
  {
   "title": "Total Tetragon Pod Restarts",
   "type": "stat",
   "description": "Displays Tetragon components that have restarted in the given time range.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (container) (round(increase(kube_pod_container_status_restarts_total{container=~\"tetragon.*\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "{{container}} restarts"
    }
   ]
  },
  {
   "title": "Total Tetragon Pod Restarts",
   "type": "stat",
   "description": "Displays Tetragon components that have restarted in the given time range.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (container) (round(increase(kube_pod_container_status_restarts_total{container=~\"tetragon.*\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "{{container}} restarts"
    }
   ]
  },
  {
   "title": "📝 Tetragon Lost Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Lost Events Rate",
     "type": "timeseries",
     "description": "Rate of Lost Events per saturated component\n\nThis panel shows total count across all Tetragon agents.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_observer_ringbuf_events_lost_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "ringbuffer"
      },
      {
       "expr": "sum(rate(tetragon_observer_ringbuf_queue_events_lost_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "ringbuffer queue"
      }
     ]
    },
    {
     "title": "Total Lost Events (top k)",
     "type": "stat",
     "description": "Total Lost Events\n\nThis panel shows top k pods with the highest loss rates across all Tetragon agents. If you spot an outlier pod, you can select it in a dashboard filter for more insights.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, sum(round(increase(tetragon_observer_ringbuf_events_lost_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range]))) by (pod) + sum(round(increase(tetragon_observer_ringbuf_queue_events_lost_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range]))) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Lost Events (top k)",
     "type": "stat",
     "description": "Total Lost Events\n\nThis panel shows top k pods with the highest loss rates across all Tetragon agents. If you spot an outlier pod, you can select it in a dashboard filter for more insights.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 332 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, sum(round(increase(tetragon_observer_ringbuf_events_lost_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range]))) by (pod) + sum(round(increase(tetragon_observer_ringbuf_queue_events_lost_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range]))) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Lost Events (top k)",
     "type": "stat",
     "description": "Total Lost Events\n\nThis panel shows top k pods with the highest loss rates across all Tetragon agents. If you spot an outlier pod, you can select it in a dashboard filter for more insights.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 336 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, sum(round(increase(tetragon_observer_ringbuf_events_lost_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range]))) by (pod) + sum(round(increase(tetragon_observer_ringbuf_queue_events_lost_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range]))) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗄️ Tetragon BPF Maps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
     "options": {
      "content": "ℹ️ Tetragon uses BPF maps as a datastore.\n\n**These maps are fundamental to Tetragon's operations. If they reach capacity then related functionality may fail.**"
     }
    },
    {
     "title": "Total Map Utilization",
     "type": "timeseries",
     "description": "Utilization of BPF maps, which act as data stores for Tetragon.  \n\nHigh values can indicate overutilization of BPF maps and may lead to degradation of functionality. This graph calculates total utilization across all Tetragon nodes and it might not highlight outlier nodes with higher pressure.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(tetragon_map_entries{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", map!~\"tg_socket_tuple_map\"}) by (map) / sum(tetragon_map_capacity{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) by (map) or label_replace(sum(tetragon_inode_map_entries{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) / sum(tetragon_inode_map_max{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}), \"map\", \"hash_map_inode_alloc\", \"\", \"\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Map Utilization (current, top k)",
     "type": "stat",
     "description": "Utilization of BPF maps, which act as data stores for Tetragon.  \n\nHigh values can indicate overutilization of BPF maps and may lead to degradation of functionality. This graph shows top k maps with the highest utilization across all Tetragon nodes. If you spot an outlier pod, you can select it in a dashboard filter for more insights.\n\nLegend format:\n<map> : <policy (if applicable)> : <Tetragon pod>",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, tetragon_map_entries{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", map!~\"tg_socket_tuple_map\"} / tetragon_map_capacity{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} or label_replace(tetragon_inode_map_entries{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} / tetragon_inode_map_max{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}, \"map\", \"hash_map_inode_alloc\", \"\", \"\"))",
       "legendFormat": "{{map}}  : {{policy}} : {{pod}}"
      }
     ]
    },
    {
     "title": "Total Map Update Error Rate",
     "type": "timeseries",
     "description": "This is a low level indicator that provides a rate of errors Tetragon BPF code returned when updating BPF maps.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "errs/s" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_map_errors_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (map)",
       "legendFormat": "{{map}}"
      }
     ]
    },
    {
     "title": "Map Update Error Rate (current, top k)",
     "type": "stat",
     "description": "This is a low level indicator that provides a rate of errors Tetragon BPF code returned when updating BPF maps.\n\nLegend format:\n<map> : <Tetragon pod>",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "errs/s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, sum(rate(tetragon_map_errors_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (map, pod))",
       "legendFormat": "{{map}} : {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "📦 Tetragon Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    { "title": "Process Cache", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 } },
    {
     "title": "Total Process Cache Usage",
     "type": "timeseries",
     "description": "Number of entries in the process cache\n\nThis panel shows total usage across all Tetragon agents, so it might not highlight outlier nodes with higher pressure.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(tetragon_process_cache_size{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(tetragon_process_cache_capacity{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Process Cache Utilization per Agent (current, top k)",
     "type": "stat",
     "description": "Utilization of the process cache\n\nThis panel shows top k pods with the highest utilization across all Tetragon agents. If you spot an outlier pod, you can select it in a dashboard filter for more insights.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tetragon_process_cache_size{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} / tetragon_process_cache_capacity{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Process Cache Misses Rate",
     "type": "timeseries",
     "description": "Rate of misses when querying process cache\n\nThis panel shows total count across all Tetragon agents.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_process_cache_misses_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Process Cache Misses Rate per Agent (current, top k)",
     "type": "stat",
     "description": "Rate of misses when querying process cache\n\nThis panel shows top k pods with the highest miss rates across all Tetragon agents. If you spot an outlier pod, you can select it in a dashboard filter for more insights.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, sum(rate(tetragon_process_cache_misses_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Process Cache LRU Evictions Rate",
     "type": "timeseries",
     "description": "Rate of process cache LRU evictions\n\nThis panel shows total count across all Tetragon agents.\n",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_process_cache_evictions_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Cache LRU Evictions Rate per Agent (current, top k)",
     "type": "stat",
     "description": "Rate of process cache LRU evictions\n\nThis panel shows top k pods with the highest eviction rates across all Tetragon agents. If you spot an outlier pod, you can select it in a dashboard filter for more insights.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, sum(rate(tetragon_process_cache_evictions_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    { "title": "Event Cache", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 92 } },
    {
     "title": "Total Event Cache Entries",
     "type": "timeseries",
     "description": "Number of entries in the event cache",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tetragon_event_cache_entries{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Event Cache Inserts Rate",
     "type": "timeseries",
     "description": "Rate of inserts to the event cache\n\nThis panel shows total count across all Tetragon agents.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_event_cache_inserts_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event Cache Insert Rate per Agent (current, top k)",
     "type": "stat",
     "description": "Rate of inserts to the event cache\n\nThis panel shows top k pods with the highest insert rates across all Tetragon agents. If you spot an outlier pod, you can select it in a dashboard filter for more insights.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_event_cache_inserts_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Event Cache Fetch Failures Rate",
     "type": "timeseries",
     "description": "Number of failed fetches from the event cache. These won’t be retried as they already exceeded the limit.\n\nThis panel shows total count across all Tetragon agents.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_event_cache_fetch_failures_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (entry_type)",
       "legendFormat": "{{entry_type}}"
      }
     ]
    },
    {
     "title": "Event Cache Fetch Failures Rate per Agent (current, top k)",
     "type": "stat",
     "description": "Number of failed fetches from the event cache. These won’t be retried as they already exceeded the limit.\n\nThis panel shows top k pods with the highest failure rates across all Tetragon agents. If you spot an outlier pod, you can select it in a dashboard filter for more insights.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(tetragon_event_cache_fetch_failures_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "💻 Tetragon CPU/Memory Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
     "options": {
      "content": "ℹ️ Memory and CPU consumption of Tetragon components.\n\nFor more information about understanding Tetragon memory consumption, refer to [Tetragon Troubleshooting Documentation](https://docs.isovalent.com/operations-guide/tetragon/troubleshooting/index.html#understanding-tetragon-memory-consumption).\n\nNote: some panels in this section require metrics exported by [cAdvisor](https://github.com/google/cadvisor) (in Kubernetes they're provided by kubelet) and [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics)."
     }
    },
    {
     "title": "Tetragon Agent Container Memory Consumption (current, top k)",
     "type": "stat",
     "description": "Memory consumption of Tetragon agents",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, sum(container_memory_working_set_bytes{pod=~\"$pod\", pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", container=\"\", }) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tetragon Agent Container CPU Consumption (current, top k)",
     "type": "stat",
     "description": "CPU consumption of Tetragon agents",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", container=\"\", cpu=\"total\"}[$__rate_interval])) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Tetragon Agent Container Memory Consumption (top k)",
     "type": "timeseries",
     "description": "Memory consumption of Tetragon agents",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "topk($k, sum(container_memory_working_set_bytes{pod=~\"$pod\", pod=~\"tetragon-[0-9a-z]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", container=\"\"}) by (pod))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tetragon Agent Container CPU Consumption (top k)",
     "type": "timeseries",
     "description": "CPU consumption of Tetragon agents",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk($k, sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", container=\"\", cpu=\"total\"}[$__rate_interval])) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Tetragon Agent Container Memory Request Utilization",
     "type": "timeseries",
     "description": "This graph shows how close Tetragon Agent Pods are to their memory requests. By default Tetragon installs without explicit memory request - in which case nothing should be shown here. However, if Tetragon has a memory request set, this graph shows how much of their requests pods are using.\n\nFor more details about resource management in Kubernetes see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/.\n\nNote: this panel requires metrics exported by [kube-state-metrics](https://kubernetes.io/docs/concepts/cluster-administration/kube-state-metrics/).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by (pod, container)(container_memory_working_set_bytes{pod=~\"$pod\", pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})) / (sum by (pod, container) (kube_pod_container_resource_requests{pod=~\"$pod\", pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", resource=\"memory\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tetragon Agent CPU Runtime Latency (P50) (current, top k)",
     "type": "stat",
     "description": "This metric provides the 50th (i.e. median) percentile of Tetragon agent runtime scheduling.\n\nThis is related to CPU availability and utilization, high values or increases here denote in either throttling or lack of compute resources.\n\nHigh sustained runtime will likely indicate problems with Tetragon functionality.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, histogram_quantile(0.50, sum(rate(go_sched_latencies_seconds_bucket{pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le, pod)) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tetragon Agent CPU Runtime Latency (P95) (current, top k)",
     "type": "stat",
     "description": "This metric provides the 95th percentile of Tetragon agent runtime scheduling.\n\nThis is related to CPU availability and utilization, high values or increases here denote in either throttling or lack of compute resources.\n\nHigh sustained runtime will likely indicate problems with Tetragon functionality.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk($k, histogram_quantile(0.95, sum(rate(go_sched_latencies_seconds_bucket{pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le, pod)) )",
       "legendFormat": "{{pod}}: P95"
      }
     ]
    },
    {
     "title": "Tetragon Agent Container Memory Limit Utilization",
     "type": "timeseries",
     "description": "This graph shows how close Tetragon Agent Pods are to their memory limits. By default Tetragon installs without explicit memory limit - in which case nothing should be shown here. However, if Tetragon has a memory limit set, this graph shows how much of their limits pods are using.\n\nPods that hit their limit will be killed for running out of memory by the Linux host OS and can cause disruptions in functionality. Consistently high values here should indicate that you may want to increase limits.\n\nFor more details about resource management in Kubernetes see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/.\n\nNote: this panel requires metrics exported by [kube-state-metrics](https://kubernetes.io/docs/concepts/cluster-administration/kube-state-metrics/).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by (pod, container)(container_memory_working_set_bytes{pod=~\"$pod\", pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})) / (sum by (pod, container) (kube_pod_container_resource_limits{pod=~\"$pod\", pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", resource=\"memory\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tetragon Agent CPU Runtime Latency",
     "type": "timeseries",
     "description": "This metric provides the 95th and 50th (i.e. median) percentile of Tetragon agent runtime scheduling.\n\nThis is related to CPU availability and utilization, high values or increases here denote in either throttling or lack of compute resources.\n\nHigh sustained runtime will likely indicate problems with Tetragon functionality.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(go_sched_latencies_seconds_bucket{pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(go_sched_latencies_seconds_bucket{pod=~\"tetragon-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50"
      }
     ]
    }
   ]
  }
 ]
}