apiVersion: cilium.io/v1alpha1
kind: TetragonNetworkPolicy
metadata:
  name: "example-label-segmentation"
  annotations:
    author: "IsovalentQATeam"
spec:
  processSelector:
    operator: "In"
    values:
      - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
  defaultAction: "allow"
  rules:
  - description: "connectDenyRule"
    hook: "connect"
    action: "deny"
    destination:
    - ipBlock:
        cidr: "142.250.217.78/24" # google
      ports:
        protocol: "TCP"
    - FQDN:
      - "ebpf.io"
      - "tetragon.io"
      ports:
        protocol: "TCP"
        ports: [80, 8080]
