# This 'ptrace' Tracing Policy monitors any ptrace attempts and
# posts and event.
#
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "ptrace"
spec:
  kprobes:
  - call: "sys_ptrace"
    syscall: true
    args:
    - index: 0
      type: "int64"
    - index: 1
      type: "int64"
    - index: 2
      type: "uint64"
