apiVersion: cilium.io/v1alpha1
kind: TetragonNetworkPolicy
metadata:
  name: "example-label-segmentation"
  annotations:
    author: "IsovalentQATeam"
spec:
  podSelector:
    matchLabels:
      class: "xwing"
  processSelector:
    operator: "In"
    values:
      - "/usr/bin/curl"
      - "/usr/sbin/curl"
  defaultAction: "deny"
  rules:
  - hook: "connect"
    action: "allow"
    destination:
    - matchLabels:
        app.kubernetes.io/name: "deathstar"
      ports:
        protocol: "TCP"
        ports: [80, 8080]
    - fqdn:
      - "ebpf.io"
      - "tetragon.io"]
      ports:
        protocol: "TCP"
        ports: [80, 8080]
