apiVersion: cilium.io/v1alpha1
kind: TetragonNetworkPolicy
metadata:
  name: "example-label-segmentation"
  annotations:
    author: "IsovalentQATeam"
spec:
  podSelector:
    matchLabels:
      class: "xwing"
  defaultAction: "deny"
  rules:
  - hook: "connect"
    action: "allow"
    destination:
    - labels:
        matchLabels: ["org=empire"]
      ports:
        protocol: "TCP"
