---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fgs-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    debug: {{ .Values.debug }}
{{- if .Values.enableCiliumAPI }}
    enable-cilium-api: true
    cilium-bpf: /sys/fs/bpf/tc/globals/
{{- end }}
    enable-k8s-api: {{ .Values.enableK8sAPI }}
    enable-crd: {{ .Values.enableCRD }}
    export-file-compress: {{ .Values.exportFileCompress }}
    export-file-max-backups: {{ .Values.exportFileMaxBackups }}
    export-file-max-size-mb: {{ .Values.exportFileMaxSizeMB }}
{{- if .Values.exportFileRotationInterval }}
    export-file-rotation-interval: {{ .Values.exportFileRotationInterval }}
{{- end }}
    export-filename: {{ .Values.exportFilename }}
    metrics-server: {{ .Values.metricsServer }}
    process-cache-size: {{ .Values.processCacheSize }}
    procfs: {{ .Values.procFS }}
    tlstc: {{ .Values.enableTLSEvents }}
