package ops

import (
	"fmt"

	"github.com/cilium/tetragon/pkg/logger"
)

type OpCode int

// OpCodes must be in sync with iso_msg_ops enum in bpf/lib/iso_msg_types.h
// and should have a human-readable representation in OpCodeStrings.
const (
	MSG_OP_UNDEF = 0
	// The following events generate MsgTcpConnectUnix type events.

	// MSG_OP_TCPCONNECT event indicates a TCP connect() syscall
	// has been started. The event is generated on entry into a connect() call
	// and includes the info listed in `MsgTcpConnect`. It does _not_
	// imply the connect call will be successful and the 'Return' field
	// is undefined at this point. The event is disabled by default users
	// should use TCPCONNECTRET events which populate the 'Return' field.
	// The other fields `Kube`, `Common`, and `PID' will be populated using
	// data stored from exec() call of the associated pid.
	MSG_OP_TCPCONNECT = 1
	// MSG_OP_IPV5_TCPCONNECTRET event indicates a connect() syscall has
	// returned. The event populates the `MsgTcpConnect` and `Return`
	// codes. If the call is an asynchronous call the `Return` code will
	// indicate this. The other fields `Kube`, `Common`, and `PID' will
	// be populated using data stored from exec() call of the associated pid.
	MSG_OP_TCPCONNECTRET = 2
	// MSG_OP_BIND event indicates a bind() syscall has been issued.
	// This hook is placed behind the syscall in order to account for
	// kernel side generating ports and IP addresses when user does not
	// provide them. This event is not generated by default. By default
	// the bind() information is stored and only returned when the process
	// issues a subsequent listen() call. The other fields `Kube`, `Common`,
	// and `PID' will be populated using data stored from exec() call of
	// the associated pid.
	MSG_OP_BIND = 3
	// MSG_OP_LISTEN event indicates a listen() syscall has been issued.
	// This hook will generate an event including the information stored
	// from previous exec call and bind call.
	MSG_OP_LISTEN = 4
	// MSG_OP_EXECVE event indicates a process was created. The 'PID'
	// and 'Common' fields will be populated. This event is positioned
	// after exec() calls have been validated so failed syscalls will
	// not be reported. To generate events provide the '-e' option to
	// hubble-fgs, without the option the hook only populates the data
	// store for later use by above events.
	MSG_OP_EXECVE = 5

	MSG_OP_TLS = 6

	MSG_OP_EXIT = 7

	MSG_OP_TCPCLOSE = 8

	MSG_OP_ACCEPT = 9

	MSG_OP_CRED = 10

	MSG_OP_KFREE_SKB = 11

	MSG_OP_TLS_CONT = 12

	MSG_OP_GENERIC_KPROBE     = 13
	MSG_OP_GENERIC_TRACEPOINT = 14
	MSG_OP_GENERIC_UPROBE     = 15
	MSG_OP_GENERIC_LSM        = 16

	MSG_OP_UDPCLOSE   = 17
	MSG_OP_UDPCONNECT = 18
	MSG_OP_UDPSTATS   = 19

	MSG_OP_INTERFACE_STATS = 20

	MSG_OP_UDPPAYLOAD = 21

	MSG_OP_PROCESS_NETWORK_BURST = 22

	// MSG_OP_CLONE notifies user-space that a clone() event has occurred.
	MSG_OP_CLONE = 23

	MSG_OP_DATA = 24

	MSG_OP_CGROUP = 25

	MSG_OP_LOADER = 26

	MSG_OP_THROTTLE = 27

	MSG_OP_GENERIC_USDT = 28

	// just for testing
	MSG_OP_TEST = 254

	// for user space payload parsers
	MSG_OP_DNS = 128

	MSG_OP_FILE = 129

	MSG_OP_IP_ERROR = 130

	MSG_OP_FILE_RENAME = 131

	MSG_OP_PROCESS_NETWORK_WATERMARK = 132

	MSG_OP_UDP_SEQ_ERROR = 133

	MSG_OP_ICMP   = 134
	MSG_OP_ICMPV6 = 135

	MSG_OP_UDPLISTEN = 136

	MSG_OP_RAWSOCK_CREATE = 137
	MSG_OP_RAWSOCK_CLOSE  = 138

	MSG_OP_FILE_LINK    = 139
	MSG_OP_FILE_SYMLINK = 140
	MSG_OP_FILE_OPENRAW = 141

	// MSG_OP_TCPSTATS event report socket stats for TCP sockets.
	MSG_OP_TCPSTATS = 142

	MSG_OP_HTTP = 143

	// MSG_OP_EXIT event indicates a network namespace is being destroyed.
	MSG_OP_NETNS_EXIT = 144
)

var OpCodeStrings = map[OpCode]string{
	MSG_OP_UNDEF:                     "Undef",
	MSG_OP_TCPCONNECT:                "TCPConnect",
	MSG_OP_TCPCONNECTRET:             "TCPConnectReturn",
	MSG_OP_BIND:                      "TCPBind",
	MSG_OP_LISTEN:                    "TCPListen",
	MSG_OP_EXECVE:                    "Execve",
	MSG_OP_TLS:                       "TLS",
	MSG_OP_EXIT:                      "Exit",
	MSG_OP_TCPCLOSE:                  "TCPClose",
	MSG_OP_ACCEPT:                    "TCPAccept",
	MSG_OP_CRED:                      "Cred",
	MSG_OP_KFREE_SKB:                 "KfreeSkb",
	MSG_OP_TLS_CONT:                  "TLSCont",
	MSG_OP_GENERIC_KPROBE:            "GenericKprobe",
	MSG_OP_GENERIC_TRACEPOINT:        "GenericTracepoint",
	MSG_OP_TCPSTATS:                  "TCPStats",
	MSG_OP_HTTP:                      "HTTP",
	MSG_OP_UDPCLOSE:                  "UDPClose",
	MSG_OP_UDPCONNECT:                "UDPConnect",
	MSG_OP_UDPSTATS:                  "UDPStats",
	MSG_OP_INTERFACE_STATS:           "InterfaceStats",
	MSG_OP_UDPPAYLOAD:                "UDPPayload",
	MSG_OP_PROCESS_NETWORK_BURST:     "ProcessNetworkBurst",
	MSG_OP_CLONE:                     "Clone",
	MSG_OP_DATA:                      "Data",
	MSG_OP_NETNS_EXIT:                "NetNsExit",
	MSG_OP_TEST:                      "Test",
	MSG_OP_DNS:                       "DNS",
	MSG_OP_FILE:                      "File",
	MSG_OP_IP_ERROR:                  "IPError",
	MSG_OP_FILE_RENAME:               "FileRename",
	MSG_OP_PROCESS_NETWORK_WATERMARK: "ProcessNetworkWatermark",
	MSG_OP_UDP_SEQ_ERROR:             "UDPSeqError",
	MSG_OP_ICMP:                      "Icmp",
	MSG_OP_ICMPV6:                    "IcmpV6",
	MSG_OP_UDPLISTEN:                 "UDPListen",
	MSG_OP_RAWSOCK_CREATE:            "RawsockCreate",
	MSG_OP_RAWSOCK_CLOSE:             "RawsockClose",
	MSG_OP_FILE_LINK:                 "FileLink",
	MSG_OP_FILE_SYMLINK:              "FileSymlink",
	MSG_OP_FILE_OPENRAW:              "FileOpenraw",
}

func (op OpCode) String() string {
	s, ok := OpCodeStrings[op]
	if !ok {
		logger.GetLogger().Info("Unknown OpCode. This is a bug, please report it to Tetragon developers.", "opcode", op)
		return fmt.Sprintf("Unknown(%d)", op)
	}
	return s
}
