package ops

const (
	MSG_OP_UNDEF = 0
	// The following events generate MsgIPv4TcpConnectUnix type events.

	// MSG_OP_IPV4_TCPCONNECT event indicates a TCP connect() syscall
	// has been started. The event is generated on entry into a connect() call
	// and includes the info listed in `MsgIPv4TcpConnect`. It does _not_
	// imply the connect call will be successful and the 'Return' field
	// is undefined at this point. The event is disabled by default users
	// should use TCPCONNECTRET events which populate the 'Return' field.
	// The other fields `Kube`, `Common`, and `PID' will be populated using
	// data stored from exec() call of the associated pid.
	MSG_OP_IPV4_TCPCONNECT = 1
	// MSG_OP_IPV5_TCPCONNECTRET event indicates a connect() syscall has
	// returned. The event populates the `MsgIPv4TcpConnect` and `Return`
	// codes. If the call is an asynchronous call the `Return` code will
	// indicate this. The other fields `Kube`, `Common`, and `PID' will
	// be populated using data stored from exec() call of the associated pid.
	MSG_OP_IPV4_TCPCONNECTRET = 2
	// MSG_OP_IPV4_BIND event indicates a bind() syscall has been issued.
	// This hook is placed behind the syscall in order to account for
	// kernel side generating ports and IP addresses when user does not
	// provide them. This event is not generated by default. By default
	// the bind() information is stored and only returned when the process
	// issues a subsequent listen() call. The other fields `Kube`, `Common`,
	// and `PID' will be populated using data stored from exec() call of
	// the associated pid.
	MSG_OP_IPV4_BIND = 3
	// MSG_OP_IPV4_LISTEN event indicates a listen() syscall has been issued.
	// This hook will generate an event including the information stored
	// from previous exec call and bind call.
	MSG_OP_IPV4_LISTEN = 4
	// MSG_OP_EXECVE event indicates a process was created. The 'PID'
	// and 'Common' fields will be populated. This event is positioned
	// after exec() calls have been validated so failed syscalls will
	// not be reported. To generate events provide the '-e' option to
	// hubble-fgs, without the option the hook only populates the data
	// store for later use by above events.
	MSG_OP_EXECVE = 5

	MSG_OP_TLS = 6

	MSG_OP_EXIT = 7

	MSG_OP_IPV4_TCPCLOSE = 8

	MSG_OP_IPV4_ACCEPT = 9

	MSG_OP_CRED = 10

	MSG_OP_KFREE_SKB = 11

	MSG_OP_TLS_CONT = 12

	MSG_OP_GENERIC_KPROBE     = 13
	MSG_OP_GENERIC_TRACEPOINT = 14

	// MSG_OP_TCPSTATS event report socket stats for TCP sockets.
	MSG_OP_IPV4_TCPSTATS = 15

	MSG_OP_HTTP = 16

	MSG_OP_IPV4_UDPCLOSE   = 17
	MSG_OP_IPV4_UDPCONNECT = 18
	MSG_OP_IPV4_UDPSTATS   = 19

	MSG_OP_INTERFACE_STATS = 20

	MSG_OP_IPV4_UDPPAYLOAD = 21

	MSG_OP_IPV4_PROCESS_BURST = 22

	// MSG_OP_CLONE notifies user-space that a clone() event has occurred.
	MSG_OP_CLONE = 23

	// MSG_OP_DATA = 24 // defined in OSS

	// just for testing
	MSG_OP_TEST = 254

	// for user space payload parsers
	MSG_OP_IPV4_DNS = 128

	MSG_OP_FILE = 129
)

type OpCode int

const (
	MsgOpUndef                = iota
	MsgOpIPv4TCPConnect       = 1
	MsgOpIPv4TCPConnectReturn = 2
	MsgOpIPv4Bind             = 3
	MsgOpIPv4Listen           = 4
	MsgOpExecve               = 5
	MsgOpTLS                  = 6
	MsgOpExit                 = 7
	MsgOpIPv4TCPClose         = 8
	MsgOpIPv4Accept           = 9
	MsgOpCred                 = 10
	MsgOpKfreeSkb             = 11
	MsgOpTLSCont              = 12
	MsgOpGenericKprobe        = 13
	MsgOpGeneric_Tracepoint   = 14
	MsgOpIPv4TCPStats         = 15
	MsgOpHTTP                 = 16
	MsgOpIPv4UDPClose         = 17
	MsgOpIPv4UDPConnect       = 18
	MsgOpIPv4UDPStats         = 19
	MsgOpInterfaceStats       = 20
	MsgOpIPv4UDPPayload       = 21
	MsgOpIPv4ProcessBurst     = 22
	MsgOpClone                = 23
	MsgOpData                 = 24
	MsgOpTest                 = 254
	MsgOpIPv4DNS              = 128
	MsgOpFile                 = 129
)

func (op OpCode) String() string {
	opCodeMap := map[OpCode]string{
		MsgOpUndef:                "Undef",
		MsgOpIPv4TCPConnect:       "TCPConnect",
		MsgOpIPv4TCPConnectReturn: "TCPConnectReturn",
		MsgOpIPv4Bind:             "TCPBind",
		MsgOpIPv4Listen:           "TCPListen",
		MsgOpExecve:               "Execve",
		MsgOpTLS:                  "TLS",
		MsgOpExit:                 "Exit",
		MsgOpIPv4TCPClose:         "TCPClose",
		MsgOpIPv4Accept:           "TCPAccept",
		MsgOpCred:                 "Cred",
		MsgOpKfreeSkb:             "KfreeSkb",
		MsgOpTLSCont:              "TLSCont",
		MsgOpGenericKprobe:        "GenericKprobe",
		MsgOpGeneric_Tracepoint:   "GenericTracepoint",
		MsgOpIPv4TCPStats:         "TCPStats",
		MsgOpHTTP:                 "HTTP",
		MsgOpIPv4UDPClose:         "UDPClose",
		MsgOpIPv4UDPConnect:       "UDPConnect",
		MsgOpIPv4UDPStats:         "UDPStats",
		MsgOpInterfaceStats:       "InterfaceStats",
		MsgOpIPv4UDPPayload:       "UDPPayload",
		MsgOpIPv4ProcessBurst:     "ProcessNetworkBurst",
		MsgOpClone:                "Clone",
		MsgOpData:                 "Data",
		MsgOpTest:                 "Test",
		MsgOpIPv4DNS:              "DNS",
		MsgOpFile:                 "File",
	}
	if val, ok := opCodeMap[op]; ok {
		return val
	}
	return "undefOpCode"
}
