#
# Configures whether Tetragon pods run on the host network.
#
# IMPORTANT: Tetragon must be on the host network for the process visibility to
# function properly. However, S3 export does not work on the host network when used with
# kiam to assign a role due to a limitation in how kiam configures iptables rules to
# intercept requests to AWS metadata server.
#
# Set this flag to false if and only if you don't use the process visibility functionality
# and you use kiam to assign a role to upload events to S3.
#
# Reference: https://github.com/uswitch/kiam/issues/119
#
hostNetwork: true
tetragon:
  image:
    repository: artifactory.devhub-cloud.cisco.com/isovalent-iep-docker/tetragon
    tag: v1.20.0-pre.2
  metadata:
    enabled: false
    image:
      override: ~
      repository: quay.io/isovalent/hubble-enterprise-metadata
      tag: current
      # Override the global image pull policy.
      imagePullPolicy: Always
  alerts:
    # -- Enable alerts.
    enabled: true
    # -- Directory for alert JSON export (filenames will be retrieved from alert rule names).
    exportDirectory: "/var/log/tetragon"
    # -- Global filename for alert JSON export (instead of retrieving it from alert rule names).
    exportFilename: ""
  # -- EXPERIMENTAL: Enable Hubble flow export. When this value is not empty, Tetragon exports
  # ProcessConnect events as Hubble flow JSON in addition to exporting them as process_connect JSON.
  flowExportFilename: ""
  # Size in megabytes at which to rotate flow JSON export files.
  flowExportFileMaxSizeMB: 10
  # Number of rotated flow JSON export files to retain.
  flowExportFileMaxBackups: 5
  # Compress rotated flow JSON export files.
  flowExportFileCompress: false
  exportAllowList: |-
    {"event_set":["PROCESS_CONNECT", "PROCESS_EXEC", "PROCESS_FILE", "PROCESS_HTTP", "PROCESS_KPROBE", "PROCESS_LISTEN", "PROCESS_SANDBOX_SYSCALL", "PROCESS_TLS"]}
  exportDenyList: |-
    {"health_check":true}
    {"namespace":["", "cilium", "tetragon", "kube-system", "hubble-timescape"]}
  # -- Access Cilium API to associate Tetragon events with Cilium DNS cache.
  enableCiliumAPI: false
  # fimRuntimeEndpoint provides a custom container runtime endpoint for FIM (can be used only for containerd or cri-o)
  fimRuntimeEndpoint: ""
  # fimDispatcher provides the option to enable FIM dispatcher when supported (only path-based for now)
  fimDispatcher:
    enabled: false
  # Set --btf option to explicitly specify an absolute path to the metadata file. For advanced users only.
  btf: ""
  k8sWatcher:
    policy:
      # -- Enable watching Kubernetes API server for policy resources.
      # If true, Tetragon watches all supported policy resources:
      # TracingPolicy(Namespaced), SandboxPolicy(Namespaced), AlertRule and
      # TetragonNetworkPolicy(Namespaced), unless some of the features are
      # disabled by other options, or Kubernetes API server is disabled
      # entirely.
      enabled: true
  # -- Enable sandboxpolicies.
  enableSandboxpolicies: true
  # -- Enable process tree.
  enableProcessTree: false
  # -- Enable system call tracking in the process tree.
  enableSyscallTracking: false
  enableEvents:
    network: true
  # Layer3
  layer3:
    disabled: false
    bpfSocketCacheSize: 32768
    bpfWatermarksCacheSize: 32768
    tcp:
      enabled: false
      bpfSocketCacheSize: 32768
      statsInterval: 0s
      watermarks:
        enabled: false
        windowSizeMs: 0
        burstTriggerPercent: 0
        dipTriggerPercent: 0
      rtt:
        enabled: false
        min: 0
        max: 0
      metrics:
        enabled: true
        labelFilter: ""
      disableEvents: ""
    udp:
      enabled: false
      bpfSocketCacheSize: 32768
      cgroup: true
      statsInterval: 0s
      idleSocketTimeout: 2m
      inKernelManaged: false
      multicast:
        app: ""
        ports: ""
        seqCheck: false
        samplePercent: 0
      watermarks:
        enabled: false
        windowSizeMs: 0
        burstTriggerPercent: 0
        dipTriggerPercent: 0
      metrics:
        enabled: true
        labelFilter: ""
      disableEvents: ""
    icmp:
      enabled: false
      bpfSocketCacheSize: 32768
      v6info: false
      socketTracking: false
    igmp:
      enabled: false
    rawsock:
      enabled: false
      reportClose: false
      metrics:
        enabled: true
        labelFilter: ""
    watermarksExitGen:
      enabled: true
      interval: 1s
  # userspace DNS
  userDNS:
    enabled: false
    ports: ""
    reportQuestions: false
    metrics:
      enabled: true
      labelFilter: ""
  # HTTP
  http:
    enabled: false
    bpfContextCacheSize: 1000
    ports: ""
    http2Handling: true
    metrics:
      enabled: true
      labelFilter: ""
  # TLS
  tls:
    enabled: false
    bpfContextCacheSize: 32000
    mode: cgroup
    ports: ""
    metrics:
      enabled: true
      labelFilter: ""
  nop:
    enabled: false
    ports: ""
  networkInterfaceStats:
    enabled: false
    interval: 10s
  prometheus:
    metricsLabelFilter: "namespace,workload,binary"
  # EXPERIMENTAL: Publish metrics to AWS Sonar.
  # @ignored
  awsSonar:
    enabled: false
    region: ""
  dnsStatsPerSocket: false
  bpfDNSParser:
    # -- Enable in-kernel BPF DNS parser. A 5.15.0+ kernel is required.
    enabled: false
    # -- Enable in-kernel BPF DNS parser maps per Pod partitioning.
    perPod: false
    # -- Number of maps to preallocate at startup for BPF DNS parser maps per Pod partitioning.
    perPodPrealloc: 15
    # -- Threshold of free maps to keep at runtime for the BPF DNS parser maps per Pod partitioning.
    perPodThreshold: 5
  # -- Enable application model.
  enableApplicationModel: false
  # -- Cache size for application model.
  applicationModelCacheSize: 65536
  # -- Export filename for application model (e.g "application-model.log"). Set to empty
  # to disable exporting the application model.
  applicationModelExportFilename: ""
  # -- Interval at which to export application model.
  applicationModelExportInterval: 60s
  # Size in megabytes at which to rotate flow JSON export files.
  applicationModelExportFileMaxSizeMB: 25
  # Number of rotated flow JSON export files to retain.
  applicationModelExportFileMaxBackups: 1
  # Compress rotated flow JSON export files.
  applicationModelExportFileCompress: false
  # -- Whether to export complete application model objects or "fragments" that
  # can be reassembled into a complete application model. Using fragments is
  # desirable when there is a maximum message size limit when collecting
  # application model objects from tetragon agents and saving to a central
  # data store. Complete application model objects might hit this limit but
  # fragments would not.
  applicationModelExportFragments: false
  # -- Export filename for telemetry data (e.g "telemetry.log"). Set to empty
  # to disable. Note that tetragon.enableApplicationModel must be set to true
  # for Telemetry export to take effect. Telemetry export uses the export
  # interval specified by tetragon.applicationModelExportInterval value.
  telemetryExportFilename: ""
  # -- Export filename for connections log (e.g "connections.log"). Set to empty
  # to disable. Note that tetragon.enableApplicationModel must be set to true
  # for connections log export to take effect. Connections log export uses the export
  # interval specified by tetragon.applicationModelExportInterval value.
  connectionLogFilename: ""
# Tetragon Aggregator settings
tetragonAggregator:
  # -- Enables the Tetragon Aggregator.
  enabled: false
  # -- Annotations for the Tetragon Aggregator Deployment.
  annotations: {}
  # -- Annotations for the Tetragon Aggregator Deployment Pods.
  podAnnotations: {}
  # -- Extra labels to be added on the Tetragon Aggregator Deployment.
  extraLabels: {}
  # -- Extra labels to be added on the Tetragon Aggregator Deployment Pods.
  extraPodLabels: {}
  # -- priorityClassName for the Tetragon Aggregator Deployment Pods.
  priorityClassName: ""
  # -- securityContext for the Tetragon Aggregator Deployment Pods.
  securityContext: {}
  # -- securityContext for the Tetragon Aggregator Deployment Pod container.
  podSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - "ALL"
  # -- resources for the Tetragon Operator Deployment Pod container.
  resources: {}
  #limits:
  #  cpu: 500m
  #  memory: 128Mi
  #requests:
  #  cpu: 10m
  #  memory: 64Mi
  # -- resources for the Tetragon Aggregator Deployment update strategy
  strategy: {}
  # -- Steer the Tetragon Aggregator Deployment Pod placement via nodeSelector, tolerations and affinity rules.
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # -- tetragon-aggregator image.
  image:
    override: ~
    repository: artifactory.devhub-cloud.cisco.com/isovalent-iep-docker/tetragon-aggregator
    tag: v1.20.0-pre.2
    pullPolicy: IfNotPresent
  # -- Extra volumes for the Tetragon Aggregator Deployment.
  extraVolumes: []
  extraVolumeMounts: []
rthooks:
  image:
    repository: artifactory.devhub-cloud.cisco.com/isovalent-iep-docker/tetragon-rthooks
    tag: v1.20.0-pre.2
tetragonOperator:
  image:
    repository: artifactory.devhub-cloud.cisco.com/isovalent-iep-docker/tetragon-operator
    tag: v1.20.0-pre.2
  podInfo:
    # -- Enables the PodInfo CRD and the controller that reconciles PodInfo
    # custom resources.
    enabled: true
export:
  # Valid values: "stdout". Disabled by default, populate the value to enable.
  mode: ""
  extraArgs: {}
  extraEnv: []
  extraVolumeMounts: []
  securityContext: {}
  # Override the command. For advanced users only.
  commandOverride: []
  # Override the arguments. For advanced users only.
  argsOverride: []
  # filenames defines list of files for fluentd to tail and export.
  filenames:
    - tetragon.log
  stdout:
    image:
      override: ~
      repository: quay.io/isovalent/hubble-export-stdout
      tag: v1.1.1
# -- Deprecated: Install tracing policies.
# These options require the TracingPolicy CRD to be present in the cluster. Normally Tetragon CRDs are installed by
# either the Tetragon operator (which is installed by the same Helm chart) or by the same Helm chart
# (see crds.installMethod). This means we have a chicken-and-egg situation here. To avoid races, most users should
# disable tracing policies when first installing Tetragon Helm chart and enable them after CRDs are created.
# The default policies and the tracingPolicies.default values will be removed in the next release.
tracingPolicies:
  default:
    # -- Deprecated: Enable all default ruleset policies.
    enabled: false
    fim:
      # -- Deprecated: Enable the File Integrity Monitoring (FIM) policy.
      enabled: false
    network:
      # -- Deprecated: Enable the Network policy.
      enabled: false
    mount:
      # -- Deprecated: Enable the Changing Mounts and root filesystem policy.
      enabled: false
    osi:
      # -- Deprecated: Enable the Operating System Integrity (OSI) policy.
      enabled: false
    privileges:
      # -- Deprecated: Enable the Privileges monitoring policy.
      enabled: false
# -- Grafana dashboards, installed as ConfigMaps.
# They can be mounted in a Grafana deployment, or loaded automatically using the Grafana's sidecar for dashboards.
# See: https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-dashboards
# If integratedGrafana.enabled is true, all dashboards are installed,
# regardless of their individual enabled values.
dashboards:
  health:
    # -- Enable dashboards for monitoring Tetragon health and operations.
    enabled: false
    # -- Annotations to add to the dashboards ConfigMaps.
    annotations: {}
  network:
    # -- Enable dashboards for layer 3/4 networking.
    enabled: false
    # -- Annotations to add to the dashboards ConfigMaps.
    annotations: {}
  # -- Namespace to create the dashboards ConfigMaps in. Defaults to namespace of the Helm release.
  namespace: ~
  # -- Labels to add to the dashboards ConfigMaps. If using the dashboards sidecar, these
  # must include the label used for dashboards discovery.
  labels:
    grafana_dashboard: "1"
integratedGrafana:
  # -- Install Grafana with dashboards and lightweight Prometheus datasource.
  # It's intended to quickly set up Tetragon monitoring and/or get value out of
  # Tetragon without setting up a custom data pipeline.
  # If enabled, grafana automatically creates a secret named "$release-grafana"
  # storing "admin" user base64 encoded password.
  # Example command to retrieve the password:
  # kubectl get secret -n tetragon tetragon-grafana -o jsonpath='{.data.admin-password}' | base64 -d
  enabled: false
  prometheus:
    # -- Prometheus image
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v3.15.0
      sha: ~
      pullPolicy: IfNotPresent
    # -- Resources for the Prometheus container.
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
# Values for grafana subchart, used when integratedGrafana.enabled is true.
grafana:
  # @ignored
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          # Grafana subchart templates this value, so we can use {{ .Release.Name }} etc:
          # https://github.com/grafana/helm-charts/blob/563977e617b8f6861fadfe567c9dd399a4c8c054/charts/grafana/templates/_config.tpl#L45
          url: http://{{ include "prometheus.name" . }}:9090
          access: proxy
          isDefault: true
  # @ignored
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: tetragon-events
          folder: Tetragon Health
          options:
            path: /var/lib/grafana/dashboards/tetragon-events
        - name: tetragon-high-level-health
          folder: Tetragon Health
          options:
            path: /var/lib/grafana/dashboards/tetragon-high-level-health
        - name: tetragon-tcp-throughput-socket
          folder: Tetragon Network
          options:
            path: /var/lib/grafana/dashboards/tetragon-tcp-throughput-socket
        - name: tetragon-tcp-throughput-socket-host-binaries
          folder: Tetragon Network
          options:
            path: /var/lib/grafana/dashboards/tetragon-tcp-throughput-socket-host-binaries
        - name: tetragon-udp-throughput-socket
          folder: Tetragon Network
          options:
            path: /var/lib/grafana/dashboards/tetragon-udp-throughput-socket
        - name: tetragon-udp-throughput-socket-host-binaries
          folder: Tetragon Network
          options:
            path: /var/lib/grafana/dashboards/tetragon-udp-throughput-socket-host-binaries
  # @ignored
  dashboardsConfigMaps:
    # Grafana subchart templates these values, so we can use {{ .Release.Name }} etc:
    # https://github.com/grafana/helm-charts/blob/563977e617b8f6861fadfe567c9dd399a4c8c054/charts/grafana/templates/_pod.tpl#L1195
    # NOTE: Dashboards configmap will be mounted correctly only if it's
    # installed in the same namespace as Tetragon (see dashboards.namespace
    # value). If required, we can lift this limitation by installing two
    # configmaps in case both dashboards.namespace is set and
    # integratedGrafana.enabled is set to true.
    tetragon-events: "{{ .Release.Name }}-dashboard-events"
    tetragon-high-level-health: "{{ .Release.Name }}-dashboard-high-level-health"
    tetragon-tcp-throughput-socket: "{{ .Release.Name }}-dashboard-tcp-throughput-socket"
    tetragon-tcp-throughput-socket-host-binaries: "{{ .Release.Name }}-dashboard-tcp-throughput-socket-host-binaries"
    tetragon-udp-throughput-socket: "{{ .Release.Name }}-dashboard-udp-throughput-socket"
    tetragon-udp-throughput-socket-host-binaries: "{{ .Release.Name }}-dashboard-udp-throughput-socket-host-binaries"
  # -- Resources for the Grafana container.
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  # @ignored
  testFramework:
    enabled: false
# Values for kube-state-metrics subchart, used when integratedGrafana.enabled is true.
kube-state-metrics:
  # Enable only collectors needed by Tetragon dashboards.
  # @ignored
  collectors:
    - pods
  # -- Resources for the kube-state-metrics container.
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
splunk_hec:
  enabled: false
  # -- Namespace to create the otel collector ConfigMaps in. Defaults to namespace of the Helm release.
  namespace: ~
  image:
    override: ~
    repository: quay.io/isovalent/opentelemetry-collector-contrib
    tag: 0.161.0
    pullPolicy: IfNotPresent
  resources:
    requests: {cpu: "200m", memory: "256Mi"}
    limits: {cpu: "500m", memory: "512Mi"}
  # URL to a Splunk instance to send data to.
  endpoint:
    secretName: "splunk-hec"
    secretKey: "hec-endpoint"
  token:
    secretName: "splunk-hec"
    secretKey: "hec-token"
  index: ~
  # Disables gzip compression over HTTP.
  disable_compression: false
  # HTTP timeout when sending data. Defaults to 10s.
  timeout: 10s
  tls:
    # Retrieve TLS/mTLS details from externally lifecycled secret (must already exist in the same namespace).
    # defining the secret is mutually exclusive with including the ca, cert and key directly in the values file.
    # secret:
    #   name: "splunk-tls-user"
    #   # Define the keynames in the secret for CA cert, mTLS Client cert and mTLS Client key respectively.
    #   # CA Cert is required if TLS is enabled, insecureSkipVerify is false (Default) and Splunk endpoint cert is not signed by a trusted CA
    #   # Client cert and key are both required if mTLS is enabled and required on the splunk endpoint.
    #   keys:
    #     ca_cert: ca.crt
    #     client_cert: tls.crt
    #     client_key: tls.key
    # # Define ca cert to validate the HEC endpoint certificate when using HTTPS.  Specifying values inline is mutually exclusive with using the secret option.
    # ca: |
    #   -----BEGIN CERTIFICATE-----
    # # Define crt and key for mTLS authentication (if required by Splunk)
    # crt: |
    #   -----BEGIN CERTIFICATE-----
    # key: |
    #   -----BEGIN PRIVATE KEY-----
    # Whether to skip checking the certificate of the HEC endpoint when sending data over HTTPS. Defaults to false.
    insecureSkipVerify: false
