#
# Configures whether Tetragon pods run on the host network.
#
# IMPORTANT: Tetragon must be on the host network for the process visibility to
# function properly. However, S3 export does not work on the host network when used with
# kiam to assign a role due to a limitation in how kiam configures iptables rules to
# intercept requests to AWS metadata server.
#
# Set this flag to false if and only if you don't use the process visibility functionality
# and you use kiam to assign a role to upload events to S3.
#
# Reference: https://github.com/uswitch/kiam/issues/119
#
hostNetwork: true
tetragon:
  image:
    repository: quay.io/isovalent/tetragon
    tag: v1.15.0-pre.2
  metadata:
    enabled: false
    image:
      override: ~
      repository: quay.io/isovalent/hubble-enterprise-metadata
      tag: current
      # Override the global image pull policy.
      imagePullPolicy: Always
  # -- EXPERIMENTAL: Enable Hubble flow export. When this value is not empty, Tetragon exports
  # ProcessConnect events as Hubble flow JSON in addition to exporting them as process_connect JSON.
  flowExportFilename: ""
  # Size in megabytes at which to rotate flow JSON export files.
  flowExportFileMaxSizeMB: 10
  # Number of rotated flow JSON export files to retain.
  flowExportFileMaxBackups: 5
  # Compress rotated flow JSON export files.
  flowExportFileCompress: false
  exportAllowList: |-
    {"event_set":["PROCESS_CONNECT", "PROCESS_EXEC", "PROCESS_FILE", "PROCESS_HTTP", "PROCESS_KPROBE", "PROCESS_LISTEN", "PROCESS_SANDBOX_SYSCALL", "PROCESS_TLS"]}
  # -- Access Cilium API to associate Tetragon events with Cilium DNS cache.
  enableCiliumAPI: false
  # fimRuntimeEndpoint provides a custom container runtime endpoint for FIM (can be used only for containerd or cri-o)
  fimRuntimeEndpoint: ""
  # Set --btf option to explicitly specify an absolute path to the metadata file. For advanced users only.
  btf: ""
  # -- Enable sandboxpolicies.
  enableSandboxpolicies: true
  # -- Enable process tree.
  enableProcessTree: false
  prometheus:
    metricsLabelFilter: "namespace,workload,binary"
  # EXPERIMENTAL: Publish metrics to AWS Sonar.
  # @ignored
  awsSonar:
    enabled: false
    region: ""
  dnsStatsPerSocket: false
  # -- Enable in-kernel BPF DNS parser. A 5.15.0+ kernel is required.
  enableBPFDNSParser: false
tetragonOperator:
  image:
    repository: quay.io/isovalent/tetragon-operator
    tag: v1.15.0-pre.2
  podInfo:
    # -- Enables the PodInfo CRD and the controller that reconciles PodInfo
    # custom resources.
    enabled: true
export:
  # Valid values: "stdout". Disabled by default, populate the value to enable.
  mode: ""
  extraArgs: {}
  extraEnv: []
  extraVolumeMounts: []
  securityContext: {}
  # Override the command. For advanced users only.
  commandOverride: []
  # Override the arguments. For advanced users only.
  argsOverride: []
  # filenames defines list of files for fluentd to tail and export.
  filenames:
    - tetragon.log
  stdout:
    image:
      override: ~
      repository: quay.io/isovalent/hubble-export-stdout
      tag: v1.0.4
# -- Install tracing policies.
# These options require the TracingPolicy CRD to be present in the cluster. Normally Tetragon CRDs are installed by
# either the Tetragon operator (which is installed by the same Helm chart) or by the same Helm chart
# (see crds.installMethod). This means we have a chicken-and-egg situation here. To avoid races, most users should
# disable tracing policies when first installing Tetragon Helm chart and enable them after CRDs are created.
tracingPolicies:
  default:
    # -- Enable all default ruleset policies.
    enabled: false
    fim:
      # -- Enable File Integrity Monitoring (FIM) default policy.
      enabled: false
    network:
      # -- Enable Network default policy.
      enabled: false
    mount:
      # -- Enable Changing Mounts and root filesystem default policy.
      enabled: false
    osi:
      # -- Enable Operating System Integrity (OSI) default policy.
      enabled: false
    privileges:
      # -- Enable Privileges monitoring default policy.
      enabled: false
# -- Grafana dashboards, installed as ConfigMaps.
# They can be mounted in a Grafana deployment, or loaded automatically using the Grafana's sidecar for dashboards.
# See: https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-dashboards
# If integratedGrafana.enabled is true, all dashboards are installed,
# regardless of their individual enabled values.
dashboards:
  health:
    # -- Enable dashboards for monitoring Tetragon health and operations.
    enabled: false
    # -- Annotations to add to the dashboards ConfigMaps.
    annotations: {}
  network:
    # -- Enable dashboards for layer 3/4 networking.
    enabled: false
    # -- Annotations to add to the dashboards ConfigMaps.
    annotations: {}
  # -- Namespace to create the dashboards ConfigMaps in. Defaults to namespace of the Helm release.
  namespace: ~
  # -- Labels to add to the dashboards ConfigMaps. If using the dashboards sidecar, these
  # must include the label used for dashboards discovery.
  labels:
    grafana_dashboard: "1"
integratedGrafana:
  # -- Install Grafana with dashboards and lightweight Prometheus datasource.
  # It's intended to quickly set up Tetragon monitoring and/or get value out of
  # Tetragon without setting up a custom data pipeline.
  enabled: false
  prometheus:
    # -- Prometheus image
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v3.1.0
      sha: ~
      pullPolicy: IfNotPresent
    # -- Resources for the Prometheus container.
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
# Values for grafana subchart, used when integratedGrafana.enabled is true.
grafana:
  # Password for the admin user. Grafana subchart defaults to "admin", but then
  # Grafana prompts you to change it on the first login because it's insecure.
  # "tetragon" is a very secure password though, so Grafana is fine with it.
  adminPassword: tetragon
  # @ignored
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          # Grafana subchart templates this value, so we can use {{ .Release.Name }} etc:
          # https://github.com/grafana/helm-charts/blob/563977e617b8f6861fadfe567c9dd399a4c8c054/charts/grafana/templates/_config.tpl#L45
          url: http://{{ include "prometheus.name" . }}:9090
          access: proxy
          isDefault: true
  # @ignored
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: tetragon-events
          folder: Tetragon Health
          options:
            path: /var/lib/grafana/dashboards/tetragon-events
        - name: tetragon-high-level-health
          folder: Tetragon Health
          options:
            path: /var/lib/grafana/dashboards/tetragon-high-level-health
        - name: tetragon-tcp-throughput-socket
          folder: Tetragon Network
          options:
            path: /var/lib/grafana/dashboards/tetragon-tcp-throughput-socket
        - name: tetragon-tcp-throughput-socket-host-binaries
          folder: Tetragon Network
          options:
            path: /var/lib/grafana/dashboards/tetragon-tcp-throughput-socket-host-binaries
        - name: tetragon-udp-throughput-socket
          folder: Tetragon Network
          options:
            path: /var/lib/grafana/dashboards/tetragon-udp-throughput-socket
        - name: tetragon-udp-throughput-socket-host-binaries
          folder: Tetragon Network
          options:
            path: /var/lib/grafana/dashboards/tetragon-udp-throughput-socket-host-binaries
  # @ignored
  dashboardsConfigMaps:
    # Grafana subchart templates these values, so we can use {{ .Release.Name }} etc:
    # https://github.com/grafana/helm-charts/blob/563977e617b8f6861fadfe567c9dd399a4c8c054/charts/grafana/templates/_pod.tpl#L1195
    # NOTE: Dashboards configmap will be mounted correctly only if it's
    # installed in the same namespace as Tetragon (see dashboards.namespace
    # value). If required, we can lift this limitation by installing two
    # configmaps in case both dashboards.namespace is set and
    # integratedGrafana.enabled is set to true.
    tetragon-events: "{{ .Release.Name }}-dashboard-events"
    tetragon-high-level-health: "{{ .Release.Name }}-dashboard-high-level-health"
    tetragon-tcp-throughput-socket: "{{ .Release.Name }}-dashboard-tcp-throughput-socket"
    tetragon-tcp-throughput-socket-host-binaries: "{{ .Release.Name }}-dashboard-tcp-throughput-socket-host-binaries"
    tetragon-udp-throughput-socket: "{{ .Release.Name }}-dashboard-udp-throughput-socket"
    tetragon-udp-throughput-socket-host-binaries: "{{ .Release.Name }}-dashboard-udp-throughput-socket-host-binaries"
  # -- Resources for the Grafana container.
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  # @ignored
  testFramework:
    enabled: false
# Values for kube-state-metrics subchart, used when integratedGrafana.enabled is true.
kube-state-metrics:
  # Enable only collectors needed by Tetragon dashboards.
  # @ignored
  collectors:
    - pods
  # -- Resources for the kube-state-metrics container.
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
