{
 "title": "Tetragon Events Overview",
 "description": "Overview of events produced by Tetragon Enterprise (part of Isovalent Platform). It's designed to give users insights into Tetragon operations and workloads activity, and help configure things like resources or export filters.",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tetragon_events_total,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\",namespace=~\"$namespace\"},workload)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\",namespace=~\"$namespace\",workload=~\"$workload\"},pod)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"},node)"
    }
   },
   {
    "name": "binary",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\",namespace=~\"$namespace\",workload=~\"$workload\",pod=~\"$pod\",node=~\"$node\"},binary)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Generated Events by Type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Tetragon generates different types of events, depending on the policies loaded.\nEvents are then exposed via gRPC API and exported to a JSON log file.\n\nThis dashboard provides an overview of events generated by Tetragon.\nIt's intended mainly to help configure Tetragon and design a data pipeline consuming these events.\n\nBefore events are exported to a JSON log file, they pass through export filters,\nmeaning that the volume of exported events might be significantly smaller than the volume of generated events.\nSee the \"Export Insights\" section for a comparison.\nFor details on filtering, refer to [Tetragon Events Export Documentation](https://docs.isovalent.com/operations-guide/tetragon/configuration/export.html#filter-exported-tetragon-events).\n\nFor description and examples of each event type, refer to\n[Tetragon Events API Reference](https://docs.isovalent.com/user-guide/reference/events/index.html)."
   }
  },
  {
   "title": "Event Rate by Type (avg over time)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (type) (rate(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Event Rate (current)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Rate by Type (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Events by Type",
   "type": "piechart",
   "description": "Total number of events in the selected time range.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__range])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Generated Events by Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "Most Tetragon events are associated with a process.\nEvents are annotated with the process node and binary, as well as Kubernetes metadata: namespace, workload, pod.\n\nThis section highlists clusters, namespaces, workloads, nodes and binaries with the highest rate of generated events.\nIf you spot an outlier, you can select it in dashboard filters to see drill down by event type.\n\nNote: since events metrics can have high cardinality, Tetragon allows you to configure which metric labels are enabled\n(see [documentation](https://tetragon.io/docs/installation/metrics/#configure-labels-on-events-metrics)).\nIf relevant labels are disabled, this section will show limited information.\n"
   }
  },
  {
   "title": "Event Rate by Cluster (top 5, avg over time)",
   "type": "stat",
   "description": "Legend format:\n<cluster>",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (cluster) (rate(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__rate_interval])))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Event Rate by Node & Binary (top 5, avg over time)",
   "type": "stat",
   "description": "Legend format:\n<node> > <binary>",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (node, binary) (rate(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__rate_interval])))",
     "legendFormat": "{{node}} > {{binary}}"
    }
   ]
  },
  {
   "title": "Event Rate by K8s Namespace (top 5, avg over time)",
   "type": "stat",
   "description": "Legend format:\n<cluster> > <namespace>",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (cluster, namespace) (rate(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__rate_interval])))",
     "legendFormat": "{{cluster}} > {{namespace}}"
    }
   ]
  },
  {
   "title": "Event Rate by K8s Workload & Binary (top 5, avg over time)",
   "type": "stat",
   "description": "Legend format:\n<cluster> > <namespace>/<workload> > <binary>",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (cluster, namespace, workload, binary) (rate(tetragon_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workload=~\"$workload\", pod=~\"$pod\", node=~\"$node\", binary=~\"$binary\"}[$__rate_interval])))",
     "legendFormat": "{{cluster}} > {{namespace}}/{{workload}} > {{binary}}"
    }
   ]
  },
  { "title": "Event Export Insights (total)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 62 },
   "options": {
    "content": "Tetragon events are typically exported to a JSON log file.\n\nThis section provides an overview of the exported data.\nMetrics shown here are total counts for the selected cluster(s) - they don't recognize other filters.\n\nLarge volume of exported events might lead to high infrastructure cost and make it harder to extract valuable insights.\nCommon solutions include configuring export filters and rate limiting.\nFor guides on these refer to [Tetragon Events Export Documentation](https://docs.isovalent.com/operations-guide/tetragon/configuration/export.html).\n"
   }
  },
  {
   "title": "Exported Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_exported_bytes_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exported Bytes Rate (current)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_exported_bytes_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_events_exported_bytes_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_events_exported_bytes_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_events_exported_bytes_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generated vs Exported Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "produced"
    },
    {
     "expr": "sum(rate(tetragon_events_exported_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "exported"
    }
   ]
  },
  {
   "title": "Exported Event Rate (current)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "evt/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_exported_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_events_exported_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_events_exported_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_events_exported_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alert Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 85 },
   "options": {
    "content": "Tetragon alerts (AlertRules) trigger alerts based on evaluation of events against CEL expressions.\n\nThis section provides insights into the alert' operation and resource usage. \nMetrics shown here help monitor the volume of generated alerts and their exported data.\n\nLarge volumes of exported alert data might impact storage requirements and downstream processing.\nMonitor these metrics to ensure your alert configuration is efficient and properly sized.\n\nFor guidance on configuring alerts, see the [Tetragon Alert Rules Documentation](https://docs.isovalent.com/operations-guide/tetragon/alerts/)."
   }
  },
  {
   "title": "Total Loaded Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (severity) (tetragon_alert_rules_total{cluster=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Loaded Alerts per Severity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (severity) (tetragon_alert_rules_total{cluster=~\"$cluster\",severity=\"info\"})",
     "legendFormat": "Info"
    },
    {
     "expr": "max by (severity) (tetragon_alert_rules_total{cluster=~\"$cluster\",severity=\"warning\"})",
     "legendFormat": "Warning"
    },
    {
     "expr": "max by (severity) (tetragon_alert_rules_total{cluster=~\"$cluster\",severity=\"critical\"})",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Total Alerts CEL Compilation Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without (pod,instance,node,tetragon_pod) (tetragon_alert_rules_compilation_errors_total) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Alerts CEL Evaluation Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_alert_rules_evaluation_errors_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts with CEL Compilation Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(pod,instance,node,tetragon_pod) (tetragon_alert_rules_compilation_errors_total{cluster=~\"$cluster\"}) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts with CEL Evaluation Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(pod,instance,node,tetragon_pod) (tetragon_alert_rules_evaluation_errors_total{cluster=~\"$cluster\"}) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Triggered Alerts by Severity",
   "type": "piechart",
   "description": "Total number of alerts in the selected time range.",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_alert_rules_by_severity_total{cluster=~\"$cluster\",severity=\"info\"}[$__range]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(increase(tetragon_alert_rules_by_severity_total{cluster=~\"$cluster\",severity=\"warning\"}[$__range]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(increase(tetragon_alert_rules_by_severity_total{cluster=~\"$cluster\",severity=\"critical\"}[$__range]))",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Total Triggered Alerts (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 19, "x": 5, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (rule) (increase(tetragon_alert_rules_triggered_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exported Bytes Rate for Alerts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_alert_rules_exported_bytes_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exported Bytes Rate for Alerts (current)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_alert_rules_exported_bytes_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Bytes for Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_alert_rules_exported_bytes_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Bytes for Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_alert_rules_exported_bytes_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Bytes for Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(tetragon_alert_rules_exported_bytes_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generated Events vs. Exported Events vs. Exported Alerts Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_events_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Produced Events"
    },
    {
     "expr": "sum(rate(tetragon_events_exported_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Exported Events"
    },
    {
     "expr": "sum without(pod,instance,node,tetragon_pod,rule,severity)(rate(tetragon_alert_rules_triggered_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Exported Alerts"
    }
   ]
  },
  {
   "title": "Exported Alert Rate (current)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "evt/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod,instance,node,tetragon_pod,rule,severity)(rate(tetragon_alert_rules_triggered_total{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod,instance,node,tetragon_pod,rule,severity)(round(increase(tetragon_alert_rules_triggered_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod,instance,node,tetragon_pod,rule,severity)(round(increase(tetragon_alert_rules_triggered_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exported Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod,instance,node,tetragon_pod,rule,severity)(round(increase(tetragon_alert_rules_triggered_total{cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Rule Events Exported (by rule)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tetragon_alert_rules_events_exported_total{cluster=~\"$cluster\"}",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Alert Rule Rate Limit Active (by rule)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tetragon_alert_rules_rate_limit_active{cluster=~\"$cluster\"}",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Alert Rule Rate Limit Drops (by rule)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tetragon_alert_rules_rate_limit_drops_total{cluster=~\"$cluster\"}",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Alert Rule Rate Limit Window Usage (by rule)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "tetragon_alert_rules_rate_limit_window_usage{cluster=~\"$cluster\"}",
     "legendFormat": "{{rule}}"
    }
   ]
  }
 ]
}