#define __V61_BPF_PROG
#define __ENABLE_GLOB_SUPPORT
#include "bpf_file.h"
#include "dispatcher.h"
#include "getname.h"

char _license[] __attribute__((section("license"), used)) = "GPL";

struct {
	__uint(type, BPF_MAP_TYPE_LRU_HASH);
	__type(key, struct kpath_key);
	__type(value, int);
	__uint(max_entries, 4096);
} file_openraw_enforce_map SEC(".maps");

SEC("fentry/do_open")
int BPF_PROG(do_open, struct nameidata *nd, struct file *file, const struct open_flags *op)
{
	const char *uptr = BPF_CORE_READ(nd, name, uptr);
	__u32 flags = BPF_CORE_READ(op, open_flag);
	struct kpath_key map_key = {
		.ptr = (__u64)uptr,
		.pid_tgid = get_current_pid_tgid(),
	};
	struct kpath_val *kpath;
	__u32 operation = 0;
	int zero = 0;

	if (skip_access(BPF_CORE_READ(nd, inode)))
		return 0;

	if (!policy_filter_match())
		return 0;

	// find the user provided path
	// that was generated by getname hook
	kpath = map_lookup_elem(&open_user_to_kernel_path, &map_key);
	if (!kpath)
		return 0;

	operation = eval_selectors((struct sel_args){ .action = action_openraw, .flags = flags, .retval = 0x7FFFFFFF /* INT32_MAX */ }, 0, (struct sel_path){ kpath->str, kpath->size }, 0);
	if (!(operation & FILE_OP_BLOCK))
		return 0;

	// selector parsing indicates that we need to enforce this operation
	// first step is to fix the key by using the file pointer
	// and then add this to file_openraw_enforce_map that will be consumed
	// on another eBPF program and enforce the operation
	map_key.ptr = (__u64)file;
	map_update_elem(&file_openraw_enforce_map, &map_key, &zero, 0);

	return 0;
}

SEC("lsm/file_open")
int BPF_PROG(file_enforcer_open, struct file *file, int ret)
{
	struct kpath_key map_key = {
		.ptr = (__u64)file,
		.pid_tgid = get_current_pid_tgid(),
	};

	if (ret)
		return ret;

	// if we find that key in this map, we need to block that open call
	if (!map_lookup_elem(&file_openraw_enforce_map, &map_key))
		return 0;

	// we are done here, so cleanup that entry
	map_delete_elem(&file_openraw_enforce_map, &map_key);

	// block this operation
	return -EPERM;
}
