# We define a separate Tetragon ServiceMonitor instead of templating the one
# from the OSS chart to add extra labels and reset the scrape interval.
# TODO: Scrape only metrics used in dashboards.
{{- if .Values.observabilityStack.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tetragon-observability-tetragon
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tetragon-observability-tetragon
    app.kubernetes.io/part-of: tetragon-observability
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ include "tetragon.chart" . }}
    release: {{ .Release.Name }} # used by servicemonitor selector
spec:
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
      relabelings:
        - replacement: ${1}
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
        - replacement: ${1}
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: tetragon_pod
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- with .Values.serviceLabelsOverride}}
      {{- toYaml . | nindent 6 }}
      {{- else }}
      {{- include "tetragon.selectorLabels" . | nindent 6 }}
      {{- end }}
{{- end }}
