# This 'uid-git-changes' Tracing Policy monitors processes trying
# to change their uids/gids. If we want to reduce the noise we could match
# args to only post events that return without errors or only post events
# that try to set git/uid root. However we judge its interesting to know
# if failed attempts are done and/or if processes are changing uid/gid
# even if not to root.
#
#  __sys_setuid
#    - __x64_sys_setuid
#    - __ia32_sys_setuid
#    - __x64_sys_setuid16
#    - __ia32_sys_setuid16
#
#  __sys_setgid
#    - __x64_sys_setgid
#    - __ia32_sys_setgid
#    - __x64_sys_setgid16
#    - __ia32_sys_setgid16
#
#  __sys_setreuid
#    - __x64_sys_setreuid
#    - __ia32_sys_setreuid
#    - __x64_sys_setreuid16
#    - __ia32_sys_setreuid16
#
#  __sys_setregid
#    - __x64_sys_setregid
#    - __ia32_sys_setregid
#    - __x64_sys_setregid16
#    - __ia32_sys_setregid16
#
# __sys_setresuid
#    - __x64_sys_setresuid
#    - __ia32_sys_setresuid
#    - __x64_sys_setresuid16
#    - __ia32_sys_setresuid16
#
# __sys_setresgid
#    - __x64_sys_setresgid
#    - __ia32_sys_setresgid
#    - __x64_sys_setresgid16
#    - __ia32_sys_setresgid16
#
# __sys_setfsuid
#    - __x64_sys_setfsuid
#    - __ia32_sys_setfsuid
#    - __x64_sys_setfsuid16
#    - __ia32_sys_setfsuid16
#
# __sys_setfsgid
#    - __x64_sys_setfsgid
#    - __ia32_sys_setfsgid
#    - __x64_sys_setfsgid16
#    - __ia32_sys_setfsgid16
#

apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "privileges-setuid-root"
  labels:
    app.kubernetes.io/version: 1.14.0-pre.0
spec:
  kprobes:
    - call: "__sys_setuid"
      syscall: false
      args:
        - index: 0
          type: "int"
    - call: "__sys_setgid"
      syscall: false
      args:
        - index: 0
          type: "int"
    - call: "__sys_setreuid"
      syscall: false
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "int"
    - call: "__sys_setregid"
      syscall: false
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "int"
    - call: "__sys_setresuid"
      syscall: false
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "int"
        - index: 2
          type: "int"
    - call: "__sys_setresgid"
      syscall: false
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "int"
        - index: 2
          type: "int"
    - call: "__sys_setfsuid"
      syscall: false
      args:
        - index: 0
          type: "int"
    - call: "__sys_setfsgid"
      syscall: false
      args:
        - index: 0
          type: "int"
