// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

#include "vmlinux.h"
#include "bpf_igmp.h"

char _license[] __attribute__((section("license"), used)) = "GPL";
#ifdef VMLINUX_KERNEL_VERSION
int _version __attribute__((section(("version")), used)) =
	VMLINUX_KERNEL_VERSION;
#endif

// Handles IGMP joins
__attribute__((section("kprobe/__ip_mc_join_group"), used)) int
tg_ip_mc_join_group(struct pt_regs *ctx)
{
	struct ip_mreqn *imr = (struct ip_mreqn *)PT_REGS_PARM2(ctx);
	unsigned int mode = (unsigned int)PT_REGS_PARM3(ctx);
	struct sock *sk = (struct sock *)PT_REGS_PARM1(ctx);
	u64 cookie = (u64)sk;

	ip_mc_join_group(ctx, cookie, imr, mode);
	return 0;
}

// Handles IGMP leaves
__attribute__((section("kprobe/ip_mc_leave_group"), used)) int
tg_ip_mc_leave_group(struct pt_regs *ctx)
{
	struct ip_mreqn *imr = (struct ip_mreqn *)PT_REGS_PARM2(ctx);
	struct sock *sk = (struct sock *)PT_REGS_PARM1(ctx);
	u64 cookie = (u64)sk;

	ip_mc_leave_group(ctx, cookie, imr);
	return 0;
}

// Membership reports are generated by igmp_send_report() and igmpv3_send_report(). These are
// both subject to ISRA manipulations so are unsuitable for hooking. Instead, we hook the
// functions that call these, and there are only four.

// Responds to V1/V2 membership queries
// Can respond with V3 reports
__attribute__((section("kprobe/igmp_timer_expire"), used)) int
tg_igmp_timer_expire(struct pt_regs *ctx)
{
	struct timer_list *t = (struct timer_list *)PT_REGS_PARM1(ctx);

	igmp_timer_expire(ctx, t);
	return 0;
}

// Responds to V3 membership queries
__attribute__((section("kprobe/igmp_gq_timer_expire"), used)) int
tg_igmp_gq_timer_expire(struct pt_regs *ctx)
{
	struct timer_list *t = (struct timer_list *)PT_REGS_PARM1(ctx);

	igmp_gq_timer_expire(ctx, t);
	return 0;
}

// Triggered when a group is dropped as opposed to left. This happens when a process terminates
// without leaving the group.
__attribute__((section("kprobe/__igmp_group_dropped"), used)) int
tg_igmp_group_dropped(struct pt_regs *ctx)
{
	struct ip_mc_list *im = (struct ip_mc_list *)PT_REGS_PARM1(ctx);

	igmp_group_dropped(ctx, im);
	return 0;
}

// Triggered when an interface changes state.
__attribute__((section("kprobe/igmp_netdev_event"), used)) int
tg_igmp_netdev_event(struct pt_regs *ctx)
{
	unsigned long event = PT_REGS_PARM2(ctx);
	void *ptr = (void *)PT_REGS_PARM3(ctx);

	if (event == NETDEV_RESEND_IGMP)
		igmp_netdev_event(ctx, ptr);
	return 0;
}
