// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

#include "vmlinux.h"
#include "bpf_igmp.h"

volatile __CONST u16 TG_IGMPV3_MAX_PMCS = 128;
volatile __CONST u16 TG_IGMPV3_MAX_SOURCES = 256;

char _license[] __attribute__((section("license"), used)) = "GPL";
#ifdef VMLINUX_KERNEL_VERSION
int _version __attribute__((section(("version")), used)) =
	VMLINUX_KERNEL_VERSION;
#endif

// Handles IGMP joins
SEC("fentry/__ip_mc_join_group")
int BPF_PROG(tg_ip_mc_join_group, struct sock *sk, struct ip_mreqn *imr, unsigned int mode)
{
	u64 cookie = (u64)sk;

	ip_mc_join_group(ctx, cookie, imr, mode);
	return 0;
}

// Handles IGMP leaves
SEC("fentry/ip_mc_leave_group")
int BPF_PROG(tg_ip_mc_leave_group, struct sock *sk, struct ip_mreqn *imr)
{
	u64 cookie = (u64)sk;

	ip_mc_leave_group(ctx, cookie, imr);
	return 0;
}

// Membership reports are generated by igmp_send_report() and igmpv3_send_report(). These are
// both subject to ISRA manipulations so are unsuitable for hooking. Instead, we hook the
// functions that call these, and there are only four.

// Responds to V1/V2 membership queries
// Can respond with V3 reports
SEC("fentry/igmp_timer_expire")
int BPF_PROG(tg_igmp_timer_expire, struct timer_list *t)
{
	igmp_timer_expire(ctx, t);
	return 0;
}

// Responds to V3 membership queries
SEC("fentry/igmp_gq_timer_expire")
int BPF_PROG(tg_igmp_gq_timer_expire, struct timer_list *t)
{
	igmp_gq_timer_expire(ctx, t);
	return 0;
}

// Triggered when a group is dropped as opposed to left. This happens when a process terminates
// without leaving the group.
SEC("fentry/__igmp_group_dropped")
int BPF_PROG(tg_igmp_group_dropped, struct ip_mc_list *im, gfp_t gfp)
{
	igmp_group_dropped(ctx, im);
	return 0;
}

// Triggered when an interface changes state.
SEC("fentry/igmp_netdev_event")
int BPF_PROG(tg_igmp_netdev_event, struct notifier_block *this, unsigned long event, void *ptr)
{
	if (event == NETDEV_RESEND_IGMP)
		igmp_netdev_event(ctx, ptr);
	return 0;
}
