syntax = "proto3";

package proto.ha.v1;

option go_package = "github.com/isovalent/hubble-fgs/pkg/proto/ha/v1";

service Ha {
    rpc Adjacency(AdjRequest) returns (AdjResponse) {}
}

enum ADJ_RESPONSE_STATUS {
    ADJ_SUCCESS = 0;
    ADJ_FAILURE = 1;
    // add more errors here 
}

enum SERVICE_STATE {
    SVC_SUCCESS = 0;
    SVC_FAILURE = 1;
    SVC_UNKNOWN = 2;
}

enum HA_STATE {
    NO_HA = 0;
    HA_READY = 1;
    HA_NOTREADY = 2;
    HA_SWITCHOVER = 3;
}

enum MBR_STATE {
    HA_NA = 0;
    HA_OK = 1;
    HA_FAIL = 2;
}

message VrfInfo {
    string name = 1;
    uint32 id = 2;
    uint32 dpu = 3;
}

message VlanInfo {
    uint32 id = 1;
    uint32 dpu = 2;
}

message HaInfo {
    SERVICE_STATE service = 1;
    HA_STATE ha = 2;
}

message DpuVer {
    string name = 1;
    string version = 2;
}

message SysInfo {
    string ser_num = 1;
    string model = 2;
    string sw_ver = 3;
    string cpa = 4;
    repeated DpuVer dpus = 5;
    string lb_mode = 6;
}

message PolInfo {
    bool watching = 1;
    string revision = 2;
    string hash = 3;
}

message MbrInfo {
    SysInfo sys_info = 1;
    PolInfo pol_info = 2;
    HaInfo ha_info = 3;
    repeated VrfInfo vrf_info = 4;
    repeated VlanInfo vlan_info = 5;
}

message AdjRequest {
    string trace_id = 1;
    string ha_ip = 2;
    MbrInfo mbr_info = 3;
}

message AdjResponse {
    ADJ_RESPONSE_STATUS status = 1;
    string details = 2; // status details if error
    string trace_id = 3;
    MbrInfo mbr_info = 4;
}
