// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: pkg/proto/ha/v1/ha.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ADJ_RESPONSE_STATUS int32

const (
	ADJ_RESPONSE_STATUS_ADJ_SUCCESS ADJ_RESPONSE_STATUS = 0
	ADJ_RESPONSE_STATUS_ADJ_FAILURE ADJ_RESPONSE_STATUS = 1 // add more errors here
)

// Enum value maps for ADJ_RESPONSE_STATUS.
var (
	ADJ_RESPONSE_STATUS_name = map[int32]string{
		0: "ADJ_SUCCESS",
		1: "ADJ_FAILURE",
	}
	ADJ_RESPONSE_STATUS_value = map[string]int32{
		"ADJ_SUCCESS": 0,
		"ADJ_FAILURE": 1,
	}
)

func (x ADJ_RESPONSE_STATUS) Enum() *ADJ_RESPONSE_STATUS {
	p := new(ADJ_RESPONSE_STATUS)
	*p = x
	return p
}

func (x ADJ_RESPONSE_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ADJ_RESPONSE_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_ha_v1_ha_proto_enumTypes[0].Descriptor()
}

func (ADJ_RESPONSE_STATUS) Type() protoreflect.EnumType {
	return &file_pkg_proto_ha_v1_ha_proto_enumTypes[0]
}

func (x ADJ_RESPONSE_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ADJ_RESPONSE_STATUS.Descriptor instead.
func (ADJ_RESPONSE_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{0}
}

type SERVICE_STATE int32

const (
	SERVICE_STATE_SVC_SUCCESS SERVICE_STATE = 0
	SERVICE_STATE_SVC_FAILURE SERVICE_STATE = 1
	SERVICE_STATE_SVC_UNKNOWN SERVICE_STATE = 2
)

// Enum value maps for SERVICE_STATE.
var (
	SERVICE_STATE_name = map[int32]string{
		0: "SVC_SUCCESS",
		1: "SVC_FAILURE",
		2: "SVC_UNKNOWN",
	}
	SERVICE_STATE_value = map[string]int32{
		"SVC_SUCCESS": 0,
		"SVC_FAILURE": 1,
		"SVC_UNKNOWN": 2,
	}
)

func (x SERVICE_STATE) Enum() *SERVICE_STATE {
	p := new(SERVICE_STATE)
	*p = x
	return p
}

func (x SERVICE_STATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SERVICE_STATE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_ha_v1_ha_proto_enumTypes[1].Descriptor()
}

func (SERVICE_STATE) Type() protoreflect.EnumType {
	return &file_pkg_proto_ha_v1_ha_proto_enumTypes[1]
}

func (x SERVICE_STATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SERVICE_STATE.Descriptor instead.
func (SERVICE_STATE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{1}
}

type HA_STATE int32

const (
	HA_STATE_NO_HA         HA_STATE = 0
	HA_STATE_HA_READY      HA_STATE = 1
	HA_STATE_HA_NOTREADY   HA_STATE = 2
	HA_STATE_HA_SWITCHOVER HA_STATE = 3
)

// Enum value maps for HA_STATE.
var (
	HA_STATE_name = map[int32]string{
		0: "NO_HA",
		1: "HA_READY",
		2: "HA_NOTREADY",
		3: "HA_SWITCHOVER",
	}
	HA_STATE_value = map[string]int32{
		"NO_HA":         0,
		"HA_READY":      1,
		"HA_NOTREADY":   2,
		"HA_SWITCHOVER": 3,
	}
)

func (x HA_STATE) Enum() *HA_STATE {
	p := new(HA_STATE)
	*p = x
	return p
}

func (x HA_STATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HA_STATE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_ha_v1_ha_proto_enumTypes[2].Descriptor()
}

func (HA_STATE) Type() protoreflect.EnumType {
	return &file_pkg_proto_ha_v1_ha_proto_enumTypes[2]
}

func (x HA_STATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HA_STATE.Descriptor instead.
func (HA_STATE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{2}
}

type MBR_STATE int32

const (
	MBR_STATE_HA_NA   MBR_STATE = 0
	MBR_STATE_HA_OK   MBR_STATE = 1
	MBR_STATE_HA_FAIL MBR_STATE = 2
)

// Enum value maps for MBR_STATE.
var (
	MBR_STATE_name = map[int32]string{
		0: "HA_NA",
		1: "HA_OK",
		2: "HA_FAIL",
	}
	MBR_STATE_value = map[string]int32{
		"HA_NA":   0,
		"HA_OK":   1,
		"HA_FAIL": 2,
	}
)

func (x MBR_STATE) Enum() *MBR_STATE {
	p := new(MBR_STATE)
	*p = x
	return p
}

func (x MBR_STATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MBR_STATE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_ha_v1_ha_proto_enumTypes[3].Descriptor()
}

func (MBR_STATE) Type() protoreflect.EnumType {
	return &file_pkg_proto_ha_v1_ha_proto_enumTypes[3]
}

func (x MBR_STATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MBR_STATE.Descriptor instead.
func (MBR_STATE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{3}
}

type VrfInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Dpu  uint32 `protobuf:"varint,3,opt,name=dpu,proto3" json:"dpu,omitempty"`
}

func (x *VrfInfo) Reset() {
	*x = VrfInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfInfo) ProtoMessage() {}

func (x *VrfInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VrfInfo.ProtoReflect.Descriptor instead.
func (*VrfInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{0}
}

func (x *VrfInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VrfInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VrfInfo) GetDpu() uint32 {
	if x != nil {
		return x.Dpu
	}
	return 0
}

type VlanInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Dpu uint32 `protobuf:"varint,2,opt,name=dpu,proto3" json:"dpu,omitempty"`
}

func (x *VlanInfo) Reset() {
	*x = VlanInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VlanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanInfo) ProtoMessage() {}

func (x *VlanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanInfo.ProtoReflect.Descriptor instead.
func (*VlanInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{1}
}

func (x *VlanInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VlanInfo) GetDpu() uint32 {
	if x != nil {
		return x.Dpu
	}
	return 0
}

type HaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service SERVICE_STATE `protobuf:"varint,1,opt,name=service,proto3,enum=proto.ha.v1.SERVICE_STATE" json:"service,omitempty"`
	Ha      HA_STATE      `protobuf:"varint,2,opt,name=ha,proto3,enum=proto.ha.v1.HA_STATE" json:"ha,omitempty"`
}

func (x *HaInfo) Reset() {
	*x = HaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaInfo) ProtoMessage() {}

func (x *HaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaInfo.ProtoReflect.Descriptor instead.
func (*HaInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{2}
}

func (x *HaInfo) GetService() SERVICE_STATE {
	if x != nil {
		return x.Service
	}
	return SERVICE_STATE_SVC_SUCCESS
}

func (x *HaInfo) GetHa() HA_STATE {
	if x != nil {
		return x.Ha
	}
	return HA_STATE_NO_HA
}

type DpuVer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DpuVer) Reset() {
	*x = DpuVer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DpuVer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpuVer) ProtoMessage() {}

func (x *DpuVer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpuVer.ProtoReflect.Descriptor instead.
func (*DpuVer) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{3}
}

func (x *DpuVer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DpuVer) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SysInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SerNum string    `protobuf:"bytes,1,opt,name=ser_num,json=serNum,proto3" json:"ser_num,omitempty"`
	Model  string    `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	SwVer  string    `protobuf:"bytes,3,opt,name=sw_ver,json=swVer,proto3" json:"sw_ver,omitempty"`
	Cpa    string    `protobuf:"bytes,4,opt,name=cpa,proto3" json:"cpa,omitempty"`
	Dpus   []*DpuVer `protobuf:"bytes,5,rep,name=dpus,proto3" json:"dpus,omitempty"`
	LbMode string    `protobuf:"bytes,6,opt,name=lb_mode,json=lbMode,proto3" json:"lb_mode,omitempty"`
}

func (x *SysInfo) Reset() {
	*x = SysInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysInfo) ProtoMessage() {}

func (x *SysInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysInfo.ProtoReflect.Descriptor instead.
func (*SysInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{4}
}

func (x *SysInfo) GetSerNum() string {
	if x != nil {
		return x.SerNum
	}
	return ""
}

func (x *SysInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SysInfo) GetSwVer() string {
	if x != nil {
		return x.SwVer
	}
	return ""
}

func (x *SysInfo) GetCpa() string {
	if x != nil {
		return x.Cpa
	}
	return ""
}

func (x *SysInfo) GetDpus() []*DpuVer {
	if x != nil {
		return x.Dpus
	}
	return nil
}

func (x *SysInfo) GetLbMode() string {
	if x != nil {
		return x.LbMode
	}
	return ""
}

type PolInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Watching bool   `protobuf:"varint,1,opt,name=watching,proto3" json:"watching,omitempty"`
	Revision string `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Hash     string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *PolInfo) Reset() {
	*x = PolInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolInfo) ProtoMessage() {}

func (x *PolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolInfo.ProtoReflect.Descriptor instead.
func (*PolInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{5}
}

func (x *PolInfo) GetWatching() bool {
	if x != nil {
		return x.Watching
	}
	return false
}

func (x *PolInfo) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *PolInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type MbrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SysInfo  *SysInfo    `protobuf:"bytes,1,opt,name=sys_info,json=sysInfo,proto3" json:"sys_info,omitempty"`
	PolInfo  *PolInfo    `protobuf:"bytes,2,opt,name=pol_info,json=polInfo,proto3" json:"pol_info,omitempty"`
	HaInfo   *HaInfo     `protobuf:"bytes,3,opt,name=ha_info,json=haInfo,proto3" json:"ha_info,omitempty"`
	VrfInfo  []*VrfInfo  `protobuf:"bytes,4,rep,name=vrf_info,json=vrfInfo,proto3" json:"vrf_info,omitempty"`
	VlanInfo []*VlanInfo `protobuf:"bytes,5,rep,name=vlan_info,json=vlanInfo,proto3" json:"vlan_info,omitempty"`
}

func (x *MbrInfo) Reset() {
	*x = MbrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MbrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MbrInfo) ProtoMessage() {}

func (x *MbrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MbrInfo.ProtoReflect.Descriptor instead.
func (*MbrInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{6}
}

func (x *MbrInfo) GetSysInfo() *SysInfo {
	if x != nil {
		return x.SysInfo
	}
	return nil
}

func (x *MbrInfo) GetPolInfo() *PolInfo {
	if x != nil {
		return x.PolInfo
	}
	return nil
}

func (x *MbrInfo) GetHaInfo() *HaInfo {
	if x != nil {
		return x.HaInfo
	}
	return nil
}

func (x *MbrInfo) GetVrfInfo() []*VrfInfo {
	if x != nil {
		return x.VrfInfo
	}
	return nil
}

func (x *MbrInfo) GetVlanInfo() []*VlanInfo {
	if x != nil {
		return x.VlanInfo
	}
	return nil
}

type AdjRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	HaIp    string   `protobuf:"bytes,2,opt,name=ha_ip,json=haIp,proto3" json:"ha_ip,omitempty"`
	MbrInfo *MbrInfo `protobuf:"bytes,3,opt,name=mbr_info,json=mbrInfo,proto3" json:"mbr_info,omitempty"`
}

func (x *AdjRequest) Reset() {
	*x = AdjRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjRequest) ProtoMessage() {}

func (x *AdjRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjRequest.ProtoReflect.Descriptor instead.
func (*AdjRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{7}
}

func (x *AdjRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AdjRequest) GetHaIp() string {
	if x != nil {
		return x.HaIp
	}
	return ""
}

func (x *AdjRequest) GetMbrInfo() *MbrInfo {
	if x != nil {
		return x.MbrInfo
	}
	return nil
}

type AdjResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ADJ_RESPONSE_STATUS `protobuf:"varint,1,opt,name=status,proto3,enum=proto.ha.v1.ADJ_RESPONSE_STATUS" json:"status,omitempty"`
	Details string              `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"` // status details if error
	TraceId string              `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	MbrInfo *MbrInfo            `protobuf:"bytes,4,opt,name=mbr_info,json=mbrInfo,proto3" json:"mbr_info,omitempty"`
}

func (x *AdjResponse) Reset() {
	*x = AdjResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjResponse) ProtoMessage() {}

func (x *AdjResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ha_v1_ha_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjResponse.ProtoReflect.Descriptor instead.
func (*AdjResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ha_v1_ha_proto_rawDescGZIP(), []int{8}
}

func (x *AdjResponse) GetStatus() ADJ_RESPONSE_STATUS {
	if x != nil {
		return x.Status
	}
	return ADJ_RESPONSE_STATUS_ADJ_SUCCESS
}

func (x *AdjResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *AdjResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AdjResponse) GetMbrInfo() *MbrInfo {
	if x != nil {
		return x.MbrInfo
	}
	return nil
}

var File_pkg_proto_ha_v1_ha_proto protoreflect.FileDescriptor

var file_pkg_proto_ha_v1_ha_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x2f, 0x76,
	0x31, 0x2f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x22, 0x3f, 0x0a, 0x07, 0x56, 0x72, 0x66, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x70, 0x75, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x70, 0x75, 0x22, 0x2c, 0x0a, 0x08, 0x56, 0x6c, 0x61, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x70, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x64, 0x70, 0x75, 0x22, 0x65, 0x0a, 0x06, 0x48, 0x61, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x34, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x02, 0x68, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x41, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x52, 0x02, 0x68, 0x61, 0x22, 0x36, 0x0a,
	0x06, 0x44, 0x70, 0x75, 0x56, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xa3, 0x01, 0x0a, 0x07, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x15, 0x0a, 0x06, 0x73, 0x77, 0x5f, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x77, 0x56, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x61, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x70, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x70, 0x75, 0x56, 0x65, 0x72, 0x52, 0x04, 0x64, 0x70,
	0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x62, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x62, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x55, 0x0a, 0x07, 0x50,
	0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x22, 0xfe, 0x01, 0x0a, 0x07, 0x4d, 0x62, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f,
	0x0a, 0x08, 0x73, 0x79, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x2f, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x2c, 0x0a, 0x07, 0x68, 0x61, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x68, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f,
	0x0a, 0x08, 0x76, 0x72, 0x66, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x72, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x76, 0x72, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x32, 0x0a, 0x09, 0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x6c, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x76, 0x6c, 0x61, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x6d, 0x0a, 0x0a, 0x41, 0x64, 0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05,
	0x68, 0x61, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x49,
	0x70, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x62, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x62, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6d, 0x62, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0xad, 0x01, 0x0a, 0x0b, 0x41, 0x64, 0x6a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x44, 0x4a, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x62, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x62, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6d, 0x62, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x2a, 0x37, 0x0a, 0x13, 0x41, 0x44, 0x4a, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e,
	0x53, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x44, 0x4a,
	0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x44,
	0x4a, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x2a, 0x42, 0x0a, 0x0d, 0x53,
	0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x12, 0x0f, 0x0a, 0x0b,
	0x53, 0x56, 0x43, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x53, 0x56, 0x43, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x12, 0x0f,
	0x0a, 0x0b, 0x53, 0x56, 0x43, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x2a,
	0x47, 0x0a, 0x08, 0x48, 0x41, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x12, 0x09, 0x0a, 0x05, 0x4e,
	0x4f, 0x5f, 0x48, 0x41, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x41, 0x5f, 0x52, 0x45, 0x41,
	0x44, 0x59, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x41, 0x5f, 0x4e, 0x4f, 0x54, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x48, 0x41, 0x5f, 0x53, 0x57, 0x49, 0x54,
	0x43, 0x48, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x03, 0x2a, 0x2e, 0x0a, 0x09, 0x4d, 0x42, 0x52, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x41, 0x5f, 0x4e, 0x41, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x48, 0x41, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x48,
	0x41, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x32, 0x46, 0x0a, 0x02, 0x48, 0x61, 0x12, 0x40,
	0x0a, 0x09, 0x41, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6a, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x68, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x6a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x73, 0x6f, 0x76, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x2f, 0x68, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x2d,
	0x66, 0x67, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_ha_v1_ha_proto_rawDescOnce sync.Once
	file_pkg_proto_ha_v1_ha_proto_rawDescData = file_pkg_proto_ha_v1_ha_proto_rawDesc
)

func file_pkg_proto_ha_v1_ha_proto_rawDescGZIP() []byte {
	file_pkg_proto_ha_v1_ha_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ha_v1_ha_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_ha_v1_ha_proto_rawDescData)
	})
	return file_pkg_proto_ha_v1_ha_proto_rawDescData
}

var file_pkg_proto_ha_v1_ha_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pkg_proto_ha_v1_ha_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_ha_v1_ha_proto_goTypes = []interface{}{
	(ADJ_RESPONSE_STATUS)(0), // 0: proto.ha.v1.ADJ_RESPONSE_STATUS
	(SERVICE_STATE)(0),       // 1: proto.ha.v1.SERVICE_STATE
	(HA_STATE)(0),            // 2: proto.ha.v1.HA_STATE
	(MBR_STATE)(0),           // 3: proto.ha.v1.MBR_STATE
	(*VrfInfo)(nil),          // 4: proto.ha.v1.VrfInfo
	(*VlanInfo)(nil),         // 5: proto.ha.v1.VlanInfo
	(*HaInfo)(nil),           // 6: proto.ha.v1.HaInfo
	(*DpuVer)(nil),           // 7: proto.ha.v1.DpuVer
	(*SysInfo)(nil),          // 8: proto.ha.v1.SysInfo
	(*PolInfo)(nil),          // 9: proto.ha.v1.PolInfo
	(*MbrInfo)(nil),          // 10: proto.ha.v1.MbrInfo
	(*AdjRequest)(nil),       // 11: proto.ha.v1.AdjRequest
	(*AdjResponse)(nil),      // 12: proto.ha.v1.AdjResponse
}
var file_pkg_proto_ha_v1_ha_proto_depIdxs = []int32{
	1,  // 0: proto.ha.v1.HaInfo.service:type_name -> proto.ha.v1.SERVICE_STATE
	2,  // 1: proto.ha.v1.HaInfo.ha:type_name -> proto.ha.v1.HA_STATE
	7,  // 2: proto.ha.v1.SysInfo.dpus:type_name -> proto.ha.v1.DpuVer
	8,  // 3: proto.ha.v1.MbrInfo.sys_info:type_name -> proto.ha.v1.SysInfo
	9,  // 4: proto.ha.v1.MbrInfo.pol_info:type_name -> proto.ha.v1.PolInfo
	6,  // 5: proto.ha.v1.MbrInfo.ha_info:type_name -> proto.ha.v1.HaInfo
	4,  // 6: proto.ha.v1.MbrInfo.vrf_info:type_name -> proto.ha.v1.VrfInfo
	5,  // 7: proto.ha.v1.MbrInfo.vlan_info:type_name -> proto.ha.v1.VlanInfo
	10, // 8: proto.ha.v1.AdjRequest.mbr_info:type_name -> proto.ha.v1.MbrInfo
	0,  // 9: proto.ha.v1.AdjResponse.status:type_name -> proto.ha.v1.ADJ_RESPONSE_STATUS
	10, // 10: proto.ha.v1.AdjResponse.mbr_info:type_name -> proto.ha.v1.MbrInfo
	11, // 11: proto.ha.v1.Ha.Adjacency:input_type -> proto.ha.v1.AdjRequest
	12, // 12: proto.ha.v1.Ha.Adjacency:output_type -> proto.ha.v1.AdjResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_proto_ha_v1_ha_proto_init() }
func file_pkg_proto_ha_v1_ha_proto_init() {
	if File_pkg_proto_ha_v1_ha_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_ha_v1_ha_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ha_v1_ha_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VlanInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ha_v1_ha_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ha_v1_ha_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DpuVer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ha_v1_ha_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ha_v1_ha_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ha_v1_ha_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MbrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ha_v1_ha_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ha_v1_ha_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_ha_v1_ha_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_ha_v1_ha_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ha_v1_ha_proto_depIdxs,
		EnumInfos:         file_pkg_proto_ha_v1_ha_proto_enumTypes,
		MessageInfos:      file_pkg_proto_ha_v1_ha_proto_msgTypes,
	}.Build()
	File_pkg_proto_ha_v1_ha_proto = out.File
	file_pkg_proto_ha_v1_ha_proto_rawDesc = nil
	file_pkg_proto_ha_v1_ha_proto_goTypes = nil
	file_pkg_proto_ha_v1_ha_proto_depIdxs = nil
}
