{
 "title": "Tetragon / UDP Throughput / Socket - Host Binaries",
 "tags": [
  "Tetragon",
  "networking"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tetragon_events_total, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\"}, node)"
    }
   },
   {
    "name": "binary",
    "query": {
     "query": "label_values(tetragon_events_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\"}, binary)"
    }
   },
   {
    "name": "dstdns",
    "label": "remote DNS name",
    "query": {
     "query": "query_result(tetragon_socket_stats_udp_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\"} or tetragon_socket_stats_udp_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes Sent (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_udp_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_udp_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Received (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_udp_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_udp_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Sent (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pkt/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_udp_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pkt/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_udp_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Received (avg over time)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pkt/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_udp_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pkt/s" } },
   "targets": [
    {
     "expr": "sum(rate(tetragon_socket_stats_udp_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Sent Segment Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_udp_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range])) / sum(increase(tetragon_socket_stats_udp_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Sent Segment Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_udp_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) / sum(increase(tetragon_socket_stats_udp_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Received Segment Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_udp_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range])) / sum(increase(tetragon_socket_stats_udp_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Received Segment Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(tetragon_socket_stats_udp_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) / sum(increase(tetragon_socket_stats_udp_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket Drops per $__interval",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "topk(5, sum(increase(tetragon_socket_stats_udp_drops_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX by Node & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Sent (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (rate(tetragon_socket_stats_udp_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Segments Sent (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "pkt/s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (rate(tetragon_socket_stats_udp_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Avg Sent Segment Size (top 5)",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "topk(5, (sum by (node, binary) (increase(tetragon_socket_stats_udp_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) / sum by (node, binary) (increase(tetragon_socket_stats_udp_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RX by Node & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Received (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (rate(tetragon_socket_stats_udp_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Segments Received (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "pkt/s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (rate(tetragon_socket_stats_udp_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    },
    {
     "title": "Avg Received Segment Size (top 5)",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "topk(5, (sum by (node, binary) (increase(tetragon_socket_stats_udp_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) / sum by (node, binary) (increase(tetragon_socket_stats_udp_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval]))) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drops by Node & Binary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Socket Drops per $__interval",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "topk(5, sum by (node, binary) (increase(tetragon_socket_stats_udp_drops_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0)",
       "legendFormat": "{{node}} > {{binary}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TX by Remote DNS Name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Sent (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (rate(tetragon_socket_stats_udp_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Segments Sent (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "pkt/s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (rate(tetragon_socket_stats_udp_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Avg Sent Segment Size (top 5)",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "topk(5, (sum by (dstdns) (increase(tetragon_socket_stats_udp_txbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) / sum by (dstdns) (increase(tetragon_socket_stats_udp_txsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RX by Remote DNS Name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Received (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (rate(tetragon_socket_stats_udp_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Segments Received (top 5, avg over time)",
     "type": "stat",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pkt/s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (rate(tetragon_socket_stats_udp_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    },
    {
     "title": "Avg Received Segment Size (top 5)",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "topk(5, (sum by (dstdns) (increase(tetragon_socket_stats_udp_rxbytes_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) / sum by (dstdns) (increase(tetragon_socket_stats_udp_rxsegs_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval]))) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drops by Remote DNS Name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Socket Drops per $__interval",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "topk(5, sum by (dstdns) (increase(tetragon_socket_stats_udp_drops_total{cluster=~\"$cluster\", namespace=\"\", workload=\"\", pod=\"\", node=~\"$node\", binary=~\"$binary\", dstdns=~\"$dstdns\"}[$__interval])) > 0)",
       "legendFormat": "{{dstdns}}"
      }
     ]
    }
   ]
  }
 ]
}