# This tracing policy monitors kernel modules operations.
#
# Description:
#  This tracing policy reports loading of signed and unsigned modules
#
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "monitor-kernel-modules"
  annotations:
    author: "Isovalent"
  labels:
    app.kubernetes.io/version: 1.17.0-pre.4
spec:
  kprobes:
    # Automatic module loading detection
    # int security_kernel_module_request(char *kmod_name)
    - call: "security_kernel_module_request"
      syscall: false
      return: true
      args:
        - index: 0
          type: "string"
      returnArg:
        index: 0
        type: "int"
    - call: "security_kernel_read_file"
      # Explicit module loading using file descriptor finit_module() to print module full path
      syscall: false
      return: true
      args:
        - index: 0
          type: "file"
        - index: 1
          type: "int"
      returnArg:
        index: 0
        type: "int"
      selectors:
        - matchArgs:
            - index: 1
              operator: "Equal"
              values:
                - "2" # READING_MODULE
    # Explicit module loading using old deprecated init_module system call
    # int security_kernel_load_data(enum kernel_load_data_id id, bool contents)
    - call: "security_kernel_load_data"
      syscall: false
      return: true
      args:
        - index: 0
          type: "int"
      returnArg:
        index: 0
        type: "int"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "2" # READING_MODULE
