# This 'monitor-ptrace' Tracing Policy monitors any ptrace attempts and
# posts events.
#
# We consider ptrace as part of Operating System Integrity since
# if a process ptraces PID 1 it can panic the machine.
#
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "monitor-ptrace"
  annotations:
    author: "Isovalent"
  labels:
    app.kubernetes.io/version: 1.19.0-rc.1
spec:
  kprobes:
    - call: "sys_ptrace"
      syscall: true
      args:
        - index: 0
          type: "int64"
        - index: 1
          type: "int64"
        - index: 2
          type: "uint64"
