name: Nightly BPF regression test
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  bpf-nightly:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@master
        with:
          path: go/src/github.com/isovalent/hubble-fgs/
      - name: Run test
        id: run-test
        run: |
          docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }}
          sudo apt update
          sudo apt install libelf-dev cmake libdw-dev qemu-system-x86 llvm
          cd /home/runner/work/hubble-fgs/hubble-fgs/go/src/github.com/isovalent/hubble-fgs
          contrib/install-pahole.sh
          contrib/vmtest/test-bpf-latest.sh
