name: Build Tarballs

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
        description: "Git ref to build: tag, branch or commit SHA"
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        description: "Git ref to build (defaults to github.ref)"

jobs:
  build-tarballs:
    name: Build Tarballs (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest-4cores-16gb
            arch: amd64
          - os: ubuntu-22.04-arm64
            arch: arm64
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to Artifactory
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ vars.ARTIFACTORY_HOST }}
          username: ${{ vars.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Checkout Source Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.ref || github.ref }}
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Generate Tetragon Tarball Release
        run: |
          make tarball-release

      - name: Generate Tetragon Slim Tarball Release
        run: |
          make tarball-slim-release

      - name: Checksum Tetragon Tarball
        run: sha256sum -c tetragon-ee-*-${{ matrix.arch }}.tar.gz.sha256sum
        working-directory: ./release

      - name: Checksum Tetragon Slim Tarball
        run: sha256sum -c tetragon-slim-*-${{ matrix.arch }}.tar.gz.sha256sum
        working-directory: ./release

      - name: Upload Tetragon Tarball artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tetragon-tarball-${{ matrix.arch }}
          path: |
            release/tetragon-ee-*-${{ matrix.arch }}.tar.gz
            release/tetragon-ee-*-${{ matrix.arch }}.tar.gz.sha256sum
          retention-days: 5

      - name: Upload Tetragon Slim Tarball artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tetragon-slim-tarball-${{ matrix.arch }}
          path: |
            release/tetragon-slim-*-${{ matrix.arch }}.tar.gz
            release/tetragon-slim-*-${{ matrix.arch }}.tar.gz.sha256sum
          retention-days: 5
