name: Image CI Build

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "contrib/grafana/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-push:
    uses: ./.github/workflows/build-images-base.yml
    permissions:
      contents: read
      actions: read
      # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
      id-token: write
    with:
      sha: "${{ github.event.pull_request.head.sha }}"
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_ISOVALENT_DEV_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_ISOVALENT_DEV_PASSWORD }}
      QUAY_CHARTS_USERNAME: ${{ secrets.QUAY_ISOVALENT_CHARTS_DEV_USERNAME }}
      QUAY_CHARTS_PASSWORD: ${{ secrets.QUAY_ISOVALENT_CHARTS_DEV_PASSWORD }}

  build-and-push-ubi:
    uses: ./.github/workflows/build-images-ubi-base.yml
    permissions:
      contents: read
      actions: read
      id-token: write
    with:
      sha: "${{ github.event.pull_request.head.sha }}"
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_ISOVALENT_DEV_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_ISOVALENT_DEV_PASSWORD }}
      REDHAT_USERNAME_CI: ${{ secrets.REDHAT_USERNAME_CI }}
      REDHAT_PASSWORD_CI: ${{ secrets.REDHAT_PASSWORD_CI }}
