name: Packages Releases

on:
  push:
    tags:
      - v*

env:
  BUCKET_NAME : "isovalent-tetragon-enterprise-public"
  AWS_REGION : "us-west-2"

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: amd64
          - os: buildjet-2vcpu-ubuntu-2204-arm
            arch: arm64

    steps:
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Getting version tag
        id: tag
        run: |
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Checkout Source Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Generate Tetragon EE Tarball Release
        id: tetragon-tarball-release
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          make tarball-release

      - name: Checksum Tetragon EE Tarball
        run: sha256sum -c tetragon-*-${{ matrix.arch }}.tar.gz.sha256sum
        working-directory: ./release

      - name: Install AWC CLI for arm64
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        if: ${{ matrix.arch == 'arm64' }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::679388779924:role/tetragon-enterprise-github-actions
          role-session-name: tetragon-enterprise-s3-upload

      - name: Upload Tetragon EE Tarball to AWS s3
        run: |
          # new naming, 1.12 onwards
          # NB: before 1.12, we pushed to <bucket>/hubble-enterprise-standalone-tetragon
          aws s3 cp tetragon-*-${{ matrix.arch }}.tar.gz s3://${{ env.BUCKET_NAME }}/tetragon-enterprise-standalone-tarball/
          aws s3 cp tetragon-*-${{ matrix.arch }}.tar.gz.sha256sum s3://${{ env.BUCKET_NAME }}/tetragon-enterprise-standalone-tarball/
        working-directory: ./release
