name: Image CI Latest

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Latest ${{ matrix.is_lseg && '(LSEG)' || '' }} Images
    uses: ./.github/workflows/build-images-base.yml
    strategy:
      matrix:
        include:
          - is_lseg: true
          - is_lseg: false
    permissions:
      contents: read
      actions: read
      # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
      id-token: write
    with:
      is_lseg: ${{ matrix.is_lseg }}
      sha: "${{ github.sha }}"
      tag: latest
    secrets: inherit
