name: Image CI Latest

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    uses: ./.github/workflows/build-images-base.yml
    with:
      sha: "${{ github.sha }}"
      tag: latest
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_ISOVALENT_DEV_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_ISOVALENT_DEV_PASSWORD }}
