name: Image CI Releases

on:
  push:
    tags:
      - v*

permissions:
  # For softprops/action-gh-release draft release creation and artifact upload
  contents: write
  # For creating a PR to update the OLM catalog
  pull-requests: write

jobs:
  conf:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.conf.outputs.matrix }}
    steps:
      - name: Getting image tag
        id: tag
        run: |
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: generate matrix configuration
        id: conf
        shell: bash
        run: |
          truncate -s 0 /tmp/out
          if (echo ${{ steps.tag.outputs.tag }} | grep -q -e '^v1.12\|^v1.11\|^v1.10'); then
              echo "Build legacy matrix for ${{ steps.tag.outputs.tag }}"
              echo '{"name": "tetragon", "dockerfile": "./Dockerfile", "legacy-name": "hubble-enterprise"}' >> /tmp/out
              echo '{"name": "tetragon-operator", "dockerfile": "./Dockerfile.operator", "legacy-name": "hubble-enterprise-operator"}' >> /tmp/out
          else
              echo "Build matrix for ${{ steps.tag.outputs.tag }}"
              echo '{"name": "tetragon", "dockerfile": "./Dockerfile"}' >> /tmp/out
              echo '{"name": "tetragon-operator", "dockerfile": "./Dockerfile.operator"}' >> /tmp/out
          fi
          echo "matrix=$(jq -cs . </tmp/out)" | tee -a $GITHUB_OUTPUT

  build-and-push:
    needs: conf
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include: ${{ fromJSON(needs.conf.outputs.matrix) }}

    steps:
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
        with:
          platforms: arm64

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@aa33708b10e362ff993539393ff100fa93ed6a27 # v3.5.0

      - name: Login to quay.io
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Getting image tag
        id: tag
        run: |
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Checkout Source Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Legacy Release Build ${{ matrix.name }}
        if: ${{ matrix.legacy-name != '' }}
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        id: docker_build_release-legacy
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          target: release
          tags: |
            quay.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ steps.tag.outputs.tag }}
            quay.io/${{ github.repository_owner }}/${{ matrix.legacy-name }}:${{ steps.tag.outputs.tag }}

      - name: Legacy Image Release Digest
        if: ${{ matrix.legacy-name != '' }}
        shell: bash
        run: |
          mkdir -p image-digest/
          job_name=${{ matrix.name }}
          job_name_capital=${job_name^^}
          job_name_underscored=${job_name_capital//-/_}
          echo "${job_name_underscored}_DIGEST := \"${{ steps.docker_build_release-legacy.outputs.digest }}\"" > image-digest/makefile-digest.txt

          echo "### ${{ matrix.name }}" > image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt
          echo "\`quay.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ steps.tag.outputs.tag }}@${{ steps.docker_build_release-legacy.outputs.digest }}\`" >> image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt

      - name: Release Build ${{ matrix.name }}
        if: ${{ matrix.legacy-name == '' }}
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        id: docker_build_release
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          target: release
          tags: |
            quay.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ steps.tag.outputs.tag }}

      - name: Image Release Digest
        if: ${{ matrix.legacy-name == '' }}
        shell: bash
        run: |
          mkdir -p image-digest/
          job_name=${{ matrix.name }}
          job_name_capital=${job_name^^}
          job_name_underscored=${job_name_capital//-/_}
          echo "${job_name_underscored}_DIGEST := \"${{ steps.docker_build_release.outputs.digest }}\"" > image-digest/makefile-digest.txt

          echo "### ${{ matrix.name }}" > image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt
          echo "\`quay.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ steps.tag.outputs.tag }}@${{ steps.docker_build_release.outputs.digest }}\`" >> image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: image-digest ${{ matrix.name }}
          path: image-digest
          retention-days: 1

  # The ClusterServiceVersion part of the bundle is dependent on the previous builds as it needs to be updated with the image digests
  # produced during these builds.
  # The bundle is just a bunch of manifests, no binary, there is no need for a multi-arch build. It is already platform independent.
  # The context needs to be passed to the build.
  # => hence a separate job
  bundle-build-and-push:
    needs: build-and-push
    runs-on: ubuntu-22.04
    steps:
      - name: Getting image tag
        id: tag
        run: |
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "minor=$(echo ${GITHUB_REF##*/} | cut -d. -f-2)" >> $GITHUB_OUTPUT

      - name: Legacy check
        id: legacy
        shell: bash
        run: |
          if (echo ${{ steps.tag.outputs.tag }} | grep -q -e '^v1.12\|^v1.11\|^v1.10'); then
            echo "is=true" >> $GITHUB_OUTPUT
          else
            echo "is=false" >> $GITHUB_OUTPUT
          fi
        
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        if: ${{ steps.legacy.outputs.is == 'false' }}
        uses: docker/setup-buildx-action@aa33708b10e362ff993539393ff100fa93ed6a27 # v3.5.0

      - name: Login to quay.io
        if: ${{ steps.legacy.outputs.is == 'false' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      # Checking out the release branch
      - name: Checkout Source Code
        if: ${{ steps.legacy.outputs.is == 'false' }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Prepare download of image digests
        if: ${{ steps.legacy.outputs.is == 'false' }}
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        if: ${{ steps.legacy.outputs.is == 'false' }}
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: image-digest/
      
      - name: Update ClusterServiceVersion
        env:
          # renovate: datasource=github-releases depName=mikefarah/yq
          yq_version: 4.44.3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.legacy.outputs.is == 'false' }}
        run: |
          lower_tag="${{ steps.tag.outputs.tag }}"
          lower_tag="${lower_tag,,}"
          git checkout ${{ steps.tag.outputs.minor }}
          git checkout -b pr/release-wf/${{ steps.tag.outputs.tag }}
          tetragon_img="$(cat image-digest/image-digest\ tetragon/tetragon.txt | grep isovalent)"
          tetragon_img="${tetragon_img//\`}"
          echo "tetragon image: ${tetragon_img}"
          tetragon_operator_img="$(cat image-digest/image-digest\ tetragon-operator/tetragon-operator.txt | grep isovalent)"
          tetragon_operator_img="${tetragon_operator_img//\`}"
          echo "tetragon-operator image: ${tetragon_operator_img}"
          hubble_enterprise_metadata_digest=$(docker run quay.io/skopeo/stable:v1.15 inspect docker://quay.io/isovalent/hubble-enterprise-metadata:current | jq -r '.Digest')
          # sed commands seem fragile. Templating or yq may be better.
          sed -i "s/quay.io\/isovalent\/tetragon[:@].*\"$/${tetragon_img//\//\\/}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon[:@].*[^\"]$/${tetragon_img//\//\\/}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon-operator[:@].*\"$/${tetragon_operator_img//\//\\/}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon-operator[:@].*[^\"]$/${tetragon_operator_img//\//\\/}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/hubble-enterprise-metadata[:@].*\"$/quay.io\/isovalent\/hubble-enterprise-metadata:${{ steps.tag.outputs.tag }}@${hubble_enterprise_metadata_digest}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/hubble-enterprise-metadata[:@].*[^\"]$/quay.io\/isovalent\/hubble-enterprise-metadata:${{ steps.tag.outputs.tag }}@${hubble_enterprise_metadata_digest}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          # TODO: the value in the olm.skipRange annotation may need to be replaced when the annotation has been added.
          name_of_previous_csv=$(docker run -i --rm -v "${PWD}":/workdir -u "$(id -u)" mikefarah/yq:${yq_version} '.metadata.name' /workdir/install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml)
          docker run -i --rm -v "${PWD}":/workdir -u "$(id -u)" mikefarah/yq:${yq_version} e -i ".spec.replaces = \"${name_of_previous_csv}\"" /workdir/install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          version="${lower_tag:1}"
          sed -i "s/^[ ]*name: tetragon-operator\.v.*$/  name: tetragon-operator.${lower_tag}/" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/^[ ]*version: .*$/  version: ${version}/" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          git add ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          git config --global user.email "isovalent-bot@isovalent.com"
          git config --global user.name "isovalent-bot"
          git remote set-url origin https://isovalent-bot:${GITHUB_TOKEN}@github.com/isovalent/hubble-fgs.git
          git commit -m "chore: Update CSV images to ${{ steps.tag.outputs.tag }}"
          git push --set-upstream origin pr/release-wf/${{ steps.tag.outputs.tag }}
          # Create a PR with the updated ClusterServiceVersion against the release branch
          gh pr create -B ${{ steps.tag.outputs.minor }} --title "chore: Update CSV images to ${{ steps.tag.outputs.tag }}" --body 'Created by GitHub action: Image CI Releases.'

      - name: Bundle build 
        if: ${{ steps.legacy.outputs.is == 'false' }}
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        id: bundle_build
        with:
          context: ./install/olm
          file: ./install/olm/bundle.Dockerfile
          push: true
          tags: |
            quay.io/${{ github.repository_owner }}/tetragon-operator-bundle:${{ steps.tag.outputs.tag }}
      
      - name: Catalog update PR
        if: ${{ steps.legacy.outputs.is == 'false' }}
        run: |
          git checkout master
          git checkout -b pr/release-wf/catalog-${{ steps.tag.outputs.tag }}
          export DOCKER_IMAGE_TAG=${{ steps.tag.outputs.tag }}
          make olm-index-add
          git add install/olm/catalog/index.yaml
          git commit -m "chore: Update the OLM catalog with the latest bundle: ${{ steps.tag.outputs.tag }}"
          git push --set-upstream origin pr/release-wf/catalog-${{ steps.tag.outputs.tag }}
          # Create a PR with the updated ClusterServiceVersion against the release branch
          body="Created by GitHub action: Image CI Releases.
            DON'T MERGE RELEASE CANDIDATES INTO THE CATALOG!"
          gh pr create -B master --title "chore: Add bundle ${{ steps.tag.outputs.tag }} to the OLM catalog" --body "${body}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  image-digests:
    if: ${{ github.repository == 'isovalent/hubble-fgs' }}
    name: Display Digests
    runs-on: ubuntu-22.04
    needs: build-and-push
    steps:
      - name: Prepare download of image digests
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: image-digest/

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat

  draft-github-release:
    name: Create Release
    if: github.repository == 'isovalent/hubble-fgs'
    environment: release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          # renovate: datasource=golang-version depName=go
          go-version: '1.22.6'

      - name: Generate tetra CLI artifacts
        run: make cli-release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: ${{ steps.tag.outputs.tag }}
          draft: true
          prerelease: ${{ contains(steps.tag.outputs.tag, '-') }}
          body: |
            Please update the description with the actual release notes and publish the release.
            See the release issue for instructions.
          files: |
            release/*
