name: Base Image Build

on:
  workflow_call:
    inputs:
      # Used to checkout the source code and as a tag for non-release images.
      sha:
        required: true
        type: string
      # Tag to push. Optional for non-release images - if empty, only the sha tag is pushed.
      tag:
        type: string
      # Release images are pushed to isovalent Quay org, non-release to isovalent-dev.
      is_release:
        type: boolean

jobs:
  build-and-push:
    permissions:
      contents: read
      actions: read
      # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
      id-token: write
    runs-on: ubuntu-latest-4cores-16gb
    strategy:
      matrix:
        include:
          - name: tetragon
            dockerfile: ./Dockerfile

          - name: tetragon-slim
            dockerfile: ./Dockerfile.slim

          - name: tetragon-aggregator
            dockerfile: ./Dockerfile.aggregator

          - name: tetragon-operator
            dockerfile: ./Dockerfile.operator

          - name: tetragon-rthooks
            dockerfile: ./Dockerfile.rthooks

    steps:
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
        with:
          platforms: arm64

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Login to Artifactory
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ vars.ARTIFACTORY_HOST }}
          username: ${{ vars.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Checkout Source Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.sha }}
          submodules: true
          persist-credentials: false
          fetch-depth: 0

      # TODO: Validate that at least one tag is set. If is_release=true and
      # tag="" then there is no tag to push.
      - name: Get image tags
        id: tags
        run: |
          repo="${{ matrix.name }}"
          # CI images go to isovalent-eng-docker, release images go to isovalent-iep-docker
          if ${{ inputs.is_release }}; then
            registry_path="isovalent-iep-docker"
          else
            registry_path="isovalent-eng-docker"
            repo="$repo-ci"
          fi

          echo "tags<<EOF" >> $GITHUB_OUTPUT
          if ! ${{ inputs.is_release }}; then
            echo "${{ vars.ARTIFACTORY_HOST }}/${registry_path}/$repo:${{ inputs.sha }}" >> $GITHUB_OUTPUT
          fi
          if [ -n "${{ inputs.tag }}" ]; then
            echo "${{ vars.ARTIFACTORY_HOST }}/${registry_path}/$repo:${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        id: build-and-push
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.tags.outputs.tags }}

      - name: Get first tag for subsequent steps
        id: first-tag
        run: |
          first_tag=$(echo "${{ steps.tags.outputs.tags }}" | head -n1)
          echo "tag=${first_tag}" >> $GITHUB_OUTPUT

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Sign Container Image
        run: |
          cosign sign -y "${{ steps.first-tag.outputs.tag }}@${{ steps.build-and-push.outputs.digest }}"

      - name: Generate SBOM
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          artifact-name: sbom${{ inputs.is_release && '' || '_ci' }}_${{ matrix.name }}_${{ inputs.tag || inputs.sha }}.spdx.json
          output-file: ./sbom${{ inputs.is_release && '' || '_ci' }}_${{ matrix.name }}_${{ inputs.tag || inputs.sha }}.spdx.json
          image: ${{ steps.first-tag.outputs.tag }}
          upload-release-assets: false

      - name: Attach SBOM attestation to container image
        run: |
          cosign attest -y --predicate ./sbom${{ inputs.is_release && '' || '_ci' }}_${{ matrix.name }}_${{ inputs.tag || inputs.sha }}.spdx.json --type spdxjson "${{ steps.first-tag.outputs.tag }}@${{ steps.build-and-push.outputs.digest }}"

      - name: Image Release Digest
        shell: bash
        run: |
          mkdir -p image-digest/
          job_name=${{ inputs.is_release && matrix.name || format('{0}-ci', matrix.name) }}
          job_name_capital=${job_name^^}
          job_name_underscored=${job_name_capital//-/_}
          echo "${job_name_underscored}_DIGEST := \"${{ steps.build-and-push.outputs.digest }}\"" > image-digest/makefile-digest.txt

          echo "### $job_name" > image-digest/$job_name.txt
          echo "" >> image-digest/$job_name.txt
          echo "${{ steps.first-tag.outputs.tag }}@${{ steps.build-and-push.outputs.digest }}" >> image-digest/$job_name.txt
          echo "" >> image-digest/$job_name.txt

      - name: Upload artifact digests
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: image-digest-${{ inputs.is_release && matrix.name || format('{0}-ci', matrix.name) }}
          path: image-digest
          retention-days: ${{ inputs.is_release && 90 || 7 }}

  image-digests:
    name: Display Digests
    runs-on: ubuntu-24.04
    needs: build-and-push
    permissions:
      actions: read
      contents: read
    steps:
      - name: Getting image tag and making image-digest directory
        id: tag
        run: |
          echo tag=${GITHUB_REF##*/} >> $GITHUB_OUTPUT
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: image-digest/
          pattern: image-digest-*

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          echo "## Docker Manifests" > ../image-digest-output.txt
          echo "" >> ../image-digest-output.txt
          find -type f -not -name "makefile-digest.txt" | sort | xargs -d '\n' cat >> ../image-digest-output.txt

      - name: Image Makefile Digests
        shell: bash
        run: |
          cd image-digest/
          echo "# File generated by .github/workflows/build-images-base.yml; DO NOT EDIT." > ../Makefile.digests
          echo "# Copyright $(date +'%Y') Authors of Tetragon" >> ../Makefile.digests
          echo "# Copyright (C) Isovalent, Inc. - All Rights Reserved." >> ../Makefile.digests
          echo "" >> ../Makefile.digests
          find -type f  -name "makefile-digest.txt" | sort | xargs -d '\n' awk '{print "export " $0}' >> ../Makefile.digests

      - name: Upload artifact digests
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: image-digest-output.txt-${{ steps.tag.outputs.tag }}
          path: image-digest-output.txt
          retention-days: ${{ inputs.is_release && 90 || 7 }}

      - name: Upload artifact digests
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Makefile.digests-${{ steps.tag.outputs.tag }}
          path: Makefile.digests
          retention-days: ${{ inputs.is_release && 90 || 7 }}

  helm-chart:
    if: ${{ success() }}
    name: Push OCI Helm Chart
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    needs: build-and-push
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.sha }}
          submodules: true
          persist-credentials: false
          fetch-depth: 0

      - name: Get chart version
        id: version
        run: |
          echo "chart_version=$(make chart-version)" >> $GITHUB_OUTPUT

      - name: Push OCI Helm dev chart
        uses: cilium/reusable-workflows/.github/actions/push-helm-chart@6ae27958f2f37545bf48e44106b73df05b1f6d12 # v0.1.0
        with:
          name: tetragon
          path: install/kubernetes/tetragon
          version: ${{ steps.version.outputs.chart_version }}
          values_file_changes: |
            {
              "tetragon.image.repository": "${{ vars.ARTIFACTORY_HOST }}/isovalent-eng-docker/tetragon-ci",
              "tetragon.image.tag": "${{ inputs.sha }}",
              "tetragonAggregator.image.repository": "${{ vars.ARTIFACTORY_HOST }}/isovalent-eng-docker/tetragon-aggregator-ci",
              "tetragonAggregator.image.tag": "${{ inputs.sha }}",
              "tetragonOperator.image.repository": "${{ vars.ARTIFACTORY_HOST }}/isovalent-eng-docker/tetragon-operator-ci",
              "tetragonOperator.image.tag": "${{ inputs.sha }}",
              "rthooks.image.repository": "${{ vars.ARTIFACTORY_HOST }}/isovalent-eng-docker/tetragon-rthooks-ci",
              "rthooks.image.tag": "${{ inputs.sha }}",
            }
          registry: ${{ vars.ARTIFACTORY_HOST }}
          registry_namespace: isovalent-eng-docker
          registry_username: ${{ vars.ARTIFACTORY_USERNAME }}
          registry_password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Print helm command
        run: |
          echo "Example commands:"
          echo helm template -n tetragon oci://${{ vars.ARTIFACTORY_HOST }}/isovalent-eng-docker/tetragon --version ${{ steps.version.outputs.chart_version }}
          echo helm install tetragon -n tetragon oci://${{ vars.ARTIFACTORY_HOST }}/isovalent-eng-docker/tetragon --version ${{ steps.version.outputs.chart_version }}
