name: Image CI Build

on:
  pull_request:
    paths-ignore:
    - "**.md"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-push-prs:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: hubble-enterprise
            dockerfile: ./Dockerfile

          - name: hubble-enterprise-operator
            dockerfile: ./operator.Dockerfile

    steps:
      - name: Login to quay.io for CI
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ISOVALENT_DEV_USERNAME }}
          password: ${{ secrets.QUAY_ISOVALENT_DEV_PASSWORD }}

      - name: Getting image tag
        id: tag
        run: |
          if [ ${{ github.event.pull_request.head.sha }} != "" ]; then
            echo ::set-output name=tag::${{ github.event.pull_request.head.sha }}
          else
            echo ::set-output name=tag::${{ github.sha }}
          fi

      - name: Checkout Source Code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          submodules: true
          persist-credentials: false
          ref: ${{ steps.tag.outputs.tag }}
          fetch-depth: 0

      # PR updates
      - name: CI Build (PR)
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        id: docker_build_ci_pr
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: |
            quay.io/${{ github.repository_owner }}-dev/${{ matrix.name }}-ci:${{ steps.tag.outputs.tag }}

      - name: CI Image digests (PR)
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "quay.io/${{ github.repository_owner }}-dev/${{ matrix.name }}-ci:${{ steps.tag.outputs.tag }}@${{ steps.docker_build_ci_pr.outputs.digest }}" >> image-digest/${{ matrix.name }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: image-digest ${{ matrix.name }}
          path: image-digest
          retention-days: 1

  image-digests:
    if: ${{ always() }}
    name: Display Digests
    runs-on: ubuntu-20.04
    needs: [build-and-push-prs]
    steps:
      - name: Downloading Image Digests
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60
        with:
          path: image-digest/

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat
