name: Image CI Stable Branches

on:
  push:
    branches:
      - v*

jobs:
  build-and-push:
    uses: ./.github/workflows/build-images-base.yml
    permissions:
      contents: read
    with:
      sha: "${{ github.sha }}"
      tag: "${{ github.ref_name }}-latest"
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_ISOVALENT_DEV_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_ISOVALENT_DEV_PASSWORD }}
      QUAY_CHARTS_USERNAME: ${{ secrets.QUAY_ISOVALENT_CHARTS_DEV_USERNAME }}
      QUAY_CHARTS_PASSWORD: ${{ secrets.QUAY_ISOVALENT_CHARTS_DEV_PASSWORD }}
