name: Image CI Build

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master

jobs:
  build-and-push-prs:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to quay.io for CI
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Getting image tag
        id: tag
        run: |
          if [ ${{ github.event.pull_request.head.sha }} != "" ]; then
            echo ::set-output name=tag::${{ github.event.pull_request.head.sha }}
          else
            echo ::set-output name=tag::${{ github.sha }}
          fi

      - name: Checkout Source Code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          persist-credentials: false
          ref: ${{ steps.tag.outputs.tag }}

      # master branch pushes
      - name: CI Build
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        id: docker_build_ci_master
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            quay.io/${{ github.repository_owner }}/hubble-enterprise-ci:latest
            quay.io/${{ github.repository_owner }}/hubble-enterprise-ci:${{ steps.tag.outputs.tag }}

      # PR updates
      - name: CI Build ${{ matrix.name }}
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        id: docker_build_ci_pr
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            quay.io/${{ github.repository_owner }}/hubble-enterprise-ci:${{ steps.tag.outputs.tag }}
