name: Image CI Releases

on:
  push:
    tags:
      - v*

permissions:
  # For softprops/action-gh-release draft release creation and artifact upload
  contents: write
  # For creating a PR to update the OLM catalog
  pull-requests: write
  # Required for the GitHub Action to authenticate to Vault
  id-token: write

env:
  ARTIFACTORY_ORGANIZATION_PROD: ${{ vars.ARTIFACTORY_ORGANIZATION_PROD || 'isovalent-iep-docker' }}

jobs:
  build-and-push:
    name: Build and Push Release ${{ matrix.is_lseg && 'LSEG' || '' }} Images
    strategy:
      matrix:
        include:
          - is_lseg: true
          - is_lseg: false
    uses: ./.github/workflows/build-images-base.yml
    permissions:
      contents: read
      actions: read
      # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
      id-token: write
    with:
      sha: "${{ github.sha }}"
      tag: "${{ github.ref_name }}"
      is_release: true
      is_lseg: ${{ matrix.is_lseg }}
    secrets: inherit

  build-and-push-ubi:
    uses: ./.github/workflows/build-images-ubi-base.yml
    permissions:
      contents: read
      actions: read
      id-token: write
    with:
      sha: "${{ github.sha }}"
      tag: "${{ github.ref_name }}"
      is_release: true
    secrets: inherit

  build-tarballs:
    uses: ./.github/workflows/build-tarballs.yml
    secrets: inherit

  # The ClusterServiceVersion is dependent on the previous builds as it needs to be updated with the image digests
  # produced during these builds. The bundle is platform-independent, so it does not need a multi-arch build.
  bundle-build-and-push:
    needs: build-and-push
    runs-on: ubuntu-26.04
    environment:
      name: release
      deployment: false
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Get tag and branch
        id: tag
        run: |
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          branch="$(echo ${GITHUB_REF##*/} | cut -d. -f-2)"
          # If the branch doesn't exist, use the master branch
          if ! git show-ref --verify --quiet "refs/remotes/origin/$branch"; then
            branch=master
          fi
          echo "branch=$branch" >> $GITHUB_OUTPUT

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Login to Artifactory
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ vars.ARTIFACTORY_HOST }}
          username: ${{ vars.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Download digests of all images built
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: digests/
          pattern: image-digest-*

      # This is with the verified assumption that images are mirrored with the same digest
      # between devhub and containers.isovalent.com
      - name: Get Image references
        id: image-refs
        env:
          ARTIFACTORY_HOST: ${{ vars.ARTIFACTORY_HOST }}
        run: |
          tetragon_img="$(cat digests/image-digest-tetragon-ci/tetragon.txt | grep isovalent)"
          echo "tetragon image: ${tetragon_img}"
          echo "tetragon_img=$tetragon_img" >> $GITHUB_OUTPUT
          tetragon_aggregator_img="$(cat digests/image-digest-tetragon-aggregator-ci/tetragon-aggregator.txt | grep isovalent)"
          echo "tetragon-aggregator image: ${tetragon_aggregator_img}"
          echo "tetragon_aggregator_img=$tetragon_aggregator_img" >> $GITHUB_OUTPUT
          tetragon_operator_img="$(cat digests/image-digest-tetragon-operator-ci/tetragon-operator.txt | grep isovalent)"
          echo "tetragon-operator image: ${tetragon_operator_img}"
          echo "tetragon_operator_img=$tetragon_operator_img" >> $GITHUB_OUTPUT
          hubble_enterprise_metadata_repo="${ARTIFACTORY_HOST}/${ARTIFACTORY_ORGANIZATION_PROD}/hubble-enterprise-metadata"
          hubble_enterprise_metadata_digest="$(
            set -o pipefail
            docker buildx imagetools inspect "${hubble_enterprise_metadata_repo}:current" --format '{{json .}}' | jq -er '.manifest.digest'
          )"
          hubble_enterprise_metadata_img="${hubble_enterprise_metadata_repo}:${{ steps.tag.outputs.tag }}@${hubble_enterprise_metadata_digest}"
          echo "hubble-enterprise-metadata image: ${hubble_enterprise_metadata_img}"
          echo "hubble_enterprise_metadata_img=$hubble_enterprise_metadata_img" >> $GITHUB_OUTPUT
          tetragon_rthooks_img="$(cat digests/image-digest-tetragon-rthooks-ci/tetragon-rthooks.txt | grep isovalent)"
          echo "tetragon-rthooks image: ${tetragon_rthooks_img}"
          echo "tetragon_rthooks_img=$tetragon_rthooks_img" >> $GITHUB_OUTPUT


      - name: Update ClusterServiceVersion internal registry
        env:
          # renovate: datasource=github-releases depName=mikefarah/yq
          yq_version: 4.53.6
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          csv_file=install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          yq_image="mikefarah/yq:${yq_version}"
          lower_tag="${{ steps.tag.outputs.tag }}"
          lower_tag="${lower_tag,,}"
          git checkout ${{ steps.tag.outputs.branch }}
          git checkout -b pr/release-wf/${{ steps.tag.outputs.tag }}
          docker run -i --rm \
            -e TETRAGON_IMG="${{ steps.image-refs.outputs.tetragon_img }}" \
            -e TETRAGON_AGGREGATOR_IMG="${{ steps.image-refs.outputs.tetragon_aggregator_img }}" \
            -e TETRAGON_OPERATOR_IMG="${{ steps.image-refs.outputs.tetragon_operator_img }}" \
            -e TETRAGON_RTHOOKS_IMG="${{ steps.image-refs.outputs.tetragon_rthooks_img }}" \
            -e HUBBLE_ENTERPRISE_METADATA_IMG="${{ steps.image-refs.outputs.hubble_enterprise_metadata_img }}" \
            -v "${PWD}":/workdir \
            -u "$(id -u)" \
            "${yq_image}" e -i '
              (.spec.install.spec.deployments[] | select(.name == "tetragon-operator") | .spec.template.spec.containers[] | select(.name == "tetragon-operator") | .env[] | select(.name == "TETRAGON_IMAGE") | .value) = strenv(TETRAGON_IMG) |
              (.spec.install.spec.deployments[] | select(.name == "tetragon-operator") | .spec.template.spec.containers[] | select(.name == "tetragon-operator") | .env[] | select(.name == "TETRAGON_AGGREGATOR_IMAGE") | .value) = strenv(TETRAGON_AGGREGATOR_IMG) |
              (.spec.install.spec.deployments[] | select(.name == "tetragon-operator") | .spec.template.spec.containers[] | select(.name == "tetragon-operator") | .env[] | select(.name == "TETRAGON_RTHOOKS_IMAGE") | .value) = strenv(TETRAGON_RTHOOKS_IMG) |
              (.spec.install.spec.deployments[] | select(.name == "tetragon-operator") | .spec.template.spec.containers[] | select(.name == "tetragon-operator") | .env[] | select(.name == "TETRAGON_METADATA_IMAGE") | .value) = strenv(HUBBLE_ENTERPRISE_METADATA_IMG) |
              (.spec.install.spec.deployments[] | select(.name == "tetragon-operator") | .spec.template.spec.containers[] | select(.name == "tetragon-operator") | .image) = strenv(TETRAGON_OPERATOR_IMG)
            ' "/workdir/${csv_file}"
          # TODO: the value in the olm.skipRange annotation may need to be replaced when the annotation has been added.
          name_of_previous_csv=$(docker run -i --rm -v "${PWD}":/workdir -u "$(id -u)" "${yq_image}" '.metadata.name' "/workdir/${csv_file}")
          docker run -i --rm -v "${PWD}":/workdir -u "$(id -u)" "${yq_image}" e -i ".spec.replaces = \"${name_of_previous_csv}\"" "/workdir/${csv_file}"
          version="${lower_tag:1}"
          sed -i "s/^[ ]*name: tetragon-operator\.v.*$/  name: tetragon-operator.${lower_tag}/" "${csv_file}"
          sed -i "s/^[ ]*version: .*$/  version: ${version}/" "${csv_file}"
          git add "${csv_file}"
          git config --global user.email "isovalent-bot@isovalent.com"
          git config --global user.name "isovalent-bot"
          git remote set-url origin https://isovalent-bot:${GITHUB_TOKEN}@github.com/isovalent/hubble-fgs.git
          git commit -m "chore: Update CSV images to ${{ steps.tag.outputs.tag }}"
          # The CSV for the internal registry does not get pushed into GitHub, it is only used for creating the bundle

      - name: Bundle build internal Artifactory
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: ./install/olm
          file: ./install/olm/bundle.Dockerfile
          push: true
          tags: |
            ${{ vars.ARTIFACTORY_HOST }}/${{ env.ARTIFACTORY_ORGANIZATION_PROD }}/tetragon-operator-bundle:${{ steps.tag.outputs.tag }}

      - name: Configure JFrog CLI for OIDC Auth
        id: setup-isovalent-registry
        uses: jfrog/setup-jfrog-cli@68c0efdc951dd2359bbbfa15c48bc67b3ae8e4d6 # v5.2.0
        env:
          JF_URL: ${{ vars.ISOVALENT_ARTIFACTORY_URL }}
        with:
          oidc-provider-name: ${{ vars.ISOVALENT_ARTIFACTORY_PROVIDER_NAME }}
          oidc-audience: ${{ vars.ISOVALENT_ARTIFACTORY_OIDC_AUDIENCE }}
          custom-server-id: isovalent-registry

      - name: Login to Isovalent Registry
        id: login-isovalent-registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ vars.ISOVALENT_ARTIFACTORY_HOST }}
          username: ${{ steps.setup-isovalent-registry.outputs.oidc-user }}
          password: ${{ steps.setup-isovalent-registry.outputs.oidc-token }}

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Update ClusterServiceVersion customer facing registry
        env:
          # renovate: datasource=github-releases depName=mikefarah/yq
          yq_version: 4.53.6
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACTORY_HOST: ${{ vars.ISOVALENT_ARTIFACTORY_HOST }}
        run: |
          csv_file=install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          yq_image="mikefarah/yq:${yq_version}"
          lower_tag="${{ steps.tag.outputs.tag }}"
          lower_tag="${lower_tag,,}"
          git checkout ${{ steps.tag.outputs.branch }}
          git checkout -b pr/release-wf/isovalent-${{ steps.tag.outputs.tag }}
          tetragon_img=${{ steps.image-refs.outputs.tetragon_img }}
          tetragon_img="${ARTIFACTORY_HOST}/tetragon:${tetragon_img#*:}"
          echo "tetragon image: ${tetragon_img}"
          tetragon_aggregator_img=${{ steps.image-refs.outputs.tetragon_aggregator_img }}
          tetragon_aggregator_img="${ARTIFACTORY_HOST}/tetragon-aggregator:${tetragon_aggregator_img#*:}"
          echo "tetragon-aggregator image: ${tetragon_aggregator_img}"
          tetragon_operator_img=${{ steps.image-refs.outputs.tetragon_operator_img }}
          tetragon_operator_img="${ARTIFACTORY_HOST}/tetragon-operator:${tetragon_operator_img#*:}"
          echo "tetragon-operator image: ${tetragon_operator_img}"
          hubble_enterprise_metadata_img=${{ steps.image-refs.outputs.hubble_enterprise_metadata_img }}
          hubble_enterprise_metadata_img="${ARTIFACTORY_HOST}/hubble-enterprise-metadata:${hubble_enterprise_metadata_img#*:}"
          echo "hubble-enterprise-metadata image: ${hubble_enterprise_metadata_img}"
          tetragon_rthooks_img=${{ steps.image-refs.outputs.tetragon_rthooks_img }}
          tetragon_rthooks_img="${ARTIFACTORY_HOST}/tetragon-rthooks:${tetragon_rthooks_img#*:}"
          echo "tetragon-rthooks image: ${tetragon_rthooks_img}"
          docker run -i --rm \
            -e TETRAGON_IMG="${tetragon_img}" \
            -e TETRAGON_AGGREGATOR_IMG="${tetragon_aggregator_img}" \
            -e TETRAGON_OPERATOR_IMG="${tetragon_operator_img}" \
            -e TETRAGON_RTHOOKS_IMG="${tetragon_rthooks_img}" \
            -e HUBBLE_ENTERPRISE_METADATA_IMG="${hubble_enterprise_metadata_img}" \
            -v "${PWD}":/workdir \
            -u "$(id -u)" \
            "${yq_image}" e -i '
              (.spec.install.spec.deployments[] | select(.name == "tetragon-operator") | .spec.template.spec.containers[] | select(.name == "tetragon-operator") | .env[] | select(.name == "TETRAGON_IMAGE") | .value) = strenv(TETRAGON_IMG) |
              (.spec.install.spec.deployments[] | select(.name == "tetragon-operator") | .spec.template.spec.containers[] | select(.name == "tetragon-operator") | .env[] | select(.name == "TETRAGON_AGGREGATOR_IMAGE") | .value) = strenv(TETRAGON_AGGREGATOR_IMG) |
              (.spec.install.spec.deployments[] | select(.name == "tetragon-operator") | .spec.template.spec.containers[] | select(.name == "tetragon-operator") | .env[] | select(.name == "TETRAGON_RTHOOKS_IMAGE") | .value) = strenv(TETRAGON_RTHOOKS_IMG) |
              (.spec.install.spec.deployments[] | select(.name == "tetragon-operator") | .spec.template.spec.containers[] | select(.name == "tetragon-operator") | .env[] | select(.name == "TETRAGON_METADATA_IMAGE") | .value) = strenv(HUBBLE_ENTERPRISE_METADATA_IMG) |
              (.spec.install.spec.deployments[] | select(.name == "tetragon-operator") | .spec.template.spec.containers[] | select(.name == "tetragon-operator") | .image) = strenv(TETRAGON_OPERATOR_IMG)
            ' "/workdir/${csv_file}"
          # TODO: the value in the olm.skipRange annotation may need to be replaced when the annotation has been added.
          name_of_previous_csv=$(docker run -i --rm -v "${PWD}":/workdir -u "$(id -u)" "${yq_image}" '.metadata.name' "/workdir/${csv_file}")
          docker run -i --rm -v "${PWD}":/workdir -u "$(id -u)" "${yq_image}" e -i ".spec.replaces = \"${name_of_previous_csv}\"" "/workdir/${csv_file}"
          version="${lower_tag:1}"
          sed -i "s/^[ ]*name: tetragon-operator\.v.*$/  name: tetragon-operator.${lower_tag}/" "${csv_file}"
          sed -i "s/^[ ]*version: .*$/  version: ${version}/" "${csv_file}"
          git add "${csv_file}"
          git config --global user.email "isovalent-bot@isovalent.com"
          git config --global user.name "isovalent-bot"
          git remote set-url origin https://isovalent-bot:${GITHUB_TOKEN}@github.com/isovalent/hubble-fgs.git
          git commit -m "chore: Update CSV images to ${{ steps.tag.outputs.tag }}"
          git push --set-upstream origin pr/release-wf/isovalent-${{ steps.tag.outputs.tag }}
          # Create a PR with the updated ClusterServiceVersion against the release branch
          gh pr create -B ${{ steps.tag.outputs.branch }} --title "chore: Update CSV images to ${{ steps.tag.outputs.tag }}" --body 'Created by GitHub action: Image CI Releases.'

      - name: Bundle build customer facing Artifactory
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: ./install/olm
          file: ./install/olm/bundle.Dockerfile
          push: true
          tags: |
            ${{ vars.ISOVALENT_ARTIFACTORY_HOST }}/tetragon-operator-bundle:${{ steps.tag.outputs.tag }}

      - name: Get Readonly Github App Credentials
        uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc # v4
        with:
          url: ${{ vars.VAULT_URL }}
          method: ${{ vars.VAULT_METHOD }}
          namespace: ${{ vars.VAULT_NAMESPACE }}
          secrets: |
            secret/data/org/${{ github.repository_owner }} github_app_id | GH_READONLY_APP_ID;
            secret/data/org/${{ github.repository_owner }} github_app_pem | GH_READONLY_APP_PEM;

      - id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ env.GH_READONLY_APP_ID }}
          private-key: ${{ env.GH_READONLY_APP_PEM }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ipa

      - name: Configure git to use generated token
        run: |
             READONLY_GH_TOKEN=${{ steps.generate-token.outputs.token }}
             # override git config to use the token for cloning
             git config --global \
               url."https://x-access-token::${READONLY_GH_TOKEN}@github.com/isovalent".insteadOf \
               "https://github.com/isovalent"

      - name: Internal catalog update PR
        run: |
          git checkout master
          git checkout -b pr/release-wf/catalog-${{ steps.tag.outputs.tag }}
          export DOCKER_IMAGE_TAG=${{ steps.tag.outputs.tag }}
          export IMAGE_REPOSITORY="${{ vars.ARTIFACTORY_HOST }}/${ARTIFACTORY_ORGANIZATION_PROD}"
          make olm-index-add
          git add install/olm/catalog/index.yaml
          git commit -m "chore: Update the OLM catalog with: ${{ steps.tag.outputs.tag }}"
          git push --set-upstream origin pr/release-wf/catalog-${{ steps.tag.outputs.tag }}
          body="Created by GitHub action: Image CI Releases.
            DON'T MERGE RELEASE CANDIDATES INTO THE CATALOG!"
          gh pr create -B master --title "chore: Add bundle ${{ steps.tag.outputs.tag }} to the internal OLM catalog" --body "${body}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Customer facing catalog update PR
        run: |
          git checkout master
          git checkout -b pr/release-wf/isovalent-catalog-${{ steps.tag.outputs.tag }}
          export DOCKER_IMAGE_TAG=${{ steps.tag.outputs.tag }}
          export IMAGE_REPOSITORY="${{ vars.ISOVALENT_ARTIFACTORY_HOST }}"
          export INDEX_DIR="isovalent-catalog"
          make olm-index-add
          git add install/olm/${INDEX_DIR}/index.yaml
          git commit -m "chore: Update the Isovalent OLM catalog with: ${{ steps.tag.outputs.tag }}"
          git push --set-upstream origin pr/release-wf/isovalent-catalog-${{ steps.tag.outputs.tag }}
          body="Created by GitHub action: Image CI Releases.
            DON'T MERGE RELEASE CANDIDATES INTO THE CATALOG!"
          gh pr create -B master --title "chore: Add bundle ${{ steps.tag.outputs.tag }} to the Customer facing OLM catalog" --body "${body}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  draft-github-release:
    name: Create Release
    needs: build-tarballs
    if: github.repository == 'isovalent/hubble-fgs' && (!contains(github.ref_name, '-') || contains(github.ref_name, '-pre') || contains(github.ref_name, '-rc'))
    environment: release
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: '1.27.1'

      - name: Generate tetra CLI artifacts
        run: make cli-release

      - name: Download Tetragon Slim Tarball (amd64)
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tetragon-slim-tarball-amd64
          path: release

      - name: Download Tetragon Slim Tarball (arm64)
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tetragon-slim-tarball-arm64
          path: release

      - name: Download Tetragon Tarball (amd64)
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tetragon-tarball-amd64
          path: release

      - name: Download Tetragon Tarball (arm64)
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tetragon-tarball-arm64
          path: release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          draft: true
          body: |
            Please update the description with the actual release notes and publish the release.
            See the release issue for instructions.
          files: |
            release/*

  dev-hub-artifactory-release:
    name: Dev Hub Artifactory tarballs release
    needs: build-tarballs
    if: github.repository == 'isovalent/hubble-fgs' && (!contains(github.ref_name, '-') || contains(github.ref_name, '-pre') || contains(github.ref_name, '-rc'))
    environment: release
    runs-on: ubuntu-26.04
    steps:
      - name: Setup access to Artifactory
        uses: jfrog/setup-jfrog-cli@68c0efdc951dd2359bbbfa15c48bc67b3ae8e4d6 # v5.2.0
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_USER: ${{ vars.ARTIFACTORY_USERNAME }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Download Tetragon Tarball artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: tetragon-*tarball-*
          path: release
          merge-multiple: true

      - name: Upload to Artifactory
        env:
          ARTIFACTORY_PATH: "${{ vars.ARTIFACTORY_REPO_GENERIC }}/tetragon/${{ github.ref_name }}"
        run: |
          jf rt u --flat "release/*" "${ARTIFACTORY_PATH}/"
