name: Image CI Releases

on:
  push:
    tags:
      - v*

permissions:
  # For softprops/action-gh-release draft release creation and artifact upload
  contents: write
  # For creating a PR to update the OLM catalog
  pull-requests: write

jobs:
  build-and-push:
    uses: ./.github/workflows/build-images-base.yml
    with:
      sha: "${{ github.sha }}"
      tag: "${{ github.ref_name }}"
      is_release: true
      is_legacy: ${{ startsWith(github.ref_name, 'v1.11') || startsWith(github.ref_name, 'v1.12') }}
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USER }}
      QUAY_PASSWORD: ${{ secrets.QUAY_TOKEN }}
      QUAY_CHARTS_USERNAME: ${{ secrets.QUAY_ISOVALENT_CHARTS_DEV_USERNAME }}
      QUAY_CHARTS_PASSWORD: ${{ secrets.QUAY_ISOVALENT_CHARTS_DEV_PASSWORD }}

  # The ClusterServiceVersion part of the bundle is dependent on the previous builds as it needs to be updated with the image digests
  # produced during these builds.
  # The bundle is just a bunch of manifests, no binary, there is no need for a multi-arch build. It is already platform independent.
  # The context needs to be passed to the build.
  # => hence a separate job
  bundle-build-and-push:
    if: ${{ !startsWith(github.ref_name, 'v1.11') && !startsWith(github.ref_name, 'v1.12') }}
    needs: build-and-push
    runs-on: ubuntu-24.04
    steps:
      - name: Getting image tag
        id: tag
        run: |
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "minor=$(echo ${GITHUB_REF##*/} | cut -d. -f-2)" >> $GITHUB_OUTPUT
        
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - name: Login to quay.io
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      # Checking out the release branch
      - name: Checkout Source Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Download digests of all images built
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: digests/
          pattern: digest-*
          merge-multiple: true
      
      - name: Update ClusterServiceVersion
        env:
          # renovate: datasource=github-releases depName=mikefarah/yq
          yq_version: 4.44.6
          # renovate: datasource=docker depName=quay.io/cilium/tetragon-rthooks
          rthooks_tag: v0.4
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          lower_tag="${{ steps.tag.outputs.tag }}"
          lower_tag="${lower_tag,,}"
          git checkout ${{ steps.tag.outputs.minor }}
          git checkout -b pr/release-wf/${{ steps.tag.outputs.tag }}
          tetragon_img="$(cat digests/tetragon.txt | grep isovalent)"
          echo "tetragon image: ${tetragon_img}"
          tetragon_operator_img="$(cat digests/tetragon-operator.txt | grep isovalent)"
          echo "tetragon-operator image: ${tetragon_operator_img}"
          hubble_enterprise_metadata_digest=$(docker run quay.io/skopeo/stable:v1.15 inspect docker://quay.io/isovalent/hubble-enterprise-metadata:current | jq -r '.Digest')
          tetragon_rthooks_image_digest=$(docker run quay.io/skopeo/stable:v1.15 inspect docker://quay.io/cilium/tetragon-rthooks:${rthooks_tag} | jq -r '.Digest')
          # sed commands seem fragile. Templating or yq may be better.
          sed -i "s/quay.io\/isovalent\/tetragon[:@].*\"$/${tetragon_img//\//\\/}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon[:@].*[^\"]$/${tetragon_img//\//\\/}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon-operator[:@].*\"$/${tetragon_operator_img//\//\\/}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon-operator[:@].*[^\"]$/${tetragon_operator_img//\//\\/}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/cilium\/tetragon-rthooks[:@].*\"$/quay.io\/cilium\/tetragon-rthooks:${rthooks_tag}@${tetragon_rthooks_image_digest}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/cilium\/tetragon-rthooks[:@].*[^\"]$/quay.io\/cilium\/tetragon-rthooks:${rthooks_tag}@${tetragon_rthooks_image_digest}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/hubble-enterprise-metadata[:@].*\"$/quay.io\/isovalent\/hubble-enterprise-metadata:${{ steps.tag.outputs.tag }}@${hubble_enterprise_metadata_digest}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/hubble-enterprise-metadata[:@].*[^\"]$/quay.io\/isovalent\/hubble-enterprise-metadata:${{ steps.tag.outputs.tag }}@${hubble_enterprise_metadata_digest}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          # TODO: the value in the olm.skipRange annotation may need to be replaced when the annotation has been added.
          name_of_previous_csv=$(docker run -i --rm -v "${PWD}":/workdir -u "$(id -u)" mikefarah/yq:${yq_version} '.metadata.name' /workdir/install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml)
          docker run -i --rm -v "${PWD}":/workdir -u "$(id -u)" mikefarah/yq:${yq_version} e -i ".spec.replaces = \"${name_of_previous_csv}\"" /workdir/install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          version="${lower_tag:1}"
          sed -i "s/^[ ]*name: tetragon-operator\.v.*$/  name: tetragon-operator.${lower_tag}/" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/^[ ]*version: .*$/  version: ${version}/" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          git add ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          git config --global user.email "isovalent-bot@isovalent.com"
          git config --global user.name "isovalent-bot"
          git remote set-url origin https://isovalent-bot:${GITHUB_TOKEN}@github.com/isovalent/hubble-fgs.git
          git commit -m "chore: Update CSV images to ${{ steps.tag.outputs.tag }}"
          git push --set-upstream origin pr/release-wf/${{ steps.tag.outputs.tag }}
          # Create a PR with the updated ClusterServiceVersion against the release branch
          gh pr create -B ${{ steps.tag.outputs.minor }} --title "chore: Update CSV images to ${{ steps.tag.outputs.tag }}" --body 'Created by GitHub action: Image CI Releases.'

      - name: Bundle build 
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # v6.12.0
        id: bundle_build
        with:
          context: ./install/olm
          file: ./install/olm/bundle.Dockerfile
          push: true
          tags: |
            quay.io/${{ github.repository_owner }}/tetragon-operator-bundle:${{ steps.tag.outputs.tag }}
      
      - name: Catalog update PR
        run: |
          git checkout master
          make oss-checkout
          git checkout -b pr/release-wf/catalog-${{ steps.tag.outputs.tag }}
          export DOCKER_IMAGE_TAG=${{ steps.tag.outputs.tag }}
          make olm-index-add
          git add install/olm/catalog/index.yaml
          git commit -m "chore: Update the OLM catalog with the latest bundle: ${{ steps.tag.outputs.tag }}"
          git push --set-upstream origin pr/release-wf/catalog-${{ steps.tag.outputs.tag }}
          # Create a PR with the updated ClusterServiceVersion against the release branch
          body="Created by GitHub action: Image CI Releases.
            DON'T MERGE RELEASE CANDIDATES INTO THE CATALOG!"
          gh pr create -B master --title "chore: Add bundle ${{ steps.tag.outputs.tag }} to the OLM catalog" --body "${body}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  draft-github-release:
    name: Create Release
    if: github.repository == 'isovalent/hubble-fgs' && !contains(github.ref_name, '-')
    environment: release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: '1.23.5'

      - name: Generate tetra CLI artifacts
        run: make cli-release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          draft: true
          body: |
            Please update the description with the actual release notes and publish the release.
            See the release issue for instructions.
          files: |
            release/*
