name: Packages Releases

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version to build: tag, branch or commit SHA"

env:
  BUCKET_NAME : "isovalent-tetragon-enterprise-public"
  AWS_REGION : "us-west-2"

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: amd64
          - os: ubuntu-22.04-arm64
            arch: arm64

    steps:
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Checkout Source Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref_name }}
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Generate Tetragon EE Tarball Release
        id: tetragon-tarball-release
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          make tarball-release

      - name: Checksum Tetragon EE Tarball
        run: sha256sum -c tetragon-*-${{ matrix.arch }}.tar.gz.sha256sum
        working-directory: ./release

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::679388779924:role/tetragon-enterprise-github-actions
          role-session-name: tetragon-enterprise-s3-upload

      - name: Upload Tetragon EE Tarball to AWS s3
        run: |
          aws s3 cp tetragon-*-${{ matrix.arch }}.tar.gz s3://${{ env.BUCKET_NAME }}/tetragon-enterprise-standalone-tarball/
          aws s3 cp tetragon-*-${{ matrix.arch }}.tar.gz.sha256sum s3://${{ env.BUCKET_NAME }}/tetragon-enterprise-standalone-tarball/
        working-directory: ./release
