name: Image CI Build

on:
  pull_request:
    paths-ignore:
    - "**.md"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-push:
    uses: ./.github/workflows/build-images-base.yml
    with:
      sha: "${{ github.event.pull_request.head.sha }}"
      is_legacy: ${{ github.event.pull_request.base.ref == 'v1.11' || github.event.pull_request.base.ref == 'v1.12' }}
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_ISOVALENT_DEV_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_ISOVALENT_DEV_PASSWORD }}
      QUAY_CHARTS_USERNAME: ${{ secrets.QUAY_ISOVALENT_CHARTS_DEV_USERNAME }}
      QUAY_CHARTS_PASSWORD: ${{ secrets.QUAY_ISOVALENT_CHARTS_DEV_PASSWORD }}
