name: OLM Image CI Build

on:
  push:
    branches:
      - master
      - v*
  pull_request:
    paths-ignore:
      - "**.md"
      - "contrib/grafana/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-push-prs:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Login to quay.io for CI
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ISOVALENT_DEV_USERNAME }}
          password: ${{ secrets.QUAY_ISOVALENT_DEV_PASSWORD }}

      - name: Getting image tag
        id: tag
        run: |
          if [ ${{ github.event.pull_request.head.sha }} != "" ]; then
            echo "tag=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Source Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false
          ref: ${{ steps.tag.outputs.tag }}
          fetch-depth: 0

      - name: Update CSV references
        run: |
          tetragon_img="quay.io/${{ github.repository_owner }}-dev/tetragon-ci:${{ steps.tag.outputs.tag }}"
          tetragon_operator_img="quay.io/${{ github.repository_owner }}-dev/tetragon-operator-ci:${{ steps.tag.outputs.tag }}"
          sed -i "s/quay.io\/isovalent\/tetragon[:@].*\"$/${tetragon_img//\//\\/}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon[:@].*[^\"]$/${tetragon_img//\//\\/}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon-operator[:@].*\"$/${tetragon_operator_img//\//\\/}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon-operator[:@].*[^\"]$/${tetragon_operator_img//\//\\/}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/^[ ]*name: tetragon-operator\.v.*$/  name: tetragon-operator.${{ steps.tag.outputs.tag }}/" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml

      - name: CI Bundle Build
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: ./install/olm
          file: ./install/olm/bundle.Dockerfile
          push: true
          tags: |
            quay.io/${{ github.repository_owner }}-dev/tetragon-operator-bundle-ci:${{ steps.tag.outputs.tag }}
          labels: quay.expires-after=2d

      - name: Update catalog index references
        run: |
          sed -i  "s/{{CI_VERSION}}/${{ steps.tag.outputs.tag }}/g" ./install/olm/catalog-ci/index.yaml

      - name: CI Catalog Index Build
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: ./install/olm
          file: ./install/olm/catalog-ci.Dockerfile
          push: true
          tags: |
            quay.io/${{ github.repository_owner }}-dev/tetragon-operator-index-ci:${{ steps.tag.outputs.tag }}
          labels: quay.expires-after=2d
