name: Base Image Build

on:
  workflow_call:
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_PASSWORD:
        required: true
      QUAY_CHARTS_USERNAME:
        required: true
      QUAY_CHARTS_PASSWORD:
        required: true
    inputs:
      # Used to checkout the source code and as a tag for non-release images.
      sha:
        required: true
        type: string
      # Tag to push. Optional for non-release images - if empty, only the sha tag is pushed.
      tag:
        type: string
      # Release images are pushed to isovalent Quay org, non-release to isovalent-dev.
      is_release:
        type: boolean

jobs:
  build-and-push:
    permissions:
      contents: read
    runs-on: ubuntu-latest-4cores-16gb
    strategy:
      matrix:
        include:
          - name: tetragon
            dockerfile: ./Dockerfile

          - name: tetragon-slim
            dockerfile: ./Dockerfile.slim

          - name: tetragon-aggregator
            dockerfile: ./Dockerfile.aggregator

          - name: tetragon-operator
            dockerfile: ./Dockerfile.operator

    steps:
      - name: Set environment variables
        run: |
          org="${{ github.repository_owner }}"
          if ! ${{ inputs.is_release }}; then
            org="$org-dev"
          fi
          echo "QUAY_ORGANIZATION=$org" >> $GITHUB_ENV

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          platforms: arm64

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to quay.io
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Checkout Source Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.sha }}
          submodules: true
          persist-credentials: false
          fetch-depth: 0

      # TODO: Validate that at least one tag is set. If is_release=true and
      # tag="" then there is no tag to push.
      - name: Get image tags
        id: tags
        run: |
          org="${{ github.repository_owner }}"
          repo="${{ matrix.name }}"
          if ! ${{ inputs.is_release }}; then
            org="$org-dev"
            repo="$repo-ci"
          fi

          echo "tags<<EOF" >> $GITHUB_OUTPUT
          if ! ${{ inputs.is_release }}; then
            echo "quay.io/$org/$repo:${{ inputs.sha }}" >> $GITHUB_OUTPUT
          fi
          if [ -n "${{ inputs.tag }}" ]; then
            echo "quay.io/$org/$repo:${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: build-and-push
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.tags.outputs.tags }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac # v3.9.1

      - name: Sign Container Image
        run: |
          cosign sign -y quay.io/${{ env.QUAY_ORGANIZATION }}/${{ matrix.name }}@${{ steps.build-and-push.outputs.digest }}

      - name: Generate SBOM
        uses: anchore/sbom-action@9246b90769f852b3a8921f330c59e0b3f439d6e9 # v0.20.1
        with:
          artifact-name: sbom_${{ matrix.name }}_${{ steps.tags.outputs.tag }}.spdx.json
          output-file: ./sbom_${{ matrix.name }}_${{ steps.tags.outputs.tag }}.spdx.json
          image: quay.io/${{ env.QUAY_ORGANIZATION }}/${{ matrix.name }}:${{ steps.tags.outputs.tag }}
          upload-release-assets: false

      - name: Attach SBOM attestation to container image
        run: |
          cosign attest -y --predicate sbom_${{ matrix.name }}_${{ steps.tags.outputs.tag }}.spdx.json --type spdxjson quay.io/${{ env.QUAY_ORGANIZATION }}/${{ matrix.name }}@${{ steps.build-and-push.outputs.digest }}

      - name: Image digests
        run: |
          > "digest-${{ matrix.name }}.txt"
          IFS=$'\n'
          for tag in $(cat <<EOF
          ${{ steps.tags.outputs.tags }}
          EOF
          ); do
            echo "$tag@${{ steps.build-and-push.outputs.digest }}" >> "digest-${{ matrix.name }}.txt"
          done
          unset IFS
          echo "" >> "digest-${{ matrix.name }}.txt"

      - name: Upload digests artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: digest-${{ matrix.name }}
          path: digest-${{ matrix.name }}.txt
          retention-days: 1

  image-digests:
    name: Display Digests
    runs-on: ubuntu-24.04
    needs: build-and-push
    permissions:
      actions: read
      contents: read
    steps:
      - name: Getting image tag and making image-digest directory
        id: tag
        run: |
          echo tag=${GITHUB_REF##*/} >> $GITHUB_OUTPUT
          mkdir -p image-digest/
      
      - name: Download digests of all images built
          uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
          with:
            path: image-digest/
            pattern: "*image-digest *"
  
        - name: Image Digests Output
          shell: bash
          run: |
            cd image-digest/
            echo "## Docker Manifests" > ../image-digest-output.txt
            echo "" >> ../image-digest-output.txt
            find -type f -regex ".*image-digest .*" -not -name "makefile-digest.txt" | sort | xargs -d '\n' cat >> ../image-digest-output.txt
  
        - name: Image Makefile Digests
          shell: bash
          run: |
            cd image-digest/
            echo "# File generated by .github/workflows/build-images-base.yml; DO NOT EDIT." > ../Makefile.digests
            echo "# Copyright $(date +'%Y') Authors of Tetragon" >> ../Makefile.digests
            echo "# SPDX-License-Identifier: Apache-2.0" >> ../Makefile.digests
            echo "" >> ../Makefile.digests
            # shellcheck disable=SC2016
            find -type f  -name "makefile-digest.txt" | sort | xargs -d '\n' awk '{print "export " $0}' >> ../Makefile.digests
  
        # Upload artifact digests
        - name: Upload artifact digests
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
          with:
            name: image-digest-output.txt-${{ steps.tag.outputs.tag }}
            path: image-digest-output.txt
  
        # Upload artifact digests
        - name: Upload artifact digests
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
          with:
            name: Makefile.digests-${{ steps.tag.outputs.tag }}
            path: Makefile.digests

  helm-chart:
    if: ${{ success() }}
    name: Push OCI Helm Chart
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    needs: build-and-push
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.sha }}
          submodules: true
          persist-credentials: false
          fetch-depth: 0

      - name: Get chart version
        id: version
        run: |
          echo "chart_version=$(make chart-version)" >> $GITHUB_OUTPUT

      - name: Push OCI Helm dev chart
        uses: cilium/reusable-workflows/.github/actions/push-helm-chart@6ae27958f2f37545bf48e44106b73df05b1f6d12 # v0.1.0
        with:
          name: tetragon
          path: install/kubernetes/tetragon
          version: ${{ steps.version.outputs.chart_version }}
          values_file_changes: |
            {
              "tetragon.image.repository": "quay.io/isovalent-dev/tetragon-ci",
              "tetragon.image.tag": "${{ inputs.sha }}",
              "tetragonAggregator.image.repository": "quay.io/isovalent-dev/tetragon-aggregator-ci",
              "tetragonAggregator.image.tag": "${{ inputs.sha }}",
              "tetragonOperator.image.repository": "quay.io/isovalent-dev/tetragon-operator-ci",
              "tetragonOperator.image.tag": "${{ inputs.sha }}",
            }
          registry: quay.io
          registry_namespace: isovalent-charts-dev
          registry_username: ${{ secrets.QUAY_CHARTS_USERNAME }}
          registry_password: ${{ secrets.QUAY_CHARTS_PASSWORD }}

      - name: Print helm command
        run: |
          echo "Example commands:"
          echo helm template -n tetragon oci://quay.io/isovalent-charts-dev/tetragon --version ${{ steps.version.outputs.chart_version }}
          echo helm install tetragon -n tetragon oci://quay.io/isovalent-charts-dev/tetragon --version ${{ steps.version.outputs.chart_version }}
