name: OLM Image CI Build

on:
  push:
    branches:
      - master
      - v*
  pull_request:
    paths-ignore:
    - "**.md"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-push-prs:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Login to quay.io for CI
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ISOVALENT_DEV_USERNAME }}
          password: ${{ secrets.QUAY_ISOVALENT_DEV_PASSWORD }}

      - name: Getting image tag
        id: tag
        run: |
          if [ ${{ github.event.pull_request.head.sha }} != "" ]; then
            echo "tag=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Source Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          persist-credentials: false
          ref: ${{ steps.tag.outputs.tag }}
          fetch-depth: 0

      - name: Update CSV references
        run: |
          tetragon_img="quay.io/${{ github.repository_owner }}-dev/tetragon-ci:${{ steps.tag.outputs.tag }}"
          tetragon_operator_img="quay.io/${{ github.repository_owner }}-dev/tetragon-operator-ci:${{ steps.tag.outputs.tag }}"
          sed -i "s/quay.io\/isovalent\/tetragon[:@].*\"$/${tetragon_img//\//\\/}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon[:@].*[^\"]$/${tetragon_img//\//\\/}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon-operator[:@].*\"$/${tetragon_operator_img//\//\\/}\"/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/quay.io\/isovalent\/tetragon-operator[:@].*[^\"]$/${tetragon_operator_img//\//\\/}/g" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml
          sed -i "s/^[ ]*name: tetragon-operator\.v.*$/  name: tetragon-operator.${{ steps.tag.outputs.tag }}/" ./install/olm/bundle/manifests/tetragon-operator.clusterserviceversion.yaml

      - name: CI Bundle Build
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: ./install/olm
          file: ./install/olm/bundle.Dockerfile
          push: true
          tags: |
            quay.io/${{ github.repository_owner }}-dev/tetragon-operator-bundle-ci:${{ steps.tag.outputs.tag }}
          labels: quay.expires-after=2d

      - name: Update catalog index references
        run: |
          sed -i  "s/{{CI_VERSION}}/${{ steps.tag.outputs.tag }}/g" ./install/olm/catalog-ci/index.yaml

      - name: CI Catalog Index Build
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: ./install/olm
          file: ./install/olm/catalog-ci.Dockerfile
          push: true
          tags: |
            quay.io/${{ github.repository_owner }}-dev/tetragon-operator-index-ci:${{ steps.tag.outputs.tag }}
          labels: quay.expires-after=2d
