---
name: Trigger kubespec.dev @ Isovalent CRD Deployments
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  id-token: write

jobs:
  dispatch:
    name: Dispatch kubespec.dev workflow event
    runs-on:
      labels: extra-small
      group: isovalent-wait-runners
    steps:
      - name: Get Vault Credentials
        uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc # v4
        with:
          url: ${{ vars.VAULT_URL }}
          method: ${{ vars.VAULT_METHOD }}
          namespace: ${{ vars.VAULT_NAMESPACE }}
          secrets: |
            secret/data/release-mgmt/${{ github.repository_owner }} github_app_pem | GH_WF_DISPATCH_APP_PEM;
            secret/data/release-mgmt/${{ github.repository_owner }} github_app_id | GH_WF_DISPATCH_APP_ID;

      - name: Get Token for kubespec.dev
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ env.GH_WF_DISPATCH_APP_ID }}
          private-key: ${{ env.GH_WF_DISPATCH_APP_PEM }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ${{ vars.CRDS_TARGET_REPO_NAME }}

      - name: Trigger kubespec.dev CRD Deployments
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { repo, owner } = context.repo;
            const target_repo = '${{ vars.CRDS_TARGET_REPO_NAME }}';
            const workflow_id = '${{ vars.CRDS_TARGET_REPO_WORKFLOW_NAME }}';
            const default_branch = '${{ vars.DEFAULT_BRANCH }}';

            const response = await github.rest.actions.createWorkflowDispatch({
              owner: owner,
              repo: target_repo,
              workflow_id: workflow_id,
              ref: default_branch,
            });
