name: Generated files
on:
  push:
    branches:
      - master
      - v*
  pull_request:
jobs:
  generated-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
        with:
          go-version: '1.16.7'
      - name: Validate that generated files are up to date.
        run: |
          make generate
          make -C api/v1 doc
          git diff --exit-code
