name: Generated files
on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master
jobs:
  generated-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate that generated files are up to date.
        run: |
          make generate
          make quick-install
          make -C api/v1 doc
          git diff --exit-code
