name: Check generated docs
on:
  push:
    branches:
      - master
      - v*
    paths:
      - "**"
      - "!docs/**"
      - "!examples/**"
      - "!install/**"
      - "!tests/**"
      - "!contrib/grafana/**"
      - "!**.md"
      - "!**.yaml"
      - docs/metrics/metrics.md
      - docs/configuration/tetragon_flags.yaml
      - .github/workflows/generated-docs.yaml
  pull_request:
    paths:
      - "**"
      - "!docs/**"
      - "!examples/**"
      - "!install/**"
      - "!tests/**"
      - "!contrib/grafana/**"
      - "!**.md"
      - "!**.yaml"
      - docs/metrics/metrics.md
      - docs/configuration/tetragon_flags.yaml
      - .github/workflows/generated-docs.yaml

jobs:
  check-generated-docs:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: "1.25.3"
      - name: Go version
        run: go version
      - name: Check Tetragon daemon flags
        run: |
          set -ex
          make generate-flags
          test -z "$(git status --porcelain)"
          if [ $? != 0 ]; then
            git status
            git diff
            echo "Generated flags reference is outdated."
            echo "Please run 'make generate-flags' and submit your changes."; exit 1
          fi
      - name: Check metrics docs
        run: |
          set -ex
          make metrics-docs
          test -z "$(git status --porcelain)"
          if [ $? != 0 ]; then
            git status
            git diff
            echo "Generated metrics reference is outdated."
            echo "Please run 'make metrics-docs' and submit your changes."; exit 1
          fi
