name: ConformanceGKE

on:
  pull_request:
    paths-ignore:
    - "**.md"
  push:
    branches:
      - master
env:
  zone: us-west2-a
  ciliumCliVersion: v0.12.11
  ciliumVersion: v1.12.4

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 75
    strategy:
      matrix:
        release-channel:
          - 'stable'
          - 'regular'
          # - 'rapid' # Temporarily disabled pending cilium bugfix
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: 'True'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: hubble-fgs
          submodules: true

      - uses: actions/setup-go@v4
        with:
          go-version: '1.18.3'

      - name: Set up job variables
        id: vars
        run: |
          if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
            PR_API_JSON=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.issue.pull_request.url || github.event.pull_request.url }})
            SHA=$(echo "$PR_API_JSON" | jq -r ".head.sha")
          else
            SHA=${{ github.sha }}
          fi
          echo "sha=${SHA}" >> $GITHUB_OUTPUT
          echo "agentImage=quay.io/isovalent-dev/hubble-enterprise-ci:${SHA}" >> $GITHUB_OUTPUT
          echo "operatorImage=quay.io/isovalent-dev/hubble-enterprise-operator-ci:${SHA}" >> $GITHUB_OUTPUT
          echo "clusterName=fgs-cli-ci-${{ github.run_id }}-${{ matrix.release-channel }}" >> $GITHUB_OUTPUT

      - name: Install Cilium CLI
        run: |
          GOOS=$(go env GOOS)
          GOARCH=$(go env GOARCH)
          curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${{ env.ciliumCliVersion }}/cilium-${GOOS}-${GOARCH}.tar.gz{,.sha256sum}
          sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
          sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/bin
          rm cilium-linux-amd64.tar.gz{,.sha256sum}
          cilium version

      - uses: azure/setup-helm@v3
        with:
           version: 'v3.11.0'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@ee9693ff89cdf73862b8a13988f6a71070e8fc58
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          version: "405.0.0"

      - name: install beta component
        run: |
          gcloud components install beta
          gcloud components install gke-gcloud-auth-plugin

      - name: gcloud info
        run: |
          gcloud info

      - name: Create GKE cluster
        id: cluster
        run: |
          gcloud container clusters create ${{ steps.vars.outputs.clusterName }} \
            --preemptible \
            --labels "usage=pr,owner=${{ github.event.pull_request.number }}" \
            --image-type COS_CONTAINERD \
            --num-nodes 2 \
            --machine-type n1-standard-4 \
            --release-channel ${{ matrix.release-channel }} \
            --node-taints node.cilium.io/agent-not-ready=true:NoExecute \
            --zone ${{ env.zone }}

      - name: Get Credentials
        run: |
          gcloud container clusters get-credentials ${{ steps.vars.outputs.clusterName }} --zone ${{ env.zone }}

      - name: Attempt to pull the FGS image
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 30
          retry_wait_seconds: 30
          command: |
            docker pull ${{ steps.vars.outputs.agentImage }}
            docker pull ${{ steps.vars.outputs.operatorImage }}

      - name: Run end-to-end tests
        timeout-minutes: 30
        run: |
          cd hubble-fgs
          export HOST_PROC=/proc
          go test -p 1 -parallel 1 -timeout 20m -failfast -cover ./tests/e2e/tests/... \
            -tetragon.helm.set enterprise.image.override=${{ steps.vars.outputs.agentImage }} \
            -tetragon.helm.set hubbleEnterpriseOperator.image.override=${{ steps.vars.outputs.operatorImage }} \
            -tetragon.keep-export=true \
            -tetragon.cilium-version=${{ env.ciliumVersion }} \
            -cluster-name ${{ steps.vars.outputs.clusterName }} \
            -kubeconfig ~/.kube/config

      - name: Cleanup
        id: cleanup
        if: ${{ always() }}
        run: |
          echo "kernel_version=$(kubectl get node -o go-template='{{(index .items 0).status.nodeInfo.kernelVersion}}')" >> $GITHUB_OUTPUT
          gcloud container clusters delete --quiet ${{ steps.vars.outputs.clusterName }} --zone ${{ env.zone }}
        shell: bash {0}

      - name: Upload Tetragon test artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: tetragon-artifacts
          path: /tmp/tetragon.e2e.*
          retention-days: 5
