name: ConformanceGKE

on:
  pull_request:
    paths-ignore:
    - "**.md"
  push:
    branches:
      - master
env:
  clusterName: fgs-cli-ci-${{ github.run_id }}
  zone: us-west2-a

jobs:
  installation-and-connectivity:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: hubble-fgs
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'

      - name: Set up job variables
        id: vars
        run: |
          if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
            PR_API_JSON=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.issue.pull_request.url || github.event.pull_request.url }})
            SHA=$(echo "$PR_API_JSON" | jq -r ".head.sha")
          else
            SHA=${{ github.sha }}
          fi
          echo ::set-output name=sha::${SHA}
          echo ::set-output name=agentImage::quay.io/isovalent/hubble-enterprise-ci:${SHA}
          echo ::set-output name=operatorImage::quay.io/isovalent/hubble-enterprise-operator-ci:${SHA}

      - name: Install Cilium CLI
        run: |
          curl -sSL --remote-name-all https://github.com/cilium/cilium-cli/releases/download/v0.10.4/cilium-linux-amd64.tar.gz{,.sha256sum}
          sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
          sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/bin
          rm cilium-linux-amd64.tar.gz{,.sha256sum}
          cilium version

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: install beta component
        run: gcloud components install beta

      - name: gcloud info
        run: |
          gcloud info

      - name: Create GKE cluster
        id: cluster
        run: |
          gcloud container clusters create ${{ env.clusterName }} \
            --preemptible \
            --labels "usage=pr,owner=${{ github.event.pull_request.number }}" \
            --image-type COS_CONTAINERD \
            --num-nodes 2 \
            --machine-type n1-standard-4 \
            --node-taints node.cilium.io/agent-not-ready=true:NoExecute \
            --zone ${{ env.zone }}
          CLUSTER_CIDR=$(gcloud container clusters describe ${{ env.clusterName }} --zone ${{ env.zone }} --format="value(clusterIpv4Cidr)")
          echo ::set-output name=cluster_cidr::${CLUSTER_CIDR}

      - name: Get Credentials
        run: |
          gcloud container clusters get-credentials ${{ env.clusterName }} --zone ${{ env.zone }}

      - name: Attempt to pull the FGS image
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 30
          retry_wait_seconds: 30
          command: |
            docker pull ${{ steps.vars.outputs.agentImage }}
            docker pull ${{ steps.vars.outputs.operatorImage }}

      - name: Run end-to-end tests
        run: |
          cd hubble-fgs
          go test -p 1 -parallel 1 -timeout 20m -failfast -cover ./tests/e2e/tests/... \
            -tetragon.helm.set enterprise.image.override=${{ steps.vars.outputs.agentImage }} \
            -tetragon.helm.set hubbleEnterpriseOperator.image.override=${{ steps.vars.outputs.operatorImage }} \
            -tetragon.keep-export=true \
            -cluster-name ${{ env.clusterName }} \
            -kubeconfig ~/.kube/config

      - name: Cleanup
        id: cleanup
        if: ${{ always() }}
        run: |
          echo ::set-output name=kernel_version::$(kubectl get node -o go-template='{{(index .items 0).status.nodeInfo.kernelVersion}}')
          gcloud container clusters delete --quiet ${{ env.clusterName }} --zone ${{ env.zone }}
        shell: bash {0}

      - name: Upload Tetragon test artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: tetragon-artifacts
          path: /tmp/tetragon.e2e.*
          retention-days: 5
