name: ConformanceGKE

on:
  pull_request:
  push:
    branches:
      - master
env:
  clusterName: fgs-cli-ci-${{ github.run_id }}
  zone: us-west2-a

jobs:
  installation-and-connectivitiy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: hubble-fgs

      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.17.0'

      - name: Set up job variables
        id: vars
        run: |
          if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
            PR_API_JSON=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.issue.pull_request.url || github.event.pull_request.url }})
            SHA=$(echo "$PR_API_JSON" | jq -r ".head.sha")
          else
            SHA=${{ github.sha }}
          fi
          echo ::set-output name=sha::${SHA}

      - name: Install Cilium CLI
        run: |
          curl -LO https://github.com/cilium/cilium-cli/releases/download/v0.9.0/cilium-linux-amd64.tar.gz
          sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/bin
          rm cilium-linux-amd64.tar.gz

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: install beta component
        run: gcloud components install beta

      - name: gcloud info
        run: |
          gcloud info

      - name: Create GKE cluster
        run: |
          gcloud container clusters create ${{ env.clusterName }} \
            --preemptible \
            --labels "usage=pr,owner=${{ github.event.pull_request.number }}" \
            --image-type COS \
            --num-nodes 2 \
            --machine-type n1-standard-4 \
            --zone ${{ env.zone }}

      - name: Get Credentials
        run: |
          gcloud container clusters get-credentials ${{ env.clusterName }} --zone ${{ env.zone }}

      - name: Install cilium
        run: |
          cilium install \
            --cluster-name=${{ env.clusterName }} \
            --restart-unmanaged-pods=false \
            --config monitor-aggregation=none \

      - name: Enable Relay
        run: |
          cilium hubble enable

      - name: Status
        run: |
          cilium status --wait

      - name: Relay Port Forward
        run: |
          kubectl port-forward -n kube-system deployment/hubble-relay 4245:4245&
          sleep 5s

      - name: Wait for image to be available
        timeout-minutes: 10
        shell: bash
        run: |
          until curl --silent -f -lSL "https://quay.io/api/v1/repository/${{ github.repository_owner }}/hubble-enterprise-ci/tag/${{ steps.vars.outputs.sha }}/images" &> /dev/null; do sleep 45s; done

      - name: Install FGS
        run: |
          helm repo add isovalent https://helm.isovalent.com
          helm repo update
          helm install hubble-enterprise isovalent/hubble-enterprise \
                 --version 9999.9999.9999-dev \
                 --set enterprise.image.repository=quay.io/isovalent/hubble-enterprise-ci \
                 --set enterprise.image.tag=${{ steps.vars.outputs.sha }} \
                 --namespace kube-system

      - name: Wait for FGS pods to become ready
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 5
          command: |
            kubectl wait -n kube-system --for=condition=Ready --all pod -l app.kubernetes.io/name=hubble-enterprise --timeout=30s

      - name: Demo Application
        run: |
          kubectl create namespace tenant-jobs
          kubectl -n tenant-jobs apply -f https://docs.isovalent.com/public/jobs-app-attack.yaml

      - name: Wait for demo app pods to become ready
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 5
          command: |
            kubectl wait -n tenant-jobs --for=condition=Ready --all pod --timeout=30s

      # Let the demo app do its thing to generate all the events. Would be nice if we could avoid sleeping.
      - name: Sleep
        run: sleep 60

      - name: Cleanup
        if: ${{ always() }}
        run: |
          cilium status
          kubectl get pods --all-namespaces -o wide
          curl -sLO https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip
          python cilium-sysdump.zip --output cilium-sysdump-out
          kubectl get pods --selector=app.kubernetes.io/name=hubble-enterprise \
              -n kube-system -o custom-columns=name:metadata.name --no-headers \
              | xargs -I{} sh -c 'kubectl logs -c enterprise -n kube-system {} > ./hubble-enterprise-pod-{}.log'
          kubectl get pods --selector=app.kubernetes.io/name=hubble-enterprise \
              -n kube-system -o custom-columns=name:metadata.name --no-headers \
              | xargs -I{} kubectl cp -c enterprise -n kube-system {}:/var/run/cilium/hubble/fgs.log ./hubble-fgs-{}-fgs.log
          cat ./hubble-fgs*.log >> fgs.log
          gcloud container clusters delete --quiet ${{ env.clusterName }} --zone ${{ env.zone }}
        shell: bash {0}

      - name: Verify FGS
        if: ${{ always() }}
        run: |
          sudo apt install libelf-dev
          cd hubble-fgs
          sudo -E make tools-install LIBBPF_INSTALL_DIR=/usr/local/lib CLANG_INSTALL_DIR=/usr/bin
          sudo -E ldconfig /usr/local/
          go mod verify
          go run ./tests/jobs.trace.go ../fgs.log
      - name: Upload Cilium Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cilium-sysdump-out.zip
          path: cilium-sysdump-out.zip
          retention-days: 5

      - name: Upload FGS pod logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: hubble-enterprise-logs
          path: ./hubble-enterprise-pod*.log
          retention-days: 5

      - name: Upload FGS Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: fgs.log
          path: fgs.log
          retention-days: 5
