name: HubbleFGS Go Test
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "contrib/grafana/**"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      actions: read
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm64 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: true

    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        # renovate: datasource=golang-version depName=go
        go-version: '1.27.1'

    - name: Install dependencies x86
      run: |
        if [ "$RUNNER_ARCH" == "X64" ]; then
          sudo apt-get update
          sudo apt-get -y install libc6-dev-i386 gh
        fi

    - name: Install socat x86
      env:
        GH_TOKEN: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}
      run: |
        if [ "$RUNNER_ARCH" == "X64" ]; then
          gh --repo isovalent/socat release download tag-1.8.1.1 -O ~/socat -p socat-x86
          sudo chmod a+x ~/socat
          sudo ln -s ~/socat /usr/bin
          which socat
          socat -V
        fi

    - name: Install dependencies ARM
      run: |
        if [ "$RUNNER_ARCH" == "ARM64" ]; then
          sudo apt-get update
          sudo apt-get -y install gcc-arm-linux-gnueabihf gh
        fi

    - name: Install socat ARM
      env:
        GH_TOKEN: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}
      run: |
        if [ "$RUNNER_ARCH" == "ARM64" ]; then
          gh --repo isovalent/socat release download tag-1.8.1.1 -O ~/socat -p socat-arm
          sudo chmod a+x ~/socat
          sudo ln -s ~/socat /usr/bin
          which socat
          socat -V
        fi

    - name: Run go tests
      env:
        GOPATH: ${{ env.GITHUB_WORKSPACE }}/go
      run: |
        docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }}
        sudo apt update -y
        sudo apt install libelf-dev netcat-openbsd netcat-traditional libcap-dev libaio-dev liburing-dev iproute2 net-tools pahole llvm libnet1 libnet1-dev
        export PATH=${GOPATH}/bin:${PATH}
        sudo -E echo "copy build tools from images"
        sudo sed -i '/secure_path/d' /etc/sudoers
        sudo sed -i '/env_reset/d' /etc/sudoers
        echo `which clang`
        echo `which llc`
        echo `clang --version`
        make check-copyright
        sudo make tetragon-bpf
        sudo -E echo "run go tests: " `uname -a`
        export FGS_LIB="$(pwd)/bpf/objs/"
        sudo apt install gcc # needed for tester-progs
        sudo -E make tetragon-fs-scanner
        sudo -E make tester-progs
        export FLAKY_HTTP=1
        sudo -E make test GO_TEST_TIMEOUT=60m SUDO="sudo -E"

    - name: Upload FGS logs
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: hubble-fgs-json
        path: /tmp/tetragon.gotest*
        retention-days: 5

    - name: Upload bugtool dumps
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: tetragon-bugtool
        path: /tmp/tetragon-bugtool*
        retention-days: 5

    - name: Upload modeltest dumps
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: modeltest-json
        path: /tmp/TestModel*
        retention-days: 5

  # This job ensures that the plain vanilla "go test" command passes without any
  # external dependencies. It's a wonderful thing.
  unit-test:
    runs-on: ubuntu-26.04
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: true

    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        # renovate: datasource=golang-version depName=go
        go-version: '1.27.1'

    - name: Run unit tests
      run: |
        go test ./...

    # NB: run some simple tests for packages that have no trivial nok8s code
    - name: Run unit tests (nok8s)
      run: |
        go test -tags nok8s ./pkg/mandate ./pkg/sandboxpolicy ./pkg/alerts
