name: HubbleFGS Go Test
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "contrib/grafana/**"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm64 ]
    steps:
    - name: Install Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        # renovate: datasource=golang-version depName=go
        go-version: '1.23.4'
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        path: go/src/github.com/isovalent/hubble-fgs/
        submodules: true

    - name: Install dependencies x86
      run: |
        if [ "$RUNNER_ARCH" == "X64" ]; then
          sudo apt-get update
          sudo apt-get -y install libc6-dev-i386
        fi

    - name: Install dependencies ARM
      run: |
        if [ "$RUNNER_ARCH" == "ARM64" ]; then
          sudo apt-get update
          sudo apt-get -y install gcc-arm-linux-gnueabihf
        fi

    - name: Run go tests
      env:
        GOPATH: ${{ env.GITHUB_WORKSPACE }}/go
      run: |
        docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }}
        sudo apt update -y
        sudo apt install libelf-dev netcat-openbsd netcat-traditional socat libcap-dev libaio-dev liburing-dev iproute2 net-tools
        export PATH=${GOPATH}/bin:${PATH}
        sudo -E echo "copy build tools from images"
        cd ${GITHUB_WORKSPACE}/go/src/github.com/isovalent/hubble-fgs
        sudo sed -i '/secure_path/d' /etc/sudoers
        sudo sed -i '/env_reset/d' /etc/sudoers
        echo `which clang`
        echo `which llc`
        echo `clang --version`
        make check-copyright
        sudo make hubble-bpf
        sudo -E echo "run go tests: " `uname -a`
        export FGS_LIB="${GITHUB_WORKSPACE}/go/src/github.com/isovalent/hubble-fgs/bpf/objs/"
        sudo apt install gcc # needed for tester-progs
        sudo -E make tetragon-fs-scanner
        sudo -E make tester-progs
        export FLAKY_HTTP=1
        sudo -E make test GO_TEST_TIMEOUT=60m SUDO="sudo -E"

    - name: Upload FGS logs
      if: failure()
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: hubble-fgs-json
        path: /tmp/tetragon.gotest*
        retention-days: 5

    - name: Upload bugtool dumps
      if: failure()
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: tetragon-bugtool
        path: /tmp/tetragon-bugtool*
        retention-days: 5
