name: HubbleFGS Go Test
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    steps:
    - uses: actions/checkout@master
      with:
        path: go/src/github.com/covalentio/hubble-fgs/
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14'
    - name: Run go tests
      env:
        GOPATH: /home/runner/work/hubble-fgs/hubble-fgs/go
      run: |
        docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }}
        sudo apt install libelf-dev netcat-traditional
        export PATH=/opt/hostedtoolcache/go/1.13.4/x64/bin:${GOPATH}/bin:${PATH}
        docker run --name libbpf quay.io/isovalent/hubble-libbpf:v0.2.2
        docker run --name llvm quay.io/isovalent/hubble-llvm:2020-11-25-194d3985-x86
        sudo -E echo "copy build tools from images"
        sudo -E docker cp libbpf:/go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0.2.0 /usr/local/lib/
        sudo -E docker cp libbpf:/go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0     /usr/local/lib/
        sudo -E docker cp libbpf:/go/src/github.com/covalentio/hubble-fgs/src/libbpf.so       /usr/local/lib/
        sudo -E docker cp libbpf:/go/src/github.com/covalentio/hubble-fgs/src/libbpf.a        /usr/local/lib/
        sudo -E docker cp llvm:/usr/local/bin/clang-11 /usr/bin/clang
        sudo -E docker cp llvm:/usr/local/bin/llc /usr/bin/llc
        sudo -E ldconfig /usr/local/
        export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        export PATH=/usr/local/bin:$PATH
        sudo sed -i '/secure_path/d' /etc/sudoers
        sudo sed -i '/env_reset/d' /etc/sudoers
        cd /home/runner/work/hubble-fgs/hubble-fgs/go/src/github.com/covalentio/hubble-fgs
        sudo -E ./contrib/vmlinux-builder/apt-get-btf.sh
        echo `which clang`
        echo `which llc`
        echo `clang --version`
        make hubble-bpf
        sudo -E echo "run go tests: " `uname -a`
        sudo -E go mod verify
        sudo -E GO111MODULE=off go get -u golang.org/x/lint/golint
        sudo -E make test
