name: HubbleFGS Kata Go tests
on:
  workflow_dispatch:
  push:
env:
  zone: europe-west4-c
  vmName: kata-test-gh-${{ github.run_number }}
  vmHost: kata-test-gh-${{ github.run_number }}.europe-west4-c.${{ secrets.GCP_PROJECT_ID }}
  machineImage: projects/${{ secrets.GCP_PROJECT_ID }}/global/machineImages/kata-test-20210315-154212
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: hubble-fgs
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: install beta component
      run: gcloud components install beta
    - name: info
      run: |
        gcloud info
    - name: create VM
      run: |
        gcloud beta compute instances create ${{ env.vmName }} --quiet --zone ${{ env.zone }}  --min-cpu-platform "Intel Haswell" --source-machine-image ${{ env.machineImage }} --machine-type n1-standard-2
    - name: setting up ssh to VM
      run: |
        sudo apt-get -y install openssh-client
        gcloud compute ssh ${{ env.vmName }} --zone ${{ env.zone }} --command="uname -a"
        gcloud compute config-ssh
        ssh ${{ env.vmHost }} uname -a
    - name: build docker image in VM
      id: build
      run: |
        cd hubble-fgs
        git archive --prefix hubble-fgs/ HEAD | gzip | ssh ${{ env.vmHost }} 'tar zx'
        ssh ${{ env.vmHost }} 'cd hubble-fgs && sudo docker build -f Dockerfile.dev -t hubble-fgs-dev .'
        touch BUILD_OK
    - name: test kernel 5.10
      if: ${{ always() }}
      run: |
        [ -f BUILD_OK ] && echo "Build OK!"
        ssh -t -t ${{ env.vmHost }} "sh -c 'KATA_IMG=/home/kkourt/hubble-builder/kata-tester/contrib/kata-img hubble-fgs/contrib/gh-kata-tester.sh 5.10 hubble-fgs-dev'"
    - name: test kernel 5.4
      if: ${{ always() }}
      run: |
        [ -f BUILD_OK ] && echo "Build OK!"
        ssh -t -t ${{ env.vmHost }} "sh -c 'KATA_IMG=/home/kkourt/hubble-builder/kata-tester/contrib/kata-img hubble-fgs/contrib/gh-kata-tester.sh 5.4 hubble-fgs-dev'"
    - name: test kernel 4.19
      if: ${{ always() }}
      run: |
        [ -f BUILD_OK ] && echo "Build OK!"
        ssh -t -t ${{ env.vmHost }} "sh -c 'KATA_IMG=/home/kkourt/hubble-builder/kata-tester/contrib/kata-img hubble-fgs/contrib/gh-kata-tester.sh 4.19 hubble-fgs-dev'"
    - name: destroy VM
      if: ${{ always() }}
      run: |
        gcloud beta compute instances delete ${{ env.vmName }} --quiet --zone ${{ env.zone }}
