name: Kind Integration Test
on:
  pull_request: {}
jobs:
  kind-integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        # checkout pull request head ref so that "make chart-version" prints the correct chart version.
        ref: ${{ github.event.pull_request.head.ref }}
        # required for git describe used by "make chart-version"
        fetch-depth: 0
        submodules: true

    - name: Get Helm dev chart version
      id: version
      run: |
        echo "version=$(make chart-version)" >> $GITHUB_OUTPUT

    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        # renovate: datasource=golang-version depName=go
        go-version: '1.24.5'

    - name: Install the latest Cilium CLI
      run: |
        curl -sSL --remote-name-all https://github.com/isovalent/cilium-cli-releases/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}
        sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
        tar xzvfC cilium-linux-amd64.tar.gz /tmp
        sudo install /tmp/cilium /usr/local/bin
        rm cilium-linux-amd64.tar.gz{,.sha256sum} /tmp/cilium

    - name: Install Kind and create cluster
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0

    - name: Wait for Helm dev chart to be available
      timeout-minutes: 15
      shell: bash
      run: |
        until helm pull oci://quay.io/isovalent-charts-dev/tetragon --version ${{ steps.version.outputs.version }}; do sleep 30s; done

    - name: Run go integration tests
      run: |
        helm install tetragon -n tetragon --create-namespace oci://quay.io/isovalent-charts-dev/tetragon \
          --version ${{ steps.version.outputs.version }} \
          --set tetragonOperator.podInfo.enabled=true
        go test --tags=integration -v ./pkg/manager

    - name: Capture sysdump
      if: ${{ always() }}
      run: |
        kubectl get pods --all-namespaces -o wide
        cilium sysdump --output-filename "tetragon-sysdump-<ts>" --tetragon-namespace tetragon
      shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently

    - name: Upload sysdump
      if: ${{ always() }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: tetragon-sysdump
        path: tetragon-sysdump-*.zip
        retention-days: 5
