name: KVM Go Tests Arch

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner_label:
        required: true
        type: string
      apt_packages:
        required: true
        type: string
      socat_filename:
        required: true
        type: string
    secrets:
      ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES:
        description: 'Our secret token'
        required: true

jobs:
  build:
    name: Build Tetragon
    runs-on: ${{ inputs.runner_label }}
    timeout-minutes: 30
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow_ref }}-${{ inputs.arch }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: go/src/github.com/isovalent/tetragon/
          submodules: true
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: '1.27.1'
      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ${{ inputs.apt_packages }}
      - name: Install socat
        env:
          GH_TOKEN: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}
        run: |
          gh --repo isovalent/socat release download tag-1.8.1.1 -O ~/socat -p ${{ inputs.socat_filename }}
          sudo chmod a+x ~/socat
          sudo ln -s ~/socat /usr/bin
          which socat
          socat -V
      - name: Build Base build
        env:
          GOPATH: /home/runner/work/tetragon/tetragon/go
        run: |
          cd go/src/github.com/isovalent/tetragon/
          EXTRA_BUILD_FLAGS='-static' make tester-progs tetragon-bpf tetragon-bpf-test tetragon-fs-scanner
      - name: Tar Base build
        run: |
          cd go/src/github.com/isovalent/
          tar cz --exclude='tetragon/.git' -f /tmp/tetragon-${{ inputs.arch }}.tar ./tetragon
      - name: Upload Base build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tetragon-build-${{ inputs.arch }}
          path: /tmp/tetragon-${{ inputs.arch }}.tar
          retention-days: 5
      - name: Build LSEG build
        if: ${{ inputs.arch == 'amd64' }}
        env:
          GOPATH: /home/runner/work/tetragon/tetragon/go
        run: |
          cd go/src/github.com/isovalent/tetragon/
          make clean
          EXTRA_BUILD_FLAGS='-static' make LSEG=1 tester-progs tetragon-bpf tetragon-bpf-test tetragon-fs-scanner
      - name: Tar LSEG build
        if: ${{ inputs.arch == 'amd64' }}
        run: |
          cd go/src/github.com/isovalent/
          rm /tmp/tetragon-${{ inputs.arch }}.tar
          tar cz --exclude='tetragon/.git' -f /tmp/tetragon-${{ inputs.arch }}.tar ./tetragon
      - name: Upload build
        if: ${{ inputs.arch == 'amd64' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tetragon-build-lseg-${{ inputs.arch }}
          path: /tmp/tetragon-${{ inputs.arch }}.tar
          retention-days: 5

  run-tests:
    name: Run tests (${{ matrix.kernel }}, ${{ matrix.variation }})
    strategy:
      fail-fast: false
      matrix:
        variation: [BASE, LSEG]
        arch:
          - ${{ inputs.arch }}
        kernel:
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "bpf-next-20260928.013030"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "rhel8.10-20260928.013030"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "6.18-20260928.013030"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "6.12-20260928.013030"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "6.6-20260928.013030"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "6.1-20260928.013030"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "5.15-20260928.013030"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "5.10-20260928.013030"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "5.4-20260928.013030"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "4.19-20260928.013030"
        exclude:
          - arch: arm64
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: "rhel8.10-20260928.013030"
          - variation: LSEG # LSEG are not running on ARM
            arch: arm64
          - variation: LSEG # LSEG only need kernels >=v6.12
            arch: amd64
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: "rhel8.10-20260928.013030"
          - variation: LSEG # LSEG only need kernels >=v6.12
            arch: amd64
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: "6.6-20260928.013030"
          - variation: LSEG # LSEG only need kernels >=v6.12
            arch: amd64
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: "6.1-20260928.013030"
          - variation: LSEG # LSEG only need kernels >=v6.12
            arch: amd64
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: "5.15-20260928.013030"
          - variation: LSEG # LSEG only need kernels >=v6.12
            arch: amd64
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: "5.10-20260928.013030"
          - variation: LSEG # LSEG only need kernels >=v6.12
            arch: amd64
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: "5.4-20260928.013030"
          - variation: LSEG # LSEG only need kernels >=v6.12
            arch: amd64
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: "4.19-20260928.013030"
    runs-on: ${{ inputs.runner_label }}
    needs: [build]
    timeout-minutes: 120
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow_ref }}-${{ inputs.arch }}-${{ matrix.kernel }}-${{ matrix.variation }}
      cancel-in-progress: true
    permissions:
      contents: read
      actions: read
    steps:
      - name: Get CPU and Memory
        id: get-cpu-mem
        run: |
          echo "cpu=$(( $(nproc) / 2 ))" >> $GITHUB_OUTPUT
          echo "mem=$(cat /proc/meminfo | awk '/^MemTotal:/{print int($2/1024/1024/2)}')G" >> $GITHUB_OUTPUT
    
      - name: download Base build data
        if: ${{ matrix.variation != 'LSEG' }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tetragon-build-${{ inputs.arch }}

      - name: download LSEG build data
        if: ${{ matrix.variation == 'LSEG' }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tetragon-build-lseg-${{ inputs.arch }}

      - name: extract build data
        run: |
          mkdir -p go/src/github.com/isovalent/
          tar xf tetragon-${{ inputs.arch }}.tar -C go/src/github.com/isovalent

      - name: Provision LVH VM and run tests
        id: provision-lvh-vm
        uses: cilium/little-vm-helper@5ae749011735fd77f30f38add52f1a53a5568671 # v0.0.30
        with:
          install-dependencies: true
          test-name: tetragon-unit-tests
          image: kind
          image-version: '${{ matrix.kernel }}'
          images-folder-parent:  ${{ github.workspace }}/.github/lvh-action-cache
          kernel-version: ${{ inputs.arch == 'arm64' && matrix.kernel || '' }}
          host-mount: ./
          mem: ${{ steps.get-cpu-mem.outputs.mem }}
          cpu: ${{ steps.get-cpu-mem.outputs.cpu }}
          cpu-kind: host
          arch: ${{ inputs.arch }}
          cmd: |
            set -euxo pipefail

            systemd-detect-virt
            systemd-detect-virt | grep -Eiq 'kvm|qemu' || { echo 'No KVM or QEMU support detected! Bailing out...'; exit 1; }

            cd /host/go/src/github.com/isovalent/tetragon/
            ln -s -f /host/go/src/github.com/isovalent/tetragon/modules/tetragon-oss/contrib vendor/github.com/cilium/tetragon/

            mkdir /build
            export GOTMPDIR=/build

            # copy btf file
            mkdir -p bpf/objs
            ln -vsnf /boot/btf-\$(uname -r) bpf/objs/btf

            export KVM_CI=true
            export SUDO=
            case "${{ matrix.kernel }}" in
              bpf-next-*)
                # FIXME: TestCGTLS13 fails on bpf-next kernels.
                export FLAKY_HTTP=1
                ;;
              6.12-*|6.18-*|6.6-*|6.1-*|5.15-*|5.10-*)
                # FIXME: TestTLS13 fails on these kernels.
                export FLAKY_HTTP=1
                ;;
            esac

            export CGO_ENABLED=0
            if [[ ${{ matrix.variation }} != LSEG ]]; then
              make test-nodeps 2>&1 | tee /tmp/test-output-${{ inputs.arch }}-${{ matrix.kernel }}-${{ matrix.variation }}.log
            else
              make test-nodeps-lseg 2>&1 | tee /tmp/test-output-${{ inputs.arch }}-${{ matrix.kernel }}-${{ matrix.variation }}.log
            fi

      - name: Copy out Tetragon logs
        if: ${{ failure() || cancelled() }}
        timeout-minutes: 15
        run: |
          # Make output dirs for logs
          mkdir -p logs/unit-tests
          mkdir -p logs/model-test-dumps
          mkdir -p logs/test-output

          # Copy logs over
          scp -P 2222 'root@localhost:/tmp/*.yaml' logs/unit-tests || true
          scp -P 2222 'root@localhost:/tmp/*.json' logs/unit-tests || true
          scp -P 2222 'root@localhost:/tmp/*bugtool*' logs/unit-tests || true
          scp -P 2222 'root@localhost:/tmp/TestModel*' logs/model-test-dumps || true
          scp -P 2222 'root@localhost:/tmp/test-output-*.log' logs/test-output || true

      # AWS Baremetal Instances do not honor shutdown signals when QEMU VMs are running
      # Cleanup by force killing QEMU processes
      - name: Delete LVH VM
        if: ${{ always() && steps.provision-lvh-vm.outcome == 'success' }}
        run: sudo pkill -9 qemu-system

      - name: Upload unit test logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tetragon-unit-tests-${{ matrix.kernel }}-${{ inputs.arch }}-${{ matrix.variation }}
          path: logs/unit-tests
          retention-days: 5

      - name: Upload test output log
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-output-${{ matrix.kernel }}-${{ inputs.arch }}-${{ matrix.variation }}
          path: logs/test-output
          retention-days: 5

      - name: Upload modeltest dumps
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: modeltest-json-${{ matrix.kernel }}-${{ inputs.arch }}-${{ matrix.variation }}
          path: logs/model-test-dumps
          retention-days: 5

  post-test:
    name: Cleanup
    runs-on: ${{ inputs.runner_label }}
    needs: [run-tests]
    if: ${{ needs.run-tests.result == 'success' }}
    steps:
      # Delete built binaries from artifacts in case of success.
      - uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
        with:
          name: tetragon-build-${{ inputs.arch }}
