name: KVM e2e Tests

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}-kvm-e2e
  cancel-in-progress: true

env:
  ciliumCliVersion: v0.12.11
  ciliumVersion: v1.12.6

jobs:
  ensure-image-available:
    runs-on: ubuntu-22.04
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: hubble-fgs
          submodules: true

      - name: Set up job variables
        id: vars
        run: |
          if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
            PR_API_JSON=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.issue.pull_request.url || github.event.pull_request.url }})
            SHA=$(echo "$PR_API_JSON" | jq -r ".head.sha")
          else
            SHA=${{ github.sha }}
          fi
          echo "sha=${SHA}" >> $GITHUB_OUTPUT
          echo "agentImage=quay.io/isovalent-dev/tetragon-ci:${SHA}" >> $GITHUB_OUTPUT
          echo "operatorImage=quay.io/isovalent-dev/tetragon-operator-ci:${SHA}" >> $GITHUB_OUTPUT
          echo "olmIndexImage=quay.io/isovalent-dev/tetragon-operator-index-ci:${SHA}" >> $GITHUB_OUTPUT

      - name: Attempt To Pull Docker Images
        uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
        with:
          timeout_minutes: 2
          max_attempts: 60
          retry_wait_seconds: 60
          command: |
            set -e
            docker pull ${{ steps.vars.outputs.agentImage }}
            docker pull ${{ steps.vars.outputs.operatorImage }}
            docker pull ${{ steps.vars.outputs.olmIndexImage }}

  run-tests:
    needs: ensure-image-available
    runs-on:
      - majestic-ketchup-light
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        kernel:
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - 'rhel8-20240404.144247'
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - 'bpf-next-20240618.013132'
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "6.6-20240612.090637"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "6.1-20240612.090637"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "5.15-20240612.090637"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "5.10-20240612.090637"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "5.4-20240612.090637"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "4.19-20240612.090637"
        testDir:
          # Tests run after Tetragon has been deployed with helm
          - 'helm'
          # Tests run after Tetragon has been deployed with OLM
          - 'olm'
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: hubble-fgs
          submodules: true

      - name: Set up job variables
        id: vars
        run: |
          if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
            PR_API_JSON=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.issue.pull_request.url || github.event.pull_request.url }})
            SHA=$(echo "$PR_API_JSON" | jq -r ".head.sha")
          else
            SHA=${{ github.sha }}
          fi
          echo "sha=${SHA}" >> $GITHUB_OUTPUT
          echo "agentImage=quay.io/isovalent-dev/tetragon-ci:${SHA}" >> $GITHUB_OUTPUT
          echo "operatorImage=quay.io/isovalent-dev/tetragon-operator-ci:${SHA}" >> $GITHUB_OUTPUT
          echo "olmIndexImage=quay.io/isovalent-dev/tetragon-operator-index-ci:${SHA}" >> $GITHUB_OUTPUT

      - name: Update OLM catalog index
        env:
          # renovate: datasource=github-releases depName=mikefarah/yq
          yq_version: 4.44.2
        run: |
            set -eux
            # Point to the newly built CI catalog index tests/e2e/olm/catalogsource.yaml
            docker run -i --rm -v "${PWD}"/hubble-fgs:/workdir -u "$(id -u)" mikefarah/yq:${yq_version} e -i ".spec.image = \"${{ steps.vars.outputs.olmIndexImage }}\"" /workdir/tests/e2e/olm/catalogsource.yaml

      - name: Install Cilium CLI
        run: |
          GOOS=$(go env GOOS)
          GOARCH=$(go env GOARCH)
          curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${{ env.ciliumCliVersion }}/cilium-${GOOS}-${GOARCH}.tar.gz{,.sha256sum}
          sha256sum --check cilium-${GOOS}-${GOARCH}.tar.gz.sha256sum
          sudo tar -xzvf cilium-${GOOS}-${GOARCH}.tar.gz
          rm cilium-${GOOS}-${GOARCH}.tar.gz{,.sha256sum}

      - name: Provision LVH VM
        uses: cilium/little-vm-helper@97c89f004bd0ab4caeacfe92ebc956e13e362e6b # v0.0.19
        with:
          install-dependencies: true
          test-name: tetragon-e2e
          image: kind
          image-version: "${{ matrix.kernel }}"
          host-mount: ./
          ssh-port: 2222
          mem: 8G
          cpu: 2
          cpu-kind: host
          cmd: |
            set -eux

            systemd-detect-virt
            (systemd-detect-virt | grep -q -i kvm) || { echo 'No KVM support detected! Bailing out...'; exit 1; }

            cd /host/hubble-fgs

            # wait for network to be available
            while true;
            do
              wget --spider -q -T 10  http://google.com && break
              sleep 10
            done

            mv /host/cilium /bin/cilium
            for i in {1..5}; do
              curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash && break || sleep 60
              if [ \$i -eq 5 ]; then
                echo "Failed to install Helm after 5 tries"
                exit 1 
              fi
            done

      - name: Pull Docker Images
        run: |
          set -e
          docker pull ${{ steps.vars.outputs.agentImage }}
          docker pull ${{ steps.vars.outputs.operatorImage }}

      - name: Load Docker Images Into LVH
        run: |
          docker save ${{ steps.vars.outputs.agentImage }} ${{ steps.vars.outputs.operatorImage }} | ssh -p 2222 root@localhost -o "StrictHostKeyChecking=no" "docker load"

      - name: Run Tests
        uses: cilium/little-vm-helper@97c89f004bd0ab4caeacfe92ebc956e13e362e6b # v0.0.19
        with:
          provision: "false"
          cmd: |
            set -eux
            cd /host/hubble-fgs
            export HOST_PROC=/procRoot
            if [[ ${{ matrix.kernel }} == 4.19-* ]]; then
              export E2E_BTF=/boot/btf-\$(uname -r)
            else
              export E2E_BTF=/sys/kernel/btf/vmlinux
            fi
            make e2e-test                                          \
              E2E_BUILD_IMAGES=0                                   \
              E2E_EXTRA_GOTEST_FLAGS="-failfast"                   \
              E2E_AGENT=${{ steps.vars.outputs.agentImage }}       \
              E2E_OPERATOR=${{ steps.vars.outputs.operatorImage }} \
              E2E_TESTS="./tests/e2e/tests/${{ matrix.testDir }}/..."  \
              E2E_EXTRA_TEST_FLAGS="-tetragon.cilium-version=${{ env.ciliumVersion }} -tetragon.helm.set tetragon.extraArgs.fim-fifo-path=/tetragonExport -v"

      - name: Copy out e2e test logs
        if: ${{ failure() || cancelled() }}
        run: |
          rm -rf logs/e2e
          mkdir -p logs/e2e
          scp -r -P 2222 'root@localhost:/tmp/tetragon.e2e.*' logs/e2e/

      - name: Upload end-to-end test logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: tetragon-e2e-${{ matrix.kernel }}-${{ matrix.testDir }}
          path: logs/e2e
          retention-days: 5
