name: BPF Nightly Go Tests

on:
  pull_request:
    paths-ignore:
    - "**.md"
  workflow_dispatch: {}
  schedule:
    - cron:  '0 3 * * *'
  push:
    branches:
      - master

# We don't want multiple copies of this job to be running for a single PR (for example,
# after a rebase). So cancel in-progress jobs for the same ref head jobs when we start the
# workflow.
concurrency:
  group: ${{ github.ref }}-bpf-nightly-gotests
  cancel-in-progress: true

env:
  # Version of the little-vm-helper image
  lvh-version: 'v0.0.2'
  # Version of the root filesystem image
  root-image-version: '5.15'

jobs:
  # Build the latest BPF nightly master kernel. We run this part of the workflow on the
  # basic ubuntu-22.04 VM rather than a large runner because it should be cheaper that
  # way.
  #
  # While it _does_ slow down job by quite a bit, we cache the resulting vmlinuz image for
  # the rest of the day. This means that this is a one-time slowdown (that should be
  # incurred primarily in the nightly cron runs). PRs should still be super speedy.
  build-kernel:
    runs-on:
    - ubuntu-22.04
    # 30 minutes seems reasonable to build a kernel image in my experiments. If this
    # becomes a problem, we can always bump this in the future.
    timeout-minutes: 30
    steps:
      # Name the kernel image artifact after the current date. This lets us cache images
      # once per day.
      - name: Set Job Variables
        run: |
          echo kernel-build-name="kernel-build-$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Note that we are purposely not using the official download-artifact action here.
      # This custom action does the same thing but supports downloading the artifacts
      # _across_ different workflow runs. This is what enables us to cache the kernel
      # image so we can get speedy runs.
      #
      # This step simply checks for this existence of this artifact so that we can avoid
      # building it twice.
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: '${{ env.kernel-build-name }}'
          if_no_artifact_found: 'ignore'
          check_artifacts: true
          search_artifacts: true
          workflow_conclusion: ''
      - id: check-build-exists
        run: |
          if [ -f "vmlinuz-bpf" ]; then
            echo 'exists=true' >> $GITHUB_OUTPUT
          fi

      - name: Checkout Git Repo
        if: ${{ steps.check-build-exists.outputs.exists != 'true' }}
        uses: actions/checkout@v3

      # Install the little vm helper CLI so we can use it to build the kernel image.
      - name: Install LVH CLI
        if: ${{ steps.check-build-exists.outputs.exists != 'true' }}
        run: |
          cid=$(docker create quay.io/lvh-images/lvh:${{ env.lvh-version }})
          docker cp $cid:/usr/bin/lvh /tmp/lvh
          docker rm $cid
          chmod +x /tmp/lvh
          sudo mv /tmp/lvh /bin/lvh

      # Dependencies needed to build the kernel and include BTF definitions.
      - name: Install Kernel Build Dependencies
        if: ${{ steps.check-build-exists.outputs.exists != 'true' }}
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libelf-dev cmake libdw-dev pahole

      # Use LVH to build the kernel.
      - name: Build Kernel
        if: ${{ steps.check-build-exists.outputs.exists != 'true' }}
        run: |
          cd contrib/kvm
          make fetch-kernel KERNEL=bpf
          make build-kernel KERNEL=bpf
          cp _data/kernels/bpf/tar-install/boot/vmlinuz* /tmp/vmlinuz-bpf

      - name: Upload Build
        if: ${{ steps.check-build-exists.outputs.exists != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: '${{ env.kernel-build-name }}'
          path: /tmp/vmlinuz-bpf
          retention-days: 5

  run-tests:
    runs-on:
    - majestic-ketchup-light
    timeout-minutes: 20
    needs: build-kernel
    steps:
      - name: Set Job Variables
        run: |
          echo kernel-build-name="kernel-build-$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Checkout Git Repo
        uses: actions/checkout@v3
        with:
          path: hubble-fgs
          submodules: true

      # Note that we are purposely not using the official download-artifact action here.
      # This custom action does the same thing but supports downloading the artifacts
      # _across_ different workflow runs. This is what enables us to cache the kernel
      # image so we can get speedy runs.
      - name: download build data
        uses: dawidd6/action-download-artifact@v2
        with:
          name: '${{ env.kernel-build-name }}'
          check_artifacts: true
          search_artifacts: true
          workflow_conclusion: ''

      # Provision the VM using the kernel image we downloaded from the previous step.
      - name: Provision LVH VM
        uses: cilium/little-vm-helper@d14bb6ba7bb7718afdecd6f674425f2380d1350f
        with:
          install-dependencies: true
          test-name: tetragon-unit-tests
          image: kind
          image-version: '${{ env.root-image-version }}'
          lvh-version: '${{ env.lvh-version }}'
          host-mount: ./
          ssh-port: 2222
          mem: 4G
          cpu: 2
          cpu-kind: host
          kernel: 'vmlinuz-bpf'
          cmd: |
            set -eux
            cd /host/hubble-fgs

            systemd-detect-virt
            (systemd-detect-virt | grep -q -i kvm) || { echo 'No KVM support detected! Bailing out...'; exit 1; }

            uname -r

            # install test deps
            apt update -y
            DEBIAN_FRONTEND=noninteractive apt install -y libcap-dev libaio-dev liburing-dev libelf-dev iptables software-properties-common netcat-openbsd

      # Run the tests.
      - name: Run Tests
        uses: cilium/little-vm-helper@d14bb6ba7bb7718afdecd6f674425f2380d1350f
        with:
          provision: 'false'
          cmd: |
            set -eux
            cd /host/hubble-fgs

            export KVM_CI=true
            export SUDO=
            make hubble-bpf hubble-fgs-fs-scanner tester-progs test

      - name: Copy out FGS logs
        if: ${{ failure() || cancelled() }}
        timeout-minutes: 15
        run: |
          # Make output dirs for logs
          mkdir -p logs/unit-tests

          # Copy logs over
          scp -P 2222 'root@localhost:/tmp/*.yaml' logs/unit-tests || true
          scp -P 2222 'root@localhost:/tmp/*.json' logs/unit-tests || true
          scp -P 2222 'root@localhost:/tmp/*bugtool*' logs/unit-tests || true

      - name: Upload unit test logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: tetragon-nightly-bpf-tests
          path: logs/unit-tests
          retention-days: 5
