name: KVMEndToEnd

on:
  pull_request:
  push:
    branches:
      - master

env:
  clusterName: fgs-cli-ci
  zone: us-west2-a
  vmName: fgs-ci-${{ github.run_id }}
  vmHost: fgs@fgs-ci-${{ github.run_id }}.us-west2-a.${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}
  machineImage: projects/${{ secrets.CILIUM_DEV_GCP_PROJECT_ID }}/global/machineImages/fgs-kvm-ci

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      matrix:
        kernel:
          - '5.10-lts'
    steps:
      - uses: actions/checkout@master
        with:
          path: hubble-fgs

      - name: Set up job variables
        id: vars
        run: |
          if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
            PR_API_JSON=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.issue.pull_request.url || github.event.pull_request.url }})
            SHA=$(echo "$PR_API_JSON" | jq -r ".head.sha")
          else
            SHA=${{ github.sha }}
          fi
          echo ::set-output name=sha::${SHA}
          echo ::set-output name=fgsImage::quay.io/isovalent/hubble-enterprise-ci:${SHA}

      - name: Authenticate with gcloud
        uses: 'google-github-actions/auth@v0'
        with:
          project_id: ${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}
          credentials_json: '${{ secrets.CILIUM_PR_GCP_SA_KEY }}'
          create_credentials_file: true

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}

      - name: Install beta component
        run: gcloud components install beta && gcloud info

      - name: Create VM
        run: |
          gcloud beta compute instances create ${{ env.vmName }} --quiet --zone ${{ env.zone }} \
            --machine-type n1-standard-4 --min-cpu-platform "Intel Haswell" \
            --enable-nested-virtualization \
            --source-machine-image ${{ env.machineImage }} \
            --preemptible --no-restart-on-failure --maintenance-policy=terminate \
            --service-account isovalent-hubble-fgs-sa@cilium-pr.iam.gserviceaccount.com

      - name: Set up ssh into VM
        run: |
          sudo apt-get -y install openssh-client
          gcloud compute ssh fgs@${{ env.vmName }} --zone ${{ env.zone }} --command="uname -a"
          gcloud compute config-ssh
          ssh ${{ env.vmHost }} 'whoami && uname -a'

      - name: Copy over FGS
        run: |
          tar cz hubble-fgs | ssh ${{ env.vmHost }} 'tar xz'

      - name: Spin up KVM
        run: |
          cat <<-EOF | ssh ${{ env.vmHost }} 'cat > hubble-fgs/contrib/kvm/conf'
            # Public key for ssh
            PUBKEY="\\$HOME/.ssh/id_rsa.pub"
            # Path to store the created vm image
            ROOTIMG="/home/fgs/img/kvm.img"
            # Path to mount the created image for chroot + debootstrap
            MNTDIR=mnt
            # Packages to install with debootstrap
            PACKAGES=("less" "vim" "sudo" "openssh-server" "python3" "curl" "iptables" "build-essential" "libelf-dev")

            # Disk size for the VM
            # This currently is recommended to be about 20GiB to support running in KinD
            # and at least 4GiB to run FGS locally.
            VMDISK=20G
            # RAM for the VM
            VMRAM=8G
            # Number of CPUs to the use for the VM
            VMCPUS=4
            # MAC address for VM's NIC
            MACADDR="52:54:00:12:34:56"
            # Port to use for SSH on the host
            SSHPORT=3000

            # Name of kernel config to use
            KCONFIG=kernel.config
            # Path to download kernel sources
            KSRCDIR=.ksrc
            # Path to place compiled kernel bzImage and bpftool
            KOUT=kout
            # Full path for kernel bzImage, can be overridden to manually point to other kernel images
            BZIMAGE="/home/fgs/kernels/${{ matrix.kernel }}"
            # Path where FGS directory is located, used to mount FGS as a network share
            FGSDIR="/home/fgs/hubble-fgs"
            # Path to install kernel modules
            MODULESDIR=modules
          EOF
          cat <<-EOF | ssh ${{ env.vmHost }}
            set -xeu
            hubble-fgs/contrib/kvm/run.sh
            ssh -p 3000 root@localhost 'uname -r'
          EOF

      - name: Bootstrap k8s cluster
        run: |
          ssh ${{ env.vmHost }} 'ssh -p 3000 root@localhost "/fgs/contrib/end-to-end/bootstrap-cluster.sh"'

      - name: Wait for image to be available
        timeout-minutes: 10
        shell: bash
        run: |
          until curl --silent -f -lSL "https://quay.io/api/v1/repository/${{ github.repository_owner }}/hubble-enterprise-ci/tag/${{ steps.vars.outputs.sha }}/images" &> /dev/null; do sleep 45s; done

      - name: Install FGS
        run: |
          docker pull ${{ steps.vars.outputs.fgsImage }}
          docker save ${{ steps.vars.outputs.fgsImage }} | bzip2 | ssh ${{ env.vmHost }} 'ssh -p 3000 root@localhost "docker load"'
          cat <<-EOF | ssh ${{ env.vmHost }} 'ssh -p 3000 root@localhost'
            set -xeu
            kind load docker-image ${{ steps.vars.outputs.fgsImage }} --name ${{ env.clusterName }}
            helm repo add isovalent https://helm.isovalent.com
            helm repo update
            helm install hubble-enterprise isovalent/hubble-enterprise \
                   --version 9999.9999.9999-dev \
                   --set enterprise.image.repository=quay.io/isovalent/hubble-enterprise-ci \
                   --set enterprise.image.tag=${{ steps.vars.outputs.sha }} \
                   --set enterprise.exportAllowList="" \
                   --namespace kube-system
          EOF

      - name: Wait for FGS pods to become ready
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          command: |
            ssh ${{ env.vmHost }} 'ssh -p 3000 root@localhost "kubectl wait -n kube-system --for=condition=Ready --all pod -l app.kubernetes.io/name=hubble-enterprise --timeout=45s"'

      - name: Run HTTP and TLS tests
        run: |
          ssh ${{ env.vmHost }} 'ssh -p 3000 root@localhost "/fgs/contrib/end-to-end/tests/http-tls.sh"'

      - name: Run demo app tests
        run: |
          ssh ${{ env.vmHost }} 'ssh -p 3000 root@localhost "/fgs/contrib/end-to-end/tests/demo-app.sh"'

      - name: Copy out FGS logs
        if: ${{ failure() }}
        run: |
          cat <<-EOF | ssh ${{ env.vmHost }}
            mkdir -p ~/logs
            scp -P 3000 'root@localhost:/fgs/contrib/end-to-end/logs/*' ~/logs
          EOF
          scp -r ${{ env.vmHost }}:~/logs logs

      - name: Upload FGS pod logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: hubble-enterprise-logs
          path: logs/hubble-enterprise-pod*.log
          retention-days: 5

      - name: Upload bugtool dumps
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: bugtool-dumps
          path: logs/bugtool*.tar.gz
          retention-days: 5

      - name: Upload FGS artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: fgs.json
          path: logs/fgs.json
          retention-days: 5

      - name: Destroy VM
        if: ${{ always() }}
        run: |
          gcloud beta compute instances delete ${{ env.vmName }} --quiet --zone ${{ env.zone }}
