name: KVM Compliance Tests (HTTP)

on:
  schedule:
    # Run at 4PM UTC every day
    - cron: "0 16 * * *"
  pull_request:
    paths:
    - ".github/workflows/kvm-compliance-tests.yaml"
    - "tests/compliance/**"
    - "pkg/sensors/http/**"
    - "bpf/lib/tlsmsg.h"
    - "bpf/parsers/parser.h"
    - "bpf/parsers/http/**"
  push:
    branches:
    - master
    paths:
    - ".github/workflows/kvm-compliance-tests.yaml"
    - "tests/compliance/**"
    - "pkg/sensors/http/**"
    - "bpf/lib/tlsmsg.h"
    - "bpf/parsers/parser.h"
    - "bpf/parsers/http/**"

env:
  ISSUE_LABELS: bug,area/http,kind/kernel,release-blocker,compliance-test

concurrency:
  group: ${{ github.ref }}-kvm-compliance-tests
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on:
    - majestic-ketchup-light
    permissions:
      contents: read
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        kernel:
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - 'bpf-next-20260928.013030'
          # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
          - '6.18-20260928.013030'
          # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
          - '6.12-20260928.013030'
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - '6.6-20260928.013030'
          # FIXME: following kernels temporarily disabled pending bugfixes
          # # renovate: datasource=docker depName=quay.io/lvh-images/kind
          # - '6.1-20260928.013030'
          # # renovate: datasource=docker depName=quay.io/lvh-images/kind
          # - '5.15-20260928.013030'
          # # renovate: datasource=docker depName=quay.io/lvh-images/kind
          # - '5.10-20260928.013030'
          # NB: it doesn't make sense to test the http parser on kernels <5.10
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: hubble-fgs
          submodules: true

      - name: Provision LVH VM
        uses: cilium/little-vm-helper@5ae749011735fd77f30f38add52f1a53a5568671 # v0.0.30
        with:
          test-name: tetragon-compliance-tests
          host-mount: ./
          install-dependencies: true
          image: kind
          image-version: '${{ matrix.kernel }}'
          ssh-port: 2222
          mem: 4G
          cpu: 2
          cpu-kind: host
          cmd: |
            set -eux
            cd /host/hubble-fgs

            # wait for network to be available
            while true;
            do
              wget --spider -q -T 10  http://google.com && break
              sleep 10
            done

            systemd-detect-virt
            (systemd-detect-virt | grep -q -i kvm) || { echo 'No KVM support detected! Bailing out...'; exit 1; }

            # copy btf file
            mkdir -p bpf/objs
            ln -vsnf /boot/btf-\$(uname -r) bpf/objs/btf

      - name: Run Tests
        uses: cilium/little-vm-helper@5ae749011735fd77f30f38add52f1a53a5568671 # v0.0.30
        id: runTests
        with:
          test-name: tetragon-compliance-tests
          host-mount: ./
          provision: 'false'
          cmd: |
            set -eux
            cd /host/hubble-fgs
            
            mkdir /build
            export GOTMPDIR=/build
            export DOCKER_API_VERSION=1.47

            export KVM_CI=true
            export SUDO=
            make tetragon-bpf
            go test ./tests/compliance -print-stdout

      - name: Create an issue
        if: ${{ failure() && steps.runTests.outcome == 'failure' && github.event_name == 'schedule' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: "http: compliance test failure on ${{ matrix.kernel }}"
          ASSIGNESS: willfindlay,jrfastab
          LABELS: ${{ env.ISSUE_LABELS }}
          BODY: |
            A compliance test run failed for kernel ${{ matrix.kernel }} (Tetragon ref: ${{ github.ref }}).

            See job output for more information: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          cd hubble-fgs
          previous_issue_number=$(gh issue list \
            --label "$LABELS" \
            -s closed \
            -S "${{ matrix.kernel }}" \
            --json number \
            --jq '.[0].number')
          if [[ -n $previous_issue_number ]]; then
            gh issue reopen "$previous_issue_number"
            gh issue edit \
              --title "$TITLE" \
              --body "$BODY" \
              "$previous_issue_number"
          else 
            gh issue create \
              --title "$TITLE" \
              --assignee "$ASSIGNEES" \
              --label "$LABELS" \
              --body "$BODY"
          fi

      - name: Close existing issue
        if: ${{ steps.runTests.outcome == 'success' && github.event_name == 'schedule' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: ${{ env.ISSUE_LABELS }}
        run: |
          cd hubble-fgs
          previous_issue_number=$(gh issue list \
            --label "$LABELS" \
            -S "${{ matrix.kernel }}" \
            --json number \
            --jq '.[0].number')
          if [[ -n $previous_issue_number ]]; then
            gh issue close "$previous_issue_number"
          fi
