name: Nightly BPF regression test
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

env:
  agentImage: quay.io/${{ github.repository_owner }}/hubble-enterprise:latest
  operatorImage: quay.io/${{ github.repository_owner }}/hubble-enterprise-operator:latest
  clusterName: tetragon-ci
  zone: us-west2-a
  vmName: fgs-ci-nightly-${{ github.run_id }}
  vmHost: fgs@fgs-ci-nightly-${{ github.run_id }}.us-west2-a.${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}
  machineImage: projects/${{ secrets.CILIUM_DEV_GCP_PROJECT_ID }}/global/machineImages/fgs-kvm-ci-v5

jobs:
  nightly-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    steps:
      - uses: actions/checkout@v3
        with:
          path: hubble-fgs
          submodules: true

      - name: Authenticate with gcloud
        uses: 'google-github-actions/auth@v0'
        with:
          project_id: ${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}
          credentials_json: '${{ secrets.CILIUM_PR_GCP_SA_KEY }}'
          create_credentials_file: true

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}

      - name: Install beta component
        run: gcloud components install beta && gcloud info

      - name: Build kernel
        run: |
          # Install build dependencies
          sudo apt-get -y update
          sudo apt-get -y install libelf-dev cmake libdw-dev llvm
          hubble-fgs/contrib/install-pahole.sh

          git clone --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf.git /home/runner/bpf
          rm -rf /home/runner/bpf/.git

          # Setup custom config file for contrib/kvm so that it points to the right disk
          # image and kernel
          cat <<-EOF >> hubble-fgs/contrib/kvm/conf
            KSRCDIR=/home/runner/bpf
            ROOTIMG=/home/fgs/img/kvm.img
            FGSDIR="/home/fgs/hubble-fgs"
          EOF

          # Build the kernel
          hubble-fgs/contrib/kvm/build-kernel.sh

      - name: Create VM
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          command: |
            gcloud beta compute instances create ${{ env.vmName }} --quiet --zone ${{ env.zone }} \
              --machine-type n1-standard-4 --min-cpu-platform "Intel Haswell" \
              --enable-nested-virtualization \
              --source-machine-image ${{ env.machineImage }} \
              --preemptible --no-restart-on-failure --maintenance-policy=terminate \
              --service-account isovalent-hubble-fgs-sa@cilium-pr.iam.gserviceaccount.com

      - name: Set up ssh client
        run: |
            sudo apt-get -y install openssh-client
            mkdir -p ~/.ssh && chmod 700 ~/.ssh
            echo "${{ secrets.KVM_SSH_FINGERPRINT }}" >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts

      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up ssh into VM
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          command: |
            gcloud compute ssh --quiet fgs@${{ env.vmName }} --zone ${{ env.zone }} --command="uname -a"
            gcloud compute config-ssh --quiet
            ssh ${{ env.vmHost }} 'whoami && uname -a'

      - name: Copy over FGS
        run: |
          tar cz hubble-fgs | ssh ${{ env.vmHost }} 'tar xz'

      - name: Spin up KVM
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          command: |
            # Spin up KVM
            cat <<-EOF | ssh ${{ env.vmHost }}
              hubble-fgs/contrib/kvm/run.sh
            EOF

            # Ensure VM is running. If not, back off for 10 seconds and exit with a bad
            # status code so we can try again.
            if ! ssh ${{ env.vmHost }} 'ps ax | grep "qemu-system"'; then
              sleep 10
              exit 1
            fi

            # Set up an ssh tunnel into the VM
            ssh ${{ env.vmHost }} -NL 3000:localhost:3000 & sleep 10

            # Verify we can login via the tunnel
            ssh -p 3000 root@localhost "uname -a"

      - name: Install liburing and libaio
        run: |
          cat <<-EOF | ssh -p 3000 root@localhost
            set -e

            apt install libaio-dev -y

            rm -rf liburing
            git clone https://github.com/axboe/liburing.git
            cd liburing
            ./configure
            make
            sudo make install
          EOF

      - name: Run unit tests
        timeout-minutes: 30
        run: |
          cat <<-EOF | ssh -p 3000 root@localhost
            set -e

            cd /fgs
            export PATH="\\$PATH:/usr/local/go/bin"

            make  hubble-bpf tester-progs test
          EOF

      - name: Copy out FGS logs
        if: ${{ failure() }}
        timeout-minutes: 15
        run: |
          # Make output dirs for logs
          mkdir -p logs/unit-tests

          # Copy logs over
          scp -P 3000 'root@localhost:/tmp/*.yaml' logs/unit-tests || true
          scp -P 3000 'root@localhost:/tmp/*.json' logs/unit-tests || true
          scp -P 3000 'root@localhost:/tmp/*bugtool*' logs/unit-tests || true

      - name: Attempt to pull the FGS image
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 30
          retry_wait_seconds: 30
          command: |
            set -e
            docker pull ${{ env.agentImage }}
            docker pull ${{ env.operatorImage }}

      - name: Set up kind cluster
        run: |
          # Check if the image is already loaded and, if so, break out early
          if [[ "$(ssh -p 3000 root@localhost 'docker images -q ${{ env.agentImage }}')" != "" ]]; then
            exit 0
          fi

          docker save ${{ env.agentImage }} | bzip2 | ssh -p 3000 root@localhost "docker load"
          docker save ${{ env.operatorImage }} | bzip2 | ssh -p 3000 root@localhost "docker load"

          # Create kind cluster
          cat <<-EOF | ssh -p 3000 root@localhost
            kind create cluster --name ${{ env.clusterName }}
            kind --name ${{ env.clusterName }} load docker-image ${{ env.agentImage }}
            kind --name ${{ env.clusterName }} load docker-image ${{ env.operatorImage }}
            cilium install
          EOF

      - name: Run e2e tests
        run: |
          cat <<-EOF | ssh -p 3000 root@localhost
            export PATH="$PATH:/usr/local/go/bin"
            cd /fgs
            go test -p 1 -parallel 1 -timeout 20m -failfast ./tests/e2e/tests/... \
              -tetragon.helm.set enterprise.image.override=${{ env.agentImage }} \
              -tetragon.helm.set hubbleEnterpriseOperator.image.override=${{ env.operatorImage }} \
              -tetragon.helm.set enterprise.btf="/sys/kernel/btf/vmlinux" \
              -cluster-name ${{ env.clusterName }} \
              -kubeconfig ~/.kube/config
          EOF

      - name: Copy out e2e test logs
        if: ${{ failure() }}
        run: |
          rm -rf logs/e2e
          mkdir -p logs/e2e
          scp -r -P 3000 'root@localhost:/tmp/tetragon.e2e.*' logs/e2e/

      - name: Shut off KVM
        timeout-minutes: 5
        run: |
          ssh ${{ env.vmHost }} "hubble-fgs/contrib/kvm/stop.sh"
          sleep 10

      - name: Upload unit test artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: unit-test-artifacts
          path: logs/unit-tests
          retention-days: 5

      - name: Upload e2e artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: e2e-artifacts
          path: logs/e2e
          retention-days: 5

      - name: Destroy VM
        if: ${{ always() }}
        run: |
          gcloud beta compute instances delete ${{ env.vmName }} --quiet --zone ${{ env.zone }}
