name: KVM Go Tests

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "contrib/grafana/**"
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}-${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner_labels: ${{ vars.KVM_GH_RUNNER_AMD64 }}
          - arch: arm64
            runner_labels: ${{ vars.KVM_GH_RUNNER_ARM64 }}
        kernel:
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "rhel8.9-20251031.120020"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "bpf-next-20251110.091626"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "6.6-20251110.091626"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "6.1-20251110.091626"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "5.15-20251110.091626"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "5.10-20251110.091626"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "5.4-20251110.091626"
          # renovate: datasource=docker depName=quay.io/lvh-images/kind
          - "4.19-20251110.091626"
        # TODO: temporarily disable testing for 4.19 and 5.4 kernels
        # The excluded kernels require more test failure investigation
        exclude:
          - arch: arm64
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: "rhel8.9-20251031.120020" # currently not supported on ARM64
    runs-on: ${{ matrix.runner_labels }}
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: hubble-fgs
          submodules: true

      - name: Get CPU and Memory
        id: get-cpu-mem
        run: |
          echo "cpu=$(( $(nproc) / 2 ))" >> $GITHUB_OUTPUT
          echo "mem=$(cat /proc/meminfo | awk '/^MemTotal:/{print int($2/1024/1024/2)}')G" >> $GITHUB_OUTPUT

      - name: Provision LVH VM
        id: provision-lvh-vm
        uses: cilium/little-vm-helper@01debd6cb7e5514cfdb4a33e776bdc647bc5306e # v0.0.27
        with:
          install-dependencies: true
          test-name: tetragon-unit-tests
          image: kind
          image-version: '${{ matrix.kernel }}'
          images-folder-parent:  ${{ github.workspace }}/.github/lvh-action-cache
          kernel-version: ${{ matrix.arch == 'arm64' && matrix.kernel || '' }}
          host-mount: ./
          mem: ${{ steps.get-cpu-mem.outputs.mem }}
          cpu: ${{ steps.get-cpu-mem.outputs.cpu }}
          cpu-kind: host
          arch: ${{ matrix.arch }}
          cmd: |
            set -eux
            cd /host/hubble-fgs
            git config --global --add safe.directory /host/hubble-fgs

            systemd-detect-virt
            systemd-detect-virt | grep -Eiq 'kvm|qemu' || { echo 'No KVM or QEMU support detected! Bailing out...'; exit 1; }

            # copy btf file
            mkdir -p bpf/objs
            ln -vsnf /boot/btf-\$(uname -r) bpf/objs/btf

            # wait for network to be available
            while true;
            do
              wget --spider -q -T 10 http://google.com && break
              sleep 10
            done

            # install test deps
            apt-get update -y
            # TODO remove bind9-dnsutils package once image version is >= 20250214.144547
            DEBIAN_FRONTEND=noninteractive apt install -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" -y libcap-dev libaio-dev liburing-dev libelf-dev iptables software-properties-common netcat-openbsd socat iproute2 net-tools bind9-dnsutils pahole llvm

            if [[ "${{ matrix.arch }}" == "amd64" ]]
            then
              DEBIAN_FRONTEND=noninteractive apt install -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" -y libc6-dev-i386 gcc-multilib
            else
              DEBIAN_FRONTEND=noninteractive apt install -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" -y gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf build-essential
            fi

            # restart ssh server
            service ssh restart

      - name: Run Tests
        uses: cilium/little-vm-helper@01debd6cb7e5514cfdb4a33e776bdc647bc5306e # v0.0.27
        with:
          test-name: tetragon-unit-tests
          host-mount: ./
          provision: 'false'
          arch: ${{ matrix.arch }}
          kernel-version: ${{ matrix.arch == 'arm64' && matrix.kernel || '' }}
          cmd: |
            set -eux
            cd /host/hubble-fgs

            mkdir /build
            export GOTMPDIR=/build

            export KVM_CI=true
            export SUDO=
            # FIXME: TestCGTLS13 test fails bpf-next kernels
            if [[ "${{ matrix.kernel }}" == bpf-next-* ]]; then
              export FLAKY_HTTP=1
            fi
            # FIXME: TestTLS13 test fails 6.6 kernels
            if [[ "${{ matrix.kernel }}" == 6.6-* ]]; then
              export FLAKY_HTTP=1
            fi
            # FIXME: TestTLS13 test fails 6.1 kernels
            if [[ "${{ matrix.kernel }}" == 6.1-* ]]; then
              export FLAKY_HTTP=1
            fi
            # FIXME: TestTLS13 test fails 5.15 kernels
            if [[ "${{ matrix.kernel }}" == 5.15-* ]]; then
              export FLAKY_HTTP=1
            fi
            # FIXME: TestTLS13 test fails 5.10 kernels
            if [[ "${{ matrix.kernel }}" == 5.10-* ]]; then
              export FLAKY_HTTP=1
            fi
            make tetragon-fs-scanner test

      - name: Copy out FGS logs
        if: ${{ failure() || cancelled() }}
        timeout-minutes: 15
        run: |
          # Make output dirs for logs
          mkdir -p logs/unit-tests
          mkdir -p logs/model-test-dumps

          # Copy logs over
          scp -P 2222 'root@localhost:/tmp/*.yaml' logs/unit-tests || true
          scp -P 2222 'root@localhost:/tmp/*.json' logs/unit-tests || true
          scp -P 2222 'root@localhost:/tmp/*bugtool*' logs/unit-tests || true
          scp -P 2222 'root@localhost:/tmp/TestModel*' logs/model-test-dumps || true

      # AWS Baremetal Instances do not honor shutdown signals when QEMU VMs are running
      # Cleanup by force killing QEMU processes
      - name: Delete LVH VM
        if: ${{ always() && steps.provision-lvh-vm.outcome == 'success' }}
        run: sudo pkill -9 qemu-system

      - name: Upload unit test logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: tetragon-unit-tests-${{ matrix.kernel }}-${{ matrix.arch }}
          path: logs/unit-tests
          retention-days: 5

      - name: Upload modeltest dumps
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: modeltest-json-${{ matrix.kernel }}-${{ matrix.arch }}
          path: logs/model-test-dumps
          retention-days: 5
