name: KVM e2e Tests

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}-kvm-e2e
  cancel-in-progress: true

env:
  ciliumCliVersion: v0.12.11
  ciliumVersion: v1.12.6

jobs:
  ensure-image-available:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          path: hubble-fgs
          submodules: true

      - name: Set up job variables
        id: vars
        run: |
          if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
            PR_API_JSON=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.issue.pull_request.url || github.event.pull_request.url }})
            SHA=$(echo "$PR_API_JSON" | jq -r ".head.sha")
          else
            SHA=${{ github.sha }}
          fi
          echo "sha=${SHA}" >> $GITHUB_OUTPUT
          echo "agentImage=quay.io/isovalent-dev/tetragon-ci:${SHA}" >> $GITHUB_OUTPUT
          echo "operatorImage=quay.io/isovalent-dev/tetragon-operator-ci:${SHA}" >> $GITHUB_OUTPUT

      - name: Attempt To Pull Docker Images
        uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd # v2.8.3
        with:
          timeout_minutes: 2
          max_attempts: 30
          retry_wait_seconds: 30
          command: |
            set -e
            docker pull ${{ steps.vars.outputs.agentImage }}
            docker pull ${{ steps.vars.outputs.operatorImage }}

  run-tests:
    needs: ensure-image-available
    runs-on:
      - majestic-ketchup-light
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        kernel:
          - "5.15-20230420.212204"
          - "5.10-20230420.212204"
          - "5.4-20230420.212204"
          - "4.19-20230420.212204"
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          path: hubble-fgs
          submodules: true

      - name: Set up job variables
        id: vars
        run: |
          if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
            PR_API_JSON=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.issue.pull_request.url || github.event.pull_request.url }})
            SHA=$(echo "$PR_API_JSON" | jq -r ".head.sha")
          else
            SHA=${{ github.sha }}
          fi
          echo "sha=${SHA}" >> $GITHUB_OUTPUT
          echo "agentImage=quay.io/isovalent-dev/tetragon-ci:${SHA}" >> $GITHUB_OUTPUT
          echo "operatorImage=quay.io/isovalent-dev/tetragon-operator-ci:${SHA}" >> $GITHUB_OUTPUT

      - name: Install Cilium CLI
        run: |
          GOOS=$(go env GOOS)
          GOARCH=$(go env GOARCH)
          curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${{ env.ciliumCliVersion }}/cilium-${GOOS}-${GOARCH}.tar.gz{,.sha256sum}
          sha256sum --check cilium-${GOOS}-${GOARCH}.tar.gz.sha256sum
          sudo tar -xzvf cilium-${GOOS}-${GOARCH}.tar.gz
          rm cilium-${GOOS}-${GOARCH}.tar.gz{,.sha256sum}

      - name: Provision LVH VM
        uses: cilium/little-vm-helper@908ab1ff8a596a03cd5221a1f8602dc44c3f906d # v0.0.12
        with:
          install-dependencies: true
          test-name: tetragon-e2e
          image: kind
          image-version: "${{ matrix.kernel }}"
          host-mount: ./
          ssh-port: 2222
          mem: 8G
          cpu: 2
          cpu-kind: host
          cmd: |
            set -eux

            systemd-detect-virt
            (systemd-detect-virt | grep -q -i kvm) || { echo 'No KVM support detected! Bailing out...'; exit 1; }

            cd /host/hubble-fgs

            mv /host/cilium /bin/cilium
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Pull Docker Images
        run: |
          set -e
          docker pull ${{ steps.vars.outputs.agentImage }}
          docker pull ${{ steps.vars.outputs.operatorImage }}

      - name: Load Docker Images Into LVH
        run: |
          docker save ${{ steps.vars.outputs.agentImage }} ${{ steps.vars.outputs.operatorImage }} | ssh -p 2222 root@localhost -o "StrictHostKeyChecking=no" "docker load"

      - name: Run Tests
        uses: cilium/little-vm-helper@908ab1ff8a596a03cd5221a1f8602dc44c3f906d # v0.0.12
        with:
          provision: "false"
          cmd: |
            set -eux
            cd /host/hubble-fgs
            export HOST_PROC=/procRoot
            make e2e-test                                          \
              E2E_BUILD_IMAGES=0                                   \
              E2E_EXTRA_GOTEST_FLAGS="-failfast"                   \
              E2E_BTF=/boot/btf-\$(uname -r)                       \
              E2E_AGENT=${{ steps.vars.outputs.agentImage }}       \
              E2E_OPERATOR=${{ steps.vars.outputs.operatorImage }} \
              E2E_EXTRA_TEST_FLAGS="-tetragon.cilium-version=${{ env.ciliumVersion }} -tetragon.helm.set tetragon.extraArgs.fim-fifo-path=/tetragonExport -v"

      - name: Copy out e2e test logs
        if: ${{ failure() || cancelled() }}
        run: |
          rm -rf logs/e2e
          mkdir -p logs/e2e
          scp -r -P 2222 'root@localhost:/tmp/tetragon.e2e.*' logs/e2e/

      - name: Upload end-to-end test logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: tetragon-e2e-${{ matrix.kernel }}
          path: logs/e2e
          retention-days: 5
