name: KVM Go Tests

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "contrib/grafana/**"
  push:
    branches:
      - master

jobs:
  amd64:
    uses: ./.github/workflows/kvm-gotests-arch.yaml
    permissions:
      contents: read
      actions: read
    with:
      arch: amd64
      runner_label: ${{ vars.KVM_GH_RUNNER_AMD64 }}
      apt_packages: >-
        bind9-dnsutils libcap-dev libaio-dev liburing-dev libelf-dev
        iptables software-properties-common netcat-openbsd socat
        iproute2 net-tools pahole clang lld llvm libc6-dev-i386
        gcc-multilib libnet1 libnet1-dev

  arm64:
    uses: ./.github/workflows/kvm-gotests-arch.yaml
    permissions:
      contents: read
      actions: read
    with:
      arch: arm64
      runner_label: ${{ vars.KVM_GH_RUNNER_ARM64 }}
      apt_packages: >-
        bind9-dnsutils libcap-dev libaio-dev liburing-dev libelf-dev
        iptables software-properties-common netcat-openbsd socat
        iproute2 net-tools pahole clang lld llvm
        gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf
        libc6-dev-armhf-cross build-essential libnet1 libnet1-dev
