name: KVM Tests

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  clusterName: fgs-cli-ci
  zone: us-west2-a
  vmName: fgs-ci-${{ github.run_id }}
  vmHost: fgs@fgs-ci-${{ github.run_id }}.us-west2-a.${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}
  machineImage: projects/${{ secrets.CILIUM_DEV_GCP_PROJECT_ID }}/global/machineImages/fgs-kvm-ci

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      max-parallel: 1
      matrix:
        kernel:
          - '5.15-lts'
          - '5.10-lts'
          - '5.4-lts'
          - '4.19-lts'
    outputs:
      job_status: ${{ job.status }}
    steps:
      - uses: actions/checkout@master
        with:
          path: hubble-fgs
          submodules: true

      - name: Set up ssh client
        run: |
            sudo apt-get -y install openssh-client
            mkdir -p ~/.ssh && chmod 700 ~/.ssh
            echo "${{ secrets.KVM_SSH_FINGERPRINT }}" >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts

      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up job variables
        id: vars
        run: |
          if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
            PR_API_JSON=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.issue.pull_request.url || github.event.pull_request.url }})
            SHA=$(echo "$PR_API_JSON" | jq -r ".head.sha")
          else
            SHA=${{ github.sha }}
          fi
          echo ::set-output name=sha::${SHA}
          echo ::set-output name=fgsImage::quay.io/isovalent/hubble-enterprise-ci:${SHA}

      - name: Authenticate with gcloud
        uses: 'google-github-actions/auth@v0'
        with:
          project_id: ${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}
          credentials_json: '${{ secrets.CILIUM_PR_GCP_SA_KEY }}'
          create_credentials_file: true

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}

      - name: Install beta component
        run: gcloud components install beta && gcloud info

      - name: Create VM if needed
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          command: |
            # Probe to see if VM already exists and, if so, exit early
            # Otherwise let's keep going
            gcloud compute ssh --quiet fgs@${{ env.vmName }} --zone ${{ env.zone }} --command="uname -a" && exit 0 || true

            # Create the vm
            gcloud beta compute instances create ${{ env.vmName }} --quiet --zone ${{ env.zone }} \
              --machine-type n1-standard-4 --min-cpu-platform "Intel Haswell" \
              --enable-nested-virtualization \
              --source-machine-image ${{ env.machineImage }} \
              --preemptible --no-restart-on-failure --maintenance-policy=terminate \
              --service-account isovalent-hubble-fgs-sa@cilium-pr.iam.gserviceaccount.com

      - name: Set up ssh into VM
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          command: |
            gcloud compute ssh --quiet fgs@${{ env.vmName }} --zone ${{ env.zone }} --command="uname -a"
            gcloud compute config-ssh --quiet
            ssh ${{ env.vmHost }} 'whoami && uname -a'

      - name: Copy over FGS
        run: |
          # Break out early if hubble-fgs directory already exists
          ssh ${{ env.vmHost }} "ls hubble-fgs" && exit 0 || true

          # Copy over FGS
          tar cz hubble-fgs | ssh ${{ env.vmHost }} 'tar xz'

      - name: Spin up KVM
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          command: |
            # Setup custom config file for contrib/kvm so that it points to the right disk
            # image and kernel
            cat <<-EOF | ssh ${{ env.vmHost }} 'cat >> hubble-fgs/contrib/kvm/conf'
              ROOTIMG="/home/fgs/img/kvm.img"
              BZIMAGE="/home/fgs/kernels/${{ matrix.kernel }}"
              FGSDIR="/home/fgs/hubble-fgs"
            EOF

            # Spin up KVM
            cat <<-EOF | ssh ${{ env.vmHost }}
              hubble-fgs/contrib/kvm/run.sh
            EOF

            # Ensure VM is running. If not, back off for 10 seconds and exit with a bad
            # status code so we can try again.
            if ! ssh ${{ env.vmHost }} 'ps ax | grep "qemu-system"'; then
              sleep 10
              exit 1
            fi

            # Set up an ssh tunnel into the VM
            ssh ${{ env.vmHost }} -NL 3000:localhost:3000 & sleep 10

            # Verify we can login via the tunnel
            ssh -p 3000 root@localhost "uname -a"

      - name: Copy over BTF info
        run: |
          # Copy over BTF file if one exists
          BTF_FILE="/home/fgs/btf/${{ matrix.kernel }}"
          cat <<-EOF | ssh ${{ env.vmHost }}
            if [ -f "$BTF_FILE" ]; then
              echo "Copying over $BTF_FILE"
              ssh -p 3000 root@localhost "mkdir -p /fgs/bpf/objs"
              scp -P 3000 "$BTF_FILE" root@localhost:/fgs/bpf/objs/btf
            fi
          EOF

      - name: Run unit tests
        timeout-minutes: 30
        run: |
          cat <<-EOF | ssh -p 3000 root@localhost
            set -e

            cd /fgs
            export PATH="$PATH:/usr/local/go/bin"

            make hubble-bpf tester-progs test
          EOF

      - name: Wait for kube-system pods to be ready
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          command: |
            ssh -p 3000 root@localhost "kubectl wait -n kube-system --for=condition=Ready pods --all --timeout=45s"

      - name: Attempt to pull the FGS image
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 30
          retry_wait_seconds: 30
          command: |
            docker pull ${{ steps.vars.outputs.fgsImage }}

      - name: Preload FGS image
        run: |
          # Check if the image is already loaded and, if so, break out early
          if [[ "$(ssh -p 3000 root@localhost 'docker images -q ${{ steps.vars.outputs.fgsImage }}')" != "" ]]; then
            exit 0
          fi
          docker save ${{ steps.vars.outputs.fgsImage }} | bzip2 | ssh -p 3000 root@localhost "docker load"

      - name: Install FGS
        run: |
          cat <<-EOF | ssh -p 3000 root@localhost
            if [ -f "/fgs/bpf/objs/btf" ]; then
              echo "Installing FGS with BTF info..."
              /fgs/contrib/end-to-end/install-fgs.sh --image ${{ steps.vars.outputs.fgsImage }} --btf /fgs/bpf/objs/btf
            else
              echo "Installing FGS without BTF info..."
              /fgs/contrib/end-to-end/install-fgs.sh --image ${{ steps.vars.outputs.fgsImage }}
            fi
          EOF

      - name: Wait for FGS pods to become ready
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 10
          command: |
            ssh -p 3000 root@localhost "kubectl rollout status -n kube-system ds/hubble-enterprise --timeout=30s"

      - name: Run HTTP and TLS tests
        timeout-minutes: 15
        run: |
          ssh -p 3000 root@localhost "kubectl get pods -A"
          ssh -p 3000 root@localhost "/fgs/contrib/end-to-end/tests/http-tls.sh"

      - name: Run demo app tests
        timeout-minutes: 15
        run: |
          ssh -p 3000 root@localhost "kubectl get pods -A"
          ssh -p 3000 root@localhost "/fgs/contrib/end-to-end/tests/demo-app.sh"

      - name: Copy out FGS logs
        if: ${{ failure() || cancelled() }}
        timeout-minutes: 15
        run: |
          # Dump the end-to-end logs
          ssh -p 3000 root@localhost "/fgs/contrib/end-to-end/dump-fgs-logs.sh" || true

          # Make output dirs for logs
          mkdir -p logs/unit-tests
          mkdir -p logs/end-to-end

          # Copy logs over
          scp -P 3000 'root@localhost:/fgs/contrib/end-to-end/logs/*' logs/end-to-end || true
          scp -P 3000 'root@localhost:/tmp/*.yaml' logs/unit-tests || true
          scp -P 3000 'root@localhost:/tmp/*.json' logs/unit-tests || true
          scp -P 3000 'root@localhost:/tmp/*bugtool*' logs/unit-tests || true

      # This step is necessary since kube-system pods won't ever become ready on 4.19 if
      # BTF info isn't available, meaning we would get stuck on the "Wait for kube-system
      # pods to be ready" step otherwise.
      - name: Remove FGS
        timeout-minutes: 5
        run: |
          ssh -p 3000 root@localhost "helm uninstall hubble-enterprise --namespace kube-system"
          ssh -p 3000 root@localhost "rm -f /fgs/bpf/objs/btf"

      - name: Shut off KVM
        timeout-minutes: 5
        run: |
          ssh ${{ env.vmHost }} "hubble-fgs/contrib/kvm/stop.sh"
          sleep 10

      - name: Upload end-to-end test logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: fgs-end-to-end-tests-${{ matrix.kernel }}
          path: logs/end-to-end
          retention-days: 5

      - name: Upload unit test logs
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: fgs-unit-tests-${{ matrix.kernel }}
          path: logs/unit-tests
          retention-days: 5

  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [run-tests]
    if: always()
    steps:
      - name: Authenticate with gcloud
        uses: 'google-github-actions/auth@v0'
        with:
          project_id: ${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}
          credentials_json: '${{ secrets.CILIUM_PR_GCP_SA_KEY }}'
          create_credentials_file: true

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.CILIUM_PR_GCP_PROJECT_ID }}

      - name: Destroy VM
        if: ${{ always() }}
        run: |
          gcloud compute instances delete ${{ env.vmName }} --quiet --zone ${{ env.zone }}

      - name: Force job to fail if run-tests failed
        if: "needs.run-tests.outputs.job_status!='success'"
        run: |
          echo "Some tests failed, forcing cleanup job to fail to that it will be re-run when running failed jobs"
          exit 1
