name: Push to Loki

on:
  workflow_run:
    workflows:
      - "Image CI Build"
      - "Image CI Latest"
      - "Image CI Releases"
      - "Image CI Stable Branches"
      - "Validate that generated files are up to date"
      - "ConformanceGKE"
      - "HubbleFGS Go Test"
      - "Nightly BPF regression test"
      - "KVM e2e Tests"
      - "KVM Go Tests"
      - "Run static checks"
    types:
      - completed

permissions:
  actions: read

jobs:
  push-to-loki:
    runs-on: ubuntu-latest
    steps:
      - name: Push to Loki
        uses: michi-covalent/push-to-loki@d23647451078d19828deaa27a45e83437fd4a17c # v0.2.2
        with:
          endpoint: https://logs-prod3.grafana.net/loki/api/v1/push
          username: ${{ secrets.LOKI_USERNAME }}
          password: ${{ secrets.LOKI_PASSWORD }}
