name: Build and Publish OLM catalog

on:
  push:
    branches:
      - master
    paths:
      - 'install/olm/catalog/index.yaml'

env:
  ARTIFACTORY_ORGANIZATION_PROD: ${{ vars.ARTIFACTORY_ORGANIZATION_PROD || 'isovalent-iep-docker' }}

jobs:
  build-and-push-catalog:
    name: Build and push OLM catalog to ${{ vars.ARTIFACTORY_HOST }}
    runs-on: ubuntu-26.04
    permissions:
      contents: read
    steps:
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Login to Artifactory
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ vars.ARTIFACTORY_HOST }}
          username: ${{ vars.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      
      - name: Checkout Source Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Build and push
        shell: bash
        run: |
          IMAGE_REPOSITORY="${{ vars.ARTIFACTORY_HOST }}/${ARTIFACTORY_ORGANIZATION_PROD}" make olm-index-build olm-index-push
