name: Build and Publish OLM catalog

on:
  push:
    branches:
      - master
    paths:
      - 'install/olm/catalog/index.yaml'

jobs:
  build-and-push-catalog:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Login to quay.io
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      
      - name: Checkout Source Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Build and push
        shell: bash
        run: |
          make olm-index-build olm-index-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
