name: Push Docker Image
on:
  push:
    branches:
    - master
    - v*
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push the Docker image
      run: |
        IMAGE=quay.io/isovalent/hubble-enterprise
        docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }}

        # GITHUB_REF is set to "refs/heads/$branch" for branches and "refs/tags/$tag" for tags.
        VERSION=$(basename "$GITHUB_REF")
        docker build -t "$IMAGE":"$VERSION" .
        docker push "$IMAGE":"$VERSION"

        if [ "$(dirname $GITHUB_REF)" == "refs/heads" ]; then
          # This is a push to a branch. Also create a "$branch-$sha" image tag.
          SHA=$(git rev-parse --short HEAD)
          docker tag "$IMAGE":"$VERSION" "$IMAGE":"$VERSION"-"$SHA"
          docker push "$IMAGE":"$VERSION"-"$SHA"
        fi
        if [ "$(dirname $GITHUB_REF)" == "refs/heads/master" ]; then
          # This is a push to master. Also create a "latest" image tag.
          SHA=$(git rev-parse --short HEAD)
          docker tag "$IMAGE":"$VERSION" "$IMAGE":latest
          docker push "$IMAGE":latest
        fi
