name: Tarball Tests

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "contrib/grafana/**"

concurrency:
  group: ${{ github.ref }}-tarball-tests
  cancel-in-progress: true

jobs:
  build-tarballs:
    uses: ./.github/workflows/build-tarballs.yml
    permissions:
      contents: read
    secrets: inherit

  build-policytest-assets:
    uses: ./.github/workflows/build-policytest-assets.yml
    permissions:
      contents: read

  packages-e2e-tests:
    needs: [build-tarballs]
    uses: ./.github/workflows/packages-e2e-tests.yml
    permissions:
      contents: read

  vmpolicytests-ee:
    name: policy tests ee tarball
    needs: [build-tarballs, build-policytest-assets]
    uses: ./.github/workflows/policytests.yml
    permissions:
      contents: read
    with:
      artifact: tetragon-tarball
      amd64_runner_label: ${{ vars.KVM_GH_RUNNER_AMD64 }}
      arm64_runner_label: ${{ vars.KVM_GH_RUNNER_ARM64 }}

  vmpolicytests-slim:
    name: policy tests slim tarball
    needs: [build-tarballs, build-policytest-assets]
    uses: ./.github/workflows/policytests.yml
    permissions:
      contents: read
    with:
      artifact: tetragon-slim-tarball
      amd64_runner_label: ${{ vars.KVM_GH_RUNNER_AMD64 }}
      arm64_runner_label: ${{ vars.KVM_GH_RUNNER_ARM64 }}

  post-test:
    name: Cleanup
    runs-on: ubuntu-26.04
    needs: [packages-e2e-tests, vmpolicytests-ee, vmpolicytests-slim]
    if: ${{ needs.packages-e2e-tests.result == 'success' && needs.vmpolicytests.result == 'success' }}
    permissions:
      actions: write
    steps:
      - uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
        with:
          failOnError: false
          name: |
            tetragon-tarball-amd64
            tetragon-tarball-arm64
            tetragon-slim-tarball-amd64
            tetragon-slim-tarball-arm64
            policytest-assets-amd64
            policytest-assets-arm64
