name: Run veristat compare
on:
  pull_request:
    paths:
      - 'bpf/**'
      - '.github/actions/veristat/**'

jobs:
  veristat-compare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: branch
          submodules: true

      - name: Checkout base ref
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: base
          submodules: true
          ref: ${{ github.base_ref }}

      - name: Build BPF programs
        run: |
          make -C branch tetragon-bpf
          make -C base tetragon-bpf

      - name: Run veristat comparison
        uses: ./branch/.github/actions/veristat
        with:
          compare: true
          baseline-programs: "base/bpf/objs/*.o"
          comparison-programs: "branch/bpf/objs/*.o"
