name: Run veristat
on:
  push:
    branches:
      - main
      - v*
    paths:
      - 'bpf/**'
      - '.github/actions/veristat/**'
  pull_request:
    paths:
      - 'bpf/**'
      - '.github/actions/veristat/**'

jobs:
  veristat:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - name: Build BPF programs
        run: make tetragon-bpf

      - name: Run veristat
        uses: ./.github/actions/veristat
        with:
          programs: "bpf/objs/*.o"
